src/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <label>Competitor</label>
    <nameField>
        <displayFormat>Com-{0000}</displayFormat>
        <label>Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Competitor__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitors</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Raw</businessProcess>
        <label>Outbound</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/VOC_Accounts__c/VOC_Accounts__c.object-meta.xml
<CustomObject>
    <label>VOC Account</label>
    <nameField>
        <label>VOC Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VOC Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Voice_of_Customer__c/Voice_of_Customer__c.object-meta.xml
<CustomObject>
    <label>VOC</label>
    <nameField>
        <displayFormat>VOC-{0000}</displayFormat>
        <label>Voice of Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOC Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Voice_of_Customer__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Competitive Information?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Name__c</fullName>
    <formula>CreatedBy.FirstName+&apos; &apos;+CreatedBy.LastName</formula>
    <label>Created By Name</label>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Date_of_VOC__c.field-meta.xml
<CustomField>
    <fullName>Date_of_VOC__c</fullName>
    <description>Its a Date of VOC</description>
    <label>Date of VOC</label>
    <type>Date</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <label>Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Reviewed - No Action Taken</fullName>
            </value>
            <value>
                <fullName>Reviewed - Action Taken</fullName>
            </value>
            <value>
                <fullName>Reviewed - Action Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Enddate__c.field-meta.xml
<CustomField>
    <fullName>Enddate__c</fullName>
    <label>Enddate</label>
    <type>Date</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Honeywell__c.field-meta.xml
<CustomField>
    <fullName>Honeywell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Honeywell Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Voice_of_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Key_Action_Items__c.field-meta.xml
<CustomField>
    <fullName>Key_Action_Items__c</fullName>
    <label>Key Action Items</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Key_Takeaways1__c.field-meta.xml
<CustomField>
    <fullName>Key_Takeaways1__c</fullName>
    <label>Key Takeaways</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <label>OEM</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Boeing</fullName>
            </value>
            <value>
                <fullName>Bombardier</fullName>
            </value>
            <value>
                <fullName>Cessna</fullName>
            </value>
            <value>
                <fullName>China OEM</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>Defense Aftermarket Americas</fullName>
            </value>
            <value>
                <fullName>Defense Boeing</fullName>
            </value>
            <value>
                <fullName>Defense International</fullName>
            </value>
            <value>
                <fullName>Defense OEM and Partners  Americas</fullName>
            </value>
            <value>
                <fullName>Embraer</fullName>
            </value>
            <value>
                <fullName>Federal Manufacturing and technologies</fullName>
            </value>
            <value>
                <fullName>Gulfstream</fullName>
            </value>
            <value>
                <fullName>HON  Technology Solutions Inc</fullName>
            </value>
            <value>
                <fullName>LM NG GA</fullName>
            </value>
            <value>
                <fullName>Missiles &amp; Munitions</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other - AT&amp;R</fullName>
            </value>
            <value>
                <fullName>Other - BGA</fullName>
            </value>
            <value>
                <fullName>Pan-Aero</fullName>
            </value>
            <value>
                <fullName>Pilatus</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Other- D&amp;S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Other_Hoenywell_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Other_Hoenywell_Attendees__c</fullName>
    <description>Its VOC Honeywell Attendees</description>
    <label>Other Honeywell Attendees</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Platform</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipName>Voice_of_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Services</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Crew Interface</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Lighting</fullName>
            </value>
            <value>
                <fullName>Mechanical Components</fullName>
            </value>
            <value>
                <fullName>Mechanical Subsystems</fullName>
            </value>
            <value>
                <fullName>Navigation Systems &amp; Sensors</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Platform Systems</fullName>
            </value>
            <value>
                <fullName>Propulsion</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Info Mgmt</fullName>
            </value>
            <value>
                <fullName>Wheels &amp; Brakes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT&amp;R</fullName>
            </value>
            <value>
                <fullName>B&amp;GA</fullName>
            </value>
            <value>
                <fullName>Commercial(AT&amp;R &amp; B&amp;GA)</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pan-Aero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>NOTE: When “Sensitive Information” is selected, VOC information is available to key CBT members only</inlineHelpText>
    <label>Sensitive Information?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Its a VOC source</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>FBO</fullName>
            </value>
            <value>
                <fullName>FSDO</fullName>
            </value>
            <value>
                <fullName>Government Official</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/StartDateval__c.field-meta.xml
<CustomField>
    <fullName>StartDateval__c</fullName>
    <label>StartDateval</label>
    <type>Date</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Its a VOC Name of Title</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC_Account__c.field-meta.xml
<CustomField>
    <fullName>VOC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VOC Account</label>
    <referenceTo>VOC_Accounts__c</referenceTo>
    <relationshipName>Voice_of_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC_Link__c.field-meta.xml
<CustomField>
    <fullName>VOC_Link__c</fullName>
    <formula>HYPERLINK( LEFT( $Api.Enterprise_Server_URL_25 , FIND(&apos;/&apos;, $Api.Enterprise_Server_URL_25, 9) ) + Id, Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VOC Link</label>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC_Type__c.field-meta.xml
<CustomField>
    <fullName>VOC_Type__c</fullName>
    <description>Its VOC type</description>
    <label>VOC Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anecdotal</fullName>
            </value>
            <value>
                <fullName>Observational</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/VOCSearchDesktop.cls
public with sharing class VOCSearchDesktop {
    public String Keywords{get;set;}
    public boolean showresult{get;set;}
    public Voice_of_Customer__c SearchRecord{get;set;}
    public List<Voice_of_Customer__c> objCuslist  {get;set;}
    public List<Voice_of_Customer__c> objCuslist1  {get;set;}
    
    public VOCSearchDesktop(ApexPages.StandardController controller) 
    {
        if(SearchRecord==null)
            SearchRecord=new Voice_of_Customer__c();
    }
    
    public List<SelectOption> getoem()
    {
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult =  Voice_of_Customer__c.OEM__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
       options.add(new selectoption('','--None--')) ;     
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
    }
    
    
   public pagereference searchform()
    {
        system.debug('test methode');
        String strQuery = '';
        
       
        
        List<string> resultstring=new List<string>();
        DateTime stdt = SearchRecord.StartDateval__c;
        DateTime eddt =SearchRecord.EndDate__c;
        system.debug('WWWWWWWWWWWWWWWWWW'+SearchRecord.StartDateval__c);
        system.debug('xxxxxxxxxxxxxxxxxx'+SearchRecord.EndDate__c );
        TimeZone tz1 = UserInfo.getTimeZone();
        string tz=string.valueof(tz1);
        string ed= String.valueOf(SearchRecord.EndDate__c);
        string sd= String.valueOf(SearchRecord.StartDateval__c);
       
        
        system.debug('StartDate*************'+sd); 
        system.debug('EndDate**************'+ed);    
      
        
        String strCondition = '';
        if (SearchRecord.Sensitive__c!= true)
        strCondition +='(Sensitive__c=false or Sensitive__c=true)';
        if (SearchRecord.Sensitive__c== true)
        strCondition +='(Sensitive__c=true)';
        if (SearchRecord.Competitor__c!= true)
        strCondition +=' and (Competitor__c=false or Competitor__c=true)';
        if (SearchRecord.Competitor__c== true)
        strCondition +=' and (Competitor__c=true)';
        if (SearchRecord.StartDateval__c!= null && SearchRecord.EndDate__c== null)
        strCondition += ' and  Date_of_VOC__c >='+ sd;
        
        if (SearchRecord.StartDateval__c== null && SearchRecord.EndDate__c!= null)
       strCondition += ' and  Date_of_VOC__c <='+ ed;
         
        if (SearchRecord.StartDateval__c!= null && SearchRecord.EndDate__c!= null)
       strCondition += ' and  (Date_of_VOC__c >='+sd+ ' and ' + 'Date_of_VOC__c <='+ed+ ')';
       
       if (SearchRecord.Disposition__c != null && strCondition == '')
        strCondition += 'Disposition__c =\''+ SearchRecord.Disposition__c+ '\'';
        else if (SearchRecord.Disposition__c != null && strCondition != '')
        strCondition += ' and  Disposition__c = \''+ SearchRecord.Disposition__c + '\'';

        if (SearchRecord.VOC_Type__c != null && strCondition == '')
        strCondition += 'VOC_Type__c =\''+ SearchRecord.VOC_Type__c+ '\'';
        else if (SearchRecord.VOC_Type__c != null && strCondition != '')
        strCondition += ' and  VOC_Type__c = \''+ SearchRecord.VOC_Type__c + '\'';

        if (SearchRecord.Source__c != null && strCondition == '')
        strCondition += 'Source__c =\''+ SearchRecord.Source__c+ '\'';
        else if (SearchRecord.Source__c != null && strCondition != '')
        strCondition += ' and  Source__c =\''+ SearchRecord.Source__c+ '\'';

        if (SearchRecord.Honeywell__c != null && strCondition == '')
        {
        strCondition += 'createdById  =\''+ SearchRecord.Honeywell__c+ '\'';
        system.debug('check honeywell lead'+strCondition);
        }
        else if (SearchRecord.Honeywell__c != null && strCondition != '')
        {
        strCondition += ' and  createdById   =\''+ SearchRecord.Honeywell__c+ '\'';
        system.debug('check honeywell lead'+strCondition);
        }

        //checking account 
        if (SearchRecord.VOC_Account__c != null && strCondition == '')
        strCondition += 'VOC_Account__c=\''+ SearchRecord.VOC_Account__c+ '\'';
        else if (SearchRecord.VOC_Account__c!= null && strCondition != '')
        strCondition += ' and  VOC_Account__c=\''+ SearchRecord.VOC_Account__c+ '\'';


        if (SearchRecord.SBU__c!= null && strCondition == '')
        strCondition += 'SBU__c=\''+ SearchRecord.SBU__c+ '\'';
        else if (SearchRecord.SBU__c!= null && strCondition != '')
        strCondition += ' and SBU__c=\''+ SearchRecord.SBU__c+ '\'';

      /**  if(SearchRecord.OEM__c!= null && strCondition == '')
        {
            system.debug('test oem result'+SearchRecord.OEM__c);
            String strProd1 = SearchRecord.OEM__c;
            strProd1  = strProd1.replace('[','');
            strProd1  = strProd1.replace(']','');
            strProd1  = strProd1.replace(',','\',\'');
            system.debug('test result of OEM'+strProd1  );
            strCondition += strProd1; 
        }**/
        
        if (SearchRecord.OEM__c!= null && strCondition == '')
        {
            system.debug('test oem result'+SearchRecord.OEM__c);
            String strProd1 = SearchRecord.OEM__c;
            strProd1  = strProd1.replace('[','');
            strProd1  = strProd1.replace(']','');
            strProd1  = strProd1.replace(',','\',\'');
            system.debug('test result of OEM'+strProd1  );
            if(strProd1.trim() != null && strProd1.trim() != '')
            strCondition += 'OEM__c in (\''+ strProd1+ '\')';
        }
        else if (SearchRecord.OEM__c!= null && strCondition != '')
        {
            system.debug('test oem result'+SearchRecord.OEM__c);
            String strProd1 = SearchRecord.OEM__c;
            strProd1  = strProd1.replace('[','');
            strProd1  = strProd1.replace(']','');
            strProd1  = strProd1.replace(',','\',\'');
            system.debug('test result of OEM'+strProd1  );
            if(strProd1.trim() != null && strProd1.trim() != '')
            strCondition += ' and OEM__c in (\''+ strProd1+ '\')';
        }

        if(SearchRecord.Product_Family__c!= null && strCondition == '')
        {
            system.debug('test result'+SearchRecord.Product_Family__c);
            String strProd = SearchRecord.Product_Family__c;
            strProd  = strProd.replace('[','');
            strProd  = strProd.replace(']','');
            strProd  = strProd.replace(',','\',\'');
            system.debug('test result strProd'+strProd);
            if(strProd.trim() != null && strProd.trim() != '')
            strCondition += ' Product_Family__c in (\''+ strProd + '\')';
        }
        else if (SearchRecord.Product_Family__c!= null && strCondition != '')
        {
            system.debug('test result'+SearchRecord.Product_Family__c);
            String strProd = SearchRecord.Product_Family__c;
            strProd  = strProd.replace('[','');
            strProd  = strProd.replace(']','');
            strProd  = strProd.replace(',','\',\'');
            system.debug('test result strProd'+strProd);
            if(strProd.trim() != null && strProd.trim() != '')
            strCondition += ' and Product_Family__c in (\''+ strProd + '\')';
        }
      
        if (SearchRecord.Platform__c!= null && strCondition == '')
        strCondition += 'Platform__c=\''+ SearchRecord.Platform__c+ '\'';
        else if (SearchRecord.Platform__c!= null && strCondition != '')
        strCondition += ' and  Platform__c=\''+ SearchRecord.Platform__c+ '\'';

       

        /*if (SearchRecord.Competitor__c!= null && strCondition == '')
        strCondition += 'Competitor__c='+ SearchRecord.Competitor__c;
        else if (SearchRecord.Competitor__c!= null && strCondition != '')
        strCondition += ' and  Competitor__c='+ SearchRecord.Competitor__c;*/

        if (SearchRecord.Other_Hoenywell_Attendees__c!= null && strCondition == '')
        strCondition += 'Other_Hoenywell_Attendees__c=\''+ SearchRecord.Other_Hoenywell_Attendees__c+ '\'';
        else if (SearchRecord.Other_Hoenywell_Attendees__c!= null && strCondition != '')
        strCondition += ' and Other_Hoenywell_Attendees__c=\''+ SearchRecord.Other_Hoenywell_Attendees__c+ '\'';

        System.debug('Strcondition----------'+strCondition );
        
        if(strCondition != Null)
        strQuery = 'SELECT Id,Title__c,Date_of_VOC__c,Product_Family__c,Platform__r.name,SBU__c,oem__c,VOC_Account__c,Voc_link__C ,name,Key_Takeaways1__c,VOC_Account__r.name,Key_Action_Items__c,Created_By_Name__c,createdByID,Owner.name from Voice_of_Customer__c where '+strCondition+' ORDER BY Date_of_VOC__c DESC, name DESC limit 500 ';
        else
        strQuery  = 'SELECT Id,Title__c,Date_of_VOC__c,name,Product_Family__c,Platform__r.name,SBU__c,oem__c,Voc_link__C ,VOC_Account__c,Key_Takeaways1__c,VOC_Account__r.name,Key_Action_Items__c,Created_By_Name__c,createdByID,Owner.name from Voice_of_Customer__c ORDER BY Date_of_VOC__c DESC, name DESC limit 500 ';

        System.debug('strQuery ------------->'+strQuery );
        objCuslist  = new List<Voice_of_Customer__c>();
        objCuslist  =  Database.Query(strQuery);
        system.debug('test objCuslist'+objCuslist);
        objCuslist1   = new List<Voice_of_Customer__c>();
        Voice_of_Customer__c objVOC ;
       /* System.debug( 'Keywords-------->'+Keywords);
        System.debug( 'Keywords-------->'+Keywords.indexOf('and')); 
        System.debug( 'Keywords-------->'+Keywords.indexOf('or')); 
        System.debug( 'Keywords-------->'+Keywords.indexOf('not')); **/
        List<String> arlKeywordsand = new List<String>();
        List<String> arlKeywordsor  = new List<String>();
        List<String> arlKeywordsnot = new List<String>();

        String strKeywd = '';
        //added this to check and or condition
         /** list<string>temp=new list<string>();
          string orstring='';
          string andstring='';
          temp=Keywords.split(' ', -2);
          
          for(string s:temp)
          {
            if(orstring!='')
              orstring=orstring+' or '+s;
            else
               orstring=s;
            if(andstring!='')
              andstring=andstring+' and '+s;
            else
               andstring=s;
              
          }
         if(orstring!='' && andstring!='')
         keywords='('+orstring+') or ('+andstring+')';
         system.debug('keywords***********'+keywords);**/
        for(Integer inCnt = 0;inCnt < objCuslist.Size(); inCnt ++ )
        {
            objVOC = objCuslist[inCnt];
            if((null != objVOC.Key_Takeaways1__c &&  objVOC.Key_Takeaways1__c.toLowercase().contains(Keywords.toLowercase())) 
                || (null != objVOC.Title__c &&  objVOC.Title__c.toLowercase().contains(Keywords.toLowercase()))
                || (objVOC.Name!=null && objVOC.name.toLowercase().contains(Keywords.toLowercase())) 
                || (objVOC.Key_Action_Items__c!=null && objVOC.Key_Action_Items__c.toLowercase().contains(Keywords.toLowercase()))
                || (objVOC.Created_By_Name__c!=null && objVOC.Created_By_Name__c.toLowercase().contains(Keywords.toLowercase()))
                || (objVOC.VOC_Account__c!=null && objVOC.VOC_Account__r.name.toLowercase().contains(Keywords.toLowercase()))
                || (objVOC.Platform__c!=null && objVOC.Platform__r.name.toLowercase().contains(Keywords.toLowercase()))
                || (objVOC.Product_Family__c!=null && objVOC.Product_Family__c.toLowercase().contains(Keywords.toLowercase()))
                || (objVOC.oem__c!=null && objVOC.oem__c.toLowercase().contains(Keywords.toLowercase())))
            {
                objCuslist1.add(objVOC);
            }
        }
        System.debug( 'objCuslist1-------->'+objCuslist1.size()); 
 
        objCuslist = objCuslist1;
        if(objCuslist.size()>0)
            showresult=true;
           
        return null;
    }
   public pageReference DetailPage()
   {
     String fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm();
     PageReference pageRef = new PageReference(fullRecordURL+'/'+apexpages.currentpage().getparameters().get('vocid'));
     return pageRef;
   }

}