src/objects/GDMFSL_Site_License__c/GDMFSL_Site_License__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store Site Licenses. It is used on Extended Match Rule to match a Location requiring a License and Resources who have a valid License.</description>
    <label>Site License</label>
    <nameField>
        <label>Site License Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDMFSL_Vertical__c/GDMFSL_Vertical__c.object-meta.xml
<CustomObject>
    <label>Environment Vertical</label>
    <nameField>
        <label>Vertical Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Verticals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location/fields/GDMFSL_Region__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Region__c</fullName>
    <description>Region field will be used for Sharing Rules, and derived from Shipping Account or Service Location.</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/objects/Location/fields/GDMFSL_Site_License__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Site_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identify License/Clearance required by the Location</description>
    <inlineHelpText>Identify License/Clearance required by the Location</inlineHelpText>
    <label>Site License</label>
    <referenceTo>GDMFSL_Site_License__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Location/fields/GDMFSL_Vertical__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Vertical__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment Vertical</label>
    <referenceTo>GDMFSL_Vertical__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Chargeable__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Chargeable__c</fullName>
    <label>Chargeable</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Disable_GeoTracking__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Disable_GeoTracking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable GeoTracking</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Extra_Travel__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Extra_Travel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Extra Travel</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Location__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Location</description>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Non_Reactive_Work__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Non_Reactive_Work__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-Reactive Work</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_OT_Labor_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_OT_Labor_in_minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OT Labor (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_OT_Travel_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_OT_Travel_in_minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OT Travel (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_PO_Required_for_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Required_for_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Number Required for Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_PT_Labor_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PT_Labor_in_minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PT Labor (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_PT_Travel_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PT_Travel_in_minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PT Travel (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Region__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Region__c</fullName>
    <description>This is getting derived from the parent work order</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Regular_Labor_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Regular_Labor_in_minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Regular Labor (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Regular_Travel_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Regular_Travel_in_minutes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Regular Travel (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>will be derived from WorkOrder.ServiceContractID upon creation of SA</description>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Site_License__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Site_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Required License for the Location of the SA</description>
    <inlineHelpText>Required License for the Location of the SA</inlineHelpText>
    <label>Site License</label>
    <referenceTo>GDMFSL_Site_License__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Sold_To_Source_System_Reference__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Sold_To_Source_System_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Source System Reference</label>
    <referenceTo>Source_System__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Vertical__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Vertical__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vertical</label>
    <referenceTo>GDMFSL_Vertical__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ServiceAppointment/fields/Work_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Number__c</fullName>
    <label>Work Order Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/ServiceContract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract/fields/GDMFSL_Region__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Region__c</fullName>
    <description>This Field will be populated with the Region from the Sold To Account, and used in Sharing Rules for SC.</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/objects/ServiceResource.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceResource/fields/GDMFSL_IsContractor__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_IsContractor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This tracks whether the Service Resource is a contractor or not</description>
    <label>Is Contractor</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceResource/fields/GDMFSL_Region__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Region__c</fullName>
    <formula>TEXT(RelatedRecord.Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

src/objects/ServiceTerritory/fields/GDMFSL_Maximum_SA_Duration_Hrs__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Maximum_SA_Duration_Hrs__c</fullName>
    <label>Maximum SA Duration (Hrs.)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceTerritory/fields/GDMFSL_Region__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/objects/WorkOrder.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder/fields/GDMFSL_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Arrival_Time__c</fullName>
    <label>Arrival Time</label>
    <type>DateTime</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Chargeable__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Chargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This value indicates if the Work Is chargeable and can be edited.</description>
    <label>Chargeable</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Created_by_WO_Merge_Process__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Created_by_WO_Merge_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created by WO Merge Process</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Executed_by_Sub_Contractor__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Executed_by_Sub_Contractor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Executed by Sub-Contractor</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Extra_Travel__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Extra_Travel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Extra Travel</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Non_Reactive_Work__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Non_Reactive_Work__c</fullName>
    <formula>ISPICKVAL(WorkType.GDMFSL_WorkType_Category__c,&apos;PM&apos;)
 ||  ISPICKVAL(WorkType.GDMFSL_WorkType_Category__c,&apos;Audit&apos;)
 ||  ISPICKVAL(WorkType.GDMFSL_WorkType_Category__c,&apos;Site Survey&apos;)
 ||  ISPICKVAL(WorkType.GDMFSL_WorkType_Category__c,&apos;Install&apos;)</formula>
    <label>Non-Reactive Work</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_PO_Required_for_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Required_for_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Number Required for Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Region__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Response_Time__c</fullName>
    <label>Response Time</label>
    <type>DateTime</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Sold_To_Source_System_Reference__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Sold_To_Source_System_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Source System Reference</label>
    <referenceTo>Source_System__c</referenceTo>
    <relationshipLabel>Work Orders (Sold To Source System Reference)</relationshipLabel>
    <relationshipName>Work_Orders_SoldTo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Americas</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Pacific Rim</fullName>
    </customValue>
    <customValue>
        <fullName>Europe/MiddleEast/Africa/India</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary</fullName>
    </customValue>
    <customValue>
        <fullName>Unassigned</fullName>
    </customValue>
    <customValue>
        <fullName>Unmapped</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/GDMFSL_ServiceAppointmentProcessor.cls
/*******************************************************************************************
Name       :    GDMFSL_ServiceAppointmentProcessor
Purpose    :    Business Logic for ServiceAppointment object . See method descriptions for proper context for calling each method
--------------------------------------------------------------------------
Developer               Date          Description
--------------------------------------------------------------------------
Udbhav                  2020-Sep-01    Created
**********************************************************************************************/

public without sharing class GDMFSL_ServiceAppointmentProcessor {


    public static final String CANCELLEDSTATUS = 'Canceled';
    public static final String UNSCHEDULEDSTATUS = 'None';
    public static final String COMPLETEDSTATUS = 'Completed';
    public static final String STATUSFORLOCSHARING = 'Dispatched';

    private static final String LOCATIONACCESSLEVEL = 'Read';

    public static final Set<String> STATUSFORCANCELLATION = new Set<String>{
            'None',
            'New',
            'Scheduled',
            'Dispatched',
            'Accepted',
            'Rejected'
    };

    public static final Set<String> CLOSEDSTATUSES = new Set<String>{
            'Closed',
            'Canceled',
            'Completed'
    };

    public static final Map<String, String> SASTATUSTOSTATUSCATEGORYMAP = new Map<String, String>{
            'Null' => 'None',
            'None' => 'None',
            'Scheduled' => 'Scheduled',
            'Dispatched' => 'Dispatched',
            'Accepted' => 'Dispatched',
            'Rejected' => 'Dispatched',
            'Travel' => 'InProgress',
            'Onsite' => 'InProgress',
            'Paused' => 'InProgress',
            'Follow Up Required' => 'InProgress',
            'Check Out' => 'InProgress',
            'Cannot Complete' => 'Cannot Complete',
            COMPLETEDSTATUS => 'Completed',
            CANCELLEDSTATUS => CANCELLEDSTATUS
    };

    private static final Set<String> STATUSFORUPDATES = new Set<String>{
            'None',
            'Scheduled'
    };

    public static final Set<String> STATUSFORUNSCHEDULING = new Set<String>{
            'Scheduled',
            'Dispatched',
            'Accepted'
    };

    //Service Appointment Fields ==> Work Order Fields mapping
    // make sure to add the WO fields to  GDMFSL_WorkOrderProcessor.getRecords()
    private static final Map<String, String> SERVAPPFIELDSTOWOMAP = new Map<String, String>{
            'ServiceTerritoryId' => 'ServiceTerritoryId',
            'EarliestStartTime' => 'StartDate',
            'DueDate' => 'EndDate',
            'ArrivalWindowEndTime' => 'GDMFSL_Arrival_Time__c',
            'ArrivalWindowStartTime' => 'GDMFSL_Response_Time__c',
            'GDMFSL_Extra_Travel__c' => 'GDMFSL_Extra_Travel__c',
            'GDMFSL_Service_Contract__c' => 'ServiceContractId',
            'GDMFSL_PO_Number__c' => 'GDMFSL_PO_Number__c',
            'GDMFSL_PO_Required_for_Reactive_Coverage__c' => 'GDMFSL_PO_Required_for_Reactive_Coverage__c',
            'GDMFSL_Location__c' => 'LocationId',
            'GDMFSL_Sold_To_Source_System_Reference__c' => 'GDMFSL_Sold_To_Source_System_Reference__c',
            'GDMFSL_Non_Reactive_Work__c' => 'GDMFSL_Non_Reactive_Work__c',
            'Work_Order_Number__c' => 'WorkOrderNumber',
            'GDMFSL_Region__c' => 'GDMFSL_Region__c'

    };

    /**
     * method to set Fields from WO to SA
     *
     * @param lstSA List of Service Appointment Passed
     **/
    public static void setSAFieldsFromWO(List<ServiceAppointment> lstSA) {

        Map<Id, List<ServiceAppointment>> woIDtoSAs = generateMapWOIdToSA(lstSA);

        setSAFieldsFromWO(woIDtoSAs, null);
    }


    /**
     * method to set Fields from WO to SA
     *
     * @param parentIDToSAs List of Service Appointment Passed
     * @param newWOMap workOrder map with Id and WorkOrder Object
     * @param oldWOMap WorkOrder Old Map passed from WorkOrder Processor
     *
     * @return Map of Id and List of Service Appointments
     **/
    public static Map<Id, List<ServiceAppointment>> setSAFieldsFromWO(Map<Id, List<ServiceAppointment>> parentIDToSAs, Map<Id, WorkOrder> newWOMap) {

        if (GDMFSL_CommonUtilities.isFlagSet('setSAFieldsFromWO')) {
            return parentIDToSAs;
        }

        GDMFSL_CommonUtilities.setFlag('setSAFieldsFromWO');

        Map<Id, WorkOrder> woInfo = newWOMap;

        Boolean calledFromWOTrigger = (newWOMap != null);
        System.debug('setSAFieldsFromWO() called from WO trigger: ' + calledFromWOTrigger);

        if (!calledFromWOTrigger) {
            System.debug('No WorkOrders passed to setSAFieldsFromWO() need to get WOs');
            woInfo = fetchSARelatedWO(parentIDToSAs);
        }

        System.debug('working with WOs: ' + woInfo.size());

        Map<Id, Schema.Location> locationMap = new Map<Id, Schema.Location>();

        if (calledFromWOTrigger && woInfo != null && !woInfo.isEmpty()) {
            System.debug('Called from WO trigger so we need to go get WO related records (Location)');
            Set<Id> locationIds = new Set<Id>();

            for (WorkOrder wo : woInfo.values()) {
                if (wo.LocationId != null) {
                    locationIds.add(wo.LocationId);
                }
            }

            if (!locationIds.isEmpty()) {
                locationMap = GDMFSL_LocationProcessor.getRecords(locationIds);
                System.debug('Locations fetched: ' + locationMap);
            }
        }

        for (WorkOrder theWO : woInfo.values()) {

            System.debug('WO ID: ' + theWO.Id);
            System.debug('WO Duration: ' + theWO.Duration);
            System.debug('WO Location: ' + theWO.LocationId);

            System.debug('has this many SAs: ' + (parentIDToSAs.containsKey(theWO.Id) ? parentIDToSAs.get(theWO.Id).size() : 0));

            if (parentIDToSAs.containsKey(theWO.Id)) {

                for (ServiceAppointment sa : parentIDToSAs.get(theWO.Id)) {

                    if (Trigger.isExecuting && Trigger.operationType == TriggerOperation.BEFORE_INSERT) {
                        System.debug('Set SA Disable GeoTracking field from the WO.ServiceTerritory');
                        sa.GDMFSL_Disable_GeoTracking__c = theWO.ServiceTerritory.GDMFSL_Disable_GeoTracking__c;
                    }

                    System.debug('Service Appointment Status: ' + sa.Status);

                    if (STATUSFORUPDATES.contains(sa.Status)) {

                        for (String saFieldName : SERVAPPFIELDSTOWOMAP.keySet()) {
                            System.debug('SA Field : Value ' + saFieldName + ' : ' + theWO.get(SERVAPPFIELDSTOWOMAP.get(saFieldName)));
                            sa.put(saFieldName, theWO.get(SERVAPPFIELDSTOWOMAP.get(saFieldName)));
                        }

                        System.debug('Deriving Chargeable field on SA from WO');
                        sa.GDMFSL_Chargeable__c = theWO.GDMFSL_Chargeable__c ? 'Yes' : 'No';
                        System.debug('SA Chargeable is now : ' + sa.GDMFSL_Chargeable__c);
                        if (!theWO.GDMFSL_Created_by_WO_Merge_Process__c && theWO.Duration != null
                                && (sa.Duration == null || !(sa.Duration > 0))) {
                            System.debug('Setting ServiceAppt Duration from WO');
                            sa.Duration = theWO.Duration;
                        }

                        System.debug('SA Duration is now: ' + sa.Duration);

                        if (theWO.LocationId != null && theWO.Location.GDMFSL_Vertical__c != null) {
                            System.debug('Setting SA Vertical from the WO: ' + theWO.Location.GDMFSL_Vertical__c);
                            sa.GDMFSL_Vertical__c = theWO.Location.GDMFSL_Vertical__c;
                        } else if (theWO.LocationId != null && locationMap != null && locationMap.containsKey(theWO.LocationId)) {
                            System.debug('Setting SA Vertical from the Location: ' + locationMap.get(theWO.LocationId).GDMFSL_Vertical__c);
                            sa.GDMFSL_Vertical__c = locationMap.get(theWO.LocationId).GDMFSL_Vertical__c;
                        }

                        System.debug('Vertical on SA is: ' + sa.GDMFSL_Vertical__c);


                        if (theWO.LocationId != null && theWO.Location.GDMFSL_Site_License__c != null) {
                            System.debug('Setting SA Site License from the WO: ' + theWO.Location.GDMFSL_Site_License__c);
                            sa.GDMFSL_Site_License__c = theWO.Location.GDMFSL_Site_License__c;
                        } else if (theWO.LocationId != null && locationMap != null && locationMap.containsKey(theWO.LocationId)) {
                            System.debug('Setting SA Site License from the Location: ' + locationMap.get(theWO.LocationId).GDMFSL_Site_License__c);
                            sa.GDMFSL_Site_License__c = locationMap.get(theWO.LocationId).GDMFSL_Site_License__c;
                        }

                        System.debug('Site License on SA is: ' + sa.GDMFSL_Site_License__c);
                    }
                }
            }
        }

        return parentIDToSAs;
    }


    /**
     * Retrieves ServiceAppointments from SF
     *
     * @param saIds the Set of SAppt Ids to retrieve
     *
     * @return a Map of Id to record
     */
    public static Map<Id, ServiceAppointment> getRecords(Set<Id> saIds) {

        Map<Id, ServiceAppointment> retVals = new Map<Id, ServiceAppointment>();

        for (ServiceAppointment sa : getRecords(saIds, ServiceAppointment.getSObjectType())) {
            retVals.put(sa.Id, sa);
        }

        System.debug('Retrieved ServiceAppointments: ' + retVals);
        return retVals;
    }

    public static Map<Id, Boolean> canSABeCanceled(Map<Id, WorkOrder> wOToCancel, String fieldAPIforReturnId) {
        Map<Id, Boolean> keyIdCanBeCanceled = new Map<Id, Boolean>();
        System.debug('fieldAPIforReturnId:' + fieldAPIforReturnId);
        System.debug('Setting all WO to Cancellable');
        for (Id woId : wOToCancel.keySet()) {
            if (fieldAPIforReturnId == null || fieldAPIforReturnId == 'ParentRecordId') {
                keyIdCanBeCanceled.put(woId, true);
            } else if (fieldAPIforReturnId == 'CaseId') {
                keyIdCanBeCanceled.put(wOToCancel.get(woId).CaseId, true);

            }
        }

        List<ServiceAppointment> theSAs = new List<ServiceAppointment>([
                SELECT Id, Status, ParentRecordId
                FROM ServiceAppointment
                WHERE Status NOT IN :CLOSEDSTATUSES
                AND ParentRecordId IN :wOToCancel.keySet()
        ]);

        List<ServiceAppointment> saToUpdate = new List<ServiceAppointment>();

        for (ServiceAppointment sa : theSAs) {

            System.debug('Looking at SA: ' + sa.Id);
            System.debug('SA Status: ' + sa.Status);

            if (STATUSFORCANCELLATION.contains(sa.Status)) {
                sa.Status = CANCELLEDSTATUS;
                saToUpdate.add(sa);
            } else {
                if (fieldAPIforReturnId == null || fieldAPIforReturnId == 'ParentRecordId') {
                    keyIdCanBeCanceled.put(sa.ParentRecordId, false);
                } else if (fieldAPIforReturnId == 'CaseId') {
                    System.debug('fieldAPIforReturnId = caseId');
                    System.debug('wOToCancel.get(sa.ParentRecordId).CaseId: ' + wOToCancel.get(sa.ParentRecordId).CaseId);
                    keyIdCanBeCanceled.put(wOToCancel.get(sa.ParentRecordId).CaseId, true);
                }
            }
        }

        System.debug('This many SAs to update: ' + saToUpdate.size());

        if (!saToUpdate.isEmpty()) {
            GDMFSL_CommonUtilities.updateRecords(saToUpdate);
        }

        return keyIdCanBeCanceled;
    }

    /**
     * Retrieves ServiceAppointments from WorkOrder
     *
     * @param workorderIds the Set of WorkOrder Ids to retrieve SA
     *
     * @return a List of SA
     */
    public static Map<Id, List<ServiceAppointment>> getRecordsForWOs(Set<Id> workorderIds) {
        Map<Id, List<ServiceAppointment>> woIdToSAs = new Map<Id, List<ServiceAppointment>>();

        for (ServiceAppointment sa : getRecords(workorderIds, WorkOrder.getSObjectType())) {

            if (!woIdToSAs.containsKey(sa.ParentRecordId)) {
                woIdToSAs.put(sa.ParentRecordId, new List<ServiceAppointment>());
            }
            woIdToSAs.get(sa.ParentRecordId).add(sa);
        }

        return woIdToSAs;
    }

    @TestVisible
    private static List<ServiceAppointment> getRecords(Set<Id> iDsToUse, SObjectType typeOfIds) {

        System.debug('ServiceAppointment getRecords() getting for ID type: ' + typeOfIds);

        String queryString = 'SELECT Id, AccountId, ParentRecordId, Status, DurationType, Duration, GDMFSL_Vertical__c, GDMFSL_Service_Contract__c,' +
                'GDMFSL_OT_Labor_in_minutes__c,GDMFSL_PT_Labor_in_minutes__c,GDMFSL_Regular_Labor_in_minutes__c,' +
                'GDMFSL_OT_Travel_in_minutes__c,GDMFSL_PT_Travel_in_minutes__c,GDMFSL_Regular_Travel_in_minutes__c ';
        queryString += ' FROM ServiceAppointment ';

        if (typeOfIds == null || typeOfIds == ServiceAppointment.getSObjectType()) {
            queryString += ' WHERE Id ';
        } else if (typeOfIds == WorkOrder.getSObjectType()) {
            queryString += ' WHERE ParentRecordId ';
        } else if (typeOfIds == ServiceContract.getSObjectType()) {
            queryString += ' WHERE GDMFSL_Service_Contract__c ';
        } else if (typeOfIds == Account.getSObjectType()) {
            queryString += ' WHERE AccountId ';
        }

        queryString += ' IN :iDsToUse';

        System.debug('SA getRecords query: ' + queryString);
        List<ServiceAppointment> saList = Database.query(queryString);

        return saList;
    }


    /**
     * Update ServiceAppointments from WorkOrder
     *
     * @param newWOMap
     * @param oldWOMap
     */
    public static void updateSAFieldsfromWO(Map<Id, WorkOrder> newWOMap) {
        System.debug('updateSAFieldsfromWO()');

        if (newWOMap != null && !newWOMap.isEmpty()) {

            Map<Id, List<ServiceAppointment>> theWOIdToSAs = getRecordsForWOs(newWOMap.keySet());

            System.debug('Fetched Service Appointments: ' + theWOIdToSAs);

            Map<Id, List<ServiceAppointment>> woIDToSAs = setSAFieldsFromWO(theWOIdToSAs, newWOMap);

            List<ServiceAppointment> sasToUpdate = new List<ServiceAppointment>();

            for (List<ServiceAppointment> saList : woIDToSAs.values()) {
                System.debug('Adding ServiceAppts to list for update: ' + saList);
                sasToUpdate.addAll(saList);
            }

            if (!sasToUpdate.isEmpty()) {
                GDMFSL_CommonUtilities.updateRecords(sasToUpdate);
            }
        }
    }

    /**
     * Update related Objects after SA is Completed
     *
     * @param theSAs list of SA's
     */
    public static void processCompletedSAs(List<ServiceAppointment> theSAs) {

        System.debug('Inside GDMFSL_ServiceAppointmentProcessor.processCompletedSAs()');

        Map<Id, ServiceAppointment> completedAppointments = new Map<Id, ServiceAppointment>();

        for (ServiceAppointment sa : theSAs) {
            if (sa.Status == COMPLETEDSTATUS
                    && sa.ParentRecordId != null
                    && sa.ParentRecordId.getSobjectType() == WorkOrder.getSObjectType()) {

                completedAppointments.put(sa.Id, sa);
            }
        }

        System.debug('Total number of Completed SAs: ' + completedAppointments.size());

        if (!completedAppointments.isEmpty()) {

            Map<Id, List<ServiceAppointment>> woIDtoSAs = generateMapWOIdToSA(completedAppointments.values());

            Map<Id, WorkOrder> workOrderMap = fetchSARelatedWO(woIDtoSAs);

            Map<Id, List<AssignedResource>> mapSAtoASR = GDMFSL_AssignedResourceProcessor.getAssignedResByServiceAppointmentId(completedAppointments.keySet());

            Set<WorkOrder> workOrdersToUpdate = new Set<WorkOrder>();
            Map<Id, ServiceContract> sContractsToUpdate = new Map<Id, ServiceContract>();

            for (ServiceAppointment sa : completedAppointments.values()) {

                System.debug('Checking SA: ' + sa.Id);

                if (mapSAtoASR.containsKey(sa.Id)) {

                    System.debug('Checking Assigned Resources');
                    for (AssignedResource r : mapSAtoASR.get(sa.Id)) {

                        if (r.ServiceResource.GDMFSL_IsContractor__c) {

                            for (WorkOrder wo : workOrderMap.values()) {

                                if (!wo.GDMFSL_Executed_by_Sub_Contractor__c) {
                                    wo.GDMFSL_Executed_by_Sub_Contractor__c = true;
                                    workOrdersToUpdate.add(wo);
                                }
                            }
                        }
                    }
                }
            }

            System.debug('Service Contracts to be Updated: ' + sContractsToUpdate.size());
            if (!sContractsToUpdate.isEmpty()) {
                GDMFSL_CommonUtilities.updateRecords(sContractsToUpdate.values());
            }

            System.debug('Work Orders to be Updated: ' + workOrdersToUpdate.size());
            if (!workOrdersToUpdate.isEmpty()) {
                List<WorkOrder> woToUpdate = new List<WorkOrder>();
                woToUpdate.addAll(workOrdersToUpdate);
                GDMFSL_CommonUtilities.updateRecords(woToUpdate);
            }
        }

    }

    /**
     * Generate Map of WorkOrder Id and related List of SA
     *
     * @param lstSA list of Service Appointments to generate Map
     *
     * @return Map of WorkOrder Id and List of ServiceAppointments
     */
    private static Map<Id, List<ServiceAppointment>> generateMapWOIdToSA(List<ServiceAppointment> lstSA) {

        Map<Id, List<ServiceAppointment>> woIDtoSAs = new Map<Id, List<ServiceAppointment>>();

        if (lstSA != null) {
            for (ServiceAppointment sa : lstSA) {
                if (sa.ParentRecordId != null && WorkOrder.SObjectType == sa.ParentRecordId.getSobjectType()) {

                    if (!woIDtoSAs.containsKey(sa.ParentRecordId)) {
                        woIDtoSAs.put(sa.ParentRecordId, new List<ServiceAppointment>());
                    }

                    woIDtoSAs.get(sa.ParentRecordId).add(sa);
                }
            }
        }

        return woIDtoSAs;
    }

    /**
     * Generate Map of WorkOrder Id and WorkOrder passing the list of Service Appointments and ParentId Map
     *
     * @param parentIDToSAs Map of ParentRecordId and List of related SAs
     *
     * @return Map of WorkOrder Id and  WorkOrder
     */
    private static Map<Id, WorkOrder> fetchSARelatedWO(Map<Id, List<ServiceAppointment>> parentIDToSAs) {
        Set<Id> workOrderRefId = new Set<Id>();

        for (List<ServiceAppointment> saList : parentIDToSAs.values()) {
            for (ServiceAppointment sa : saList) {
                if (sa.ParentRecordId != null) {
                    workOrderRefId.add(sa.ParentRecordId);
                }
            }
        }
        System.debug('Getting these WO Ids related to the SAs: ' + workOrderRefId);
        Map<Id, WorkOrder> woInfo = new Map<Id, WorkOrder>(GDMFSL_WorkOrderProcessor.getRecords(workOrderRefId));
        return woInfo;
    }

    public static void updateRelatedWorkOrderStatus(List<ServiceAppointment> theSAs, Map<Id, ServiceAppointment> oldSaMap) {

        List<ServiceAppointment> tempList = new List<ServiceAppointment>();

        System.debug('Service Appointment: ' + theSAs);
        System.debug('Service Appointment Old Map: ' + (oldSaMap != null ? oldSaMap.values() : null));

        for (ServiceAppointment sa : theSAs) {
            if (sa.ParentRecordId != null
                    && sa.ParentRecordId.getSobjectType() == WorkOrder.getSObjectType()
                    && oldSaMap != null
                    && sa.Status != oldSaMap.get(sa.Id).Status) {
                System.debug('SA ParentRecord != null AND SObject is WorkOrder And Old Map n0t null AND SA Status != Old Map Status');
                tempList.add(sa);
            }
        }

        System.debug('SA Temp List : ' + tempList);
        System.debug('SA Temp List : ' + tempList.size());

        if (tempList.size() > 0) {
            GDMFSL_WorkOrderProcessor.updateWorkOrderStatusFromServiceAppointment(tempList);
        }

    }

    public static void unscheduleServContractSAs(Set<Id> servContractIds) {

        List<ServiceAppointment> saToUpdate = new List<ServiceAppointment>();

        for (ServiceAppointment sa : getRecords(servContractIds, ServiceContract.getSObjectType())) {
            if (STATUSFORUNSCHEDULING.contains(sa.Status)) {
                sa.Status = UNSCHEDULEDSTATUS;
                saToUpdate.add(sa);
            }
        }

        System.debug('SAs to Unschedule: ' + saToUpdate.size());

        if (!saToUpdate.isEmpty()) {
            GDMFSL_CommonUtilities.updateRecords(saToUpdate);
        }
    }

    public static void unScheduleAccountBlockedSAs(List<ServiceAppointment> serviceAppointments) {

        for (ServiceAppointment sa : serviceAppointments) {

            if (STATUSFORUNSCHEDULING.contains(sa.Status)) {
                System.debug('SA: ' + sa.Id + ' is being set to Status ' + UNSCHEDULEDSTATUS);
                sa.Status = UNSCHEDULEDSTATUS;
            }
        }

        GDMFSL_CommonUtilities.updateRecords(serviceAppointments);
    }


    public static void deleteSAsIfNeeded(List<ServiceAppointment> saList) {

        List<ServiceAppointment> saToDelete = new List<ServiceAppointment>();
        Set<Id> woIdsToGenSA = new Set<Id>();

        if (saList != null && !saList.isEmpty()) {

            Set<Id> woIdsNeeded = new Set<Id>();

            for (ServiceAppointment theSA : saList) {

                if (theSA.ParentRecordId != null && theSA.ParentRecordId.getSobjectType() == WorkOrder.getSObjectType()) {
                    woIdsNeeded.add(theSA.ParentRecordId);
                }

                if (theSA.ParentRecordId != null && theSA.ParentRecordId.getSobjectType() == WorkOrderLineItem.getSObjectType()) {
                    System.debug('Always delete SA on WOLIs -- they are not needed, but might have been auto-created due to WorkType: ' + theSA.Id);
                    saToDelete.add(new ServiceAppointment(Id = theSA.Id));
                }
            }

            System.debug('Have this many WOs to get: ' + woIdsNeeded.size());

            if (!woIdsNeeded.isEmpty()) {

                Map<Id, WorkOrder> woInfo = new Map<Id, WorkOrder>(GDMFSL_WorkOrderProcessor.getRecords(woIdsNeeded));

                for (ServiceAppointment theSA : saList) {

                    if (theSA.ParentRecordId != null && woInfo.containsKey(theSA.ParentRecordId)
                            && woInfo.get(theSA.ParentRecordId).ServiceTerritoryId != null
                            && (woInfo.get(theSA.ParentRecordId).Status == 'New' || woInfo.get(theSA.ParentRecordId).Status == 'Scheduled')) {

                        System.debug('Checking SA against WO.ServTerr.Max: ' + theSA.Id);
                        System.debug('Checking SA Duration: ' + theSA.DurationInMinutes);
                        System.debug('Checking WO.ServTerr.Max: ' + woInfo.get(theSA.ParentRecordId).ServiceTerritory.GDMFSL_Maximum_SA_Duration_Hrs__c);

                        Double maxSADurationToUse = woInfo.get(theSA.ParentRecordId).ServiceTerritory.GDMFSL_Maximum_SA_Duration_Hrs__c != null
                                ? (woInfo.get(theSA.ParentRecordId).ServiceTerritory.GDMFSL_Maximum_SA_Duration_Hrs__c * 60)
                                : (GDMFSL_ServiceAppointmentGenerator.DEFAULTMAXSERVICEAPPTDURATIONHRS * 60);

                        System.debug('Max SA Duration being used: ' + maxSADurationToUse);

                        if (theSA.DurationInMinutes > maxSADurationToUse) {
                            System.debug('SA Duration is too long -- deleting the SA');
                            saToDelete.add(new ServiceAppointment(Id = theSA.Id));
                            woIdsToGenSA.add(theSA.ParentRecordId);
                        }
                    }
                }
            }

            System.debug('SAs to Delete: ' + saToDelete.size());

            if (!saToDelete.isEmpty() && !GDMFSL_CommonUtilities.isFlagSet('SA Generation from Trigger')) {

                System.debug('Setting flag to prevent Batch recursion');
                GDMFSL_CommonUtilities.setFlag('SA Generation from Trigger');

                GDMFSL_CommonUtilities.deleteRecords(saToDelete);

                if (!woIdsToGenSA.isEmpty()) {
                    System.debug('WO Ids to Generate new SAs: ' + woIdsToGenSA.size());
                    GDMFSL_ServiceAppointmentGenerator genSA = new GDMFSL_ServiceAppointmentGenerator();
                    genSA.woIdsToTestWith.addAll(woIdsToGenSA);
                    Database.executeBatch(genSA);
                }
            }
        }
    }

}