src/objects/RMU_VALUE__c/RMU_VALUE__c.object-meta.xml
<CustomObject>
    <description>Retrofit Modification Upgrade</description>
    <label>Offering</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RMU_VALUE__c/fields/RMU_Type__c.field-meta.xml
<CustomField>
    <fullName>RMU_Type__c</fullName>
    <inlineHelpText>Contract = Sales records pulled from Contracts returned from SAP. 
Product = Sales records pulled from Opportunities Closed Won and/or SAP</inlineHelpText>
    <label>Offering Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestRmuValueBuilder_Test.cls
/**
 * Created by Nikolay Kolev on 4/16/2019.
 * OWNED BY THE CRM SALES TEAM.
 */

@IsTest
private class TestRmuValueBuilder_Test {
    @IsTest
    static void testDefaultBuild() {
        System.Test.startTest();
        Rmu_Value__c rmuValue = new TestRmuValueBuilder()
                .build();
        System.Test.stopTest();

        System.assertEquals(null, rmuValue.Id);
        System.assertEquals('Test Rmu Value',rmuValue.Name);
    }
    @IsTest
    static void testGenerate() {
        System.Test.startTest();
        Rmu_Value__c rmuValue = new TestRmuValueBuilder()
                .setName('My Rmu Value')
                .addField('RMU_Type__c', 'Product')
                .generate();
        System.Test.stopTest();

        Rmu_Value__c insertedRmuProduct = [
                SELECT Id
                FROM Rmu_Value__c
                WHERE Name = 'My Rmu Value'
                AND Id = :rmuValue.Id
                AND RMU_Type__c = 'Product'
        ];

        System.assertEquals(insertedRmuProduct.Id, rmuValue.Id);
        System.assertEquals('My Rmu Value', rmuValue.Name);
    }
}