src/objects/BGA_PO_Tracker__c/BGA_PO_Tracker__c.object-meta.xml
<CustomObject>
    <label>PO Tracker</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PO Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BGA_PO_Tracker__c/fields/Aircraft_not_in_service__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_not_in_service__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Aircraft not in service</description>
    <label>Aircraft not in service?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/BGA_PO_Tracker__c/fields/Charts_Platform_Family__c.field-meta.xml
<CustomField>
    <fullName>Charts_Platform_Family__c</fullName>
    <description>Charts Platform Family, this field is used for charts and to group platforms.</description>
    <label>Platform Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Challenger 601-3A/R</fullName>
            </value>
            <value>
                <fullName>Falcon 2000</fullName>
            </value>
            <value>
                <fullName>Falcon 7X</fullName>
            </value>
            <value>
                <fullName>Falcon 8X</fullName>
            </value>
            <value>
                <fullName>Falcon 900/900B</fullName>
            </value>
            <value>
                <fullName>Falcon 900 C/EX</fullName>
            </value>
            <value>
                <fullName>Falcon 900X</fullName>
            </value>
            <value>
                <fullName>Falcon 9X</fullName>
            </value>
            <value>
                <fullName>G550/G450/G350</fullName>
            </value>
            <value>
                <fullName>Global Express</fullName>
            </value>
            <value>
                <fullName>Gulfstream 650</fullName>
            </value>
            <value>
                <fullName>Gulfstream IV/V</fullName>
            </value>
            <value>
                <fullName>Hawker 800/1000</fullName>
            </value>
            <value>
                <fullName>Legacy 600</fullName>
            </value>
            <value>
                <fullName>Legacy 650</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/BGA_PO_Tracker__c/fields/Date_APM_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Date_APM_Shipped__c</fullName>
    <description>APM Shipment Date, this field and content is moved to option level</description>
    <label>APM Shipment Date ( obsolute )</label>
    <type>Date</type>
</CustomField>

src/objects/BGA_PO_Tracker__c/fields/Has_Baseline_or_Basic__c.field-meta.xml
<CustomField>
    <fullName>Has_Baseline_or_Basic__c</fullName>
    <description>If count is &gt; 0 then aircraft has EasyII Baseline or Cert Basic</description>
    <label>With Baseline or Basic</label>
    <summaryFilterItems>
        <field>BGA_PO_Tracker_Entry__c.RMU_Config_Detail_Name__c</field>
        <operation>equals</operation>
        <value>Baseline Only, Baseline, Basic</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>BGA_PO_Tracker_Entry__c.Sales_Price__c</field>
        <operation>greaterOrEqual</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>BGA_PO_Tracker_Entry__c.BGA_Purchase_Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/BGA_PO_Tracker__c/fields/Number_of_options__c.field-meta.xml
<CustomField>
    <fullName>Number_of_options__c</fullName>
    <label>Number of Entries</label>
    <summaryForeignKey>BGA_PO_Tracker_Entry__c.BGA_Purchase_Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/BGA_PO_Tracker__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>EMEIA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/BGA_PO_Tracker__c/fields/SN__c.field-meta.xml
<CustomField>
    <fullName>SN__c</fullName>
    <label>Serial#</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/BGA_PO_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/BGA_PO_Tracker_Entry__c/BGA_PO_Tracker_Entry__c.object-meta.xml
<CustomObject>
    <label>PO Tracker Option</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Tracker Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BGA_PO_Tracker_Entry__c/fields/BGA_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>BGA_Purchase_Order__c</fullName>
    <label>PO Tracker</label>
    <referenceTo>BGA_PO_Tracker__c</referenceTo>
    <relationshipLabel>PO Tracker Options</relationshipLabel>
    <relationshipName>PO_Tracker_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/BGA_PO_Tracker_Entry__c/fields/RMU_Config_Detail_Name__c.field-meta.xml
<CustomField>
    <fullName>RMU_Config_Detail_Name__c</fullName>
    <label>RMU Detail Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RMU_Name__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ADM Opt 4</fullName>
                <color>#78C953</color>
                <label>ADM Opt 4</label>
            </value>
            <value>
                <fullName>ADSB-Out Opt 2</fullName>
                <color>#A845DC</color>
                <label>ADSB-Out Opt 2</label>
            </value>
            <value>
                <fullName>ADS-B out V1</fullName>
            </value>
            <value>
                <fullName>ADS-B out V2</fullName>
                <color>#E27001</color>
                <label>ADS-B out V2</label>
            </value>
            <value>
                <fullName>AIS2000</fullName>
                <color>#F3D904</color>
                <label>AIS2000</label>
            </value>
            <value>
                <fullName>AMT700</fullName>
            </value>
            <value>
                <fullName>Baseline</fullName>
                <color>#A53711</color>
                <label>Baseline</label>
            </value>
            <value>
                <fullName>Baseline Only</fullName>
                <color>#66E9BD</color>
                <label>Baseline Only</label>
            </value>
            <value>
                <fullName>Basic</fullName>
                <color>#0B24BE</color>
                <label>Basic</label>
            </value>
            <value>
                <fullName>CDSR</fullName>
                <color>#419249</color>
                <label>CDSR</label>
            </value>
            <value>
                <fullName>Cert F</fullName>
                <color>#B6E32E</color>
                <label>Cert F</label>
            </value>
            <value>
                <fullName>Cert G</fullName>
                <color>#641CCF</color>
                <label>Cert G</label>
            </value>
            <value>
                <fullName>CGCR</fullName>
                <color>#F96FB7</color>
                <label>CGCR</label>
            </value>
            <value>
                <fullName>CNX200</fullName>
            </value>
            <value>
                <fullName>CPDLC</fullName>
                <color>#2F5D85</color>
                <label>CPDLC</label>
            </value>
            <value>
                <fullName>CPDLC ATN</fullName>
            </value>
            <value>
                <fullName>CPDLC FANS 1/A</fullName>
            </value>
            <value>
                <fullName>CVR</fullName>
                <color>#AFCADF</color>
                <label>CVR</label>
            </value>
            <value>
                <fullName>DL 950</fullName>
            </value>
            <value>
                <fullName>DU875</fullName>
                <color>#8F6429</color>
                <label>DU875</label>
            </value>
            <value>
                <fullName>DU885</fullName>
                <color>#EFAE73</color>
                <label>DU885</label>
            </value>
            <value>
                <fullName>Dual RAAS</fullName>
                <color>#57F17C</color>
                <label>Dual RAAS</label>
            </value>
            <value>
                <fullName>E-NAV</fullName>
                <color>#0B6FCE</color>
                <label>E-NAV</label>
            </value>
            <value>
                <fullName>Enhanced Nav Opt 1</fullName>
                <color>#78C953</color>
                <label>Enhanced Nav Opt 1</label>
            </value>
            <value>
                <fullName>FANS</fullName>
            </value>
            <value>
                <fullName>FANS2</fullName>
            </value>
            <value>
                <fullName>FANS Option</fullName>
                <color>#E27001</color>
                <label>FANS Option</label>
            </value>
            <value>
                <fullName>FMS 6.1</fullName>
                <color>#A845DC</color>
                <label>FMS 6.1</label>
            </value>
            <value>
                <fullName>GD04 GPS</fullName>
                <color>#F3D904</color>
                <label>GD04 GPS</label>
            </value>
            <value>
                <fullName>HD710</fullName>
                <color>#A53711</color>
                <label>HD710</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/BGA_PO_Tracker_Entry__c/fields/RMU_Date__c.field-meta.xml
<CustomField>
    <fullName>RMU_Date__c</fullName>
    <label>Finance Date</label>
    <type>Date</type>
</CustomField>

src/objects/BGA_PO_Tracker_Entry__c/fields/RMU_Name__c.field-meta.xml
<CustomField>
    <fullName>RMU_Name__c</fullName>
    <label>RMU Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADS B</fullName>
            </value>
            <value>
                <fullName>AIS2000</fullName>
            </value>
            <value>
                <fullName>AMT700</fullName>
            </value>
            <value>
                <fullName>Batch 3</fullName>
            </value>
            <value>
                <fullName>CDSR</fullName>
            </value>
            <value>
                <fullName>Cert D - G450/G550</fullName>
            </value>
            <value>
                <fullName>Cert E - G450/G550</fullName>
            </value>
            <value>
                <fullName>Cert F - G450/G550</fullName>
            </value>
            <value>
                <fullName>Cert G/H - G450/G550</fullName>
            </value>
            <value>
                <fullName>CGCR</fullName>
            </value>
            <value>
                <fullName>CNX200</fullName>
            </value>
            <value>
                <fullName>DL 950</fullName>
            </value>
            <value>
                <fullName>DU875</fullName>
            </value>
            <value>
                <fullName>DU885</fullName>
            </value>
            <value>
                <fullName>Easy II</fullName>
            </value>
            <value>
                <fullName>FANS</fullName>
            </value>
            <value>
                <fullName>FMS 6.1</fullName>
            </value>
            <value>
                <fullName>G650</fullName>
            </value>
            <value>
                <fullName>HD710</fullName>
            </value>
            <value>
                <fullName>Legacy 600</fullName>
            </value>
            <value>
                <fullName>OVATION</fullName>
            </value>
            <value>
                <fullName>Smart Landing</fullName>
            </value>
            <value>
                <fullName>Smart Runway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/BGA_PO_Tracker_Entry__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <formula>Value__c - Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Price ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/BGA_PO_Tracker_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>Text(BGA_Purchase_Order__r.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

src/classes/POTrackerRMUDetailPieChartController.cls
public class POTrackerRMUDetailPieChartController extends POTrackerPieChartMaster{
    
    List<BGA_PO_Tracker__c> listPO = null;
    public String newDebugMsg{get;set;}
    public Map<String,List<List<PieWedgeData>>> maplistpwd  {get;set;}
    public Map<String,Integer[]> regionCnt {get;set;}
    public Integer globalCnt {get;set;}
    	   Integer withBasicCount = 0;
    public Map<String,Map<String,Integer>> statusCnt {get;set;} 
    public Map<String,String> constantValues {get;set;}
    Map<String,String> doIncludeStatus = new Map<String,String>();
    public POTrackerRMUDetailPieChartController(){
    	constantValues = convertJsonIntoMap(Label.PieCharts_Static_String);
		String statusValues = (includeStatus == null ? Label.penetrationStatusIncluded : includeStatus );
		for(String s :statusValues.split(constantValues.get('semicolon'))){
			doIncludeStatus.put(s,s);
			if(includeBlanks == true)
			doIncludeStatus.put('','NONE');	
		}
		
        statusCnt =  new Map<String,Map<String,Integer>>();
        statusCnt.put(constantValues.get('global'),null);
        globalCnt =0;
        getPODetails();
        setLabelNameForRMU();
        getRegionalEasy2Charts();
        getMonthlySalesData();
    }
     String printStatusCount(String region){
     	String retVal = '';
     	
     	if(statusCnt == null){
     		return retVal;
     	}

     	if(statusCnt.containsKey(region) && statusCnt.get(region) == null){
     		return retVal;	
     	}
     	
     	String blankStr = '';
     	for(String s : doIncludeStatus.keySet()){
     		
     		if(statusCnt.get(region).containsKey(s) && s != blankStr )
     		if(statusCnt.get(region).get(s) != null){
     			retVal = retVal + s +'=' +statusCnt.get(region).get(s)+''+constantValues.get('semicolon')+' ';
     		}
     	}
     	
     	if(doIncludeStatus.containsKey(blankStr) && statusCnt.get(region).containsKey(blankStr)){
     			if(statusCnt.get(region).get(blankStr) != null)
     			retVal = retVal + constantValues.get('blank') +'=' +statusCnt.get(region).get(blankStr)+''+constantValues.get('semicolon');
     		}
     	
     	
     	return retVal;
     }

	

    
    Boolean hasValidStatus(String status){
    	if(status == null)
    	status = '';
    	return doIncludeStatus.containsKey(status);
    }
    
    void getPODetails(){
            		
	                listPO  =   
	                [   
	                	select Name,SN__c,Id,Region__c,Date_APM_Shipped__c,Has_Baseline_or_Basic__c,Status__c,Number_of_options__c,
	                            (
	                                select 
	                                RMU_Config_Detail_Name__c , BGA_Purchase_Order__r.Has_Baseline_or_Basic__c
	                                from PO_Tracker_Options__r 
	                                where RMU_Config_Detail_Name__c != null 
	                                and RMU_Name__c in :poRecTypeId.keySet()
	                                and RMU_Config_Detail_Name__c != :constantValues.get('others')
	                                and RMU_Config_Detail_Name__c in :getRMUConfigValues()
	                                and Status__c in :doIncludeStatus.keySet()
	                             ) 
	                    from BGA_PO_Tracker__c 
	                    where Charts_Platform_Family__c in :rmuReportPlatforms 
	                    and Region__c != ''
	                    and Aircraft_not_in_service__c = false
	                    ];
	                
	                for(BGA_PO_Tracker__c rec: listPO){
	                	if(rec.Has_Baseline_or_Basic__c > 0 && hasValidStatus(rec.Status__c))
	                    withBasicCount++;
	                }
	                    
	                 
            }
                
    public Map<String,List<List<PieWedgeData>>> getRegionalEasy2Charts(){
        
        regionCnt = new Map<String,Integer[]>();
        Map<String,RMUConfigTable>  mapCatData = new Map<String,RMUConfigTable>();
        List<String> configPickListValues  = getRMUConfigValues(); 
        
        for(String regn : getRegionValues()){
            
            for(String val : configPickListValues)
            if(val != constantValues.get('others')){
                mapCatData.put(regn+val,new RMUConfigTable(regn,0));
            }
            
            regionCnt.put(regn,new Integer[]{0,0});
            statusCnt.put(regn,null);
        }
        
        
        for(BGA_PO_Tracker__c poDetl : listPO)
        if(poDetl != null && poDetl.Region__c != null )
       	{
                    
                    regionCnt.put(	poDetl.Region__c,
                    				new Integer[]{
                    								regionCnt.get(poDetl.Region__c)[0] + 1,
                    								regionCnt.get(poDetl.Region__c)[1]+
                    									(poDetl.Has_Baseline_or_Basic__c > 0 && hasValidStatus(poDetl.Status__c)? 1:0)
                    							}
                    				);
                    
                    if(						(poRecTypeId.containsKey(Label.Easy_II) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (poRecTypeId.containsKey(Label.Cert_F) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (!poRecTypeId.containsKey(Label.Cert_F) && !poRecTypeId.containsKey(Label.Easy_II) && poDetl.Number_of_options__c > 0 )
	                  )
	                        			
                    		addStatusCnt(poDetl.Region__c,poDetl.Status__c);
                    

                    
                    Map<String,Integer> rmuCount = new Map<String,Integer>();
                    
                     For(BGA_PO_Tracker_Entry__c poEntry : poDetl.PO_Tracker_Options__r){
                     	
	                        if(
	                        		poEntry!=null 
	                        		&&  (
	                        				(poRecTypeId.containsKey(Label.Easy_II) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (poRecTypeId.containsKey(Label.Cert_F) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (!poRecTypeId.containsKey(Label.Cert_F) && !poRecTypeId.containsKey(Label.Easy_II) )
	                        			)
	                        ){ 
	                        	
	                            if(!rmuCount.containsKey(poEntry.RMU_Config_Detail_Name__c)){
	                            	
	                                rmuCount.put(poEntry.RMU_Config_Detail_Name__c,1);
	                                mapCatData.put(
	                                            poDetl.Region__c+poEntry.RMU_Config_Detail_Name__c, 
	                                            new RMUConfigTable(
	                                            	poDetl.Region__c,
	                                            	mapCatData.get(poDetl.Region__c+poEntry.RMU_Config_Detail_Name__c).cnt 
	                                            	+ 1
	                                            )
	                                        );                                      
	                            
	                            }
	                        
	            		 }
	            		 
                     }
        }
        
        
        maplistpwd = new Map<String,List<List<PieWedgeData>>>();
        for(String regn : getRegionValues())
        for(String key : getRMUConfigValues())
        if(key != constantValues.get('others')){
            String labelKey = rmuShortNameValue(key);
            key = regn+key;
            
            if(maplistpwd.get(mapCatData.get(key).region) == null){
                maplistpwd.put(mapCatData.get(key).region,new List<List<PieWedgeData>>());
            }
            
            List<PieWedgeData> data = new List<PieWedgeData>();
            
            Integer totalCnt = regionCnt.get(mapCatData.get(key).region)[0];
            Integer baselineBasicCnt = regionCnt.get(mapCatData.get(key).region)[1];
            
            if(poRecTypeId.containsKey(Label.Easy_II)){
                         if(key.contains(constantValues.get('baselineonly'))){ 
                            if(mapCatData.get(key).cnt > 0)
                            data.add(new PieWedgeData(labelKey  ,  mapCatData.get(key).cnt,'Baseline',totalCnt));
                            data.add(new PieWedgeData(constantValues.get('baseline')+' '+constantValues.get('with')+' '+constantValues.get('opt') ,   mapCatData.get(regn+'Baseline').cnt, constantValues.get('baseline'),totalCnt));
                            if(totalCnt      -  mapCatData.get(key).cnt - mapCatData.get(regn+'Baseline').cnt > 0 )
                            data.add(new PieWedgeData(constantValues.get('nobaseline'),            totalCnt      -  mapCatData.get(key).cnt - mapCatData.get(regn+'Baseline').cnt,constantValues.get('baseline')));
                            maplistpwd.get(mapCatData.get(key).region).add(data);
                            
                        }
                        else if(!key.contains(constantValues.get('baseline'))){
                            
                            data.add(new PieWedgeData(''+constantValues.get('with')+' - '+  labelKey ,        mapCatData.get(key).cnt, labelKey,baselineBasicCnt));
                            if( baselineBasicCnt - mapCatData.get(key).cnt > 0)
                            data.add(new PieWedgeData(''+constantValues.get('without')+'  - ' + labelKey ,      baselineBasicCnt - mapCatData.get(key).cnt, labelKey) );
                            maplistpwd.get(mapCatData.get(key).region).add(data);
                        
                        }
            }
            else if(poRecTypeId.containsKey(Label.Cert_F)){
                        if(key.contains(constantValues.get('sv1'))){    
                        	if(mapCatData.get(regn+constantValues.get('sv2')).cnt > 0)
                            data.add(new PieWedgeData(constantValues.get('sv1_or_sv2') ,     	mapCatData.get(regn+constantValues.get('sv2')).cnt,''+constantValues.get('sv1_or_sv2')+'',baselineBasicCnt));
                            data.add(new PieWedgeData(''+constantValues.get('sv1')+' '+constantValues.get('only') ,   	mapCatData.get(key).cnt -   mapCatData.get(regn+constantValues.get('sv2')).cnt, ''+constantValues.get('sv1_or_sv2')+'',baselineBasicCnt));
                            if(baselineBasicCnt   -  mapCatData.get(key).cnt > 0)
                            data.add(new PieWedgeData(''+constantValues.get('without')+' '+constantValues.get('sv1_or_sv2')+'', baselineBasicCnt   -  mapCatData.get(key).cnt ,''+constantValues.get('sv1_or_sv2')+''));
                            maplistpwd.get(mapCatData.get(key).region).add(data);
                        }
                        else if(!key.contains(constantValues.get('sv2'))){
                            data.add(new PieWedgeData(''+constantValues.get('with')+' - '+  labelKey ,        mapCatData.get(key).cnt, labelKey,(key.contains(constantValues.get('basic'))? totalCnt:baselineBasicCnt)));
	                        if( (key.contains(constantValues.get('basic'))? totalCnt:baselineBasicCnt) - mapCatData.get(key).cnt > 0)
                            data.add(new PieWedgeData(''+constantValues.get('without')+'  - ' + labelKey ,      (key.contains(constantValues.get('basic'))? totalCnt:baselineBasicCnt) - mapCatData.get(key).cnt, labelKey) );
                            maplistpwd.get(mapCatData.get(key).region).add(data);
                        
                        }
            }
            else{
                            data.add(new PieWedgeData(''+constantValues.get('with')+' - '+  labelKey ,        mapCatData.get(key).cnt, labelKey,totalCnt));
                            if(totalCnt - mapCatData.get(key).cnt > 0 )
                            data.add(new PieWedgeData(''+constantValues.get('without')+'  - ' + labelKey ,      totalCnt - mapCatData.get(key).cnt, labelKey) );
                            maplistpwd.get(mapCatData.get(key).region).add(data);
            }
            
            
        }
        return maplistpwd;
    }

       public List<List<PieWedgeData>> getGlobalEasy2Charts(){
        Map<String,Integer>  mapCatData = new Map<String,Integer>();
        List<String> configPickListValues  = getRMUConfigValues(); 
        
        for(String val : configPickListValues)
        if(val != constantValues.get('others')) {
            mapCatData.put(val,0);
        }
        
        globalCnt = listPO.size();
        
        for(BGA_PO_Tracker__c poDetl : listPO)
        {
            Map<String,Integer> rmuCount = new Map<String,Integer>();
            
           if((poRecTypeId.containsKey(Label.Easy_II) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (poRecTypeId.containsKey(Label.Cert_F) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (!poRecTypeId.containsKey(Label.Cert_F) && !poRecTypeId.containsKey(Label.Easy_II) && poDetl.Number_of_options__c > 0 ))
            addStatusCnt('Global',poDetl.status__c);
            
            for(BGA_PO_Tracker_Entry__c poEntry : poDetl.PO_Tracker_Options__r) // This line blocks with basic/basline options
                if(poEntry != null &&  (
	                        				(poRecTypeId.containsKey(Label.Easy_II) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (poRecTypeId.containsKey(Label.Cert_F) && poDetl.Has_Baseline_or_Basic__c > 0)
	                        			||  (!poRecTypeId.containsKey(Label.Cert_F) && !poRecTypeId.containsKey(Label.Easy_II) )
	                        			)
	              )
		            {
		                if(!rmuCount.containsKey(poEntry.RMU_Config_Detail_Name__c)){
		                                        rmuCount.put(poEntry.RMU_Config_Detail_Name__c,1);
		                                        mapCatData.put(poEntry.RMU_Config_Detail_Name__c, mapCatData.get(poEntry.RMU_Config_Detail_Name__c) + 1)  ;
		                                    }
		            }
            
            
        }
        
        List<List<PieWedgeData>> listpwd = new List<List<PieWedgeData>>();
        for(String key : getRMUConfigValues())
        if(key != constantValues.get('others')){
            List<PieWedgeData> data = new List<PieWedgeData>();
            
            if(poRecTypeId.containsKey(Label.Easy_II)){
                    if(key.contains(constantValues.get('baseline')) && key != constantValues.get('baseline')){
                    	if(mapCatData.get(key) > 0)  
                        data.add(new PieWedgeData(constantValues.get('baselineonly') ,        mapCatData.get(key),constantValues.get('baseline'),listPO.size()));
                        data.add(new PieWedgeData(constantValues.get('baseline')+' '+constantValues.get('with')+' '+constantValues.get('opt') ,        mapCatData.get(constantValues.get('baseline')), constantValues.get('baseline'),listPO.size()));
                        
                        if(listPO.size() -  mapCatData.get(key) - mapCatData.get(constantValues.get('baseline')) > 0)
                        data.add(new PieWedgeData(constantValues.get('nobaseline'),   listPO.size() -  mapCatData.get(key) - mapCatData.get(constantValues.get('baseline')),constantValues.get('baseline')));
                        listpwd.add(data);
                    }
                    else if(key != constantValues.get('baseline')){
                        data.add(new PieWedgeData(''+constantValues.get('with')+' - '+ rmuShortNameValue(key) ,      mapCatData.get(key), rmuShortNameValue(key),withBasicCount));
                        if(withBasicCount - mapCatData.get(key) > 0)
                        data.add(new PieWedgeData(''+constantValues.get('without')+'  - ' + rmuShortNameValue(key) ,  withBasicCount - mapCatData.get(key), rmuShortNameValue(key)) );
                        
                        listpwd.add(data);
                    }
            }
            else if(poRecTypeId.containsKey(Label.Cert_F)){
                if(key == constantValues.get('sv1')){   
                		if(mapCatData.get(constantValues.get('sv2')) > 0)
                        data.add(new PieWedgeData(constantValues.get('sv1_or_sv2') ,        mapCatData.get(constantValues.get('sv2')),constantValues.get('sv1_or_sv2'),withBasicCount));
                        data.add(new PieWedgeData(''+constantValues.get('sv1')+' '+constantValues.get('only') ,      (mapCatData.get(key) -  mapCatData.get(constantValues.get('sv2'))), constantValues.get('sv1_or_sv2'),withBasicCount));
                        if(withBasicCount -  mapCatData.get(key) > 0)
                        data.add(new PieWedgeData(''+constantValues.get('without')+' '+constantValues.get('sv1_or_sv2')+'',   withBasicCount -  mapCatData.get(key),constantValues.get('sv1_or_sv2')));
                        listpwd.add(data);
                    }
                    else if(key != constantValues.get('sv2')){
                        data.add(new PieWedgeData(''+constantValues.get('with')+' - '+ rmuShortNameValue(key) ,      mapCatData.get(key), rmuShortNameValue(key),(key.contains(constantValues.get('basic'))? listPO.size():withBasicCount)));
                        if( (key.contains(constantValues.get('basic'))? listPO.size():withBasicCount) - mapCatData.get(key) > 0)
                        data.add(new PieWedgeData(''+constantValues.get('without')+'  - ' + rmuShortNameValue(key) ,  (key.contains(constantValues.get('basic'))? listPO.size():withBasicCount) - mapCatData.get(key), rmuShortNameValue(key)) );
                        listpwd.add(data);
                    }
            }
            else{
                        data.add(new PieWedgeData(''+constantValues.get('with')+' - '+ rmuShortNameValue(key) ,      mapCatData.get(key), rmuShortNameValue(key),listPO.size()));
                        if(listPO.size() - mapCatData.get(key) > 0)
                        data.add(new PieWedgeData(''+constantValues.get('without')+'  - ' + rmuShortNameValue(key) ,  listPO.size() - mapCatData.get(key), rmuShortNameValue(key)) );
                        listpwd.add(data);
            }
        
        }
        return listpwd;
    }
        
	public Map<String,Map<String,Integer>> displayMonthlyData {get;set;}
	public List<String> ytdMonthsList {get;set;}
	void getMonthlySalesData(){
		
					List<AggregateResult> dataFromMonthlySales = 
							 [	select 
							 			RMU_Config_Detail_Name__c,
							 			CALENDAR_MONTH(RMU_Date__c) month ,
							 			Count(Id) 
								from 	BGA_PO_Tracker_Entry__c  
								where 	RMU_Name__c in :poRecTypeId.keySet()
									and CALENDAR_YEAR(RMU_Date__c) 	= :getCurrentYear()
	                                and RMU_Config_Detail_Name__c 	!= :constantValues.get('others')
	                                and RMU_Config_Detail_Name__c 	in :getRMUConfigValues()								
	                                and ( Sales_Price__c = null or Sales_Price__c >= 0 )
	                                and CALENDAR_MONTH(RMU_Date__c) <= :getCurrentMonth()
	                                and BGA_Purchase_Order__r.Status__c  in :doIncludeStatus.keySet()
	                                and BGA_Purchase_Order__r.Charts_Platform_Family__c in :rmuReportPlatforms 
								group by RMU_Config_Detail_Name__c,CALENDAR_MONTH(RMU_Date__c)
								order by RMU_Config_Detail_Name__c,CALENDAR_MONTH(RMU_Date__c)
							];
				
				displayMonthlyData = new Map<String,Map<String,Integer>>();
				ytdMonthsList = new List<String>();
				Integer cnt =1;
					for(String monthName : monthsList){
						ytdMonthsList.add(monthName);
						
						if(getCurrentMonth() <= cnt){
							break;
						}
						cnt ++;
						
					}
				
				for(String rec : getRMUConfigValues()){
					
					Map<String,Integer> newNode = new Map<String,Integer>();
					for(String monthName : ytdMonthsList){
						newNode.put(monthName , 0 );
					}
					
					if(rmuShortNameValue(rec) == constantValues.get('sv1') || rmuShortNameValue(rec) == constantValues.get('sv2')){
						displayMonthlyData.put(constantValues.get('sv1_or_sv2'),newNode);
					}
					else{
						displayMonthlyData.put(rmuShortNameValue(rec),newNode);
					}
					
				}
				
				 for (AggregateResult ar : dataFromMonthlySales) {
				 	
							if(	rmuShortNameValue(String.valueOf(ar.get('RMU_Config_Detail_Name__c'))) == constantValues.get('sv1') || 
								rmuShortNameValue(String.valueOf(ar.get('RMU_Config_Detail_Name__c'))) == constantValues.get('sv2')){
								
								displayMonthlyData.get(constantValues.get('sv1_or_sv2')).
								put(
										monthsList[Integer.valueof(ar.get('month'))-1],
										displayMonthlyData.get(constantValues.get('sv1_or_sv2')).get(monthsList[Integer.valueof(ar.get('month'))-1])+
										Integer.valueof(ar.get('expr0'))
									
									);
								
								
							}
							else if(	rmuShortNameValue(String.valueOf(ar.get('RMU_Config_Detail_Name__c'))).contains(constantValues.get('baseline'))){
										displayMonthlyData.get(constantValues.get('baseline')).put(
												monthsList[Integer.valueof(ar.get('month'))-1],
															displayMonthlyData.get(constantValues.get('baseline')).get(monthsList[Integer.valueof(ar.get('month'))-1]) 
														+ Integer.valueof(ar.get('expr0'))
											);
							}
							else if(displayMonthlyData.containsKey(String.valueOf(rmuShortNameValue(String.valueOf(ar.get('RMU_Config_Detail_Name__c')))))){
									
								displayMonthlyData.get(rmuShortNameValue(String.valueOf(ar.get('RMU_Config_Detail_Name__c')))).
								put(monthsList[Integer.valueof(ar.get('month'))-1],Integer.valueof(ar.get('expr0')));
							
							}
					
				}
							
		
	}    
	
	public String getPieColors2(){
		return constantValues.get('piecolor2'); 
	}
	public String getPieColors3(){
		return constantValues.get('piecolor3'); 
	}	
	
	public String getPrintGlobalCount(){
		return printStatusCount(constantValues.get('global'));
	}
	public String getPrintAmericasCount(){
		return printStatusCount(constantValues.get('americas'));
	}
		public String getPrintEMEIACount(){
		return printStatusCount(constantValues.get('emeia'));
	}
		public String getPrintAPACCount(){
		return printStatusCount(constantValues.get('apac'));
	}
    
    void addStatusCnt(String regn,String status){
	    	if(status == null){
	    		status = '';
	    	}
	    	
	    	if(
	    	//Label.penetrationStatusIncluded.contains(status)
	    	doIncludeStatus.containsKey(status)
	    	){		
			    	if(statusCnt.get(regn) == null){
			    		statusCnt.put(regn,  new Map<String,Integer>{status => 0});
			    	}
			    	if(statusCnt.get(regn).containsKey(status)){	
			    		statusCnt.get(regn).put(status,statusCnt.get(regn).get(status)+1);
			    	}
			    	else{
			    		statusCnt.get(regn).put(status,1);
			    	}
	    	}
    }
}