src/objects/OpportunityLineItem/fields/OpportunityAccountChange__c.field-meta.xml
<CustomField>
    <fullName>OpportunityAccountChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OpportunityAccountChange</label>
    <type>Checkbox</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Tech_Sales__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales__c</fullName>
    <label>Tech Sales</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aerospace Services</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>Auxiliary Power and Thermal Systems</fullName>
            </value>
            <value>
                <fullName>BendixKing</fullName>
            </value>
            <value>
                <fullName>Cockpit Systems</fullName>
            </value>
            <value>
                <fullName>Electric Power and Lighting</fullName>
            </value>
            <value>
                <fullName>Engines</fullName>
            </value>
            <value>
                <fullName>FM&amp;T National Security Campus</fullName>
            </value>
            <value>
                <fullName>HTSI</fullName>
            </value>
            <value>
                <fullName>Mechanical Components</fullName>
            </value>
            <value>
                <fullName>Navigation and Sensors</fullName>
            </value>
            <value>
                <fullName>Other Product Line</fullName>
            </value>
            <value>
                <fullName>Safety and Connectivity</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Wheels and Braking Systems</fullName>
            </value>
            <value>
                <fullName>Avionics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/Tech_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tech Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Tech_Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales_Product__c</fullName>
    <label>Tech Sales Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tech_Sales__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Adjacencies</fullName>
            </value>
            <value>
                <fullName>AGT1500</fullName>
            </value>
            <value>
                <fullName>AIMS/ VIA</fullName>
            </value>
            <value>
                <fullName>Air Cycle Systems</fullName>
            </value>
            <value>
                <fullName>Air Data Products</fullName>
            </value>
            <value>
                <fullName>Airframe Hydraulics</fullName>
            </value>
            <value>
                <fullName>Air Source Systems</fullName>
            </value>
            <value>
                <fullName>Air Turbine Start Systems &amp; Motors</fullName>
            </value>
            <value>
                <fullName>ALF502 / LF507</fullName>
            </value>
            <value>
                <fullName>APU 131</fullName>
            </value>
            <value>
                <fullName>APU 331</fullName>
            </value>
            <value>
                <fullName>APU 331 Large</fullName>
            </value>
            <value>
                <fullName>APU 36-100</fullName>
            </value>
            <value>
                <fullName>APU 36-150</fullName>
            </value>
            <value>
                <fullName>APU 36-155</fullName>
            </value>
            <value>
                <fullName>APU 36-200</fullName>
            </value>
            <value>
                <fullName>APU 36-280 / 36-300</fullName>
            </value>
            <value>
                <fullName>APU 36-50/55</fullName>
            </value>
            <value>
                <fullName>APU 660 / 700</fullName>
            </value>
            <value>
                <fullName>APU 85</fullName>
            </value>
            <value>
                <fullName>APU AMADs</fullName>
            </value>
            <value>
                <fullName>APU G250</fullName>
            </value>
            <value>
                <fullName>APU HGT1700</fullName>
            </value>
            <value>
                <fullName>APU HGT750</fullName>
            </value>
            <value>
                <fullName>APU Jet Fuel Starter</fullName>
            </value>
            <value>
                <fullName>APU JSF</fullName>
            </value>
            <value>
                <fullName>APU Misc Adv Tech</fullName>
            </value>
            <value>
                <fullName>APU Other D&amp;S</fullName>
            </value>
            <value>
                <fullName>APU RE100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product_Line_Tech_Sales__c/Product_Line_Tech_Sales__c.object-meta.xml
<CustomObject>
    <label>Product Line Tech Sales</label>
    <nameField>
        <displayFormat>PLT-{000000000}</displayFormat>
        <label>Product Line Tech Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Line Tech Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Line_Tech_Sales__c/fields/Tech_Sales__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales__c</fullName>
    <label>Tech Sales</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aerospace Services</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>Auxiliary Power and Thermal Systems</fullName>
            </value>
            <value>
                <fullName>BendixKing</fullName>
            </value>
            <value>
                <fullName>Cockpit Systems</fullName>
            </value>
            <value>
                <fullName>Electric Power and Lighting</fullName>
            </value>
            <value>
                <fullName>Engines</fullName>
            </value>
            <value>
                <fullName>FM&amp;T National Security Campus</fullName>
            </value>
            <value>
                <fullName>HTSI</fullName>
            </value>
            <value>
                <fullName>Mechanical Components</fullName>
            </value>
            <value>
                <fullName>Navigation and Sensors</fullName>
            </value>
            <value>
                <fullName>Other Product Line</fullName>
            </value>
            <value>
                <fullName>Safety and Connectivity</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Wheels and Braking Systems</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product_Line_Tech_Sales__c/fields/Tech_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tech Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Line_Tech_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product_Line_Tech_Sales__c/fields/Tech_Sales_Product__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales_Product__c</fullName>
    <label>Tech Sales Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tech_Sales__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Adjacencies</fullName>
            </value>
            <value>
                <fullName>AGT1500</fullName>
            </value>
            <value>
                <fullName>AIMS/ VIA</fullName>
            </value>
            <value>
                <fullName>Air Cycle Systems</fullName>
            </value>
            <value>
                <fullName>Air Data Products</fullName>
            </value>
            <value>
                <fullName>Airframe Hydraulics</fullName>
            </value>
            <value>
                <fullName>Air Source Systems</fullName>
            </value>
            <value>
                <fullName>Air Turbine Start Systems &amp; Motors</fullName>
            </value>
            <value>
                <fullName>ALF502 / LF507</fullName>
            </value>
            <value>
                <fullName>APU 131</fullName>
            </value>
            <value>
                <fullName>APU 331</fullName>
            </value>
            <value>
                <fullName>APU 331 Large</fullName>
            </value>
            <value>
                <fullName>APU 36-100</fullName>
            </value>
            <value>
                <fullName>APU 36-150</fullName>
            </value>
            <value>
                <fullName>APU 36-155</fullName>
            </value>
            <value>
                <fullName>APU 36-200</fullName>
            </value>
            <value>
                <fullName>APU 36-280 / 36-300</fullName>
            </value>
            <value>
                <fullName>APU 36-50/55</fullName>
            </value>
            <value>
                <fullName>APU 660 / 700</fullName>
            </value>
            <value>
                <fullName>APU 85</fullName>
            </value>
            <value>
                <fullName>APU AMADs</fullName>
            </value>
            <value>
                <fullName>APU G250</fullName>
            </value>
            <value>
                <fullName>APU HGT1700</fullName>
            </value>
            <value>
                <fullName>APU HGT750</fullName>
            </value>
            <value>
                <fullName>APU Jet Fuel Starter</fullName>
            </value>
            <value>
                <fullName>APU JSF</fullName>
            </value>
            <value>
                <fullName>APU Misc Adv Tech</fullName>
            </value>
            <value>
                <fullName>APU Other D&amp;S</fullName>
            </value>
            <value>
                <fullName>APU RE100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/SetTechSalesFromProductLineTechSale.cls
/**
 * Created by Nikolay Kolev on 4/10/2019.
 * OWNED BY THE CRM SALES TEAM.
 * @description Used in the tech sales builder factory for the OLI triggers.
 */

public class SetTechSalesFromProductLineTechSale implements TechSalesSettable {

    private OpportunityLineItem lineItem;
    private Product_Line_Tech_Sales__c productLineTechSale;

    public SetTechSalesFromProductLineTechSale(OpportunityLineItem lineItem, Product_Line_Tech_Sales__c productLineTechSale) {
        this.lineItem = lineItem;
        this.productLineTechSale = productLineTechSale;
    }

    /**
     * @param lineItem Corresponds to the line item which tech sales will be updated.
     * @param productLineTechSale Corresponds to the product line tech sales object which data will be used to populate
     * the line item's tech sales.
     */
    public void setTechSales() {
        lineItem.Tech_Sales__c = productLineTechSale.Tech_Sales__c;
        lineItem.Tech_Sales_Product__c = productLineTechSale.Tech_Sales_Product__c;
        lineItem.Tech_Sales_Manager__c = productLineTechSale.Tech_Sales_Manager__c;
        lineItem.OpportunityAccountChange__c = false;
    }
}