src/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>AT-{0000}-{YY}-{YYYY}</displayFormat>
        <label>Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Class__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

src/objects/Class__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value>Null</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <formula>Course_Name__r.Name</formula>
    <label>Course</label>
    <type>Text</type>
</CustomField>

src/objects/Class__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF((TEXT(End_Date__c-Start_Date__c)==&apos;1&apos; || TEXT(End_Date__c-Start_Date__c)==&apos;0&apos;), TEXT(End_Date__c-Start_Date__c) +&apos; &apos;+ &apos;day&apos;, TEXT(End_Date__c-Start_Date__c) +&apos; &apos;+ &apos;days&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

src/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Field used in the course schedule VF page</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/objects/Class__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Class__c/fields/Seats_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Seats_Remaining__c</fullName>
    <formula>Total_Number_of_Seats__c - Number_of_reservations__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seats Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Field used in the course schedule VF page</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Added for location calculation - this will allow comparison of contact location to other data such as user location, and return distance. It also allows mapping. It stores Latitude and Longitude in decimal form.</description>
    <inlineHelpText>SF Geolocation data field - This will allow comparison of contact location to other data such as user location, and return distance. It also allows mapping. It stores Latitude and Longitude in decimal form.</inlineHelpText>
    <label>Location</label>
    <scale>12</scale>
    <type>Location</type>
</CustomField>

src/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>For Req 3085</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Course Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location</relationshipLabel>
    <relationshipName>Location</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Confirmation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reservation__c/fields/Attended__c.field-meta.xml
<CustomField>
    <fullName>Attended__c</fullName>
    <label>Attended</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
                <default>true</default>
                <label>No Show</label>
            </value>
            <value>
                <fullName>No Show/Confirmed</fullName>
            </value>
            <value>
                <fullName>Attended/Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Reservation__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <formula>Class_Name__r.Class_Name__c</formula>
    <label>Class</label>
    <type>Text</type>
</CustomField>

src/objects/Reservation__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Reservation__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <formula>Class_Name__r.Course_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Name</label>
    <type>Text</type>
</CustomField>

src/objects/Reservation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Class_Name__r.End_Date__c</formula>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/objects/Reservation__c/fields/Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Status__c</fullName>
    <label>Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Time Out</fullName>
            </value>
            <value>
                <fullName>Wait List</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Reservation__c/fields/Reservation_Type__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Type__c</fullName>
    <label>Reservation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Item</fullName>
            </value>
            <value>
                <fullName>Instructor</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
                <default>true</default>
                <label>Student</label>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Reservation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Class_Name__r.Start_Date__c</formula>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/objects/Reservation__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Reservation__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <formula>Student__r.FirstName + &apos; &apos; +  Student__r.LastName</formula>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

src/objects/Reservation__c/fields/Unique_Field__c.field-meta.xml
<CustomField>
    <fullName>Unique_Field__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Field</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/classes/TestReg_cls.cls
public class TestReg_cls {
Class__c c = new Class__c();
public boolean showselectedlist{get;set;}
public boolean showdetails{get;set;}
//public string relatedContactName {get; set;}
 

list<Contact> selectedcontactlist = new List<Contact>();
list<Reservation__c> rv  = new list<Reservation__c>();
list<Reservation__c> reservetoinsert = new List<Reservation__c>();
list<ID> reservetoinsertadd = new List<ID>();
String  uid;
Id i;

public void getdetails(){
        system.debug('****************Userid******'+Userinfo.getuserid());
        i = ApexPages.currentPage().getParameters().get('id');
        //i= System.currentPagereference().getParameters().get('id');
        system.debug('************ID VALUE*************'+i);
        
        c  = [select name,Contact__c, Course_Name__c,Description__c,End_Date__c,Start_Date__c,Course__c,Location__r.name,Duration__c,Seats_Remaining__c  from Class__c where id =:i]; 
    }

public class__c getclass(){
        return c;
    }
 
public void addrow(){
         //system.debug('***********gotta*********'+c);
         contact addrow= new contact(id=c.Contact__c);
         selectedcontactlist.add(addrow);
         showselectedlist=True;
         Reservation__c  rv0 = new Reservation__c();
         rv0.Student__c = c.Contact__c;
         rv0.Class_Name__c = i;
         rv0.Reservation_Type__c = 'Item';
         rv0.Reservation_Status__c = 'Registered';
         rv0.Attended__c = 'No Show';
         reservetoinsert.add(rv0);
    } 
    
public List<contact> getselectedcontactlist(){
        List<Contact> Name = [Select id, name from contact where id in : selectedcontactlist];
        return Name;
    }
         
public void reserve(){
        System.debug('************************* Inside reserve block');
    try
        {
            insert reservetoinsert;
            if(reservetoinsert.size()>0)
        for(Reservation__c rev : reservetoinsert){
            reservetoinsertadd.add(rev.ID);
            selectedcontactlist.clear();
        }
            rv = [select name,Reservation_Type__c,Reservation_Status__c,Student__c,Course_Name__c,Class_Name__c,Student_Name__c,Class__c from Reservation__c where Id In: reservetoinsertadd]; 
            showdetails = true;
            showselectedlist = False;
            reservetoinsert.clear();
        }
    catch(Exception e)
        {
            String str = String.valueof(e);
            if(str.contains('Unique_Field__c duplicates value'))
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'You already have a reservation or Same contact has been added again.');
                ApexPages.addMessage(myMsg);
            }
    else
        {
            ApexPages.addMessages(e);
        }
            System.debug('************************* Exception in inserting reservation records');
        }
}

public list<Reservation__c> getrv(){
        return rv;
    }
    
public PageReference Done(){   
        Pagereference p = new Pagereference('/'+i);
        p.setredirect(true);
        return p;
    }        
}