src/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Account Address</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SFDC Row ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Address__c/fields/Authorized_Avionics_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Avionics_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Create for BGA Mobile Directory App</description>
    <label>Authorized Avionics Dealer</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Account_Address__c/fields/Authorized_Mechanical_Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Mechanical_Service_Center__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for the BGA Mobile Directory App</description>
    <label>Authorized Mechanical Service Center</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Account_Address__c/fields/Avionics_Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Avionics_Support_Level__c</fullName>
    <description>Created for BGA Mobile Directory App. Same field as Avionics Dealer Type</description>
    <label>Avionics Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Avionic Sales and Installation</fullName>
            </value>
            <value>
                <fullName>Avionic Sales, Installation and Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Address_1__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Address_1__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob Address 1</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Address_2__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Address_2__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob Address 2</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Address_3__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Address_3__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob Address 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_City_Name__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_City_Name__c</fullName>
    <description>Created for BGA Mobile Directory</description>
    <label>BGAMob City Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Contact_Email__c</fullName>
    <description>Created for BGA Mobile Directory</description>
    <label>BGAMob Contact Email</label>
    <type>Email</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Contact_Name__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob Contact Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Country_Nm__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Country_Nm__c</fullName>
    <description>Created for BGA Mobile App</description>
    <label>BGAMob Country Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Customer_Phone__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob Customer Phone</label>
    <type>Phone</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Geo_Code__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Geo_Code__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob_Geo_Code</label>
    <scale>7</scale>
    <type>Location</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Postal_Code__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_State_Province__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_State_Province__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob State/Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/BGAMob_Website__c.field-meta.xml
<CustomField>
    <fullName>BGAMob_Website__c</fullName>
    <description>Created for BGA Mobile Directory App</description>
    <label>BGAMob Website</label>
    <type>Url</type>
</CustomField>

src/objects/Account_Address__c/fields/Engine_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Engine_Authorization__c</fullName>
    <description>Created for BGA Mobile App to capture the Specific Engine Platform services by the dealer or service center</description>
    <label>Engine Authorization</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/Mechanical_Product_Lines__c.field-meta.xml
<CustomField>
    <fullName>Mechanical_Product_Lines__c</fullName>
    <description>Created for BGA Mobile App</description>
    <label>Mechanical Product Lines</label>
    <type>TextArea</type>
</CustomField>

src/objects/Account_Address__c/fields/Mobile_App_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Mobile_App_Visibility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for BGA Mobile Directory App. Will determine if account will be visible in the mobile app or not</description>
    <label>Mobile App Visibility</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Account_Address__c/fields/Report_Account_name__c.field-meta.xml
<CustomField>
    <fullName>Report_Account_name__c</fullName>
    <formula>Account_Name__r.Report_Account_Name_upper__c</formula>
    <label>Report Account name</label>
    <type>Text</type>
</CustomField>

src/objects/Account_Address__c/fields/Report_Account_Name_small__c.field-meta.xml
<CustomField>
    <fullName>Report_Account_Name_small__c</fullName>
    <description>SR#442809</description>
    <formula>Account_Name__r.REPORT_ACCOUNT_NAME__c</formula>
    <label>Report Account Name small</label>
    <type>Text</type>
</CustomField>

src/objects/BGAMobile_MechanicalAuthorizations__c/BGAMobile_MechanicalAuthorizations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>BGA Mobile Mechanical Authorizations</description>
    <label>BGAMobile_MechanicalAuthorizations</label>
</CustomObject>

src/classes/BGAProductLine.cls
public without sharing class BGAProductLine 
{

   public BGAProductLine (ApexPages.StandardController controller) {
              // acc= New Account_Address__c();
                lSelectedacc= New List<Account_Address__c>();
                 try{
        String prodn = ApexPages.currentPage().getParameters().get('prod');
        System.debug('UAT Testing'+prodn );

            objAccounts = new list<Account_Address__c>(); 
            if(prodn!='AvionicSalesandInstallation' && prodn!='AvionicSalesInstallationandRepair'){ 
            prodn  = '%' + prodn +'%';
          objAccounts.addAll([Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Website__c,BGAMob_Geo_Code__Latitude__s, BGAMob_Geo_Code__Longitude__s,BGAMob_Contact_Name__c,Avionics_Support_Level__c,Engine_Authorization__c,BGAMob_Contact_Email__c,Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_Address_1__c,BGAMob_Address_2__c,BGAMob_Address_3__c,BGAMob_City_Name__c,BGAMob_State_Province__c,BGAMob_Postal_Code__c,BGAMob_Country_Nm__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,Mobile_App_Visibility__c from Account_Address__c where  Mobile_App_Visibility__c=true and Mechanical_Product_Lines__c like :prodn   and BGAMob_Geo_Code__Latitude__s != null] );
             //  objAccounts.addAll([Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Website__c,BGAMob_Geo_Code__Latitude__s, BGAMob_Geo_Code__Longitude__s,BGAMob_Contact_Name__c,Avionics_Support_Level__c,Engine_Authorization__c,BGAMob_Contact_Email__c,Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_Address_1__c,BGAMob_Address_2__c,BGAMob_Address_3__c,BGAMob_City_Name__c,BGAMob_State_Province__c,BGAMob_Postal_Code__c,BGAMob_Country_Nm__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,Mobile_App_Visibility__c from Account_Address__c where  Mobile_App_Visibility__c=true and BGAMob_Geo_Code__Latitude__s != null] );         
            }
            else
            {
            if(prodn=='AvionicSalesandInstallation')
             prodn='Avionic Sales and Installation';
             if(prodn=='AvionicSalesInstallationandRepair')
             prodn='Avionic Sales, Installation and Repair';
             
             prodn  = '%' + prodn +'%';
            objAccounts.addAll([Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Website__c,BGAMob_Geo_Code__Latitude__s, BGAMob_Geo_Code__Longitude__s,BGAMob_Contact_Name__c,Avionics_Support_Level__c,Engine_Authorization__c,BGAMob_Contact_Email__c,Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_Address_1__c,BGAMob_Address_2__c,BGAMob_Address_3__c,BGAMob_City_Name__c,BGAMob_State_Province__c,BGAMob_Postal_Code__c,BGAMob_Country_Nm__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,Mobile_App_Visibility__c from Account_Address__c where  Mobile_App_Visibility__c=true and Avionics_Support_Level__c like :prodn   and BGAMob_Geo_Code__Latitude__s != null] );
               // objAccounts.addAll([Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Website__c,BGAMob_Geo_Code__Latitude__s, BGAMob_Geo_Code__Longitude__s,BGAMob_Contact_Name__c,Avionics_Support_Level__c,Engine_Authorization__c,BGAMob_Contact_Email__c,Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_Address_1__c,BGAMob_Address_2__c,BGAMob_Address_3__c,BGAMob_City_Name__c,BGAMob_State_Province__c,BGAMob_Postal_Code__c,BGAMob_Country_Nm__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,Mobile_App_Visibility__c from Account_Address__c where  Mobile_App_Visibility__c=true and BGAMob_Geo_Code__Latitude__s != null] );
            }
        System.debug(objAccounts);
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error:'
                                                        +ex.getMessage()));
        }   
            }

            List<Account_Address__c> lSelectedacc= New List<Account_Address__c>();
            public list<Account_Address__c> objAccounts {get;set;}
            
            
            @RemoteAction 
       public  static List<Account_Address__c> getProductLineDealers(String strProd) 
       {
            list<Account_Address__c> objAccountDeal = new list<Account_Address__c>(); 
            if(strProd !='AvionicSalesandInstallation' && strProd !='AvionicSalesInstallationandRepair'){ 
            strProd = '%' + strProd+'%';
            objAccountDeal.addAll([Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Website__c,BGAMob_Geo_Code__Latitude__s, BGAMob_Geo_Code__Longitude__s,BGAMob_Contact_Name__c,Avionics_Support_Level__c,Engine_Authorization__c,BGAMob_Contact_Email__c,Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_Address_1__c,BGAMob_Address_2__c,BGAMob_Address_3__c,BGAMob_City_Name__c,BGAMob_State_Province__c,BGAMob_Postal_Code__c,BGAMob_Country_Nm__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,Mobile_App_Visibility__c from Account_Address__c where  Mobile_App_Visibility__c=true and Mechanical_Product_Lines__c like :strProd and BGAMob_Geo_Code__Latitude__s != null] );
            }
            else
            {
            if(strProd =='AvionicSalesandInstallation')
             strProd ='Avionic Sales and Installation';
             if(strProd=='AvionicSalesInstallationandRepair')
             strProd='Avionic Sales, Installation and Repair';
             
             strProd = '%' + strProd +'%';
            objAccountDeal.addAll([Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Website__c,BGAMob_Geo_Code__Latitude__s, BGAMob_Geo_Code__Longitude__s,BGAMob_Contact_Name__c,Avionics_Support_Level__c,Engine_Authorization__c,BGAMob_Contact_Email__c,Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_Address_1__c,BGAMob_Address_2__c,BGAMob_Address_3__c,BGAMob_City_Name__c,BGAMob_State_Province__c,BGAMob_Postal_Code__c,BGAMob_Country_Nm__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,Mobile_App_Visibility__c from Account_Address__c where  Mobile_App_Visibility__c=true and Avionics_Support_Level__c like :strProd and BGAMob_Geo_Code__Latitude__s != null] );
            }
        System.debug(objAccountDeal);
            
        
        
       
      // lfinalprod = [SELECT Mechanical_Product_Lines__c FROM Account_Address__c where Mobile_App_Visibility__c = true and Mechanical_Product_Lines__c  != null group by Mechanical_Product_Lines__c order by Mechanical_Product_Lines__c  ];
     //System.debug(lfinalprod);
      return objAccountDeal;
      
      
       }
 @RemoteAction 
       public  static List<BGAMobile_MechanicalAuthorizations__c> getProduct() 
       {
       List<BGAMobile_MechanicalAuthorizations__c> lfinalprod=New List<BGAMobile_MechanicalAuthorizations__c>();
       
        Map<String, BGAMobile_MechanicalAuthorizations__c> mechprod= BGAMobile_MechanicalAuthorizations__c.getAll();
        
        // Sort them by name
         for(BGAMobile_MechanicalAuthorizations__c mechsett: mechprod.values()) {
           
                lfinalprod.add(mechsett);
            
        }
        
        lfinalprod.sort();
      // lfinalprod = [SELECT Mechanical_Product_Lines__c FROM Account_Address__c where Mobile_App_Visibility__c = true and Mechanical_Product_Lines__c  != null group by Mechanical_Product_Lines__c order by Mechanical_Product_Lines__c  ];
     //System.debug(lfinalprod);
      return lfinalprod;
      
      
       }
       @RemoteAction
           Static public Account_Address__c getContact(String strId)
           {
           Account_Address__c Arec = [select id,Report_Account_name__c,Report_Account_Name_small__c,Avionics_Support_Level__c,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,BGAMob_Address_1__c,BGAMob_Address_2__c,BGAMob_Address_3__c,BGAMob_City_Name__c,BGAMob_State_Province__c,BGAMob_Country_Nm__c,BGAMob_Postal_Code__c,BGAMob_Website__c ,Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c from Account_Address__c where id=:strId];
           
           return Arec;
           }   
         @RemoteAction
           public  static List<List<Account_Address__c>> getContactByProduct(String strProd)
           {
                 //  String strProd = ApexPages.currentPage().getParameters().get('prod');
           String str = null;
           
            //String strProd = getProdln();
       //    strProd = strProd.replace('amp;','');
           List<List<Account_Address__c>> lAccRec = new List<List<Account_Address__c>>();
    
      List<Account_Address__c> lisAvionics = new List<Account_Address__c>();
      
      List<Account_Address__c> lisMechanical = new List<Account_Address__c>();
      List<Account_Address__c> lisAll = new List<Account_Address__c>();
      
      if(strProd!='AvionicSalesandInstallation' && strProd!='AvionicSalesInstallationandRepair'){ 
             String q = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      q+= 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      q+= 'where Mobile_App_Visibility__c=true ';
        str = '%'+ strProd +'%';
               q+= ' and Mechanical_Product_Lines__c like: str'; 
      
 
      q += ' order by BGAMob_Country_Nm__c,BGAMob_State_Province__c';
      //System.debug('q value--->'+q);
      lisAll = Database.query(q);
            }
            else
            {
            if(strProd=='AvionicSalesandInstallation')
             str ='Avionic Sales and Installation';
             if(strProd=='AvionicSalesInstallationandRepair')
             str ='Avionic Sales, Installation and Repair';
             
            String q = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      q+= 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      q+= 'where Mobile_App_Visibility__c=true ';
        str = '%'+ str +'%';
               q+= ' and Avionics_Support_Level__c  like: str'; 
      
 
      q += ' order by BGAMob_Country_Nm__c,BGAMob_State_Province__c';
      //System.debug('q value--->'+q);
      lisAll = Database.query(q);
            }
            System.debug('strProd value'+strProd);
          if(strProd!='AvionicSalesandInstallation' && strProd!='AvionicSalesInstallationandRepair'){ 
             String avin = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      avin+= 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      avin+= 'where Mobile_App_Visibility__c=true AND Authorized_Avionics_Dealer__c=true ';
      str = '%'+ strProd +'%';
               avin+= ' and Mechanical_Product_Lines__c like: str'; 
      avin+= ' order by BGAMob_Country_Nm__c,BGAMob_State_Province__c'; 
     System.debug('avin value--->'+avin);
    lisAvionics =Database.query(avin);
            }
            else
            {
            System.debug('strProd value else condition of line 121 '+strProd);
            if(strProd=='AvionicSalesandInstallation')
             str ='Avionic Sales and Installation';
             if(strProd=='AvionicSalesInstallationandRepair')
             str ='Avionic Sales, Installation and Repair';
             
            String avin = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      avin+= 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      avin+= 'where Mobile_App_Visibility__c=true AND Authorized_Avionics_Dealer__c=true ';
      str = '%'+ str +'%';
               avin+= ' and Avionics_Support_Level__c like: str'; 
      avin+= ' order by BGAMob_Country_Nm__c,BGAMob_State_Province__c'; 
     System.debug('avin value--->'+avin);
    lisAvionics =Database.query(avin);
            }
       if(strProd!='AvionicSalesandInstallation' && strProd!='AvionicSalesInstallationandRepair'){ 
             String mech = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      mech += 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      mech += 'where Mobile_App_Visibility__c=true AND Authorized_Mechanical_Service_Center__c=true';
      
       str = '%'+ strProd +'%';
               mech += ' and Mechanical_Product_Lines__c like: str'; 
      mech += ' order by BGAMob_Country_Nm__c,BGAMob_State_Province__c'; 
       //System.debug('mech  value--->'+mech);
    lisMechanical=Database.query(mech);
            }
            else
            {
            if(strProd=='AvionicSalesandInstallation')
             str ='Avionic Sales and Installation';
             if(strProd=='AvionicSalesInstallationandRepair')
             str ='Avionic Sales, Installation and Repair';
             
            String mech = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      mech += 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      mech += 'where Mobile_App_Visibility__c=true AND Authorized_Mechanical_Service_Center__c=true';
      
       str = '%'+ str +'%';
               mech += ' and Avionics_Support_Level__c like: str'; 
      mech += ' order by BGAMob_Country_Nm__c,BGAMob_State_Province__c'; 
       System.debug('mech  value--->'+mech);
    lisMechanical=Database.query(mech);
            }
            lAccRec.add(lisAvionics);
        lAccRec.add(lisMechanical);
        lAccRec.add(lisAll);  
           return lAccRec;
           }
        
        
         @RemoteAction
           public static List<List<Account_Address__c>> getContactByProductUsingGPS(String strProd,Decimal lat,Decimal lng)
           {
           
          String str = null;
    
           
           
          
           List<List<Account_Address__c>> lAccRec = new List<List<Account_Address__c>>();
    
      List<Account_Address__c> lisAvionics = new List<Account_Address__c>();
      
      List<Account_Address__c> lisMechanical = new List<Account_Address__c>();
      List<Account_Address__c> lisAll = new List<Account_Address__c>();
      
     if(strProd!='AvionicSalesandInstallation' && strProd!='AvionicSalesInstallationandRepair'){ 
 String q = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Geo_Code__Latitude__s ,BGAMob_Geo_Code__Longitude__s ,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      q+= 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      q+= 'where Mobile_App_Visibility__c=true ';
       str = '%'+ strProd +'%';
               q+= ' and Mechanical_Product_Lines__c like: str'; 
q += ' and  BGAMob_Geo_Code__Latitude__s != null and BGAMob_Geo_Code__Longitude__s != null ';
      q += ' order by DISTANCE(BGAMob_Geo_Code__c, GEOLOCATION(';
      q += String.valueOf(lat) + ',' + String.valueOf(lng) + '), \'mi\')';

        lisAll = Database.query(q);
        }
        else
        {
        if(strProd=='AvionicSalesandInstallation')
             str ='Avionic Sales and Installation';
             if(strProd=='AvionicSalesInstallationandRepair')
             str ='Avionic Sales, Installation and Repair';
             String q = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Geo_Code__Latitude__s ,BGAMob_Geo_Code__Longitude__s ,Engine_Authorization__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      q+= 'Mechanical_Product_Lines__c,Avionics_Support_Level__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      q+= 'where Mobile_App_Visibility__c=true ';
       str = '%'+ str +'%';
               q+= ' and Avionics_Support_Level__c like: str'; 
q += ' and  BGAMob_Geo_Code__Latitude__s != null and BGAMob_Geo_Code__Longitude__s != null ';
      q += ' order by DISTANCE(BGAMob_Geo_Code__c, GEOLOCATION(';
      q += String.valueOf(lat) + ',' + String.valueOf(lng) + '), \'mi\')';

        lisAll = Database.query(q);
        }
        
        if(strProd!='AvionicSalesandInstallation' && strProd!='AvionicSalesInstallationandRepair'){ 
 String avin = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Geo_Code__Latitude__s ,BGAMob_Geo_Code__Longitude__s ,Engine_Authorization__c,Avionics_Support_Level__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      avin+= 'Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      avin+= 'where Mobile_App_Visibility__c=true AND Authorized_Avionics_Dealer__c=true ';
       str = '%'+ strProd +'%';
               avin += ' and Mechanical_Product_Lines__c like: str'; 
      avin += ' and  BGAMob_Geo_Code__Latitude__s != null and BGAMob_Geo_Code__Longitude__s != null ';
      avin += ' order by DISTANCE(BGAMob_Geo_Code__c, GEOLOCATION(';
      avin += String.valueOf(lat) + ',' + String.valueOf(lng) + '), \'mi\')';
    
    lisAvionics =Database.query(avin);
        }
        else
        {
        if(strProd=='AvionicSalesandInstallation')
             str ='Avionic Sales and Installation';
             if(strProd=='AvionicSalesInstallationandRepair')
             str ='Avionic Sales, Installation and Repair';
              String avin = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Geo_Code__Latitude__s ,BGAMob_Geo_Code__Longitude__s ,Engine_Authorization__c,Avionics_Support_Level__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      avin+= 'Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      avin+= 'where Mobile_App_Visibility__c=true AND Authorized_Avionics_Dealer__c=true ';
       str = '%'+ str  +'%';
               avin += ' and Avionics_Support_Level__c like: str'; 
      avin += ' and  BGAMob_Geo_Code__Latitude__s != null and BGAMob_Geo_Code__Longitude__s != null ';
      avin += ' order by DISTANCE(BGAMob_Geo_Code__c, GEOLOCATION(';
      avin += String.valueOf(lat) + ',' + String.valueOf(lng) + '), \'mi\')';
    
    lisAvionics =Database.query(avin);
        }
        
        
         
      if(strProd!='AvionicSalesandInstallation' && strProd!='AvionicSalesInstallationandRepair'){ 
 String mech = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Geo_Code__Latitude__s ,BGAMob_Geo_Code__Longitude__s ,Engine_Authorization__c,Avionics_Support_Level__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      mech += 'Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      mech += 'where Mobile_App_Visibility__c=true AND Authorized_Mechanical_Service_Center__c=true';
      str = '%'+ strProd +'%';
               mech+= ' and Mechanical_Product_Lines__c like: str'; 
      mech += ' and  BGAMob_Geo_Code__Latitude__s != null and BGAMob_Geo_Code__Longitude__s != null ';
      mech += ' order by DISTANCE(BGAMob_Geo_Code__c, GEOLOCATION(';
      mech += String.valueOf(lat) + ',' + String.valueOf(lng) + '), \'mi\')';
      
    lisMechanical=Database.query(mech);
        }
        else
        {
        if(strProd=='AvionicSalesandInstallation')
             str ='Avionic Sales and Installation';
             if(strProd=='AvionicSalesInstallationandRepair')
             str ='Avionic Sales, Installation and Repair';
              String mech = 'Select Id,Report_Account_name__c,Report_Account_Name_small__c,BGAMob_Geo_Code__Latitude__s ,BGAMob_Geo_Code__Longitude__s ,Engine_Authorization__c,Avionics_Support_Level__c,BGAMob_Contact_Name__c,BGAMob_Contact_Email__c,';
      mech += 'Mechanical_Product_Lines__c,BGAMob_Customer_Phone__c,BGAMob_State_Province__c, Authorized_Avionics_Dealer__c,Authorized_Mechanical_Service_Center__c,BGAMob_Country_Nm__c,Mobile_App_Visibility__c from Account_Address__c ';
      mech += 'where Mobile_App_Visibility__c=true AND Authorized_Mechanical_Service_Center__c=true';
      str = '%'+ str +'%';
               mech+= ' and Avionics_Support_Level__c like: str'; 
      mech += ' and  BGAMob_Geo_Code__Latitude__s != null and BGAMob_Geo_Code__Longitude__s != null ';
      mech += ' order by DISTANCE(BGAMob_Geo_Code__c, GEOLOCATION(';
      mech += String.valueOf(lat) + ',' + String.valueOf(lng) + '), \'mi\')';
      
    lisMechanical=Database.query(mech);
        }
            lAccRec.add(lisAvionics);
        lAccRec.add(lisMechanical);
        lAccRec.add(lisAll);  
           return lAccRec;
           }
}