src/objects/Apttus_Billing__BillingSchedule__c/Apttus_Billing__BillingSchedule__c.object-meta.xml
<CustomObject>
    <description>Represents a billing schedule for a product or service</description>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{00000000}</displayFormat>
        <label>Schedule Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__BillingSchedule__c/fields/Apttus_Billing__OrderLineItemId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__OrderLineItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The ID of the associated Order Line Item</description>
    <inlineHelpText>The ID of the associated Order Line Item</inlineHelpText>
    <label>Order Line Item</label>
    <referenceTo>Apttus_Config2__OrderLineItem__c</referenceTo>
    <relationshipLabel>Billing Schedules</relationshipLabel>
    <relationshipName>Billing_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Billing__BillingSchedule__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The schedule status</description>
    <inlineHelpText>The schedule status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Milestone</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
                <default>true</default>
                <label>Pending Billing</label>
            </value>
            <value>
                <fullName>Pending Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoiced Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/Apttus_Billing__Invoice__c.object-meta.xml
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__Invoice__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The invoice status</description>
    <inlineHelpText>The invoice status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
            <value>
                <fullName>Draft Obsolete</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/fields/Is_License_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_License_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_License_Required</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/fields/SoldTo_Number__c.field-meta.xml
<CustomField>
    <fullName>SoldTo_Number__c</fullName>
    <label>SoldTo Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/Apttus_Billing__InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a single item in an invoice</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__BillingScheduleId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillingScheduleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated billing schedule</description>
    <inlineHelpText>ID of the associated billing schedule</inlineHelpText>
    <label>Billing Schedule</label>
    <referenceTo>Apttus_Billing__BillingSchedule__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__InvoiceId__c</fullName>
    <description>ID of the associated invoice</description>
    <inlineHelpText>ID of the associated invoice</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The iline item status</description>
    <inlineHelpText>The line item status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/SoldTo_Number__c.field-meta.xml
<CustomField>
    <fullName>SoldTo_Number__c</fullName>
    <formula>TEXT(VALUE(IF
(Find(&quot;-&quot;, Apttus_Billing__BillingScheduleId__r.Apttus_Billing__OrderLineItemId__r.Apttus_Config2__OrderId__r.soldToNumber__c) &gt; 0, 
LEFT(Apttus_Billing__BillingScheduleId__r.Apttus_Billing__OrderLineItemId__r.Apttus_Config2__OrderId__r.soldToNumber__c, Find(&quot;-&quot;, Apttus_Billing__BillingScheduleId__r.Apttus_Billing__OrderLineItemId__r.Apttus_Config2__OrderId__r.soldToNumber__c)-1), 
Apttus_Billing__BillingScheduleId__r.Apttus_Billing__OrderLineItemId__r.Apttus_Config2__OrderId__r.soldToNumber__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SoldTo Number</label>
    <type>Text</type>
</CustomField>

src/objects/Apttus_Config2__Order__c/Apttus_Config2__Order__c.object-meta.xml
<CustomObject>
    <description>Represents an order associated with an account</description>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c/fields/Apttus_Config2__PODate__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PODate__c</fullName>
    <description>The purchase order date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The purchase order date</inlineHelpText>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

src/objects/Apttus_Config2__Order__c/fields/Apttus_Config2__PONumber__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__PONumber__c</fullName>
    <description>The purchase order number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The purchase order number</inlineHelpText>
    <label>PO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Apttus_Config2__Order__c/fields/SoldTo_Number__c.field-meta.xml
<CustomField>
    <fullName>SoldTo_Number__c</fullName>
    <label>SoldTo_Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

src/objects/Apttus_Config2__OrderLineItem__c/fields/License_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiry_Date__c</fullName>
    <formula>IF(ISBLANK(Apttus_Config2__EndDate__c),&apos;&apos;,
    IF(AND(ISNULL(Apttus_Config2__OptionId__c),ISNULL(Apttus_Config2__ProductId__c)), &apos;&apos;,

       IF(AND(ISBLANK(TEXT(Apttus_Config2__OptionId__r.Term__c)),ISNULL(Apttus_Config2__OptionId__c),ISBLANK(TEXT(Apttus_Config2__ProductId__r.Term__c))), &apos;&apos;,
           IF(AND(NOT(ISNULL(Apttus_Config2__OptionId__c)),NOT(ISBLANK(TEXT(Apttus_Config2__OptionId__r.Term__c))),ISPICKVAL(Apttus_Config2__OptionId__r.Term__c, &apos;1 year&apos;),NOT(ISPICKVAL(Apttus_Config2__OptionId__r.License_Type__c,&apos;APU&apos;))), TEXT(ADDMONTHS(Apttus_Config2__EndDate__c,12)) ,
               IF(AND(NOT(ISNULL(Apttus_Config2__OptionId__c)),NOT(ISBLANK(TEXT(Apttus_Config2__OptionId__r.Term__c))),ISPICKVAL(Apttus_Config2__OptionId__r.Term__c, &apos;Indefinite&apos;),NOT(ISPICKVAL(Apttus_Config2__OptionId__r.License_Type__c,&apos;APU&apos;))),&apos;Unlimited&apos;,
                   IF(AND(NOT(ISNULL(Apttus_Config2__OptionId__c)),ISBLANK(TEXT(Apttus_Config2__OptionId__r.Term__c))),&apos;&apos;,

                      IF(AND(ISNULL(Apttus_Config2__OptionId__c),NOT(ISBLANK(TEXT(Apttus_Config2__ProductId__r.Term__c))),ISPICKVAL(Apttus_Config2__ProductId__r.Term__c, &apos;1 year&apos;),NOT(ISPICKVAL(Apttus_Config2__OptionId__r.License_Type__c,&apos;APU&apos;))), TEXT(ADDMONTHS(Apttus_Config2__EndDate__c,12)),
                          IF(AND(ISNULL(Apttus_Config2__OptionId__c),NOT(ISBLANK(TEXT(Apttus_Config2__ProductId__r.Term__c))),ISPICKVAL(Apttus_Config2__ProductId__r.Term__c, &apos;Indefinite&apos;),NOT(ISPICKVAL(Apttus_Config2__OptionId__r.License_Type__c,&apos;APU&apos;))), &apos;Unlimited&apos;,
                              IF(AND(ISNULL(Apttus_Config2__OptionId__c),ISBLANK(TEXT(Apttus_Config2__ProductId__r.Term__c))), &apos;&apos;,
&apos;&apos;
                        )
                       )
                      )
                    )
                )
             )
         )
      )
  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Expiry Date</label>
    <type>Text</type>
</CustomField>

src/objects/CPQ_Platform__c/CPQ_Platform__c.object-meta.xml
<CustomObject>
    <label>CPQ Platform</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CPQ_Platform__c/fields/License_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiry_Date__c</fullName>
    <label>License Expiry Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/CPQ_Platform__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <referenceTo>Apttus_Config2__OrderLineItem__c</referenceTo>
    <relationshipLabel>CPQ Platforms</relationshipLabel>
    <relationshipName>CPQ_Platforms</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Product2/fields/Apttus_Config2__ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Config2__ConfigurationType__c</fullName>
    <description>The product configuration type</description>
    <label>Configuration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standalone</fullName>
                <default>true</default>
                <label>Standalone</label>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Is_License_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_License_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is License Required</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Product2/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APU</fullName>
            </value>
            <value>
                <fullName>Flexera</fullName>
            </value>
            <value>
                <fullName>lmx</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 year</fullName>
            </value>
            <value>
                <fullName>Indefinite</fullName>
            </value>
            <value>
                <fullName>100 year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Term__c/Term__c.object-meta.xml
<CustomObject>
    <description>TOOLKIT - used to capture key terms and their details as they relate the project</description>
    <label>Term</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderLicenseRestResourceTest.cls
@istest
public class OrderLicenseRestResourceTest{
    
    @isTest
    static void getOrderlicensestest1(){
        //Creating Standalone product
        product2 prod1 = new product2();
        prod1.Name = 'test1'; 
        prod1.IsActive = true;   
        prod1.Apttus_Config2__ConfigurationType__c = 'Standalone'; 
        prod1.family = 'Nav Database';
        prod1.Is_License_Required__c=true;
        prod1.Term__c= 'Indefinite';
        insert prod1;
        Apttus_Config2__Order__c objOrder= new Apttus_Config2__Order__c();
        objOrder.Apttus_Config2__Type__c='New';
        objOrder.CurrencyIsoCode='EUR';
        objOrder.Apttus_Config2__PODate__c=system.today();
        objOrder.Apttus_Config2__PONumber__c='1234';
        objOrder.SoldTo_Number__c='32324';
        insert objOrder;
        Apttus_Config2__Order__c objOrder2= new Apttus_Config2__Order__c();
        objOrder2.Apttus_Config2__Type__c='New';
        objOrder2.CurrencyIsoCode='EUR';
        objOrder2.Apttus_Config2__PODate__c=system.today();
        objOrder2.Apttus_Config2__PONumber__c='1234';
        objOrder2.SoldTo_Number__c='2443144';
        insert objOrder2;
        
        Apttus_Config2__OrderLineItem__c objLineitem = new Apttus_Config2__OrderLineItem__c();
        objLineitem.Apttus_Config2__LineNumber__c=1;
        objLineitem.Apttus_Config2__ItemSequence__c=1;
        objLineitem.CurrencyIsoCode='EUR';
        objLineitem.Apttus_Config2__OrderId__c=objOrder.id;
        objLineitem.Apttus_Config2__ProductId__c=prod1.id;
        objLineitem.Apttus_Config2__OptionId__c=prod1.id;
        objLineitem.Apttus_Config2__EndDate__c=system.today();
        insert objLineitem;
        CPQ_Platform__c platf= new CPQ_Platform__c();
        platf.Order_Line_Item__c=objLineitem.id;
        platf.Type__c='test';
        insert platf;
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
            Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        Apttus_Billing__BillingSchedule__c billingSchedule = new Apttus_Billing__BillingSchedule__c();
        billingSchedule.Apttus_Billing__OrderLineItemId__c=objLineitem.Id;
        insert billingSchedule;
        
        Apttus_Billing__InvoiceLineItem__c invoiceLineItem = new Apttus_Billing__InvoiceLineItem__c(
            Apttus_Billing__InvoiceId__c = invoice.id,
            Apttus_Billing__BillingScheduleId__c = billingSchedule.id
        );
        
        RestRequest request = new RestRequest();    
        RestResponse response = new RestResponse();   
        request.requestUri = 'https://hon-aero--apttusdev.my.salesforce.com/services/apexrest/ngbss/licenses';
        request.httpMethod = 'GET';
        request.addParameter('invoiceId', invoice.id);
        //request.addParameter('soldTos', '32324');
        request.addParameter('category', 'Nav Database');
        RestContext.request = request;
        RestContext.response = response;
        OrderLicenseRestResource.getOrderlicenses();
        
        RestRequest request2 = new RestRequest();    
        RestResponse response2 = new RestResponse();   
        request2.requestUri = 'https://hon-aero--apttusdev.my.salesforce.com/services/apexrest//ngbss/licenses';
        request2.httpMethod = 'GET';
        //request2.addParameter('invoiceId', invoice.id);
        request2.addParameter('soldTos', '32324');
        request2.addParameter('category', 'Nav Database');
        RestContext.request = request2;
        RestContext.response = response2;
        OrderLicenseRestResource.getOrderlicenses();
        
        RestRequest request3 = new RestRequest();    
        RestResponse response3 = new RestResponse();   
        request3.requestUri = 'https://hon-aero--apttusdev.my.salesforce.com/services/apexrest//ngbss/licenses';
        request3.httpMethod = 'GET';
        request3.addParameter('invoiceId', invoice.id);
        request3.addParameter('soldTos', '32324');
        request3.addParameter('category', 'Nav Database');
        RestContext.request = request3;
        RestContext.response = response3;
        OrderLicenseRestResource.getOrderlicenses();
    }
    @isTest
    static void getOrderlicensestest2(){
        //Creating Standalone product
        product2 prod1 = new product2();
        prod1.Name = 'test1'; 
        prod1.IsActive = true;   
        prod1.Apttus_Config2__ConfigurationType__c = 'Standalone'; 
        prod1.family = 'Nav Database';
        prod1.Is_License_Required__c=true;
        //prod1.Term__c= 'Indefinite';
    prod1.License_Type__c = 'APU';
        insert prod1;
        Apttus_Config2__Order__c objOrder= new Apttus_Config2__Order__c();
        objOrder.Apttus_Config2__Type__c='New';
        objOrder.CurrencyIsoCode='EUR';
        objOrder.Apttus_Config2__PODate__c=system.today();
        objOrder.Apttus_Config2__PONumber__c='1234';
        objOrder.SoldTo_Number__c='32324';
        insert objOrder;
        Apttus_Config2__Order__c objOrder2= new Apttus_Config2__Order__c();
        objOrder2.Apttus_Config2__Type__c='New';
        objOrder2.CurrencyIsoCode='EUR';
        objOrder2.Apttus_Config2__PODate__c=system.today();
        objOrder2.Apttus_Config2__PONumber__c='1234';
        objOrder2.SoldTo_Number__c='2443144';
        insert objOrder2;
        
        Apttus_Config2__OrderLineItem__c objLineitem = new Apttus_Config2__OrderLineItem__c();
        objLineitem.Apttus_Config2__LineNumber__c=1;
        objLineitem.Apttus_Config2__ItemSequence__c=1;
        objLineitem.CurrencyIsoCode='EUR';
        objLineitem.Apttus_Config2__OrderId__c=objOrder.id;
        objLineitem.Apttus_Config2__ProductId__c=prod1.id;
        objLineitem.Apttus_Config2__OptionId__c=prod1.id;
        objLineitem.Apttus_Config2__EndDate__c=system.today();
        //objLineitem.License_Expiry_Date__c=;
        insert objLineitem;
        CPQ_Platform__c platf= new CPQ_Platform__c();
        platf.Order_Line_Item__c=objLineitem.id;
        platf.Type__c='test';
        insert platf;
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
            Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        Apttus_Billing__BillingSchedule__c billingSchedule = new Apttus_Billing__BillingSchedule__c();
        billingSchedule.Apttus_Billing__OrderLineItemId__c=objLineitem.Id;
        insert billingSchedule;
        
        Apttus_Billing__InvoiceLineItem__c invoiceLineItem = new Apttus_Billing__InvoiceLineItem__c(
            Apttus_Billing__InvoiceId__c = invoice.id,
            Apttus_Billing__BillingScheduleId__c = billingSchedule.id
        );
        
        RestRequest request = new RestRequest();    
        RestResponse response = new RestResponse();   
        request.requestUri = 'https://hon-aero--apttusdev.my.salesforce.com/services/apexrest/ngbss/licenses';
        request.httpMethod = 'GET';
        request.addParameter('invoiceId', invoice.id);
        //request.addParameter('soldTos', '32324');
        request.addParameter('category', 'Nav Database');
        RestContext.request = request;
        RestContext.response = response;
        OrderLicenseRestResource.getOrderlicenses();
        
        RestRequest request2 = new RestRequest();    
        RestResponse response2 = new RestResponse();   
        request2.requestUri = 'https://hon-aero--apttusdev.my.salesforce.com/services/apexrest//ngbss/licenses';
        request2.httpMethod = 'GET';
        //request2.addParameter('invoiceId', invoice.id);
        request2.addParameter('soldTos', '32324');
        request2.addParameter('category', 'Nav Database');
        RestContext.request = request2;
        RestContext.response = response2;
        OrderLicenseRestResource.getOrderlicenses();
        
        RestRequest request3 = new RestRequest();    
        RestResponse response3 = new RestResponse();   
        request3.requestUri = 'https://hon-aero--apttusdev.my.salesforce.com/services/apexrest//ngbss/licenses';
        request3.httpMethod = 'GET';
        request3.addParameter('invoiceId', invoice.id);
        request3.addParameter('soldTos', '32324');
        request3.addParameter('category', 'Nav Database');
        RestContext.request = request3;
        RestContext.response = response3;
        OrderLicenseRestResource.getOrderlicenses();
    }
    @isTest
    static void OrderlicensesHeadertest1(){
        test.starttest();
        //Creating Standalone product
        product2 prod1 = new product2();
        prod1.Name = 'test1'; 
        prod1.IsActive = true;   
        prod1.Apttus_Config2__ConfigurationType__c = 'Standalone'; 
    prod1.family = 'Nav Database';
        prod1.Is_License_Required__c=true;
        prod1.Term__c= 'Indefinite';
    insert prod1;
        Apttus_Config2__Order__c objOrder= new Apttus_Config2__Order__c();
        objOrder.Apttus_Config2__Type__c='New';
        objOrder.CurrencyIsoCode='EUR';
        objOrder.Apttus_Config2__PODate__c=system.today();
        objOrder.Apttus_Config2__PONumber__c='1234';
        objOrder.SoldTo_Number__c='32324';
        insert objOrder;
        Apttus_Config2__OrderLineItem__c objLineitem = new Apttus_Config2__OrderLineItem__c();
        objLineitem.Apttus_Config2__LineNumber__c=1;
        objLineitem.Apttus_Config2__ItemSequence__c=1;
        objLineitem.CurrencyIsoCode='EUR';
        objLineitem.Apttus_Config2__OrderId__c=objOrder.id;
        objLineitem.Apttus_Config2__ProductId__c=prod1.id;
        objLineitem.Apttus_Config2__OptionId__c=prod1.id;
        objLineitem.Apttus_Config2__EndDate__c=system.today();
        insert objLineitem;
        CPQ_Platform__c platf= new CPQ_Platform__c();
        platf.Order_Line_Item__c=objLineitem.id;
        platf.Type__c='test';
        insert platf;
        Apttus_Config2__OrderLineItem__c objLineitem2 = new Apttus_Config2__OrderLineItem__c();
        objLineitem2.Apttus_Config2__LineNumber__c=1;
        objLineitem2.Apttus_Config2__ItemSequence__c=1;
        objLineitem2.CurrencyIsoCode='EUR';
        objLineitem2.Apttus_Config2__OrderId__c=objOrder.id;
        objLineitem2.Apttus_Config2__ProductId__c=prod1.id;
        objLineitem2.Apttus_Config2__OptionId__c=prod1.id;
        objLineitem2.Apttus_Config2__EndDate__c=system.today();
        insert objLineitem2;
        CPQ_Platform__c platf2= new CPQ_Platform__c();
        platf2.Order_Line_Item__c=objLineitem2.id;
        platf2.Type__c='test';
        insert platf2;
        
        String json='{'+
    '    "lineItems": ['+
    '        {'+
    '            "lineItemId": "'+objLineitem.id+'",'+
    '            "activationKey": "a123",'+
    '            "platforms": ['+
    '                {'+
    '                    "platformId": "'+platf.id+'",'+
    '                    "activationKey": "a456",'+
    '                    "licenseStatus": "Activation Key-Linked"'+
    '                },'+
        '          {'+
            '                    "platformId": "'+platf2.id+'",'+
    '                    "activationKey": "a456",'+
    '                    "licenseStatus": "Activation Key-Linked"'+
    '                }'+
    '            ]'+
    '        }'+
    '    ]'+
    '}';
        RestRequest request = new RestRequest();
        request.requestUri = 'https://hon-aero--apttusdev.my.salesforce.com/services/apexrest/ngbss/licenses';
        request.httpMethod = 'POST';
        //request.addParameter('action', 'reprice');
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf(json);
        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;
        system.debug('response'+response);
        OrderLicenseRestResource.OrderlicensesHeader();
        test.stoptest();
    }
}