src/objects/Apttus_Billing__BillingSchedule__c/Apttus_Billing__BillingSchedule__c.object-meta.xml
<CustomObject>
    <description>Represents a billing schedule for a product or service</description>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{00000000}</displayFormat>
        <label>Schedule Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__BillingSchedule__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The schedule status</description>
    <inlineHelpText>The schedule status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending Milestone</fullName>
            </value>
            <value>
                <fullName>Pending Billing</fullName>
                <default>true</default>
                <label>Pending Billing</label>
            </value>
            <value>
                <fullName>Pending Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoiced Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__CreditMemo__c/Apttus_Billing__CreditMemo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Credit Memo Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__CreditMemo__c/fields/Apttus_Billing__InvoiceID__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__InvoiceID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Invoice ID for which the Credit Memo is created.</description>
    <inlineHelpText>Invoice ID for which this Credit Memo is created.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Billing__CreditMemo__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The Credit Memo Status.</description>
    <inlineHelpText>The Credit Memo Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
            <value>
                <fullName>Draft Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__CreditMemoLineItem__c/Apttus_Billing__CreditMemoLineItem__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Line Item</label>
    <nameField>
        <displayFormat>CMI-{00000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__CreditMemoLineItem__c/fields/Apttus_Billing__BillingScheduleId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillingScheduleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Corresponding Billing Schedule.</description>
    <inlineHelpText>Corresponding Billing Schedule.</inlineHelpText>
    <label>Billing Schedule</label>
    <referenceTo>Apttus_Billing__BillingSchedule__c</referenceTo>
    <relationshipLabel>Credit Memo Line Items</relationshipLabel>
    <relationshipName>CreditMemoLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Billing__CreditMemoLineItem__c/fields/Apttus_Billing__CreditMemoId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__CreditMemoId__c</fullName>
    <description>Parent Credit Memo ID.</description>
    <inlineHelpText>Parent Credit Memo ID.</inlineHelpText>
    <label>Credit Memo</label>
    <referenceTo>Apttus_Billing__CreditMemo__c</referenceTo>
    <relationshipLabel>Credit Memo Line Items</relationshipLabel>
    <relationshipName>CreditMemoLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Apttus_Billing__CreditMemoLineItem__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>Status field for respective line item (Draft/Approved/Cancelled/Draft Obsolete) inherited from Credit Memo Status.</description>
    <inlineHelpText>Lifecycle status of each credit memo Line item.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/Apttus_Billing__Invoice__c.object-meta.xml
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__Invoice__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The invoice status</description>
    <inlineHelpText>The invoice status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
            <value>
                <fullName>Draft Obsolete</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/Apttus_Billing__InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a single item in an invoice</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__BillingScheduleId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillingScheduleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the associated billing schedule</description>
    <inlineHelpText>ID of the associated billing schedule</inlineHelpText>
    <label>Billing Schedule</label>
    <referenceTo>Apttus_Billing__BillingSchedule__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__InvoiceId__c</fullName>
    <description>ID of the associated invoice</description>
    <inlineHelpText>ID of the associated invoice</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The iline item status</description>
    <inlineHelpText>The line item status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/APTS_BillingServiceTest.cls
@isTest
public class APTS_BillingServiceTest {
	@isTest
    public static void testApproveInvoice() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
        	Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        List<Id> invoiceIds = new List<Id>();
        invoiceIds.add(invoice.id);
        APTS_InvoiceActionResult result = APTS_BillingService.approveInvoice(invoiceIds);
        System.assert(result.isSuccess());
        
        invoice = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__Invoice__c Where Id = :invoice.id];
        System.assertEquals('Approved',invoice.Apttus_Billing__Status__c);
    }
    
    @isTest
    public static void testCancelInvoice() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
        	Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        List<Id> invoiceIds = new List<Id>();
        invoiceIds.add(invoice.id);
        APTS_InvoiceActionResult result = APTS_BillingService.cancelInvoice(invoiceIds);
        System.assert(result.isSuccess());
        
        invoice = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__Invoice__c Where Id = :invoice.id];
        System.assertEquals('Cancelled', invoice.Apttus_Billing__Status__c);
    }
    
    @isTest
    public static void testDeleteInvoice() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
        	Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        List<Id> invoiceIds = new List<Id>();
        invoiceIds.add(invoice.id);
        delete invoice;
        APTS_InvoiceActionResult result = APTS_BillingService.approveInvoice(invoiceIds);
        System.assert(!result.isSuccess());
        System.assertEquals('Invoice not found', result.getMessage());
    }

    
    @isTest
    public static void testInvoiceEmptyIdList() {
        APTS_InvoiceActionResult result = APTS_BillingService.cancelInvoice(null);
        System.assert(!result.isSuccess());
        
        List<Id> invoiceIds = new List<Id>();
        result = APTS_BillingService.cancelInvoice(invoiceIds);
        System.assert(!result.isSuccess());
    }
    
    
    @isTest
    public static void testApproveInvoiceLineItem() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
        	Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        List<Id> invoiceIds = new List<Id>();
        invoiceIds.add(invoice.id);
        
        Apttus_Billing__InvoiceLineItem__c invoiceLineItem = new Apttus_Billing__InvoiceLineItem__c(
        	Apttus_Billing__InvoiceId__c = invoice.id
        );
        insert invoiceLineItem;
        
        APTS_InvoiceActionResult result = APTS_BillingService.approveInvoice(invoiceIds);
        System.assert(result.isSuccess());
        
        invoiceLineItem = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__InvoiceLineItem__c Where Id = :invoiceLineItem.id];
		System.assertEquals('Approved', invoiceLineItem.Apttus_Billing__Status__c);
    }
    
    @isTest
    public static void testCancelleInvoiceLineItem() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
        	Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        List<Id> invoiceIds = new List<Id>();
        invoiceIds.add(invoice.id);
        
        Apttus_Billing__InvoiceLineItem__c invoiceLineItem = new Apttus_Billing__InvoiceLineItem__c(
        	Apttus_Billing__InvoiceId__c = invoice.id
        );
        insert invoiceLineItem;
        
        APTS_InvoiceActionResult result = APTS_BillingService.cancelInvoice(invoiceIds);
        System.assertEquals(result.isSuccess(), true);
        
        invoiceLineItem = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__InvoiceLineItem__c Where Id = :invoiceLineItem.id];
		System.assertEquals('Cancelled', invoiceLineItem.Apttus_Billing__Status__c);
    }
    
    
    @isTest
    public static void testApproveInvoiceBillingSchedule() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
        	Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        List<Id> invoiceIds = new List<Id>();
        invoiceIds.add(invoice.id);
        
        Apttus_Billing__BillingSchedule__c billingSchedule = new Apttus_Billing__BillingSchedule__c();
        insert billingSchedule;
        
        Apttus_Billing__InvoiceLineItem__c invoiceLineItem = new Apttus_Billing__InvoiceLineItem__c(
        	Apttus_Billing__InvoiceId__c = invoice.id,
            Apttus_Billing__BillingScheduleId__c = billingSchedule.id
        );
        insert invoiceLineItem;
        
        APTS_InvoiceActionResult result = APTS_BillingService.approveInvoice(invoiceIds);
        System.assertEquals(result.isSuccess(), true);
        
        billingSchedule = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__BillingSchedule__c Where Id = :billingSchedule.id];

        System.assertEquals(billingSchedule.Apttus_Billing__Status__c=='Invoiced', true);
    }
    
    @isTest
    public static void testCancelleInvoiceBillingSchedule() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
        	Apttus_Billing__Status__c = 'Draft'
        );
        insert invoice;
        List<Id> invoiceIds = new List<Id>();
        invoiceIds.add(invoice.id);
        
        Apttus_Billing__BillingSchedule__c billingSchedule = new Apttus_Billing__BillingSchedule__c();
        insert billingSchedule;
        
        Apttus_Billing__InvoiceLineItem__c invoiceLineItem = new Apttus_Billing__InvoiceLineItem__c(
        	Apttus_Billing__InvoiceId__c = invoice.id,
            Apttus_Billing__BillingScheduleId__c = billingSchedule.id
        );
        insert invoiceLineItem;
        
        APTS_InvoiceActionResult result = APTS_BillingService.cancelInvoice(invoiceIds);
        System.assertEquals(result.isSuccess(), true);
        
        billingSchedule = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__BillingSchedule__c Where Id = :billingSchedule.id];
        
        System.assertEquals(billingSchedule.Apttus_Billing__Status__c=='Pending Billing', true);
    }
    
    //----
    @isTest
    public static void testApproveCreditMemo() {
        Apttus_Billing__CreditMemo__c creditMemo = TestDataFactory.createCreditMemo();
        List<Id> creditMemoIds = new List<Id>();
        creditMemoIds.add(creditMemo.id);
        APTS_CreditMemoActionResult result = APTS_BillingService.approveCreditMemo(creditMemoIds);
        System.assertEquals(result.isSuccess(), true);
        
        creditMemo = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__CreditMemo__c Where Id = :creditMemo.id];
        System.assertEquals(creditMemo.Apttus_Billing__Status__c=='Approved', true);
    }
    
    @isTest
    public static void testCancelCreditMemo() {
        Apttus_Billing__CreditMemo__c creditMemo = TestDataFactory.createCreditMemo();
        List<Id> creditMemoIds = new List<Id>();
        creditMemoIds.add(creditMemo.id);
        APTS_CreditMemoActionResult result = APTS_BillingService.cancelCreditMemo(creditMemoIds);
        System.assertEquals(result.isSuccess(), true);
        
        creditMemo = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__CreditMemo__c Where Id = :creditMemo.id];
        System.assertEquals(creditMemo.Apttus_Billing__Status__c=='Cancelled', true);
    }
    
    @isTest
    public static void testDeleteCreditMemo() {
        Apttus_Billing__CreditMemo__c creditMemo = TestDataFactory.createCreditMemo();
        List<Id> creditMemoIds = new List<Id>();
        creditMemoIds.add(creditMemo.id);
        delete creditMemo;
        APTS_CreditMemoActionResult result = APTS_BillingService.approveCreditMemo(creditMemoIds);
        System.assert(!result.isSuccess());
        System.assertEquals('CreditMemo not found', result.getMessage());
    }

    
    @isTest
    public static void testCreditMemoEmptyIdList() {
        APTS_CreditMemoActionResult result = APTS_BillingService.cancelCreditMemo(null);
        System.assertEquals(result.isSuccess(), false);
        
        List<Id> creditMemoIds = new List<Id>();
        result = APTS_BillingService.cancelCreditMemo(creditMemoIds);
        System.assertEquals(result.isSuccess(), false);
    }
    
    
    @isTest
    public static void testApproveCreditMemoLineItem() {
        Apttus_Billing__CreditMemo__c creditMemo = TestDataFactory.createCreditMemo();
        List<Id> creditMemoIds = new List<Id>();
        creditMemoIds.add(creditMemo.id);
        
        Apttus_Billing__CreditMemoLineItem__c creditMemoLineItem = new Apttus_Billing__CreditMemoLineItem__c(
        	Apttus_Billing__CreditMemoId__c = creditMemo.id
        );
        insert creditMemoLineItem;
        
        APTS_CreditMemoActionResult result = APTS_BillingService.approveCreditMemo(creditMemoIds);
        System.assertEquals(result.isSuccess(), true);
        
        creditMemoLineItem = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__CreditMemoLineItem__c Where Id = :creditMemoLineItem.id];
		System.assertEquals(creditMemoLineItem.Apttus_Billing__Status__c=='Approved', true);
    }
    
    @isTest
    public static void testCancelleCreditMemoLineItem() {
        Apttus_Billing__CreditMemo__c creditMemo = TestDataFactory.createCreditMemo();
        List<Id> creditMemoIds = new List<Id>();
        creditMemoIds.add(creditMemo.id);
        
        Apttus_Billing__CreditMemoLineItem__c creditMemoLineItem = new Apttus_Billing__CreditMemoLineItem__c(
        	Apttus_Billing__CreditMemoId__c = creditMemo.id
        );
        insert creditMemoLineItem;
        
        APTS_CreditMemoActionResult result = APTS_BillingService.cancelCreditMemo(creditMemoIds);
        System.assertEquals(result.isSuccess(), true);
        
        creditMemoLineItem = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__CreditMemoLineItem__c Where Id = :creditMemoLineItem.id];
		System.assertEquals(creditMemoLineItem.Apttus_Billing__Status__c=='Cancelled', true);
    }
    
    
    @isTest
    public static void testApproveCreditMemoBillingSchedule() {
        Apttus_Billing__CreditMemo__c creditMemo = TestDataFactory.createCreditMemo();
        List<Id> creditMemoIds = new List<Id>();
        creditMemoIds.add(creditMemo.id);
        
        Apttus_Billing__BillingSchedule__c billingSchedule = new Apttus_Billing__BillingSchedule__c();
        insert billingSchedule;
        
        Apttus_Billing__CreditMemoLineItem__c creditMemoLineItem = new Apttus_Billing__CreditMemoLineItem__c(
        	Apttus_Billing__CreditMemoId__c = creditMemo.id,
            Apttus_Billing__BillingScheduleId__c = billingSchedule.id
        );
        insert creditMemoLineItem;
        
        APTS_CreditMemoActionResult result = APTS_BillingService.approveCreditMemo(creditMemoIds);
        System.assertEquals(result.isSuccess(), true);
        
        billingSchedule = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__BillingSchedule__c Where Id = :billingSchedule.id];

        System.assertEquals(billingSchedule.Apttus_Billing__Status__c=='CreditMemod', true);
    }
    
    @isTest
    public static void testCancelleCreditMemoBillingSchedule() {
        Apttus_Billing__CreditMemo__c creditMemo = TestDataFactory.createCreditMemo();
        List<Id> creditMemoIds = new List<Id>();
        creditMemoIds.add(creditMemo.id);
        
        Apttus_Billing__BillingSchedule__c billingSchedule = new Apttus_Billing__BillingSchedule__c();
        insert billingSchedule;
        
        Apttus_Billing__CreditMemoLineItem__c creditMemoLineItem = new Apttus_Billing__CreditMemoLineItem__c(
        	Apttus_Billing__CreditMemoId__c = creditMemo.id,
            Apttus_Billing__BillingScheduleId__c = billingSchedule.id
        );
        insert creditMemoLineItem;
        
        APTS_CreditMemoActionResult result = APTS_BillingService.cancelCreditMemo(creditMemoIds);
        System.assertEquals(result.isSuccess(), true);
        
        billingSchedule = [Select Id, Apttus_Billing__Status__c From Apttus_Billing__BillingSchedule__c Where Id = :billingSchedule.id];
        
        System.assertEquals(billingSchedule.Apttus_Billing__Status__c=='Pending Billing', true);
    }
}