src/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>SR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>&quot;Open&quot;: Investigation is active or fix is in work.
&quot;Closed&quot;: Issue has been resolved or completed.
&quot;Monitor&quot;: Issue is waiting for additional information from customer or there is a request for issue to be monitored.
&quot;Queue&quot;: SR awaiting to be assigned</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Containment</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>RCCA</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/SRD_Customer_Communication__c/SRD_Customer_Communication__c.object-meta.xml
<CustomObject>
    <description>For monthly updates regarding open SRDs.</description>
    <label>SRD Customer Communication</label>
    <nameField>
        <label>SRD Customer Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRD Customer Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SRD_Customer_Communication__c/fields/Attachment_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Last_Modified__c</fullName>
    <description>User to select date when changes are made to the attachment</description>
    <label>Attachment Last Modified</label>
    <type>DateTime</type>
</CustomField>

src/objects/SRD_Customer_Communication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/Aero_SRDCommunicationReminder_Batch.cls
global class Aero_SRDCommunicationReminder_Batch implements Database.Batchable<sObject>,schedulable{
    global String query;
     
    
    
    global Database.QueryLocator start(Database.BatchableContext bc){ 
        query='select id,Name,Attachment_Last_Modified__c,ownerid,owner.name,owner.email,Status__c from SRD_Customer_Communication__c where Status__c!=\'Closed\' and Attachment_Last_Modified__c!=null and owner.IsActive=true and owner.email!=null';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.batchableContext bc,List<SObject> scope){
        try{
            List<Messaging.SingleEmailMessage> allmails = new List<Messaging.SingleEmailMessage>();
            
            string tempid='';
            string htmlbody='';
            string plainbody='';
            string emailsub='';
            EmailTemplate emp=new EmailTemplate();
            
            for(SObject s:scope){
                SRD_Customer_Communication__c srdcustomer = (SRD_Customer_Communication__c) s;
                DateTime attachdatetime=srdcustomer.Attachment_Last_Modified__c;
                Date myDate = date.newinstance(attachdatetime.year(), attachdatetime.month(), attachdatetime.day());
                Integer daycount= myDate.daysBetween(Date.today());
                system.debug('newdate' +daycount);
                
                tempid=label.Aero_SRDCommunicationReminder_EmailTempID;
                emp=[select id,subject, HtmlValue, Body from EmailTemplate where id=:tempid];
                htmlbody=emp.HtmlValue;
                plainbody=emp.Body;
                emailsub = emp.Subject;
                system.debug('htmlbody is '+htmlbody);
                system.debug('plainbody is '+plainbody);
                
                if(daycount==25){
                    Messaging.SingleEmailMessage mail1=new Messaging.SingleEmailMessage();
                    
                    String[] toAddresses = new String[]{srdcustomer.owner.email};
                    htmlBody = htmlBody.replace('{!days}', '25 days');
                    plainBody = plainBody.replace('{!days}','25 days');
                    htmlBody = htmlBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    plainBody = plainBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    htmlBody = htmlBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    plainBody= plainBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    mail1.setToAddresses(toAddresses);  
                    mail1.setHtmlBody(htmlBody);
                    mail1.setPlainTextBody(plainBody);
                    mail1.setTemplateId(label.Aero_SRDCommunicationReminder_EmailTempID);
                    mail1.setSubject(emailsub);
                    allmails.add(mail1);
                }
                
                if(daycount==28){
                    Messaging.SingleEmailMessage mail2=new Messaging.SingleEmailMessage();
                    
                    String[] toAddresses1 = new String[]{srdcustomer.owner.email};
                    htmlBody = htmlBody.replace('{!days}', '28 days');
                    plainBody = plainBody.replace('{!days}','28 days');  
                    htmlBody = htmlBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    plainBody = plainBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    htmlBody = htmlBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    plainBody= plainBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    mail2.setToAddresses(toAddresses1);
                    mail2.setHtmlBody(htmlBody);
                    mail2.setPlainTextBody(plainBody);
                    mail2.setTemplateId(label.Aero_SRDCommunicationReminder_EmailTempID);
                    mail2.setSubject(emailsub);
                    allmails.add(mail2);
                }
                
                if(daycount==30){
                    Messaging.SingleEmailMessage mail3=new Messaging.SingleEmailMessage();
                    String[] toAddresses2 = new String[]{srdcustomer.owner.email};
                    htmlBody = htmlBody.replace('{!days}', '30 days');
                    plainBody = plainBody.replace('{!days}','30 days'); 
                    htmlBody = htmlBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    plainBody = plainBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    htmlBody = htmlBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    plainBody= plainBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    mail3.setToAddresses(toAddresses2);
                    mail3.setHtmlBody(htmlBody);
                    mail3.setPlainTextBody(plainBody);
                    mail3.setTemplateId(label.Aero_SRDCommunicationReminder_EmailTempID);
                    mail3.setSubject(emailsub);
                    allmails.add(mail3);
                }
                
                if(daycount>30){
                    system.debug('inside more than 30 days execute method');
                    Messaging.SingleEmailMessage mail4=new Messaging.SingleEmailMessage();
                    String[] toAddresses3 = new String[]{srdcustomer.owner.email};
                    htmlBody = htmlBody.replace('{!days}', '30 days');
                    plainBody = plainBody.replace('{!days}','30 days');   
                    htmlBody = htmlBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    plainBody = plainBody.replace('{!Service_Request__c.OwnerFullName}',srdcustomer.owner.Name);
                    htmlBody = htmlBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    plainBody= plainBody.replace('{!SRD_Customer_Communication__c.Name}',srdcustomer.Name);
                    system.debug('owner email is '+srdcustomer.owner.email);
                    list<user> u=new list<user>();
                    u=[select id,email,Manager.email from user where id=:srdcustomer.ownerid and Manager.email!=null and Manager.IsActive=true];
                    if(u.size()>0){
                        for(user usr:u){
                            string mgrmail='';
                            mgrmail=usr.Manager.email; 
                            toAddresses3.add(mgrmail);
                        }
                     }
                     else{
                        system.debug(' no manager found');
                    }   
                        mail4.setToAddresses(toAddresses3);
                        mail4.setHtmlBody(htmlBody);
                        mail4.setPlainTextBody(plainBody);
                        mail4.setTemplateId(label.Aero_SRDCommunicationReminder_EmailTempID);
                        mail4.setSubject(emailsub);
                        allmails.add(mail4);
                    
                    
                }
                
            }
            if(allmails.size()>0){
                Messaging.sendEmail(allmails);
            }
        }
        catch(Exception e){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.subject='SRD Batch Exception';
            mail.htmlbody=e.getMessage() + ' ' + e.getStackTraceString();
            mail.toaddresses=label.email_archival_recipients.split(';');
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
    global void execute(SchedulableContext sc){
        Aero_SRDCommunicationReminder_Batch emailsrdcommreminderbatch = new Aero_SRDCommunicationReminder_Batch();
        database.executeBatch(emailsrdcommreminderbatch,200);
    }
}