src/objects/Apttus_Billing__Invoice__c/Apttus_Billing__Invoice__c.object-meta.xml
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__Invoice__c/fields/APTS_Integration_Method__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Method__c</fullName>
    <label>Integration Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit Memo Request</fullName>
            </value>
            <value>
                <fullName>Simulate Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/fields/APTS_Integration_Result__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Result__c</fullName>
    <label>Integration Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/fields/APTS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Received by External System</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The invoice status</description>
    <inlineHelpText>The invoice status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
            <value>
                <fullName>Draft Obsolete</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/Apttus_Billing__InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <description>Represents a single item in an invoice</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__InvoiceId__c</fullName>
    <description>ID of the associated invoice</description>
    <inlineHelpText>ID of the associated invoice</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Apttus_Billing__InvoiceLineItem__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>The iline item status</description>
    <inlineHelpText>The line item status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__InvoiceRunResult__c/Apttus_Billing__InvoiceRunResult__c.object-meta.xml
<CustomObject>
    <description>Shows the list of invoices created by an associated invoice run.</description>
    <label>Invoice Run Result</label>
    <nameField>
        <label>Invoice Run Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Run Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__InvoiceRunResult__c/fields/Apttus_Billing__Status__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__Status__c</fullName>
    <description>Holds the status of the current scheduled job run.</description>
    <inlineHelpText>Holds the status of the current scheduled job run.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/APTS_OnInvoiceRunCompleteTest.cls
@isTest
public class APTS_OnInvoiceRunCompleteTest {
    @isTest
    public static void testInsert() {
        Apttus_Billing__InvoiceRunResult__c runResult = new Apttus_Billing__InvoiceRunResult__c(
            Apttus_Billing__Status__c = 'Completed'
        );
        insert runResult;
        
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
            Apttus_Billing__InvoiceRunResultId__c = runResult.id
        );
        insert invoice;
        
        invoice = [Select Id, APTS_Integration_Status__c,Apttus_Billing__Status__c, APTS_Integration_Requested__c, APTS_Integration_Result__c, APTS_Integration_Method__c From Apttus_Billing__Invoice__c Where Apttus_Billing__InvoiceRunResultId__c = : runResult.id];
        System.assertEquals(invoice==null, false);
        
        System.assertEquals(invoice.APTS_Integration_Status__c=='To be Processed', false);
        System.assertEquals(invoice.APTS_Integration_Method__c=='Simulate Order', false);
    }
    
    @isTest
    public static void testUpdate() {
        Apttus_Billing__InvoiceRunResult__c runResult = new Apttus_Billing__InvoiceRunResult__c(
            Apttus_Billing__Status__c = 'Completed'
        );
        insert runResult;
        
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
            Apttus_Billing__InvoiceRunResultId__c = runResult.id
        );
        insert invoice;
        
        runResult.Apttus_Billing__Status__c = 'To be Processed';
        update runResult;
        
        invoice = [Select Id, APTS_Integration_Status__c,Apttus_Billing__Status__c, APTS_Integration_Requested__c, APTS_Integration_Result__c, APTS_Integration_Method__c From Apttus_Billing__Invoice__c Where Apttus_Billing__InvoiceRunResultId__c = : runResult.id];
        System.assertEquals(invoice==null, false);
        
        System.assertEquals(invoice.APTS_Integration_Status__c=='To be Processed', false);
        System.assertEquals(invoice.APTS_Integration_Method__c=='Simulate Order', false);
    }
    
    
    @isTest
    public static void testOnEmty() {
        Apttus_Billing__InvoiceRunResult__c runResult = new Apttus_Billing__InvoiceRunResult__c(
            Apttus_Billing__Status__c = null
        );
        insert runResult;
        
        Apttus_Billing__Invoice__c[] invoices  = [Select Id, APTS_Integration_Status__c,Apttus_Billing__Status__c, APTS_Integration_Requested__c, APTS_Integration_Result__c, APTS_Integration_Method__c From Apttus_Billing__Invoice__c Where Apttus_Billing__InvoiceRunResultId__c = : runResult.id];
        System.assertEquals(invoices.isEmpty(), true);
    }
    
    
    @isTest
    public static void testUpdate2() {
        Apttus_Billing__InvoiceRunResult__c runResult = new Apttus_Billing__InvoiceRunResult__c(
            Apttus_Billing__Status__c = null
        );
        insert runResult;
        
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c(
            Apttus_Billing__InvoiceRunResultId__c = runResult.id
        );
        insert invoice;
        
        Apttus_Billing__InvoiceLineItem__c invoiceLineItem = new Apttus_Billing__InvoiceLineItem__c(
            Apttus_Billing__InvoiceId__c = invoice.id
        );
        insert invoiceLineItem;
        
        runResult.Apttus_Billing__Status__c = 'Completed';
        update runResult;
        
        invoice = [Select Id, APTS_Integration_Status__c,Apttus_Billing__Status__c, APTS_Integration_Requested__c, APTS_Integration_Result__c, APTS_Integration_Method__c From Apttus_Billing__Invoice__c Where Apttus_Billing__InvoiceRunResultId__c = : runResult.id];
        System.assert(invoice!=null);
    }
    
}