src/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Invoices related to the Invoice Disputes Case</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Status__c</fullName>
    <label>Deal Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Green [90%]</fullName>
            </value>
            <value>
                <fullName>Yellow [50-89%]</fullName>
            </value>
            <value>
                <fullName>Red [0-49%]</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/HIPI_CONTRACT_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>HIPI_CONTRACT_NUMBER__c</fullName>
    <label>HIPI CONTRACT NUMBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/lic_to_IP_agreements__c.field-meta.xml
<CustomField>
    <fullName>lic_to_IP_agreements__c</fullName>
    <label>SFDC Closed;lic to IP agreements</label>
    <type>Date</type>
</CustomField>

src/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

src/classes/MPMOppupdate.cls
@RestResource(urlMapping='/MPMOppupdate/*')
global with sharing class MPMOppupdate {
    @HttpPost
    global static  List<opportunity> MPMOppupdate(string oppNumber,string Contract,string dealphase,string status,string invoiceno) {           
        List<opportunity> opp=[select id,Opportunity_Number__c,HIPI_CONTRACT_NUMBER__c,Deal_Status__c,stagename,Contract_Number__c,lic_to_IP_agreements__c,Invoice__c from opportunity where Opportunity_Number__c=:oppNumber limit 1];     
        Date today1 = date.valueof(system.today());
        if(
           (Contract != null && Contract != '' && opp[0].HIPI_CONTRACT_NUMBER__c == null ) ||
           (invoiceno != null && invoiceno != '' && opp[0].Invoice__c == null ) ||
           ((dealphase == 'Closed/Won' || dealphase == 'Closed/Lost' || dealphase == 'Closed Won' || dealphase == 'Closed Lost') )
          )
        {
            if((Contract != null && Contract != ''  && opp[0].HIPI_CONTRACT_NUMBER__c == null))
            opp[0].HIPI_CONTRACT_NUMBER__c=Contract;
            if (invoiceno != null && invoiceno != '' && opp[0].Invoice__c == null )
            opp[0].Invoice__c = invoiceno;
            if(dealphase == 'Closed/Won' || dealphase == 'Closed/Lost' || dealphase == 'Closed Won' || dealphase == 'Closed Lost')
            {                       
                if(opp[0].stagename != dealphase)
                {             
                    if(dealphase == 'Closed/Won')
                    {
                         opp[0].stagename= 'Closed Won';
                         opp[0].Deal_Status__c= 'Closed/Won';
                    }
                    if(dealphase == 'Closed/Lost')
                    {
                         opp[0].stagename= 'Closed Lost';
                         opp[0].Deal_Status__c= 'Closed/Lost';
                    }
                    //opp[0].stagename = dealphase;
                }                         
            }
            if(opp[0].lic_to_IP_agreements__c == null){             
                opp[0].lic_to_IP_agreements__c= today1 ;
            }           
            update opp;             
        }                       
        return opp; 
    }  
}