src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <inlineHelpText>Market names to coincide with appropriate SBU (Air Transport and/or Regional Transport, Business and/or General Aviation, etc)</inlineHelpText>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Air Transport</fullName>
            </value>
            <value>
                <fullName>Business Aviation</fullName>
            </value>
            <value>
                <fullName>General Aviation</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Helicopters</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>Non-Aerospace</fullName>
            </value>
            <value>
                <fullName>Regional Transport</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Raw</businessProcess>
        <label>Outbound</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ( NOT 2)</booleanFilter>
        <errorMessage>Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Lead/fields/Account_Address_line_1__c.field-meta.xml
<CustomField>
    <fullName>Account_Address_line_1__c</fullName>
    <label>Account Address line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Lead/fields/Account_City__c.field-meta.xml
<CustomField>
    <fullName>Account_City__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Lead/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Azores, Autonomous Region of</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Lead/fields/Account_Phone__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone__c</fullName>
    <label>Account Phone Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Lead/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Opportunity within partner agreement w/o Offer Support</fullName>
                <default>true</default>
                <label>Opportunity within partner agreement w/o Offer Support</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Lead/fields/Primary_Fax_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Fax_Number__c</fullName>
    <inlineHelpText>ONLY one data point is required to be filled in, more is better</inlineHelpText>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Lead/fields/Primary_Work_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Work_Number__c</fullName>
    <inlineHelpText>ONLY one data point is required to be filled in, more is better</inlineHelpText>
    <label>Primary Work Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Lead/fields/Regional_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Sales_Manager__c</fullName>
    <label>Regional Sales Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC RSM</fullName>
            </value>
            <value>
                <fullName>Ali Sadoudi</fullName>
            </value>
            <value>
                <fullName>Andy Gill</fullName>
            </value>
            <value>
                <fullName>Emil Pope</fullName>
            </value>
            <value>
                <fullName>Frank Muscolino</fullName>
            </value>
            <value>
                <fullName>Paul Ardizzoni</fullName>
            </value>
            <value>
                <fullName>Rishi Singh</fullName>
            </value>
            <value>
                <fullName>Freddie Zonoozi</fullName>
            </value>
            <value>
                <fullName>Roger Dykmann</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/SBU_User__c.field-meta.xml
<CustomField>
    <fullName>SBU_User__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ALT</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>C&amp;PS</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>E&amp;T</fullName>
            </value>
            <value>
                <fullName>EngPS</fullName>
            </value>
            <value>
                <fullName>EngPS BD</fullName>
            </value>
            <value>
                <fullName>EngPS OE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FNCE</fullName>
            </value>
            <value>
                <fullName>FNCE AMER</fullName>
            </value>
            <value>
                <fullName>FNCE APAC</fullName>
            </value>
            <value>
                <fullName>FNCE ELECSOL</fullName>
            </value>
            <value>
                <fullName>FNCE EMEA</fullName>
            </value>
            <value>
                <fullName>FNCE ENGPS</fullName>
            </value>
            <value>
                <fullName>FNCE MECH</fullName>
            </value>
            <value>
                <fullName>FNCE SERVCONN</fullName>
            </value>
            <value>
                <fullName>HBT</fullName>
            </value>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>HOS</fullName>
            </value>
            <value>
                <fullName>HOS CE</fullName>
            </value>
            <value>
                <fullName>HOS CE CRM</fullName>
            </value>
            <value>
                <fullName>HOS CE SO</fullName>
            </value>
            <value>
                <fullName>HOSG</fullName>
            </value>
            <value>
                <fullName>HOS PMO</fullName>
            </value>
            <value>
                <fullName>HOS PRICING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestClass_ApexTrigger_leadconverterror.cls
/** * File Name: TestClass_ApexTrigger_leadconverterror
* Description Test Method
* Copyright : Wipro Technologies Limited Copyright (c) 2010
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
@isTest
private  class TestClass_ApexTrigger_leadconverterror
{
static testmethod void Test_leadconverterror(){

//variable declaration
    Profile pf= [select id from Profile where name = 'System Administrator'];
    User usr = new User(FirstName = 'Test', LastName = 'UserLead',Username = 'testuserlead@test.com',Email = 'testuser@test.com',Alias = 'tuLead' ,CommunityNickname= 'tuld' ,TimeZoneSidKey = 'America/Los_Angeles',LocaleSidKey='en_US',EmailEncodingKey= 'ISO-8859-1',ProfileId = pf.Id, LanguageLocaleKey = 'en_US',SBU_User__c = 'D&S');
    insert usr;

//creating account;
    Account acc= new Account(name='TestLead Account', Market_name__c = 'Military');
    insert acc;

Test.starttest();
    Lead Initiator1 = new Lead(LastName='Test',Account__c=acc.Id,Primary_Fax_Number__c='12345',Company='Test Lead Company', status = 'Qualified', Opportunity_Type__c = 'BGA Aftermarket',Regional_Sales_Manager__c = 'Ali Sadoudi', IsConverted = true, ConvertedAccountID = acc.id, Account_Country__c='India',Account_City__c='Los Angeles',Account_Address_line_1__c='teddy',Primary_Work_Number__c='7572457456',Account_Phone__c='2652490533');
    insert Initiator1;
Test.stopTest();

}// end of method
}// end of class