src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/APTS_Aviaso_Delta_Fleet_Count__c.field-meta.xml
<CustomField>
    <fullName>APTS_Aviaso_Delta_Fleet_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel Efficiency Delta Fleet Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Account/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <description>Business Segment is relabeled as CBT as per Business request.</description>
    <inlineHelpText>A further division into Business Segments within the Strategic Business Unit/Market (e.g., Aftermarket, Airlines, Military/Operators, etc.)</inlineHelpText>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES CBT</fullName>
            </value>
            <value>
                <fullName>DEW</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
                <label>Embraer D&amp;S</label>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/CBT_Team__c.field-meta.xml
<CustomField>
    <fullName>CBT_Team__c</fullName>
    <label>CBT Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CBT__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACST</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>AES: Advanced Electronics &amp; Services</fullName>
            </value>
            <value>
                <fullName>Airbus Companies</fullName>
            </value>
            <value>
                <fullName>Airbus Defense &amp; Space</fullName>
            </value>
            <value>
                <fullName>Airbus Helicopters</fullName>
            </value>
            <value>
                <fullName>AMCOM/SOCOM/CECOM</fullName>
            </value>
            <value>
                <fullName>AM Partners Defense (AMPD)</fullName>
            </value>
            <value>
                <fullName>AMS: Advanced Mechanical &amp; Services</fullName>
            </value>
            <value>
                <fullName>APAC BGA</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>APEX Non-EMEA</fullName>
            </value>
            <value>
                <fullName>ASM: Advanced Sensors &amp; Microsystems</fullName>
            </value>
            <value>
                <fullName>ATE: Advanced Technology Europe</fullName>
            </value>
            <value>
                <fullName>ATR Airlines Americas</fullName>
            </value>
            <value>
                <fullName>ATR Airlines Asia Pacific</fullName>
            </value>
            <value>
                <fullName>ATR Airlines EMEAI</fullName>
            </value>
            <value>
                <fullName>ATR Airlines Other</fullName>
            </value>
            <value>
                <fullName>ATR Other</fullName>
            </value>
            <value>
                <fullName>Australasia Defense</fullName>
            </value>
            <value>
                <fullName>AVCC</fullName>
            </value>
            <value>
                <fullName>Avions de Transport Regional</fullName>
            </value>
            <value>
                <fullName>BAAPAC</fullName>
            </value>
            <value>
                <fullName>Bendix King</fullName>
            </value>
            <value>
                <fullName>BGA Other</fullName>
            </value>
            <value>
                <fullName>Boeing/Intl</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>C&amp;PS AERO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU_Contact__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S Other CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
            <value>
                <fullName>General Atomics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Is_Portal_Super_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Portal_Super_User__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Defines if the current Contact is a Portal Super User.</inlineHelpText>
    <label>Is Portal Super User</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Contact/fields/SBU_Contact__c.field-meta.xml
<CustomField>
    <fullName>SBU_Contact__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>Stores feedback data from various surveys</description>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FEE-{0}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback__c/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <formula>TEXT(Account__r.CBT__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CBT</label>
    <type>Text</type>
</CustomField>

src/objects/Feedback__c/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <formula>TEXT( Contact__r.Contact_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Status</label>
    <type>Text</type>
</CustomField>

src/classes/MyAerospacePortalSurveyTest.cls
@isTest
public class MyAerospacePortalSurveyTest {
    @testSetup static void methodName() {
        Account acc = new Account();
        acc.Name = 'testAcc';
        acc.Type = 'Air Cargo Transporter';
        acc.APTS_Aviaso_Delta_Fleet_Count__c = 10;
        insert acc;        
        
        Contact con = new Contact();
        con.Is_Portal_Super_User__c = true;
        con.Contact_Status__c = 'Active';
        con.Primary_Email_Address__c = 'test@gmail.com';
        con.LastName = 'test';
        con.SBU_Contact__c = 'BGA';
        con.CBT__c='BGA Aftermarket';
        con.CBT_Team__c ='OEM & Dealers';
        con.Sales_Channel_Contact__c= 'Americas AM';
        con.Contact_Function__c = 'Maintenance';
        con.AccountId = acc.Id;        
        insert con;
    }
    
    @isTest static void testmethod1(){
        Test.startTest();
            Test.setCurrentPageReference(new pageReference('Page.MyAerospacePortalSurvey'));
            System.currentPageReference().getParameters().put('sonumber', '123');
            System.currentPageReference().getParameters().put('email', 'test@gmail.com');
            MyAerospacePortalSurvey ctrl = new MyAerospacePortalSurvey();
        	ctrl.feeedback.CES_Score__c = 8;
            ctrl.feeedback.FCR__c = 8;
        	ctrl.submitFeedback();
        Test.stopTest();
    }
    
    @isTest static void testmethod2(){
        Feedback__c fback = new Feedback__c();
        fback.Interviewer_Name__c = UserInfo.getUserId();
        fback.Order_Number__c = '123';
        fback.CES_Score__c = 8;
        fback.FCR__c = 8;
        insert fback;
        Test.startTest();
            Test.setCurrentPageReference(new pageReference('Page.MyAerospacePortalSurvey'));
            System.currentPageReference().getParameters().put('sonumber', '123');
            System.currentPageReference().getParameters().put('email', 'test@gmail.com');
            MyAerospacePortalSurvey ctrl = new MyAerospacePortalSurvey();
        Test.stopTest();
    }
    
    @isTest static void testmethod3(){
        Test.startTest();
            Test.setCurrentPageReference(new pageReference('Page.MyAerospacePortalSurvey'));
            System.currentPageReference().getParameters().put('email', 'test@gmail.com');
            MyAerospacePortalSurvey ctrl = new MyAerospacePortalSurvey();
        Test.stopTest();
    }
}