src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/SPoG_Case_Status__mdt/SPoG_Case_Status__mdt.object-meta.xml
<CustomObject>
    <description>For Spog Custom Service console case status types</description>
    <label>SPoG Case Status</label>
    <pluralLabel>SPoG Case Status</pluralLabel>
</CustomObject>

src/objects/SPoG_General_Settings__mdt/SPoG_General_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Custom List Meta data to store the SAP System information &amp; APIGEE connection information</description>
    <label>SPoG General Setting</label>
    <pluralLabel>SPoG General Settings</pluralLabel>
</CustomObject>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Access_Token_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Access_Token_Client_Id__c</fullName>
    <label>APIGEE Access Token Client Id</label>
    <type>TextArea</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Access_Token_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Access_Token_Client_Secret__c</fullName>
    <label>APIGEE Access Token Client Secret</label>
    <type>TextArea</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Access_Token_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Access_Token_Path__c</fullName>
    <label>APIGEE Access Token Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Attachment_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Attachment_Path__c</fullName>
    <label>APIGEE Attachment Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Claims_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Claims_Path__c</fullName>
    <label>APIGEE Claims Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Client_ID__c</fullName>
    <inlineHelpText>APIGEE Client ID</inlineHelpText>
    <label>APIGEE Client ID</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Client_Secret__c</fullName>
    <label>APIGEE Client Secret</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Customer_Search_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Customer_Search_Path__c</fullName>
    <label>APIGEE Customer Search Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Delivery_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Delivery_Path__c</fullName>
    <label>APIGEE Delivery Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Order_Details_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Order_Details_Path__c</fullName>
    <label>APIGEE Order Details Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Order_Metric_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Order_Metric_Path__c</fullName>
    <label>APIGEE Order Metric Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Order_Summary_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Order_Summary_Path__c</fullName>
    <label>APIGEE Order Summary Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Pricing_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Pricing_Path__c</fullName>
    <label>APIGEE Pricing Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Search_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Search_Path__c</fullName>
    <label>APIGEE Search Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Shipment_Metric_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Shipment_Metric_Path__c</fullName>
    <label>APIGEE Shipment Metric Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Stocks_Overview_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Stocks_Overview_Path__c</fullName>
    <label>APIGEE Stocks Overview Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_Stocks_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_Stocks_Path__c</fullName>
    <label>APIGEE Stocks Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/APIGEE_UserStatus_Path__c.field-meta.xml
<CustomField>
    <fullName>APIGEE_UserStatus_Path__c</fullName>
    <label>APIGEE UserStatus Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/SAP_Client_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Client_Number__c</fullName>
    <inlineHelpText>Enter SAP Client Number eg: 900</inlineHelpText>
    <label>SAP Client Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/SPoG_General_Settings__mdt/fields/SAP_Source_System__c.field-meta.xml
<CustomField>
    <fullName>SAP_Source_System__c</fullName>
    <inlineHelpText>Enter the SAP Source System Name , eg: CIP</inlineHelpText>
    <label>SAP Source System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/SPoG_Utility.cls
/*****************************************************
 * @Description: 
 * ****************************************************/
public with Sharing class SPoG_Utility {
    
    // For pilot , PMT_AM is fixed, but this should change based on Order/Customer for which
    // the information needs to be retrieved. Setting contains information for SAP Source System & Client Number  
    private static final String GENERAL_SETTING = 'AERO';
    public final String TYPE_PO_NUMBER = 'PO_NUMBER'; 
    public final String TYPE_CUSTOMER_NUMBER = 'SOLD_TO_NUMBER';
    public final String TYPE_SALES_ORDER = 'SALES_ORDER_NUMBER'; 
    public final String TYPE_MAT_NUMBER = 'MATERIAL_NUMBER';
    public final String TYPE_DELIVERY_NUMBER = 'DELIVERY_NUMBER'; 
    
    
    public Id getClaimCaseRecordTypeId() {
        Id returnValue = null ; 
        List<RecordType> lstRecordType = [SELECT id,DeveloperName
                                         FROM RecordType 
                                         WHERE sObjectType = 'Case'
                                         AND DeveloperName = 'Consumer_Support'
                                         LIMIT 1];
        if(!lstRecordType.isEmpty()){
            returnValue = lstRecordType[0].Id ; 
        }
        return returnValue ; 
    }
    
    /**********************************************************
     * @Descrpition : Utility method to parse and display date
     * fields
     * ********************************************************/
    public String parseDateForOutput(String inputValue){
        
        if(String.isNotBlank(inputValue)) {
            String year = inputValue.substring(0, 4) ; 
            String month = inputValue.substring(4,6) ; 
            String dateValue =inputValue.substring(6,8) ;
            inputValue = month+'/'+dateValue+'/'+year ;
        }
        
        return inputValue ; 
    }
    
    /**********************************************************
     * @Descrpition : Utility method to parse and display date
     * fields
     * ********************************************************/
    public String parseDateForInput(String inputValue) {
        
        if(String.isNotBlank(inputValue)){
            inputValue = inputValue.replaceAll('-', ''); 
        }
        
        return inputvalue ;
    }
    
    
    /********************************************************
     * @Description : Method to get Customer Ids associated to Service Agent
     * 
     * *******************************************************/
    public List<Account> getMyCustomers(String searchInput) {
        Set<Id> setAccountIds = new Set<Id>(); 
        SPoG_Utility objUtility = new SPoG_Utility(); 
        List<Account> lstResults = new List<Account>(); 
        for(Case objCase : objUtility.getCases()) {
            setAccountIds.add(objCase.AccountId); 
        }
        if(!setAccountIds.isEmpty()) {
            lstResults = [SELECT id , Name , AccountNumber 
                          FROM Account WHERE ID IN: setAccountIds 
                          LIMIT : (Limits.getLimitQueryRows() - Limits.getQueryRows()) ]; 
        }
        return lstResults ; 
    }
    
    /********************************************************
     * @Description : Method to retrieve open cases for the current user
     * ******************************************************/
    public List<Case> getCases(){
        Set<Id> setOwnerIds = new Set<Id>(); 
        setOwnerIds.add(UserInfo.getUserId()); 
        List<Case> lstCases = new List<Case>();
        List<String> Rectyp = new List<String>();
        Rectyp =System.Label.spog_Case_RecordTypes.Split(',');
                    
        List<String> caseStatus = new List<String>();
        for(SPoG_Case_Status__mdt status : [SELECT MasterLabel FROM SPoG_Case_Status__mdt]) {
        caseStatus.add(status.MasterLabel);
        }
        
        lstCases = [SELECT id , AccountId FROM Case 
                    WHERE OwnerId IN :setOwnerIds 
                    AND IsClosed = FALSE 
                    AND RecordType.DeveloperName IN :Rectyp
                    AND Status IN : caseStatus
                    LIMIT : (Limits.getLimitQueryRows() - Limits.getQueryRows())]; 
        return lstCases ; 
    }
    
    /*************************************************************
     * @Description : Method to get the Sales Office information
     * configured on User record
     * ************************************************************/
    public String getCurrentUserInfo() {
        OptionsInfo objOption = new OptionsInfo(); 
        List<OptionsInfo> lstOptions = new List<OptionsInfo>(); 
        
        OP_UserInfo objResponse = new OP_UserInfo(); 
        
        List<User> lstCurrentUser = [SELECT Id //, SPoG_Sales_Office__c 
                                     FROM User WHERE Id =: UserInfo.getUserId() 
                                     LIMIT 1]; 
        /*if(!lstCurrentUser.isEmpty() && String.isNotBlank(lstCurrentUser[0].SPoG_Sales_Office__c)) {
            for(String salesOffice : lstCurrentUser[0].SPoG_Sales_Office__c.split(',') ){
                objOption = new OptionsInfo();
                objOption.label = salesOffice ; 
                objOption.value = salesOffice ; 
                lstOptions.add(objOption);
            }*/
            objResponse.isSuccess = true ; 
            //objResponse.salesOffices = lstOptions; 
       // }
        
        return JSON.serialize(objResponse) ; 
    }
    
    public String addPrefix(String inputValue , String inputType) {
        String paddingValue = '';
        Integer paddingIterations = 0 ; 
        if(String.isNotBlank(inputValue) && String.isNotBlank(inputType)) {
            if(TYPE_PO_NUMBER.equalsIgnoreCase(inputType) && inputValue.length() <20) {
                paddingIterations = 20 - inputValue.length() ; 
            }
            else if(TYPE_MAT_NUMBER.equalsIgnoreCase(inputType) && inputValue.length() <18) {
                paddingIterations = 18 - inputValue.length(); 
            }
            else if(TYPE_SALES_ORDER.equalsIgnoreCase(inputType) && inputValue.length() < 10) {
                paddingIterations = 10 - inputValue.length(); 
            }
            else if(TYPE_CUSTOMER_NUMBER.equalsIgnoreCase(inputType) && inputValue.length() < 10) {
                paddingIterations = 10 - inputValue.length(); 
            }
            else if(TYPE_DELIVERY_NUMBER.equalsIgnoreCase(inputType) && inputValue.length() < 10) {
                paddingIterations = 10 - inputValue.length(); 
            }
        }
        for(Integer i = 0 ; i < paddingIterations ; i++){
            paddingValue+='0'; 
        }
        inputValue = paddingValue+inputValue; 
        return inputValue ; 
    }
    
    public SPoG_General_Settings__mdt getSystemSetting() {
        
        return [SELECT id , APIGEE_Client_ID__c, APIGEE_Client_Secret__c ,
                SAP_Client_Number__c , SAP_Source_System__c,
                APIGEE_Attachment_Path__c , APIGEE_Claims_Path__c , 
                APIGEE_Customer_Search_Path__c , APIGEE_Delivery_Path__c , 
                APIGEE_Order_Details_Path__c , APIGEE_Order_Metric_Path__c , 
                APIGEE_Order_Summary_Path__c, APIGEE_Pricing_Path__c , APIGEE_Shipment_Metric_Path__c,
                APIGEE_Access_Token_Client_Id__c,APIGEE_Access_Token_Client_Secret__c,APIGEE_Access_Token_Path__c,
                APIGEE_Stocks_Path__c,APIGEE_Stocks_Overview_Path__c, APIGEE_Search_Path__c,
                APIGEE_UserStatus_Path__c
                FROM SPoG_General_Settings__mdt WHERE DeveloperName =: GENERAL_SETTING
                LIMIT 1];
    }
    
    private with Sharing Class OP_UserInfo {
        Boolean isSuccess = false ; 
        List<OptionsInfo> salesOffices = new List<OptionsInfo>(); 
    }
    
    private with Sharing Class OptionsInfo {
        String label ; 
        String value ;
    }

}