src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/GoDirect_View__c.field-meta.xml
<CustomField>
    <fullName>GoDirect_View__c</fullName>
    <label>GoDirect View</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HAPP/MPP Dealer</fullName>
            </value>
            <value>
                <fullName>Management Company</fullName>
            </value>
            <value>
                <fullName>Non Management Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account_Email_Domains__c/Account_Email_Domains__c.object-meta.xml
<CustomObject>
    <label>Web Portal Account Email Domains</label>
    <nameField>
        <label>Account Email Domains Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Portal Account Email Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Email_Domains__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ( NOT 2)</booleanFilter>
        <errorMessage>Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Web Portal Account Email Domains</relationshipLabel>
    <relationshipName>Account_Email_Domains</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account_Email_Domains__c/fields/Account_Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Email_Domain__c</fullName>
    <label>Account Email Domain</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <description>Access level to aircrafts</description>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/All_Aircrafts__c.field-meta.xml
<CustomField>
    <fullName>All_Aircrafts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check for user&apos;s access to all aircrafts</description>
    <label>All Aircrafts</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Assigned_Aircrafts__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Aircrafts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check for user&apos;s assigned aircrafts</description>
    <label>Assigned Aircrafts</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Has_Restriction__c.field-meta.xml
<CustomField>
    <fullName>Has_Restriction__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check for user&apos;s restriction to aircrafts</description>
    <label>Has Restriction</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Is_Portal_Super_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Portal_Super_User__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Defines if the current Contact is a Portal Super User.</inlineHelpText>
    <label>Is Portal Super User</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Portal_Honeywell_ID__c/Portal_Honeywell_ID__c.object-meta.xml
<CustomObject>
    <label>Web Portal Honeywell ID</label>
    <nameField>
        <label>Portal Honeywell ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Portal Honeywell ID</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Honeywell_ID__c/fields/account_name__c.field-meta.xml
<CustomField>
    <fullName>account_name__c</fullName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Portal_Honeywell_ID__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Contact Status should not be inactive</errorMessage>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Web Portal Honeywell ID (Contact)</relationshipLabel>
    <relationshipName>Portal_Honeywell_ID</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Portal_Honeywell_ID__c/fields/Portal_Status__c.field-meta.xml
<CustomField>
    <fullName>Portal_Status__c</fullName>
    <description>This field is used by Customer Registration 2 project</description>
    <label>Portal_Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Portal_Honeywell_ID__c/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/REG_SuperUser.cls
/** * File Name: REG_SuperUser

* Description  Service class for Super User API

* * @author : TCS 

Date 01/16/2019 

* */
public with sharing class REG_SuperUser {
    
    /**
*Method used to fetch super user and contacts related to super user
**/
    public static REG_Result getSuperUserDetail(string honId){
        
        string contact_ID = '';
        List<contact> conList = new List<contact>();
        List<Portal_Honeywell_ID__c> conListSuperUser = new List<Portal_Honeywell_ID__c>();
        List<account> AccountList1 = new List<account>();
        List<REG_PortalUser_Wrapper> wrapperList = new List<REG_PortalUser_Wrapper  >();
        List<REG_PortalUser_Wrapper> wrapperListIden = new List<REG_PortalUser_Wrapper  >();
        REG_Result result = new REG_Result();
        //to find if honid is associated to any contact
        contact_ID = REG_PortalContact_Service.getContact(honId);
        if(string.isBlank(contact_ID)){
            
            result.handleError(404, 'Contact details not found for the given honeywell id', 'Please provide a valid honeywell id.');
            return result;
        }        
        //to find if user is super user
        conList = [SELECT Id,Honeywell_ID__c,Primary_Email_Address__c,Is_Portal_Super_User__c,Account_Name__c,account.GoDirect_View__c 
                   FROM Contact WHERE Id IN (SELECT Contact__c FROM Portal_Honeywell_ID__c WHERE Name =: honId) AND Is_Portal_Super_User__c = true ];       
        //system.debug(logginglevel.info,'conList[0]' +conList[0]);
        if(conList.isEmpty()){
            result.handleError(400, 'Provided honeywell Id is not a super user', 'Provided honeywell Id is not a super user');    
            return result;
        }else{
            String emailId = conList[0].Primary_Email_Address__c;
            String domain = emailId.substring(emailId.lastIndexOf('@') +1);
            //flowVars.superUser.Account.GoDirect_View__c when flowVars.superUser.Account.GoDirect_View__c != null otherwise p('user.manage.godirect.view')
            string company = !string.isBlank(conList[0].account.GoDirect_View__c) ? conList[0].account.GoDirect_View__c : system.label.REG_user_manage_godirect_view;
            //to find the contacts associated to super user, by using the domain of super user 
            AccountList1 = [select id from account where customer_status__c= 'active' and id IN (select account__c from account_email_domains__c where account_email_domain__c=: domain) and name NOT IN ('HONEYWELL UNIDENTIFIED PORTAL USERS','Bendix King UNIDENTIFIED PORTAL USERS','Honeywell Default Account','NO ACCOUNT FOUND','FSR TEMPORARY OPERATOR','Portal Missing Users (Do not use)') and (not name like '%Various%')];
            //system.debug('AccountList1'+AccountList1);  
            
            for(Portal_Honeywell_ID__c phid : [select contact__r.firstname,Contact__r.lastname,Contact__r.primary_email_address__c,name,Contact__r.Account_Name__c,portal_status__c, contact__r.Access__c,contact__r.All_Aircrafts__c, contact__r.Assigned_Aircrafts__c, contact__r.Has_Restriction__c,contact__r.Is_Portal_Super_User__c,contact__c from Portal_Honeywell_ID__c where  Portal_Status__c not in ('Deleted') and Contact__r.accountId in :AccountList1]){
                
                REG_PortalUser_Wrapper  porUserWrapper = new REG_PortalUser_Wrapper(phid, conList[0].Account_Name__c, company); 
                if(conList[0].Account_Name__c == phid.Contact__r.Account_Name__c ){
                    wrapperListIden.add(porUserWrapper);
                    //system.debug(logginglevel.info,'wrapperListIden' +wrapperListIden);
                }else
                    if(conList[0].Account_Name__c != phid.Contact__r.Account_Name__c){
                        wrapperList.add(porUserWrapper);
                        //system.debug(logginglevel.info,'wrapperList' +wrapperList);
                    }
                
            }
            wrapperListIden.addAll(wrapperList);
            //system.debug(logginglevel.info,'wrapperListIden1' +wrapperListIden);                 
            result.data = wrapperListIden;
        }
        return result;
    }
}