src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Asia and Japan</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Account/fields/External_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Account_Name__c</fullName>
    <description>Created for INC000008923162</description>
    <label>External Account Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Sbl_Account_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Sbl Account Row ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account_Cross_Ref__c/Account_Cross_Ref__c.object-meta.xml
<CustomObject>
    <label>Account Cross Ref</label>
    <nameField>
        <label>Account Cross Ref Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Cross Ref</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Cross_Ref__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Account Status should not be inactive</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Cross Ref</relationshipLabel>
    <relationshipName>Account_Cross_Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT( Account_Name__r.Customer_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Defines the Account Status as defined within the Account entry.</inlineHelpText>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Account_ID__c</fullName>
    <inlineHelpText>Defines the External unique ID for this Account Cross Reference.</inlineHelpText>
    <label>External  Account ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Account_Name__c</fullName>
    <inlineHelpText>Defines the External Account Name for this Account Cross Reference.</inlineHelpText>
    <label>External Account Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>External_Address_Line_1__c</fullName>
    <inlineHelpText>Defines the External Account Address Line 1 for this Account Cross Reference.</inlineHelpText>
    <label>External Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>External_Address_Line_2__c</fullName>
    <inlineHelpText>Defines the External Account Address Line 2 for this Account Cross Reference.</inlineHelpText>
    <label>External Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>External_Address_Line_3__c</fullName>
    <inlineHelpText>Defines the External Account Address Line 3 for this Account Cross Reference.</inlineHelpText>
    <label>External Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_City_Name__c.field-meta.xml
<CustomField>
    <fullName>External_City_Name__c</fullName>
    <inlineHelpText>Defines the External Account City Name for this Account Cross Reference.</inlineHelpText>
    <label>External City Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Country_Name__c</fullName>
    <inlineHelpText>Defines the External Account Country Name for this Account Cross Reference.</inlineHelpText>
    <label>External Country Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/Sbl_Account_Row_ID__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_ID__c</fullName>
    <label>Sbl Account Row ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/XREF_Type__c.field-meta.xml
<CustomField>
    <fullName>XREF_Type__c</fullName>
    <inlineHelpText>Defines the Account Cross Reference Type Code for this Account Cross Reference.</inlineHelpText>
    <label>XREF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTUAL_REVENUES</fullName>
            </value>
            <value>
                <fullName>ASA_CUSTOMER_XREF</fullName>
            </value>
            <value>
                <fullName>ASA_VOC_CARD</fullName>
            </value>
            <value>
                <fullName>ASA_VOC_CARD_CONTACT</fullName>
            </value>
            <value>
                <fullName>ASA_VOC_CARD_SR</fullName>
            </value>
            <value>
                <fullName>BIZVIEW_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>BMS_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>NonSAP_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>SAP_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>SIMS_SOLD_TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Customer_PO_RO_WONumber__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_RO_WONumber__c</fullName>
    <description>Text Field used to hold the PO number. 
05/22 - Set to external ID for PO/SN deployment to avoid 554 connection error in Salesforce</description>
    <externalId>true</externalId>
    <label>Customer PO/RO/WO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>Text(Account.Region_Name__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Name</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Repair_Notification_Number__c.field-meta.xml
<CustomField>
    <fullName>Repair_Notification_Number__c</fullName>
    <externalId>true</externalId>
    <label>Repair Notification Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/SAP_Account_Number1__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number1__c</fullName>
    <formula>IF(CONTAINS(SAP_Account_Number__r.External_Account_ID__c, &apos;-&apos;), LEFT(SAP_Account_Number__r.External_Account_ID__c, LEN(SAP_Account_Number__r.External_Account_ID__c)-3),SAP_Account_Number__r.External_Account_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Account Number</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Sbl_Account_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_Id__c</fullName>
    <label>Sbl Account Row Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/SPoG_MyCustomerHelper.cls
/********************************************************
* @Description : Apex Class to retrieve the customer information
* for the current user. 
* ******************************************************/
public with Sharing class SPoG_MyCustomerHelper {
    /**************************************************************
     * @Description: Method to get All SFDC Accounts 
     * ***********************************************************/
    public String getSFDCAccountInfo(String searchString, List<String> selData){
        AccountInfo results = new AccountInfo();
        try{
            List<Option> options = new List<Option>();
            Map<String,AccountData> accountdata = new Map<String,AccountData>();
            String query = 'select sbl_account_row_id__c,external_account_id__c,external_account_name__c, external_address_line_1__c, external_address_line_2__c,external_address_line_3__c, external_city_name__c, external_country_name__c, id FROM Account_Cross_Ref__c ';
            if(selData != null && selData.size()>0){
                String query1 = query+' WHERE ID IN :selData Order By external_account_name__c ASC ';
                for(Account_Cross_Ref__c each_acc : DataBase.query(query1)){
                    options.add(new Option(each_acc.external_account_name__c!=null?each_acc.external_account_name__c.toUpperCase():'',each_acc.external_account_id__c!=null?each_acc.external_account_id__c.replace('-01',''):'',each_acc.Id,true));
                    String address = each_acc.external_address_line_1__c!=null?each_acc.external_address_line_1__c+',':'';
                    address += each_acc.external_address_line_2__c!=null?each_acc.external_address_line_2__c+',':'';
                    address += each_acc.external_address_line_3__c!=null?each_acc.external_address_line_3__c+',':'';
                    address += each_acc.external_city_name__c!=null?each_acc.external_city_name__c+',':'';
                    address += each_acc.external_country_name__c!=null?each_acc.external_country_name__c:'';
                    accountdata.put(each_acc.Id,new AccountData(each_acc.external_account_name__c,each_acc.external_account_id__c!=null?each_acc.external_account_id__c.replace('-01',''):'',each_acc.Sbl_Account_Row_Id__c,address));
            	}
            }
            query += ' where (((not external_account_name__c like \'%do not use%\') and (not external_account_name__c like \'%reference account%\') and (not external_account_name__c like \'%various%\') and (not account_name__r.name like \'%various%\') and (not external_account_id__c like \'%-02\' ))  and (external_account_name__c !=\'\' and account_status__c=\'active\' and xref_type__c = \'SAP_SOLD_TO\')) ';
            if(String.isNotEmpty(searchString)){
                query += ' AND ( external_account_name__c LIKE \''+searchString+'%\' ) ';
            }
            query += ' Order By external_account_name__c ASC LIMIT 50 ';
            Set<String> setseldata = new Set<String>(selData);
            for(Account_Cross_Ref__c each_acc : DataBase.query(query)){
                if(!setseldata.contains(each_acc.Id)){
                    options.add(new Option(each_acc.external_account_name__c!=null?each_acc.external_account_name__c.toUpperCase():'',each_acc.external_account_id__c!=null?each_acc.external_account_id__c.replace('-01',''):'',each_acc.Id,false));
                    String address = each_acc.external_address_line_1__c!=null?each_acc.external_address_line_1__c+',':'';
                    address += each_acc.external_address_line_2__c!=null?each_acc.external_address_line_2__c+',':'';
                    address += each_acc.external_address_line_3__c!=null?each_acc.external_address_line_3__c+',':'';
                    address += each_acc.external_city_name__c!=null?each_acc.external_city_name__c+',':'';
                    address += each_acc.external_country_name__c!=null?each_acc.external_country_name__c:'';
                    accountdata.put(each_acc.Id,new AccountData(each_acc.external_account_name__c,each_acc.external_account_id__c!=null?each_acc.external_account_id__c.replace('-01',''):'',each_acc.Sbl_Account_Row_Id__c,address));
                }
            }
            results.count		 = options.size();
            results.message      = 'Success';
            results.isSuccess    = true;
            results.options      = options;
            results.accountdata  = accountdata;
        }catch(Exception ex){
            results.message   = ex.getMessage();
            results.isSuccess = false;
        }
        return JSON.serialize(results);
    }
    public class AccountInfo{
        public Integer count;
        public string message;
        public Boolean isSuccess;
        public List<Option> options;
        public Map<String,AccountData> accountdata;
    }
    public class AccountData{
        public String acc_name;
        public string soldto;
        public string crmid;
        public string address;
        public AccountData(String acc_name,string soldto,string crmid,string address){
            this.acc_name = acc_name;
            this.soldto   = soldto;
            this.crmid    = crmid;
            this.address  = address;
        }
    }
    public class Option{
        public string label;
        public string sublabel;
        public string value;
        public Boolean selected;
        public Option(string label,string sublabel,string value,Boolean selected){
            this.label = label;
            this.sublabel = sublabel;
            this.value = value;
            this.selected = selected;
        }
    }
    /**************************************************************
     * @Description: Method to get the SAP information from a 
     * case. 
     * ***********************************************************/
    public String getSAPInfo(Map<String , Object> mapInputRequest){
        Id caseId = (Id) mapInputRequest.get('caseId'); 
        SAPInfo objResult = new SAPInfo(); 
        if(caseId != null) { 
            List<Case> lstCurrentCase = [SELECT id,CaseNumber,SAP_Account_Number1__c,
                                         Customer_PO_RO_WONumber__c,Repair_Notification_Number__c,
                                         Sales_Order_Number__c
                                         FROM Case WHERE Id =: caseId
                                         LIMIT 1
                                        ];
            if(!lstCurrentCase.isEmpty()){
                objResult.isSuccess = true ; 
                objResult.message = 'Success';
                objResult.custNO = lstCurrentCase[0].SAP_Account_Number1__c!=null?lstCurrentCase[0].SAP_Account_Number1__c:''; 
                objResult.caseNumber = lstCurrentCase[0].CaseNumber.containsIgnoreCase('CASE-')?lstCurrentCase[0].CaseNumber.split('CASE-')[1]:lstCurrentCase[0].CaseNumber; 
                objResult.orderNO = lstCurrentCase[0].Sales_Order_Number__c!=null?lstCurrentCase[0].Sales_Order_Number__c:''; 
                objResult.custPO = lstCurrentCase[0].Customer_PO_RO_WONumber__c!=null?lstCurrentCase[0].Customer_PO_RO_WONumber__c:'';
            }
        }
        return JSON.serialize(objResult) ; 
    }
    
    public with Sharing Class SAPInfo {
        Boolean isSuccess = false ; 
        String message = '';
        String custNO = '' ; 
        String caseNumber = '' ; 
        String orderNO = '' ; 
        String custPO = '';
    }

    /*******************************************************
* @Description : Method to get customer for the current user. 
* ******************************************************/
    public String getCustomerInfo(Map<String , Object> mapInputRequest){
        String result ;
        SPoG_Utility objUtility = new SPoG_Utility(); 
        //ResponseCustomerInfo objResult = new ResponseCustomerInfo(); 
        List<Account> lstAccounts = objUtility.getMyCustomers(null); 
        List<CustomerInfo> objResult = new List<CustomerInfo>();
        for(Account objAccount : lstAccounts) {
            objResult.add(new CustomerInfo(objAccount.Id , objAccount.Name.toUpperCase())); 
        }
        result = JSON.serialize(objResult); 
        return result ; 
    }
    
    /**************************************************************
*@Description: Method to send the search key to SAP HANA, to get the
customer search results. 
* ************************************************************/
    public String doCustomerSearch(Map<String,Object> mapInputRequest) {
        //add search input headers
        Map<String,String> mapSearchInputs = addInputHeader(mapInputRequest); 
        SPoG_InterfaceHelper objHelper = new SPoG_InterfaceHelper(); 
        HttpResponse objHttpResponse = objHelper.getSearchResult(mapSearchInputs); 
        
        return objHttpResponse.getBody() ; 
    }
    
    /*************************************************************
* 
* 
* ***********************************************************/
    private Map<String,String> addInputHeader(Map<String,Object> mapInputRequest) {
       
         String searchByDChnl = (String) mapInputRequest.get('searchByDChnl'); 
         String soldToName = (String) mapInputRequest.get('soldToName'); 
        system.debug('soldToName::::::'+soldToName);
         String soldToNumb = (String) mapInputRequest.get('soldToNumb'); 
         String vatNumb = (String) mapInputRequest.get('vatNumb'); 
         String postalCode = (String) mapInputRequest.get('postalCode'); 
         String salesOrg = (String) mapInputRequest.get('salesOrg'); 
         String searchByCountry = (String) mapInputRequest.get('searchByCountry'); 
        
        Map<String,String> mapInputs = new Map<String,String>(); 
        mapInputs.put('IP_HON_ID','ALL'); //Hon Id selection to ALL
       
        /*
        
        if(String.isNotBlank(soldToName)){
            mapInputs.put('IP_SOLDTO_NAME',soldToName); 
        }else{
            mapInputs.put('IP_SOLDTO_NAME','ALL'); 
        }
         if(String.isNotBlank(soldToNumb)){
            mapInputs.put('IP_SOLDTO',soldToNumb); 
        }else{
            mapInputs.put('IP_SOLDTO','ALL'); 
        }
         if(String.isNotBlank(vatNumb)){
            mapInputs.put('IP_VAT_NUMBER',vatNumb); 
        }else{
            mapInputs.put('IP_VAT_NUMBER','ALL'); 
        }
         if(String.isNotBlank(postalCode)){
            mapInputs.put('IP_POSTAL_CODE',postalCode); 
        }else{
            mapInputs.put('IP_POSTAL_CODE','ALL'); 
        }
         if(String.isNotBlank(salesOrg)){
            mapInputs.put('IP_SALES_ORG',salesOrg); 
        }else{
            mapInputs.put('IP_SALES_ORG','ALL'); 
        }
         if(String.isNotBlank(searchByDChnl) && searchByDChnl != 'None'){
            mapInputs.put('IP_DIST_CHNL',searchByDChnl); 
        }else{
            mapInputs.put('IP_DIST_CHNL','ALL'); 
        }
         if(String.isNotBlank(searchByCountry) && searchByCountry != 'None'){
            mapInputs.put('IP_COUNTRY',searchByCountry); 
        }*/
        //else{
            mapInputs.put('IP_COUNTRY','ALL'); 
        //}
        
        return mapInputs ; 
    }
    
    /***************************************************************
* @Description : Wrapper instances to de-serialize responses. 
* 
* ************************************************************
    private with Sharing Class ResponseSearch {
        Boolean isSuccess = false ; 
        Integer total_results = 0 ; 
        
        List<CustomerSearchInfo> results = new List<CustomerSearchInfo>();
    }
    private with Sharing Class CustomerSearch {
        SearchResults OPEN_ORDERS = new SearchResults(); 
    }    
    private with Sharing Class SearchResults {
        List<CustomerSearchInfo> results = new List<CustomerSearchInfo>(); 
    }
    
    private with Sharing Class CustomerSearchInfo {
        String CLIENT_NUMBER ; 
        String SOLDTO ; 
        String SOLDTO_NAME ; 
        String SALES_ORG ; 
        String DISTRIBUTION_CHANNEL ; 
        String ORDER_NUMBER;
        String PO_NUMBER ; 
        String DIVISION ; 
        String POSTAL_CODE; 
        String VAT_REG_NUMBER ;
        String PART_NUMBER ; 
    }
    
    /****************************************************
* @Description : Method to Show Customer information
* ****************************************************/
   /* public with Sharing Class ResponseCustomerInfo {
        Boolean isSuccess = false ; 
        List<CustomerInfo> lstCustomers = new List<CustomerInfo>(); 
    }*/
    
    /**************************************************
* @Description : wrapper instance to send account id , name
* ************************************************/
    public with Sharing Class CustomerInfo {
        String value ; 
        String label ;
        //String soldToNumber ; 
        public CustomerInfo(String value , String label ) {
            this.value = value ; 
            this.label = label ; 
            //this.soldToNumber = soldToNumber ; 
        }
    }
    
        
     /**************************************************
* @Description : To Extract All The Coutry Names
* ************************************************/
    
    public String doCountryInfo() {
        
        String result ;
        List<String> countryList = new List<String>();
        countryList.add('None');
       Schema.DescribeFieldResult fieldResult = Account.Region__c.getDescribe(); 
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues(); 
        System.debug('Picklist::'+ple); 
        for( Schema.PicklistEntry f : ple)
        { 
            System.debug(f.getLabel() +'::'+ f.getValue()); 
            countryList.add(f.getValue());
        }
        
        result = JSON.serialize(countryList);
        
        return result ; 
    }
    
}