src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <inlineHelpText>One of three strategic regions: EMEAI, APAC, Americas.  This value is assigned based on the Sub-Region Name.  EMEAI = Europe, Middle East, Africa, India.  APAC = Asia Pacific.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Asia/Pacific Rim</fullName>
            </value>
            <value>
                <fullName>Europe/MiddleEast/Africa/India</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Report_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Country_Name__c</fullName>
    <label>Report Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Raw</businessProcess>
        <label>Outbound</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Co_Owner2__c.field-meta.xml
<CustomField>
    <fullName>Co_Owner2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-Owner2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesEOC7</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Engineering__c.field-meta.xml
<CustomField>
    <fullName>Engineering__c</fullName>
    <description>This field is populated from the trigger  OpportunityTeam_UpdatePrimaryManager    when Opportunity team role is Engineering.</description>
    <label>Engineering</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/ISC__c.field-meta.xml
<CustomField>
    <fullName>ISC__c</fullName>
    <description>This field is populated from the trigger  OpportunityTeam_UpdatePrimaryManager    when Opportunity team role is ISC.</description>
    <label>ISC</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Pricing__c.field-meta.xml
<CustomField>
    <fullName>Pricing__c</fullName>
    <description>This field is populated from the trigger  OpportunityTeam_UpdatePrimaryManager    when Opportunity team role is Pricing.</description>
    <label>Pricing</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Programme_Manager__c.field-meta.xml
<CustomField>
    <fullName>Programme_Manager__c</fullName>
    <label>Program Manager</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <inlineHelpText>SBU responsible for this opportunity</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Tech_Sales1__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales1__c</fullName>
    <description>This field is populated from the trigger  OpportunityTeam_UpdatePrimaryManager    when Opportunity team role is Tech Sales.</description>
    <label>Tech Sales Reporting</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Tech_Sales2__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales2__c</fullName>
    <label>Tech Sales Reporting Secondary</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity_Sales_Team__c/Opportunity_Sales_Team__c.object-meta.xml
<CustomObject>
    <label>Opportunity Team</label>
    <nameField>
        <displayFormat>OT-{0}</displayFormat>
        <label>Opportunity Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Sales_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sales_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Opportunity_Sales_Team__c/fields/Opportunity_Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Team_Role__c</fullName>
    <inlineHelpText>Only one &quot;Role&quot; representation is allowed for each team.</inlineHelpText>
    <label>Opportunity Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Aerospace Leadership</fullName>
            </value>
            <value>
                <fullName>Aerospace President</fullName>
            </value>
            <value>
                <fullName>AGBM</fullName>
            </value>
            <value>
                <fullName>AMERICAS Sales Leadership</fullName>
            </value>
            <value>
                <fullName>APAC Sales Leadership</fullName>
            </value>
            <value>
                <fullName>Area Sales</fullName>
            </value>
            <value>
                <fullName>Area Sales - Mgt Co</fullName>
            </value>
            <value>
                <fullName>Area Sales – Mgt Co</fullName>
            </value>
            <value>
                <fullName>Area Sales - Operator</fullName>
            </value>
            <value>
                <fullName>Boeing Growth</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Administration India</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Business Leadership</fullName>
            </value>
            <value>
                <fullName>Business Management AMERICAS</fullName>
            </value>
            <value>
                <fullName>Business Management APAC</fullName>
            </value>
            <value>
                <fullName>Business Management EMEAI</fullName>
            </value>
            <value>
                <fullName>Business Vice President</fullName>
            </value>
            <value>
                <fullName>C&amp;PS</fullName>
            </value>
            <value>
                <fullName>Campaign Mgr</fullName>
            </value>
            <value>
                <fullName>Capture Mgr</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>CBTL</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Clearinghouse</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Contracts Lead</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Customer Business</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>ISC</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Program Mgr</fullName>
            </value>
            <value>
                <fullName>Sales Lead</fullName>
            </value>
            <value>
                <fullName>Technical Sales</fullName>
            </value>
            <value>
                <fullName>Tech Sales Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity_Sales_Team__c/fields/Team_Member_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Full_Name__c</fullName>
    <formula>IF(User__c !=null, (User__r.FirstName+&apos; &apos;+User__r.LastName) ,IF(Contact__c !=null, (Contact__r.FirstName+&apos; &apos;+Contact__r.LastName) ,&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Team Member Full Name</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity_Sales_Team__c/recordTypes/BGA.recordType-meta.xml
<RecordType>
    <fullName>BGA</fullName>
    <active>false</active>
    <description>This is for BGA opportunities</description>
    <label>BGA</label>
</RecordType>

src/objects/OppType__c/OppType__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OppType</label>
</CustomObject>

src/objects/OppType__c/fields/RestrictedAccount__c.field-meta.xml
<CustomField>
    <fullName>RestrictedAccount__c</fullName>
    <label>RestrictedAccount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/OppTeam_UpdatePrimaryManager_Test.cls
/**
 * Created by Meiying Liang on 1/8/2020.
 */

@IsTest
private class OppTeam_UpdatePrimaryManager_Test {
    private final static String BENDIXKING = 'BendixKing';
    private final static String AMERICAS = 'Americas';
    private final static String AMERICA = 'America';
    private static Opportunity opportunity;
    private static Account acct;
    private static OppType__c oppType;
    private static Contact contact;

    static void init() {
        acct = new TestAccountBuilder()
                .addField( 'Report_Country_Name__c', AMERICA )
                .addField( 'Region_Name__c', AMERICAS )
                .generate();
        oppType = new OppType__c( RestrictedAccount__c = acct.Id, Name = 'Test' );
        insert oppType;
        opportunity = new TestOpportunityBuilder( 'Test', BENDIXKING )
                .addField( 'AccountId', acct.Id )
                .addField( 'SBU__c', 'BGA' )
                .addField( 'StageName', 'Closed Won' )
                .build();

        contact = new TestContactBuilder().generate();
        Product2 product = new TestProductBuilder()
                .addField( 'CanUseRevenueSchedule', true )
                .generate();
        PricebookEntry standardPricebookEntry = new PriceBookEntry(
                Pricebook2Id = System.Test.getStandardPricebookId(),
                Product2Id = product.Id,
                UnitPrice = 50
        );

        Database.insert(standardPricebookEntry);
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_Engineering() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'Engineering' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Engineering')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Program Mgr';
        update oppTeam;

        system.assertEquals(opportunity.Programme_Manager__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_ProgramManager() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'ProgramManager' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Program Mgr')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Co-Owner2';
        update oppTeam;

        system.assertEquals(opportunity.Co_Owner2__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_ISC() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'ISC' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','ISC')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Engineering';
        update oppTeam;

        system.assertEquals(opportunity.Engineering__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_Pricing() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'Pricing' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Pricing')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'ISC';
        update oppTeam;

        system.assertEquals(opportunity.ISC__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_TechnicalSales() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'TechnicalSales' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Technical Sales')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Pricing';
        update oppTeam;

        system.assertEquals(opportunity.Pricing__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_TechnicalSalesSecondary() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'TechnicalSalesSecondary' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Tech Sales Secondary')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Technical Sales';
        update oppTeam;

        system.assertEquals(opportunity.Tech_Sales1__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_SalesLead() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'SalesLead' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Sales Lead')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Tech Sales Secondary';
        update oppTeam;

        system.assertEquals(opportunity.Tech_Sales2__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_CoOwner() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'Co-Owner' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Co-Owner')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Sales Lead';
        update oppTeam;

        system.assertEquals(opportunity.Sales_Lead__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AU_OppTeam_UpdatePrimaryManager_CoOwner2() {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'Co-Owner2' )
                .setLastName( 'Test' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Co-Owner2')
                .generate();

        oppTeam.Opportunity_Team_Role__c = 'Co-Owner';
        update oppTeam;

        system.assertEquals(opportunity.Co_Owner__c,oppTeam.Team_Member_Full_Name__c);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_Engineering()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Engineering')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Engineering__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_ProgramManager()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Program Mgr')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Programme_Manager__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_ISC()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','ISC')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.ISC__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_Pricing()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Pricing')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Pricing__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_TechnicalSales()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Technical Sales')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Tech_Sales1__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_TechnicalSalesSecondary()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Tech Sales Secondary')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Tech_Sales2__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_SalesLead()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Sales Lead')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Sales_Lead__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_CoOwner()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Co-Owner')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Co_Owner__c,null);

        Test.stopTest();
    }

    @IsTest
    static void AD_OppTeam_UpdatePrimaryManager_CoOwner2()
    {
        init();

        insert opportunity;

        Test.startTest();

        User user = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();

        Opportunity_Sales_Team__c oppTeam = new TestOpportunityTeamBuilder()
                .addField('Opportunity__c', opportunity.Id)
                .setUserId(user.Id)
                .addField('Opportunity_Team_Role__c','Co-Owner2')
                .generate();

        delete oppTeam;

        system.assertEquals(opportunity.Co_Owner2__c,null);

        Test.stopTest();
    }

}