src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Account/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <inlineHelpText>One of three strategic regions: EMEAI, APAC, Americas.  This value is assigned based on the Sub-Region Name.  EMEAI = Europe, Middle East, Africa, India.  APAC = Asia Pacific.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Asia/Pacific Rim</fullName>
            </value>
            <value>
                <fullName>Europe/MiddleEast/Africa/India</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Report_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Country_Name__c</fullName>
    <label>Report Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Referrer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Marketing Engaged</fullName>
            </value>
            <value>
                <fullName>With Telemarketing</fullName>
            </value>
            <value>
                <fullName>Assigned - Target Team</fullName>
            </value>
            <value>
                <fullName>Working - Target Team</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>With Customer Marketing</fullName>
            </value>
            <value>
                <fullName>Working - Contacted</fullName>
            </value>
            <value>
                <fullName>Closed - Existing Opportunity</fullName>
            </value>
            <value>
                <fullName>Closed - No Project Now</fullName>
            </value>
            <value>
                <fullName>Closed - Converted (Qualified)</fullName>
            </value>
            <value>
                <fullName>Redirected - Channel Sales</fullName>
            </value>
            <value>
                <fullName>Closed - Competitor</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid Contact</fullName>
            </value>
            <value>
                <fullName>Redirected - LGS</fullName>
            </value>
            <value>
                <fullName>Sent to Partner</fullName>
            </value>
            <value>
                <fullName>Redirected - Partner Sales Manager</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Assigned - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Working - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Contacted - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Handoff</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Converted to Opportunity</fullName>
            </value>
            <value>
                <fullName>Converted To Contact</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Log_F2F_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Log_F2F_Meeting__c</fullName>
    <label>Log F2F Meeting</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/fields/Log_F2F_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Log_F2F_Meeting_Date__c</fullName>
    <label>Log F2F Meeting Date</label>
    <type>Date</type>
</CustomField>

src/objects/Opportunity/fields/Log_Virtual_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Log_Virtual_Meeting__c</fullName>
    <label>Log Virtual Meeting</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/fields/Log_Virtual_Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Log_Virtual_Meeting_Date__c</fullName>
    <label>Log Virtual Meeting Date</label>
    <type>Date</type>
</CustomField>

src/objects/Opportunity/fields/Next_Step__c.field-meta.xml
<CustomField>
    <fullName>Next_Step__c</fullName>
    <label>Internal Next Steps</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <defaultValue>$RecordType.Name</defaultValue>
    <label>Opportunity Record Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <inlineHelpText>SBU responsible for this opportunity</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Customer Status</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OppType__c/OppType__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OppType</label>
</CustomObject>

src/objects/OppType__c/fields/RestrictedAccount__c.field-meta.xml
<CustomField>
    <fullName>RestrictedAccount__c</fullName>
    <label>RestrictedAccount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Task.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task/recordTypes/Customer_Status.recordType-meta.xml
<RecordType>
    <fullName>Customer_Status</fullName>
    <active>true</active>
    <description>Used by Sales to capture the latest Status with customer for this opportunity</description>
    <label>Customer Status</label>
</RecordType>

src/objects/Task/recordTypes/Log_F2F.recordType-meta.xml
<RecordType>
    <fullName>Log_F2F</fullName>
    <active>true</active>
    <description>Used by Sales to capture all Face to Face Customer Visits/Meetings/Interactions that follows the criteria from Seller Playbook</description>
    <label>Log F2F Meeting</label>
</RecordType>

src/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tact</description>
    <label>Task</label>
</RecordType>

src/classes/Update_Oppt_Customer_Status_Test.cls
/**
 * Created by Meiying Liang on 12/7/2019.
 */

@IsTest
private class Update_Oppt_Customer_Status_Test {
    private final static String BENDIXKING = 'BendixKing';
    private final static String AMERICAS = 'Americas';
    private final static String AMERICA = 'America';
    private final static String RESTRICTED = 'Restricted';

    private static Opportunity opportunity;
    private static Account acct;
    private static User userOne;
    private static OppType__c oppType;
    private static Contact contact;

    static void init() {
        acct = new TestAccountBuilder()
                .addField( 'Report_Country_Name__c', AMERICA )
                .addField( 'Region_Name__c', AMERICAS )
                .generate();
        oppType = new OppType__c( RestrictedAccount__c = acct.Id, Name = 'Test' );
        insert oppType;
        opportunity = new TestOpportunityBuilder( 'Test', BENDIXKING )
                .addField( 'AccountId', acct.Id )
                .addField( 'SBU__c', 'BGA' )
                .addField( 'StageName', 'Closed Won' )
                .build();

        contact = new TestContactBuilder()
                .addField( 'AccountId', acct.Id )
                .generate();
        userOne = new TestUserBuilder()
                .setFirstName( 'John' )
                .setLastName( 'Doe' )
                .generate();
    }

    @IsTest
    static void InsertNewOpportunityWithCustomerStatus() {
        init();

        System.Test.startTest();
        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Status__c = 'TestCustomerStatus';
        insert opportunity;
        System.Test.stopTest();

        List<Task> newCustomerStatusTasks = [Select Description From Task Where WhatId =: opportunity.Id LIMIT 1];

        System.assertEquals(1,newCustomerStatusTasks.size());
        System.assertEquals('TestCustomerStatus', newCustomerStatusTasks[0].Description);
    }

    @IsTest
    static void InsertNewOpportunityWithNextStep(){
        init();

        System.Test.startTest();
        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Next_Step__c = 'TestNextStep';
        opportunity.Next_Step_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;
        System.Test.stopTest();

        List<Task> newNextStepTasks = [Select Description, ActivityDate From Task Where WhatId =: opportunity.Id LIMIT 1];

        System.assertEquals(1, newNextStepTasks.size());
        System.assertEquals('TestNextStep', newNextStepTasks[0].Description);
        System.assertEquals(Date.newInstance(2019, 12, 24), newNextStepTasks[0].ActivityDate);
    }

    @IsTest
    static void UpdateOpportunityWithCustomerStatus() {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Status__c = 'TestCustomerStatus';
        insert opportunity;

        System.Test.startTest();
        opportunity.Status__c = 'UpdatedTestCustomerStatus';
        update opportunity;

        System.Test.stopTest();

        List<Task> newCustomerStatusTasks = [Select Description From Task Where WhatId =: opportunity.Id ORDER By CreatedDate DESC LIMIT 1];

        System.assertEquals(1,newCustomerStatusTasks.size());
        System.assertEquals('UpdatedTestCustomerStatus', newCustomerStatusTasks[0].Description);
    }

    @IsTest
    static void UpdateOpportunityWithNextStep() {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Next_Step__c = 'TestNextStep';
        opportunity.Next_Step_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;

        System.Test.startTest();
        opportunity.Next_Step__c = 'UpdatedTestNextStep';
        opportunity.Next_Step_Date__c = Date.newInstance(2019, 12, 25);
        update opportunity;

        System.Test.stopTest();

        List<Task> newNextStepTasks = [Select Description, ActivityDate From Task Where WhatId =: opportunity.Id ORDER BY CreatedDate DESC LIMIT 1];

        System.assertEquals(1,newNextStepTasks.size());
        System.assertEquals('UpdatedTestNextStep', newNextStepTasks[0].Description);
        System.assertEquals(Date.newInstance(2019, 12, 25), newNextStepTasks[0].ActivityDate);
    }

    @IsTest
    static void InsertNewCustomerStatusTask(){
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Customer Status').getRecordTypeId();

        Task newCustomerStatusTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Customer Status',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'NewCustomerStatusTask',
                ActivityDate = null,
                CreatedDate = system.now());

        System.Test.startTest();

        insert newCustomerStatusTask;

        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT Id,Status__c FROM Opportunity WHERE Id =:opportunity.Id LIMIT 1];

        System.assertEquals('NewCustomerStatusTask', updatedOpportunity.Status__c);
    }

    @IsTest
    static void InsertNewNextStepTask(){
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Next Step').getRecordTypeId();

        Task newNextStepTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Next Step',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'NewNextStepTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                CreatedDate = system.now());

        System.Test.startTest();

        insert newNextStepTask;

        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT Id,Next_Step__c,Next_Step_Date__c FROM Opportunity WHERE Id =:opportunity.Id LIMIT 1];

        System.assertEquals('NewNextStepTask', updatedOpportunity.Next_Step__c);
        System.assertEquals(Date.newInstance(2019, 12, 25), updatedOpportunity.Next_Step_Date__c);

    }

    @IsTest
    static void DeleteTheOnlyCustomerStatusTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Status__c = 'CustomerStatusTask';
        insert opportunity;

        List<Task> customerStatusTasks = [SELECT Id From Task Where WhatId =: opportunity.Id LIMIT 1];

        System.Test.startTest();
        delete customerStatusTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT  Id, Status__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];

        System.assertEquals(true, String.isBlank(updatedOpportunity.Status__c));
    }

    @IsTest
    static void DeleteTheOnlyNextStepTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Next_Step__c = 'NextStepTask';
        opportunity.Next_Step_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;

        List<Task> nextStepTasks = [SELECT Id From Task Where WhatId =: opportunity.Id LIMIT 1];

        System.Test.startTest();
        delete nextStepTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT  Id, Next_Step__c, Next_Step_Date__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];

        System.assertEquals(true, String.isBlank(updatedOpportunity.Next_Step__c));
        System.assertEquals(null, updatedOpportunity.Next_Step_Date__c);
    }

    @IsTest
    static void DeleteTheOnlyLogVirtualMeetingTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Log_Virtual_Meeting__c = 'LogVirtualMeetingTask';
        opportunity.Log_Virtual_Meeting_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;

        List<Task> logVirtualMeetingTasks = [SELECT Id From Task Where WhatId =: opportunity.Id LIMIT 1];

        System.Test.startTest();
        delete logVirtualMeetingTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT  Id, Log_Virtual_Meeting__c, Log_Virtual_Meeting_Date__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];

        System.assertEquals(true, String.isBlank(updatedOpportunity.Log_Virtual_Meeting__c));
        System.assertEquals(null, updatedOpportunity.Log_Virtual_Meeting_Date__c);
    }

    @IsTest
    static void DeleteTheOnlyLogF2FMeetingTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Log_F2F_Meeting__c = 'LogF2FMeetingTask';
        opportunity.Log_F2F_Meeting_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;

        List<Task> logF2FMeetingTasks = [SELECT Id From Task Where WhatId =: opportunity.Id LIMIT 1];

        System.Test.startTest();
        delete logF2FMeetingTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT  Id, Log_F2F_Meeting__c, Log_F2F_Meeting_Date__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];

        System.assertEquals(true, String.isBlank(updatedOpportunity.Log_F2F_Meeting__c));
        System.assertEquals(null, updatedOpportunity.Log_F2F_Meeting_Date__c);
    }

    @IsTest
    static void DeleteLatestCustomerStatusTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Status__c = 'FirstCustomerStatusTask';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Customer Status').getRecordTypeId();

        Task newCustomerStatusTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Customer Status',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'SecondCustomerStatusTask',
                ActivityDate = null,
                CreatedDate = system.now());

        insert newCustomerStatusTask;

        List<Task> customerStatusTasks = [SELECT Id From Task Where WhatId =: opportunity.Id ORDER BY CreatedDate DESC LIMIT 1];

        System.Test.startTest();
        delete customerStatusTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT  Id, Status__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];

        System.assertEquals('FirstCustomerStatusTask', updatedOpportunity.Status__c);
    }

    @IsTest
    static void DeleteLatestNextStepTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Next_Step__c = 'FirstNextStepTask';
        opportunity.Next_Step_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Next Step').getRecordTypeId();

        Task newNextStepTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Next Step',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'SecondNextStepTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                CreatedDate = system.now());

        insert newNextStepTask;

        List<Task> nextStepTasks = [SELECT Id From Task Where WhatId =: opportunity.Id ORDER BY CreatedDate DESC LIMIT 1];

        System.Test.startTest();
        delete nextStepTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT Id, Next_Step__c, Next_Step_Date__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];


        System.assertEquals('FirstNextStepTask', updatedOpportunity.Next_Step__c);
        System.assertEquals(Date.newInstance(2019, 12, 24), updatedOpportunity.Next_Step_Date__c);
    }

    @IsTest
    static void DeleteLatestLogVirtualMeetingTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Log_Virtual_Meeting__c = 'FirstLogVirtualMeetingTask';
        opportunity.Log_Virtual_Meeting_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Log Virtual Meeting').getRecordTypeId();

        Task newLogVirtualMeetingTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Log Virtual Meeting',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'SecondLogVirtualMeetingTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                Activity_Date__c = Date.newInstance(2019, 12, 25),
                CreatedDate = system.now());

        insert newLogVirtualMeetingTask;

        List<Task> logVirtualMeetingTasks = [SELECT Id From Task Where WhatId =: opportunity.Id ORDER BY CreatedDate DESC LIMIT 1];

        System.Test.startTest();
        delete logVirtualMeetingTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT Id, Log_Virtual_Meeting__c, Log_Virtual_Meeting_Date__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];


        System.assertEquals('FirstLogVirtualMeetingTask', updatedOpportunity.Log_Virtual_Meeting__c);
        System.assertEquals(Date.newInstance(2019, 12, 24), updatedOpportunity.Log_Virtual_Meeting_Date__c);
    }

    @IsTest
    static void DeleteLatestLogF2FMeetingTask()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        opportunity.Log_F2F_Meeting__c = 'FirstLogF2FMeetingTask';
        opportunity.Log_F2F_Meeting_Date__c = Date.newInstance(2019, 12, 24);
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Log F2F Meeting').getRecordTypeId();

        Task newLogF2FMeetingTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Log F2F Meeting',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'SecondLogF2FMeetingTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                Activity_Date__c = Date.newInstance(2019, 12, 25),
                CreatedDate = system.now());

        insert newLogF2FMeetingTask;

        List<Task> logF2FMeetingTasks = [SELECT Id From Task Where WhatId =: opportunity.Id ORDER BY CreatedDate DESC LIMIT 1];

        System.Test.startTest();
        delete logF2FMeetingTasks[0];
        System.Test.stopTest();

        Opportunity updatedOpportunity = [SELECT Id, Log_F2F_Meeting__c, Log_F2F_Meeting_Date__c FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];


        System.assertEquals('FirstLogF2FMeetingTask', updatedOpportunity.Log_F2F_Meeting__c);
        System.assertEquals(Date.newInstance(2019, 12, 24), updatedOpportunity.Log_F2F_Meeting_Date__c);
    }

    @IsTest
    static void InsertNullDateForNewNextStepTaskFromTactAI()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Next Step').getRecordTypeId();

        Task newNextStepTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Next Step',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'NewNextStepTask',
                ActivityDate = null,
                Source__c = 'TACT AI',
                CreatedDate = system.now());

        System.Test.startTest();

        insert newNextStepTask;

        System.Test.stopTest();

        Task insertedTask = [SELECT ActivityDate,Activity_Date__c FROM Task WHERE Id =:newNextStepTask.Id LIMIT 1];

        System.assertEquals(insertedTask.ActivityDate, date.today());
        System.assertEquals(insertedTask.Activity_Date__c, date.today());
    }

    @IsTest
    static void InsertDateForNewNextStepTaskFromTactAI()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Next Step').getRecordTypeId();

        Task newNextStepTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Next Step',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'NewNextStepTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                Source__c = 'TACT AI',
                CreatedDate = system.now());

        System.Test.startTest();

        insert newNextStepTask;

        System.Test.stopTest();

        Task insertedTask = [SELECT ActivityDate,Activity_Date__c FROM Task WHERE Id =:newNextStepTask.Id LIMIT 1];

        System.assertEquals(insertedTask.Activity_Date__c, Date.newInstance(2019, 12, 25));
    }

    @IsTest
    static void CloneCustomerStatusTaskForLogF2F_FromTactAI()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Log_F2F').getRecordTypeId();

        Task newLogF2FTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Customer Status',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'ClonedTask',
                //ActivityDate = Date.newInstance(2019, 12, 25),
                //Activity_Date__c = Date.newInstance(2019, 12, 25),
                Source__c = 'TACT AI',
                Type__c = 'Customer Status',
                CreatedDate = system.now());

        System.Test.startTest();

        insert newLogF2FTask;

        System.Test.stopTest();

        //System.assertEquals(insertedTask.size(),2);
    }

    @IsTest
    static void CloneLogMeetingTaskForCustomerStatus_FromTactAI()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Customer_Status').getRecordTypeId();

        Task newCustomerStatusTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Customer Status',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'ClonedTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                Activity_Date__c = Date.newInstance(2019, 12, 25),
                Source__c = 'TACT AI',
                Type__c = 'Log Virtual Meeting',
                CreatedDate = system.now());

        System.Test.startTest();

        insert newCustomerStatusTask;

        System.Test.stopTest();

        List<Task> insertedTask = [SELECT ActivityDate,Activity_Date__c FROM Task WHERE WhatId =: opportunity.Id And Activity_Date__c < YESTERDAY];

        System.assertEquals(insertedTask.size(),2);
    }

    @IsTest
    static void CloneLogCallTaskForCustomerStatus_FromTactAI()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Customer_Status').getRecordTypeId();

        Task newCusotmerStatusTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Customer Status',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'ClonedTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                Source__c = 'TACT AI',
                Type__c = 'Log Call',
                CreatedDate = system.now());

        System.Test.startTest();

        insert newCusotmerStatusTask;

        System.Test.stopTest();

        List<Task> insertedTask = [SELECT ActivityDate,Activity_Date__c FROM Task WHERE WhatId =: opportunity.Id];

        System.assertEquals(insertedTask.size(),2);
    }

    @IsTest
    static void CloneLogF2FMeetingTaskForCustomerStatus_FromTactAI()
    {
        init();

        opportunity.Opportunity_Type__c = 'Test';
        insert opportunity;

        Id recTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Customer_Status').getRecordTypeId();

        Task newCustomerStatusTask = new Task(
                RecordtypeID = recTypeId,
                Subject = 'Log F2F Meeting',

                WhatId = opportunity.Id,
                //This is the default..
                OwnerId = UserInfo.getUserId(),
                Status = 'Completed',
                Type = 'Call',
                Description = 'ClonedTask',
                ActivityDate = Date.newInstance(2019, 12, 25),
                Activity_Date__c = Date.newInstance(2019, 12, 25),
                Source__c = 'TACT AI',
                Type__c = 'Log F2F Meeting',
                CreatedDate = system.now());

        System.Test.startTest();

        insert newCustomerStatusTask;

        System.Test.stopTest();

        List<Task> insertedTask = [SELECT ActivityDate,Activity_Date__c FROM Task WHERE WhatId =: opportunity.Id And Activity_Date__c < YESTERDAY];

        System.assertEquals(insertedTask.size(),2);
    }

}