src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <inlineHelpText>Market names to coincide with appropriate SBU (Air Transport and/or Regional Transport, Business and/or General Aviation, etc)</inlineHelpText>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Air Transport</fullName>
            </value>
            <value>
                <fullName>Business Aviation</fullName>
            </value>
            <value>
                <fullName>General Aviation</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Helicopters</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>Non-Aerospace</fullName>
            </value>
            <value>
                <fullName>Regional Transport</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Sbl_Account_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Sbl Account Row ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <inlineHelpText>This field is mandatory for many business processes.  It is recommended that you populate this field prior to closing the case.  Coming soon: In December 2020, the resolution will be visible to customers on the portal.</inlineHelpText>
    <label>Resolution</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Sbl_Account_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_Id__c</fullName>
    <label>Sbl Account Row Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Supported_Product__c.field-meta.xml
<CustomField>
    <fullName>Supported_Product__c</fullName>
    <description>Do NOT change this list without Troy Barrett / Jenn Searle Approval - They are the Business Owners (TOC)</description>
    <label>Supported Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Catalog_Product_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>787 Maintenance System</fullName>
            </value>
            <value>
                <fullName>ACARS MU</fullName>
            </value>
            <value>
                <fullName>ADAHRS/AHRS</fullName>
            </value>
            <value>
                <fullName>ADAHRS - Bendix King</fullName>
            </value>
            <value>
                <fullName>ADC/DADC (Digital Air Data Computer)</fullName>
            </value>
            <value>
                <fullName>ADF, Primus II/EPIC</fullName>
            </value>
            <value>
                <fullName>ADF DFA-74X</fullName>
            </value>
            <value>
                <fullName>ADIRS</fullName>
            </value>
            <value>
                <fullName>ADIRU</fullName>
            </value>
            <value>
                <fullName>AESS</fullName>
            </value>
            <value>
                <fullName>AFIS</fullName>
            </value>
            <value>
                <fullName>AGT1500 Military</fullName>
            </value>
            <value>
                <fullName>AHRS</fullName>
            </value>
            <value>
                <fullName>Aircraft Personality Module</fullName>
            </value>
            <value>
                <fullName>Airframe Hydraulics</fullName>
            </value>
            <value>
                <fullName>Airplane Information Management System (AIMS)</fullName>
            </value>
            <value>
                <fullName>AirSat 1</fullName>
            </value>
            <value>
                <fullName>Air Traffic Services</fullName>
            </value>
            <value>
                <fullName>Air Turbine Starter</fullName>
            </value>
            <value>
                <fullName>AL/Ex / SPEX / ISS</fullName>
            </value>
            <value>
                <fullName>ALF502 Engine</fullName>
            </value>
            <value>
                <fullName>Anti-Ice Valves - ATR</fullName>
            </value>
            <value>
                <fullName>Anti-Ice Valves - BGA</fullName>
            </value>
            <value>
                <fullName>AOG Lease / Engine Rental Bank</fullName>
            </value>
            <value>
                <fullName>APEX Pilatus</fullName>
            </value>
            <value>
                <fullName>APEX Viking</fullName>
            </value>
            <value>
                <fullName>APM</fullName>
            </value>
            <value>
                <fullName>APU - 100-2/-3/-135</fullName>
            </value>
            <value>
                <fullName>APU - 131-9A</fullName>
            </value>
            <value>
                <fullName>APU - 131-9B</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Contact/fields/Sbl_Account_Row_ID__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_ID__c</fullName>
    <label>Sbl Account Row ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/classes/sendmailclass_edit_TestCls.cls
@isTest
private class sendmailclass_edit_TestCls{

    static testMethod void sendmailclass_edit_Testcls()
    {
        TriggerInactive.testTrigger = false;
        List<Folder> EMTFolder = [Select Id, Name, DeveloperName from Folder where type = 'email' and (( Name like 'CSO%') or ( Name like 'GTO%') or ( Name like 'Survey%'))];
        system.debug('@@@@TEST:EmailTemplate='+ EMTFolder);
        test.starttest(); 
        EmailTemplate etemp = [Select Name, HtmlValue, Subject, Body, DeveloperName, TemplateType, IsActive, FolderId from EmailTemplate where Name LIKE 'CSO - Account Request'];
        //creating account;
        Account acc= new Account(name='Test Accountabc123', Market_Name__c = 'Military', Sbl_Account_Row_Id__c = 'A-9999999');
        insert acc;
        
        //creating contact;
        Contact cont=new Contact(firstname='Test',LastName='Contact1',AccountId=acc.Id,Phone_3__c='9986502495',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='T123567' );
        insert cont;        
        
        //creating case
        Case newcase =new Case(AccountId=acc.Id,subject='Test Case:Do not Delete',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
        //No_FCR_Reason__c='Not Trained',For Ticket INC000009687923
        Type='Order',Supported_Product__c='Radio',Origin ='Email-Anniston.RFQ',Resolution__c='Test Resolution');
        insert newcase ;
            
        //Case newcase = [Select id, Contactid, Origin, Classification__c, Status, HON_Commit_Date__c, Export_Compliance_Content_ITAR_EAR__c, Government_Compliance_SM_M_Content__c, Sub_Class__c, Detail_Class__c,Resolution__c from Case where subject='Test Case:Do not Delete' limit 1];
        //system.debug('**************'+newcase);
        
        /*Attachment attach = new Attachment();
        attach.Name = 'NewAttachment';
        attach.ParentId = newcase.ID;
        String asd = 'asd';
        attach.Body = blob.valueof(asd);
        insert attach;*/
        
        EmailMessage emess = new EmailMessage();
        emess.BccAddress = 'anup.narayanan@wipro.com';
        emess.CcAddress = 'albin.arul@wipro.com';
        emess.HtmlBody = 'This is Html body Case:';
        emess.Subject = 'Test Subject';
        emess.TextBody = 'This is Text body';
        emess.ToAddress = 'niveda.jeyaseelan@wipro.com';
        emess.FromAddress = 'anup.narayanan@wipro.com'; 
        emess.ParentID = newcase.id;
        emess.INCOMING=True;
        insert emess;
        
        ApexPages.CurrentPage().getParameters().Put('BCClist','anup.narayanan@gmail.com');
        ApexPages.CurrentPage().getParameters().Put('AddCClist','n.anup89@gmail.com');
        ApexPages.CurrentPage().getParameters().Put('ToList','anup.narayanan@wipro.com');
        ApexPages.CurrentPage().getParameters().Put('caseid',newcase.id); 
        ApexPages.CurrentPage().getParameters().Put('isHtml','true'); 
        ApexPages.CurrentPage().getParameters().Put('isHTMLval','true');
        ApexPages.CurrentPage().getParameters().Put('templateId',etemp.id);
        
        ApexPages.CurrentPage().getParameters().Put('Id',emess.id);
        ApexPages.CurrentPage().getParameters().Put('forward','True');
        ApexPages.StandardController std = new ApexPages.StandardController(emess);  
        sendmailclass_edit test1 = new sendmailclass_edit(std);
        
        
        test1.fileName = 'asd';
        String bb = 'dsa';       
        test1.filebody = blob.valueof(bb); 
        test1.doref();
        test1.doref1();
        test1.attachtemplate();
        test1.template();
        String s = test1.getEmailTemplate();
        test1.setEmailTemplate(s);
        
        String s1 = test1.gettemplateId();
        test1.settemplateId(s1);
        
        List<SelectOption> templist = test1.getTempList();
        List<EmailTemplate> etmp = test1.getemailTemplates();   
        
        Case c = test1.getcaseRecord();  
        test1.cancelTemplate();
        test1.ViewDetails();
        test1.ViewTemplateDetails();
        
        test1.send();
        test1.cancel();
        test1.attachfile();
        test1.nodisp();
        
        List<Id> selattach = test1.GetSelectedattachments(); 
        List<Attachment> attch = test1.getattachments(); 
        List<Attachment> showatt = test1.getshowatt();
        
        id pageid=test1.getPageId();
        pageid=emess.id;
        test1.setPageid(pageid);    
    
    }
    
    static testMethod void sendmailclass_edit_Testcls1()
    {
        TriggerInactive.testTrigger = false;
        List<Folder> EMTFolder = [Select Id, Name, DeveloperName from Folder where type = 'email' and (( Name like 'CSO%') or ( Name like 'GTO%') or ( Name like 'Survey%'))];
        system.debug('@@@@TEST:EmailTemplate='+ EMTFolder);
        test.starttest(); 
        EmailTemplate etemp = [Select Name, HtmlValue, Subject, Body, DeveloperName, TemplateType, IsActive, FolderId from EmailTemplate where Name LIKE 'CSO - Account Request'];
        //creating account;
        Account acc= new Account(name='Test Accountabc123', Market_Name__c = 'Military', Sbl_Account_Row_Id__c = 'A-9999999');
        insert acc;
        
        //creating contact;
        Contact cont=new Contact(firstname='Test',LastName='Contact1',AccountId=acc.Id,Phone_3__c='9986502495',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567' );
        insert cont;        
        
        //creating case
        Case newcase =new Case(AccountId=acc.Id,subject='Test Case:Do not Delete',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
        //No_FCR_Reason__c='Not Trained',For Ticket INC000009687923
        Type='Order',Supported_Product__c='Radio',Origin ='Email-Anniston.RFQ',Resolution__c='Test Resolution');
        insert newcase ;
            
        //Case newcase = [Select id, Contactid, Origin, Classification__c, Status, HON_Commit_Date__c, Export_Compliance_Content_ITAR_EAR__c, Government_Compliance_SM_M_Content__c, Sub_Class__c, Detail_Class__c,Resolution__c from Case where subject='Test Case:Do not Delete' limit 1];
        //system.debug('**************'+newcase);
        
        /*Attachment attach = new Attachment();
        attach.Name = 'NewAttachment';
        attach.ParentId = newcase.ID;
        String asd = 'asd';
        attach.Body = blob.valueof(asd);
        insert attach;*/
        
        EmailMessage emess = new EmailMessage();
        emess.BccAddress = 'anup.narayanan@wipro.com';
        emess.CcAddress = 'albin.arul@wipro.com';
        emess.HtmlBody = 'This is Html body Case:';
        emess.Subject = 'Test Subject';
        emess.TextBody = 'This is Text body';
        emess.ToAddress = 'niveda.jeyaseelan@wipro.com';
        emess.FromAddress = 'anup.narayanan@wipro.com'; 
        emess.ParentID = newcase.id;
        emess.INCOMING=True;
        insert emess;
        
        ApexPages.CurrentPage().getParameters().Put('BCClist','anusuya.murugiah@honeywell.com');
        ApexPages.CurrentPage().getParameters().Put('AddCClist','latha.priya@nttdata.com');
        ApexPages.CurrentPage().getParameters().Put('ToList','anusuya.murugiah@nttdata.com');
        ApexPages.CurrentPage().getParameters().Put('caseid',newcase.id); 
        ApexPages.CurrentPage().getParameters().Put('isHtml','true'); 
        ApexPages.CurrentPage().getParameters().Put('isHTMLval','false');
        ApexPages.CurrentPage().getParameters().Put('templateId',null);
        ApexPages.CurrentPage().getParameters().Put('HtmlemailBody','test< & >test-ing');
        ApexPages.CurrentPage().getParameters().Put('Id',emess.id);
        ApexPages.CurrentPage().getParameters().Put('forward','True');
        ApexPages.StandardController std2 = new ApexPages.StandardController(emess);  
        sendmailclass_edit test3 = new sendmailclass_edit(std2);
        
        
        test3.fileName = 'asd';
        
        String bb = 'dsa';       
        test3.filebody = blob.valueof(bb); 
        test3.doref();
        test3.doref1();
        test3.attachtemplate();
        test3.template();
        
        String s = test3.getEmailTemplate();
        test3.setEmailTemplate(s);
        
        String s1 = test3.gettemplateId();
        test3.settemplateId(s1);
        
        List<SelectOption> templist2 = test3.getTempList();
        List<EmailTemplate> etmp2 = test3.getemailTemplates();   
        
        Case c2 = test3.getcaseRecord();
        test3.setsubject(null);
        String s2 = test3.getsubject();
         test3.UploadFile();
        
        test3.ViewDetails();
        
        test3.cancel();
        test3.attachfile();
        test3.nodisp();
        List<Id> selattach2 = test3.GetSelectedattachments();     
        List<Attachment> attch2 = test3.getattachments(); 
        List<Attachment> showatt2 = test3.getshowatt();
        id pageid2=test3.getPageId();
        pageid2=emess.id;
        test3.setPageid(pageid2);
        
        //////////////////////////////////////////////////////////////////////////////////////////
        test.stoptest();
    }
    
}