src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor or Supplier Accounts</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Account/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <description>Business Segment is relabeled as CBT as per Business request.</description>
    <inlineHelpText>A further division into Business Segments within the Strategic Business Unit/Market (e.g., Aftermarket, Airlines, Military/Operators, etc.)</inlineHelpText>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES CBT</fullName>
            </value>
            <value>
                <fullName>DEW</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
                <label>Embraer D&amp;S</label>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <inlineHelpText>One of three strategic regions: EMEAI, APAC, Americas.  This value is assigned based on the Sub-Region Name.  EMEAI = Europe, Middle East, Africa, India.  APAC = Asia Pacific.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Asia/Pacific Rim</fullName>
            </value>
            <value>
                <fullName>Europe/MiddleEast/Africa/India</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/REPORT_ACCOUNT_NAME__c.field-meta.xml
<CustomField>
    <fullName>REPORT_ACCOUNT_NAME__c</fullName>
    <label>REPORT ACCOUNT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <inlineHelpText>A category that indicates the type of service the customer is expected to receive, as determined by HON business entities based on sales, anticipated opportunities, etc.</inlineHelpText>
    <label>Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Refer to Network</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Superior</fullName>
            </value>
            <value>
                <fullName>Unauthorized Dist/Brkr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Sub_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_Name__c</fullName>
    <inlineHelpText>A specific country or area that is derived from a larger region or continent.  It is generally based on location (Europe, Middle East, Japan, etc.) but occasionally is based on business divisions</inlineHelpText>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region_Name__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Australia / NZ</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>China / HKG</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Russia and CU</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <formula>Text(Account.CBT__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CBT</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <formula>TEXT(Account.Customer_Status__c)</formula>
    <label>Customer Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <formula>HYPERLINK(&quot;mailto:&quot;&amp; Contact.Primary_Email_Address__c, Contact.Primary_Email_Address__c, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Email Address</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <formula>TEXT( Account.Service_Level__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Level</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU_Contact__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S Other CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
            <value>
                <fullName>General Atomics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/classes/SendCaseEmail_test1.cls
/**************************************************************************************************
* Company Name          : Honeywell Aero
* Name                  : SendCaseEmail_test1
* Description           : Test Class for the trigger SendcaseEmail
* 
* Modification History  :
* Date             Version No.    Modified by           Brief Description of Modification
* Nov-08-2013      1.0            Anusuy Murugiah       Wrapping the testmethod with Start and Stop
**************************************************************************************************/
@isTest(SeeAllData=true)
public class SendCaseEmail_test1
{ 
    static testmethod void SendCaseEmailtest1()
    {
        List<Case> lstCases = new List<Case>();
        List<Account> lstAccts = new List<Account>();
        List<Contact> lstContacts = new List<Contact>();
        
        Account acc = new Account();
        acc.Name = 'Honeywell Test1';
        acc.Customer_Status__c = 'Active';
        acc.Strategic_Business_Unit__c = 'ATR';
        acc.CBT__c = 'Airbus';
        acc.Region_Name__c = 'Americas';
        acc.Sub_Region_Name__c = 'Canada';
        acc.Service_Level__c = 'Standard';
        acc.Type = 'OEM';
        acc.REPORT_ACCOUNT_NAME__c = 'HONEYWELL TEST1';
        lstAccts.add(acc);
        
        Account acc2 = new Account();
        acc2.Name = 'Honeywell Test11';
        acc2.Customer_Status__c = 'Active';
        acc2.Strategic_Business_Unit__c = 'ATR';
        acc2.CBT__c = 'Airbus';
        acc2.Region_Name__c = 'Americas';
        acc2.Sub_Region_Name__c = 'Canada';
        acc2.Service_Level__c = 'Standard';
        acc2.Type = 'OEM';
        acc2.REPORT_ACCOUNT_NAME__c = 'HONEYWELL TEST11';
        lstAccts.add(acc2);
        
        insert lstAccts;
        
        Contact con = new Contact();
        con.LastName = 'sampath1';
        con.FirstName = 'praveen1';
        con.AccountId = acc.Id;
        con.Primary_Email_Address__c = 'sampathspraveen1@gmail.com';
        con.Email='kapil.nowhere1@gmail.com';
        lstContacts.add(con);
        
        Contact con2 = new Contact();
        con2.LastName = 'LNAME1';
        con2.FirstName = 'FNAME1';
        con2.AccountId = acc2.Id;
        con2.Primary_Email_Address__c = 'mythreyee1.sureshkumar@nttdata.com';
        con2.Email='mythreyee.sureshkumar1@nttdata.com';
        lstContacts.add(con2);
        
        insert lstContacts;
                
        RecordType rt= [select id,name from recordtype where sobjecttype='Case' and name='Quotes'];
        Test.startTest();                    
        Case cs2 = new Case();
        cs2.Emailbox_Origin__c ='Email-Aero GSE Vendor Support';
        cs2.Origin = 'Email';
        cs2.Status = 'Open';
        cs2.ContactId = con.Id;
        cs2.Type='';
        cs2.RecordtypeId=label.GSS_Quotes_Orders;
        //cs2.No_FCR_Reason__c='Not Trained'; For Ticket INC000009687923          
        cs2.Agent_Contact_Flag__c =True;
        cs2.HON_Commit_Date__c=system.now();
        cs2.Classification__c = '';
        cs2.HON_Commit_Date__c = System.now() + 1;
        cs2.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cs2.Government_Compliance_SM_M_Content__c = 'NO';
        lstCases.add(cs2);
        
        cs2 = new Case();
        cs2.Emailbox_Origin__c ='Email-Aero GSE Support';
        cs2.Origin = 'Email';
        cs2.Status = 'Open';
        cs2.ContactId = con.Id;
        cs2.Type='';
        cs2.RecordtypeId=label.GSS_Technical_Support;
        //cs2.No_FCR_Reason__c='Not Trained';  For Ticket INC000009687923         
        cs2.Agent_Contact_Flag__c =True;
        cs2.HON_Commit_Date__c=system.now();
        cs2.Classification__c = 'GTO Field Service';
        cs2.HON_Commit_Date__c = System.now();
        cs2.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cs2.Government_Compliance_SM_M_Content__c = 'NO';
        lstCases.add(cs2);
        
        cs2 = new Case();
        cs2.Emailbox_Origin__c ='Email-Aero GSE Quotes';
        cs2.Origin = 'Email';
        cs2.Status = 'Open';
        cs2.ContactId = con.Id;
        cs2.Type='';
        cs2.RecordtypeId=label.GSS_Quotes_Orders;
        //cs2.No_FCR_Reason__c='Not Trained';    For Ticket INC000009687923       
        cs2.Agent_Contact_Flag__c =True;
        cs2.HON_Commit_Date__c=system.now();
        cs2.Classification__c = '';
        cs2.HON_Commit_Date__c = System.now();
        cs2.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cs2.Government_Compliance_SM_M_Content__c = 'NO';
        lstCases.add(cs2);
        
        cs2 = new Case();
        cs2.Emailbox_Origin__c ='Email-Aero GSE Orders';
        cs2.Origin = 'Email';
        cs2.Status = 'Open';
        cs2.ContactId = con.Id;
        cs2.Type='';
        cs2.RecordtypeId=label.GSS_Quotes_Orders;
        //cs2.No_FCR_Reason__c='Not Trained';   For Ticket INC000009687923        
        cs2.Agent_Contact_Flag__c =True;
        cs2.HON_Commit_Date__c=system.now();
        cs2.Classification__c = '';
        cs2.HON_Commit_Date__c = System.now();
        cs2.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cs2.Government_Compliance_SM_M_Content__c = 'NO';
        lstCases.add(cs2);
        
        cs2 = new Case();
        cs2.Emailbox_Origin__c ='Email-Aero GSE Quotes';
        cs2.Origin = 'Email';
        cs2.Status = 'Open';
        cs2.ContactId = con.Id;
        cs2.Type='';
        cs2.RecordtypeId=label.GSS_Quotes_Orders;
        //cs2.No_FCR_Reason__c='Not Trained';     For Ticket INC000009687923      
        cs2.Agent_Contact_Flag__c =false;
        cs2.HON_Commit_Date__c=system.now();
        cs2.Classification__c = '';
        cs2.HON_Commit_Date__c = System.now();
        cs2.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cs2.Government_Compliance_SM_M_Content__c = 'NO';
        lstCases.add(cs2);
        
        cs2 = new Case();
        cs2.Emailbox_Origin__c ='Email-Aero GSE Orders';
        cs2.Origin = 'Email';
        cs2.Status = 'Open';
        cs2.ContactId = con.Id;
        cs2.Type='';
        cs2.RecordtypeId=label.GSS_Quotes_Orders;
        //cs2.No_FCR_Reason__c='Not Trained';   For Ticket INC000009687923        
        cs2.Agent_Contact_Flag__c =false;
        cs2.HON_Commit_Date__c=system.now();
        cs2.Classification__c = '';
        cs2.HON_Commit_Date__c = System.now();
        cs2.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cs2.Government_Compliance_SM_M_Content__c = 'NO';
        lstCases.add(cs2);
             
        insert lstCases;
        Test.stopTest();
                
        
    }
}