src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/GDMFSL_Integration_Work_Order_Canonical__c.object-meta.xml
<CustomObject>
    <description>Canonical Data Object for Work Order/Service Order Interface to SAP</description>
    <label>FSL Integration Work Order Canonical</label>
    <nameField>
        <displayFormat>FSLINTWO-{0000000000}</displayFormat>
        <label>FSLINTWO Txn Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSL Integration Work Order Canonical</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/Forge_Root_Cause_Code__c.field-meta.xml
<CustomField>
    <fullName>Forge_Root_Cause_Code__c</fullName>
    <label>Forge Root Cause Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/Forge_Service_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Forge_Service_Case_Number__c</fullName>
    <label>Forge Service Case Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/Forge_Site_Id__c.field-meta.xml
<CustomField>
    <fullName>Forge_Site_Id__c</fullName>
    <label>Forge Site Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/IoT_Integration_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>IoT_Integration_Error_Message__c</fullName>
    <label>IoT Integration Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/IoT_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>IoT_Integration_Status__c</fullName>
    <label>IoT Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/Related_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Related_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>FSL Integration Work Order Canonical</relationshipLabel>
    <relationshipName>FSL_Integration_Work_Order_Canonical</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/Resolution_Code__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Code__c</fullName>
    <label>Resolution Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/GDMFSL_Integration_Work_Order_Canonical__c/fields/Work_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Number__c</fullName>
    <label>Work Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/WorkOrder.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder/fields/GDMFSL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

src/objects/WorkOrder/fields/IoT_Integration_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>IoT_Integration_Error_Message__c</fullName>
    <label>IoT Integration Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/WorkOrder/fields/IoT_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>IoT_Integration_Status__c</fullName>
    <label>IoT Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <description>DTXFSL-8130</description>
    <masterLabel>Integration Status</masterLabel>
</GlobalValueSet>

src/classes/CloseCallout_to_forgeIoTTest.cls
@isTest
private class CloseCallout_to_forgeIoTTest {
    
    @testSetup static void setup() {

        Account theAccount = GDMFSL_DataFactory.createTestAccount('TestAcc');
        insert theAccount;

        OperatingHours theOpHours = GDMFSL_DataFactory.createOperatingHour();
        insert theOpHours;

        ServiceTerritory theServiceTerritory = GDMFSL_DataFactory.createServiceTerritory('ServAppt Test', theOpHours.Id);
        insert theServiceTerritory;

        Schema.Location aLocation = GDMFSL_DataFactory.createLocation('Campus',theServiceTerritory.Id);
        insert aLocation;

        List<WorkType> lstworktype = GDMFSL_DataFactory.createWorkTypes('W001',3,30);
        insert lstworktype;

        WorkOrder theWorkOrder = GDMFSL_DataFactory.createWorkOrder(lstworktype[0].Id, theAccount.Id, aLocation.Id, Datetime.valueOfGmt('2020-09-04 18:00:00'), Datetime.valueOfGmt('2020-09-05 18:00:00'));
        theWorkOrder.GDMFSL_PO_Number__c = '12345';
        insert theWorkOrder;

        
        GDMFSL_Integration_Work_Order_Canonical__c woTestRec = new GDMFSL_Integration_Work_Order_Canonical__c();
        woTestRec.End_Date__c = System.today();
        woTestRec.Forge_Root_Cause_Code__c = 'TBD';
        woTestRec.Forge_Service_Case_Number__c='12345';
        woTestRec.Forge_Site_Id__c='12345';
        woTestRec.Priority__c='High';
        woTestRec.Related_Work_Order__c= theWorkOrder.id;
        woTestRec.Resolution_Code__c='TBD';
        woTestRec.Resolution_Notes__c='TBD';
        woTestRec.Status__c='Completed';
        woTestRec.Work_Order_Number__c='00002176';
        
        insert woTestRec;             
    }
        
    @isTest
    static void testGetAccessTokenSuccess()
    {
        GDMFSL_Integration_Work_Order_Canonical__c wo = [SELECT ID,Name,End_Date__c,Forge_Root_Cause_Code__c,Forge_Service_Case_Number__c,
                                                                                   Forge_Site_Id__c,Priority__c,Related_Work_Order__c,
                                                                                   Resolution_Code__c,Resolution_Notes__c,Status__c,Work_Order_Number__c
                                                                                   FROM GDMFSL_Integration_Work_Order_Canonical__c LIMIT 1
                                                                                   ];
        Set<Id> woIdSet = new Set<Id>();
        woIdSet.add(wo.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new getAccessTokenMock());
        CloseCallout_to_forgeIoT.getAccessToken(woIdSet);
        Test.stopTest();
        
        GDMFSL_Integration_Work_Order_Canonical__c wo_obj = [SELECT ID, IoT_Integration_Status__c,IoT_Integration_Error_Message__c 
                                                             		    FROM GDMFSL_Integration_Work_Order_Canonical__c LIMIT 1];
        System.assertEquals('Completed', wo_obj.IoT_Integration_Status__c, 'Integrated Successfully');
    }
    
    @isTest
    static void testGetAccessTokenError()
    {
        GDMFSL_Integration_Work_Order_Canonical__c wo = [SELECT ID,Name,End_Date__c,Forge_Root_Cause_Code__c,Forge_Service_Case_Number__c,
                                                                                   Forge_Site_Id__c,Priority__c,Related_Work_Order__c,
                                                                                   Resolution_Code__c,Resolution_Notes__c,Status__c,Work_Order_Number__c
                                                                                   FROM GDMFSL_Integration_Work_Order_Canonical__c LIMIT 1
                                                                                   ];
        Set<Id> woIdSet = new Set<Id>();
        woIdSet.add(wo.Id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new forgeCloseCalloutMock());
        CloseCallout_to_forgeIoT.getAccessToken(woIdSet);
        Test.stopTest();
        
        GDMFSL_Integration_Work_Order_Canonical__c wo_obj = [SELECT ID, IoT_Integration_Status__c,IoT_Integration_Error_Message__c 
                                                             		    FROM GDMFSL_Integration_Work_Order_Canonical__c LIMIT 1];
        System.assertEquals('Failed', wo_obj.IoT_Integration_Status__c, 'Integration Failed');
    }
    
    @isTest
    static void testInvocableMethod()
    {
        GDMFSL_Integration_Work_Order_Canonical__c wo = [SELECT ID,Name,End_Date__c,Forge_Root_Cause_Code__c,Forge_Service_Case_Number__c,
                                                                                   Forge_Site_Id__c,Priority__c,Related_Work_Order__c,
                                                                                   Resolution_Code__c,Resolution_Notes__c,Status__c,Work_Order_Number__c
                                                                                   FROM GDMFSL_Integration_Work_Order_Canonical__c LIMIT 1
                                                                                   ];
        List<Id> woIdSet = new List<Id>();
        woIdSet.add(wo.Id);
        
        Test.startTest();
        CloseCallout_to_forgeIoT.forgeCloseCallout(woIdSet);
        Test.stopTest();
        
        System.assertEquals(woIdSet.size() > 0, true, 'Work Order Canonical list is not null');
    }
    
}