src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/ICAO_Code__c.field-meta.xml
<CustomField>
    <fullName>ICAO_Code__c</fullName>
    <label>ICAO Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

src/objects/APTS_User_Session_Proposal__c/APTS_User_Session_Proposal__c.object-meta.xml
<CustomObject>
    <label>User Session Proposal</label>
    <nameField>
        <displayFormat>USP-{0000000000}</displayFormat>
        <label>User Session Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Session Proposal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_User_Session_Proposal__c/fields/Proposal_Record_id__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Record_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Proposal Record id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/APTS_User_Session_Proposal__c/fields/User_Session_id__c.field-meta.xml
<CustomField>
    <fullName>User_Session_id__c</fullName>
    <externalId>true</externalId>
    <label>User Session id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Account__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Prospect Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SFDC_520_Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Proposal__Proposal__c/fields/Apttus_Proposal__Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
    <description>The proposal approval stage</description>
    <label>Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>For Configure</fullName>
            </value>
            <value>
                <fullName>For Pricing</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published - In Progress</fullName>
            </value>
            <value>
                <fullName>Published - Ready</fullName>
            </value>
            <value>
                <fullName>Call-off Ready</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rebid</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Closed (Won)</fullName>
            </value>
            <value>
                <fullName>Closed(not won)</fullName>
                <label>Closed (Not Won)</label>
            </value>
            <value>
                <fullName>Required Approval</fullName>
            </value>
            <value>
                <fullName>Requires Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Proposal__Proposal__c/fields/Apttus_QPConfig__BillToAccountId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__BillToAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the bill to account associated with the quote/proposal</description>
    <inlineHelpText>ID of the bill to account associated with the quote/proposal</inlineHelpText>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Bill To)</relationshipLabel>
    <relationshipName>QuotesBillTo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Proposal__Proposal__c/fields/Apttus_QPConfig__ShipToAccountId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_QPConfig__ShipToAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the ship to account associated with the quote/proposal</description>
    <inlineHelpText>ID of the ship to account associated with the quote/proposal</inlineHelpText>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Ship To)</relationshipLabel>
    <relationshipName>QuotesShipTo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/APTS_RedirecttoAcceptTest.cls
@isTest
public class APTS_RedirecttoAcceptTest 
{
    public static testMethod void testAccept() 
    {
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        User usr = new User(LastName = 'Test1',
                           FirstName='Test2',
                           Alias = 'jliv',
                           Email = 'Test1.Test2@sfdc.com',
                           Username = 'Test1.Test2@sfdc.com',
                           EmailEncodingKey='UTF-8',LanguageLocaleKey='en_US',
                           LocaleSidKey='en_US', ProfileId = profileId.Id,
                           TimeZoneSidKey='America/Los_Angeles');
         System.RunAs(usr)
        {                  
        Account objA= new Account();
        objA.name='Test';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_Proposal__Account__c=objA.id;
        insert objp;
        
                           
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getsessionID();
        
        Insert ObjU;
        Update objU;
        
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
        }
    }
    
    public static testMethod void testAccept_Billto() 
    {
        Account objA= new Account();
        objA.name='Test';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__ShipToAccountId__c=objA.id;
        insert objp;
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Developer Administrator (Non US)' LIMIT 1];
        
        User usr = new User(LastName = 'Test1',
                           FirstName='Test2',
                           Alias = 'jliv',
                           Email = 'Test1.Test2@sfdc.com',
                           Username = 'Test1.Test2@sfdc.com',
                           ProfileId = profileId.id);
                           
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = usr.id;
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_shipto() 
    {
        Account objA= new Account();
        objA.name='Test';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__BillToAccountId__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_ICAO() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_Proposal__Account__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_Billto_ICAO() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__ShipToAccountId__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_shipto_ICAO() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__BillToAccountId__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_BS() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        objA.BillingStreet='test';
        objA.BillingCountry='tes1';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_Proposal__Account__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_Billto_BS() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        objA.BillingStreet='test';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__ShipToAccountId__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_shipto_BCity() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        objA.BillingStreet='test';
        objA.BillingCity='test';
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__BillToAccountId__c=objA.id;
        insert objp;
       
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
         Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_Billto_BCity() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        objA.BillingStreet='test';
        objA.BillingCity='test';
       
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__ShipToAccountId__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
    
    public static testMethod void testAccept_shipto_BCity1() 
    {
        Account objA= new Account();
        objA.name='Test';
        objA.ICAO_Code__c='1234';
        objA.BillingStreet='test';
        
        insert objA;
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_QPConfig__BillToAccountId__c=objA.id;
        insert objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
        controller.ProoposalDetails();
    }
     public static testMethod void testAccept_TwoUsers() 
    {
        
        Account objA= new Account();
        objA.Name = 'Test123';
        objA.ICAO_Code__c='1234';
        objA.BillingStreet='test';
        objA.BillingCity='test';
        objA.BillingCountry='tes1';
        insert objA;
        
        Apttus_Proposal__Proposal__c objp= new Apttus_Proposal__Proposal__c();
        objp.Apttus_Proposal__Account__c=objA.id;
        objp.Apttus_Proposal__Approval_Stage__c ='Presented';
        insert objp;
        
        objp.Apttus_Proposal__Approval_Stage__c ='Approved';
        Update objp;
        
        APTS_User_Session_Proposal__c ObjU = new APTS_User_Session_Proposal__c();
        objU.Proposal_Record_id__c = objp.Id;
        objU.User_Session_id__c = userinfo.getuserid();
        
        Insert ObjU;
        Update objU;
             
        Id proposalId = (Id)objp.get('id');
        PageReference pageRef = new PageReference('/' + proposalId);
        Test.setCurrentPage(pageRef);
                        
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objp);
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', proposalId);
        APTS_RedirecttoAccept controller = new APTS_RedirecttoAccept(standardController); 
                      
        controller.ProoposalDetails();
       
       
        }
}