src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/GCE_CSS__c.field-meta.xml
<CustomField>
    <fullName>GCE_CSS__c</fullName>
    <label>GCE CSS Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phoenix/America</fullName>
            </value>
            <value>
                <fullName>Hangzhou/APAC</fullName>
            </value>
            <value>
                <fullName>Chennai/America</fullName>
            </value>
            <value>
                <fullName>Chennai/EMEAI</fullName>
            </value>
            <value>
                <fullName>Chennai/APAC</fullName>
            </value>
            <value>
                <fullName>Bangalore/America</fullName>
            </value>
            <value>
                <fullName>Bangalore/EMEAI</fullName>
            </value>
            <value>
                <fullName>Bangalore/APAC</fullName>
            </value>
            <value>
                <fullName>Puerto Rico/America</fullName>
            </value>
            <value>
                <fullName>Puerto Rico/APAC</fullName>
            </value>
            <value>
                <fullName>Puerto Rico/EMEAI</fullName>
            </value>
            <value>
                <fullName>Lodz/EMEAI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/GCE_CSS_Assignment__c.field-meta.xml
<CustomField>
    <fullName>GCE_CSS_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact used for use by the Global Customer Experience organization</description>
    <label>GCE CSS Assignment</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>GCE CSS Assignment on Account can have only Active contacts</errorMessage>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (GCE CSS Assignment)</relationshipLabel>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/GCE_CSS_Type__c.field-meta.xml
<CustomField>
    <fullName>GCE_CSS_Type__c</fullName>
    <description>For use by the Global Customer Experience Organization</description>
    <label>GCE CSS Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dedicated</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Team</fullName>
                <isActive>false</isActive>
                <label>Team</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/GCE_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>GCE_Customer_Segment__c</fullName>
    <description>for use by Global Customer Experience group</description>
    <label>GCE Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Military/Government</fullName>
            </value>
            <value>
                <fullName>CP &amp; Owner/Operator</fullName>
            </value>
            <value>
                <fullName>Non-Customer</fullName>
            </value>
            <value>
                <fullName>OEM – Restricted</fullName>
            </value>
            <value>
                <fullName>DOD/DLA</fullName>
                <isActive>false</isActive>
                <label>DOD/DLA</label>
            </value>
            <value>
                <fullName>Owner/Operators</fullName>
                <isActive>false</isActive>
                <label>Owner/Operators</label>
            </value>
            <value>
                <fullName>Vendor/Supplier</fullName>
                <isActive>false</isActive>
                <label>Vendor/Supplier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Sbl_Account_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Sbl Account Row ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Account/fields/SFDC_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Row_Id__c</fullName>
    <displayFormat>A-{0000000}</displayFormat>
    <inlineHelpText>Defines unique SFDC account number. To be used to link data in external systems.</inlineHelpText>
    <label>SFDC Row ID</label>
    <type>AutoNumber</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Sbl_Account_Row_ID__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_ID__c</fullName>
    <label>Sbl Account Row ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/classes/GetGCECustomerAccountDetails.cls
/*********
*** @@ DESC : This Rest Service Class will expose the service with Customer Details Based on Customer Segement filter.
*** @@ COMPONENTName : GetGCECustomerAccountDetails
*** @@ URL MAPPING : /services/apexrest/GetGCECustomerAccountDetails
*** @@ REST METHOD : POST
*** @@ Request Parameters : HonOrgId,GCESegment
*** @@ Response Parameters : GCESegment,CustomerName,CRMID,CSSAssignment,CSSRegion,CSSType
*** @@ Response Type : JSON Format
**********/
@RestResource(urlMapping='/GetGCECustomerAccountDetails/*')
global with sharing class GetGCECustomerAccountDetails{
    // POST Method 
    @HttpPost
    global static Void doPost(){
        List<GCECustomerDetails> listcustomerdetails = new List<GCECustomerDetails>();
        RestRequest  req = RestContext.request;
        RestResponse res = RestContext.response;
        try{
            String segments = System.Label.Appian_Case_Segments;
            res.addHeader('Content-Type', 'application/json');
            GCESegmentDetail reqdetails = (GCESegmentDetail)JSON.deserializeStrict(req.requestBody.toString(),GCESegmentDetail.class);
            String query = 'Select Id,Name,AccountNumber,Sbl_Account_Row_Id__c,GCE_CSS_Assignment__c,GCE_CSS_Assignment__r.Name,GCE_CSS__c,GCE_CSS_Type__c,GCE_Customer_Segment__c,SFDC_Row_Id__c FROM Account Where Customer_Status__c = \'Active\' AND ';
            if(reqdetails.GCESegment == '' || reqdetails.GCESegment == null || reqdetails.GCESegment == 'All'){
                query += ' ( ';
                List<String> listsegments = segments.split(',');
                for(Integer i=1; i<=listsegments.size(); i++){
                    query += ' GCE_Customer_Segment__c = \''+listsegments[i-1]+'\' ';
                    if(i != listsegments.size())
                    query += ' OR ';
                }
                query += ' ) ';
            }else{
                query += ' GCE_Customer_Segment__c =\''+reqdetails.GCESegment+'\'';
            }
            query += ' ORDER BY Sbl_Account_Row_Id__c DESC LIMIT 50000';
            for(Account eachacc : DataBase.query(query)){
                listcustomerdetails.add(new GCECustomerDetails(eachacc.GCE_Customer_Segment__c, eachacc.Name, eachacc.Sbl_Account_Row_Id__c, eachacc.GCE_CSS_Assignment__r.Name, eachacc.GCE_CSS__c, eachacc.GCE_CSS_Type__c )); //, eachacc.SFDC_Row_Id__c
            }
            res.statusCode = 200;
            res.responseBody = listcustomerdetails.size()>0 ? Blob.valueOf(JSON.serializePretty(listcustomerdetails)) : Blob.valueOf('No Data Found');
        }catch(Exception ex){
            res.statusCode = 500;
            res.responseBody = Blob.valueOf('The following exception has occurred: '+ex.getTypeName() + ' - ' + ex.getCause() + ': ' + ex.getMessage());
        }
    }
    // Request Parameters 
    global class GCESegmentDetail{
        global String HonOrgId;
        global String GCESegment;
        global GCESegmentDetail(){
        }
    }
    // Response Parameters
    global class GCECustomerDetails{
        global String GCESegment;
        global String CustomerName;
        global String CRMID;
        global String CSSAssignment;
        global String CSSRegion;
        global String CSSType;
        //global String CustomerAccountNumber;
        global GCECustomerDetails(String GCESegment, String CustomerName, String CRMID, String CSSAssignment, String CSSRegion, String CSSType ){ // , String CustomerAccountNumber
            this.GCESegment             = GCESegment;
            this.CustomerName           = CustomerName;
            this.CRMID                  = CRMID;
            this.CSSAssignment          = CSSAssignment;
            this.CSSRegion              = CSSRegion;
            this.CSSType                = CSSType;
            //this.CustomerAccountNumber  = CustomerAccountNumber;
        }
    }
}