src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <formula>TEXT( Account.Strategic_Business_Unit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Contract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adv Payment</fullName>
            </value>
            <value>
                <fullName>APM</fullName>
            </value>
            <value>
                <fullName>APU Selection Agreement</fullName>
            </value>
            <value>
                <fullName>Asset Availability - Other</fullName>
            </value>
            <value>
                <fullName>Authorized Service Centers</fullName>
            </value>
            <value>
                <fullName>Avionics Selection Agreement</fullName>
            </value>
            <value>
                <fullName>Bailment Agreement</fullName>
            </value>
            <value>
                <fullName>BFE</fullName>
            </value>
            <value>
                <fullName>BOA</fullName>
            </value>
            <value>
                <fullName>CBL</fullName>
            </value>
            <value>
                <fullName>Cost Reimbursable</fullName>
            </value>
            <value>
                <fullName>Cost Share</fullName>
            </value>
            <value>
                <fullName>CPAL</fullName>
            </value>
            <value>
                <fullName>CPFF</fullName>
            </value>
            <value>
                <fullName>CPIF</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale ACES Based</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale Non ACES Based</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Designee Agreement</fullName>
            </value>
            <value>
                <fullName>Development Contract</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>EMCPP</fullName>
            </value>
            <value>
                <fullName>Exchange Agreement</fullName>
            </value>
            <value>
                <fullName>FFP</fullName>
            </value>
            <value>
                <fullName>Fixed Fee Incentive</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>FMP</fullName>
            </value>
            <value>
                <fullName>FMS</fullName>
            </value>
            <value>
                <fullName>FPPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract/recordTypes/Contracts.recordType-meta.xml
<RecordType>
    <fullName>Contracts</fullName>
    <active>true</active>
    <label>Contracts</label>
</RecordType>

src/objects/Entitlement__c/Entitlement__c.object-meta.xml
<CustomObject>
    <label>Entitlement</label>
    <nameField>
        <displayFormat>EN-{0}</displayFormat>
        <label>Entitlement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Entitlement__c/fields/Case_Creation__c.field-meta.xml
<CustomField>
    <fullName>Case_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Creation</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Entitlement__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Contract Number</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Entitlement__c/fields/Entitlement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Start_Date__c</fullName>
    <label>Entitlement Start Date</label>
    <type>Date</type>
</CustomField>

src/objects/Entitlement__c/fields/Entitlement_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Sub_Type__c</fullName>
    <label>Entitlement Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APU Selection</fullName>
            </value>
            <value>
                <fullName>LPO</fullName>
            </value>
            <value>
                <fullName>MCBL</fullName>
            </value>
            <value>
                <fullName>NCFR</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>R&amp;O</fullName>
            </value>
            <value>
                <fullName>Reliability Remedy</fullName>
            </value>
            <value>
                <fullName>Repair Volume Discount</fullName>
            </value>
            <value>
                <fullName>Sales Incentive</fullName>
            </value>
            <value>
                <fullName>Supply Agreement</fullName>
            </value>
            <value>
                <fullName>TAT Remedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Entitlement__c/fields/Entitlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Type__c</fullName>
    <label>Entitlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accrual - Reserve</fullName>
            </value>
            <value>
                <fullName>AFGS XM Subscription</fullName>
            </value>
            <value>
                <fullName>AFIS Datalink WX Graphics Annual</fullName>
            </value>
            <value>
                <fullName>Aircraft</fullName>
            </value>
            <value>
                <fullName>Aircraft Equipment</fullName>
            </value>
            <value>
                <fullName>Aircraft - Renewal</fullName>
            </value>
            <value>
                <fullName>Air Partners Flight Support Services</fullName>
            </value>
            <value>
                <fullName>Airsprint Flight Support Services</fullName>
            </value>
            <value>
                <fullName>Annual Datalink Satellite Package</fullName>
            </value>
            <value>
                <fullName>Annual Fax Plan</fullName>
            </value>
            <value>
                <fullName>Apex XN Subscription</fullName>
            </value>
            <value>
                <fullName>APU Rental</fullName>
            </value>
            <value>
                <fullName>Atlas Air</fullName>
            </value>
            <value>
                <fullName>Availability Remedy</fullName>
            </value>
            <value>
                <fullName>Bailed / Consigned Assets</fullName>
            </value>
            <value>
                <fullName>Basic Eastern Package</fullName>
            </value>
            <value>
                <fullName>Basic Western Package</fullName>
            </value>
            <value>
                <fullName>Basic Worldwide Package</fullName>
            </value>
            <value>
                <fullName>Boeing Defense &amp; Space Group</fullName>
            </value>
            <value>
                <fullName>Clos de Berry Custom Plan</fullName>
            </value>
            <value>
                <fullName>Collins Datalink Graphical Weather</fullName>
            </value>
            <value>
                <fullName>Contract Price Load</fullName>
            </value>
            <value>
                <fullName>Core Return Remedy</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>End-of-Term Activities</fullName>
            </value>
            <value>
                <fullName>Entry to Production</fullName>
            </value>
            <value>
                <fullName>Epic Datalink Graphical Weather</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Field Arising LRUs</fullName>
            </value>
            <value>
                <fullName>Flight Sentinel Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Entitlement__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Entitlement__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <formula>Contract_Number__r.SBU__c</formula>
    <label>SBU</label>
    <type>Text</type>
</CustomField>

src/classes/UsageCountRollup_Test.cls
@istest
public class UsageCountRollup_Test {
    public static testmethod void method1(){
    Id devRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Training Contracts').getRecordTypeId();
	Account acc = new Account();
    acc.Name = 'test account';
    acc.Strategic_Business_Unit__c = 'ATR';
    insert acc;    
    Contract ctr = new Contract();
    ctr.RecordTypeId = devRecordTypeId;
    ctr.Status = 'New';
    ctr.StartDate = system.Today();
    ctr.Type__c = 'APM';
    ctr.AccountId = acc.id;
    //ctr.SBU__c = 'ATR';
    insert ctr;
        
    Entitlement__C etc = new Entitlement__C();
    etc.Contract_Number__c = ctr.id;
    etc.Entitlement_Type__c = 'Escalation';
	etc.Entitlement_Sub_Type__c = 'Other';
    etc.Entitlement_Start_Date__c = System.today();
    etc.Reference__c = 'test';
    //etc.SBU__c = 'ATR';
    insert etc;
    etc.Case_Creation__c = true;
    update etc;
    }
}