src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Aircraft_Tail_Number__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Tail_Number__c</fullName>
    <label>Aircraft Tail Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL/Ex</fullName>
            </value>
            <value>
                <fullName>CSP/CSP Gold</fullName>
            </value>
            <value>
                <fullName>EMCPP</fullName>
            </value>
            <value>
                <fullName>HAPP</fullName>
            </value>
            <value>
                <fullName>ISS</fullName>
            </value>
            <value>
                <fullName>MPP</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSP/MSP Gold</fullName>
            </value>
            <value>
                <fullName>SPEX</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Firm Fixed Price</fullName>
            </value>
            <value>
                <fullName>FFP - Level-Of-Effort</fullName>
            </value>
            <value>
                <fullName>FFP - Materials Reimbursement</fullName>
            </value>
            <value>
                <fullName>Fixed Price Contract With Economic Price Adjustment</fullName>
            </value>
            <value>
                <fullName>Fixed Price - Fixed Price Incentive</fullName>
            </value>
            <value>
                <fullName>Fixed Price - Redetermination</fullName>
            </value>
            <value>
                <fullName>Cost Reimbursement</fullName>
            </value>
            <value>
                <fullName>Cost-Plus Fixed Fee (CPFF)</fullName>
            </value>
            <value>
                <fullName>Cost-Plus Award Fee (CPAF)</fullName>
            </value>
            <value>
                <fullName>Cost-Plus Incentive Fee (CPIF)</fullName>
            </value>
            <value>
                <fullName>Indefinite Delivery</fullName>
            </value>
            <value>
                <fullName>Indefinite Delivery, Indefinite Qty (IDIQ)</fullName>
            </value>
            <value>
                <fullName>Requirements</fullName>
            </value>
            <value>
                <fullName>Time and Material (T&amp;M)</fullName>
            </value>
            <value>
                <fullName>Labor-Hours</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>NTE</fullName>
            </value>
            <value>
                <fullName>Unpriced Orders</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>Standard Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Detail_Class__c.field-meta.xml
<CustomField>
    <fullName>Detail_Class__c</fullName>
    <label>Detail Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Class__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACARS Weather Graphics</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Issues – Tech Pubs</fullName>
            </value>
            <value>
                <fullName>Account Change</fullName>
            </value>
            <value>
                <fullName>Account Services</fullName>
            </value>
            <value>
                <fullName>Acknowledgement</fullName>
            </value>
            <value>
                <fullName>ACM</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>ACUKWIK</fullName>
            </value>
            <value>
                <fullName>Adaptiv Requests</fullName>
            </value>
            <value>
                <fullName>Add/Rem Option</fullName>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>ADDRESS UPDATE</fullName>
            </value>
            <value>
                <fullName>Advance Exchange</fullName>
            </value>
            <value>
                <fullName>AERO C</fullName>
            </value>
            <value>
                <fullName>AERO-H, H+, I</fullName>
            </value>
            <value>
                <fullName>Aerospace Catalog</fullName>
            </value>
            <value>
                <fullName>AIRCELL</fullName>
            </value>
            <value>
                <fullName>Aircraft Nav Computer/Software Issue</fullName>
            </value>
            <value>
                <fullName>Aircraft Report Delivery</fullName>
            </value>
            <value>
                <fullName>Air Waybill Number</fullName>
            </value>
            <value>
                <fullName>Alternate Part Number</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>AOG – IFSD Commanded</fullName>
            </value>
            <value>
                <fullName>AOG – IFSD Uncommanded</fullName>
            </value>
            <value>
                <fullName>AOG - IFS Technical / Alert</fullName>
            </value>
            <value>
                <fullName>AOG - Parts Request</fullName>
            </value>
            <value>
                <fullName>APG</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

src/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RMU Name</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases (Product)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <formula>Product_Number__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Part #</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Product_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Part_Number__c</fullName>
    <label>Product Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Serv_Contract__c.field-meta.xml
<CustomField>
    <fullName>Serv_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Inside_Sales__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fleet_Asset_Aircraft3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>The Serial Number of the current Fleet entry.</inlineHelpText>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Tail_Number__c.field-meta.xml
<CustomField>
    <fullName>Tail_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Fleet entry&apos;s registered Tail Number.</inlineHelpText>
    <label>Tail Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Inside_Sales__c/Inside_Sales__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inside Sales</label>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task/recordTypes/MSPAv_Mech_Task.recordType-meta.xml
<RecordType>
    <fullName>MSPAv_Mech_Task</fullName>
    <active>true</active>
    <label>MSPAv/Mech Task</label>
</RecordType>

src/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tact</description>
    <label>Task</label>
</RecordType>

src/classes/CreateTaskForCase.cls
global class CreateTaskForCase implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){   
        Date ClosedDate = System.now().dateGMT();
        String Closed = 'Closed';
        String repairOverHaul = 'Repair & Overhaul';
        String aog  = 'AOG';
        String orders = 'Orders';
        String Exchange= 'Exchange';//added for AOG/Spex Case Record Type Split
        String bga = 'BGA';
        String closedAsDuplicate = 'Closed as Duplicate';
        String blank = '';
        String query = 'SELECT Due_Date__c,AccountId,Aircraft_Tail_Number__c,Aircraft_Serial_Number__c,ClosedDate,Product_Code__c,Product_Part_Number__c, Product_Part__c,product__c,id,RecordType.Name,Sub_Class__c,Type,Classification__c,Sales_Order_Number__c,Detail_Class__c,Account.Strategic_Business_Unit__c FROM Case where (RecordType.Name=:repairOverHaul or RecordType.Name=:Exchange or RecordType.Name=:aog or RecordType.Name=:orders) and ClosedDate >=:ClosedDate'+ 
        ' and Account.Strategic_Business_Unit__c=:bga and Status <>:closedAsDuplicate '+
        ' and Sales_Order_Number__c <>:blank and Status = :Closed and Serv_Contract__c =:blank and Contract_Number__c =:blank and Contract_Type__c =:blank and Aircraft_Tail_Number__c<>:blank and Aircraft_Serial_Number__c<>:blank';//added for AOG/Spex Case Record Type Split
        SYstem.debug('ClosedDate value:'+ClosedDate);
        System.debug('query is---------->'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Case> caseRecords){
        try{
            String blank = '';
            map<String,Case> caseMap = new map<String,Case>();
            set<String> tailNumber = new set<String>();
            for(Case caseRec:caseRecords){
                tailNumber.add(caseRec.Aircraft_Tail_Number__c);
                caseMap.put(caseRec.Aircraft_Tail_Number__c+caseRec.Aircraft_Serial_Number__c,caseRec);
            }
            List<Fleet_Asset_Detail__c> fadList = new list<Fleet_Asset_Detail__c>();
            List<Task> taskList = new List<Task>();
            for(Fleet_Asset_Detail__c fadRec:[select id,Inside_Sales__c,Tail_Number__c,Serial_Number__c from Fleet_Asset_Detail__c where Tail_Number__c in :tailNumber and Serial_Number__c<>:blank]){
                string key = fadRec.Tail_Number__c+fadRec.Serial_Number__c;
                 System.debug('task1 is---------->'+tasklist);
                if(caseMap.get(key) != null){
                 System.debug('task2 is---------->'+taskList );
                    Case caseRec = caseMap.get(key);
                    Task t = new Task(); 
                    t.OwnerId = '0051300000CUHXF';
                    t.Subject = 'SPEX Billable Order';
                    t.Priority = 'Normal';
                    t.Status = 'Not Started';
                    t.Description = 'SPEX Billable Order';
                    t.whatId = caseRec.Id;
                    t.ActivityDate = caseRec.Due_Date__c;
                    t.RecordTypeId = Label.MSPAv_Mech_Task;
                    taskList.add(t);  
                }
            }
            insert taskList;
             System.debug('task3 is---------->'+taskList );
        }catch(Exception e){
            System.debug('Error1 : '+e.getMessage()); 
            System.debug('Error line1 : '+e.getLineNumber());
        }        
    }
      
    global void finish(Database.BatchableContext BC){
      // Nothing here.
    }   
}