src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <description>Business Segment is relabeled as CBT as per Business request.</description>
    <inlineHelpText>A further division into Business Segments within the Strategic Business Unit/Market (e.g., Aftermarket, Airlines, Military/Operators, etc.)</inlineHelpText>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES CBT</fullName>
            </value>
            <value>
                <fullName>DEW</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
                <label>Embraer D&amp;S</label>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <inlineHelpText>One of three strategic regions: EMEAI, APAC, Americas.  This value is assigned based on the Sub-Region Name.  EMEAI = Europe, Middle East, Africa, India.  APAC = Asia Pacific.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Asia/Pacific Rim</fullName>
            </value>
            <value>
                <fullName>Europe/MiddleEast/Africa/India</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/REPORT_ACCOUNT_NAME__c.field-meta.xml
<CustomField>
    <fullName>REPORT_ACCOUNT_NAME__c</fullName>
    <label>REPORT ACCOUNT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <inlineHelpText>A category that indicates the type of service the customer is expected to receive, as determined by HON business entities based on sales, anticipated opportunities, etc.</inlineHelpText>
    <label>Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Refer to Network</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Superior</fullName>
            </value>
            <value>
                <fullName>Unauthorized Dist/Brkr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Sub_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_Name__c</fullName>
    <inlineHelpText>A specific country or area that is derived from a larger region or continent.  It is generally based on location (Europe, Middle East, Japan, etc.) but occasionally is based on business divisions</inlineHelpText>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region_Name__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Australia / NZ</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>China / HKG</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Russia and CU</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <formula>Text(Account.CBT__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CBT</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <formula>TEXT(Account.Customer_Status__c)</formula>
    <label>Customer Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Platform</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Platform must be an active platform.</errorMessage>
        <filterItems>
            <field>Platform__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>API DATA LOAD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Cases (Platform)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <formula>TEXT( Account.Service_Level__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Level</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU_Contact__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S Other CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
            <value>
                <fullName>General Atomics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Tail_Number__c.field-meta.xml
<CustomField>
    <fullName>Tail_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Fleet entry&apos;s registered Tail Number.</inlineHelpText>
    <label>Tail Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/TestClass_Update_OnBehalfendUserStatus.cls
/***********************************************************************************************************
* Company Name          : Honeywell Aero
* Name                  : TestClass_Update_OnBehalfendUserStatus
* Description           : Test Class to test the functionality of the trigger Update_OnBehalfendUserStatus.
* 
* Modification History  :
* Date             Version No.    Modified by           Brief Description of Modification
* 04-Apr-2013      0.01           NTTData              Initial Version
***********************************************************************************************************/
@isTest(SeeAllData=true)
private class TestClass_Update_OnBehalfendUserStatus
{
    static testMethod void TestMthd_Update_OnBehalfendUserStatus()
    {
           
/*Account objAccnt = new Account();
        objAccnt.Name = 'Honeywell Test';
        objAccnt.Customer_Status__c = 'Active';
        objAccnt.Strategic_Business_Unit__c = 'D&S';
        objAccnt.CBT__c = 'DAA';
        objAccnt.Region_Name__c = 'Americas';
        objAccnt.Sub_Region_Name__c = 'Canada';
        objAccnt.Service_Level__c = 'Standard';
        objAccnt.Type = 'OEM';
        objAccnt.REPORT_ACCOUNT_NAME__c = 'HONEYWELL TEST';        
        insert objAccnt;*/
        Account objAccnt = [select id from account where(not name like '%various%') and (not name like '%Aero Level Adjust%') and Customer_Status__c = 'Active' and Strategic_Business_Unit__c = 'D&S' and CBT__c = 'DAA' and Region_Name__c = 'Americas' and Sub_Region_Name__c = 'Canada' and Service_Level__c = 'Standard' and Type = 'OEM' limit 1];
  
         Platform__c pltFrm = new Platform__c(name='Test Platform');
        insert pltFrm;

Fleet_Asset_Detail__c fltast = new Fleet_Asset_Detail__c(Name = 'Test Make Test Model',Tail_Number__c = '5555',Serial_Number__c = '6666',Platform_Name__c=pltFrm.id );
        insert fltast;
        
/*Contact objContact = new Contact();
        objContact.LastName = 'SureshKumar';
        objContact.FirstName = 'Mythreyee';
        objContact.AccountId = objAccnt.Id;
        objContact.Primary_Email_Address__c = 'mythreyee.sureshkumar@nttdata.com';
        objContact.Email='mythreyee.sureshkumar@nttdata.com';        
        insert objContact;*/
            Contact objContact = [select id from contact where Survey_Opt_Out__c = False and NPS_Survey__c = 'No' and CreatedDate > 2014-08-03T05:35:18.000+0000 limit 1];
             //Contact objContact2 = [select id from contact where Survey_Opt_Out__c = False and NPS_Survey__c = 'No' and CreatedDate > 2014-08-03T05:35:18.000+0000 limit 1];
       /* Contact objContact2 = new Contact();
        objContact2.LastName = 'Contact';
        objContact2.FirstName = 'Test';
        objContact2.AccountId = objAccnt.Id;
        objContact2.Primary_Email_Address__c = 'mythreyee.sureshkumar@honeywell.com';
        objContact2.Email='mythreyee.sureshkumar@honeywell.com';        
        insert objContact2;*/

    Case objCase = new Case();
        objCase.recordtypeid = label.Pilot_s_Corner_Avionics_RT_ID;
        objCase.contactid = objContact.id;
        objcase.status='On Hold';
        objcase.status='Open';
        objcase.status='Re-open';
        objcase.Aircraft_Name__c = fltast.Id;
        objcase.Sub_Status__c = 'Hyper Consumption';
        objcase.Type='AOG';
        insert objCase;
        objcase.Type='AOG';
        objcase.Time_of_first_Type_Change__c=System.Today();
        objcase.contactid =objContact.id;
         // objCase.recordtypeid = label.Case_AOG_RecordType;
        update objcase;
        System.debug('121212 2');        
       /* Case objCase2 = new Case();
        //objCase2.recordtypeid = label.Pilot_s_Corner_Avionics_RT_ID;
        objCase2.origin = 'Email-deferredordersweb';
        objCase2.Emailbox_Origin__c  = 'Email-deferredordersweb';
        objCase2.contactid = objContact.id;
        objcase2.status='On Hold';
        objcase2.status='Open';
        objcase2.status='Re-open';
        objcase2.Aircraft_Name__c = fltast.Id;
        objcase2.Sub_Status__c = 'Hyper Consumption';
        objcase2.subject='WebOrder; Advance Exchange; Warranty verification required[0004573049|3075583-2|111|Warranty Verification Required|SPEX]';
        objcase2.Type='AOG';
        insert objCase2;*/
        System.debug('121212 1');
        String[] toAddresses = new String[] {'deferredordersweb@honeywell.com','deferredordersweb@28o5tqj2bbtrs7m2j5t1yudii1nnyvywt159wq9om55qbuo0ce.e-dcwdeas.el.case.sandbox.salesforce.com'}; 
        
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
         // Who you are sending the email to
         message.setToAddresses(toAddresses);
         //message.setWhatId(cas.Id);
         // The email template ID used for the email
         message.setsubject('WebOrder; Advance Exchange; Warranty verification required[0004573049|3075583-2|111|Warranty Verification Required|SPEX]');
         message.setBccSender(false);
         message.setUseSignature(false);
         //message.setReplyTo('yourresponse@honeywell.com');
         //message.setSenderDisplayName('yourresponse@honeywell.com');
         message.setHtmlBody('Your case:<b>  Testing  </b>');
         message.setOrgWideEmailAddressId('0D2300000008P9e');
         message.setSaveAsActivity(false); 
         Messaging.sendEmail(new Messaging.SingleEmailMessage[] {message});
         
         
 /*objCase = new Case();
        objCase.recordtypeid = label.Pilot_s_Corner_Avionics_RT_ID;
        objCase.contactid = objContact.id;
        objcase.origin= 'Email-deferredordersweb';
objcase.Emailbox_Origin__c= 'Email-deferredordersweb';
objcase.subject= 'test[1|2|3|4|5]';

        objcase.status='Open';
        insert objCase;*/
        
objcase = new Case(id=objCase.id);
        objcase.status='On Hold';

        update objcase;   
/*
objcase = new Case(id=objCase.id);
        objcase.status='Open';

        update objcase;   */
        
    }
}