src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/REPORT_ACCOUNT_NAME__c.field-meta.xml
<CustomField>
    <fullName>REPORT_ACCOUNT_NAME__c</fullName>
    <label>REPORT ACCOUNT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Aircraft_Tail_Number__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Tail_Number__c</fullName>
    <label>Aircraft Tail Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <formula>TEXT(Account.Customer_Status__c)</formula>
    <label>Customer Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Platform</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Platform must be an active platform.</errorMessage>
        <filterItems>
            <field>Platform__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>API DATA LOAD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Cases (Platform)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Serv_Contract__c.field-meta.xml
<CustomField>
    <fullName>Serv_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Account)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contract/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <formula>Aircraft__r.Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Account (Customer) Name associated with this Fleet entry.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND ( NOT 2)</booleanFilter>
        <errorMessage>Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Account)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Aircraft_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Delivery_Date__c</fullName>
    <label>Aircraft Delivery Date</label>
    <type>Date</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Inside_Sales__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fleet_Asset_Aircraft3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>The Serial Number of the current Fleet entry.</inlineHelpText>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Tail_Number__c.field-meta.xml
<CustomField>
    <fullName>Tail_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Fleet entry&apos;s registered Tail Number.</inlineHelpText>
    <label>Tail Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Inside_Sales__c/Inside_Sales__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inside Sales</label>
</CustomObject>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/UnitTest_CreateTaskForCase.cls
@isTest
public class UnitTest_CreateTaskForCase{
    testMethod static void testCreateTaskForCase(){
      
       Id RecordTypeIdCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Repair & Overhaul').getRecordTypeId();
       system.debug('RecordTypeIdCase value:'+RecordTypeIdCase);
       Account acct = new Account(Name='Test',Customer_Status__c='Active',REPORT_ACCOUNT_NAME__c='Testing');
       acct.Strategic_Business_Unit__c='BGA';
       
        insert acct;
      Platform__c pla =new Platform__c();
        insert pla;
       Fleet_Asset_Detail__c faa = new Fleet_Asset_Detail__c();
      
       faa.Aircraft_Delivery_Date__c = Date.today();
       faa.Platform_Name__c = pla.id;
       faa.Account__c = acct.id;
       faa.Inside_Sales__c=UserInfo.getUserId();
       faa.Aircraft_Delivery_Date__c = Date.today().addMonths(-22);
       
       insert faa;
       
       Fleet_Asset_Detail__c faa1 = new Fleet_Asset_Detail__c();
      
       faa1.Aircraft_Delivery_Date__c = Date.today();
       faa1.Platform_Name__c = pla.id;
       faa1.Account__c = acct.id;
       faa1.Inside_Sales__c=UserInfo.getUserId();
       faa1.Aircraft_Delivery_Date__c = Date.today().addMonths(-22);
       faa1.Tail_Number__c = '1234';
       faa1.Serial_Number__c = '1234'; 
       insert faa1;
      Contract contractRec = new Contract();
      contractRec.AccountId = acct.id;
      insert contractRec;
       Test.startTest();
      acct = [select id,Strategic_Business_Unit__c from Account where id=:acct.id];
      Case caseRec = new Case();
      caseRec.createdDate = System.today().addMonths(-2);
      caseRec.Status ='Closed';
      caseRec.Sales_Order_Number__c ='123';
      //caseRec.Serv_Contract__c = contractRec.id;
      caseRec.Aircraft_Tail_Number__c = '1234';
      caseRec.Aircraft_Serial_Number__c ='1234';
      caseRec.RecordTypeId = RecordTypeIdCase;
      caseRec.AccountId = acct.id;
      caseRec.ClosedDate = System.now().dateGMT();
      insert caseRec;
      
      Account acctTemp = [select id,Customer_Status__c,REPORT_ACCOUNT_NAME__c,Strategic_Business_Unit__c from Account where id=:acct.id];
      system.debug('Account record details:'+acctTemp);
       Case recr = [select AccountId from Case];
       recr.AccountId = acct.id;
       update recr;
       recr = [select AccountId from Case];
       system.debug('recr Value:'+recr.AccountId);
       CreateTaskForCaseScheduler p = new CreateTaskForCaseScheduler(); //Schedule apex class name
       String sch = '0 0 * * * ?'; //schedule interval time
       system.schedule('One Time Pro', sch, p); //system method to schedule apex class*/
       
        
       CreateTaskForCase ct = new CreateTaskForCase();
       database.executebatch(ct,200);
       Test.stopTest();
    }
}