src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Notes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Additional_Web_Form_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Web_Form_Info__c</fullName>
    <label>Additional Web Form Info</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Aircraft_Name__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft Name</label>
    <referenceTo>Fleet_Asset_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Aircraft_Owner_Operator__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Owner_Operator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft Owner/Operator</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Aircraft Owner/Operator)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/BGA_Dealer_Name__c.field-meta.xml
<CustomField>
    <fullName>BGA_Dealer_Name__c</fullName>
    <label>BGA Dealer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Dollar_Amount__c.field-meta.xml
<CustomField>
    <fullName>Dollar_Amount__c</fullName>
    <label>Dollar Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Case/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Changed the Field Type from Textarea  to Textarea(Long) for SR 432766.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Rejection_Comments__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Comments__c</fullName>
    <label>Rejection Comments</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1st Follow-up</fullName>
            </value>
            <value>
                <fullName>2nd Follow-up</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Accelerated Repair</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>Accts</fullName>
            </value>
            <value>
                <fullName>Acknowledgement Provided</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Administrative Hold -Z8</fullName>
            </value>
            <value>
                <fullName>Advanced Troubleshooting</fullName>
            </value>
            <value>
                <fullName>After-exp queue</fullName>
            </value>
            <value>
                <fullName>AIDC Quote Hold</fullName>
            </value>
            <value>
                <fullName>Aircraft In Maintenance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>ATS</fullName>
            </value>
            <value>
                <fullName>ATS (Tech Support) Hold</fullName>
            </value>
            <value>
                <fullName>Aviation Services</fullName>
            </value>
            <value>
                <fullName>Awaiting Amended PO-Z2</fullName>
            </value>
            <value>
                <fullName>Awaiting billing review</fullName>
            </value>
            <value>
                <fullName>Awaiting Client reply for more info</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Verification</fullName>
            </value>
            <value>
                <fullName>Awaiting credit review</fullName>
            </value>
            <value>
                <fullName>Awaiting MSP review</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting reply from ICARUS</fullName>
            </value>
            <value>
                <fullName>AWB Sent</fullName>
            </value>
            <value>
                <fullName>B/E Quote Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <inlineHelpText>Defines Comments associated with the current Fleet Asset.</inlineHelpText>
    <label>Comments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <formula>Platform_Name__r.Make__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aircraft Make</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Platform_Name__r.Model__c</formula>
    <label>Aircraft Model</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>The Serial Number of the current Fleet entry.</inlineHelpText>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Tail_Number__c.field-meta.xml
<CustomField>
    <fullName>Tail_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Fleet entry&apos;s registered Tail Number.</inlineHelpText>
    <label>Tail Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Raw</businessProcess>
        <label>Outbound</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <label>Export Compliance Content (ITAR/EAR)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Queue GTO</fullName>
            </value>
            <value>
                <fullName>Compliance Queue CSO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Lead/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <label>Government Compliance/SM&amp;M Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Queue GTO</fullName>
            </value>
            <value>
                <fullName>Compliance Queue CSO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/caseWithAircraftWebServiceController.cls
@RestResource(urlMapping='/AerospaceAircraftCaseServices/*')
global without sharing class caseWithAircraftWebServiceController {

    @HttpPost
    global static void doPost()
    {
        String caseNum = null;
        RestRequest req = RestContext.request;
        RestContext.response.addHeader('Content-Type', 'application/json');
        system.debug('-----------Recieved data--------'+req.requestBody.toString()) ;
        CaseDetailRecord caseDetail = (CaseDetailRecord)JSON.deserialize(req.requestBody.toString(),CaseDetailRecord.class);
        
       
        System.debug('caseDetail - '+ caseDetail);
        if(caseDetail.caseNumber==null || (caseDetail.caseNumber!=null && caseDetail.updationType =='Quote Created'))
        {
            List<QueueSobject> caseOwnerQueue = [Select Id, SobjectType, QueueId, Queue.Name From QueueSobject where Queue.Name=: caseDetail.ownerQueue]; 
            List<RecordType> caseRecordType =  [SELECT Id FROM RecordType WHERE Name =: caseDetail.recordtypeName and SObjectType = 'Case' limit 1];
            Case newCaseDetail = new Case();
            string errMessage;
            if(caseRecordType.size()<1)
            {
                errMessage = 'No recordType found with this data..!';
                CaseResponse caseReturn = new CaseResponse(null,null,'Failure',errMessage);                     
                RestContext.response.responseBody = Blob.valueOf(JSON.Serialize(caseReturn));
            }
            else
            {
            
            newCaseDetail.status = caseDetail.status;
            if(caseDetail.caseNumber==null)
            {
                newCaseDetail.RecordTypeId = caseRecordType[0].id;
                if(!caseOwnerQueue.isEmpty())
                newCaseDetail.OwnerID = caseOwnerQueue[0].QueueId; //caseDetail.ownerQueue;
            }
            String subject;
            if(caseDetail.contractType != null)
            {
                subject = caseDetail.contractType+' ';
            }
            if(caseDetail.aircraftModel !=null)
            {
                subject = subject+caseDetail.aircraftModel+' ';
            }
            if(caseDetail.aircraftSerialNumber !=null)
            {
                subject = subject+caseDetail.aircraftSerialNumber;
            }
            newCaseDetail.subject = subject;
            //newCaseDetail.Classification__c = caseDetail.classification;
            if(caseDetail.comments !=null)
            newCaseDetail.Comments__c =  caseDetail.comments;
            newCaseDetail.Sub_Status__c = caseDetail.subStatus;
            //newCaseDetail.description =  caseDetail.description;                        
            List<Account> accountRecList = [select id,name from account where name=:caseDetail.operatorName or name=:caseDetail.dealerName];
            List<Fleet_Asset_Detail__c> aircraftDetails = [select id from Fleet_Asset_Detail__c where (Model__c=:caseDetail.aircraftModel and Make__c=:caseDetail.aircraftMake) and 
                                                       (Tail_Number__c=:caseDetail.aircraftTail and Serial_Number__c=:caseDetail.aircraftSerialNumber)];
                
            String dealerID;            
            String casenotes = null;
            String operatorID;
            String aircraftID;
            String additionalInfo = '';
            if(caseDetail.quotenumber != null)
            {
                additionalInfo = 'Quote Number : '+caseDetail.quotenumber+'\n ';
            }
            if(accountRecList.size()>0)
            {
                for(Account acc: accountRecList)
                {
                    if(acc.name==caseDetail.operatorName)
                        operatorID = acc.id;
                    if(acc.name==caseDetail.dealerName)
                        dealerID = acc.id;
                }
            }
                    
            if(aircraftDetails.size()>0)
            {
                aircraftID = aircraftDetails[0].id; 
                newCaseDetail.Notes__c = caseDetail.notes;
                newCaseDetail.Aircraft_Name__c = aircraftID;
            }
            else
            {
                String strNotes;                
                newcaseDetail.Notes__c = 'Make: '+caseDetail.aircraftMake+','+' Model: '+caseDetail.aircraftModel+','+' Serial Number: '+caseDetail.aircraftSerialNumber+', Tail Number: '+caseDetail.aircraftTail;
            }
            if(caseDetail.contractType !=null)
            {
                newCaseDetail.Type = caseDetail.contractType;
            }
            if(operatorID!= null){
                newCaseDetail.Aircraft_Owner_Operator__c = operatorID;
            }else{
                if(caseDetail.operatorName !=null)
                {
                    additionalInfo = additionalInfo + 'Operator :' +caseDetail.operatorName +'\n ';
                 }
            }
            if(dealerID!=null)
            {
                newCaseDetail.AccountID = dealerID;
            }else{
                if(caseDetail.dealerName !=null)
                {
                    additionalInfo = additionalInfo + 'Dealer 1 :' +caseDetail.dealerName+'\n ';
                }
            }
            if(caseDetail.leadSource !=null)
            {
                additionalInfo = additionalInfo + '\n Lead Source :' +caseDetail.leadSource;
            }
            newCaseDetail.Additional_Web_Form_Info__c = additionalInfo;
            if(caseDetail.quotePrice !=null)
                newCaseDetail.Dollar_Amount__c = integer.valueof(caseDetail.quotePrice);
            if(caseDetail.quoteValidDate!=null)
                newCaseDetail.Expiration_Date__c = datetime.valueof(caseDetail.quoteValidDate);
            if(caseDetail.dealerContact !=null) 
                newCaseDetail.BGA_Dealer_Name__c = caseDetail.dealerContact;
            newCaseDetail.Origin = 'Web';
            newCaseDetail.Government_Compliance_SM_M_Content__c = 'No';
            newCaseDetail.Export_Compliance_Content_ITAR_EAR__c = 'No'; 
            try 
            {
                if(caseDetail.caseNumber == null)
                {
                    insert newCaseDetail; 
                }
                else
                {
                    
                    Case caseUpdated = [select casenumber,id  from case where casenumber =: caseDetail.caseNumber];
                    newCaseDetail.Id = caseUpdated.id;
                    update newCaseDetail;
                }
                system.debug('@@@@Inserted Case@@@@@'+newCaseDetail);
                if(caseDetail.attachmentDetail!=null && newCaseDetail.Id !=null)
                {
                    system.debug('$$$$$$$$$$$$$$$'+caseDetail.attachmentDetail);
                    Blob attachDetail = EncodingUtil.base64Decode(caseDetail.attachmentDetail);
                                
                    Attachment a = new Attachment();
                    a.ParentId = newCaseDetail.Id;
                    a.Name = caseDetail.attachmentName+'.pdf';
                    a.Body = attachDetail;
                    a.ContentType='application/pdf'; 
                    insert a;
                }
                Case caseInserted = [select casenumber,id  from case where id =: newCaseDetail.id ];
                CaseResponse caseReturn = new CaseResponse(newCaseDetail.id, caseInserted.casenumber,'Success',null);  
                RestContext.response.responseBody = Blob.valueOf(JSON.Serialize(caseReturn));
            }
            catch(Exception e)  // exception handling
            {
                System.debug('The following exception has occurred: '+e.getTypeName() + ' - ' + e.getCause() + ': ' + e.getMessage());
                errMessage = e.getMessage();
                CaseResponse caseReturn = new CaseResponse(null,null,'Failure',errMessage);
                RestContext.response.responseBody = Blob.valueOf(JSON.Serialize(caseReturn));
                //return JSON.serialize(caseReturn);
            }
            
            }
            //return JSON.serialize(caseReturn);
        }
        else if(caseDetail.caseNumber!=null && caseDetail.updationType =='Accept-Reject')
        {
            Case updateCase = [select id,CaseNumber,Sub_Status__c,status,Comments__c,Rejection_Comments__c,description from Case where CaseNumber=:caseDetail.caseNumber];
            
            updateCase.status = caseDetail.status;
            updateCase.Rejection_Comments__c = caseDetail.comments;
            update updateCase;
           
            
            CaseResponse caseReturn = new CaseResponse(updateCase.id, updateCase.CaseNumber,'Success',null);  
            RestContext.response.responseBody = Blob.valueOf(JSON.Serialize(caseReturn));
            //return JSON.serialize(caseReturn);
        }
      
    }

    public class CaseResponse{
        public String caseId;
        public String caseNumber;
        public String Status;
        public String error;
        
        public CaseResponse(String caserecId,String caserecNumber, String statusmsg,String errormsg){
          error = '';
          caseId = caserecId;
          caseNumber = caserecNumber;
          Status = statusmsg;
          if(errormsg!=null)
          error =  errormsg;
      }
        
    }

    public class CaseDetailRecord   
    {
       //public String honeywellID;
       public String contractType;
       //public string subject;
       public string description;
       public String classification;
       public string comments;
       public String recordtypeName;
       public String subStatus;
       public String ownerQueue;
       public String leadSource;     
       public String status;
       public String caseID;
       public String caseNumber;
       public String quotePrice;
       public string dealerName;
       public string operatorName;
       public string aircraftMake; 
       public string aircraftModel;
       public string aircraftTail;
       public String aircraftSerialNumber;
       public String notes;
       public String quotenumber;
       public String quoteValidDate;
       public String attachmentDetail;
       public String attachmentName;
       public String dealerContact;
       public String updationType;
             
       public CaseDetailRecord()
       {
            
       }
    }

}