src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <inlineHelpText>Market names to coincide with appropriate SBU (Air Transport and/or Regional Transport, Business and/or General Aviation, etc)</inlineHelpText>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Air Transport</fullName>
            </value>
            <value>
                <fullName>Business Aviation</fullName>
            </value>
            <value>
                <fullName>General Aviation</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Helicopters</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>Non-Aerospace</fullName>
            </value>
            <value>
                <fullName>Regional Transport</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Task.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tact</description>
    <label>Task</label>
</RecordType>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/SBU_User__c.field-meta.xml
<CustomField>
    <fullName>SBU_User__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ALT</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>C&amp;PS</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>E&amp;T</fullName>
            </value>
            <value>
                <fullName>EngPS</fullName>
            </value>
            <value>
                <fullName>EngPS BD</fullName>
            </value>
            <value>
                <fullName>EngPS OE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FNCE</fullName>
            </value>
            <value>
                <fullName>FNCE AMER</fullName>
            </value>
            <value>
                <fullName>FNCE APAC</fullName>
            </value>
            <value>
                <fullName>FNCE ELECSOL</fullName>
            </value>
            <value>
                <fullName>FNCE EMEA</fullName>
            </value>
            <value>
                <fullName>FNCE ENGPS</fullName>
            </value>
            <value>
                <fullName>FNCE MECH</fullName>
            </value>
            <value>
                <fullName>FNCE SERVCONN</fullName>
            </value>
            <value>
                <fullName>HBT</fullName>
            </value>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>HOS</fullName>
            </value>
            <value>
                <fullName>HOS CE</fullName>
            </value>
            <value>
                <fullName>HOS CE CRM</fullName>
            </value>
            <value>
                <fullName>HOS CE SO</fullName>
            </value>
            <value>
                <fullName>HOSG</fullName>
            </value>
            <value>
                <fullName>HOS PMO</fullName>
            </value>
            <value>
                <fullName>HOS PRICING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/Test_TaskController.cls
/** * File Name: Test_TaskController
* Description Test Method
* Copyright : Wipro Technologies Limited Copyright (c) 2010
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
@isTest
private  class Test_TaskController {
    static Tasks taskCon = null;
    static void setupEnv(){
        Profile pf= [select id from Profile where name = 'System Administrator'];
        User usr = new User(LastName = 'Test', FirstName = ' UserCSO2', Username = 'tu1cso@test.com',Email = 'testuser@test.com',Alias = 'tu1' ,CommunityNickname= 'tu1cso' ,TimeZoneSidKey = 'America/Los_Angeles',LocaleSidKey='en_US',EmailEncodingKey= 'ISO-8859-1',ProfileId = pf.Id, LanguageLocaleKey = 'en_US',SBU_User__c = 'D&S');insert usr;   
        Account acc= new Account(name='Test Account', Market_Name__c = 'Military');
        insert acc;
        Task tasks= new Task (whatId=acc.Id,ownerid=usr.Id);
        insert tasks;

        PageReference pageRef = Page.TaskPage;
        Test.setCurrentPage(pageRef);

        ApexPages.StandardController sc = new ApexPages.StandardController(tasks);
        taskCon = new Tasks(sc);
    }
    static testmethod void testTasksPage1(){
        setupEnv();

        list<String> srtExp = new list<String>();
        srtExp.add('subject');
        srtExp.add('Priority');
        srtExp.add('Status');

        list<String> listSel = new list<String>();
        listSel.add('Today');
        listSel.add('Tomorrow');
        listSel.add('All Open');
        listSel.add('Next 7 days');
        listSel.add('This Month');
        listSel.add('OverDue');
        listSel.add('Today+OverDue');
        listSel.add('Next 7 days+OverDue');
        

        for(String sel : listSel){
            taskCon.setlistSel(sel);
            for(String srt : srtExp){
                taskCon.sortExpression = srt;
                taskCon.setsortDirection('ASC');
                taskCon.RefreshData();
                taskCon.setsortDirection('DESC');
                taskCon.RefreshData();
            }
        }
        taskCon.getSortDirection();
        taskCon.getlistSel();
        taskCon.getTasks();
    }
    static testmethod void testTasksPage2(){
        setupEnv();

        list<String> srtExp = new list<String>();
        srtExp.add('WhatId');
        srtExp.add('Type');
        srtExp.add('ActivityDate');
        srtExp.add('Activity_Number__c');

        list<String> listSel = new list<String>();
        listSel.add('Today');
        listSel.add('Tomorrow');
        listSel.add('All Open');
        listSel.add('Next 7 days');
        listSel.add('This Month');
        listSel.add('OverDue');
        listSel.add('Today+OverDue');
        listSel.add('Next 7 days+OverDue');
        

        for(String sel : listSel){
            taskCon.setlistSel(sel);
            for(String srt : srtExp){
                taskCon.sortExpression = srt;
                taskCon.setsortDirection('ASC');
                taskCon.RefreshData();
                taskCon.setsortDirection('DESC');
                taskCon.RefreshData();
            }
        }
    }
    /*
        taskCon.sortExpression = 'subject';
        taskCon.RefreshData();
        taskCon.sortExpression = 'subject';
        taskCon.RefreshData();
        //taskCon.sortExpression = 'Priority';
        taskCon.RefreshData();
        //taskCon.sortExpression = 'Priority';
        taskCon.RefreshData();  
        taskCon.getSortDirection();
        taskCon.setSortDirection('DESC');
        taskCon.getlistSel();
        taskCon.setlistSel('Today');
        taskCon.RefreshData();
        taskCon.getTasks();
        taskCon.setlistSel('Tomorrow');
        taskCon.RefreshData();
        taskCon.setlistSel('All Open');
        taskCon.RefreshData();
        taskCon.setlistSel('Next 7 days');
        taskCon.RefreshData();
        taskCon.setlistSel('This Month');
        taskCon.RefreshData();
        taskCon.setlistSel('OverDue');
        taskCon.RefreshData();
        taskCon.setlistSel('Today+OverDue');
        taskCon.RefreshData();
        taskCon.setlistSel('Next 7 days+OverDue');
        taskCon.RefreshData();
        */
}