src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Account/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <inlineHelpText>Market names to coincide with appropriate SBU (Air Transport and/or Regional Transport, Business and/or General Aviation, etc)</inlineHelpText>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Air Transport</fullName>
            </value>
            <value>
                <fullName>Business Aviation</fullName>
            </value>
            <value>
                <fullName>General Aviation</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Helicopters</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>Non-Aerospace</fullName>
            </value>
            <value>
                <fullName>Regional Transport</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Case_Ref_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Ref_ID__c</fullName>
    <description>Custom Case reference ID based on which email attachment to case works.
Jun 03, 2014: Updated format since Case ID format changed after Org Split</description>
    <formula>&quot;[ ref:_&quot; &amp;
LEFT( $Organization.Id , 5) &amp;
IF (MID ( $Organization.Id, 6, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id,10),
IF (MID ( $Organization.Id, 7, 1) &lt;&gt; &quot;0&quot;,RIGHT($Organization.Id, 9),
IF (MID ( $Organization.Id, 8, 1) &lt;&gt;&quot;0&quot;, RIGHT($Organization.Id, 8),
IF (MID ( $Organization.Id, 9, 1)&lt;&gt; &quot;0&quot;, RIGHT($Organization.Id, 7),
IF (MID ( $Organization.Id,10, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id, 6),
IF (MID ($Organization.Id, 11, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id, 5),
IF(MID ( $Organization.Id, 12, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id,4),
IF (MID ( $Organization.Id, 13, 1) &lt;&gt; &quot;0&quot;,RIGHT($Organization.Id, 3),
IF (MID ( $Organization.Id, 14, 1) &lt;&gt;&quot;0&quot;, RIGHT($Organization.Id, 2), &quot;&quot;) ) ) ) ) ) ) ) )
&amp; &quot;._&quot; &amp;LEFT( Id, 5) &amp;
IF(MID ( Id, 6, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 10),
IF (MID ( Id, 7, 1)&lt;&gt; &quot;0&quot;, RIGHT(Id, 9),
IF (MID ( Id, 8, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id,8),
IF (MID ( Id, 9, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 7),
IF (MID ( Id, 10,1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 6),
IF (MID ( Id, 11, 1) &lt;&gt; &quot;0&quot;,RIGHT(Id, 5),
IF (MID ( Id, 12, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 4),
IF (MID( Id, 13, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 3),
IF (MID ( Id, 14, 1) &lt;&gt;&quot;0&quot;, RIGHT(Id, 2), &quot;&quot;) ) ) ) ) ) ) ) ) &amp; &quot;:ref ]&quot;</formula>
    <label>Case Ref ID</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Customer_PO_RO_WONumber__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_RO_WONumber__c</fullName>
    <description>Text Field used to hold the PO number. 
05/22 - Set to external ID for PO/SN deployment to avoid 554 connection error in Salesforce</description>
    <externalId>true</externalId>
    <label>Customer PO/RO/WO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <label>Honeywell ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <description>Primary Email for the supported product</description>
    <label>Primary Email</label>
    <type>Email</type>
</CustomField>

src/objects/Case/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <formula>HYPERLINK(&quot;mailto:&quot;&amp; Contact.Primary_Email_Address__c, Contact.Primary_Email_Address__c, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Email Address</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Reason_for_hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_hold__c</fullName>
    <description>Used for Order record type</description>
    <label>Reason for Hold</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Sub_Status__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2020 CONTRACT PRICING-CONTRACT ESCALATION</fullName>
            </value>
            <value>
                <fullName>2020 CONTRACT PRICING- PO UPDATE REQUESTED</fullName>
            </value>
            <value>
                <fullName>2020 CONTRACT PRICING - SO REVIEW</fullName>
            </value>
            <value>
                <fullName>777 Expedite</fullName>
            </value>
            <value>
                <fullName>8130/EASA/CAAC/Certification Correction</fullName>
            </value>
            <value>
                <fullName>8130/EASA/CAAC/Certification Missing</fullName>
            </value>
            <value>
                <fullName>8130 TAG</fullName>
            </value>
            <value>
                <fullName>A/C Details</fullName>
            </value>
            <value>
                <fullName>ACAT approval</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Access Class</fullName>
            </value>
            <value>
                <fullName>Account Block Status</fullName>
            </value>
            <value>
                <fullName>Account Change: Bill To</fullName>
            </value>
            <value>
                <fullName>Account Change: Carrier</fullName>
            </value>
            <value>
                <fullName>Account Change: End User Details</fullName>
            </value>
            <value>
                <fullName>Account Change: Extend Sales Org</fullName>
            </value>
            <value>
                <fullName>Account Change: Name/Address</fullName>
            </value>
            <value>
                <fullName>Account Change: Payer</fullName>
            </value>
            <value>
                <fullName>Account Change: Ship To</fullName>
            </value>
            <value>
                <fullName>Account Creation - Bill To</fullName>
            </value>
            <value>
                <fullName>Account Creation - Ship To</fullName>
            </value>
            <value>
                <fullName>Account Creation - Sold To</fullName>
            </value>
            <value>
                <fullName>Account Edit - Bill To</fullName>
            </value>
            <value>
                <fullName>Account Edit - Ship To</fullName>
            </value>
            <value>
                <fullName>Account Edit - Sold To</fullName>
            </value>
            <value>
                <fullName>ACES Issues</fullName>
            </value>
            <value>
                <fullName>ACN#</fullName>
            </value>
            <value>
                <fullName>Add customer sold-to</fullName>
            </value>
            <value>
                <fullName>Add Customer Sold To/Sales Office</fullName>
            </value>
            <value>
                <fullName>Add Flowdown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <inlineHelpText>This field is mandatory for many business processes.  It is recommended that you populate this field prior to closing the case.  Coming soon: In December 2020, the resolution will be visible to customers on the portal.</inlineHelpText>
    <label>Resolution</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/VN_Name__c.field-meta.xml
<CustomField>
    <fullName>VN_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escalated To (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You have selected an inactive contact in the Escalated To (Contact) field. Select an active contact to be able to save the case.</errorMessage>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>API DATA LOAD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (VN Name)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/classes/ACES_CaseUpdateFromSAPTest.cls
/*******************************************************************************
Name         : ACES_CaseUpdateFromSAPTest
Created By   : Harikishore V
Company Name : NTT Data
Project      : <Phase-II>, <UFR Pricing>
Created Date : 06-April-2015
Usages       : Test Class for ACES_CaseUpdateFromSAP            
*******************************************************************************/
@isTest/*(SeeAllData=true)*/
global class ACES_CaseUpdateFromSAPTest{ 
    testMethod static void ACES_CaseUpdateFromSAPTest(){
    //Commented for Reason for Hold changes INC000010025414 
       // Case cs = [select id,CaseNumber,Reason_for_hold__c,VN_Name__c,status,origin,Primary_Email__c,ContactId,Customer_PO_RO_WONumber__c,Sales_Order_Number__c from Case where RecordtypeId=:label.QuotesRecordID and Reason_for_hold__c!=null and VN_Name__c!=null limit 1];
        //Case cs = [select id,CaseNumber,VN_Name__c,status,origin,Primary_Email__c,ContactId,Customer_PO_RO_WONumber__c,Sales_Order_Number__c from Case where RecordtypeId=:label.QuotesRecordID and VN_Name__c!=null limit 1];
        Test.startTest();
        Account acc= new Account(name = 'Test Account',Market_name__C = 'Military');
        insert acc;
        
        //creating contact
        Contact cont = new Contact(
            firstname = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Phone_3__c = '9986502495',
            Contact_Is_Employee__c = true,
            Contact_Status__c = 'Active',
            Employee_Contact_Role__c = 'Analyst',
            Employee_Number__c = 'E147567',
            Honeywell_ID__c = '01499xxx40331',
            EMAIL = 'aldcv.sfwv@vfv.com'
        );
        insert cont; 
        List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS> lists = new List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS>();
        
        Case cs = new Case(
            AccountId = acc.Id,
            subject = 'ARINC Update',
            ContactId = cont.Id,
            Origin = 'Email',
            Type = 'Quote',
            VN_Name__c =cont.Id,
            RecordtypeId=label.QuotesRecordID,
            Customer_PO_RO_WONumber__c ='p0123',
            Sales_Order_Number__c ='12345678'
        );
        insert cs;
        Task tsk = new Task();
        tsk.Status = 'In Progress';
        tsk.WhatId = cs.id;
        insert tsk;
        /*ContentVersion conVer = new ContentVersion();
        conVer.PathOnClient = 'test'; // file name with extension
        conVer.Title = 'test'; // file name to display. Usually specify the extension here also
        conVer.VersionData = EncodingUtil.base64Decode('test');
        insert conVer;
        ContentVersion conVer1 = [SELECT Id,Title,ContentDocumentId from ContentVersion where Id=: conVer.id limit 1];
        ContentDocumentlink objCDL = new ContentDocumentlink();
        objCDL.ContentDocumentId = conVer1.ContentDocumentId;
        objCDL.linkedentityId = cs.id;
        objCDL.Sharetype = 'I';
        insert objCDL;*/
        Case cas = [SELECT id,Reason_for_hold__c,VN_Name__c,Resolution__c,(select id,IsClosed from Case.Tasks where IsClosed=FALSE),Subject,Case_Ref_ID__c,Contact.Primary_Email_Address__c,CreatedDate,Status,Sub_Status__c,CaseNumber,Is_Case_Owner_a_queue__c,Customer_PO_RO_WONumber__c,SAP_Quote_Number__c,IsClosed,ContactId,Primary_Email_Address__c from Case where id=:cs.id];
        ACES_CaseUpdateFromSAP.LINEITEMDETAILS li = new ACES_CaseUpdateFromSAP.LINEITEMDETAILS();
        li.LINE_ITEM_NUMBER = '23';
        li.MATERIAL_NUMBER = '76.23';
        li.MATERIAL_DESC = 'test';
        li.ORDER_QUANTITY = '12.23';
        li.NET_PRICE = '13.22';
        li.DELIVERY_DATE = string.valueOf(system.now());
        li.LEAD_TIME = '2 weeks';
        li.LINE_ITEM_STATUS = 'Customer Hold';
        li.REPLACEMENT_PART = 'test1';
        li.LINE_ITEM_TEXT = 'test';
        li.ARO_LEAD_TIME_UNIT = '2163';
        lists.add(li);      
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces.CASE_NUMBER = cas.CaseNumber;
        aces.PDR_NUMBER = '12345678';
        aces.PDR_CREATED_ON = string.valueOf(system.now());
        aces.PDR_RELEASED_ON = string.valueOf(system.now());
        aces.RFQ_NUMBER = 'PO123'; 
        aces.QUOTATION_NUMBER = '76435837';
        aces.QSTC_PARTIAL_RELEASED = 'QSTC';
        aces.LAST_PDR = 'No';
        aces.AttBody = 'Test atta';
        aces.AttFileName = 'test.pdf';
        aces.AttContentType = 'application/pdf';
        aces.LINEITEMS = lists;
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata = ACES_CaseUpdateFromSAP.updateCase(aces);
        
        /*ACES_CaseUpdateFromSAP.SAPDataToSFDC aces1 = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces1.CASE_NUMBER = cas.CaseNumber;
        aces1.PDR_NUMBER = '12345678';
        aces1.RFQ_NUMBER = 'PO123'; 
        aces1.QUOTATION_NUMBER = '76435837';
        aces1.QSTC_PARTIAL_RELEASED = 'RELEASED';
        aces1.LAST_PDR = 'YES';
        aces1.LINEITEMS = null;
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata1 = ACES_CaseUpdateFromSAP.updateCase(aces1);*/
        
        
        Test.stopTest();
    }
    testMethod static void ACES_CaseUpdateFromSAPTest11(){
    //Commented for Reason for Hold changes INC000010025414 
       // Case cs = [select id,CaseNumber,Reason_for_hold__c,VN_Name__c,status,origin,Primary_Email__c,ContactId,Customer_PO_RO_WONumber__c,Sales_Order_Number__c from Case where RecordtypeId=:label.QuotesRecordID and Reason_for_hold__c!=null and VN_Name__c!=null limit 1];
        //Case cs = [select id,CaseNumber,VN_Name__c,status,origin,Primary_Email__c,ContactId,Customer_PO_RO_WONumber__c,Sales_Order_Number__c from Case where RecordtypeId=:label.QuotesRecordID and VN_Name__c!=null limit 1];
        Test.startTest();
        Account acc= new Account(name = 'Test Account',Market_name__C = 'Military');
        insert acc;
        
        //creating contact
        Contact cont = new Contact(
            firstname = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Phone_3__c = '9986502495',
            Contact_Is_Employee__c = true,
            Contact_Status__c = 'Active',
            Employee_Contact_Role__c = 'Analyst',
            Employee_Number__c = 'E147567',
            Honeywell_ID__c = '01499xxx40331',
            EMAIL = 'aldcv.sfwv@vfv.com'
        );
        insert cont; 
        List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS> lists = new List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS>();
        
        Case cs = new Case(
            AccountId = acc.Id,
            subject = 'ARINC Update',
            ContactId = cont.Id,
            Origin = 'Email',
            Type = 'Quote',
            VN_Name__c =cont.Id,
            RecordtypeId=label.QuotesRecordID,
            Customer_PO_RO_WONumber__c ='p0123',
            Sales_Order_Number__c ='12345678'
        );
        insert cs;
        
        P_DR_Line_Item__c pdr = new P_DR_Line_Item__c();
        pdr.Case_Number__c = cs.id;
        pdr.PDR_Number__c = '12345678';
        pdr.Line_Item_Number__c  = 23;
        insert pdr;
        /*ContentVersion conVer = new ContentVersion();
        conVer.PathOnClient = 'test'; // file name with extension
        conVer.Title = 'test'; // file name to display. Usually specify the extension here also
        conVer.VersionData = EncodingUtil.base64Decode('test');
        insert conVer;
        ContentVersion conVer1 = [SELECT Id,Title,ContentDocumentId from ContentVersion where Id=: conVer.id limit 1];
        ContentDocumentlink objCDL = new ContentDocumentlink();
        objCDL.ContentDocumentId = conVer1.ContentDocumentId;
        objCDL.linkedentityId = cs.id;
        objCDL.Sharetype = 'I';
        insert objCDL;*/
        Case cas = [SELECT id,Reason_for_hold__c,VN_Name__c,Resolution__c,(select id,IsClosed from Case.Tasks where IsClosed=FALSE),Subject,Case_Ref_ID__c,Contact.Primary_Email_Address__c,CreatedDate,Status,Sub_Status__c,CaseNumber,Is_Case_Owner_a_queue__c,Customer_PO_RO_WONumber__c,SAP_Quote_Number__c,IsClosed,ContactId,Primary_Email_Address__c from Case where id=:cs.id];
        ACES_CaseUpdateFromSAP.LINEITEMDETAILS li = new ACES_CaseUpdateFromSAP.LINEITEMDETAILS();
        li.LINE_ITEM_NUMBER = '23';
        li.MATERIAL_NUMBER = '76.23';
        li.MATERIAL_DESC = 'test';
        li.ORDER_QUANTITY = '12.23';
        li.NET_PRICE = '13.22';
        li.DELIVERY_DATE = string.valueOf(system.now());
        li.LEAD_TIME = '2 weeks';
        li.LINE_ITEM_STATUS = 'Customer Hold';
        li.REPLACEMENT_PART = 'test1';
        li.LINE_ITEM_TEXT = 'test';
        li.ARO_LEAD_TIME_UNIT = '2163';
        lists.add(li);      
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces.CASE_NUMBER = cas.CaseNumber;
        aces.PDR_NUMBER = '12345678';
        aces.PDR_CREATED_ON = string.valueOf(system.now());
        aces.PDR_RELEASED_ON = string.valueOf(system.now());
        aces.RFQ_NUMBER = 'PO123'; 
        aces.QUOTATION_NUMBER = '76435837';
        aces.QSTC_PARTIAL_RELEASED = 'QSTC';
        aces.LAST_PDR = 'No';
        aces.AttBody = 'Test atta';
        aces.AttFileName = 'test.pdf';
        aces.AttContentType = 'application/pdf';
        aces.LINEITEMS = lists;
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata = ACES_CaseUpdateFromSAP.updateCase(aces);
        
        /*ACES_CaseUpdateFromSAP.SAPDataToSFDC aces1 = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces1.CASE_NUMBER = cas.CaseNumber;
        aces1.PDR_NUMBER = '12345678';
        aces1.RFQ_NUMBER = 'PO123'; 
        aces1.QUOTATION_NUMBER = '76435837';
        aces1.QSTC_PARTIAL_RELEASED = 'RELEASED';
        aces1.LAST_PDR = 'YES';
        aces1.LINEITEMS = null;
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata1 = ACES_CaseUpdateFromSAP.updateCase(aces1);*/
        
        
        Test.stopTest();
    }
    
    testMethod static void ACES_CaseUpdateFromSAPTest1(){
        //Case cs = [select id,CaseNumber,status,origin,Primary_Email__c,ContactId,Customer_PO_RO_WONumber__c,Sales_Order_Number__c from Case where RecordtypeId=:label.QuotesRecordID and isClosed = FALSE and Is_Case_Owner_a_queue__c = TRUE limit 1];
        Account acc= new Account(name = 'Test Account',Market_name__C = 'Military');
        insert acc;
        
        //creating contact
        Contact cont = new Contact(
            firstname = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Phone_3__c = '9986502495',
            Contact_Is_Employee__c = true,
            Contact_Status__c = 'Active',
            Employee_Contact_Role__c = 'Analyst',
            Employee_Number__c = 'E147567',
            Honeywell_ID__c = '01499xxx40331',
            EMAIL = 'aldcv.sfwv@vfv.com'
        );
        insert cont; 
        Test.startTest();
        Case cs = new Case(
            AccountId = acc.Id,
            subject = 'ARINC Update',
            ContactId = cont.Id,
            Origin = 'Email',
            Type = 'Quote',
            VN_Name__c =cont.Id,
            RecordtypeId=label.QuotesRecordID,
            Is_Case_Owner_a_queue__c = true,
            Customer_PO_RO_WONumber__c ='p0123',
            Sales_Order_Number__c ='12345678'
        );
        insert cs;
        Case cas = [SELECT id,Reason_for_hold__c,VN_Name__c,Resolution__c,(select id,IsClosed from Case.Tasks where IsClosed=FALSE),Subject,Case_Ref_ID__c,Contact.Primary_Email_Address__c,CreatedDate,Status,Sub_Status__c,CaseNumber,Is_Case_Owner_a_queue__c,Customer_PO_RO_WONumber__c,SAP_Quote_Number__c,IsClosed,ContactId,Primary_Email_Address__c from Case where id=:cs.id];
        List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS> lists = new List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS>();
        ACES_CaseUpdateFromSAP.LINEITEMDETAILS li = new ACES_CaseUpdateFromSAP.LINEITEMDETAILS();
        li.LINE_ITEM_NUMBER = '23';
        li.MATERIAL_NUMBER = '76.23';
        li.MATERIAL_DESC = 'test';
        li.ORDER_QUANTITY = '12.23';
        li.NET_PRICE = '13.22';
        li.DELIVERY_DATE = string.valueOf(system.now());
        li.LEAD_TIME = '2 weeks';
        li.LINE_ITEM_STATUS = 'No Bid';
        li.REPLACEMENT_PART = 'test1';
        li.LINE_ITEM_TEXT = 'test';
        li.ARO_LEAD_TIME_UNIT = '2163';
        lists.add(li);      
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces.CASE_NUMBER = cas.CaseNumber;
        aces.PDR_NUMBER = '12345678';
        aces.PDR_CREATED_ON = string.valueOf(system.now());
        aces.PDR_RELEASED_ON = string.valueOf(system.now());
        aces.RFQ_NUMBER = 'PO123'; 
        aces.QUOTATION_NUMBER = '76435837';
        aces.QSTC_PARTIAL_RELEASED = 'QSTC';
        aces.LAST_PDR = 'YES';
        aces.AttBody = 'Test atta';
        aces.AttFileName = 'test';
        aces.AttContentType = 'application/pdf';
        aces.LINEITEMS = lists;
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata = ACES_CaseUpdateFromSAP.updateCase(aces);
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces1 = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces1.CASE_NUMBER = '123';
        aces1.PDR_NUMBER = '12345678';
        aces1.PDR_CREATED_ON = string.valueOf(system.now());
        aces1.PDR_RELEASED_ON = string.valueOf(system.now());
        aces1.RFQ_NUMBER = 'PO123'; 
        aces1.QUOTATION_NUMBER = '76435837';
        aces1.QSTC_PARTIAL_RELEASED = 'QSTC';
        aces1.LAST_PDR = 'YES';
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata1 = ACES_CaseUpdateFromSAP.updateCase(aces1);
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces2 = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces2.CASE_NUMBER = cas.CaseNumber;   
        aces2.CASE_SUB_STATUS = 'OPEN';
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata2 = ACES_CaseUpdateFromSAP.updateCase(aces2);
        
        Test.stopTest();
    }
    testMethod static void ACES_CaseUpdateFromSAPTest2(){
        //Case cs = [select id,CaseNumber,status,origin,Primary_Email__c,ContactId,Customer_PO_RO_WONumber__c,Sales_Order_Number__c,Quote_Number__c from Case where RecordtypeId=:label.QuotesRecordID and ContactId!=null Order By CreatedDate desc limit 1];
        Account acc= new Account(name = 'Test Account',Market_name__C = 'Military');
        insert acc;
        
        //creating contact
        Contact cont = new Contact(
            firstname = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Phone_3__c = '9986502495',
            Contact_Is_Employee__c = true,
            Contact_Status__c = 'Active',
            Employee_Contact_Role__c = 'Analyst',
            Employee_Number__c = 'E147567',
            Honeywell_ID__c = '01499xxx40331',
            EMAIL = 'aldcv.sfwv@vfv.com'
        );
        insert cont; 
        Test.startTest();
        Case cs = new Case(
            AccountId = acc.Id,
            subject = 'ARINC Update',
            ContactId = cont.Id,
            Origin = 'Email',
            Type = 'Quote',
            VN_Name__c =cont.Id,
            RecordtypeId=label.QuotesRecordID,
            Customer_PO_RO_WONumber__c ='p0123',
            Sales_Order_Number__c ='12345678'
        );
        insert cs;
        List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS> lists = new List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS>();
        ACES_CaseUpdateFromSAP.LINEITEMDETAILS li = new ACES_CaseUpdateFromSAP.LINEITEMDETAILS();
        li.LINE_ITEM_NUMBER = '2';
        li.MATERIAL_NUMBER = '7';
        li.MATERIAL_DESC = 'test1';
        li.ORDER_QUANTITY = '12';
        li.NET_PRICE = '13';
        li.DELIVERY_DATE = string.valueOf(system.now());
        li.LEAD_TIME = '3 weeks';
        li.LINE_ITEM_STATUS = 'Pricied';
        li.REPLACEMENT_PART = 'test1';
        li.LINE_ITEM_TEXT = 'test1';
        li.ARO_LEAD_TIME_UNIT = '216';
        lists.add(li);      
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces.CASE_NUMBER = cs.CaseNumber;
        aces.PDR_NUMBER = '00523555';
        aces.PDR_CREATED_ON = string.valueOf(system.now());
        aces.PDR_RELEASED_ON = string.valueOf(system.now());
        aces.RFQ_NUMBER = 'PO123'; 
        aces.QUOTATION_NUMBER = '76435837';
        aces.QSTC_PARTIAL_RELEASED = 'RELEASED';
        aces.LAST_PDR = 'YES';
        aces.LINEITEMS = lists;
        aces.AttBody = 'Test atta';
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata = ACES_CaseUpdateFromSAP.updateCase(aces);
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces1 = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces1.CASE_NUMBER = cs.CaseNumber;
        aces1.PDR_NUMBER = '00523555';
        aces1.PDR_CREATED_ON = string.valueOf(system.now());
        aces1.PDR_RELEASED_ON = string.valueOf(system.now());
        aces1.RFQ_NUMBER = 'PO123'; 
        aces1.QUOTATION_NUMBER = '76435837';
        aces1.QSTC_PARTIAL_RELEASED = 'RELEASED';
        aces1.LAST_PDR = 'No';
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata1 = ACES_CaseUpdateFromSAP.updateCase(aces1);
        
        List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS> lists1 = new List<ACES_CaseUpdateFromSAP.LINEITEMDETAILS>();
        ACES_CaseUpdateFromSAP.LINEITEMDETAILS li1 = new ACES_CaseUpdateFromSAP.LINEITEMDETAILS();
        li1.LINE_ITEM_NUMBER = '2';
        li1.MATERIAL_NUMBER = '7.23';
        li1.MATERIAL_DESC = 'test';
        li1.ORDER_QUANTITY = '12.2';
        li1.NET_PRICE = '1.22';
        li1.DELIVERY_DATE = string.valueOf(system.now());
        li1.LEAD_TIME = '02 weeks';
        li1.LINE_ITEM_STATUS = 'No Bid';
        li1.REPLACEMENT_PART = 'test12';
        li1.LINE_ITEM_TEXT = 'test3';
        li1.ARO_LEAD_TIME_UNIT = '2';
        lists1.add(li);     
        
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces2 = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces2.CASE_NUMBER = cs.CaseNumber;
        aces2.PDR_NUMBER = '00523555';
        aces2.PDR_CREATED_ON = string.valueOf(system.now());
        aces2.PDR_RELEASED_ON = string.valueOf(system.now());
        aces2.RFQ_NUMBER = 'PO123'; 
        aces2.QUOTATION_NUMBER = '76435837';
        aces2.QSTC_PARTIAL_RELEASED = 'RELEASED';
        aces2.LAST_PDR = 'YES';
        aces2.LINEITEMS = lists;
        aces2.RELEASED_PDRNUMLIST = '';
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata2 = ACES_CaseUpdateFromSAP.updateCase(aces2);     
        Test.stopTest();
    }
    testMethod static void ACES_CaseUpdateFromSAPTest3(){
        //Case cs = [select id,CaseNumber,status,origin,Primary_Email__c,ContactId,Customer_PO_RO_WONumber__c,Sales_Order_Number__c from Case where RecordtypeId=:label.QuotesRecordID limit 1];
        Account acc= new Account(name = 'Test Account',Market_name__C = 'Military');
        insert acc;
        
        //creating contact
        Contact cont = new Contact(
            firstname = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Phone_3__c = '9986502495',
            Contact_Is_Employee__c = true,
            Contact_Status__c = 'Active',
            Employee_Contact_Role__c = 'Analyst',
            Employee_Number__c = 'E147567',
            Honeywell_ID__c = '01499xxx40331',
            EMAIL = 'aldcv.sfwv@vfv.com'
        );
        insert cont; 
        Test.startTest();
        Case cs = new Case(
            AccountId = acc.Id,
            subject = 'ARINC Update',
            ContactId = cont.Id,
            Origin = 'Email',
            Type = 'Quote',
            VN_Name__c =cont.Id,
            RecordtypeId=label.QuotesRecordID,
            Customer_PO_RO_WONumber__c ='p0123',
            Sales_Order_Number__c ='12345678'
        );
        insert cs;
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces2 = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces2.CASE_NUMBER = cs.CaseNumber;
        aces2.CASE_SUB_STATUS = 'MTO Hold';
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata2 = ACES_CaseUpdateFromSAP.updateCase(aces2);
        
        Task tsk = new Task();
        tsk.Status = 'In Progress';
        tsk.WhatId = cs.id;
        insert tsk;
        ACES_CaseUpdateFromSAP.SAPDataToSFDC aces = new ACES_CaseUpdateFromSAP.SAPDataToSFDC();
        aces.CASE_NUMBER = cs.CaseNumber;
        aces.CASE_SUB_STATUS = 'MTO Hold';
        aces.QSTC_PARTIAL_RELEASED = 'QSTC';
        aces.LAST_PDR = 'YES';
        aces.PDR_NUMBER = '12345678';
        aces.RFQ_NUMBER = 'PO123'; 
        aces.QUOTATION_NUMBER = '76435837';
        aces.QSTC_PARTIAL_RELEASED = 'QSTC';
        ACES_CaseUpdateFromSAP.ResponseToSAP  sfdcdata = ACES_CaseUpdateFromSAP.updateCase(aces);
        
        
        Test.stopTest();
    }
}