src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/EMAIL__c.field-meta.xml
<CustomField>
    <fullName>EMAIL__c</fullName>
    <label>EMAIL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/CBT_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>CBT_Tier_2__c</fullName>
    <description>CBT Tier 2 is relabeled as CBT based on Business request. The source of the CBT is the Account CBT.</description>
    <inlineHelpText>CBT responsible for this opportunity</inlineHelpText>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACST-Connected Solutions</fullName>
            </value>
            <value>
                <fullName>ACST-E&amp;I</fullName>
            </value>
            <value>
                <fullName>ACST-Honeywell Quantum Solutions</fullName>
            </value>
            <value>
                <fullName>ACST-RTG</fullName>
            </value>
            <value>
                <fullName>ACST-Sustainability Technologies</fullName>
            </value>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
                <label>BendixKing</label>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DEW</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <inlineHelpText>SBU responsible for this opportunity</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Tech_Sales_Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales_Product_Area__c</fullName>
    <inlineHelpText>Techincal Sales Product Area</inlineHelpText>
    <label>Tech Sales  Product Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tech_Sales__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Adjacencies</fullName>
            </value>
            <value>
                <fullName>AGT1500</fullName>
            </value>
            <value>
                <fullName>AIMS/ VIA</fullName>
            </value>
            <value>
                <fullName>Air Cycle Systems</fullName>
            </value>
            <value>
                <fullName>Air Data Products</fullName>
            </value>
            <value>
                <fullName>Airframe Hydraulics</fullName>
            </value>
            <value>
                <fullName>Air Source Systems</fullName>
            </value>
            <value>
                <fullName>Air Turbine Start Systems &amp; Motors</fullName>
            </value>
            <value>
                <fullName>ALF502 / LF507</fullName>
            </value>
            <value>
                <fullName>APU 131</fullName>
            </value>
            <value>
                <fullName>APU 331</fullName>
            </value>
            <value>
                <fullName>APU 331 Large</fullName>
            </value>
            <value>
                <fullName>APU 36-100</fullName>
            </value>
            <value>
                <fullName>APU 36-150</fullName>
            </value>
            <value>
                <fullName>APU 36-155</fullName>
            </value>
            <value>
                <fullName>APU 36-200</fullName>
            </value>
            <value>
                <fullName>APU 36-280 / 36-300</fullName>
            </value>
            <value>
                <fullName>APU 36-50/55</fullName>
            </value>
            <value>
                <fullName>APU 660 / 700</fullName>
            </value>
            <value>
                <fullName>APU 85</fullName>
            </value>
            <value>
                <fullName>APU AMADs</fullName>
            </value>
            <value>
                <fullName>APU G250</fullName>
            </value>
            <value>
                <fullName>APU HGT1700</fullName>
            </value>
            <value>
                <fullName>APU HGT750</fullName>
            </value>
            <value>
                <fullName>APU Jet Fuel Starter</fullName>
            </value>
            <value>
                <fullName>APU JSF</fullName>
            </value>
            <value>
                <fullName>APU Misc Adv Tech</fullName>
            </value>
            <value>
                <fullName>APU Other D&amp;S</fullName>
            </value>
            <value>
                <fullName>APU RE100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Win_Loss_Reason_Text__c.field-meta.xml
<CustomField>
    <fullName>Win_Loss_Reason_Text__c</fullName>
    <inlineHelpText>Win/Loss Reason Text</inlineHelpText>
    <label>Win/Loss Reason Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <formula>TEXT(Opportunity.SBU__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/SBU_User__c.field-meta.xml
<CustomField>
    <fullName>SBU_User__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ALT</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>C&amp;PS</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>E&amp;T</fullName>
            </value>
            <value>
                <fullName>EngPS</fullName>
            </value>
            <value>
                <fullName>EngPS BD</fullName>
            </value>
            <value>
                <fullName>EngPS OE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FNCE</fullName>
            </value>
            <value>
                <fullName>FNCE AMER</fullName>
            </value>
            <value>
                <fullName>FNCE APAC</fullName>
            </value>
            <value>
                <fullName>FNCE ELECSOL</fullName>
            </value>
            <value>
                <fullName>FNCE EMEA</fullName>
            </value>
            <value>
                <fullName>FNCE ENGPS</fullName>
            </value>
            <value>
                <fullName>FNCE MECH</fullName>
            </value>
            <value>
                <fullName>FNCE SERVCONN</fullName>
            </value>
            <value>
                <fullName>HBT</fullName>
            </value>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>HOS</fullName>
            </value>
            <value>
                <fullName>HOS CE</fullName>
            </value>
            <value>
                <fullName>HOS CE CRM</fullName>
            </value>
            <value>
                <fullName>HOS CE SO</fullName>
            </value>
            <value>
                <fullName>HOSG</fullName>
            </value>
            <value>
                <fullName>HOS PMO</fullName>
            </value>
            <value>
                <fullName>HOS PRICING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestClass_ATR_Opp_Closed_yest.cls
/** * File Name:  TestClass_ApexShdlr_Hstry_EmailReminder
* Description Test Method
* Class Tested: ATR_Opp_Closed_yest
* Copyright : Wipro Technologies Limited Copyright (c) 2011
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
@isTest(seealldata = true)
public class TestClass_ATR_Opp_Closed_yest {
static testMethod void ATR_Opp_Closed_yest_Test() {
Date yest=System.today()-1;
list<User__c> Userlist= new list<User__c>();
attachment attchRec= new attachment();
//User__c userRec=User__c.getValues('anila.francis@wipro2234.com');
//User__c recipients = new user__c (
//email__c='anila.francis@wipro2234.com',
//Name='Anila');
//insert recipients;
//Userlist.add(recipients);
   List<User__c> recipients=User__c.getall().values();
list<Opportunity> Opplist= new list<Opportunity>();
Profile pf= [select id from Profile where name = 'System Administrator'];
User usr = new User(FirstName = 'Test1 ',LastName = 'UserEgreen',Username = '1tu1egreen@test.com',Email = recipients[0].email__c,Alias = 'tu1Test' ,
CommunityNickname= 'tu1csoTest' ,TimeZoneSidKey = 'America/Los_Angeles',LocaleSidKey='en_US',EmailEncodingKey= 'ISO-8859-1',
ProfileId = pf.Id, LanguageLocaleKey = 'en_US',SBU_User__c = 'D&S');
insert usr;
//List<User__c> recipients = new list<User__c>();
Account acc=new Account();
            acc.name='Sample';
            insert acc;
            
    
            
            Opportunity opp=new Opportunity();
            opp.Name='Sample Opp';
            opp.AccountId=acc.Id;
            //opp.stageName='Prospecting';
            opp.closeDate=yest;
            opp.Tech_Sales_Product_Area__c='Integrated Avionics';
            opp.SBU__c='ATR';
            opp.CBT_Tier_2__c='Boeing BDS';
            //opp.StageName='Closed Won';
            opp.Win_Loss_Reason_Text__c='Testing';
            opp.Win_Loss_Reason_Code__c='High Risk';
            opp.ATR_Actual_Close_Date__c=yest;
            opp.StageName='Closed Won';
            opp.ATR_Proposal_Type__c = 'AGMT';
            opp.Description='Testing';
            
            insert opp;
            opp.StageName='Closed Won';
			Test.startTest();
            update opp;
			Test.stopTest();
            
            
            Pricebook2 pb = [select name, isactive from Pricebook2 where IsStandard = true Limit 1];
            Product2 prdNew=new Product2(Name='NewProduct',ProductCode='xxx',CanUseRevenueSchedule=true);
            insert prdNew;
            PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.id,Product2Id   = prdNew.id,IsActive     = true,     UnitPrice    = 1); 
            insert pbe;
            Decimal q =5;
            Date dl1 =Date.newInstance(2011,08,1);
            Date dl2 =Date.newInstance(2011,09,12);
            OpportunityLineItem LineItem=new OpportunityLineItem( OpportunityId=Opp.Id,ServiceDate=dl1,quantity=10,pricebookentryid =pbe.Id,unitprice=1);
            insert LineItem;
            OpportunityLineItemSchedule oschedule = new OpportunityLineItemSchedule(ScheduleDate = dl2,Revenue = 10, OpportunityLineItemId=LineItem.Id,Type= 'Revenue');
            insert oschedule;
            
            
           // update opp;  
            Opplist.add(opp);
                      
    Attachment Attrec= new Attachment();
    Attrec.Name = 'TestAttachment';
    Attrec.ParentId = opp.ID;
    String body= 'testbody';       
    Blob myBlob = Blob.valueof(body);
    Attrec.body=myBlob;
    insert Attrec;
            

 ATR_Opp_Closed_yest ATrSchedule =new ATR_Opp_Closed_yest();
  String shdlr='0 0 23 * * ?';  
  System.schedule('Test ATR_Opp_Closed_yest Scheduling',shdlr,ATrSchedule);
          
}

static testMethod void ATR_Opp_Closed_yest_Test2() {
Date yest=System.today()-1;
list<User__c> Userlist= new list<User__c>();
attachment attchRec= new attachment();
//User__c userRec=User__c.getValues('anila.francis@wipro2234.com');
//User__c recipients = new user__c (
//email__c='anila.francis@wipro2234.com',
//Name='Anila');
//insert recipients;
//Userlist.add(recipients);
   List<User__c> recipients=User__c.getall().values();
list<Opportunity> Opplist= new list<Opportunity>();
Profile pf= [select id from Profile where name = 'System Administrator'];
User usr = new User(FirstName = 'Test1 ',LastName = 'UserEgreen',Username = '1tu1egreen@test.com',Email = recipients[0].email__c,Alias = 'tu1Test' ,
CommunityNickname= 'tu1csoTest' ,TimeZoneSidKey = 'America/Los_Angeles',LocaleSidKey='en_US',EmailEncodingKey= 'ISO-8859-1',
ProfileId = pf.Id, LanguageLocaleKey = 'en_US',SBU_User__c = 'D&S');
insert usr;
//List<User__c> recipients = new list<User__c>();
Account acc=new Account();
            acc.name='Sample';
            insert acc;
            
    
            
            Opportunity opp=new Opportunity();
            opp.Name='Sample Opp';
            opp.AccountId=acc.Id;
            //opp.stageName='Prospecting';
            opp.closeDate=yest;
            opp.Tech_Sales_Product_Area__c='Integrated Avionics';
            opp.SBU__c='ATR';
            opp.CBT_Tier_2__c='Boeing BDS';
            //opp.StageName='Closed Won';
            opp.Win_Loss_Reason_Text__c='Testing';
            opp.Win_Loss_Reason_Code__c='High Risk';
            opp.ATR_Actual_Close_Date__c=yest;
            opp.StageName='Closed Won';
            opp.ATR_Proposal_Type__c = 'AGMT';
            opp.Description='Testing';
            
            insert opp;
       

            
            
            Pricebook2 pb = [select name, isactive from Pricebook2 where IsStandard = true Limit 1];
            Product2 prdNew=new Product2(Name='NewProduct',ProductCode='xxx',CanUseRevenueSchedule=true);
            insert prdNew;
            PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.id,Product2Id   = prdNew.id,IsActive     = true,     UnitPrice    = 1); 
            insert pbe;
            Decimal q =5;
            Date dl1 =Date.newInstance(2011,08,1);
            Date dl2 =Date.newInstance(2011,09,12);
            OpportunityLineItem LineItem=new OpportunityLineItem( OpportunityId=Opp.Id,ServiceDate=dl1,quantity=10,pricebookentryid =pbe.Id,unitprice=1);
            insert LineItem;
            OpportunityLineItemSchedule oschedule = new OpportunityLineItemSchedule(ScheduleDate = dl2,Revenue = 10, OpportunityLineItemId=LineItem.Id,Type= 'Revenue');
            insert oschedule;
            
            
           // update opp;  
            Opplist.add(opp);
                      
    Attachment Attrec= new Attachment();
    Attrec.Name = 'TestAttachment';
    Attrec.ParentId = opp.ID;
    String body= 'testbody';       
    Blob myBlob = Blob.valueof(body);
    Attrec.body=myBlob;
    insert Attrec;
            
Test.startTest();
 ATR_Opp_Closed_yest ATrSchedule =new ATR_Opp_Closed_yest();
  String shdlr='0 0 23 * * ?';  
  System.schedule('Test ATR_Opp_Closed_yest Scheduling',shdlr,ATrSchedule);
Test.stopTest();          
}
}