src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Aircraft_Custom_Configuration__c/Aircraft_Custom_Configuration__c.object-meta.xml
<CustomObject>
    <label>Aircraft Custom Configuration</label>
    <nameField>
        <label>Aircraft LRU Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Custom Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Aircraft_Custom_Configuration__c/fields/Aircraft_Platform_Standard_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Platform_Standard_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft Platform Standard Configuration</label>
    <referenceTo>Aircraft_Platform_Configuration__c</referenceTo>
    <relationshipLabel>Aircraft Custom Configuration</relationshipLabel>
    <relationshipName>Aircraft_Custom_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/DESCRIPTION_NM__c.field-meta.xml
<CustomField>
    <fullName>DESCRIPTION_NM__c</fullName>
    <label>Description Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/Fleet_Asset_Detail__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Asset_Detail__c</fullName>
    <label>Fleet Asset Detail</label>
    <referenceTo>Fleet_Asset_Detail__c</referenceTo>
    <relationshipLabel>Aircraft Custom Configuration</relationshipLabel>
    <relationshipName>Aircraft_Custom_Configuration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/Aircraft_Platform_Configuration__c.object-meta.xml
<CustomObject>
    <label>Aircraft Platform Standard Configuration</label>
    <nameField>
        <label>LRU Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Platform Standard Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Aircraft_Platform_Configuration__c/fields/DESCRIPTION_NM__c.field-meta.xml
<CustomField>
    <fullName>DESCRIPTION_NM__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <label>Aircraft Platform</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Aircraft Platform Standard Configuration</relationshipLabel>
    <relationshipName>Aircraft_Platform_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Asset.object
<CustomObject>
</CustomObject>

src/objects/Asset/fields/OEM_Name__c.field-meta.xml
<CustomField>
    <fullName>OEM_Name__c</fullName>
    <label>OEM Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Asset/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <label>Platform Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Asset/fields/Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Type__c</fullName>
    <label>Platform Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Account (Customer) Name associated with this Fleet entry.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND ( NOT 2)</booleanFilter>
        <errorMessage>Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Account)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <formula>Platform_Name__r.Make__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aircraft Make</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Managing_SBU__c.field-meta.xml
<CustomField>
    <fullName>Managing_SBU__c</fullName>
    <formula>text( Platform_Name__r.Managing_SBU__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Managing SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Platform_Name__r.Model__c</formula>
    <label>Aircraft Model</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/New_Alert_Identification__c.field-meta.xml
<CustomField>
    <fullName>New_Alert_Identification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Alert Identification</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/OEM_Name__c.field-meta.xml
<CustomField>
    <fullName>OEM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The OEM / Maker Name for the current Fleet entry.</inlineHelpText>
    <label>OEM Name</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>OEM Name: Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (OEM Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Type__c</fullName>
    <inlineHelpText>The Fleet entry&apos;s Platform Type.</inlineHelpText>
    <label>Platform Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>The Serial Number of the current Fleet entry.</inlineHelpText>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cntry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>added on demand by Dieter for data migration</description>
    <label>Make</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Managing_SBU__c.field-meta.xml
<CustomField>
    <fullName>Managing_SBU__c</fullName>
    <label>Managing SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Platform__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Defines the Model.</inlineHelpText>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/OEM_Name__c.field-meta.xml
<CustomField>
    <fullName>OEM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defines the OEM/Maker Name for the current Platform.</inlineHelpText>
    <label>OEM Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms</relationshipLabel>
    <relationshipName>Platforms</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Type__c</fullName>
    <inlineHelpText>Defines the Platform Type.</inlineHelpText>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Airplane</fullName>
            </value>
            <value>
                <fullName>Combat Support Vehicles</fullName>
            </value>
            <value>
                <fullName>Combat Vehicles</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles</fullName>
            </value>
            <value>
                <fullName>Components</fullName>
            </value>
            <value>
                <fullName>Fire Direction Control Vehicle</fullName>
            </value>
            <value>
                <fullName>Helicopter</fullName>
            </value>
            <value>
                <fullName>Hovercraft</fullName>
            </value>
            <value>
                <fullName>Marine Craft</fullName>
            </value>
            <value>
                <fullName>Missiles &amp; Munitions</fullName>
            </value>
            <value>
                <fullName>Non-Aircraft</fullName>
            </value>
            <value>
                <fullName>Radar</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Surface Ship</fullName>
            </value>
            <value>
                <fullName>Tactical Vehicles</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestClass_ApexClass_AirPltfrmSTDConf.cls
/** * File Name:  TestClass_ApexClass_AirPltfrmSTDConf
* Description Test Method
* Class Tested: AircraftPlatformSTDConf 
* Copyright : Wipro Technologies Limited Copyright (c) 2011
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
@isTest(SeeAllData=true)
private class TestClass_ApexClass_AirPltfrmSTDConf {

    static testMethod void airPltfrmSTDConfTest() {
        
        Account tstAccRec = new Account(name = 'Test Account' );
       
        Platform__c plat1 = new Platform__c(Name='Test Platform1',Platform_Type__c='test1',Model__c='test1',Make__c='test1',Managing_SBU__c='ATR');
        insert plat1;       
       
        Fleet_Asset_Detail__c tstFleetAssetDtl = new Fleet_Asset_Detail__c( Account__c = tstAccRec.Id ,Name= 'Test Fleet Asset', OEM_Name__c=tstAccRec.Id , Platform_Name__c = plat1.id);
        insert tstFleetAssetDtl;
        
        Aircraft_Platform_Configuration__c tstAirPltStdConf = new Aircraft_Platform_Configuration__c(DESCRIPTION_NM__c = 'Test Plat Form Configuration', Platform_Name__c = plat1.id);
        insert tstAirPltStdConf;
        
        
        Aircraft_Custom_Configuration__c tstCustConfig = new Aircraft_Custom_Configuration__c(Aircraft_Platform_Standard_Configuration__c=tstAirPltStdConf.Id, Fleet_Asset_Detail__c=tstFleetAssetDtl.id);
        insert tstCustConfig;
        Test.startTest();
        ApexPages.StandardController tstController = new ApexPages.StandardController(tstFleetAssetDtl) ;
                
        AircraftPlatformSTDConf tstAirCrftPltFrm = new AircraftPlatformSTDConf(tstController);
        
        List<Aircraft_Platform_Configuration__c> tstAircrftPltList= tstAirCrftPltFrm.getPltConf();
       
        List<Aircraft_Custom_Configuration__c> tstAircrftPltList1=tstAirCrftPltFrm.getAirConf();
        
        Test.stopTest();
        
        
    }
     static testMethod void airPltfrmSTDConfTest1() {
        
        Account tstAccRec = new Account(name = 'Test Account' );
        Platform__c plat = new Platform__c(Name='Test Platform',Platform_Type__c='test',Model__c='test',Make__c='test',Managing_SBU__c='ATR');
        insert plat;
        
        Platform__c plat1 = new Platform__c(Name='Test Platform1',Platform_Type__c='test1',Model__c='test1',Make__c='test1',Managing_SBU__c='ATR');
        insert plat1;
        
         Fleet_Asset_Detail__c fleetAssetDetail = new Fleet_Asset_Detail__c();
         fleetAssetDetail.Name='testFleetAsset';
         fleetAssetDetail.Serial_Number__c ='SN61611';
         fleetAssetDetail.New_Alert_Identification__c = true;
         fleetAssetDetail.Account__c=tstAccRec.id;
         fleetAssetDetail.Platform_Name__c = plat.id;
         fleetAssetDetail.State__c='canada';
        // fleetAssetDetail.Model__c='34-tr';
         insert fleetAssetDetail;
          Attachment attach=new Attachment();     
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            attach.parentId=fleetAssetDetail.id;
            insert attach;
            
            
            
            Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=tstAccRec.Id,Phone_3__c='9986502495',Aircraft_Notifications__c=true,
            Contact_Is_Employee__c=true,  Contact_Status__c='Active' ,Employee_Number__c='E146953', 
            Employee_Contact_Role__c='Analyst',Email='test@123.com', Aircraft_Alert_for_Platforms__c=plat.id);
            insert cont;
            
            
            
        Test.startTest();    
        
        boolean isAlreadyExecuted=true; 
        AircraftNotificationsTriggerStopper.hasalreadyExecuted();
        AircraftNotificationsTriggerStopper.setalreadyExecuted();
        AircraftNotificationsTriggerStopper.unsetalreadyExecuted();
        //Added by Sagarika
        AircraftNotificationsTriggerStopper.setalreadyExecutedPFECN();
        AircraftNotificationsTriggerStopper.hasalreadyExecutedNavdb();
        AircraftNotificationsTriggerStopper.setalreadyExecutedNavdb();
        AircraftNotificationsTriggerStopper.setalreadyExecutedORdersRT();
        AircraftNotificationsTriggerStopper.hasalreadyExecutedDupeOppty();
        AircraftNotificationsTriggerStopper.setalreadyExecutedDupeOppty();
        AircraftNotificationsTriggerStopper.hasalreadyExecutedPPO();
        AircraftNotificationsTriggerStopper.setalreadyExecutedPPO();
        AircraftNotificationsTriggerStopper.hasalreadyExecutedPFECN();
        AircraftNotificationsTriggerStopper.setalreadyExecutedPFECN();
        AircraftNotificationsTriggerStopper.unsetalreadyExecuted();
        AircraftNotificationsTriggerStopper.hasalreadyExecutedORdersRT();
        plat.Parent_Platform__c=plat1.id;
        update plat; 
        
        AircraftNotificationsTriggerStopper.unsetalreadyExecuted();
        fleetAssetDetail.Fleet_Asset_Notification__c = true; 
        update fleetAssetDetail;
        Test.stopTest();
        
        
    }
}