src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Type_of_Change__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Change__c</fullName>
    <label>Type of Change</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HAPP</fullName>
            </value>
            <value>
                <fullName>MSP Account</fullName>
            </value>
            <value>
                <fullName>New Account</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tax Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestClass_EmailAttachmentCopy.cls
/***********************************************************************************************************
* Company Name          : Honeywell Aero
* Name                  : TestClass_EmailAttachmentCopy
* Description           : Test Class to test the functionality of the class EmailAttachmentCopy.
* 
* Modification History  :
* Date              Version No.     Modified by Brief Description of Modification
* 21-May-2013       0.01            NTTData     Initial Version
* 24-Nov-2014       0.02            NTTDATA     Included test data for INC000007037567
* 23-07-2019        0.03            NTTDATA     Increased code coverage
***********************************************************************************************************/
@isTest
Public class TestClass_EmailAttachmentCopy{
    
   public static testmethod void attachmenttest()
    {
        
    Case cse = new Case();
        cse.Origin = 'XML Order';
        cse.Status = 'Open';
        cse.RecordTypeId = Label.XML_Orders_RecordType_Id;
        cse.Classification__c = 'Customer Master Team / eBusiness';
        //cse.ContactId = lstContacts[i].Id;
        cse.Type_of_Change__c = 'New Account';
        cse.Type = 'Other';
        cse.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cse.Government_Compliance_SM_M_Content__c = 'NO';
        cse.Ownerid = Label.aero_default_user_id;
        cse.CreatedByID = label.aero_default_user_id;
        cse.SuppliedEmail = 'XMLtest@test.com';
        insert cse;
        Emailmessage e1 = new Emailmessage(parentid=cse.id);
        e1.ToAddress=label.Conexiom_RO_Email_Address;
        e1.Incoming=False;
        e1.ParentID = cse.ID;
        e1.subject = 'test subject';
        insert e1;
       /* Emailmessage e2 = new Emailmessage(parentid=cse.id);
        e2.ToAddress='test@test.com';
        e2.Incoming=False;
        insert e2; */
        
        Attachment a1 = new Attachment(name='sample',body=blob.valueof('samplebody'),parentid=e1.id, ContentType='text/xml');
        insert a1;
        
      EmailMessage e=   [select ID,ParentID,Status,MessageDate,subject,HasAttachment,Parent.createdDate from EmailMessage where Id=: e1.id];
        system.debug('email===' +e);
        //Time csTime = e1.Parent.createdDate.Time();
        //Time eTime = e1.MessageDate.Time();
       // decimal diffTime = ((e1.MessageDate.getTime())/1000/60)- ((e1.Parent.createdDate.getTime())/1000/60);
        List<attachment> caseatt = new List<attachment>();
        Attachment aobj = new Attachment();
            aobj.name=a1.name;
            aobj.body=a1.body;
            aobj.ContentType = a1.ContentType;
            aobj.parentid = cse.id;
            caseatt.add(aobj);
            
            if(caseatt.size()>0){
                insert caseatt;
            }
        
        
        Set<ID> temp = new Set<ID>();
        temp.add(e1.id);
        test.startTest();
       // UpdateCountOpenActivities.flag = false;
        EmailAttachmentCopy ea =new EmailAttachmentCopy();
        try{
          EmailAttachmentCopy.attachcase(temp);
        }
        catch(Exception e4)
        {
        system.debug('error in test' + e4.getMessage());
        }
        test.stopTest();
    }
    
    
    
    public static testmethod void attachmenttest1()
    {
        Case cse = new Case();
        cse.Origin = 'XML Order';
        cse.Status = 'Open';
        cse.RecordTypeId = Label.XML_Orders_RecordType_Id;
        cse.Classification__c = 'Customer Master Team / eBusiness';
        //cse.ContactId = lstContacts[i].Id;
        cse.Type_of_Change__c = 'New Account';
        cse.Type = 'Other';
        cse.Export_Compliance_Content_ITAR_EAR__c = 'NO';
        cse.Government_Compliance_SM_M_Content__c = 'NO';
        cse.Ownerid = Label.aero_default_user_id;
        cse.CreatedByID = label.aero_default_user_id;
        cse.SuppliedEmail = 'XMLtest@test.com';
        insert cse;
        Emailmessage e1 = new Emailmessage(parentid=cse.id);
        e1.ToAddress=label.Conexiom_RO_Email_Address;
        e1.Incoming=False;
        e1.ParentID = cse.ID;
        e1.subject = 'test subject';
        //e1.HasAttachment = false;
        insert e1;
       /* Emailmessage e2 = new Emailmessage(parentid=cse.id);
        e2.ToAddress='test@test.com';
        e2.Incoming=False;
        insert e2; */
        
        
        
        Set<ID> temp = new Set<ID>();
        temp.add(e1.id);
        test.startTest();
       // UpdateCountOpenActivities.flag = false;
        EmailAttachmentCopy ea =new EmailAttachmentCopy();
        try{
          EmailAttachmentCopy.attachcase(temp);
        }
        catch(Exception e4)
        {
        system.debug('error in test' + e4.getMessage());
        }
        test.stopTest();
    }
     
}