src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <description>Business Segment is relabeled as CBT as per Business request.</description>
    <inlineHelpText>A further division into Business Segments within the Strategic Business Unit/Market (e.g., Aftermarket, Airlines, Military/Operators, etc.)</inlineHelpText>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES CBT</fullName>
            </value>
            <value>
                <fullName>DEW</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
                <label>Embraer D&amp;S</label>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <inlineHelpText>One of three strategic regions: EMEAI, APAC, Americas.  This value is assigned based on the Sub-Region Name.  EMEAI = Europe, Middle East, Africa, India.  APAC = Asia Pacific.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Asia/Pacific Rim</fullName>
            </value>
            <value>
                <fullName>Europe/MiddleEast/Africa/India</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/REPORT_ACCOUNT_NAME__c.field-meta.xml
<CustomField>
    <fullName>REPORT_ACCOUNT_NAME__c</fullName>
    <label>REPORT ACCOUNT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <inlineHelpText>A category that indicates the type of service the customer is expected to receive, as determined by HON business entities based on sales, anticipated opportunities, etc.</inlineHelpText>
    <label>Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Refer to Network</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Superior</fullName>
            </value>
            <value>
                <fullName>Unauthorized Dist/Brkr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Sub_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_Name__c</fullName>
    <inlineHelpText>A specific country or area that is derived from a larger region or continent.  It is generally based on location (Europe, Middle East, Japan, etc.) but occasionally is based on business divisions</inlineHelpText>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region_Name__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Australia / NZ</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>China / HKG</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Russia and CU</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU_Contact__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S Other CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
            <value>
                <fullName>General Atomics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Portal_User_Registration__c/Portal_User_Registration__c.object-meta.xml
<CustomObject>
    <description>Custom object to track the MyAerospace Portal User Registration</description>
    <label>Portal User Registration</label>
    <nameField>
        <displayFormat>PUR-{00000}</displayFormat>
        <label>Portal User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal User Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_User_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portal User Registrations</relationshipLabel>
    <relationshipName>Portal_User_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Portal_User_Registration__c/fields/Contact_Creation_in_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Contact_Creation_in_SFDC__c</fullName>
    <description>Field to hold the success iteration for Contact Creation in SFDC step in Portal</description>
    <label>Contact_Creation_in_SFDC</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

src/objects/Portal_User_Registration__c/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <description>Field to hold the Honeywell ID value provided by Portal user during registration</description>
    <label>Honeywell ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

src/classes/PursendmailTest.cls
@isTest()
public class PursendmailTest{

    static testMethod void firstTest() 
    {
    Account acc = new Account();
acc.Name = 'Honeywell Test';
acc.Customer_Status__c = 'Active';
acc.Strategic_Business_Unit__c = 'ATR';
acc.CBT__c = 'Airbus';
acc.Region_Name__c = 'Americas';
acc.Sub_Region_Name__c = 'Canada';
acc.Service_Level__c = 'Standard';
acc.Type = 'OEM';
acc.REPORT_ACCOUNT_NAME__c = 'HONEYWELL TEST';

insert acc;

Contact con = new Contact();
con.LastName = 'Singh';
con.FirstName = 'Kapil';
con.AccountId = acc.Id;
con.Primary_Email_Address__c = 'kapil.nowhere@gmail.com.qa';
con.Email='kapil.nowhere@gmail.com.qa';
insert con;
    
    Portal_User_Registration__c p=new Portal_User_Registration__c();
     p.Contact_Creation_in_SFDC__c='N';
     p.Honeywell_ID__c='1234';
     p.Contact__c=con.id;
     insert p;  
     
     p.Contact_Creation_in_SFDC__c='Y';
     update p;
     
    
    }
    
  }