src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Market__c</fullName>
        <description>Legal Entity Field Req #625</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Market North America</fullName>
                </value>
                <value>
                    <fullName>Market Latin America</fullName>
                </value>
                <value>
                    <fullName>Market Middle East and Africa</fullName>
                </value>
                <value>
                    <fullName>Market India</fullName>
                </value>
                <value>
                    <fullName>Market Greater China</fullName>
                </value>
                <value>
                    <fullName>Market Europe</fullName>
                </value>
                <value>
                    <fullName>Market Asia Pacific &amp; Japan</fullName>
                </value>
                <value>
                    <fullName>Market Other</fullName>
                </value>
                <value>
                    <fullName>Market NFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Account/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <label>Company Address</label>
    <type>TextArea</type>
</CustomField>

src/objects/Contact/fields/Company_E_Mail_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_E_Mail_Address__c</fullName>
    <label>Company E-Mail Address</label>
    <type>Email</type>
</CustomField>

src/objects/Contact/fields/Customer_Portal_UserId__c.field-meta.xml
<CustomField>
    <fullName>Customer_Portal_UserId__c</fullName>
    <label>Customer Portal UserId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <inlineHelpText>Defines the Job Title for the current Contact.</inlineHelpText>
    <label>Job Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/objects/Contact/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Req #1313. Required for Marketo Sync</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MARKET NORTH AMERICA</fullName>
            </value>
            <value>
                <fullName>MARKET EUROPE</fullName>
            </value>
            <value>
                <fullName>MARKET GREATER CHINA</fullName>
            </value>
            <value>
                <fullName>MARKET INDIA</fullName>
            </value>
            <value>
                <fullName>MARKET LATIN AMERICA</fullName>
            </value>
            <value>
                <fullName>MARKET MIDDLE EAST AND AFRICA</fullName>
            </value>
            <value>
                <fullName>MARKET ASIA PACIFIC &amp; JAPAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Phone_1_Ext__c.field-meta.xml
<CustomField>
    <fullName>Phone_1_Ext__c</fullName>
    <inlineHelpText>Extension for primary phone if applicable.</inlineHelpText>
    <label>Primary Work Number Ext</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Web_Portal_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Portal_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Web Portal Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market field Built for requirement - 615. Dependent on Country field</description>
    <label>User Market</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market North America</fullName>
            </value>
            <value>
                <fullName>Market Latin America</fullName>
            </value>
            <value>
                <fullName>Market Middle East and Africa</fullName>
            </value>
            <value>
                <fullName>Market India</fullName>
            </value>
            <value>
                <fullName>Market Greater China</fullName>
            </value>
            <value>
                <fullName>Market Europe</fullName>
            </value>
            <value>
                <fullName>Market Asia Pacific &amp; Japan</fullName>
            </value>
            <value>
                <fullName>MARKET AMERICA</fullName>
                <isActive>false</isActive>
                <label>MARKET AMERICA</label>
            </value>
            <value>
                <fullName>MARKET ASIA AND JAPAN</fullName>
                <isActive>false</isActive>
                <label>MARKET ASIA AND JAPAN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/Web_Portal_Contact_Citizenship__c.object-meta.xml
<CustomObject>
    <description>For honeywell traing webportal tool contact citizenship information</description>
    <label>Web Portal Contact Citizenship</label>
    <nameField>
        <label>Birth City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Portal Contact Citizenships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Alternate_Work_Number__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Work_Number__c</fullName>
    <description>For updating of additional information in honeywell trainig</description>
    <label>Alternate Work Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Company_E_Mail_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_E_Mail_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Web Portal Contact Citizenships</relationshipLabel>
    <relationshipName>Web_Portal_Contact_Citizenships</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Secondary Email address</label>
    <type>Email</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>For updating contact information for honeywell traing</description>
    <inlineHelpText>Enter Jobtitle</inlineHelpText>
    <label>Job Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Transport</fullName>
            </value>
            <value>
                <fullName>Business Aviation</fullName>
            </value>
            <value>
                <fullName>General Aviation</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Helicopters</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>Non-Aerospace</fullName>
            </value>
            <value>
                <fullName>Regional Transport</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Phone_1_Ext__c.field-meta.xml
<CustomField>
    <fullName>Phone_1_Ext__c</fullName>
    <label>Primary Work Number Ext</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Primary_Work_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Work_Number__c</fullName>
    <label>Primary Work Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Web_Portal_Contact_Citizenship__c/fields/Web_Portal_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Portal_Company_Name__c</fullName>
    <label>Company Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

src/classes/Testcls_Apextrgr_webtooladditional.cls
@isTest(SeeAllData=false)
private class Testcls_Apextrgr_webtooladditional{
    static testMethod void Testcls_Apextrgr_webtooladditional(){ 
    test.starttest();
      // ID ProfileID = [ Select id from Profile where name = 'Training - Customer Portal'].id;
        Account A1 = new Account(Name = 'Test Account');
        insert A1;
        Account A2 = new Account(Name = 'Test Account');
        insert A2;
        List<Contact> ContactList = new List<Contact>();
        Contact C1 = new Contact( AccountID = A1.id, FirstName = 'Test', LastName = 'User',Honeywell_ID__c='E801543', 
        email = 'test-user@fakeemail.com' );
        insert C1;
 
        User u1 = new User( email='rathinam.ayyappan@honeywell.com', contactid = c1.id, profileid = label.Custom_Customer_Portal, 
                UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1', 
        TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
        LanguageLocaleKey='en_US', FirstName = 'Test', LastName = 'User',employeenumber='E407308' );
        insert u1;          
        try
        {
          C1.Customer_Portal_UserId__c =u1.id;
          upsert C1;
        }
        catch(Exception e){}
        system.runas(u1)
        {
       Web_Portal_Contact_Citizenship__c vlt= new Web_Portal_Contact_Citizenship__c
       (   
        First_Name__c='venkat',
        Last_Name__c='vvvvvv',
        Email_Address__c='rathinam.ayyappan@honeywell.com',
        Company_Name__c=A2.id,
        City_Name__c='bangalore',
        Web_Portal_Company_Name__c='nttdata',
        Job_Title__c='developer',
        Company_E_Mail_Address__c='rathinam.ayyappan@honeywell.com',
        Primary_Work_Number__c='7894561231',
        Alternate_Work_Number__c='9999999999',
        Fax_Number__c='GT456789',
        Market__c='Business Aviation',
        Phone_1_Ext__c='88143419',
        MobilePhone__c='9999999999',
        Company_Address__c='bangalore',
        State_Code__c='bangalore',
        Country_Name__c='india',
        Postal_Code__c='123456789',
        Name = 'test',
        Birth_city__c='India',
        Contact_Birth_Country__c = 'GDC',
        Contact_Citizenship_Country__c = 'High',
        Contact_Citizenship_Country2__c = 'Monitor',
        Passport_Number__c = 'H7777',
        Passport_Expiry_Date__c = system.today()+5,
        Visa_Number__c= 'T7777',
        Visa_Type__c='H1-B',
        Address_Line_1_c__c='basavnna Gudi',
        Address_Line_2__c='south end circle',
        Address_Line_3__c='bangalore',
        Visa_Expiry_Date__c = system.today()+3,
        createddate = system.today()-10,
        Is_US_Citizen__c = false        
       );
       try
       {
            update(vlt);
            u1.firstname = 'venkat';
            u1.lastname='test';
            u1.email='mythreyee.sureshkumar@honeywell.com';                        
            u1.title = 'developer';                               
            u1.phone = '1234567891';
            u1.Extension ='88143419'; 
            u1.MobilePhone = '9999999999'; 
            u1.fax ='FAX123'; 
            u1.postalcode = '999999'; 
            u1.city = 'bangalore';
            u1.state = 'karnatka';              
            u1.country = 'india';
            //upsert(u1);
            
       } 
       catch(exception e){}             
      }    
      test.stoptest();         
    }
}