src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Customer_Portal_UserId__c.field-meta.xml
<CustomField>
    <fullName>Customer_Portal_UserId__c</fullName>
    <label>Customer Portal UserId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/Batch_User__c.field-meta.xml
<CustomField>
    <fullName>Batch_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch User</label>
    <type>Checkbox</type>
</CustomField>

src/classes/Test_CustomResOrganizerLookupController.cls
@isTest(SeeAllData=true)
private class Test_CustomResOrganizerLookupController {
      static testMethod void CustomResOrganizerLookupController()
      {  
         
            Profile pf = [ Select id from Profile where name = 'Training - Customer Portal'];
            Account A1 = new Account(Name = 'Test Account');
            insert A1;
            Contact C1 = new Contact( AccountID = A1.id, FirstName = 'Test', LastName = 'User',Honeywell_ID__c='E812402', email = 'venkatesh.athanti@honeywell.com',Employee_Number__c = 'E123123' );
            insert C1;                            
            user u2=[select id,name,email from user where Batch_User__c = true and profileid =: pf.id and isactive = true limit 1];             
            try
            {
                C1.Customer_Portal_UserId__c =u2.id;
                upsert C1;
                upsert A1;
            }
            catch(Exception e){}
            System.runas(u2)
            {                  
              CustomResOrganizerLookupController cus=new CustomResOrganizerLookupController(); 
              cus.next();
              cus.previous();
              cus.Search();
              //cus.runSearch();
              cus.getFormTag();
              cus.getTextBox(); 
            }
      }
  }