src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Account)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contract/fields/Aircraft__c.field-meta.xml
<CustomField>
    <fullName>Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft</label>
    <referenceTo>Fleet_Asset_Detail__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contract/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <description>Field created for Service interface project</description>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Contract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adv Payment</fullName>
            </value>
            <value>
                <fullName>APM</fullName>
            </value>
            <value>
                <fullName>APU Selection Agreement</fullName>
            </value>
            <value>
                <fullName>Asset Availability - Other</fullName>
            </value>
            <value>
                <fullName>Authorized Service Centers</fullName>
            </value>
            <value>
                <fullName>Avionics Selection Agreement</fullName>
            </value>
            <value>
                <fullName>Bailment Agreement</fullName>
            </value>
            <value>
                <fullName>BFE</fullName>
            </value>
            <value>
                <fullName>BOA</fullName>
            </value>
            <value>
                <fullName>CBL</fullName>
            </value>
            <value>
                <fullName>Cost Reimbursable</fullName>
            </value>
            <value>
                <fullName>Cost Share</fullName>
            </value>
            <value>
                <fullName>CPAL</fullName>
            </value>
            <value>
                <fullName>CPFF</fullName>
            </value>
            <value>
                <fullName>CPIF</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale ACES Based</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale Non ACES Based</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Designee Agreement</fullName>
            </value>
            <value>
                <fullName>Development Contract</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>EMCPP</fullName>
            </value>
            <value>
                <fullName>Exchange Agreement</fullName>
            </value>
            <value>
                <fullName>FFP</fullName>
            </value>
            <value>
                <fullName>Fixed Fee Incentive</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>FMP</fullName>
            </value>
            <value>
                <fullName>FMS</fullName>
            </value>
            <value>
                <fullName>FPPO</fullName>
            </value>
            <value>
                <fullName>HAPP-MPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Account (Customer) Name associated with this Fleet entry.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND ( NOT 2)</booleanFilter>
        <errorMessage>Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Account)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Aircraft_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Delivery_Date__c</fullName>
    <label>Aircraft Delivery Date</label>
    <type>Date</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Inside_Sales__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inside Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fleet_Asset_Aircraft3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/OEM_Warranty_Period__c.field-meta.xml
<CustomField>
    <fullName>OEM_Warranty_Period__c</fullName>
    <formula>ADDMONTHS(Aircraft_Delivery_Date__c,VALUE(Text((Platform_Name__r.OEM_Warranty_Period__c))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avionics OEM Warranty Period</label>
    <type>Date</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <description>Field created for Service Interface project</description>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>The Fleet entry&apos;s Type.</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Inside_Sales__c/Inside_Sales__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inside Sales</label>
</CustomObject>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Aircraft__c.field-meta.xml
<CustomField>
    <fullName>Aircraft__c</fullName>
    <label>Aircraft</label>
    <summaryFilterItems>
        <field>Fleet_Asset_Detail__c.Status__c</field>
        <operation>equals</operation>
        <value>In Service,Storage</value>
    </summaryFilterItems>
    <summaryForeignKey>Fleet_Asset_Detail__c.Platform_Name__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Platform__c/fields/OEM_Warranty_Period__c.field-meta.xml
<CustomField>
    <fullName>OEM_Warranty_Period__c</fullName>
    <label>Avionics OEM Warranty Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>72</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/UnitTest_TaskLogic.cls
@isTest
public class UnitTest_TaskLogic{
    testMethod static void testTaskCreation(){
       Account acct = new Account(Name='Test',Strategic_Business_Unit__c='BGA');
        insert acct;
      Platform__c pla =new Platform__c();
      pla.OEM_warranty_period__c ='12';
             insert pla;
       Fleet_Asset_Detail__c faa = new Fleet_Asset_Detail__c();
      
       faa.Aircraft_Delivery_Date__c = Date.today();
       faa.Platform_Name__c = pla.id;
       faa.Account__c = acct.id;
       faa.Inside_Sales__c=UserInfo.getUserId();
       faa.Aircraft_Delivery_Date__c = Date.today().addMonths(-12);
       
       insert faa;
       
        Fleet_Asset_Detail__c faa1 = new Fleet_Asset_Detail__c();
      
       faa1.Aircraft_Delivery_Date__c = Date.today();
       faa1.Platform_Name__c = pla.id;
       faa1.Account__c = acct.id;
       faa1.Inside_Sales__c=UserInfo.getUserId();
       faa1.Aircraft_Delivery_Date__c = Date.today().addMonths(-12);
       
       insert faa1;
        
      contract newcontract1 = new contract(accountid=acct.id,startdate=date.valueOf('2017-02-22'),status='Draft',Aircraft__c=faa.id,EndDate=system.today(),Type__c='APM',Site_Name__c='SAP_CNT');       
        insert newcontract1; 
        contract newcontract2 = new contract(accountid=acct.id,startdate=date.valueOf('2017-02-22'),status='Draft',Aircraft__c=faa.id,EndDate=system.today(),Type__c='HAPP-MPP',Site_Name__c='SAP_CNT');       
        insert newcontract2;  
       TaskLogicScheduler p = new TaskLogicScheduler(); //Schedule apex class name
       String sch = '0 0 * * * ?'; //schedule interval time
       system.schedule('One Time Pro', sch, p); //system method to schedule apex class*/
    }
}