src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <description>Business Segment is relabeled as CBT as per Business request.</description>
    <inlineHelpText>A further division into Business Segments within the Strategic Business Unit/Market (e.g., Aftermarket, Airlines, Military/Operators, etc.)</inlineHelpText>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Strategic_Business_Unit__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES CBT</fullName>
            </value>
            <value>
                <fullName>DEW</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>Embraer D&amp;S CBT</fullName>
                <label>Embraer D&amp;S</label>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <inlineHelpText>One of three strategic regions: EMEAI, APAC, Americas.  This value is assigned based on the Sub-Region Name.  EMEAI = Europe, Middle East, Africa, India.  APAC = Asia Pacific.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Asia/Pacific Rim</fullName>
            </value>
            <value>
                <fullName>Europe/MiddleEast/Africa/India</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/REPORT_ACCOUNT_NAME__c.field-meta.xml
<CustomField>
    <fullName>REPORT_ACCOUNT_NAME__c</fullName>
    <label>REPORT ACCOUNT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Account/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <inlineHelpText>A category that indicates the type of service the customer is expected to receive, as determined by HON business entities based on sales, anticipated opportunities, etc.</inlineHelpText>
    <label>Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Refer to Network</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Superior</fullName>
            </value>
            <value>
                <fullName>Unauthorized Dist/Brkr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Account/fields/Sub_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_Name__c</fullName>
    <inlineHelpText>A specific country or area that is derived from a larger region or continent.  It is generally based on location (Europe, Middle East, Japan, etc.) but occasionally is based on business divisions</inlineHelpText>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region_Name__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Australia / NZ</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>China / HKG</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>Russia and CU</fullName>
            </value>
            <value>
                <fullName>South East Asia</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Unmapped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/AOP_For_Sales_Manger__c/AOP_For_Sales_Manger__c.object-meta.xml
<CustomObject>
    <label>AOP For Sales Manger</label>
    <nameField>
        <displayFormat>AOPSM-{0000000}</displayFormat>
        <label>AOP For Sales Manger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AOP For Sales Mangers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AOP_For_Sales_Manger__c/fields/AOP_BGA_AM__c.field-meta.xml
<CustomField>
    <fullName>AOP_BGA_AM__c</fullName>
    <label>AOP BGA AM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/AOP_For_Sales_Manger__c/fields/Opp_Closed_Won_Amount_for_RMU__c.field-meta.xml
<CustomField>
    <fullName>Opp_Closed_Won_Amount_for_RMU__c</fullName>
    <label>Opp Closed Won Amount for RMU</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/AOP_For_Sales_Manger__c/fields/Pipeline_BGA_AM__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_BGA_AM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BGA AM Total Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/AOP_For_Sales_Manger__c/fields/Pipeline_BGA_AM_Factored__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_BGA_AM_Factored__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BGA AM Factored Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/AOP_For_Sales_Manger__c/fields/Pipeline_RMU__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_RMU__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RMU Total Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/AOP_For_Sales_Manger__c/fields/Pipeline_RMU_Factored__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_RMU_Factored__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RMU Factored Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/AOP_For_Sales_Manger__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AOP_For_Sales_Mangers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Regional_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Sales_Manager__c</fullName>
    <label>Regional Sales Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bernard Guillot</fullName>
            </value>
            <value>
                <fullName>Emil Pope</fullName>
            </value>
            <value>
                <fullName>Frank Muscolino</fullName>
            </value>
            <value>
                <fullName>Freddie Zonoozi</fullName>
            </value>
            <value>
                <fullName>James Zhou</fullName>
            </value>
            <value>
                <fullName>Jason Wissink</fullName>
            </value>
            <value>
                <fullName>Joanie Alderman</fullName>
            </value>
            <value>
                <fullName>John Wong</fullName>
            </value>
            <value>
                <fullName>Kathy Tyler</fullName>
            </value>
            <value>
                <fullName>Kevin Haynes</fullName>
            </value>
            <value>
                <fullName>Marc Parizot</fullName>
            </value>
            <value>
                <fullName>Megan Towne</fullName>
            </value>
            <value>
                <fullName>Nadya Krisko</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Paul David</fullName>
            </value>
            <value>
                <fullName>Raghed Talih</fullName>
            </value>
            <value>
                <fullName>Roger Dykmann</fullName>
            </value>
            <value>
                <fullName>Shashank Shekhar</fullName>
            </value>
            <value>
                <fullName>Stephen Alcock</fullName>
            </value>
            <value>
                <fullName>Ted Varner</fullName>
            </value>
            <value>
                <fullName>Thinus Svendsen.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/REPORT_ACCOUNT_NAME__c.field-meta.xml
<CustomField>
    <fullName>REPORT_ACCOUNT_NAME__c</fullName>
    <label>REPORT ACCOUNT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Sales_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Type__c</fullName>
    <label>Sales Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Completion</fullName>
            </value>
            <value>
                <fullName>Demo / Test</fullName>
            </value>
            <value>
                <fullName>Management Co</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Retrofit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <formula>text(Opportunity.CBT_Tier_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CBT</label>
    <type>Text</type>
</CustomField>

src/classes/calculateAOP_Test.cls
@isTest (seeAllData=true)
public class calculateAOP_Test {
    static testMethod void CAOP_Method1(){
        test.startTest();
        
        AOP_For_Sales_Manger__c afsm = new AOP_For_Sales_Manger__c();
        afsm.AOP_BGA_AM__c=1.0;
        afsm.Sales_Manager__c=UserInfo.getUserId();
        afsm.Opp_Closed_Won_Amount_for_RMU__c = 0;
        afsm.Pipeline_BGA_AM_Factored__c = 0;
        afsm.Pipeline_BGA_AM__c = 0;
        afsm.Pipeline_RMU__c = 0;
        afsm.Pipeline_RMU_Factored__c = 0;
        insert afsm;
        
        Account acc = new Account();
        acc.Name = 'Testweb';
        acc.Customer_Status__c = 'Active';
        acc.Strategic_Business_Unit__c = 'BGA';
        acc.CBT__c = 'BGA Aftermarket';
        acc.Region_Name__c = 'Americas';
        acc.Sub_Region_Name__c = 'Canada';
        acc.Service_Level__c = 'Standard';
        acc.Type = 'Honeywell';
        acc.REPORT_ACCOUNT_NAME__c = 'Honeywell';
        insert acc;
        
        Opportunity opp= new opportunity();
        opp.Name= 'Test Oppty';
        opp.CloseDate=system.today();
        opp.AccountId= acc.id;
        opp.StageName= 'Prospecting' ;   
        opp.Type= 'BGA Aftermarket';
        opp.Regional_Sales_Manager__c= 'Mary Mcbride';
        opp.Sales_Type__c='Retrofit';
        opp.ForecastCategoryName = 'Pipeline';
        opp.Ownerid = afsm.Sales_Manager__c;
        opp.recordtypeid='01230000000bN7l';
        opp.dealer_account__c='0013000000bFxtr';
        insert opp;
        
        
        Product2 pdt = [select id,Name from Product2 where Name='unknown' limit 1];
                
        PricebookEntry pb = [SELECT Id,Pricebook2Id,Product2Id FROM PricebookEntry where product2.name = 'unknown' limit 1];
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.opportunityid = opp.id;
        oli.Quantity = 20;
        oli.Revenue_Type__c = 'Engineering';
        oli.ServiceDate = system.today();
        oli.UnitPrice = 30;
        oli.Probability__c = 1;
        oli.Pricebookentryid = pb.id;
        insert oli;
        
        calculateAOP cap = new calculateAOP(afsm.Id,2015);
        cap.calculate();
        
        
        
        /*OpportunityLineItem oli = new OpportunityLineItem();
        oli.opportunityid=opp.Id;
        oli.Quantity=1.0;
        oli.totalPrice = 1.0;
        //oli.UnitPrice=10;
        oli.PricebookEntryId=pbe.Id;
        insert oli;
        */
        
        
        test.stopTest();
    }
}