src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Contract_Number_I_Many__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number_I_Many__c</fullName>
    <formula>Contract__r.Contract_Number_I_Many__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Number(I-Many)</label>
    <type>Text</type>
</CustomField>

src/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract/fields/Asset_Program__c.field-meta.xml
<CustomField>
    <fullName>Asset_Program__c</fullName>
    <label>Asset Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract/fields/Contract_Number_I_Many__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number_I_Many__c</fullName>
    <label>Contract Number(Ariba)</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Contract/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>COP</fullName>
            </value>
            <value>
                <fullName>CZK</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>DZD</fullName>
            </value>
            <value>
                <fullName>EGP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>ILS</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>IRR</fullName>
            </value>
            <value>
                <fullName>ISK</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>MAD</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>NGN</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract/fields/End_date_Required__c.field-meta.xml
<CustomField>
    <fullName>End_date_Required__c</fullName>
    <label>End Date Required?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <description>Can be used to track Amendments</description>
    <inlineHelpText>Number of Revisions / Amendments to this Contract</inlineHelpText>
    <label>Revision</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Contract/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adv Payment</fullName>
            </value>
            <value>
                <fullName>APM</fullName>
            </value>
            <value>
                <fullName>APU Selection Agreement</fullName>
            </value>
            <value>
                <fullName>Asset Availability - Other</fullName>
            </value>
            <value>
                <fullName>Authorized Service Centers</fullName>
            </value>
            <value>
                <fullName>Avionics Selection Agreement</fullName>
            </value>
            <value>
                <fullName>Bailment Agreement</fullName>
            </value>
            <value>
                <fullName>BFE</fullName>
            </value>
            <value>
                <fullName>BOA</fullName>
            </value>
            <value>
                <fullName>CBL</fullName>
            </value>
            <value>
                <fullName>Cost Reimbursable</fullName>
            </value>
            <value>
                <fullName>Cost Share</fullName>
            </value>
            <value>
                <fullName>CPAL</fullName>
            </value>
            <value>
                <fullName>CPFF</fullName>
            </value>
            <value>
                <fullName>CPIF</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale ACES Based</fullName>
            </value>
            <value>
                <fullName>D&amp;S Product Sale Non ACES Based</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Designee Agreement</fullName>
            </value>
            <value>
                <fullName>Development Contract</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>EMCPP</fullName>
            </value>
            <value>
                <fullName>Exchange Agreement</fullName>
            </value>
            <value>
                <fullName>FFP</fullName>
            </value>
            <value>
                <fullName>Fixed Fee Incentive</fullName>
            </value>
            <value>
                <fullName>Flat Rate</fullName>
            </value>
            <value>
                <fullName>FMP</fullName>
            </value>
            <value>
                <fullName>FMS</fullName>
            </value>
            <value>
                <fullName>FPPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestClass_ContractEndNotification.cls
@isTest(SeeAllData=false)
private class TestClass_ContractEndNotification
{
    static testMethod void TestClass_ContractEndNotification() 
    { 
       Date today1 = date.valueof(system.today()+ 90);        
       Account A1 = new Account(Name = 'Test Account');
        insert A1;
       contract contr=new contract();
       contr.Contract_Number_I_Many__c='Test contr';
       contr.Type__c='APU Selection Agreement';
       contr.Asset_Program__c='NO';
       contr.Status='New';
       contr.StartDate=today1;
       contr.End_date_Required__c ='NO';
       contr.EndDate=today1;
      //contr.Revision__c=2;
       contr.Currency__c='ARS';
       contr.AccountID =A1.id;
       insert contr;
       
       Test.StartTest(); 
       ContractEndNotification  cont= new ContractEndNotification ();
       database.executeBatch(cont,20);
       Test.StopTest(); 
    }
}