src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Notes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/objects/Account/fields/Business_Focal__c.field-meta.xml
<CustomField>
    <fullName>Business_Focal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>CBM</inlineHelpText>
    <label>Business Focal</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Business Focal)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account/fields/Sbl_Account_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Sbl Account Row ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Additional_Web_Form_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Web_Form_Info__c</fullName>
    <label>Additional Web Form Info</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Business_Focal__c.field-meta.xml
<CustomField>
    <fullName>Business_Focal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Added as per Michelle&apos;s request.</description>
    <label>Business Focal</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Business Focal)</relationshipLabel>
    <relationshipName>Cases6</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Customer_PO_RO_WONumber__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_RO_WONumber__c</fullName>
    <description>Text Field used to hold the PO number. 
05/22 - Set to external ID for PO/SN deployment to avoid 554 connection error in Salesforce</description>
    <externalId>true</externalId>
    <label>Customer PO/RO/WO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Changed the Field Type from Textarea  to Textarea(Long) for SR 432766.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Sbl_Account_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_Id__c</fullName>
    <label>Sbl Account Row Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Sbl_Account_Row_ID__c.field-meta.xml
<CustomField>
    <fullName>Sbl_Account_Row_ID__c</fullName>
    <label>Sbl Account Row ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Invoices_for_fscmCase__c/Invoices_for_fscmCase__c.object-meta.xml
<CustomObject>
    <description>Invoices Related to Cases from SAP FSCM disputes</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoices_for_fscmCase__c/fields/FSCM_ID__c.field-meta.xml
<CustomField>
    <fullName>FSCM_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>FSCM ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Invoices_for_fscmCase__c/fields/FSCM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSCM_Status__c</fullName>
    <label>FSCM Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Invoices_for_fscmCase__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/User_EID__c.field-meta.xml
<CustomField>
    <fullName>User_EID__c</fullName>
    <label>User EID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/classes/AEROSAPtoSFtest.cls
@isTest
public class AEROSAPtoSFtest {
       
    Static testMethod void testMethod1(){
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.Invoice_FSCM_Disputes).getRecordTypeId();
        Case cas = new case();
        cas.SuppliedEmail = 'abc@gmail.com';
        cas.Additional_Web_Form_Info__c = 'test';
        cas.Origin = 'web';
        cas.Priority = 'normal';
        cas.Type = 'Orders';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Status = 'Closed';
        cas.Description = 'Test';
        cas.Subject = 'Test';
        cas.Customer_PO_RO_WONumber__c= '121';
        cas.RecordTypeId= devRecordTypeId;
        cas.Sales_Order_Number__c ='123456';
        Test.starttest();
        insert cas;
        Invoices_for_fscmCase__c inv = new Invoices_for_fscmCase__c();
        inv.FSCM_ID__c = 'test123';
        inv.FSCM_Status__c = 'New';
        inv.Parent_Case__c = cas.Id;
        insert inv;
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Open';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = 'test123';
        iwWrap.Invoice_Number = 'test123';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        iwWrap.invoice_currency = 'U.S. Dollar';
        iwWrap.SFDCID = Cas.CaseNumber;
        iwWrapLst.add(iwWrap);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
              
    }
    Static testMethod void testMethod2(){
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.Invoice_FSCM_Disputes).getRecordTypeId();
        Case cas = new case();
        cas.SuppliedEmail = 'abc@gmail.com';
        cas.Additional_Web_Form_Info__c = 'test';
        cas.Origin = 'web';
        cas.Priority = 'normal';
        cas.Type = 'Orders';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Status = 'Open';
        cas.Description = 'Test';
        cas.Subject = 'Test';
        cas.Customer_PO_RO_WONumber__c= '121';
        cas.RecordTypeId= devRecordTypeId;
        cas.Sales_Order_Number__c ='123456';
        
        Test.starttest();
        insert cas;
        Invoices_for_fscmCase__c inv = new Invoices_for_fscmCase__c();
        inv.FSCM_ID__c = 'test123';
        inv.FSCM_Status__c = 'New';
        inv.Parent_Case__c = cas.Id;
        insert inv;
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Closed';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = 'test123';
        iwWrap.Invoice_Number = 'test123';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        iwWrap.invoice_currency = 'U.S. Dollar';
        //iwWrap.SFDCID = cas.Id;
        iwWrapLst.add(iwWrap);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
              
    }
    Static testMethod void testMethod3(){
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.Invoice_FSCM_Disputes).getRecordTypeId();
        Case cas = new case();
        cas.SuppliedEmail = 'abc@gmail.com';
        cas.Additional_Web_Form_Info__c = 'test';
        cas.Origin = 'web';
        cas.Priority = 'normal';
        cas.Type = 'Orders';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Status = 'Open';
        cas.Description = 'Test';
        cas.Subject = 'Test';
        cas.Customer_PO_RO_WONumber__c= '121';
        cas.RecordTypeId= devRecordTypeId;
        cas.Sales_Order_Number__c ='123456';
        
        Test.starttest();
        insert cas;
        Invoices_for_fscmCase__c inv = new Invoices_for_fscmCase__c();
        inv.FSCM_ID__c = 'test123';
        inv.FSCM_Status__c = 'New';
        inv.Parent_Case__c = cas.Id;
        insert inv;
        Invoices_for_fscmCase__c inv2 = new Invoices_for_fscmCase__c();
        inv2.FSCM_ID__c = 'Test234';
        inv2.FSCM_Status__c = 'New';
        inv2.Parent_Case__c = cas.Id;
        insert inv2;
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Closed';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = 'test123';
        iwWrap.Invoice_Number = 'test123';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        iwWrap.invoice_currency = 'U.S. Dollar';
        //iwWrap.SFDCID = cas.Id;
        iwWrapLst.add(iwWrap);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
              
    }
    Static testMethod void testMethod4(){
       
        
        Test.starttest();
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap2 = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'New';
        CsWrap.SoldTo = '00123';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = '1098674';
        iwWrap.Invoice_Number = '12345';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        //iwWrap.invoice_currency = 'U.S. Dollar';
        iwWrapLst.add(iwWrap);
        iwWrap2.FSCM_Id = '23457654';
        iwWrap2.Invoice_Number = '132325778';
        iwWrap2.Invoice_Amount= 123;
        iwWrap2.disputed_Amount = 123;
        //iwWrap2.invoice_currency = 'U.S. Dollar';
        iwWrapLst.add(iwWrap2);
        CsWrap.invwrap = iwWrapLst;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduserForAeroFscm@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduserForAeroFscm@testorg.com',User_EID__c='H123456',IsActive = true);
        insert u;
        contact con = new Contact(LastName='test',Employee_Number__c ='H123456');
        insert con;
        account acc= new account(name= 'test',Sbl_Account_Row_Id__c = CsWrap.CRM_ID,Business_Focal__c=con.Id);
        insert acc;
        AEROSAPtoSF.CreateCase(CsWrap);
        Test.stoptest();
              
    }
    Static testMethod void testMethod5(){
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.Invoice_FSCM_Disputes).getRecordTypeId();
        Case cas = new case();
        cas.SuppliedEmail = 'abc@gmail.com';
        cas.Additional_Web_Form_Info__c = 'test';
        cas.Origin = 'web';
        cas.Priority = 'normal';
        cas.Type = 'Orders';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Status = 'Closed';
        cas.Description = 'Test';
        cas.Subject = 'Test';
        cas.Customer_PO_RO_WONumber__c= '121';
        cas.RecordTypeId= devRecordTypeId;
        cas.Sales_Order_Number__c ='123456';
        
        Test.starttest();
        insert cas;
        Invoices_for_fscmCase__c inv = new Invoices_for_fscmCase__c();
        inv.FSCM_ID__c = 'Test123';
        inv.FSCM_Status__c = 'New';
        inv.Parent_Case__c = cas.Id;
        insert inv;
        Invoices_for_fscmCase__c inv2 = new Invoices_for_fscmCase__c();
        inv2.FSCM_ID__c = 'test234';
        inv2.FSCM_Status__c = 'New';
        inv2.Parent_Case__c = cas.Id;
        insert inv2;
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Closed';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = 'test123';
        iwWrap.Invoice_Number = 'test123';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        iwWrap.invoice_currency = 'U.S. Dollar';
        iwWrap.SFDCID = cas.CaseNumber;
        iwWrapLst.add(iwWrap);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
              
    }
    
    Static testMethod void testMethod6(){
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.Invoice_FSCM_Disputes).getRecordTypeId();
        Case cas = new case();
        cas.SuppliedEmail = 'abc@gmail.com';
        cas.Additional_Web_Form_Info__c = 'test';
        cas.Origin = 'web';
        cas.Priority = 'normal';
        cas.Type = 'Orders';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Status = 'Open';
        cas.Description = 'Test';
        cas.Subject = 'Test';
        cas.Customer_PO_RO_WONumber__c= '121';
        cas.RecordTypeId= devRecordTypeId;
        cas.Sales_Order_Number__c ='123456';
        
        Test.starttest();
        insert cas;
        Invoices_for_fscmCase__c inv = new Invoices_for_fscmCase__c();
        inv.FSCM_ID__c = 'Test123';
        inv.FSCM_Status__c = 'New';
        inv.Parent_Case__c = cas.Id;
        insert inv;
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Open';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = 'Test123';
        iwWrap.Invoice_Number = 'test123';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        iwWrap.invoice_currency = 'U.S. Dollar';
        iwWrap.SFDCID =  cas.CaseNumber;
        iwWrapLst.add(iwWrap);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
              
    }
    Static testMethod void testMethod7(){
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.Invoice_FSCM_Disputes).getRecordTypeId();
        Case cas = new case();
        cas.SuppliedEmail = 'abc@gmail.com';
        cas.Additional_Web_Form_Info__c = 'test';
        cas.Origin = 'web';
        cas.Priority = 'normal';
        cas.Type = 'Orders';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Status = 'Open';
        cas.Description = 'Test';
        cas.Subject = 'Test';
        cas.Customer_PO_RO_WONumber__c= '121';
        cas.RecordTypeId= devRecordTypeId;
        cas.Sales_Order_Number__c ='123456';
        
        Test.starttest();
        insert cas;
        Invoices_for_fscmCase__c inv = new Invoices_for_fscmCase__c();
        inv.FSCM_ID__c = 'test123';
        inv.FSCM_Status__c = 'New';
        inv.Parent_Case__c = cas.Id;
        insert inv;
        Invoices_for_fscmCase__c inv2 = new Invoices_for_fscmCase__c();
        inv2.FSCM_ID__c = 'Test234';
        inv2.FSCM_Status__c = 'Closed';
        inv2.Parent_Case__c = cas.Id;
        insert inv2;
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Closed';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = 'test123';
        iwWrap.Invoice_Number = 'test123';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        iwWrap.invoice_currency = 'U.S. Dollar';
        //iwWrap.SFDCID = cas.Id;
        iwWrapLst.add(iwWrap);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
    }         
    Static testMethod void testMethod8(){
        Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.label.Invoice_FSCM_Disputes).getRecordTypeId();
    Test.starttest();
       AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
            Case cas = new case();
        cas.SuppliedEmail = 'abc@gmail.com';
        cas.Additional_Web_Form_Info__c = 'test';
        cas.Origin = 'web';
        cas.Priority = 'normal';
        cas.Type = 'Orders';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Status = 'Open';
        cas.Description = 'Test';
        cas.Subject = 'Test';
        cas.Customer_PO_RO_WONumber__c= '121';
        cas.RecordTypeId= devRecordTypeId;
        cas.Sales_Order_Number__c ='123456';
        cas.Notes__c = 'Test';
        insert cas;
        iwWrap.SFDCID =  cas.CaseNumber;
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Open';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = 'test123';
        iwWrap.Invoice_Number = 'test123';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        iwWrap.invoice_currency = 'U.S. Dollar';
        
        iwWrapLst.add(iwWrap);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
    } 
    Static testMethod void testMethod9(){
    Test.starttest();
       AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'Open';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap); 
        Test.stoptest();
    }    
     Static testMethod void testMethod10(){
       
        
        Test.starttest();
        AEROSAPtoSF.CaseWrapper CsWrap = new AEROSAPtoSF.CaseWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap = new AEROSAPtoSF.InvoiceWrapper();
        AEROSAPtoSF.InvoiceWrapper iwWrap2 = new AEROSAPtoSF.InvoiceWrapper();
        list<AEROSAPtoSF.InvoiceWrapper> iwWrapLst = new list<AEROSAPtoSF.InvoiceWrapper>();
        CsWrap.CRM_ID = 'Test123';
        CsWrap.Status = 'New';
        CsWrap.Subject = 'Test';
        CsWrap.Notes = 'Test';
        CsWrap.Dollar_Amounts= 1234;
        CsWrap.ReOpenCheck= True;
        iwWrap.FSCM_Id = '1098674';
        iwWrap.Invoice_Number = '12345';
        iwWrap.Invoice_Amount= 123;
        iwWrap.disputed_Amount = 123;
        //iwWrap.invoice_currency = 'U.S. Dollar';
        iwWrapLst.add(iwWrap);
        iwWrap2.FSCM_Id = '23457654';
        iwWrap2.Invoice_Number = '132325778';
        iwWrap2.Invoice_Amount= 123;
        iwWrap2.disputed_Amount = 123;
        //iwWrap2.invoice_currency = 'U.S. Dollar';
        iwWrapLst.add(iwWrap2);
        CsWrap.invwrap = iwWrapLst;
        AEROSAPtoSF.CreateCase(CsWrap);
        Test.stoptest();
              
    }
   
}