src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>The customer approved by CMD</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

src/objects/Account/fields/Strategic_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Business_Unit__c</fullName>
    <inlineHelpText>Honeywell&apos;s designations for its high-level business types: Air Transport &amp; Regional, Business &amp; General Aviation, Defense &amp; Space.</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Level</fullName>
                <color>#0B6FCE</color>
                <label>Aero Level</label>
            </value>
            <value>
                <fullName>ATR</fullName>
                <color>#78C953</color>
                <label>ATR</label>
            </value>
            <value>
                <fullName>BGA</fullName>
                <color>#E27001</color>
                <label>BGA</label>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
                <color>#A845DC</color>
                <label>D&amp;S</label>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/App_Email__c.field-meta.xml
<CustomField>
    <fullName>App_Email__c</fullName>
    <description>Preferred “Confirmation/Reply To” email address for this case record</description>
    <inlineHelpText>Preferred “Confirmation/Reply To” email address for this case record</inlineHelpText>
    <label>App Email</label>
    <type>Email</type>
</CustomField>

src/objects/Case/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <formula>HYPERLINK(&quot;mailto:&quot;&amp; Contact.Primary_Email_Address__c, Contact.Primary_Email_Address__c, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Email Address</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Account_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Contact Name</label>
    <referenceTo>Account_Contact__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact/fields/Contact_Function__c.field-meta.xml
<CustomField>
    <fullName>Contact_Function__c</fullName>
    <inlineHelpText>Primary responsibilities within job title. Select all that apply.</inlineHelpText>
    <label>Contact Function</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accident Investigator</fullName>
            </value>
            <value>
                <fullName>Accountable Manager</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounts Manager</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Aircraft Asset Management - Lessor</fullName>
            </value>
            <value>
                <fullName>Aircraft Certification</fullName>
            </value>
            <value>
                <fullName>Air Crew</fullName>
            </value>
            <value>
                <fullName>Air Traffic Controller</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>Auditor</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Dispatcher</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Flight Operations</fullName>
            </value>
            <value>
                <fullName>Flight Ops Decision Maker</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>Infosys</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Contact/fields/User_Primary_Manager_EID__c.field-meta.xml
<CustomField>
    <fullName>User_Primary_Manager_EID__c</fullName>
    <label>User Primary Manager EID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Contact/fields/User_Primary_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Primary_Manager_Name__c</fullName>
    <label>User Primary Manager Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>Stores feedback data from various surveys</description>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FEE-{0}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If you change the Account Name you must select a Contact that it is associated with the newly selected Account. If you do not, the original Account will be visible upon Save.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>notContain</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Feedback</relationshipLabel>
    <relationshipName>Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Feedback__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName +&apos; &apos;+ Contact__r.LastName</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

src/objects/Feedback__c/fields/Date_of_Interview__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Interview__c</fullName>
    <label>Date of Interview</label>
    <type>Date</type>
</CustomField>

src/objects/Feedback__c/fields/Field_for_Weighting__c.field-meta.xml
<CustomField>
    <fullName>Field_for_Weighting__c</fullName>
    <label>Field for Weighting</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Feedback__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Feedback__c/fields/Survey_Origin__c.field-meta.xml
<CustomField>
    <fullName>Survey_Origin__c</fullName>
    <description>Added for Customer Rating Dashboard</description>
    <label>Survey Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AIN</fullName>
            </value>
            <value>
                <fullName>Airbus Commercial</fullName>
            </value>
            <value>
                <fullName>Airbus D&amp;S</fullName>
            </value>
            <value>
                <fullName>Airbus Helicopters</fullName>
            </value>
            <value>
                <fullName>Bell Helicopter</fullName>
            </value>
            <value>
                <fullName>Boeing Commercial</fullName>
            </value>
            <value>
                <fullName>Boeing DS</fullName>
            </value>
            <value>
                <fullName>Bombardier</fullName>
            </value>
            <value>
                <fullName>CPAR</fullName>
            </value>
            <value>
                <fullName>Customer Specific - ATR</fullName>
            </value>
            <value>
                <fullName>Customer Specific - D&amp;S</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>Embraer</fullName>
            </value>
            <value>
                <fullName>GCC</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>General Atomics</fullName>
            </value>
            <value>
                <fullName>Gulfstream</fullName>
            </value>
            <value>
                <fullName>Lockheed Martin Aero</fullName>
            </value>
            <value>
                <fullName>Lockheed Missiles</fullName>
            </value>
            <value>
                <fullName>Northrop Grumman</fullName>
            </value>
            <value>
                <fullName>Pilatus</fullName>
            </value>
            <value>
                <fullName>ProPilot</fullName>
            </value>
            <value>
                <fullName>Raytheon</fullName>
            </value>
            <value>
                <fullName>Sikorsky</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Feedback__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1995</fullName>
            </value>
            <value>
                <fullName>1996</fullName>
            </value>
            <value>
                <fullName>1997</fullName>
            </value>
            <value>
                <fullName>1998</fullName>
            </value>
            <value>
                <fullName>1999</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>SR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter customer contact name.  If D&amp;S restricted, use Honeywell contact name.</inlineHelpText>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/Primary_Manager_EID__c.field-meta.xml
<CustomField>
    <fullName>Primary_Manager_EID__c</fullName>
    <label>Primary Manager EID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/User/fields/Primary_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Manager_Name__c</fullName>
    <label>Primary Manager Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/classes/DashboardHome_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class DashboardHome_Test{

    static testMethod void myUnitTest() 
    {
     DashboardHome dh= new DashboardHome();
     //RemFeedback rm= new RemFeedback('filter');
     dh.getcountgreen1() ;
     dh.getcountred();
     dh.getcountyellow();
     dh.getOverallAOGStatus();
     dh.getPlatformsAtRisk();
     dh.getmpStatus();
     dh.getscrollcomment();
     String s='ALL';
     DashboardHome.RemFeedback(s);
 
    }
    
     static testmethod void bgadrill(){
        //User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='ATR');
       Test.startTest();   
       insert acc;
       Test.stopTest();   
        //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
          
        insert con;
       
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
           
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Red';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
       
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
         
        insert Sr;
            
        DashboardHome dh= new DashboardHome();
        String s='APU';
       DashboardHome.RemFeedback(s);
 
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
       // dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getTotalSR();
        dh.getPastDueSR();
        dh.getTotalSRATR();
        dh.getPastDueSRATR();
        dh.getTotalSRBGA();
        dh.getPastDueSRBGA();
        dh.getTotalSRDS();
        dh.getPastDueSRDS();
        dh.getscrollcommentATR();
    //}
    }
     static testmethod void bgadrill1(){
        //User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='BGA');
       Test.startTest();   
       insert acc;
       Test.stopTest();
       //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
      
        insert con;
        
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
        
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Red';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
        
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
         
        insert Sr;
             
        DashboardHome dh= new DashboardHome();
        
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
        //dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getscrollcommentBGA();
    //}
    }
   
    static testmethod void bgadrill2(){
       // User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='D&S');
       Test.startTest();   
       insert acc;
       Test.stopTest();
       //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
       
        insert con;
        
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
          
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Red';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
        
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
          
        insert Sr;
    
           DashboardHome dh= new DashboardHome(); 
           
        dh.getscroll();
        dh.getscrollcomment();
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
        //dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getscrollcommentDS();
    //}
    }
     static testmethod void bgadrill3(){
        //User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='ATR');
       Test.startTest();   
       insert acc;
       Test.stopTest();   
        //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
          
        insert con;
       
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
           
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Yellow';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
       
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
         
        insert Sr;
            
        DashboardHome dh= new DashboardHome();
        String s='APU';
       DashboardHome.RemFeedback(s);
 
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
       // dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getTotalSR();
        dh.getPastDueSR();
        dh.getTotalSRATR();
        dh.getPastDueSRATR();
        dh.getTotalSRBGA();
        dh.getPastDueSRBGA();
        dh.getTotalSRDS();
        dh.getPastDueSRDS();
        dh.getscrollcommentATR();
    //}
    }
     static testmethod void bgadrill4(){
        //User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='BGA');
       Test.startTest();   
       insert acc;
       Test.stopTest();
       //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
      
        insert con;
        
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
        
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Yellow';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
        
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
         
        insert Sr;
             
        DashboardHome dh= new DashboardHome();
        
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
        //dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getscrollcommentBGA();
    //}
    }
   
    static testmethod void bgadrill5(){
       // User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='D&S');
       Test.startTest();   
       insert acc;
       Test.stopTest();
       //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
       
        insert con;
        
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
          
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Yellow';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
        
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
          
        insert Sr;
    
           DashboardHome dh= new DashboardHome(); 
           
        dh.getscroll();
        dh.getscrollcomment();
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
        //dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getscrollcommentDS();
    //}
    }
    static testmethod void bgadrill6(){
        //User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='ATR');
       Test.startTest();   
       insert acc;
       Test.stopTest();   
        //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
          
        insert con;
       
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
           
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Green';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
       
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
         
        insert Sr;
            
        DashboardHome dh= new DashboardHome();
        String s='APU';
       DashboardHome.RemFeedback(s);
 
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
       // dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getTotalSR();
        dh.getPastDueSR();
        dh.getTotalSRATR();
        dh.getPastDueSRATR();
        dh.getTotalSRBGA();
        dh.getPastDueSRBGA();
        dh.getTotalSRDS();
        dh.getPastDueSRDS();
        dh.getscrollcommentATR();
    //}
    }
     static testmethod void bgadrill7(){
        //User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='BGA');
       Test.startTest();   
       insert acc;
       Test.stopTest();
       //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
      
        insert con;
        
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
        
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Green';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
        
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
         
        insert Sr;
             
        DashboardHome dh= new DashboardHome();
        
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
        //dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getscrollcommentBGA();
    //}
    }
   
    static testmethod void bgadrill8(){
       // User usr =[select id,Primary_Manager_Name__c,Primary_Manager_EID__c from user where profile.name != 'System Administrator' and isactive = true order by createddate asc limit 1];
       Account acc= new Account(name='Test Account',Strategic_Business_Unit__c='D&S');
       Test.startTest();   
       insert acc;
       Test.stopTest();
       //System.runAs(usr){
        Contact con = new Contact();
        con.LastName = 'testupdate';
        con.FirstName = 'sbucon';
        con.AccountId = acc.Id;
         con.Contact_Function__c='Infosys';
         con.Primary_Email_Address__c = 'sofiya.peermohamed@nttdata.com';
        con.Employee_Number__c = 'E123123';
        //con.Account_Contact_Name__c=acc.name;
        con.Email='harikishore.vutukuri@honeywell.com';
        //con.User_Primary_Manager_Name__c = usr.Primary_Manager_Name__c;   
       // con.User_Primary_Manager_EID__c = usr.Primary_Manager_EID__c;
       
        insert con;
        
         Case c1=new Case(App_Email__c='test1@g.com',SuppliedEmail='test@g.com',Origin='BGAMobileApp');
          
         insert c1; 
         
       Schema.DescribeSObjectResult FeedObj = Schema.SObjectType.Feedback__c;
     Map<String,Schema.RecordTypeInfo> feedrtMapByName = FeedObj.getRecordTypeInfosByName();
     Schema.RecordTypeInfo feedrtByName =  feedrtMapByName.get('Customer Rating');
     ID feedRecTypeid =  feedrtByName.getRecordTypeId();
        Feedback__c feed=new Feedback__c();
       
        feed.Year__c='2014';
        feed.Quarter__c='Q4';
        feed.Date_of_Interview__c=date.today();
        feed.Survey_Origin__c='Bombardier';
        feed.Account__c=acc.id;
        feed.Field_for_Weighting__c=5;
        feed.Overall_Rating__c=3;
        feed.Overall_Rating_Score__c=8;
        feed.Overall_Rating_Color__c='Green';
        feed.Aggregate_Scoring__c=True;
        feed.Include_on_Customer_Rating_Dashboard__c=True;
        feed.Additional_Comments__c='test comment';
        feed.recordtypeid=feedRecTypeid;
        //feed.recordtypeid=FeedRecordTypeInfo .get('A').getRecordTypeId();
         
        insert feed;
        
         Service_Request__c  Sr =new Service_Request__c();
        Sr.Subject__c='DS Test SR';
        Sr.SR_Type__c='Significant Customer Dissatisfier';
        Sr.Priority__c='High';
        Sr.Status__c='Open';
        Sr.Problem_Description__c='Technical Problem';
        Sr.Account_Name__c=acc.id;
        Sr.Customer_Due_Date__c=date.today();
        Sr.Top_Technical_Issue__c=true;
        Sr.VOC_Card_Numb__c=feed.id;
        Sr.Contact_Name__c = con.id;
        Sr.Case_Number__c = c1.Id;
        Sr.Show_on_Dashboard__c=true;
          
        insert Sr;
    
           DashboardHome dh= new DashboardHome(); 
           
        dh.getscroll();
        dh.getscrollcomment();
        dh.getSBUValues();
        dh.getATRValues();
        dh.getBGAValues();
        dh.getDSValues();
        dh.getVOCfeedrecords();
        dh.getVOCfeedrecordsATR();
        dh.getSRDaysValues();
        dh.getSRValues();
        dh.getGreencountATR();
        dh.getYellowcountATR();
        dh.getRedcountATR();
        dh.getGreencountBGA();
        dh.getYellowcountBGA();
        dh.getRedcountBGA();
        dh.getGreencountDS();
        dh.getYellowcountDS();
        dh.getRedcountDS();
        dh.getGreencountColorATR();
        dh.getYellowcountColorATR();
        dh.getRedcountColorATR();
        dh.getGreencountColorBGA();
        dh.getYellowcountColorBGA();
        dh.getRedcountColorBGA();
        dh.getGreencountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountColorDS();
        dh.getRecorddetails();
        dh.getRedcountColorDS();
        dh.getYellowcountColorDS();
        dh.getRedcountATR();
        dh.Feedredirect();
        //dh.TopSRDSRedirect();
        dh.ATRVOC();
        dh.closePopup();
        dh.showPopup();
        dh.getTotalpercentageColor();
        dh.getTotalpercentageColorATR();
        dh.getTotalpercentageColorBGA();
        dh.getTotalpercentageColorDS();
        dh.getTotalpercentage();
        dh.getTotalpercentageATR();
        dh.getTotalpercentageBGA();
        dh.getTotalpercentageDS();
        dh.getscrollcommentDS();
    //}
    }
}