src/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>Customer Status</description>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <formula>TEXT(Account.Customer_Status__c)</formula>
    <label>Customer Status</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/OwnerName__c.field-meta.xml
<CustomField>
    <fullName>OwnerName__c</fullName>
    <formula>if(left( OwnerId ,3)==&apos;005&apos;,OwnerId__r.FirstName +&apos; &apos;+ OwnerId__r.LastName,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OwnerNameFormula</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <formula>HYPERLINK(&quot;mailto:&quot;&amp; Contact.Primary_Email_Address__c, Contact.Primary_Email_Address__c, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Email Address</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Marketing Engaged</fullName>
            </value>
            <value>
                <fullName>With Telemarketing</fullName>
            </value>
            <value>
                <fullName>Assigned - Target Team</fullName>
            </value>
            <value>
                <fullName>Working - Target Team</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>With Customer Marketing</fullName>
            </value>
            <value>
                <fullName>Working - Contacted</fullName>
            </value>
            <value>
                <fullName>Closed - Existing Opportunity</fullName>
            </value>
            <value>
                <fullName>Closed - No Project Now</fullName>
            </value>
            <value>
                <fullName>Closed - Converted (Qualified)</fullName>
            </value>
            <value>
                <fullName>Redirected - Channel Sales</fullName>
            </value>
            <value>
                <fullName>Closed - Competitor</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid Contact</fullName>
            </value>
            <value>
                <fullName>Redirected - LGS</fullName>
            </value>
            <value>
                <fullName>Sent to Partner</fullName>
            </value>
            <value>
                <fullName>Redirected - Partner Sales Manager</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Assigned - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Working - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Contacted - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Handoff</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Converted to Opportunity</fullName>
            </value>
            <value>
                <fullName>Converted To Contact</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>SR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select customer that initiated the issue</inlineHelpText>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account Name should not contain Various or be an Inactive or Temporary account.</errorMessage>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>notContain</operation>
            <value>VARIOUS</value>
        </filterItems>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive, Temporary</value>
        </filterItems>
        <infoMessage>Account Name should not contain &quot;Various&quot; or be in an Inactive or Temporary account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Service_Request__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter originating Case Number</inlineHelpText>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Service_Request__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter customer contact name.  If D&amp;S restricted, use Honeywell contact name.</inlineHelpText>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Service_Request__c/fields/OwnerName__c.field-meta.xml
<CustomField>
    <fullName>OwnerName__c</fullName>
    <formula>if(left( OwnerId ,3)==&apos;005&apos;,OwnerId__r.FirstName +&apos; &apos;+ OwnerId__r.LastName,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OwnerName</label>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>&quot;Open&quot;: Investigation is active or fix is in work.
&quot;Closed&quot;: Issue has been resolved or completed.
&quot;Monitor&quot;: Issue is waiting for additional information from customer or there is a request for issue to be monitored.
&quot;Queue&quot;: SR awaiting to be assigned</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Containment</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>RCCA</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Very brief, high level explanation of SR. Platform, Model or PN, Issue.The subject line of an email or the title of the case ticket.</description>
    <inlineHelpText>Brief description of SR (90 Char Max) (4-Up,DB)</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/SSCommunityCases_Test4.cls
@isTest(seeAllData=true)
    public class SSCommunityCases_Test4
     {
          /* static testMethod void testSSCommunityCases1()
             {
                  test.startTest();
                
                 List<Case> AllCasesList =[Select Id,CaseNumber,(select Subject__c, OwnerName__c , Name, Status__c from Service_Requests__r) from Case where Id='5003000000BjYZEAA3'];
                 SSCommunityCases_Cntrl.SRSearch(AllCasesList[0].Id);
                 system.assertEquals(AllCasesList[0].CaseNumber,'CASE-4687945');
                 test.stopTest();
             }
             
             
            static testMethod void testSSCommunityCases2()
             {
                  test.startTest();
                  
                  //Querying data usind id
                   
                  Service_Request__c srdata=[select id,OwnerName__c from Service_Request__c Limit 1];
                  Service_Request__c sr=SSCommunityCases_Cntrl.SRDetails(srdata.id);
                  system.assertEquals(sr.OwnerName__c,srdata.OwnerName__c);
                  test.stopTest();
             }
             
             
             static testMethod void testSSCommunityCases3()
             {
              
                  test.startTest();
                  
                  //Querying data usind id
                  
                  Case csdata=[select id,OwnerName__c from Case Limit 1];
                  Case cs=SSCommunityCases_Cntrl.CaseDetails(csdata.id);
                  system.assertEquals(cs.OwnerName__c,csdata.OwnerName__C);
                  test.stopTest();
             }
             
              static testMethod void testSSCommunityCases4()
             {
              
                  test.startTest();
                  
                  //Querying data usind id
                         
            Account acc = new Account();
            acc.Name = 'Test Account12';
            acc.Customer_Status__c = 'Active';
            insert acc;
            
             Contact con = new Contact();
            con.LastName = 'testLastName';
            con.FirstName = 'testFirstName';
            con.AccountId = acc.Id;
            con.Primary_Email_Address__c = 'test@tcs.com';
            con.Email='test1@tcs.com';
            insert con;

            Service_Request__c sr=new Service_Request__c();
          
            sr.Status__c='Open';
            insert sr;
            
             SSCommunityCases_Cntrl.CustomerCasesSearch('Open',acc.id);
             SSCommunityCases_Cntrl.CustomerCasesSearch('lastUpdated',acc.id);
             SSCommunityCases_Cntrl.CustomerCasesSearch('dateCreated',acc.id);
             SSCommunityCases_Cntrl.CustomerCasesSearch('aircrafttype',acc.id);
             SSCommunityCases_Cntrl.CustomerCasesSearch('atachap',acc.id);
             SSCommunityCases_Cntrl.CustomerCasesSearch('prodtype',acc.id);
             //SSCommunityCases_Cntrl.CustomerCasesSearch('partno',acc.id);
             SSCommunityCases_Cntrl.CustomerCasesSearch('subject',acc.id);
             SSCommunityCases_Cntrl.CustomerCasesSearch('status',acc.id);
                         
             system.assertEquals('Open',sr.Status__c);
             test.stopTest();
             }
             
             
             
              static testMethod void testSSCommunityCases6()
             {
              
                  test.startTest();
                  
                  //Querying data usind id
                         
            Account acc = new Account();
            acc.Name = 'Test Account12';
            acc.Customer_Status__c = 'Active';
            insert acc;
            SSCommunityCases_Cntrl.SearchAccount('Test');
             system.assertEquals('Test Account12',acc.Name);
             test.stopTest();
             }
             
             static testMethod void testSSCommunityCases7()
             {
                  test.startTest();
                  
                  //Querying data usind id
                  
                  Service_Request__c srdata=[select id,OwnerName__c from Service_Request__c Limit 1];
                  Service_Request__c sr=SSCommunityCases_Cntrl.SRDetails(srdata.id); 
                  SSCommunityCases_Cntrl.getUserIsEmloyee();
                  system.assertEquals(sr.OwnerName__c,srdata.OwnerName__c);
                  test.stopTest();
             }*/
             
      }