src/objects/Campaign.object
<CustomObject>
</CustomObject>

src/objects/Campaign/fields/CampaignPrimarySBU__c.field-meta.xml
<CustomField>
    <fullName>CampaignPrimarySBU__c</fullName>
    <inlineHelpText>Campaign primary SBU. The SBU that has primary business responsibility for this campaign.</inlineHelpText>
    <label>Primary SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Campaign/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Platform</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Campaign_Target__c/Campaign_Target__c.object-meta.xml
<CustomObject>
    <label>Campaign Target</label>
    <nameField>
        <displayFormat>CAT-{00000000}</displayFormat>
        <label>Campaign Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Target__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Targets</relationshipLabel>
    <relationshipName>Campaign_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Campaign_Target__c/fields/Target_Contact__c.field-meta.xml
<CustomField>
    <fullName>Target_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Targets</relationshipLabel>
    <relationshipName>Campaign_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <inlineHelpText>The Contact&apos;s Primary Email Address.</inlineHelpText>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Account (Customer) Name associated with this Fleet entry.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND ( NOT 2)</booleanFilter>
        <errorMessage>Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Account)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <formula>Platform_Name__r.Make__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aircraft Make</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Platform_Name__r.Model__c</formula>
    <label>Aircraft Model</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>added on demand by Dieter for data migration</description>
    <label>Make</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Defines the Model.</inlineHelpText>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/CampaignTarget_Insert_Test.cls
/** * File Name: CampaignTarget_Insert_Test
* Description Test Method
* Class Tested: CampaignTarget_Insert
* * @author : NTTDATA
* Modification Log 
=============================================================== /**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CampaignTarget_Insert_Test {

    static testMethod void myUnitTest()
    {
      test.starttest(); 
         Account acc = new Account(
            Name = 'Test Account'            
        );
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'Singh';
        con.FirstName = 'Kapil';
        con.AccountId = acc.Id;
        con.Primary_Email_Address__c = 'kapil.nowhere@gmail.com';
        con.Email='kapil.nowhere@gmail.com';
        insert con;
        
        list<Platform__c> plist= new list<Platform__c>();
         Platform__c p = new Platform__c();
         p.Name = 'Test Paltform';
         p.Model__c = '36-16A';
         p.Make__c = 'VARIOUS OEMS';
         plist.add(p);
         
         Platform__c p1 = new Platform__c();
         p1.Name = 'Test Paltform';
         p1.Model__c = '36-16A';
         p1.Make__c = 'VARIOUS OEMS';
         plist.add(p1);
         insert plist;
         
        list<Fleet_Asset_Detail__c> fleetlist= new list<Fleet_Asset_Detail__c>();
        Fleet_Asset_Detail__c make=new Fleet_Asset_Detail__c(
        Platform_Name__c = p.id,
        Account__c=acc.id
        );
        fleetlist.add(make);
        
        Fleet_Asset_Detail__c make1=new Fleet_Asset_Detail__c(
        Platform_Name__c = p.id,
        Account__c=acc.id
        );
        fleetlist.add(make1);
        insert fleetlist;
         
         Campaign cam = new Campaign();
         cam.Name='Test Campaign';
         cam.CampaignPrimarySBU__c='D&S';
         cam.Type='Email';
         cam.Platform__c=p.id;
         insert cam;
         
         Campaign_Target__c ct= new  Campaign_Target__c();
         ct.Campaign__c=cam.id;
         ct.Target_Contact__c=con.id;
         insert ct;
         
         cam.Platform__c=p1.Id;
         update cam;
         
     test.stopTest();
    }
}