src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/CaseOwnerChanged__c.field-meta.xml
<CustomField>
    <fullName>CaseOwnerChanged__c</fullName>
    <label>CSWI Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
            <value>
                <fullName>CSO Repair Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Order_Entered_By__c.field-meta.xml
<CustomField>
    <fullName>Order_Entered_By__c</fullName>
    <label>Order Entered By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Repair_Notification_Number__c.field-meta.xml
<CustomField>
    <fullName>Repair_Notification_Number__c</fullName>
    <externalId>true</externalId>
    <label>Repair Notification Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/Z_Task__c.object-meta.xml
<CustomObject>
    <label>Task Activities</label>
    <nameField>
        <label>Z Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Z_Task__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Long Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Z_Task__c/fields/Followuptask__c.field-meta.xml
<CustomField>
    <fullName>Followuptask__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followuptask</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Z_Task__c/fields/Language_Key__c.field-meta.xml
<CustomField>
    <fullName>Language_Key__c</fullName>
    <label>Language Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/Long_Text__c.field-meta.xml
<CustomField>
    <fullName>Long_Text__c</fullName>
    <label>Long Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Z_Task__c/fields/New_Long_Text__c.field-meta.xml
<CustomField>
    <fullName>New_Long_Text__c</fullName>
    <label>New Long Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Z_Task__c/fields/Other_Short_Text__c.field-meta.xml
<CustomField>
    <fullName>Other_Short_Text__c</fullName>
    <label>Other Short Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/RelatedTo__c.field-meta.xml
<CustomField>
    <fullName>RelatedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related To</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Task Activities</relationshipLabel>
    <relationshipName>Z_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Z_Task__c/fields/SAP_ZTask_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_ZTask_Number__c</fullName>
    <label>SAP ZTask Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/Short_Text2__c.field-meta.xml
<CustomField>
    <fullName>Short_Text2__c</fullName>
    <formula>IF( TEXT( Sub_Type__c ) == &apos;Other&apos; , Other_Short_Text__c , Short_Text__c )</formula>
    <label>Short Text (Final)</label>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/Short_Text__c.field-meta.xml
<CustomField>
    <fullName>Short_Text__c</fullName>
    <label>Short Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Z_Task__c/fields/Sub_Class__c.field-meta.xml
<CustomField>
    <fullName>Sub_Class__c</fullName>
    <formula>TEXT(RelatedTo__r.Sub_Class__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Class</label>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>Short Text Template</description>
    <label>Short Text Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>RAI - UFR No response</fullName>
            </value>
            <value>
                <fullName>RAI - Quote Denied</fullName>
            </value>
            <value>
                <fullName>RAI - Quote No response</fullName>
            </value>
            <value>
                <fullName>RAI - Customer Requested</fullName>
            </value>
            <value>
                <fullName>Resolve Unknown Customer</fullName>
            </value>
            <value>
                <fullName>Exchange Available</fullName>
            </value>
            <value>
                <fullName>PO review Pending</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – No Discrepancies Identified</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope Quote Reqd</fullName>
            </value>
            <value>
                <fullName>PO review complete</fullName>
            </value>
            <value>
                <fullName>Need Missing PO</fullName>
            </value>
            <value>
                <fullName>Need Missing Information</fullName>
            </value>
            <value>
                <fullName>Customer Dispute Price - Please review</fullName>
            </value>
            <value>
                <fullName>Please send Quote to Customer</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Sufficiently Priced</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope and Price Wrong</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope Incorrect</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope Wrong Price OK</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – Workscope Price required</fullName>
            </value>
            <value>
                <fullName>Missing Price - Please Price</fullName>
            </value>
            <value>
                <fullName>Scrap - Customer requested</fullName>
            </value>
            <value>
                <fullName>Exchange price needed</fullName>
            </value>
            <value>
                <fullName>Customer Approved Exchange</fullName>
            </value>
            <value>
                <fullName>Customer Rejected Exchange</fullName>
            </value>
            <value>
                <fullName>Create Sales Order</fullName>
            </value>
            <value>
                <fullName>Need Missing Paperwork</fullName>
            </value>
            <value>
                <fullName>UFR - No quote Required</fullName>
            </value>
            <value>
                <fullName>FYI Quote Approved</fullName>
            </value>
            <value>
                <fullName>Contract Flate Rate- No Quote Required</fullName>
            </value>
            <value>
                <fullName>Quote Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Z_Task__c/fields/Z_Task__c.field-meta.xml
<CustomField>
    <fullName>Z_Task__c</fullName>
    <formula>SAP_ZTask_Number__c</formula>
    <label>Z Task</label>
    <type>Text</type>
</CustomField>

src/classes/SI_ZtaskStatustoSAPTest.cls
/*******************************************************************************
Name         : SI_ZtaskStatustoSAP
Created By   : NTTDATA
Company Name : NTT Data
Project      : <SI_SAPtoSFDCServiceclass>
Created Date : 20-Sep-2016
Usages       : Test Class for CaseCreationPortaltoSFDC
*******************************************************************************/
@isTest(seealldata=true)
global class SI_ZtaskStatustoSAPTest{ 
    testMethod static void SI_ZtaskStatustoSAPTest()
    {
        Case cas = new Case();
        cas.Origin = 'web';
        cas.Status = 'Open';  
        cas.OwnerId = Label.UFR_Owner_Id;
        //cas.ContactId = objContact.Id;
        cas.RecordtypeId = label.Repair_Overhaul_RT_ID;
        cas.Classification__c = 'CSO Repair Order';
        //cas.Sub_Class__c = 'Quotes COE - Customer Response';
        cas.Repair_Notification_Number__c='12345';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Sales_Order_Number__c = '12345678';
        //cas.Order_Entered_By__c = 'Harikishore';
        cas.CaseOwnerChanged__c = 'sofiya.peermohamed@nttdata.com';
        cas.Description = 'Test cases';
        cas.subject='test case';
        insert cas;
                
        Z_Task__c zt11 = new Z_Task__c();
        zt11.SAP_ZTask_Number__c = 'Test123';
        zt11.Name = 'Tasktest1';
        zt11.RelatedTo__c = cas.id;
        zt11.Short_Text__c = 'Test & and <> and "';
        zt11.Comments__c = 'Test Ztask';
        zt11.Long_Text__c = 'Test122 & and <> and "';
        zt11.New_Long_Text__c='Test122 & and <> and "';
        zt11.Sub_Type__c = 'Test & and <> and "';
        zt11.Other_Short_Text__c = 'Test text';
        zt11.Status__c = 'Open';
        zt11.Followuptask__c=false;
        zt11.Language_Key__c='test';
        zt11.ownerid=label.CSO_R_O_Team;
        insert zt11;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        set<id> ztaskid=new set<id>();
        ztaskid.add(zt11.id);
        //SI_ZtaskStatustoSAP.SendTaskStatus(ztaskid);
        List<id> ztaskid1=new List<id>();
        ztaskid1.add(zt11.id);
        //SI_ZtaskStatustoSAP1.SendTaskStatus(ztaskid1);
    }
    testMethod static void SI_ZtaskStatustoSAPTest1()
    {
         Case cas = new Case();
        cas.Origin = 'web';
        cas.Status = 'Open';  
        cas.OwnerId = Label.UFR_Owner_Id;
        //cas.ContactId = objContact.Id;
        cas.RecordtypeId = label.Repair_Overhaul_RT_ID;
        cas.Classification__c = 'CSO Repair Order';
        //cas.Sub_Class__c = 'Quotes COE - Customer Response';
        cas.Repair_Notification_Number__c='12345';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Sales_Order_Number__c = '12345678';
        //cas.Order_Entered_By__c = 'Harikishore';
        cas.CaseOwnerChanged__c = 'sofiya.peermohamed@nttdata.com';
        cas.Description = 'Test cases';
        cas.subject='test case';
        insert cas;
        
        Z_Task__c zt12 = new Z_Task__c();
        zt12.SAP_ZTask_Number__c = 'Test123';
        zt12.Name = 'Tasktest1';
        zt12.RelatedTo__c = cas.id;
        zt12.Short_Text__c = '';
        //zt12.Short_Text2__c='';
        zt12.Comments__c = 'Test Ztask';
        zt12.Long_Text__c = 'Test122 & and <> and "';
        zt12.New_Long_Text__c='Test122 & and <> and "';
        zt12.Sub_Type__c = null;
        zt12.Other_Short_Text__c = 'Test';
        zt12.Status__c = 'Open';
        zt12.Followuptask__c=false;
        zt12.Language_Key__c='test';
        zt12.ownerid=label.CSO_R_O_Team;
        insert zt12;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        set<id> ztaskid2=new set<id>();
        ztaskid2.add(zt12.id);
        //SI_ZtaskStatustoSAP.SendTaskStatus(ztaskid2);
        List<id> ztaskid3=new List<id>();
        ztaskid3.add(zt12.id);
        
        //SI_ZtaskStatustoSAP1.SendTaskStatus(ztaskid3);
    }
     testMethod static void SI_ZtaskStatustoSAPTest2()
    {
         Case cas = new Case();
        cas.Origin = 'web';
        cas.Status = 'Open';  
        cas.OwnerId = Label.UFR_Owner_Id;
        //cas.ContactId = objContact.Id;
        cas.RecordtypeId = label.Repair_Overhaul_RT_ID;
        cas.Classification__c = 'CSO Repair Order';
        //cas.Sub_Class__c = 'Quotes COE - Customer Response';
        cas.Repair_Notification_Number__c='12345';
        cas.Export_Compliance_Content_ITAR_EAR__c = 'No';
        cas.Government_Compliance_SM_M_Content__c = 'No';
        cas.Sales_Order_Number__c = '12345678';
        //cas.Order_Entered_By__c = 'Harikishore';
        cas.CaseOwnerChanged__c = 'sofiya.peermohamed@nttdata.com';
        cas.Description = 'Test cases';
        cas.subject='test case';
        insert cas;
        
        Z_Task__c zt12 = new Z_Task__c();
        zt12.SAP_ZTask_Number__c = 'Test123';
        zt12.Name = 'Tasktest1';
        zt12.RelatedTo__c = cas.id;
        zt12.Short_Text__c = '';
        //zt12.Short_Text2__c='';
        zt12.Comments__c = 'Test Ztask';
        zt12.Long_Text__c = 'Test122 & and <> and "';
        zt12.New_Long_Text__c='Test122 & and <> and "';
        zt12.Sub_Type__c = 'Test';
        zt12.Other_Short_Text__c = 'Test';
        zt12.Status__c = 'Open';
        zt12.Followuptask__c=false;
        zt12.Language_Key__c='test';
        zt12.ownerid=label.CSO_R_O_Team;
        insert zt12;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        set<id> ztaskid2=new set<id>();
        ztaskid2.add(zt12.id);
        //SI_ZtaskStatustoSAP.SendTaskStatus(ztaskid2);
        List<id> ztaskid3=new List<id>();
        ztaskid3.add(zt12.id);
        
        //SI_ZtaskStatustoSAP1.SendTaskStatus(ztaskid3);
    }
}