src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant_Code_Master__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Account.Type )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <formula>ATR_Probability__c * Program_Go_Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>PWin * PGo</inlineHelpText>
    <label>Probability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/objects/Opportunity/fields/Revenue_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_End_Date__c</fullName>
    <label>Revenue End Date</label>
    <summarizedField>OpportunityLineItem.Revenue_End_Date__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Revenue_End_Date__c</field>
        <operation>notEqual</operation>
        <value/>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Opportunity/fields/Revenue_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Start_Date__c</fullName>
    <description>Revenue Start Date</description>
    <label>Revenue Start Date</label>
    <summarizedField>OpportunityLineItem.Revenue_Start_Date__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Revenue_Start_Date__c</field>
        <operation>notEqual</operation>
        <value/>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Opportunity/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <inlineHelpText>Revenue type of this opportunity</inlineHelpText>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ENG</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Repairs / Overhaul</fullName>
            </value>
            <value>
                <fullName>Retrofit</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Spares / AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/Amount_Net__c.field-meta.xml
<CustomField>
    <fullName>Amount_Net__c</fullName>
    <formula>TotalPrice  *  Probability__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Price * PGo * Pwin</inlineHelpText>
    <label>Total Price Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Closure_Actions__c.field-meta.xml
<CustomField>
    <fullName>Closure_Actions__c</fullName>
    <description>Closure Actions</description>
    <inlineHelpText>Actions to close within the next two weeks. Be specific and include the owners name</inlineHelpText>
    <label>Closure Actions</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Demand_Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>Demand_Decision_Date__c</fullName>
    <inlineHelpText>Demand needs to be loaded by this date</inlineHelpText>
    <label>Demand Decision Date</label>
    <type>Date</type>
</CustomField>

src/objects/OpportunityLineItem/fields/E_SIOP_Demand_Category__c.field-meta.xml
<CustomField>
    <fullName>E_SIOP_Demand_Category__c</fullName>
    <description>E/SIOP Demand Category</description>
    <inlineHelpText>Demand planning classification</inlineHelpText>
    <label>E/SIOP Demand Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Gap</fullName>
            </value>
            <value>
                <fullName>MTO</fullName>
            </value>
            <value>
                <fullName>Not Loaded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/Extended_Price__c.field-meta.xml
<CustomField>
    <fullName>Extended_Price__c</fullName>
    <formula>Quantity *  Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Extended Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/OpportunityLineItem/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id field reference used in data migration. This field value is concatenation of &quot;Legacy Opportunity Number&quot; and &quot;Legacy Opportunity Line ID&quot;.
Example &quot;OFS-9994-0_3&quot;</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Functional_Help_Required__c.field-meta.xml
<CustomField>
    <fullName>Functional_Help_Required__c</fullName>
    <description>Functional Help Required</description>
    <inlineHelpText>Other Honeywell functional help is required. Who and What?</inlineHelpText>
    <label>Functional Help Required</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Include_in_CYO_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Include_in_CYO_Tracking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CYO Overdrive</description>
    <inlineHelpText>Check indicates the revenue from this order was NOT included in baseline AOP: Current-Year Revenue from this order will contribute to the +5% Contingency tracking to reinforce/overdrive the revenue AOP. Is included in SIP “+5% CYO Contingency” Metric.</inlineHelpText>
    <label>CYO Overdrive</label>
    <type>Checkbox</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Include_Net_Rev_in_SRO_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Include_Net_Rev_in_SRO_Estimate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Include Net Rev in SRO Estimate</description>
    <inlineHelpText>Check indicates revenue from this order is included in SRO estimate / No check indicates revenue from this order is potential upside to the SRO estimate.</inlineHelpText>
    <label>Included in SRO</label>
    <type>Checkbox</type>
</CustomField>

src/objects/OpportunityLineItem/fields/M_PM_Product__c.field-meta.xml
<CustomField>
    <fullName>M_PM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field should be populated with the GBE Product Type</inlineHelpText>
    <label>Product Cross Reference Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Invalid M&amp;PM Product.  Must be active for 2021 Product Type Master File distributed by Finance.</errorMessage>
        <filterItems>
            <field>Product_Line_Cross_Ref__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Must choose from the 2021 Product Type Master File distributed by Finance.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line_Cross_Ref__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plant_Code_Master__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Code_Master__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <inlineHelpText>PGo * PWin</inlineHelpText>
    <label>Opportunity Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Revenue_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_End_Date__c</fullName>
    <inlineHelpText>To modify Revenue End date please edit Revenue Schedule</inlineHelpText>
    <label>Revenue End Date</label>
    <type>Date</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Revenue_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Start_Date__c</fullName>
    <inlineHelpText>To modify Revenue Start date please edit Revenue Schedule</inlineHelpText>
    <label>Revenue Start Date</label>
    <type>Date</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Repairs / Overhaul</fullName>
            </value>
            <value>
                <fullName>RMU</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Spares / AM / OEM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/TestEnd__c.field-meta.xml
<CustomField>
    <fullName>TestEnd__c</fullName>
    <formula>PricebookEntry.Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TestEnd</label>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APO</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
                <default>true</default>
                <label>Forecast</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/CloneOpportunityProduct.cls
/** * File Name: CloneOpportunityProduct
* Description This class is to clone the Opportunity Product with Schedules 
* @author : ITSS
* */
public class CloneOpportunityProduct {
     
    //variable declaration
    private final OpportunityLineItem olItem;
    public String msg{get;set;}
    public Boolean showInput{get;set;}
    public Boolean showOutput{get;set;}
    String profileId = System.Userinfo.getprofileId();
    //profileid = profileId.substring(0,15);
    String pName = [SELECT Name FROM Profile where Id  =: profileid].Name;
    public CloneOpportunityProduct (ApexPages.StandardController stdController) 
    {
        this.olItem = (OpportunityLineItem)stdController.getRecord();
    }
    
    public CloneOpportunityProduct () 
    {
        
    }
    public pagereference cloneOpportunityLineItemEdit(){
    msg='Please click on save to clone the product';
    List<OpportunityLineItemSchedule> scheduleList=[select id,type from OpportunityLineItemSchedule where OpportunityLineItemId=:this.olItem.id];
    if(scheduleList!=null && scheduleList.size()>0){
       showInput=false;
       showOutput=true;
    }else{
        showInput=true;
        showOutput=false;
    }
    String SOQL = 'Select ';
       // SOQL += 'pricebookentryid, hasrevenueschedule, createdbyid, lastmodifieddate, id, external_id__c, unitprice, description, plant__c, isdeleted, quantity, testend__c, extended_price__c, opportunityid, systemmodstamp, servicedate, listprice, hasschedule, price__c, createddate, subtotal, active__c, type__c, discount, sortorder, amount_net__c, description__c, probability__c, hasquantityschedule, lastmodifiedbyid';
       // Added for the Certido # - 337576 - Start
       SOQL += 'pricebookentryid, hasrevenueschedule, createdbyid, lastmodifieddate, id, external_id__c, unitprice, description, plant__c, isdeleted, quantity, testend__c, extended_price__c, opportunityid, systemmodstamp, servicedate, listprice, hasschedule, price__c, createddate, subtotal, active__c, type__c, discount, sortorder, amount_net__c, description__c, probability__c, hasquantityschedule,Revenue_Type__c,M_PM_Product__c, lastmodifiedbyid';
       // Added for the Certido # - 337576 - End
       
        //Remove the last , unnecessary comma 
        SOQL += ' From OpportunityLineItem o where id=\''+this.olItem.id+'\' LIMIT 1' ; 
        //Execute SOQL & Cast the sObject type into an OpportunityLineItem
        sObject S = Database.query(SOQL);  
        OpportunityLineItem newItem= (OpportunityLineItem)S; 
        newItem.Active__c=this.olItem.Active__c;
        newItem.ServiceDate=this.olItem.ServiceDate;
        newItem.UnitPrice=this.olItem.UnitPrice;
        if(this.olItem.Type__c == 'Booked' && pName == 'D&S Sales'){
            newItem.Type__c='Forecast';
        }else{
            newItem.Type__c=this.olItem.Type__c;
        }
        
        newItem.Quantity=this.olItem.Quantity;
        return null;
    }
    public PageReference save(){
        
        PageReference pageRef =cloneOpportunityLineItem();
        System.debug('pageRef in Save method === '+pageRef);
        if(pageRef!=null){
            pageRef.setRedirect(true); 
            return pageRef;
        }else{
        return null;
        }
    }
    public pagereference cloneOpportunityLineItem (){
        Savepoint sp = Database.setSavepoint();
        String oliID = ApexPages.currentPage().getParameters().get('id'); 
        if (oliID == null) { 
        //Display the Visualforce page's content if no Id is passed over
            return null;
        } 
        // Get the sObject describe result for the OpportunityLineItem object  
        Schema.DescribeSObjectResult r = OpportunityLineItem.sObjectType.getDescribe(); 
        Map<String, Schema.SObjectField> M = r.fields.getMap(); 
        //Generate a Map of the fields 
        //Now loop through the list of Field Names and concatenate the SOQL query string 
        String SOQL = 'Select ';
     // SOQL += 'pricebookentryid, hasrevenueschedule, createdbyid, lastmodifieddate, id, external_id__c, unitprice, description, plant__c, isdeleted, quantity, testend__c, extended_price__c, opportunityid, systemmodstamp, servicedate, listprice, hasschedule, price__c, createddate, subtotal, active__c, type__c, discount, sortorder, amount_net__c, description__c, probability__c,hasquantityschedule, lastmodifiedbyid';
         // Added for the Certido # - 337576 - Start
        SOQL += 'pricebookentryid, hasrevenueschedule, createdbyid, lastmodifieddate, id, external_id__c, unitprice, description, plant__c, isdeleted, quantity, testend__c, extended_price__c, opportunityid, systemmodstamp, servicedate, listprice, hasschedule, price__c, createddate, subtotal, active__c, type__c, discount, sortorder, amount_net__c, description__c, probability__c,Revenue_Type__c,M_PM_Product__c, hasquantityschedule, lastmodifiedbyid';
        // Added for the Certido # - 337576 - End
  
        //Remove the last , unnecessary comma 
        SOQL += ' From OpportunityLineItem o where id=\''+oliID+'\' LIMIT 1' ; 
        //Execute SOQL & Cast the sObject type into an OpportunityLineItem
        sObject S = Database.query(SOQL);  
        OpportunityLineItem oppLineItem = (OpportunityLineItem)S; 
        //Clone the OpportunityLineItem - 2 parameters (PreserveId or not, IsDeepClone or not )   
        OpportunityLineItem newOLI = oppLineItem.clone(false,true);
        //newOLI.PricebookEntryId = oppLineItem.PricebookEntryId + ' Cloned';
        //Code added by madhu for updating edited value by user
        newOLI.Active__c=this.olItem.Active__c;
        newOLI.ServiceDate=this.olItem.ServiceDate;
        newOLI.UnitPrice=this.olItem.UnitPrice;
        //newOLI.Type__c=this.olItem.Type__c;
        
        if(this.olItem.Type__c == 'Booked' && pName == 'D&S Sales' ){
            newOLI.Type__c='Forecast';
        }else{
            newOLI.Type__c=this.olItem.Type__c;
        }
        
        newOLI.Quantity=this.olItem.Quantity;
        newOLI.Probability__c=this.olItem.Probability__c;
        newOLI.Description=this.olItem.Description;
        newOLI.Revenue_Start_Date__c=this.olItem.Revenue_Start_Date__c;
        newOLI.Plant__c=this.olItem.Plant__c;
        newOLI.Revenue_End_Date__c=this.olItem.Revenue_End_Date__c;
        newOLI.Functional_Help_Required__c=this.olItem.Functional_Help_Required__c;
        newOLI.E_SIOP_Demand_Category__c=this.olItem.E_SIOP_Demand_Category__c;
        newOLI.Demand_Decision_Date__c=this.olItem.Demand_Decision_Date__c;
        newOLI.Closure_Actions__c=this.olItem.Closure_Actions__c;
        newOLI.Include_Net_Rev_in_SRO_Estimate__c=this.olItem.Include_Net_Rev_in_SRO_Estimate__c;
        newOLI.Include_in_CYO_Tracking__c=this.olItem.Include_in_CYO_Tracking__c;
        // Added for the Certido # - 337576 - Start
        newOLI.Revenue_Type__c=this.olItem.Revenue_Type__c;
        newOLI.M_PM_Product__c=this.olItem.M_PM_Product__c;
         // Added for the Certido # - 337576 - End
        try
        { 
            insert newOLI;   
        }
        catch(Exception e)
        {   
                  
            Database.rollback(sp);
            this.olItem.addError(e.getMessage());
            System.debug('in Catch block after rolledback sp newOLI ');
            return null;
        }
      
        // Get the sObject describe result for the Opportunity object  
        Schema.DescribeSObjectResult r1 = OpportunityLineItemSchedule.sObjectType.getDescribe(); 
        Map<String, Schema.SObjectField> M1 = r1.fields.getMap(); 
        //Generate a Map of the fields 
        //Now loop through the list of Field Names and concatenate the SOQL query string 
        String SOQL1 = 'Select ';  
        for (String fieldName : M1.keySet()){    
            System.debug('fieldName: ' + fieldName); 
            SOQL1 += fieldName + ',';  
        }  
        SOQL1 = SOQL1.substring(0,SOQL1.length()-1); 
        //Remove the last , unnecessary comma 
        SOQL1 += ' From OpportunityLineItemSchedule o where OpportunityLineItemId=\''+oliID+'\' ' ; 
        //Execute SOQL & Cast the sObject type into an OpportunityLineItemSchedule
        List<OpportunityLineItemSchedule> patt1= Database.query(SOQL1);  

        //Clone the OpportunityLineItem - 2 parameters (PreserveId or not, IsDeepClone or not )   
        List<OpportunityLineItemSchedule> newOLI1 = new List<OpportunityLineItemSchedule>();
        
        for(integer i=0;i<patt1.size();i++)
        {
            newOLI1.add(patt1[i].clone(false,true));
        }
        for(integer i=0;i<newOLI1.size();i++)
        {
            newOLI1[i].OpportunityLineItemId = newOLI.Id ; 
        }
        try
        {
            insert newOLI1;
        }
        catch (Exception e){
            //roll everything back in case of errors
            Database.rollback(sp);
            this.olItem.addError(e.getMessage());
            System.debug('in Catch block after rolledback sp newOLI1');
            return null;
        }
        //Redirect to the new OpportunityLineItem
        PageReference pageRef = new PageReference('/' + newOLI.Id);
        pageRef.setRedirect(true); 
        return pageRef;
    }
}