src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/HON_Commit_Date__c.field-meta.xml
<CustomField>
    <fullName>HON_Commit_Date__c</fullName>
    <defaultValue>NOW()+1</defaultValue>
    <label>HON Commit Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/Supported_Product__c.field-meta.xml
<CustomField>
    <fullName>Supported_Product__c</fullName>
    <description>Do NOT change this list without Troy Barrett / Jenn Searle Approval - They are the Business Owners (TOC)</description>
    <label>Supported Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Catalog_Product_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>787 Maintenance System</fullName>
            </value>
            <value>
                <fullName>ACARS MU</fullName>
            </value>
            <value>
                <fullName>ADAHRS/AHRS</fullName>
            </value>
            <value>
                <fullName>ADAHRS - Bendix King</fullName>
            </value>
            <value>
                <fullName>ADC/DADC (Digital Air Data Computer)</fullName>
            </value>
            <value>
                <fullName>ADF, Primus II/EPIC</fullName>
            </value>
            <value>
                <fullName>ADF DFA-74X</fullName>
            </value>
            <value>
                <fullName>ADIRS</fullName>
            </value>
            <value>
                <fullName>ADIRU</fullName>
            </value>
            <value>
                <fullName>AESS</fullName>
            </value>
            <value>
                <fullName>AFIS</fullName>
            </value>
            <value>
                <fullName>AGT1500 Military</fullName>
            </value>
            <value>
                <fullName>AHRS</fullName>
            </value>
            <value>
                <fullName>Aircraft Personality Module</fullName>
            </value>
            <value>
                <fullName>Airframe Hydraulics</fullName>
            </value>
            <value>
                <fullName>Airplane Information Management System (AIMS)</fullName>
            </value>
            <value>
                <fullName>AirSat 1</fullName>
            </value>
            <value>
                <fullName>Air Traffic Services</fullName>
            </value>
            <value>
                <fullName>Air Turbine Starter</fullName>
            </value>
            <value>
                <fullName>AL/Ex / SPEX / ISS</fullName>
            </value>
            <value>
                <fullName>ALF502 Engine</fullName>
            </value>
            <value>
                <fullName>Anti-Ice Valves - ATR</fullName>
            </value>
            <value>
                <fullName>Anti-Ice Valves - BGA</fullName>
            </value>
            <value>
                <fullName>AOG Lease / Engine Rental Bank</fullName>
            </value>
            <value>
                <fullName>APEX Pilatus</fullName>
            </value>
            <value>
                <fullName>APEX Viking</fullName>
            </value>
            <value>
                <fullName>APM</fullName>
            </value>
            <value>
                <fullName>APU - 100-2/-3/-135</fullName>
            </value>
            <value>
                <fullName>APU - 131-9A</fullName>
            </value>
            <value>
                <fullName>APU - 131-9B</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Skills2__c/Skills2__c.object-meta.xml
<CustomObject>
    <label>Skills</label>
    <nameField>
        <displayFormat>SK-{0}</displayFormat>
        <label>Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Skills2__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Skills2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Skills2__c/fields/Primary_Secondary__c.field-meta.xml
<CustomField>
    <fullName>Primary_Secondary__c</fullName>
    <label>Primary/Secondary</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Skills2__c/fields/Supported_Product__c.field-meta.xml
<CustomField>
    <fullName>Supported_Product__c</fullName>
    <label>Supported Product</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/classes/sendmailclass_TM.cls
@isTest
private class sendmailclass_TM{

 static testMethod void sendmailclass_Testcls1() 
 {
    
    //List<Folder> EMTFolder = [Select Id, Name, DeveloperName from Folder where type = 'email' and (( Name like 'CSO%') or ( Name like 'GTO%') or ( Name like 'Survey%'))];
    //system.debug('@@@@TEST:EmailTemplate='+ EMTFolder);
    
    //EmailTemplate etemp = [Select Name, HtmlValue, Subject, Body, DeveloperName, TemplateType, IsActive, FolderId from EmailTemplate where Name LIKE 'CSO - Account Request'];
    
    //creating account;
     Account acc= new Account(name='Test Account');
     insert acc;
     
     //creating contact;
     Contact cont = new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495',
      Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='T123567' );
     insert cont;
    
    
    Skills2__c skill = new Skills2__c (Primary_Secondary__c='Primary' ,Supported_Product__c='Radio',   Contact__c=cont.Id);
    insert skill;
   test.starttest();    
     //creating case
    Case cases3=new Case(AccountId=acc.Id,subject='Test Case2:Do not Delete',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
     //No_FCR_Reason__c='Not Trained',
     Type='Order',
     Supported_Product__c='Radio',Origin ='Email-Anniston.RFQ');
     insert cases3;
    
    
//    Case newcase = [Select id, Contactid, Origin, Classification__c, Status, HON_Commit_Date__c, Export_Compliance_Content_ITAR_EAR__c, Government_Compliance_SM_M_Content__c, Sub_Class__c, Detail_Class__c, Resolution__c from Case where subject='Test Case2:Do not Delete' limit 1];
  //  system.debug('**************'+newcase);
       
    
/*    Attachment attach = new Attachment();
    attach.Name = 'NewAttachment';
    attach.ParentId = newcase.ID;
    String asd = 'asd';
    attach.Body = blob.valueof(asd);
    insert attach;
*/
    
    EmailMessage emess = new EmailMessage();
    emess.BccAddress = 'anup.narayanan@wipro.com';
    emess.CcAddress = 'albin.arul@wipro.com';
    emess.HtmlBody = 'This is Html body Case:';
    emess.Subject = 'Test Subject';
    emess.TextBody = 'This is Text body';
    emess.ToAddress = 'niveda.jeyaseelan@wipro.com';
    emess.FromAddress = 'anup.narayanan@wipro.com'; 
    emess.ParentID = cases3.id;
    
    insert emess;
    
    PageReference pageRef1 = Page.SendmailPage;
    Test.setCurrentPage(pageRef1);
    ApexPages.CurrentPage().getParameters().Put('BCClist','anup.narayanan@gmail.com');
    ApexPages.CurrentPage().getParameters().Put('AddCClist','n.anup89@gmail.com');
    ApexPages.CurrentPage().getParameters().Put('ToList','anup.narayanan@wipro.com');
    ApexPages.CurrentPage().getParameters().Put('caseid',cases3.id); 
    ApexPages.CurrentPage().getParameters().Put('isHtml','true'); 
    ApexPages.CurrentPage().getParameters().Put('isHTMLval','true');
    ApexPages.CurrentPage().getParameters().Put('templateId',Null);
    Apexpages.currentPage().getParameters().put('textemailBody','<html><br/>amp;&nbsp&ndash;{!Case. hello how are you{!Case.}</html>');
    Apexpages.currentPage().getParameters().put('HtmlemailBody','<html><br/>amp;&nbsp&ndash;{!Case. hello how are you{!Case.}</html>');
     
    ApexPages.StandardController std1 = new ApexPages.StandardController(emess);  
    sendmailclass test2 = new sendmailclass(std1);
    test2.doref();
    test.stoptest();
 }

static testMethod void sendmailclass_Testcls() 
 {
    //List<Folder> EMTFolder = [Select Id, Name, DeveloperName from Folder where type = 'email' and (( Name like 'CSO%') or ( Name like 'GTO%') or ( Name like 'Survey%'))];
    //system.debug('@@@@TEST:EmailTemplate='+ EMTFolder);
    
    //EmailTemplate etemp = [Select Name, HtmlValue, Subject, Body, DeveloperName, TemplateType, IsActive, FolderId from EmailTemplate where Name LIKE 'CSO - Account Request'];
    Id etemp = Label.CSO_Account_Request_Temp_Id;
     
    //creating account;
     Account acc= new Account(name='Test Account');
     insert acc;
     
     //creating contact;
     Contact cont = new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495',
      Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='H123567' );
     insert cont;
    
    
    Skills2__c skill = new Skills2__c (Primary_Secondary__c='Primary' ,Supported_Product__c='Radio',   Contact__c=cont.Id);
    insert skill;
      
     //creating case
    Case cases3=new Case(AccountId=acc.Id,subject='Test Case2:Do not Delete',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
     //No_FCR_Reason__c='Not Trained',
     Type='Order',Supported_Product__c='Radio',Origin ='Email-Anniston.RFQ');
     test.starttest();
     insert cases3;
    
    
//    Case newcase = [Select id, Contactid, Origin, Classification__c, Status, HON_Commit_Date__c, Export_Compliance_Content_ITAR_EAR__c, Government_Compliance_SM_M_Content__c, Sub_Class__c, Detail_Class__c, Resolution__c from Case where subject='Test Case2:Do not Delete' limit 1];
  //  system.debug('**************'+newcase);
       
    
    Attachment attach = new Attachment();
    attach.Name = 'NewAttachment';
    attach.ParentId = cases3.ID;
    String asd = 'asd';
    attach.Body = blob.valueof(asd);
    insert attach;

    
    EmailMessage emess = new EmailMessage();
    emess.BccAddress = 'anup.narayanan@wipro.com';
    emess.CcAddress = 'albin.arul@wipro.com';
    emess.HtmlBody = 'This is Html body Case:';
    emess.Subject = 'Test Subject';
    emess.TextBody = 'This is Text body';
    emess.ToAddress = 'niveda.jeyaseelan@wipro.com';
    emess.FromAddress = 'anup.narayanan@wipro.com'; 
    emess.ParentID = cases3.id;
     
    insert emess;
    
    PageReference pageRef = Page.SendmailPage;
    Test.setCurrentPage(pageRef);
    ApexPages.CurrentPage().getParameters().Put('BCClist','anup.narayanan@gmail.com');
    ApexPages.CurrentPage().getParameters().Put('AddCClist','n.anup89@gmail.com');
    ApexPages.CurrentPage().getParameters().Put('ToList','anup.narayanan@wipro.com');
    ApexPages.CurrentPage().getParameters().Put('caseid',cases3.id); 
    ApexPages.CurrentPage().getParameters().Put('isHtml','true'); 
    ApexPages.CurrentPage().getParameters().Put('isHTMLval','true');
    ApexPages.CurrentPage().getParameters().Put('templateId',etemp);
    Apexpages.currentPage().getParameters().put('textemailBody','<html><br/>amp;&nbsp&ndash;{!Case. hello how are you{!Case.}</html>');
    Apexpages.currentPage().getParameters().put('HtmlemailBody','<html><br/>amp;&nbsp&ndash;{!Case. hello how are you{!Case.}</html>');
    ApexPages.StandardController std = new ApexPages.StandardController(emess);  
    
    sendmailclass test1 = new sendmailclass(std);

  
    test1.fileName = 'asd';
    
    String bb = 'dsa';       
    test1.filebody = blob.valueof(bb); 
    test1.Aname='test hello';
    test1.doref1();
    test1.attachtemplate();
    test1.template();
    test1.getemsg();
    String s = test1.getEmailTemplate();
    test1.setEmailTemplate(s);
   
    String s1 = test1.gettemplateId();
    test1.settemplateId(s1);
 
    List<SelectOption> templist = test1.getTempList();
    List<EmailTemplate> etmp = test1.getemailTemplates();   
    
    Case c = test1.getcaseRecord();  
    test1.cancelTemplate();
    test1.ViewDetails();
    test1.ViewTemplateDetails();
    test1.ViewTemplateDetails1();
    test1.send();
    test1.cancel();
    //test1.attachfile();
    //test1.nodisp();
    //test1.UploadFile();
    //test1.query();
     List<SelectOption> selOpts=test1.getFrmAdd();
    String s2 = test1.getsubject();
    test1.setsubject(s2);
    
    String s3 = test1.getTolist();
    test1.setTolist(s3);
    
    String s4 = test1.getAddCClist();
    test1.setAddCClist(s4);
    
    String s5 = test1.getBCClist();
    test1.setBCClist(s5);
    
    String s6 = test1.getHtmlemailBody();
    test1.setHtmlemailBody('{!Case.}');
    
    String s7 = test1.gettextemailBody();
    
    test1.settextemailBody('{!Case.}');
    
    String s8 = test1.getFrmlst();
    test1.setFrmlst(s8);
    
    test1.search();
  
    String s9 = test1.getfname();
    test1.setfname(s9);
    
    test1.getSelected();
    test1.Anamecc = 'aname';  
    test1.searchcc();
    //test1.querycc();
    test1.Anamebcc = 'aname'; 
    test1.aname  = 'aname'; 
    sendmailclass.contactwrapper con2= new sendmailclass.contactwrapper(cont);
    sendmailclass.contactwrappercc con1= new sendmailclass.contactwrappercc(cont);
    sendmailclass.contactwrapperbcc con3= new sendmailclass.contactwrapperbcc(cont);
    sendmailclass.attachmentwrapper att= new sendmailclass.attachmentwrapper(attach);
    
    String[] str = new String[]{'asd','dsa'};
    
    String s10 = test1.getfnamecc();
    test1.setfnamecc(s10);
    test1.setoptions(str);
    
    String[] s11233 = test1.getoptions();
    
    test1.searchbcc();
    //test1.querybcc();
    test1.Anamecc = 'wipro';
    
    String s12 = test1.getfnamebcc();
    test1.setfnamebcc(s12);
    
    test1.hidemessage();
    
    List<Id> selattach = test1.GetSelectedattachments(); 
  //  test1.attachfromcase();
  //  test1.attachfileCase();    
    List<Attachment> attch = test1.getattachments(); 
  //  test1.cancelAttachment();
    test1.getSelected1();
    List<Attachment> showatt = test1.getshowatt();
    test1.del();
  //  test1.query();
//**************************** 
   
  /*  List<Contact> c3234 = new List<Contact>([select Id,FirstName,LastName,AccountID from Contact limit 5]);
    test1.conresults.addAll(c3234);
    test1.conresultscc.addAll(c3234);
    test1.conresultsbcc.addAll(c3234);*/
    
/*  List<SelectOption> test123 = test1.getFrmAdd();
    List<String> str1 = new List<String>();
    str1 = test1.GetSelectedContacts();
    String[] str2 = test1.getoptionscc();
    test1.setoptionscc(str); 
    str1 = test1.GetSelectedContactscc();
    test1.getSelectedcc();
    str1 = test1.getoptionsbcc();
    test1.setoptionsbcc(str);
    str1 = test1.GetSelectedContactsbcc();
    test1.getSelectedbcc();
    test1.getresults();
    test1.getresultscc();
    test1.getresultsbcc();
    test1.getresults1();
*/

test.stoptest();
 }
    static testMethod void sendmailclass_Testcls2() 
 {
    //List<Folder> EMTFolder = [Select Id, Name, DeveloperName from Folder where type = 'email' and (( Name like 'CSO%') or ( Name like 'GTO%') or ( Name like 'Survey%'))];
    //system.debug('@@@@TEST:EmailTemplate='+ EMTFolder);
    
    //EmailTemplate etemp = [Select Name, HtmlValue, Subject, Body, DeveloperName, TemplateType, IsActive, FolderId from EmailTemplate where Name LIKE 'CSO - Account Request'];
    Id etemp = Label.CSO_Account_Request_Temp_Id;
     
    //creating account;
     Account acc= new Account(name='Test Account');
     insert acc;
     
     //creating contact;
     Contact cont = new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495',
      Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='H123567' );
     insert cont;
    
    
    Skills2__c skill = new Skills2__c (Primary_Secondary__c='Primary' ,Supported_Product__c='Radio',   Contact__c=cont.Id);
    insert skill;
      
     //creating case
    Case cases3=new Case(AccountId=acc.Id,subject='Test Case2:Do not Delete',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
     //No_FCR_Reason__c='Not Trained',
     Type='Order',Supported_Product__c='Radio',Origin ='Email-Anniston.RFQ');
     //test.starttest();
     insert cases3;
    
    
//    Case newcase = [Select id, Contactid, Origin, Classification__c, Status, HON_Commit_Date__c, Export_Compliance_Content_ITAR_EAR__c, Government_Compliance_SM_M_Content__c, Sub_Class__c, Detail_Class__c, Resolution__c from Case where subject='Test Case2:Do not Delete' limit 1];
  //  system.debug('**************'+newcase);
       
    
    Attachment attach = new Attachment();
    attach.Name = 'NewAttachment';
    attach.ParentId = cases3.ID;
    String asd = 'asd';
    attach.Body = blob.valueof(asd);
    insert attach;

    
    EmailMessage emess = new EmailMessage();
    emess.BccAddress = 'anup.narayanan@wipro.com';
    emess.CcAddress = 'albin.arul@wipro.com';
    emess.HtmlBody = 'This is Html body Case:';
    emess.Subject = 'Test Subject';
    emess.TextBody = 'This is Text body';
    emess.ToAddress = 'niveda.jeyaseelan@wipro.com';
    emess.FromAddress = 'anup.narayanan@wipro.com'; 
    emess.ParentID = cases3.id;
     
    insert emess;
    test.starttest();
    PageReference pageRef = Page.SendmailPage;
    Test.setCurrentPage(pageRef);
    ApexPages.CurrentPage().getParameters().Put('BCClist','anup.narayanan@gmail.com');
    ApexPages.CurrentPage().getParameters().Put('AddCClist','n.anup89@gmail.com');
    ApexPages.CurrentPage().getParameters().Put('ToList','anup.narayanan@wipro.com');
    ApexPages.CurrentPage().getParameters().Put('caseid',cases3.id); 
    ApexPages.CurrentPage().getParameters().Put('isHtml','true'); 
    ApexPages.CurrentPage().getParameters().Put('isHTMLval','false');
   // ApexPages.CurrentPage().getParameters().Put('templateId',etemp);
   ApexPages.CurrentPage().getParameters().Put('subject','');
    ApexPages.StandardController std = new ApexPages.StandardController(emess);  
    sendmailclass test1 = new sendmailclass(std);
   
  
    test1.fileName = 'asd';
    
    String bb = 'dsa';       
    test1.filebody = blob.valueof(bb); 
    test1.Aname='test hello';
    test1.doref1();
    test1.attachtemplate();
    test1.template();
    test1.getemsg();
    String s = test1.getEmailTemplate();
    test1.setEmailTemplate(s);
   
    String s1 = test1.gettemplateId();
    test1.settemplateId(s1);
 
    List<SelectOption> templist = test1.getTempList();
    List<EmailTemplate> etmp = test1.getemailTemplates();   
    
    Case c = test1.getcaseRecord();  
    /*test1.cancelTemplate();
    test1.ViewDetails();
    test1.ViewTemplateDetails();
    test1.ViewTemplateDetails1();
    test1.send();
    test1.cancel();*/
    test1.attachfile();
    test1.nodisp();
    test1.UploadFile();
    test1.query();
   
     List<SelectOption> selOpts=test1.getFrmAdd();
    String s2 = test1.getsubject();
    
    test1.setsubject(s2);
    
    String s3 = test1.getTolist();
    test1.setTolist(s3);
    
    String s4 = test1.getAddCClist();
    test1.setAddCClist(s4);
    
    String s5 = test1.getBCClist();
    test1.setBCClist(s5);
    
    String s6 = test1.getHtmlemailBody();
    test1.setHtmlemailBody(s6);
    
    String s7 = test1.gettextemailBody();
    test1.settextemailBody(s7);
    
    String s8 = test1.getFrmlst();
    test1.setFrmlst(s8);
    
    test1.search();
  
    String s9 = test1.getfname();
    test1.setfname(s9);
    
    test1.getSelected();
    test1.Anamecc = 'aname';  
    test1.searchcc();
    //test1.querycc();
    test1.Anamebcc = 'aname'; 
    test1.aname  = 'aname'; 
    sendmailclass.contactwrapper con2= new sendmailclass.contactwrapper(cont);
    sendmailclass.contactwrappercc con1= new sendmailclass.contactwrappercc(cont);
    sendmailclass.contactwrapperbcc con3= new sendmailclass.contactwrapperbcc(cont);
    sendmailclass.attachmentwrapper att= new sendmailclass.attachmentwrapper(attach);
    
    String[] str = new String[]{'asd','dsa'};
    
    String s10 = test1.getfnamecc();
    test1.setfnamecc(s10);
    test1.setoptions(str);
    
    String[] s11233 = test1.getoptions();
    
    test1.searchbcc();
    //test1.querybcc();
    test1.Anamecc = 'wipro';
    
    String s12 = test1.getfnamebcc();
    test1.setfnamebcc(s12);
    
    test1.hidemessage();
    
    List<Id> selattach = test1.GetSelectedattachments(); 
  //  test1.attachfromcase();
  //  test1.attachfileCase();    
    List<Attachment> attch = test1.getattachments(); 
  //  test1.cancelAttachment();
    test1.getSelected1();
    List<Attachment> showatt = test1.getshowatt();
    test1.del();
    Boolean a = test1.success;
    test1.getresults();
    List<String> aa = test1.GetSelectedContacts();
    Boolean b = test1.noquerycc;
    Boolean cs = test1.noresultscc;    
    Boolean d = test1.successcc;
    test1.querycc();
    test1.lnamecc = 'test';
    List<String> cc = test1.getoptionscc();
    test1.setoptionscc(cc);
    test1.getresultscc();
    List<String> aaa = test1.GetSelectedContactscc();
    PageReference aaaaa = test1.getSelectedcc();
    Boolean e = test1.noquerybcc;
    Boolean f = test1.noresultsbcc;
    Boolean g = test1.successbcc;
    test1.querybcc();
    test1.lnamebcc = 'test';
    List<String> qq = test1.getoptionsbcc();
    test1.setoptionsbcc(qq);
    test1.getresultsbcc();
    List<String> ww = test1.GetSelectedContactsbcc();
    PageReference pp = test1.getSelectedbcc();
    test1.attachfromcase();
    test1.attachfileCase();
    test1.cancelAttachment();
    test1.getresults1();
     test1.setfname('');
    test1.lname = '';
    test1.aname = '';
   test1.setfname('test');
    test1.lname = '';
    test1.aname = '';
    test1.query();
    test1.setfname('');
    test1.lname = '';
    test1.aname = '';
   test1.setfname('');
    test1.lname = 'test';
    test1.aname = '';
    test1.query();
   test1.setfname('');
    test1.lname = '';
    test1.aname = '';
     test1.setfname('test');
    test1.lname = '';
    test1.aname = 'test';
    test1.query();
   test1.setfname('');
    test1.lname = '';
    test1.aname = '';
    
    test1.setfname('');
    test1.lname = 'test';
    test1.aname = 'test';
    test1.query();
    test1.setfname('');
    test1.lname = '';
    test1.aname = '';
   test1.setfname('');
    test1.lname = '';
    test1.aname = 'test';
    test1.query();
   test1.setfname('');
    test1.lname = '';
    test1.aname = '';
  test1.setfname('test');
    test1.lname = 'test';
    test1.aname = '';
    test1.query();
  test1.setfname('');
    test1.lname = '';
    test1.aname = '';
     test1.query();
        test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = '';
   test1.setfnamecc('test');
    test1.lnamecc = '';
    test1.anamecc = '';
    test1.query();
    test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = '';
   test1.setfnamecc('');
    test1.lnamecc = 'test';
    test1.anamecc = '';
    test1.query();
   test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = '';
     test1.setfnamecc('test');
    test1.lnamecc = '';
    test1.anamecc = 'test';
    test1.query();
   test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = '';
    
    test1.setfnamecc('');
    test1.lnamecc = 'test';
    test1.anamecc = 'test';
    test1.query();
    test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = '';
   test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = 'test';
    test1.query();
   test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = '';
  test1.setfnamecc('test');
    test1.lnamecc = 'test';
    test1.anamecc = '';
    test1.query();
  test1.setfnamecc('');
    test1.lnamecc = '';
    test1.anamecc = '';
     test1.query();
      test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = '';
   test1.setfnamebcc('test');
    test1.lnamebcc = '';
    test1.anamebcc = '';
    test1.query();
    test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = '';
   test1.setfnamebcc('');
    test1.lnamebcc = 'test';
    test1.anamebcc = '';
    test1.query();
   test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = '';
     test1.setfnamebcc('test');
    test1.lnamebcc = '';
    test1.anamebcc = 'test';
    test1.query();
   test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = '';
    
    test1.setfnamebcc('');
    test1.lnamebcc = 'test';
    test1.anamebcc = 'test';
    test1.query();
    test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = '';
   test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = 'test';
    test1.query();
   test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = '';
  test1.setfnamebcc('test');
    test1.lnamebcc = 'test';
    test1.anamebcc = '';
    test1.query();
  test1.setfnamebcc('');
    test1.lnamebcc = '';
    test1.anamebcc = '';
     test1.query();
    
   
   
    Boolean vb = test1.showlist;
    
    
  //  test1.query();
//**************************** 
   
  /*  List<Contact> c3234 = new List<Contact>([select Id,FirstName,LastName,AccountID from Contact limit 5]);
    test1.conresults.addAll(c3234);
    test1.conresultscc.addAll(c3234);
    test1.conresultsbcc.addAll(c3234);*/
    
/*  List<SelectOption> test123 = test1.getFrmAdd();
    List<String> str1 = new List<String>();
    str1 = test1.GetSelectedContacts();
    String[] str2 = test1.getoptionscc();
    test1.setoptionscc(str); 
    str1 = test1.GetSelectedContactscc();
    test1.getSelectedcc();
    str1 = test1.getoptionsbcc();
    test1.setoptionsbcc(str);
    str1 = test1.GetSelectedContactsbcc();
    test1.getSelectedbcc();
    test1.getresults();
    test1.getresultscc();
    test1.getresultsbcc();
    test1.getresults1();
*/

test.stoptest();
 }
}