src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Cage_Code__c.field-meta.xml
<CustomField>
    <fullName>Cage_Code__c</fullName>
    <description>Cage Code from Web</description>
    <label>Manufacturing Plant Cage Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Spares</fullName>
            </value>
            <value>
                <fullName>Repair/Overhaul</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Special Programs</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Queries</fullName>
            </value>
            <value>
                <fullName>Advance Exchange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1st Follow-up</fullName>
            </value>
            <value>
                <fullName>2nd Follow-up</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Accelerated Repair</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>Accts</fullName>
            </value>
            <value>
                <fullName>Acknowledgement Provided</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Administrative Hold -Z8</fullName>
            </value>
            <value>
                <fullName>Advanced Troubleshooting</fullName>
            </value>
            <value>
                <fullName>After-exp queue</fullName>
            </value>
            <value>
                <fullName>AIDC Quote Hold</fullName>
            </value>
            <value>
                <fullName>Aircraft In Maintenance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>ATS</fullName>
            </value>
            <value>
                <fullName>ATS (Tech Support) Hold</fullName>
            </value>
            <value>
                <fullName>Aviation Services</fullName>
            </value>
            <value>
                <fullName>Awaiting Amended PO-Z2</fullName>
            </value>
            <value>
                <fullName>Awaiting billing review</fullName>
            </value>
            <value>
                <fullName>Awaiting Client reply for more info</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Verification</fullName>
            </value>
            <value>
                <fullName>Awaiting credit review</fullName>
            </value>
            <value>
                <fullName>Awaiting MSP review</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting reply from ICARUS</fullName>
            </value>
            <value>
                <fullName>AWB Sent</fullName>
            </value>
            <value>
                <fullName>B/E Quote Hold</fullName>
            </value>
            <value>
                <fullName>Business Hold</fullName>
            </value>
            <value>
                <fullName>Customer Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Contact/fields/Phone_Tree_Extn__c.field-meta.xml
<CustomField>
    <fullName>Phone_Tree_Extn__c</fullName>
    <label>Phone Tree Extn</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

src/classes/Test_UpdateCase_Hold.cls
@isTest (seealldata=true)
public class Test_UpdateCase_Hold{
static testmethod void UpdateCase_Hold(){
list<case> lc = new list<case>();
  Account acc= new Account(name='Test Account');
        insert acc;
  Contact cont=new Contact(firstname='Test',LastName='Contact',Email='shrivaths.kulkarni@nttdata.com',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
        insert cont;
  Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No',Sales_Order_Number__c='test1234', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Business Hold', reason_for_hold__c = '8130 TAG', vn_name__c =cont.id);// For ticket INC000010025414
        // cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Business Hold', vn_name__c =cont.id); //For ticket INC000010025414
     //insert case1;
     lc.add(case1);
     Case case2=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Returns_Recordtypeid,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373',Sales_Order_Number__c='test1234', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Customer Hold', reason_for_hold__c = '8130 TAG');// For ticket INC000010025414
        // cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Customer Hold'); //For ticket INC000010025414
     lc.add(case2);
     insert lc;

     
 lc[0].sub_status__c='Customer Hold';
 case1.vn_name__c = null;
    //Update case1;
 lc[1].sub_status__c='Business Hold';
   
    Update lc;
   
}
static testmethod void UpdateCase_Hold1(){
 Account acc= new Account(name='Test Account');
        insert acc;
  Contact cont=new Contact(firstname='Test',LastName='Contact',Email='shriva.k@nttdata.com',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
        insert cont;
          Contact cont1=new Contact(firstname='Test',LastName='Contact',Email='shriva@nttdata.com',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123587');
        insert cont1;
             Case case3=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Internal_Escalations_RecordId,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Business Hold', reason_for_hold__c = '8130 TAG', vn_name__c =cont.id); //For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Business Hold', vn_name__c =cont.id); //For ticket INC000010025414
    insert case3; 
    
    test.starttest();
    case3.vn_name__c = cont1.id;
    Update case3;
    case3.status='open';
    Update case3;
    test.stoptest();
}
static testmethod void UpdateCase_Hold2(){
 Account acc= new Account(name='Test Account');
        insert acc;
  Contact cont=new Contact(firstname='Test',LastName='Contact',Email='shriva.k@nttdata.com',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
        insert cont;

             Case case3=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Internal_Escalations_RecordId,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Business Hold', reason_for_hold__c = '8130 TAG', vn_name__c =cont.id); //For ticket INC000010025414
        // cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Business Hold', vn_name__c =cont.id); //For ticket INC000010025414
    insert case3; 
    
    test.starttest();
    //case3.reason_for_hold__c = 'Consumption Ordering - 07'; For ticket INC000010025414
    Update case3;
    test.stoptest();
}
}