src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Age_in_Hours__c.field-meta.xml
<CustomField>
    <fullName>Age_in_Hours__c</fullName>
    <description>07/23/2018 : Age in hours modified to reflect the actual age of Case from the Created Date.</description>
    <formula>IF(IsClosed, (ClosedDate - CreatedDate)*24, (now()- CreatedDate)*24)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age in Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Case/fields/Aircraft_Location__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Location__c</fullName>
    <label>Aircraft Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Aircraft_Type__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft Type</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Platform must be an active platform.</errorMessage>
        <filterItems>
            <field>Platform__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>API DATA LOAD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/AOG_Service_level__c.field-meta.xml
<CustomField>
    <fullName>AOG_Service_level__c</fullName>
    <formula>IF($RecordType.Name == &apos;Technical Issue&apos;, if( DATEVALUE(HON_Commit_Date__c) &gt;TODAY() ,&apos;Green&apos;,&apos;Red&apos; ), 
if( ispickval( X4_Hour_AOG__c ,&apos;4-hour&apos;) &amp;&amp;( now() -CreatedDate &gt;=0.123 ) &amp;&amp; ( now() -CreatedDate &lt;0.166), &apos;Yellow&apos;, 
if( ispickval( X4_Hour_AOG__c ,&apos;4-hour&apos;) &amp;&amp; (now() -CreatedDate &gt;=0.166), &apos;Red&apos;, 
if( ispickval( X4_Hour_AOG__c ,&apos;24-hour&apos;) &amp;&amp; (now() -CreatedDate &gt;=0.75 ) &amp;&amp; (now() -CreatedDate &lt;1), &apos;Yellow&apos;, 
if( ispickval( X4_Hour_AOG__c ,&apos;24-hour&apos;) &amp;&amp; (now() -CreatedDate &gt;=1), &apos;Red&apos;, 
if( ispickval( X4_Hour_AOG__c ,&apos;48-hour&apos;) &amp;&amp; (now() -CreatedDate &gt;=1.5 ) &amp;&amp; (now() -CreatedDate &lt;2), &apos;Yellow&apos;, 
if( ispickval( X4_Hour_AOG__c ,&apos;48-hour&apos;) &amp;&amp; (now() -CreatedDate &gt;=2), &apos;Red&apos;, 
&apos;Green&apos;) 
) 
) 
) 
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AOG Service level</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/AOG_Service_Level_Flag__c.field-meta.xml
<CustomField>
    <fullName>AOG_Service_Level_Flag__c</fullName>
    <formula>IMAGE( CASE( AOG_Service_level__c
, &quot;Green&quot;, &quot;/img/samples/flag_green.gif&quot;, &quot;Yellow&quot;, &quot;/img/samples/flag_yellow.gif&quot;, &quot;Red&quot;, &quot;/img/samples/flag_red.gif&quot;, &quot;/img/samples/flag_green.gif&quot;), &quot;AOG Service Level&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AOG Service Level Flag</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/AOG_Service_level_Value__c.field-meta.xml
<CustomField>
    <fullName>AOG_Service_level_Value__c</fullName>
    <formula>if(AOG_Service_level__c==&apos;Red&apos;,3,
if(AOG_Service_level__c==&apos;Yellow&apos;,2,
if(AOG_Service_level__c==&apos;Green&apos;,1,null
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AOG Service level Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Case/fields/Hardware_Ship_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Ship_From_Address__c</fullName>
    <description>Hardware Ship From Address</description>
    <label>Hardware Ship From Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Albuquerque</fullName>
            </value>
            <value>
                <fullName>Ametek</fullName>
            </value>
            <value>
                <fullName>Anniston Repair Center</fullName>
                <label>Anniston</label>
            </value>
            <value>
                <fullName>Australia (Sydney) Support Center</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Avemex</fullName>
            </value>
            <value>
                <fullName>Aviall Services</fullName>
                <label>Aviall</label>
            </value>
            <value>
                <fullName>UK (Basingstoke) Support Center</fullName>
                <label>Basingstoke</label>
            </value>
            <value>
                <fullName>Bournemouth</fullName>
            </value>
            <value>
                <fullName>Boyne City</fullName>
            </value>
            <value>
                <fullName>Century/Lanseria</fullName>
            </value>
            <value>
                <fullName>Cessna/Kansas</fullName>
            </value>
            <value>
                <fullName>CEVA/Kansas City</fullName>
            </value>
            <value>
                <fullName>CEVA/Paris</fullName>
            </value>
            <value>
                <fullName>Clearwater</fullName>
            </value>
            <value>
                <fullName>Corporate Jet Support</fullName>
            </value>
            <value>
                <fullName>Dubai - K&amp;N</fullName>
                <label>Dubai</label>
            </value>
            <value>
                <fullName>Duncan</fullName>
            </value>
            <value>
                <fullName>Gables</fullName>
            </value>
            <value>
                <fullName>Greer Repair Center</fullName>
                <label>Greer</label>
            </value>
            <value>
                <fullName>HAT</fullName>
            </value>
            <value>
                <fullName>UK (Hemel-Hempstead) ERDC</fullName>
                <label>Hemel Hempstead</label>
            </value>
            <value>
                <fullName>Jet Avn/Basel</fullName>
                <label>Jet Aviation/Basel</label>
            </value>
            <value>
                <fullName>Lufthansa</fullName>
            </value>
            <value>
                <fullName>Minneapolis Support Center</fullName>
                <label>Minneapolis</label>
            </value>
            <value>
                <fullName>Olathe Repair</fullName>
            </value>
            <value>
                <fullName>Olathe Spares</fullName>
            </value>
            <value>
                <fullName>Ottawa</fullName>
            </value>
            <value>
                <fullName>Otto Instruments</fullName>
            </value>
            <value>
                <fullName>Penang, Malaysia</fullName>
                <label>Penang</label>
            </value>
            <value>
                <fullName>Phoenix Deer Valley Dist.Center</fullName>
                <label>Phoenix Deer Valley</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Last_Modified_Text__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Text__c</fullName>
    <label>Last Modified Text</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Last_Updated_HoursMins__c.field-meta.xml
<CustomField>
    <fullName>Last_Updated_HoursMins__c</fullName>
    <formula>(now()-LastModifiedDate)*1440</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Updated HoursMins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Case/fields/Next_Flight_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Flight_Out_Date__c</fullName>
    <inlineHelpText>MEL is Minimum Expiration Date</inlineHelpText>
    <label>Next Flight Out Date/MEL Expiration Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Case/fields/OwnerName__c.field-meta.xml
<CustomField>
    <fullName>OwnerName__c</fullName>
    <formula>if(left( OwnerId ,3)==&apos;005&apos;,OwnerId__r.FirstName +&apos; &apos;+ OwnerId__r.LastName,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OwnerNameFormula</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Product_Number__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <formula>Product_Number__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Part #</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Level__c</fullName>
    <formula>TEXT( Account.Service_Level__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Level</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/SPEX_Exchange__c.field-meta.xml
<CustomField>
    <fullName>SPEX_Exchange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SPEX/Exchange</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1st Follow-up</fullName>
            </value>
            <value>
                <fullName>2nd Follow-up</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Accelerated Repair</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>Accts</fullName>
            </value>
            <value>
                <fullName>Acknowledgement Provided</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Administrative Hold -Z8</fullName>
            </value>
            <value>
                <fullName>Advanced Troubleshooting</fullName>
            </value>
            <value>
                <fullName>After-exp queue</fullName>
            </value>
            <value>
                <fullName>AIDC Quote Hold</fullName>
            </value>
            <value>
                <fullName>Aircraft In Maintenance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>ATS</fullName>
            </value>
            <value>
                <fullName>ATS (Tech Support) Hold</fullName>
            </value>
            <value>
                <fullName>Aviation Services</fullName>
            </value>
            <value>
                <fullName>Awaiting Amended PO-Z2</fullName>
            </value>
            <value>
                <fullName>Awaiting billing review</fullName>
            </value>
            <value>
                <fullName>Awaiting Client reply for more info</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Verification</fullName>
            </value>
            <value>
                <fullName>Awaiting credit review</fullName>
            </value>
            <value>
                <fullName>Awaiting MSP review</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting reply from ICARUS</fullName>
            </value>
            <value>
                <fullName>AWB Sent</fullName>
            </value>
            <value>
                <fullName>B/E Quote Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/X4_Hour_AOG__c.field-meta.xml
<CustomField>
    <fullName>X4_Hour_AOG__c</fullName>
    <label>4-Hour AOG</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>4-hour</fullName>
            </value>
            <value>
                <fullName>24-hour</fullName>
            </value>
            <value>
                <fullName>48-hour</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/AOGGetOneCase.cls
public class AOGGetOneCase{
    
    String caseId;    
    
    Case case_one = new Case();    
       
    public AOGGetOneCase() {
        caseId = System.currentPageReference().getParameters().get('CASE');
    }
   
    public Case getCase_one(){
    
        //if(caseId != '')return null;
    
        case_one=[Select Id,AOG_Service_level__c,AOG_Service_Level_Flag__c,X4_Hour_AOG__c,CaseNumber,
        Account_Name__c, Service_Level__c, Sub_Status__c, Age_in_Hours__c, Aircraft_Type__c,
        Aircraft_Location__c,OwnerName__c, lastmodifieddate, Next_Flight_Out_Date__c,
        AOG_Service_level_Value__c,Aircraft_Type__r.Name, Last_Updated_HoursMins__c,Last_Modified_Text__c,
        Product_Part__c,Hardware_Ship_From_Address__c, Product_Name__c, SPEX_Exchange__c,
        AOG_OTTR_Miss_Detail__c, AOG_OTTR_Miss_Reason__c, Market__c, SBU__c, CBT_Team__c, Contract_Type__c,
        Order_Entered__c, Customer_Request_Date__c
        from Case 
        where isClosed=false 
            and status !='Re-Open' 
            and Id = :caseId
       ];
    
        return case_one;
    }
}