src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Additional_Web_Form_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Web_Form_Info__c</fullName>
    <label>Additional Web Form Info</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Case_Ref_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Ref_ID__c</fullName>
    <description>Custom Case reference ID based on which email attachment to case works.
Jun 03, 2014: Updated format since Case ID format changed after Org Split</description>
    <formula>&quot;[ ref:_&quot; &amp;
LEFT( $Organization.Id , 5) &amp;
IF (MID ( $Organization.Id, 6, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id,10),
IF (MID ( $Organization.Id, 7, 1) &lt;&gt; &quot;0&quot;,RIGHT($Organization.Id, 9),
IF (MID ( $Organization.Id, 8, 1) &lt;&gt;&quot;0&quot;, RIGHT($Organization.Id, 8),
IF (MID ( $Organization.Id, 9, 1)&lt;&gt; &quot;0&quot;, RIGHT($Organization.Id, 7),
IF (MID ( $Organization.Id,10, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id, 6),
IF (MID ($Organization.Id, 11, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id, 5),
IF(MID ( $Organization.Id, 12, 1) &lt;&gt; &quot;0&quot;, RIGHT($Organization.Id,4),
IF (MID ( $Organization.Id, 13, 1) &lt;&gt; &quot;0&quot;,RIGHT($Organization.Id, 3),
IF (MID ( $Organization.Id, 14, 1) &lt;&gt;&quot;0&quot;, RIGHT($Organization.Id, 2), &quot;&quot;) ) ) ) ) ) ) ) )
&amp; &quot;._&quot; &amp;LEFT( Id, 5) &amp;
IF(MID ( Id, 6, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 10),
IF (MID ( Id, 7, 1)&lt;&gt; &quot;0&quot;, RIGHT(Id, 9),
IF (MID ( Id, 8, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id,8),
IF (MID ( Id, 9, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 7),
IF (MID ( Id, 10,1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 6),
IF (MID ( Id, 11, 1) &lt;&gt; &quot;0&quot;,RIGHT(Id, 5),
IF (MID ( Id, 12, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 4),
IF (MID( Id, 13, 1) &lt;&gt; &quot;0&quot;, RIGHT(Id, 3),
IF (MID ( Id, 14, 1) &lt;&gt;&quot;0&quot;, RIGHT(Id, 2), &quot;&quot;) ) ) ) ) ) ) ) ) &amp; &quot;:ref ]&quot;</formula>
    <label>Case Ref ID</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Customer_PO_RO_WONumber__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_RO_WONumber__c</fullName>
    <description>Text Field used to hold the PO number. 
05/22 - Set to external ID for PO/SN deployment to avoid 554 connection error in Salesforce</description>
    <externalId>true</externalId>
    <label>Customer PO/RO/WO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Customer_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Request_Date__c</fullName>
    <defaultValue>NOW()+1</defaultValue>
    <label>Customer Request Date</label>
    <type>Date</type>
</CustomField>

src/objects/Case/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <label>Honeywell ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Pega_Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Pega_Case_ID__c</fullName>
    <label>Pega Case ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Pega_Reason_for_Hold__c.field-meta.xml
<CustomField>
    <fullName>Pega_Reason_for_Hold__c</fullName>
    <label>Auto Escalation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipment Status</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Estimated Ship Date past Due</fullName>
                <isActive>false</isActive>
                <label>Estimated Ship Date past Due</label>
            </value>
            <value>
                <fullName>Missed Shipment</fullName>
                <isActive>false</isActive>
                <label>Missed Shipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Primary_Cell_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Cell_Number__c</fullName>
    <formula>Contact.Phone_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Contact&apos;s Alternate Work Phone Number (Not same as Primary Work Number)</inlineHelpText>
    <label>Primary Cell Number</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <description>Primary Email for the supported product</description>
    <label>Primary Email</label>
    <type>Email</type>
</CustomField>

src/objects/Case/fields/Primary_Work_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Work_Number__c</fullName>
    <formula>Contact.Phone_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Contact&apos;s Primary Work Phone Number.</inlineHelpText>
    <label>Primary Work Number</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <formula>Text( Account.Strategic_Business_Unit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Part_Number__c/Part_Number__c.object-meta.xml
<CustomObject>
    <label>Part Number</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Part Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part_Number__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <formula>Product_Name__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

src/objects/PegaCredentials__c/PegaCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This CS stores the username and password to access Pega Service</description>
    <label>Pega Credentials</label>
</CustomObject>

src/objects/PegaCredentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

src/objects/PegaCredentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

src/objects/PegaService__c/PegaService__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting stores the Service endpoints of Pega</description>
    <label>Pega Service Endpoints</label>
</CustomObject>

src/objects/PegaService__c/fields/Create_Case__c.field-meta.xml
<CustomField>
    <fullName>Create_Case__c</fullName>
    <description>Create Case Service Endpoint</description>
    <label>Create Case</label>
    <type>Url</type>
</CustomField>

src/classes/PegaCreateCaseController.cls
global class PegaCreateCaseController {
    Webservice static string CreatePegaCase(Id pegaCaseId){
        system.debug('###Case '+pegaCaseId);
        String pegaId=null;
        PegaRequestWrapper pegaCreateCaseRequest=new PegaRequestWrapper();
        List<Case> caseList=new List<Case>();
        Case pega= new Case();
        Map<Id,User> groupMap=new Map<Id,User>([Select Id from user where Name='Pega']);
        pega=[SELECT Classification__c,RecordtypeId,CaseNumber,Additional_Web_Form_Info__c,Pega_Case_Id__c,Case_Ref_ID__c,Account_Name__c,Customer_Name__c,Customer_PO_RO_WONumber__c,Contact_Name__c,contact.Email,Customer_Request_Date__c,Honeywell_ID__c,Id,LastModifiedbyId,Owner.name,OwnerId,ParentId,Pega_Reason_for_Hold__c,Primary_Cell_Number__c,Primary_Email__c,Primary_Work_Number__c,Sales_Order_Number__c,SBU__c,Status,Part_Number__c,(SELECT FromAddress,Id,ParentId,Incoming,Status,Subject,TextBody,CCAddress,ToAddress,HtmlBody,hasAttachment,createdDate FROM EmailMessages where Incoming=true order by createdDate desc limit 1) FROM Case where id=:pegaCaseId];
        User toPega=[SELECT Id,name from User where Id=:pega.LastModifiedbyId];
        system.debug('Pega Case: '+pega);
        try{ 
            List<Id> EmailIds=new List<Id>();
            if(groupMap.containsKey(pega.ownerId) && pega.status!='Done'){
                for(EmailMessage email:pega.EmailMessages){
                    if(email.HasAttachment){
                        EmailIds.add(email.id); 
                    }
                }
                List<Attachment> allAttachments=new List<Attachment>();
                if(!emailIds.isEmpty()){
                    allAttachments=[Select id,Body,ContentType,Name,ParentId,BodyLength
                    from Attachment where ParentId=:EmailIds or ParentId=:pegaCaseId];
                }
                system.debug('allAttachmentssize'+allAttachments.size());
                system.debug('allAttachments'+allAttachments);
                Map<Id,List<Attachment>> attachMap=new Map<Id,List<Attachment>>();
                if(!allAttachments.isEmpty()){
                    for (Attachment a : allAttachments) {
                        if(a.BodyLength<=3200000){
                            if (attachMap.containsKey(a.parentId)) {
                                attachMap.get(a.parentId).add(a);
                            } else {
                                List<Attachment> mailList = new List<Attachment>();
                                mailList.add(a);
                                attachMap.put(a.parentId, mailList);
                            }
                        }
                    } 
                }
                System.debug('AttachMAP:'+attachMAP);
                //system.debug('Mail Content: '+pegaEmail);
                List<PegaRequestWrapper.CustomerEmail> customerEmailList=new List<PegaRequestWrapper.CustomerEmail>();
                pegaCreateCaseRequest.CaseNumber=pega.CaseNumber.subString(5);
                pegaCreateCaseRequest.CaseOwner=pega.Owner.Name;
                for(EmailMessage em:pega.EmailMessages){
                    PegaRequestWrapper.CustomerEmail customerEmail = new PegaRequestWrapper.CustomerEmail();
                    customerEmail.pyToString = em.ToAddress;
                    customerEmail.pyCCString= em.CcAddress;
                    customerEmail.pySubject=em.Subject;
                    customerEmail.pyFromUserID=em.FromAddress;
                    customerEmail.pyBody=em.HtmlBody; 
                    datetime strDT= em.CreatedDate;
                    string s = strDT.format('MMM dd, yyyy hh:mm:ss a');
                    customerEmail.pxSentDateTime=s;
                    List<PegaRequestWrapper.AttachmentList> ceAttach=new List<PegaRequestWrapper.AttachmentList>();
                    if(attachMap.get(em.id)!=null){      
                        List<Attachment> atList=attachMap.get(em.Parentid);// Modified for INC0000362303
                        for(Attachment a:atList){
                            PegaRequestWrapper.AttachmentList emAttach=new PegaRequestWrapper.AttachmentList();
                            emAttach.pxAttachName=a.Name;
                            emAttach.pyAttachStream=EncodingUtil.base64Encode(a.Body);
                            ceAttach.add(emAttach);
                        }
                    }
                    customerEmail.AttachmentList=ceAttach;
                    customerEmailList.add(customerEmail);
                }
                pegaCreateCaseRequest.customerEmail = customerEmailList;
                system.debug('PEga '+pegaCreateCaseRequest.caseowner);
                if(pega.Pega_Reason_for_Hold__c!=null){
                    pegaCreateCaseRequest.Casetype=pega.Pega_Reason_for_Hold__c;
                }
                else{
                    return Label.Pega_Reason_For_Hold_Message;
                }
                pegaCreateCaseRequest.CreatedBy=toPega.name;
                pegaCreateCaseRequest.CustContactName=pega.Contact_Name__c;
                pegaCreateCaseRequest.CustomerHoneywellID=pega.Part_Number__c;
                pegaCreateCaseRequest.Status=pega.Status;
                pegaCreateCaseRequest.CustomerPOROWONumber=pega.Customer_PO_RO_WONumber__c;
                if(pega.Contact.Email!=null){
                    pegaCreateCaseRequest.CustPrimaryEmail=pega.Contact.Email;      
                }
                else{
                    return Label.Pega_Customer_Email;
                }
                pegaCreateCaseRequest.CustPrimaryWorkNo=pega.Primary_Work_Number__c;
                if(pega.Sales_Order_Number__c!=null){
                    pegaCreateCaseRequest.CustomerSONumber=pega.Sales_Order_Number__c;
                }
                else{
                    return Label.Pega_Sales_Order_Number;
                }
                pegaCreateCaseRequest.WorkStream=pega.Classification__c;
                pegaCreateCaseRequest.AdditionalWebFormInfo=pega.Additional_Web_Form_Info__c; //  Added for INC0000157777
                pegaCreateCaseRequest.AccountSubType=pega.SBU__c;
                pegaCreateCaseRequest.CustomerName=pega.Account_Name__c;
                pegaCreateCaseRequest.SFDCCaseID=pega.Id;
                pegaCreateCaseRequest.CaseRefID=pega.Case_Ref_ID__c;
                pegaCreateCaseRequest.SFDCTransferID=Label.Pega_Transfer_Id;
                pegaCreateCaseRequest.CaseClosureID=Label.Pega_Closure_Id;
                String pegaRequestbody=JSON.serialize(pegaCreateCaseRequest);
                system.debug('Body: '+pegaRequestbody);

                HttpRequest req=new HttpRequest();
                req.setEndpoint(PegaService__c.getInstance('Endpoints').Create_Case__c);
                Blob headerValue = Blob.valueOf(PegaCredentials__c.getInstance('ServiceCredentials').Username__c + ':' + PegaCredentials__c.getInstance('ServiceCredentials').Password__c);
                String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
                req.setHeader('Authorization', authorizationHeader);
                req.setHeader('Content-Type','application/json');
                req.setMethod('POST');
                req.setBody(pegaRequestbody);
                Http h=new Http();
                HttpResponse res=h.send(req);
                System.debug(res.getBody());
                JSONParser parser = JSON.createParser(res.getBody());
                If(res.getStatusCode()==200){
                    while (parser.nextToken() != null) {
                        if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'Pega ID')) {
                            parser.nextToken();
                            pegaId = parser.getText();
                        }
                        if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'ErrorMessage')) {
                            parser.nextToken();
                            System.debug('Err: '+parser.getText());
                            String pegaErrMessage=parser.getText();
                            System.debug('@@Already'+pegaErrMessage);
                            if(pegaErrMessage.containsIgnoreCase('Already')){
                                pegaId=null;
                                System.debug('&&Enter already');
                                return Label.Pega_Case_Open_Already;
                            }
                        }
                        else if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'ErrorMessage')) {
                            parser.nextToken();
                            pegaId=null;
                            String pegaErrMessage=parser.getText();
                            if(!pegaErrMessage.containsIgnoreCase('Already') && pegaErrMessage!='NA'){
                                System.debug('&&OtherException');
                                return Label.Pega_Exception_Message;
                            }
                        }
                    }
                    if(pegaId!=null){
                        if(pega.Pega_Case_ID__c==null){
                            pega.Pega_Case_Id__c=pegaId;
                        }
                        else{
                            pega.Pega_Case_Id__c=pega.Pega_Case_Id__c+','+pegaId;
                        }
                        caseList.add(pega);
                    }
                    else{
                        return Label.Pega_Exception_Message;   
                    }
                    if(!caseList.isEmpty()){
                        update caseList;
                    }
                }
                else if(res.getStatusCode()!=200){
                    return Label.Pega_Exception_Message;
                }
                return Label.Pega_Success_Case_Creation;
            }
            else{
                return Label.Pega_Case_Owner_Message;
            }
        }
        catch(Exception e){
            return Label.Pega_Exception_Message; 
        }
    }
}