src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <description>Record Type Name of the Case Record</description>
    <formula>$RecordType.Name</formula>
    <label>Case Record Type</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/CSM_Category__c.field-meta.xml
<CustomField>
    <fullName>CSM_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADSB Out</fullName>
            </value>
            <value>
                <fullName>AFTMKT Programs</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>Availability/Delivery</fullName>
            </value>
            <value>
                <fullName>Cost of Parts</fullName>
            </value>
            <value>
                <fullName>Easy II Upgrade</fullName>
            </value>
            <value>
                <fullName>CRT to LCD Displays</fullName>
            </value>
            <value>
                <fullName>IFSD</fullName>
            </value>
            <value>
                <fullName>JetWave</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>LearJet 40/45</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Overall Tech Support</fullName>
            </value>
            <value>
                <fullName>PrimusElite &amp; CDSR Upgrade</fullName>
            </value>
            <value>
                <fullName>Responsiveness</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Tech Publications</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>VOC</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unscheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CSM_CSM__c.field-meta.xml
<CustomField>
    <fullName>CSM_CSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases6</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/CSM_Feedback_Case__c.field-meta.xml
<CustomField>
    <fullName>CSM_Feedback_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Feedback Case</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/CSM_Region__c.field-meta.xml
<CustomField>
    <fullName>CSM_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Asia/Pacific Rim</fullName>
            </value>
            <value>
                <fullName>EMEAI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/CSM_Senior_Escalation__c.field-meta.xml
<CustomField>
    <fullName>CSM_Senior_Escalation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Senior Escalation</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/CSM_Site_Name__c.field-meta.xml
<CustomField>
    <fullName>CSM_Site_Name__c</fullName>
    <label>Site Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>ACH AES - AT Airport Systems - Simi Valley</fullName>
            </value>
            <value>
                <fullName>ACH AES - AT - Airport Systems - Sun Valley</fullName>
            </value>
            <value>
                <fullName>ACH AES - AT - Lighting &amp; Electronics</fullName>
            </value>
            <value>
                <fullName>ACH AES - BRGA - Glendale</fullName>
            </value>
            <value>
                <fullName>ACH AES - BRGA - Sarasota</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Alliance</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Australia Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Dallas Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - France Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Ft. Lauderdale Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS HAT - Ft. Lauderdale</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS HAT - Phoenix</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Long Beach Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Ohio Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Phoenix</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Savannah Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Seattle Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - UK Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - CS - Wichita Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES Albuquerque</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Clearwater Space</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Glendale Space</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES Golden Valley</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Houston</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Minneapolis</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Phoenix Service Center</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Plymouth</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Redmond</fullName>
            </value>
            <value>
                <fullName>ACH AES - DSES - Roseville</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/OpenTask__c.field-meta.xml
<CustomField>
    <fullName>OpenTask__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OpenTask</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>RMU Name</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases (Product)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <formula>Product_Number__r.Description</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Also known as part description</inlineHelpText>
    <label>Product Description</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Also known as part number</inlineHelpText>
    <label>Product Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Product_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Part_Number__c</fullName>
    <label>Product Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <inlineHelpText>This field is mandatory for many business processes.  It is recommended that you populate this field prior to closing the case.  Coming soon: In December 2020, the resolution will be visible to customers on the portal.</inlineHelpText>
    <label>Resolution</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/SPEX_Exchange__c.field-meta.xml
<CustomField>
    <fullName>SPEX_Exchange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SPEX/Exchange</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Default_Case_Owner__c</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2/fields/Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Number__c</fullName>
    <externalId>true</externalId>
    <label>Product Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Products_CSM_Toolbox_Case__c/Products_CSM_Toolbox_Case__c.object-meta.xml
<CustomObject>
    <label>Products CSM Toolbox Case</label>
    <nameField>
        <displayFormat>CSM-{0000}</displayFormat>
        <label>CSM Toolbox Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products CSM Toolbox Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Products_CSM_Toolbox_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Products CSM Toolbox Cases</relationshipLabel>
    <relationshipName>Products_CSM_Toolbox_Cases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Products_CSM_Toolbox_Case__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products CSM Toolbox Cases</relationshipLabel>
    <relationshipName>Products_CSM_Toolbox_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Task.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tact</description>
    <label>Task</label>
</RecordType>

src/classes/CSM_AmericasReport_cls.cls
//SCTASK1154614 - adithya - Deleted the field AC type in all the case queries as per this task.
public class CSM_AmericasReport_cls {
    
    List<Id> caseids = new List<Id>();
    List<Id> caseids1 = new List<Id>();
        List<Products_CSM_Toolbox_Case__c> cproducts = new List<Products_CSM_Toolbox_Case__c>();
    List<List<Products_CSM_Toolbox_Case__c>> pids = new List<List<Products_CSM_Toolbox_Case__c>>();
    List<case> amercases  =new List<case>(); string serverUrl;
     
    public CSM_AmericasReport_cls(ApexPages.StandardController controller) {
        amercases = [select OpenTask__c,Description,id,CSM_Senior_Escalation__c,CaseNumber,CSM_CSM__c,CSM_CSM__r.name,
                    Account_Name__c,CSM_Category__c, CSM_Site_Name__c,Status,SPEX_Exchange__c,
                    Product_Number__c,Product_Description__c  from Case where 
                    ( Status ='Open' or (Status= 'Closed' and (ClosedDate = yesterday or ClosedDate = TODAY))) 
                    and Case_Record_Type__c = 'CSM Toolbox' and CSM_Region__c = 'Americas' and  
                    CSM_Feedback_Case__c = false and (lastmodifieddate = TODAY OR lastmodifieddate = YESTERDAY )
                    and createddate = LAST_N_DAYS:14
                    ORDER BY CSM_Senior_Escalation__c DESC];

        for(integer i=0;i<amercases.size();i++) {
         caseids1.add(amercases[i].Id);
        amercases[i].OpenTask__c=false;
        integer  taskcount=0;
        taskcount=[Select count() from Task where whatid =:amercases[i].Id and (lastmodifieddate = TODAY OR lastmodifieddate = YESTERDAY )];
        if(taskcount>0)
        amercases[i].OpenTask__c=true;
        caseids.add(amercases[i].Id);
        }
    }
    
   public List<Case> getamerrecords()
   {
 //amercases = [select Description,id,CSM_Senior_Escalation__c,CaseNumber,CSM_CSM__c,CSM_CSM__r.name,Account_Name__c,CSM_Category__c, CSM_Site_Name__c,Product_Part_Number__c,Status  from Case where ( Status ='Open' or (Status= 'Closed' and ClosedDate = yesterday)) and Case_Record_Type__c = 'CSM Toolbox' and CSM_Region__c = 'Americas' and  CSM_Feedback_Case__c = false and (lastmodifieddate = TODAY OR lastmodifieddate = YESTERDAY ) ];
   return amercases;
   }
   List<Task> ctasks = new List<Task>();
    public List<TAsk> gettasks()
   {
  
    ctasks = [select id,status,ACTIVITY_NUMBER__C,ownerid,description,whatid,Owner_Name__c,Description__c,ActivityDate,Completed_Date__c,Subject,Resolution__c  from Task where whatid in :caseids and (lastmodifieddate = TODAY OR lastmodifieddate = YESTERDAY ) ];
    return ctasks;
   }  
    public List<Products_CSM_Toolbox_Case__c> getproducts() {  
    cproducts=[Select Case__c,Product__r.Product_Number__c,Product__r.Description from Products_CSM_Toolbox_Case__c where Case__c =:caseids1];
            //if(productcoun>0)
     return cproducts;    
    } 
   public String getserverUrl()
    {
        serverUrl = URL.getSalesforceBaseUrl().toExternalForm() +'/';
        return serverUrl;
    }
    
   public boolean getshowcases()
   {
    if(amercases.size()>0) 
    {
     return true;
    }
    else
    {
     return false;
    }
   }
}