src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>Stores feedback data from various surveys</description>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FEE-{0}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If you change the Account Name you must select a Contact that it is associated with the newly selected Account. If you do not, the original Account will be visible upon Save.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>notContain</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Feedback</relationshipLabel>
    <relationshipName>Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Feedback__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Feedback</relationshipLabel>
    <relationshipName>Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Feedback__c/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <formula>TEXT( Contact__r.Contact_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Status</label>
    <type>Text</type>
</CustomField>

src/objects/Feedback__c/fields/Delivery_Customer_Rating__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Customer_Rating__c</fullName>
    <label>Delivery Customer Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blue - Best in Class</fullName>
                <color>#0B6FCE</color>
                <label>Blue - Best in Class</label>
            </value>
            <value>
                <fullName>Green - Satisfied</fullName>
                <color>#009900</color>
                <label>Green - Satisfied</label>
            </value>
            <value>
                <fullName>Yellow - Somewhat Dissatisfied</fullName>
                <color>#FFCC33</color>
                <label>Yellow - Somewhat Dissatisfied</label>
            </value>
            <value>
                <fullName>Red - Very Dissatisfied</fullName>
                <color>#FF0000</color>
                <label>Red - Very Dissatisfied</label>
            </value>
            <value>
                <fullName>Unspecified</fullName>
                <color>#999999</color>
                <label>Unspecified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Feedback__c/fields/Delivery_Weight__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Weight__c</fullName>
    <label>Delivery  Weight %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/objects/Feedback__c/fields/Repair_Performance__c.field-meta.xml
<CustomField>
    <fullName>Repair_Performance__c</fullName>
    <label>Repair Performance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Feedback__c/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Warranty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Feedback__c/recordTypes/NSS.recordType-meta.xml
<RecordType>
    <fullName>NSS</fullName>
    <active>true</active>
    <description>NSS survey record type</description>
    <label>NSS</label>
</RecordType>

src/objects/Planned_Meeting__c/Planned_Meeting__c.object-meta.xml
<CustomObject>
    <label>Planned Meeting</label>
    <nameField>
        <label>Planned Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planned Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Planned_Meeting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Contact_Name__r.Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

src/objects/Planned_Meeting__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feedback</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Planned Meetings</relationshipLabel>
    <relationshipName>Planned_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Planned_Meeting__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <description>This is a meeting for an Air/Trade Show or other Event.</description>
    <label>Meeting</label>
</RecordType>

src/classes/Planned_Meeting_Task_TestCls.cls
@isTest
private class Planned_Meeting_Task_TestCls{
static testMethod void Planned_Meeting_Task_TestMthd(){


//creating account;
 Account acc= new Account(name='Test Task Account');
 insert acc;
 
 //creating contact;
  Contact cont=new Contact(firstname='Test',LastName='Manager',AccountId=acc.Id,Phone_3__c='9986502445',
  Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E156767',email='anila.francis@wipro.com');
  insert cont;

  //Creating feedback
  Feedback__C fdd= new Feedback__C(Account__c=acc.id,contact__C=cont.Id,Delivery_Weight__c=100,Warranty__c='1',Repair_Performance__c ='1',Delivery_Customer_Rating__c='Blue - Best in Class');
        insert fdd;
  
  //creating case
 Case cases=new Case(AccountId=acc.Id,subject='Fax:{9986502495} test data',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
 //No_FCR_Reason__c='Not Trained',For Ticket INC000009687923
 Type='Order',Supported_Product__c='ADIRS',Catalog_Product_Group__c='Cabin(SV)',Product_Type__c='Electrical',Sub_Class__c='Contracts',Detail_Class__c='Bench Assistance', CSM_Feedback__c=fdd.id);
 insert cases;
//Creating Planned meeting
Planned_Meeting__c PlndMetng = new Planned_Meeting__c();
  PlndMetng.Name='Test';
  insert PlndMetng;
//creating task
  Task tasks= new Task (whatId=cases.Id, whoId=cont.Id, subject='NSS Survey - Follow Up', PRIORITY='Normal',Description='Testing',recordtypeid= label.Sales_Task_RT_ID);    
  insert tasks;   

ApexPages.StandardController controller= new ApexPages.StandardController(tasks);
System.currentPagereference().getParameters().put('id',tasks.id);
Planned_Meeting_Task_Cls PlndMtngTsk=new Planned_Meeting_Task_Cls();

PlndMtngTsk.getTaskRec();
PlndMtngTsk.setTaskRec();
string Txtdta=PlndMtngTsk.getTextData();
Txtdta=tasks.Description;
PlndMtngTsk.setTextData(Txtdta);
string CrtBy=PlndMtngTsk.getCretdBy();
CrtBy='Test';
PlndMtngTsk.setCretdBy(CrtBy);

PlndMtngTsk.getRelatTo();
PlndMtngTsk.getSubjctPickval();
PlndMtngTsk.getSubjectpiclstval();
PlndMtngTsk.getActionRst();
PlndMtngTsk.getClaimdAmnt();
PlndMtngTsk.getDueDte();
PlndMtngTsk.getCmpltDte();
PlndMtngTsk.getCompltddate();
PlndMtngTsk.getPaidAmnt();
PlndMtngTsk.getStatuspiclst();
PlndMtngTsk.getStatuspiclstval();
PlndMtngTsk.getPriortyPickval();
PlndMtngTsk.getPriortiypiclstval();
PlndMtngTsk.getTypePickval();
PlndMtngTsk.getTypepiclstval();
PlndMtngTsk.Save();
}

}