src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <formula>Text( Account.Strategic_Business_Unit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Bid_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Bid_Type_Name__c</fullName>
    <inlineHelpText>Bid type for this opportunity</inlineHelpText>
    <label>Bid Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bridge</fullName>
            </value>
            <value>
                <fullName>Competitive</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>LTA</fullName>
            </value>
            <value>
                <fullName>On Contract Growth</fullName>
            </value>
            <value>
                <fullName>Sole Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/CBT_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>CBT_Tier_2__c</fullName>
    <description>CBT Tier 2 is relabeled as CBT based on Business request. The source of the CBT is the Account CBT.</description>
    <inlineHelpText>CBT responsible for this opportunity</inlineHelpText>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACST-Connected Solutions</fullName>
            </value>
            <value>
                <fullName>ACST-E&amp;I</fullName>
            </value>
            <value>
                <fullName>ACST-Honeywell Quantum Solutions</fullName>
            </value>
            <value>
                <fullName>ACST-RTG</fullName>
            </value>
            <value>
                <fullName>ACST-Sustainability Technologies</fullName>
            </value>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
                <label>BendixKing</label>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DEW</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/IC_Scorecard_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>IC_Scorecard_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if Yes</inlineHelpText>
    <label>OE Focused Selling</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/Incumbent__c.field-meta.xml
<CustomField>
    <fullName>Incumbent__c</fullName>
    <inlineHelpText>Is Honeywell the incumbent on this opportunity?  Would we lose existing revenue if we lose?</inlineHelpText>
    <label>Incumbent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incumbent</fullName>
            </value>
            <value>
                <fullName>Non-Incumbent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/International_Code__c.field-meta.xml
<CustomField>
    <fullName>International_Code__c</fullName>
    <inlineHelpText>FMS Recapture - Used for EMEAI recapture of International Defense sales running through a US Govt</inlineHelpText>
    <label>International Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Domestic – HON</fullName>
            </value>
            <value>
                <fullName>FMS</fullName>
            </value>
            <value>
                <fullName>International - DIR</fullName>
            </value>
            <value>
                <fullName>International – HON</fullName>
            </value>
            <value>
                <fullName>International - INDIR</fullName>
            </value>
            <value>
                <fullName>International – Non-HON</fullName>
            </value>
            <value>
                <fullName>FMS recapture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Prime_Sub__c.field-meta.xml
<CustomField>
    <fullName>Prime_Sub__c</fullName>
    <inlineHelpText>Honeywell Role (prime)</inlineHelpText>
    <label>Prime/Sub</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Joint Venture</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Sub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <inlineHelpText>Revenue type of this opportunity</inlineHelpText>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ENG</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Repairs / Overhaul</fullName>
            </value>
            <value>
                <fullName>Retrofit</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Spares / AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/RMU__c.field-meta.xml
<CustomField>
    <fullName>RMU__c</fullName>
    <inlineHelpText>This opportunity supports an RMU. (Retrofit, Modification, or Upgrade)</inlineHelpText>
    <label>Offering</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <inlineHelpText>SBU responsible for this opportunity</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/RDF_CaseCreationController_Test.cls
/*********************************************
    Class Name       : RDF_CaseCreationController_Test
    Visualforce Page : RDF_CaseCreationPage
    Created On       : 19th July 2018
    Project          : RDF - One - Off Discount process
    Created By       : NTTDATA INC
    Purpose          : This extenstion controller is used to handle the Selection and Creation on Addresses in RMA Creation    
*********************************************/
@isTest
public class RDF_CaseCreationController_Test {
    static testmethod void validateCaseInsert(){
        Id devRecordTypeId = Schema.SObjectType.case.getRecordTypeInfosByName().get('One-Off Discount').getRecordTypeId();
         date testdate = date.parse('11/23/2017');
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Method Opportunity';
        opp.RecordTypeId = [SELECT id FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = 'AM Complex'].Id;
        opp.SBU__c = 'ATR';
        opp.CBT_Tier_2__c = 'Airbus';       
        opp.Prime_Sub__c = 'Prime';
        opp.StageName = 'Cultivate';
        opp.CloseDate = testdate;
        opp.Revenue_Type__c = 'ENG';
        opp.Bid_Type_Name__c = 'LTA';
        opp.International_Code__c = 'FMS';
        opp.Incumbent__c = 'Incumbent';
        opp.RMU__c = 'YES';
        opp.IC_Scorecard_Opportunity__c = false;
        insert opp;
        
        Case newcase = new Case();
        newcase.status = 'Open';
        newcase.recordtypeid = devRecordTypeId;
        insert newcase;
        
        Id currentRecordId  = ApexPages.CurrentPage().getparameters().put('id',opp.id);
        ApexPages.StandardController controller = new ApexPages.StandardController(newcase);
        RDF_CaseCreationController obj = new RDF_CaseCreationController(controller);
        obj.save();
    }
}