src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/APU_Workcenter__c.field-meta.xml
<CustomField>
    <fullName>APU_Workcenter__c</fullName>
    <label>APU Workcenter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Account.Type )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

src/objects/Case_Extension__c/Case_Extension__c.object-meta.xml
<CustomObject>
    <description>Extension of Case object</description>
    <label>Case Extension</label>
    <nameField>
        <label>Case Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Extension__c/fields/APU_Workcenter__c.field-meta.xml
<CustomField>
    <fullName>APU_Workcenter__c</fullName>
    <label>APU Workcenter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case_Extension__c/fields/Case_object__c.field-meta.xml
<CustomField>
    <fullName>Case_object__c</fullName>
    <label>Case object</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Extensions</relationshipLabel>
    <relationshipName>Case_Extensions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Case_Extension__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case_Extension__c/fields/IDS_OTTR_Date__c.field-meta.xml
<CustomField>
    <fullName>IDS_OTTR_Date__c</fullName>
    <description>This should be retrieved from the Notification</description>
    <label>IDS OTTR Date</label>
    <type>Date</type>
</CustomField>

src/objects/Case_Extension__c/fields/Notification_Number__c.field-meta.xml
<CustomField>
    <fullName>Notification_Number__c</fullName>
    <label>Notification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case_Extension__c/fields/Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Date__c</fullName>
    <description>System Integration</description>
    <label>Receipt Date</label>
    <type>Date</type>
</CustomField>

src/objects/Case_Extension__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case_Extension__c/fields/Warranty_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Accepted__c</fullName>
    <label>Warranty Accepted</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case_Extension__c/fields/Warranty_requested__c.field-meta.xml
<CustomField>
    <fullName>Warranty_requested__c</fullName>
    <label>Warranty requested</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case_Extension__c/fields/Warranty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Start_Date__c</fullName>
    <label>Warranty Start Date</label>
    <type>Date</type>
</CustomField>

src/objects/Z_Task__c/Z_Task__c.object-meta.xml
<CustomObject>
    <label>Task Activities</label>
    <nameField>
        <label>Z Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Z_Task__c/fields/APU_Workcenter__c.field-meta.xml
<CustomField>
    <fullName>APU_Workcenter__c</fullName>
    <formula>Case_Extension__r.APU_Workcenter__c</formula>
    <label>APU Workcenter</label>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/Case_Extension__c.field-meta.xml
<CustomField>
    <fullName>Case_Extension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Extension</label>
    <referenceTo>Case_Extension__c</referenceTo>
    <relationshipLabel>Task Activities</relationshipLabel>
    <relationshipName>Task_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Z_Task__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Long Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Z_Task__c/fields/Long_Text__c.field-meta.xml
<CustomField>
    <fullName>Long_Text__c</fullName>
    <label>Long Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Z_Task__c/fields/New_Long_Text__c.field-meta.xml
<CustomField>
    <fullName>New_Long_Text__c</fullName>
    <label>New Long Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Z_Task__c/fields/Notification_Number__c.field-meta.xml
<CustomField>
    <fullName>Notification_Number__c</fullName>
    <formula>HYPERLINK( &apos;https://arpwas.honeywell.com/sap/bc/gui/sap/its/webgui?=&amp;%7etransaction=IW53&amp;%7eokcode=/00&amp;=&amp;RIWO00-QMNUM=322484009&amp;sap-client=900&amp;sap-language=ENhttps://arpwas.honeywell.com/sap/bc/gui/sap/its/webgui?=&amp;%7etransaction=IW53&amp;%7eokcode=/00&amp;=&amp;RIWO00-QMNUM=&apos; + RelatedTo__r.Repair_Notification_Number__c+&apos;&amp;sap-client=900&amp;sap-language=EN&apos;, RelatedTo__r.Repair_Notification_Number__c )</formula>
    <label>Notification Number</label>
    <type>Text</type>
</CustomField>

src/objects/Z_Task__c/fields/RelatedTo__c.field-meta.xml
<CustomField>
    <fullName>RelatedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related To</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Task Activities</relationshipLabel>
    <relationshipName>Z_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Z_Task__c/fields/Requote_Reason__c.field-meta.xml
<CustomField>
    <fullName>Requote_Reason__c</fullName>
    <description>Dependent field on the Short Text field</description>
    <label>Requote Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSR - INCORRECT OR NO CONTRACT SELECTED</fullName>
            </value>
            <value>
                <fullName>CSR – PARTIAL (OR SPLIT) BILLING INCORRECT</fullName>
            </value>
            <value>
                <fullName>CSR - WARRANTY UPDATED ON EQUIPMENT RECORD</fullName>
            </value>
            <value>
                <fullName>CSR - WRONG TIER LEVEL SELECTED</fullName>
            </value>
            <value>
                <fullName>CUSTOMER - ADDITIONAL SB REQUESTED</fullName>
            </value>
            <value>
                <fullName>CUSTOMER – INCORRECT SB CHARGED</fullName>
            </value>
            <value>
                <fullName>CUSTOMER - WARRANTY REQUESTED NOW</fullName>
            </value>
            <value>
                <fullName>CUSTOMER - WORKSCOPE CHANGE</fullName>
            </value>
            <value>
                <fullName>CUSTOMER - WRONG CONTRACT SELECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Z_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Z_Task__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>Short Text Template</description>
    <label>Short Text Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>RAI - UFR No response</fullName>
            </value>
            <value>
                <fullName>RAI - Quote Denied</fullName>
            </value>
            <value>
                <fullName>RAI - Quote No response</fullName>
            </value>
            <value>
                <fullName>RAI - Customer Requested</fullName>
            </value>
            <value>
                <fullName>Resolve Unknown Customer</fullName>
            </value>
            <value>
                <fullName>Exchange Available</fullName>
            </value>
            <value>
                <fullName>PO review Pending</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – No Discrepancies Identified</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope Quote Reqd</fullName>
            </value>
            <value>
                <fullName>PO review complete</fullName>
            </value>
            <value>
                <fullName>Need Missing PO</fullName>
            </value>
            <value>
                <fullName>Need Missing Information</fullName>
            </value>
            <value>
                <fullName>Customer Dispute Price - Please review</fullName>
            </value>
            <value>
                <fullName>Please send Quote to Customer</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Sufficiently Priced</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope and Price Wrong</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope Incorrect</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – PO Workscope Wrong Price OK</fullName>
            </value>
            <value>
                <fullName>R&amp;OI – Workscope Price required</fullName>
            </value>
            <value>
                <fullName>Missing Price - Please Price</fullName>
            </value>
            <value>
                <fullName>Scrap - Customer requested</fullName>
            </value>
            <value>
                <fullName>Exchange price needed</fullName>
            </value>
            <value>
                <fullName>Customer Approved Exchange</fullName>
            </value>
            <value>
                <fullName>Customer Rejected Exchange</fullName>
            </value>
            <value>
                <fullName>Create Sales Order</fullName>
            </value>
            <value>
                <fullName>Need Missing Paperwork</fullName>
            </value>
            <value>
                <fullName>UFR - No quote Required</fullName>
            </value>
            <value>
                <fullName>FYI Quote Approved</fullName>
            </value>
            <value>
                <fullName>Contract Flate Rate- No Quote Required</fullName>
            </value>
            <value>
                <fullName>Quote Approved</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Z_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Z100 Return to Customer</fullName>
            </value>
            <value>
                <fullName>Z101 Resolve Unknown Customer</fullName>
            </value>
            <value>
                <fullName>Z102 Resolve Unknown Material</fullName>
            </value>
            <value>
                <fullName>Z103 Product Manufacturing Approval Required</fullName>
            </value>
            <value>
                <fullName>Z104 Exchange Available</fullName>
            </value>
            <value>
                <fullName>Z105 Review Repeat Return Candidate</fullName>
            </value>
            <value>
                <fullName>Z106 Order Review and Completion</fullName>
            </value>
            <value>
                <fullName>Z107 Order Information Required</fullName>
            </value>
            <value>
                <fullName>Z108 Review Customer Request Date</fullName>
            </value>
            <value>
                <fullName>Z109 Initial Evaluation Required</fullName>
            </value>
            <value>
                <fullName>Z110 Customer Quality Investigation Required</fullName>
            </value>
            <value>
                <fullName>Z111 Engineering Review Required</fullName>
            </value>
            <value>
                <fullName>Z112 Production Resource Tool Required</fullName>
            </value>
            <value>
                <fullName>Z113 Findings Required</fullName>
            </value>
            <value>
                <fullName>Z114 Pricing Review Required</fullName>
            </value>
            <value>
                <fullName>Z115 Estimate Review Required</fullName>
            </value>
            <value>
                <fullName>Z116 Warranty Review Required</fullName>
            </value>
            <value>
                <fullName>Z117 Product Quality Deficiency Record (PQDR)</fullName>
            </value>
            <value>
                <fullName>Z118 Purchasing Action Required</fullName>
            </value>
            <value>
                <fullName>Z119 Quality Review Required</fullName>
            </value>
            <value>
                <fullName>Z120 Inspection Required</fullName>
            </value>
            <value>
                <fullName>Z121 Final Buyoff Required</fullName>
            </value>
            <value>
                <fullName>Z122 Scrap Action/Review Required</fullName>
            </value>
            <value>
                <fullName>Z123 Export Review Required</fullName>
            </value>
            <value>
                <fullName>Z124 Shipping Container Required</fullName>
            </value>
            <value>
                <fullName>Z125 Freestock/Expense Material Required</fullName>
            </value>
            <value>
                <fullName>Z126 Exchange approved</fullName>
            </value>
            <value>
                <fullName>Z127 Exchange rejected</fullName>
            </value>
            <value>
                <fullName>Z128 Ready for Release</fullName>
            </value>
            <value>
                <fullName>Z129 OK to Proceed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Z_Task__c/fields/Z_Task__c.field-meta.xml
<CustomField>
    <fullName>Z_Task__c</fullName>
    <formula>SAP_ZTask_Number__c</formula>
    <label>Z Task</label>
    <type>Text</type>
</CustomField>

src/classes/NewZtaskPageCls.cls
public with sharing class NewZtaskPageCls {
    public Z_Task__c ZTask{get;set;}
    public string taskid{get;set;} 
    public string caseid{get;set;} 
    Public String Clone1;   
    public NewZtaskPageCls(ApexPages.StandardController controller) {
        Clone1= ApexPages.currentPage().getParameters().get('Cloneid'); 
        ZTask = new Z_Task__c();
        taskid = ApexPages.currentPage().getParameters().get('id');
        system.debug('Ztask.Status__c line 10'+Ztask.Status__c);
        system.debug('Ztask.SubType__c line 24'+Ztask.Sub_Type__c);
        //caseid=ApexPages.currentPage().getParameters().get('CF00N56000000VYtl_lkid');
        caseid=ApexPages.currentPage().getParameters().get(label.SI_TaskActivitiescaseno);
        User u = [select id,firstname,lastname,name,FederationIdentifier  from user where id=:userinfo.getuserid()]; 
        if(caseid !=null){
            ZTask.RelatedTo__c=caseid;       
        }
        ZTask.Ownerid=u.id;
        string FederationIdentifier='';
        if(u.FederationIdentifier != null)
        FederationIdentifier=+'('+u.FederationIdentifier+')';
        List<Case_Extension__c> sfdccaseext = [select id,APU_Workcenter__c,Warranty_requested__c,Warranty_Accepted__c,Warranty_Start_Date__c,Warranty_End_Date__c,Notification_Number__c,Receipt_Date__c,IDS_OTTR_Date__c from Case_Extension__c where Case_object__c=:caseId limit 1];
        if(sfdccaseext.size()>0)
        {
        ZTask.Case_Extension__c=sfdccaseext[0].id;
        }
      // ZTask.Comments__c=system.now()+' '+u.name+' '+FederationIdentifier;
        ZTask.Comments__c='';       
    }
    
    public pagereference CustomSave(){
        system.debug('Ztask.Status__c line 24'+Ztask.Status__c);
        User u = [select id,firstname,lastname,name,FederationIdentifier  from user where id=:userinfo.getuserid()];
        string FederationIdentifier='';
        if(u.FederationIdentifier != null)
        FederationIdentifier=+'('+u.FederationIdentifier+')';
        system.debug('Ztask.Status__c line 28'+Ztask.Status__c); 
        if(ZTask.Comments__c != null)
        {
            ZTask.Long_Text__c=system.now()+' '+u.name+' '+FederationIdentifier+ ' ' + ZTask.Requote_Reason__c +'\n'+ZTask.Comments__c;
            ZTask.New_Long_Text__c = ZTask.Comments__c;
            ZTask.Comments__c='';           
        }
        if(ZTask.Event_Type__c == null)
        {     
            system.debug('Ztask.Status__c line 38'+Ztask.Status__c);
            if(ZTask.Status__c != 'Closed')
            {
                ZTask.Event_Type__c = 'TASK CREATION';
            }
            
            else if(ZTask.Status__c == 'Closed')
            {
                system.debug('Ztask.Status__c line 47'+Ztask.Status__c);
                ZTask.Event_Type__c = 'TASK CLOSE';
            }
            
            else 
            {
                system.debug('Ztask.Status__c line 52'+Ztask.Status__c);
                ZTask.Event_Type__c = 'TASK CREATION';
            }
        }
        ZTask.Name=ZTask.type__c;
        ZTask.Task_Created_By__c=u.name;
        ZTask.Task_Created_Date_Time__c=system.now();
        system.debug('Ztask.Status__c line 57'+Ztask.Status__c);
        system.debug('shorttext---'+ZTask.Sub_Type__c); 
        if(ZTask.Sub_Type__c == null)
        {
            system.debug('inside shorttext---'+ZTask.Sub_Type__c); 
            ZTask.Sub_Type__c='';
        }
        insert ZTask;
        system.debug('Ztask----->'+ZTask);
        system.debug('Ztask1----->'+ZTask.Task_Created_By__c);
        system.debug('Ztask2----->'+ZTask.Task_Created_Date_Time__c);
        
                
        /*try{
            if(Clone1=='1')
            {
            ZTask.id = null;
            insert ZTask;
            }
            else
            {
            ZTask.Id = ZTask.id;
            Update ZTask;
            }
        }
        catch(Exception e){
        ApexPages.addMessages(e);
        return null;
        }*/     
        //Update ZTask;
        system.debug('ZTask.Status__c#######'+ZTask.Status__c);
        if(ZTask.Status__c =='Close Follow-Up Task')
        {
            system.debug('inside closed follow');
            ZTask.Status__c='Closed';
            Update ZTask; 
            PageReference pageRef= new PageReference('/apex/ZtaskEditPage?Cloneid='+1+'&id='+ZTask.id);
            pageRef.setRedirect(true); 
            return pageRef;
        }
        else
        {
            return new PageReference('/'+ZTask.id);
        }
    }
    public Void changeshorttext() {
        system.debug('inside chnageshorttext---'+ZTask.Sub_Type__c);        
        if(ZTask.Sub_Type__c != null)
        {   string ztasksubtype= ZTask.Sub_Type__c;
            string ztaskothersubtype= ZTask.Other_Short_Text__c;
            system.debug('ztasksubtype#####'+ztasksubtype);
            system.debug('(ZTask.Sub_Type__c#####'+ZTask.Sub_Type__c);
            if(ztasksubtype.contains('[Case #]'))
            {
                string casenumber='';
                string Createddate='';
                string FederationIdentifier='';             
                if(caseid != null)
                {
                    case c=[select id,casenumber from case where id=:caseid];
                    casenumber=c.casenumber;                    
                }
                User u = [select id,firstname,lastname,name,FederationIdentifier  from user where id=:userinfo.getuserid()]; 
                if(u.FederationIdentifier != null)
                FederationIdentifier='CBM '+u.FederationIdentifier;
                string FederationIdentifier1=FederationIdentifier;  
                string caseno=casenumber;
                string subtype=ZTask.Sub_Type__c;               
                system.debug('venkattest------>'+subtype);
                String repl = subtype.replace('[Case #]',caseno);
                String repl1 = repl.replaceAll('Date',' ');
                String repl2 = repl1.replaceAll('date',' ');
                if(repl2.contains('CBM EID'))
                {                   
                    String repl3 = repl2.replaceAll('CBM EID',FederationIdentifier1);
                    string subtype1 = repl3;
                    system.debug('venkattest11111------>'+subtype1);
                    ZTask.Short_Text__c = subtype1+system.now();
                }
                else
                {
                string subtype1 = repl2;
                system.debug('venkattest11111------>'+subtype1);
                ZTask.Short_Text__c = subtype1+system.now();
                }               
            }
            else if(ztasksubtype == 'Other')
            {
                if(ztaskothersubtype != null)
                {
                   ZTask.Short_Text__c = ztaskothersubtype;
                }
                else
                {
                    ZTask.Short_Text__c = ztasksubtype;
                }
            }
            else
            {
                ZTask.Short_Text__c = ztasksubtype;
            }           
        }
        else
        {
            ZTask.Short_Text__c = '';
            system.debug('venkattestZTask.Short_Text__c------>'+ZTask.Short_Text__c);
        }       
    }
}