src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Field_Event__c.field-meta.xml
<CustomField>
    <fullName>Field_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Event</label>
    <referenceTo>Field_Event__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Field_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Marketing Engaged</fullName>
            </value>
            <value>
                <fullName>With Telemarketing</fullName>
            </value>
            <value>
                <fullName>Assigned - Target Team</fullName>
            </value>
            <value>
                <fullName>Working - Target Team</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>With Customer Marketing</fullName>
            </value>
            <value>
                <fullName>Working - Contacted</fullName>
            </value>
            <value>
                <fullName>Closed - Existing Opportunity</fullName>
            </value>
            <value>
                <fullName>Closed - No Project Now</fullName>
            </value>
            <value>
                <fullName>Closed - Converted (Qualified)</fullName>
            </value>
            <value>
                <fullName>Redirected - Channel Sales</fullName>
            </value>
            <value>
                <fullName>Closed - Competitor</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid Contact</fullName>
            </value>
            <value>
                <fullName>Redirected - LGS</fullName>
            </value>
            <value>
                <fullName>Sent to Partner</fullName>
            </value>
            <value>
                <fullName>Redirected - Partner Sales Manager</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Assigned - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Working - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Contacted - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Handoff</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Converted to Opportunity</fullName>
            </value>
            <value>
                <fullName>Converted To Contact</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Field_Event__c/Field_Event__c.object-meta.xml
<CustomObject>
    <label>Field Event</label>
    <nameField>
        <displayFormat>FE-{0}</displayFormat>
        <label>Field Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Field_Event__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Field Events</relationshipLabel>
    <relationshipName>Field_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Service_Recovery_Report__c/Service_Recovery_Report__c.object-meta.xml
<CustomObject>
    <label>Service Recovery Report</label>
    <nameField>
        <displayFormat>SRR-{0}</displayFormat>
        <label>Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Recovery Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Recovery_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Awarded - Won</fullName>
            </value>
            <value>
                <fullName>Awarded - Lost</fullName>
            </value>
            <value>
                <fullName>Service No Longer Needed</fullName>
            </value>
            <value>
                <fullName>No Bid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Recovery_Report_Team_Members__c/Service_Recovery_Report_Team_Members__c.object-meta.xml
<CustomObject>
    <label>Service Recovery Report Team Member</label>
    <nameField>
        <displayFormat>SRRTM-{00000000}</displayFormat>
        <label>SRR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Recovery Report Team Member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Recovery_Report_Team_Members__c/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <formula>Contact_Name__r.Employee_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Number</label>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>SR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>&quot;Open&quot;: Investigation is active or fix is in work.
&quot;Closed&quot;: Issue has been resolved or completed.
&quot;Monitor&quot;: Issue is waiting for additional information from customer or there is a request for issue to be monitored.
&quot;Queue&quot;: SR awaiting to be assigned</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Containment</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>RCCA</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/CSO_GTO_Test_ApexClass4.cls
/** * File Name: CSO/GTO_Test_ApexClass4
* Description Test Method
* Copyright : Wipro Technologies Limited Copyright (c) 2010
* * @author : Wipro
* Modification History  :
* Date             Version No.    Modified by           Brief Description of Modification
* Nov-08-2013      1.0            Anusuy Murugiah       Wrapping the testmethod with Start and Stop
* */
@isTest (seealldata = true)
private  class CSO_GTO_Test_ApexClass4 {
static testmethod void testCallCenter(){





//creating account;
// Account acc= new Account(name='Test Account');
// insert acc;
 
 //creating contact;
 //Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495',
  //Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='567' );
 Contact cont=[select id,AccountId from contact where Contact_Status__c='Active' and Employee_Contact_Role__c='Analyst' limit 1];
 //insert cont;

 //creating case
 Case cases=new Case(AccountId=cont.AccountId,subject='Fax:{9986502495} test data',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
 //No_FCR_Reason__c='Not Trained',For Ticket INC000009687923
 Type='Order');
 insert cases;
 //test.starttest();
List<Service_Request__c> SRs= new  List<Service_Request__c>();
//List<Field_Event__c> FEs =new List<Field_Event__c>();
List< Service_Recovery_Report__c> SRRs= new List< Service_Recovery_Report__c>();
 //creating service requests
 Service_Request__c SR= new Service_Request__c(Case_Number__c=cases.Id);
 SRs.add(SR);
 Service_Request__c SRNew= new Service_Request__c(Contact_Name__c=cont.Id);
 SRs.add(SRNew);
 insert SRs;
 //creating service request report
 Service_Recovery_Report__c SRR= new Service_Recovery_Report__c(Case_Number__c=cases.Id,status__C='In Process');
 SRRs.add(SRR);
 Service_Recovery_Report__c SRRNew= new Service_Recovery_Report__c(Contact_Name__c=cont.Id);
 SRRs.add(SRRNew);
 insert SRRs;
 SRR.status__c='Awarded - Lost';
 update SRR;
 Test.startTest();
 Service_Recovery_Report_Team_Members__c  SRRTeam = new Service_Recovery_Report_Team_Members__c(Is_Primary_Team_member__c=true,
 Service_Recovery_Report__c=SRR.Id,Contact_Name__c=cont.Id);
 insert SRRTeam;
 Service_Recovery_Report_Team_Members__c  SRRTeam1 = new Service_Recovery_Report_Team_Members__c(Is_Primary_Team_member__c=true,
 Service_Recovery_Report__c=SRR.Id,Contact_Name__c=cont.Id);
 Service_Recovery_Report_Team_Members__c  SRRTeam2 = new Service_Recovery_Report_Team_Members__c(
 Service_Recovery_Report__c=SRR.Id);
 insert SRRTeam2;
 try{
 insert SRRTeam1;}
 catch(Exception e){}

SRRTeam.Is_Primary_Team_member__c=false;
update SRRTeam;
 SRRTeam.Is_Primary_Team_member__c=true;
update SRRTeam;
  delete SRRTeam;
test.stoptest(); 
  }
  }