src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <description>Record Type Name of the Case Record</description>
    <formula>$RecordType.Name</formula>
    <label>Case Record Type</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Customer_PO_RO_WONumber__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_RO_WONumber__c</fullName>
    <description>Text Field used to hold the PO number. 
05/22 - Set to external ID for PO/SN deployment to avoid 554 connection error in Salesforce</description>
    <externalId>true</externalId>
    <label>Customer PO/RO/WO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Reason_for_hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_hold__c</fullName>
    <description>Used for Order record type</description>
    <label>Reason for Hold</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Sub_Status__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2020 CONTRACT PRICING-CONTRACT ESCALATION</fullName>
            </value>
            <value>
                <fullName>2020 CONTRACT PRICING- PO UPDATE REQUESTED</fullName>
            </value>
            <value>
                <fullName>2020 CONTRACT PRICING - SO REVIEW</fullName>
            </value>
            <value>
                <fullName>777 Expedite</fullName>
            </value>
            <value>
                <fullName>8130/EASA/CAAC/Certification Correction</fullName>
            </value>
            <value>
                <fullName>8130/EASA/CAAC/Certification Missing</fullName>
            </value>
            <value>
                <fullName>8130 TAG</fullName>
            </value>
            <value>
                <fullName>A/C Details</fullName>
            </value>
            <value>
                <fullName>ACAT approval</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Access Class</fullName>
            </value>
            <value>
                <fullName>Account Block Status</fullName>
            </value>
            <value>
                <fullName>Account Change: Bill To</fullName>
            </value>
            <value>
                <fullName>Account Change: Carrier</fullName>
            </value>
            <value>
                <fullName>Account Change: End User Details</fullName>
            </value>
            <value>
                <fullName>Account Change: Extend Sales Org</fullName>
            </value>
            <value>
                <fullName>Account Change: Name/Address</fullName>
            </value>
            <value>
                <fullName>Account Change: Payer</fullName>
            </value>
            <value>
                <fullName>Account Change: Ship To</fullName>
            </value>
            <value>
                <fullName>Account Creation - Bill To</fullName>
            </value>
            <value>
                <fullName>Account Creation - Ship To</fullName>
            </value>
            <value>
                <fullName>Account Creation - Sold To</fullName>
            </value>
            <value>
                <fullName>Account Edit - Bill To</fullName>
            </value>
            <value>
                <fullName>Account Edit - Ship To</fullName>
            </value>
            <value>
                <fullName>Account Edit - Sold To</fullName>
            </value>
            <value>
                <fullName>ACES Issues</fullName>
            </value>
            <value>
                <fullName>ACN#</fullName>
            </value>
            <value>
                <fullName>Add customer sold-to</fullName>
            </value>
            <value>
                <fullName>Add Customer Sold To/Sales Office</fullName>
            </value>
            <value>
                <fullName>Add Flowdown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1st Follow-up</fullName>
            </value>
            <value>
                <fullName>2nd Follow-up</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Accelerated Repair</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>Accts</fullName>
            </value>
            <value>
                <fullName>Acknowledgement Provided</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Administrative Hold -Z8</fullName>
            </value>
            <value>
                <fullName>Advanced Troubleshooting</fullName>
            </value>
            <value>
                <fullName>After-exp queue</fullName>
            </value>
            <value>
                <fullName>AIDC Quote Hold</fullName>
            </value>
            <value>
                <fullName>Aircraft In Maintenance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>ATS</fullName>
            </value>
            <value>
                <fullName>ATS (Tech Support) Hold</fullName>
            </value>
            <value>
                <fullName>Aviation Services</fullName>
            </value>
            <value>
                <fullName>Awaiting Amended PO-Z2</fullName>
            </value>
            <value>
                <fullName>Awaiting billing review</fullName>
            </value>
            <value>
                <fullName>Awaiting Client reply for more info</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Verification</fullName>
            </value>
            <value>
                <fullName>Awaiting credit review</fullName>
            </value>
            <value>
                <fullName>Awaiting MSP review</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting reply from ICARUS</fullName>
            </value>
            <value>
                <fullName>AWB Sent</fullName>
            </value>
            <value>
                <fullName>B/E Quote Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/VN_Name__c.field-meta.xml
<CustomField>
    <fullName>VN_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escalated To (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You have selected an inactive contact in the Escalated To (Contact) field. Select an active contact to be able to save the case.</errorMessage>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$User.Profile_Name__c</field>
            <operation>equals</operation>
            <value>API DATA LOAD</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (VN Name)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Escalations_and_Holds__c/Escalations_and_Holds__c.object-meta.xml
<CustomObject>
    <label>Escalations and Holds</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>Escalations and Holds</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalations and Holds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Escalations_and_Holds__c/fields/Automate__c.field-meta.xml
<CustomField>
    <fullName>Automate__c</fullName>
    <label>Automate</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Escalations_and_Holds__c/fields/Reason_for_Hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Hold__c</fullName>
    <label>Reason for Hold</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2020 Contract Pricing-Contract Escalation</fullName>
            </value>
            <value>
                <fullName>2020 Contract Pricing-SO Review</fullName>
            </value>
            <value>
                <fullName>777 Expedite</fullName>
            </value>
            <value>
                <fullName>8130/EASA/CAAC/CERTIFICATION CORRECTION</fullName>
            </value>
            <value>
                <fullName>8130/EASA/CAAC/CERTIFICATION MISSING</fullName>
            </value>
            <value>
                <fullName>ACAT NEEDED</fullName>
            </value>
            <value>
                <fullName>ACCOUNT BLOCK STATUS</fullName>
            </value>
            <value>
                <fullName>ACCOUNT CHANGE: BILL TO</fullName>
            </value>
            <value>
                <fullName>ACCOUNT CHANGE: CARRIER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT CHANGE: END USER DETAILS</fullName>
            </value>
            <value>
                <fullName>ACCOUNT CHANGE: EXTEND SALES OG</fullName>
            </value>
            <value>
                <fullName>ACCOUNT CHANGE: NAME/ADDRESS</fullName>
            </value>
            <value>
                <fullName>ACCOUNT CHANGE: SHIP TO</fullName>
            </value>
            <value>
                <fullName>ACES ISSUE</fullName>
            </value>
            <value>
                <fullName>ACES ISSUES</fullName>
            </value>
            <value>
                <fullName>ACN#</fullName>
            </value>
            <value>
                <fullName>ADD CUSTOMER SOLD TO/SALES OFFICE</fullName>
            </value>
            <value>
                <fullName>ADD PART NUMBER TO CONTRACT</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT DETAILS</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - CONTRACT PRICING</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - HONEYWELL ADDRESS</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - LIST PRICING</fullName>
            </value>
            <value>
                <fullName>AMENDED PO- LIST PRICING</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - MINIMUM ORDER QUANTITY</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - MTO PRICING</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - PART NUMBER</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - SERIAL NUMBER</fullName>
            </value>
            <value>
                <fullName>AMENDED PO - TERMS AND CONDITIONS</fullName>
            </value>
            <value>
                <fullName>APM ORDER REVIEW</fullName>
            </value>
            <value>
                <fullName>APM PN ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Escalations_and_Holds__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S&amp;C</fullName>
            </value>
            <value>
                <fullName>BUSINESS HOLD</fullName>
            </value>
            <value>
                <fullName>CONTRACT ADMIN HOLD</fullName>
            </value>
            <value>
                <fullName>CSO HOLD</fullName>
            </value>
            <value>
                <fullName>CUSTOMER HOLD</fullName>
            </value>
            <value>
                <fullName>CUSTOMER MASTER HOLD</fullName>
            </value>
            <value>
                <fullName>ENGINEERING HOLD</fullName>
            </value>
            <value>
                <fullName>EXPORT HOLD</fullName>
            </value>
            <value>
                <fullName>FINANCE HOLD</fullName>
            </value>
            <value>
                <fullName>IMPORT HOLD</fullName>
            </value>
            <value>
                <fullName>INTEGRATED SUPPLY CHAIN HOLD</fullName>
            </value>
            <value>
                <fullName>PMO HOLD</fullName>
            </value>
            <value>
                <fullName>QUALITY HOLD</fullName>
            </value>
            <value>
                <fullName>SAP/IT SUPPORT HOLD</fullName>
            </value>
            <value>
                <fullName>WARRANTY HOLD</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>PRICING HOLD</fullName>
            </value>
            <value>
                <fullName>CONTRACT MANAGER HOLD</fullName>
            </value>
            <value>
                <fullName>MTO HOLD</fullName>
            </value>
            <value>
                <fullName>SPEX C&amp;PS</fullName>
            </value>
            <value>
                <fullName>GBE HOLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/CaseEscalationController.cls
/*****************************************************
Name         : CaseEscalationController
Test Class	 : CaseEscalationController_Test
Created By   : Mahesh M
Created Date : 05-03-2021
Usages       : This Class is used for Case Escalation Component.  
*****************************************************/
public class CaseEscalationController {
 @AuraEnabled
     public static Boolean returnvalue(id coid, string substatus, string reasonhold, list<Object> filesToInsert){     
        Case cse = new case(); 
        Boolean istrue = false;
        list<Escalations_and_Holds__c> tsk = new list<Escalations_and_Holds__c>();
        list<Escalations_and_Holds__c> tsks = new list<Escalations_and_Holds__c>();
        String escrecordtype;
        cse = [select id,Customer_PO_RO_WONumber__c, OwnerId,Status,Sub_Status__c,VN_Name__c, Reason_for_hold__c,Case_Record_Type__c from case where id =: coid limit 1];
            system.debug('case cse== ' + cse);
         	System.debug('VN_Name__c=='+cse.VN_Name__c);
         if(cse.VN_Name__c == null){
             throw new AuraHandledException('Please enter value for Escalated To (Contact)');
         }
         String csownid = cse.OwnerId;
         System.debug('csownid::'+csownid);
         if(csownid.startsWith('00G')){
                throw new AuraHandledException('Case Owner Cannot be Queue. It should be User for auto escalations');
         }
            escrecordtype = cse.Case_Record_Type__c;
        
        tsk = [select id,Sub_Status__c,Automate__c,Case_Type__c,Reason_for_Hold__c from Escalations_and_Holds__c where Sub_Status__c =:substatus AND Reason_for_Hold__c =:reasonhold AND Case_Type__c =:escrecordtype];
        //tsks = [select id,Sub_Status__c,Automate__c,Case_Type__c,Reason_for_Hold__c from Escalations_and_Holds__c where Sub_Status__c =:substatus AND Reason_for_Hold__c =:reasonhold AND Case_Type__c =:escrecordtype AND Automate__c ='No'];
        system.debug(tsk);
        system.debug(tsk.size());        
        if(tsk.size() == 0){
            istrue = true;
        }
        
       else if(tsk.size() != 0){
           for(Escalations_and_Holds__c esh: tsk){
               if(esh.Automate__c == 'No'){
                   istrue = true;
               }
           }
        }
        system.debug(istrue);
        List<ContentVersion> lstConVer = new List<ContentVersion>();
        if(filesToInsert != null){
        for (Object file : filesToInsert) {
            FileInfo fileData = (FileInfo)JSON.deserialize(JSON.serialize(file), FileInfo.class);
            system.debug('fileData.Title: '+fileData.Title);
            system.debug('fileData.VersionData: '+fileData.VersionData);
            ContentVersion objCntVersion = new ContentVersion();
            objCntVersion.PathOnClient = fileData.Title;
            objCntVersion.Title = reasonhold+'-'+fileData.Title;
            objCntVersion.VersionData = fileData.VersionData;
            lstConVer.add(objCntVersion);
         }
        
        system.debug('lstConVer : '+lstConVer.size());
        if(lstConVer != null && lstConVer.size()>0){
            system.debug('content Version bef insert::'+lstConVer);
            insert lstConVer;
            system.debug('Content Version aft insert'+lstConVer);
        }
        set<id> setConvID = new set<id>();
        for(ContentVersion objCon1 : lstConVer){
            if(objCon1 != null){
                setConvID.add(objCon1.Id);
            }
        }
        system.debug('setConvID: '+setConvID);
        List<ContentDocumentlink> lstConDoclink = new List<ContentDocumentLink>();
        
        if(setConvID != null && setConvID.size()>0){
            for(ContentVersion objCon : [SELECT Id,Title,ContentDocumentId from ContentVersion where Id IN: setConvID AND IsLatest = true]){
                ContentDocumentlink objCDL = new ContentDocumentlink();
                objCDL.ContentDocumentId = objCon.ContentDocumentId;
                objCDL.linkedentityId = coid;
                objCDL.Sharetype = 'I';
                lstConDoclink.add(objCDL);
           }
        }
        if(lstConDoclink != null && lstConDoclink.size()>0){
            Insert lstConDoclink;  
            system.debug('check::::::'+lstConDoclink);
        }
        }
        CaseEscalationForHolds.sendescalatedemailFirstEscalation(coid);
        return istrue;

    }
    public class FileInfo {
        @AuraEnabled
        public String Title {get;set;}
        @AuraEnabled
        public Blob VersionData {get;set;}
    }
}