src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <description>Record Type Name of the Case Record</description>
    <formula>$RecordType.Name</formula>
    <label>Case Record Type</label>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Internal_HW_Action__c.field-meta.xml
<CustomField>
    <fullName>Internal_HW_Action__c</fullName>
    <label>Internal HW Action</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1st Follow-up</fullName>
            </value>
            <value>
                <fullName>2nd Follow-up</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Accelerated Repair</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>Accts</fullName>
            </value>
            <value>
                <fullName>Acknowledgement Provided</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Administrative Hold -Z8</fullName>
            </value>
            <value>
                <fullName>Advanced Troubleshooting</fullName>
            </value>
            <value>
                <fullName>After-exp queue</fullName>
            </value>
            <value>
                <fullName>AIDC Quote Hold</fullName>
            </value>
            <value>
                <fullName>Aircraft In Maintenance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>ATS</fullName>
            </value>
            <value>
                <fullName>ATS (Tech Support) Hold</fullName>
            </value>
            <value>
                <fullName>Aviation Services</fullName>
            </value>
            <value>
                <fullName>Awaiting Amended PO-Z2</fullName>
            </value>
            <value>
                <fullName>Awaiting billing review</fullName>
            </value>
            <value>
                <fullName>Awaiting Client reply for more info</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Verification</fullName>
            </value>
            <value>
                <fullName>Awaiting credit review</fullName>
            </value>
            <value>
                <fullName>Awaiting MSP review</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting reply from ICARUS</fullName>
            </value>
            <value>
                <fullName>AWB Sent</fullName>
            </value>
            <value>
                <fullName>B/E Quote Hold</fullName>
            </value>
            <value>
                <fullName>Business Hold</fullName>
            </value>
            <value>
                <fullName>Contract Hold</fullName>
            </value>
            <value>
                <fullName>Engineering Hold</fullName>
            </value>
            <value>
                <fullName>Export Hold</fullName>
            </value>
            <value>
                <fullName>Integrated Supply Chain Hold</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Quality Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <description>BM 8/11/12 - Created for MSP HAPP Projects - Classification for Contract. Parent to Sub-Classification constrained picklist
KH 9/12/2013 - added picklist values for NavDB and GDC</description>
    <inlineHelpText>Classification for Contract. Parent to Sub-Classification constrained picklist</inlineHelpText>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>GSE Tools</fullName>
            </value>
            <value>
                <fullName>New Aircraft enrollment</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Transfer inbound</fullName>
            </value>
            <value>
                <fullName>Transfer outbound</fullName>
            </value>
            <value>
                <fullName>Transfer to bank</fullName>
            </value>
            <value>
                <fullName>Waiting sale</fullName>
            </value>
            <value>
                <fullName>Internal Purchase</fullName>
            </value>
            <value>
                <fullName>Misc</fullName>
            </value>
            <value>
                <fullName>Shipping Issue</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contract/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>BM 8/11/12 - Created for MSP HAPP Project. This is a constrained picklist tied to Status.
BM 7/22/2013 - added missing SAP Sub-Status options and updated constrained pick accordingly - for Services SFDC Interfaces project</description>
    <inlineHelpText>This is a constrained picklist tied to Status.</inlineHelpText>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Transfer Request Received – HON</fullName>
            </value>
            <value>
                <fullName>Transfer Package Sent – Customer</fullName>
            </value>
            <value>
                <fullName>Contract Returned – HON</fullName>
            </value>
            <value>
                <fullName>Contract Returned – Customer</fullName>
            </value>
            <value>
                <fullName>Input to SAP – In Process</fullName>
            </value>
            <value>
                <fullName>Input to SAP – Pending Info</fullName>
            </value>
            <value>
                <fullName>Back from Input – HON</fullName>
            </value>
            <value>
                <fullName>Renewal package Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Renewal package Sent to Dealer</fullName>
            </value>
            <value>
                <fullName>Contract Returned – Awaiting PO</fullName>
            </value>
            <value>
                <fullName>On hold with Dealer</fullName>
            </value>
            <value>
                <fullName>PO Req Sent</fullName>
            </value>
            <value>
                <fullName>PO # Received</fullName>
            </value>
            <value>
                <fullName>Invoice Sent - Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Prior Auth Req</fullName>
            </value>
            <value>
                <fullName>Loss</fullName>
            </value>
            <value>
                <fullName>Suspended non-payment</fullName>
            </value>
            <value>
                <fullName>Bad Request (Cancelled)</fullName>
            </value>
            <value>
                <fullName>Customer Loss</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Insufficient Data</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Reply</fullName>
            </value>
            <value>
                <fullName>In Transfer</fullName>
            </value>
            <value>
                <fullName>Sale Pending</fullName>
            </value>
            <value>
                <fullName>Termination Pending</fullName>
            </value>
            <value>
                <fullName>Renewal Not Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/setCaseStatusOpen.cls
/**********************************Change Log******************************** 
Tikcet : INC000006437197
Object - Case
Description:
Sent cases status to Open and send alerts to case owners
****************************************************************************/
global class setCaseStatusOpen implements Database.batchable<sObject>, Schedulable{
    global string query;
        
    global setCaseStatusOpen(){
        //Query to fetch cases of GDC Tech Issue records
        query = 'select id,Classification__c,Sub_Status__c, status,Internal_HW_Action__c,ownerid,CaseNumber from Case where (Case_Record_Type__c= \'D&S Quotes Orders\' or Case_Record_Type__c= \'Repair & Overhaul\') and status=\'On Hold\' and (Classification__c= \'CSO D&S Repair\' or Classification__c= \'CSO D&S Internal\') and lastmodifieddate <= YESTERDAY and lastmodifieddate >= LAST_N_DAYS:2';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);     
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Case> listReminderCases = new List<Case>();
        List<Case> listCaseUpdates = new List<Case>();
        system.debug('----> scope' + scope);
        for(sObject caseRec : scope)
        {   
            case caseRec1 = (case)caseRec;
            if(caseRec1.Sub_Status__c =='Business Hold' || caseRec1.Sub_Status__c =='Integrated Supply Chain Hold' || caseRec1.Sub_Status__c =='Quality Hold' || caseRec1.Sub_Status__c =='Contract Hold' || caseRec1.Sub_Status__c =='Export Hold' || caseRec1.Sub_Status__c =='Engineering Hold'){
                caseRec1.status = 'Open';
                listCaseUpdates.add(caseRec1); 
                listReminderCases.add(caseRec1);
            }
        }
        try{
            if(listCaseUpdates.size() > 0){
                update listCaseUpdates;
            }
        }catch(Exception ex){
            system.debug('Error from setCaseStatusOpen--->' + ex.getMessage());
        }   
        
        List<Messaging.SingleEMailMessage>  mails = new List<Messaging.SingleEMailMessage>(); 
        system.debug('---->reminders' + listReminderCases);
        string msgBody = 'status has been changed to Open. Please provide an Internal Honeywell Action and notify the action owner via email using the appropriate Honeywell Internal Action template.';
        string msgSubject = '- Status has been changed to Open';
        for(Case orderCase : listReminderCases){
            if(string.valueof(orderCase.ownerid).startswith('00G') == false && (orderCase.Internal_HW_Action__c == null || orderCase.Internal_HW_Action__c == '')){  
                Messaging.SingleEMailMessage mail = new Messaging.SingleEMailMessage();
                mail.setOrgWideEmailAddressId(label.AeroNo_Reply_email_ID);
                mail.setTargetObjectId(orderCase.ownerid);
                string msgBodyNew = orderCase.CaseNumber + ' '+ msgBody;
                string msgSubjectNew = orderCase.CaseNumber + ' '+ msgSubject;
                mail.setSubject(msgSubjectNew);
                mail.setPlainTextBody(msgBodyNew);
                mail.setSaveAsActivity(false);
                mails.add(mail);
            }
        }
        Messaging.sendEmail(mails);
    }
    
    global void finish(Database.BatchableContext BC){} 
    
    global void execute(SchedulableContext sc){
        setCaseStatusOpen ordersBatch = new setCaseStatusOpen();
        database.executeBatch(ordersBatch,200);
    }
}