src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Additional_Web_Form_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Web_Form_Info__c</fullName>
    <label>Additional Web Form Info</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <label>Honeywell ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1st Follow-up</fullName>
            </value>
            <value>
                <fullName>2nd Follow-up</fullName>
            </value>
            <value>
                <fullName>ACAT Needed</fullName>
            </value>
            <value>
                <fullName>Accelerated Repair</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>Accts</fullName>
            </value>
            <value>
                <fullName>Acknowledgement Provided</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Administrative Hold -Z8</fullName>
            </value>
            <value>
                <fullName>Advanced Troubleshooting</fullName>
            </value>
            <value>
                <fullName>After-exp queue</fullName>
            </value>
            <value>
                <fullName>AIDC Quote Hold</fullName>
            </value>
            <value>
                <fullName>Aircraft In Maintenance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>ATS</fullName>
            </value>
            <value>
                <fullName>ATS (Tech Support) Hold</fullName>
            </value>
            <value>
                <fullName>Aviation Services</fullName>
            </value>
            <value>
                <fullName>Awaiting Amended PO-Z2</fullName>
            </value>
            <value>
                <fullName>Awaiting billing review</fullName>
            </value>
            <value>
                <fullName>Awaiting Client reply for more info</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Verification</fullName>
            </value>
            <value>
                <fullName>Awaiting credit review</fullName>
            </value>
            <value>
                <fullName>Awaiting MSP review</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR</fullName>
            </value>
            <value>
                <fullName>Awaiting Primary CSR Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting reply from ICARUS</fullName>
            </value>
            <value>
                <fullName>AWB Sent</fullName>
            </value>
            <value>
                <fullName>B/E Quote Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/classes/CaseWebServiceController.cls
@RestResource(urlMapping='/AerospaceCaseServices/*')
global without sharing class CaseWebServiceController {
    
    @HttpPost
    global static void doPost(){
        String caseNum = null;
        RestRequest req = RestContext.request;
        RestContext.response.addHeader('Content-Type', 'application/json');
        system.debug('-----------Recieved data--------'+req.requestBody.toString()) ;
        CaseDetailRecord caseDetail = (CaseDetailRecord)JSON.deserialize(req.requestBody.toString(),CaseDetailRecord.class);
        List<QueueSobject> caseOwnerQueue = [Select Id, SobjectType, QueueId, Queue.Name From QueueSobject where Queue.Name=: caseDetail.ownerQueue]; 
        List<RecordType> caseRecordType = [SELECT Id FROM RecordType WHERE Name =: caseDetail.recordtypeName and SObjectType = 'Case' limit 1];
        System.debug('caseDetail - '+ caseDetail); 
        
        if(caseDetail.caseID==null){
            String isServiceMissing = caseDetail.isServiceMissing;
            
            Contact contactName = [select id,AccountId from Contact where Honeywell_ID__c =:caseDetail.honeywellID LIMIT 1];  
            system.debug('##@$#$@ '+contactName);
            system.debug('##@$#$@ isServiceMissing '+isServiceMissing);
            system.debug('##@$#$@ govtComplianceContent '+caseDetail.govtComplianceContent);
            system.debug('##@$#$@ exportComplianceContent '+caseDetail.exportComplianceContent);
            
            Case newCaseDetail = new Case();
            newCaseDetail.AccountID = contactName.AccountId;
            newCaseDetail.contactID = contactName.id;
            newCaseDetail.subject = caseDetail.subject;
            newCaseDetail.Classification__c = caseDetail.classification;
            newCaseDetail.Origin = 'Web';
            newCaseDetail.RecordTypeId = caseRecordType[0].id;
            newCaseDetail.status = caseDetail.status;
            newCaseDetail.Sub_Status__c = caseDetail.subStatus;
            newCaseDetail.description = caseDetail.description;
            newCaseDetail.Government_Compliance_SM_M_Content__c = 'No';//caseDetail.govtComplianceContent;
            newCaseDetail.Export_Compliance_Content_ITAR_EAR__c = 'No'; //caseDetail.exportComplianceContent;
            
            if(isServiceMissing == 'Y'){
                newCaseDetail.SuppliedEmail = caseDetail.email;
                
                newCaseDetail.type = caseDetail.caseType;
                newCaseDetail.Additional_Web_Form_Info__c = caseDetail.subscriptionDetails;
            }else{
                newCaseDetail.Comments__c =  caseDetail.comments;
            }
            
            if(!caseOwnerQueue.isEmpty())
                newCaseDetail.OwnerID = caseOwnerQueue[0].QueueId; //caseDetail.ownerQueue;
            
            string errMessage;
            try {
                Database.DMLOptions options = new Database.DMLOptions();
                options.assignmentRuleHeader.useDefaultRule = true;
                newCaseDetail.setOptions(options);
                insert newCaseDetail; 
                system.debug('@@@@Inserted Case@@@@@'+newCaseDetail);
            }
            catch(Exception e)  // exception handling
            {
                System.debug('The following exception has occurred: '+e.getTypeName() + ' - ' + e.getCause() + ': ' + e.getMessage());
                errMessage = e.getMessage();
                CaseResponse caseReturn = new CaseResponse(null,null,'Failure',errMessage);
                RestContext.response.responseBody = Blob.valueOf(JSON.Serialize(caseReturn));
                //return JSON.serialize(caseReturn);
            }
            Case caseInserted = [select casenumber,id  from case where id =: newCaseDetail.id ];
            CaseResponse caseReturn = new CaseResponse(newCaseDetail.id, caseInserted.casenumber,'Success',null);  
            RestContext.response.responseBody = Blob.valueOf(JSON.Serialize(caseReturn));
            //return JSON.serialize(caseReturn);
        }
        else{
            Case updateCase = [select id,CaseNumber,Sub_Status__c,status,Comments__c,description from Case where id=:caseDetail.caseID];
            updateCase.Sub_Status__c = caseDetail.subStatus;
            updateCase.status = caseDetail.status;
            updateCase.Comments__c = caseDetail.comments;
            updateCase.description = caseDetail.description;
            update updateCase;
            CaseResponse caseReturn = new CaseResponse(updateCase.id, updateCase.CaseNumber,'Success',null);  
            RestContext.response.responseBody = Blob.valueOf(JSON.Serialize(caseReturn));
            //return JSON.serialize(caseReturn);
        }
    }


public class CaseResponse{
    public String caseId;
    public String caseNumber;
    public String Status;
    public String error;
    
    public CaseResponse(String caserecId,String caserecNumber, String statusmsg,String errormsg){
        error = '';
        caseId = caserecId;
        caseNumber = caserecNumber;
        Status = statusmsg;
        if(errormsg!=null)
            error =  errormsg;
    }   
}

public class CaseDetailRecord   
{
    public String honeywellID;
    public string subject;
    public string description;
    public String classification;
    public string comments;
    public String recordtypeName;
    public String subStatus;
    public String ownerQueue;
    public String caseType;     
    public String status;
    public String caseID;
    
    public String subscriptionDetails;
    public String exportComplianceContent;
    public String govtComplianceContent;
    public String email;
    public String origin;
    public String isServiceMissing;
    
    public CaseDetailRecord()
    {
        
    }
}

}