src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Supported_Product__c.field-meta.xml
<CustomField>
    <fullName>Supported_Product__c</fullName>
    <description>Do NOT change this list without Troy Barrett / Jenn Searle Approval - They are the Business Owners (TOC)</description>
    <label>Supported Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Catalog_Product_Group__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>787 Maintenance System</fullName>
            </value>
            <value>
                <fullName>ACARS MU</fullName>
            </value>
            <value>
                <fullName>ADAHRS/AHRS</fullName>
            </value>
            <value>
                <fullName>ADAHRS - Bendix King</fullName>
            </value>
            <value>
                <fullName>ADC/DADC (Digital Air Data Computer)</fullName>
            </value>
            <value>
                <fullName>ADF, Primus II/EPIC</fullName>
            </value>
            <value>
                <fullName>ADF DFA-74X</fullName>
            </value>
            <value>
                <fullName>ADIRS</fullName>
            </value>
            <value>
                <fullName>ADIRU</fullName>
            </value>
            <value>
                <fullName>AESS</fullName>
            </value>
            <value>
                <fullName>AFIS</fullName>
            </value>
            <value>
                <fullName>AGT1500 Military</fullName>
            </value>
            <value>
                <fullName>AHRS</fullName>
            </value>
            <value>
                <fullName>Aircraft Personality Module</fullName>
            </value>
            <value>
                <fullName>Airframe Hydraulics</fullName>
            </value>
            <value>
                <fullName>Airplane Information Management System (AIMS)</fullName>
            </value>
            <value>
                <fullName>AirSat 1</fullName>
            </value>
            <value>
                <fullName>Air Traffic Services</fullName>
            </value>
            <value>
                <fullName>Air Turbine Starter</fullName>
            </value>
            <value>
                <fullName>AL/Ex / SPEX / ISS</fullName>
            </value>
            <value>
                <fullName>ALF502 Engine</fullName>
            </value>
            <value>
                <fullName>Anti-Ice Valves - ATR</fullName>
            </value>
            <value>
                <fullName>Anti-Ice Valves - BGA</fullName>
            </value>
            <value>
                <fullName>AOG Lease / Engine Rental Bank</fullName>
            </value>
            <value>
                <fullName>APEX Pilatus</fullName>
            </value>
            <value>
                <fullName>APEX Viking</fullName>
            </value>
            <value>
                <fullName>APM</fullName>
            </value>
            <value>
                <fullName>APU - 100-2/-3/-135</fullName>
            </value>
            <value>
                <fullName>APU - 131-9A</fullName>
            </value>
            <value>
                <fullName>APU - 131-9B</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Skills2__c/Skills2__c.object-meta.xml
<CustomObject>
    <label>Skills</label>
    <nameField>
        <displayFormat>SK-{0}</displayFormat>
        <label>Skills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Skills2__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Skills2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Skills2__c/fields/Primary_Secondary__c.field-meta.xml
<CustomField>
    <fullName>Primary_Secondary__c</fullName>
    <label>Primary/Secondary</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Skills2__c/fields/Supported_Product__c.field-meta.xml
<CustomField>
    <fullName>Supported_Product__c</fullName>
    <label>Supported Product</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/objects/Supported_Product__c/Supported_Product__c.object-meta.xml
<CustomObject>
    <label>Supported Product</label>
    <nameField>
        <label>Supported Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supported Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdatePrimary_ApexClass4.cls
/** * File Name: UpdatePrimary_ApexClass4
* Description Test Method
* Copyright : Wipro Technologies Limited Copyright (c) 2010
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
@isTest
private  class UpdatePrimary_ApexClass4 {
static testmethod void testUpdatePrimary(){

 //creating account;
 /*Account acc= new Account(name='Test Account');
 insert acc;
 
 //creating contact;
 Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495',
  Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='567' );
 insert cont;


Skills2__c skill= new Skills2__c (Primary_Secondary__c='Primary' ,Supported_Product__c='Radio',   Contact__c=cont.Id);
insert skill;

test.starttest();
Case cases14=new Case(AccountId=acc.Id,subject='Fax:{9986502495} test data',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
No_FCR_Reason__c='Not Trained',Type='Order',
//Supported_Product__c='Radio',Origin ='Email-GBS-AES-Repair'); -- Commented for INC000006656211
Supported_Product__c='Radio',Origin ='Email-R&O Avionics');
insert cases14;
test.stoptest();*/
 }

}