src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Aircraft_Type_Model__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Type_Model__c</fullName>
    <label>Aircraft Type / Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/City_Town__c.field-meta.xml
<CustomField>
    <fullName>City_Town__c</fullName>
    <description>Created for AERO Training project : Used in Special Training Request Form</description>
    <label>City/Town</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Created for AERO Training project</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Company_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Street_Address__c</fullName>
    <label>Company Street Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Used for web to Case</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antartica</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Brbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brit. Indian Ocean Terr.</fullName>
            </value>
            <value>
                <fullName>British Virgin Islands</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Customer_Service_Level__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Level__c</fullName>
    <label>Customer Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Superior</fullName>
            </value>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Select one</fullName>
            </value>
            <value>
                <fullName>Authorized Service Center</fullName>
            </value>
            <value>
                <fullName>Honeywell Dealer</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>MSP</fullName>
            </value>
            <value>
                <fullName>Retail Customer</fullName>
            </value>
            <value>
                <fullName>New Customer</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Honeywell_Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_Product_Area__c</fullName>
    <label>Honeywell Product Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Propulsion, APR, and ECS</fullName>
            </value>
            <value>
                <fullName>Avionics and Electronics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Level_of_Training__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Training__c</fullName>
    <label>Level of Training</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Familiarization</fullName>
            </value>
            <value>
                <fullName>Line Maintenance</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Number_of_Students__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Students__c</fullName>
    <label>Number of Students</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Other_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Other_Customer_Type__c</fullName>
    <description>Field Created for Aero Training project. Field used in the Special Training form</description>
    <label>Other Customer Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Preferred_Date_for_Training__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_for_Training__c</fullName>
    <label>Preferred Date for Training</label>
    <type>Date</type>
</CustomField>

src/objects/Case/fields/Requested_Training_Location__c.field-meta.xml
<CustomField>
    <fullName>Requested_Training_Location__c</fullName>
    <label>Requested Training Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Select a location</fullName>
                <default>true</default>
                <label>Select a location</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>Honeywell Facility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Requestor_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email_Address__c</fullName>
    <label>Requestor Email Address</label>
    <type>Email</type>
</CustomField>

src/objects/Case/fields/Requestor_Fax__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Fax__c</fullName>
    <label>Requestor Fax</label>
    <type>Phone</type>
</CustomField>

src/objects/Case/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <label>Requestor Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Requestor_Telephone__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Telephone__c</fullName>
    <label>Requestor Telephone</label>
    <type>Phone</type>
</CustomField>

src/objects/Case/fields/Specific_Honeywell_Product_for_ur_requst__c.field-meta.xml
<CustomField>
    <fullName>Specific_Honeywell_Product_for_ur_requst__c</fullName>
    <label>Specific Honeywell Product for ur requst</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Created for AERO Training project : Used in Special Training Request Form</description>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Types_of_Training__c.field-meta.xml
<CustomField>
    <fullName>Types_of_Training__c</fullName>
    <description>Field created for Aero Training Project. This field is used in the special training form</description>
    <label>Types of Training</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BGA Training</fullName>
            </value>
            <value>
                <fullName>ATR Training</fullName>
            </value>
            <value>
                <fullName>D&amp;S Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Created for AERO Training project : Used in Special Training Request Form</description>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Req #1313. Required for Marketo Sync</description>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Jiangxi</fullName>
            </value>
            <value>
                <fullName>Henan</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Chongqing</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Fujian</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Gansu</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Guangdong</fullName>
            </value>
            <value>
                <fullName>Guangxi</fullName>
            </value>
            <value>
                <fullName>Guizhou</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Req #1313. Required for Marketo Sync</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip/Postal Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/classes/HwTrng_SpclTrngForm_Cls.cls
public class HwTrng_SpclTrngForm_Cls {

    public HwTrng_SpclTrngForm_Cls(ApexPages.StandardController controller) {

    }
 
RecordType RecType = new RecordType();
QueueSobject QueueRec= new QueueSobject();
list<Contact> Cntlst = new list<Contact>();    
Case CaseNewRec=new case();
    
Public case getCaseNewRec()  
  {     
     return CaseNewRec;  
  }
Public void setCaseNewRec()  
  {     
     this.CaseNewRec=CaseNewRec;  
  }
    
public pagereference ClearForm()
  {
     Pagereference p = new pagereference('/apex/HwTrng_SpclTrngForm');
     return p.setredirect(true);
  }
   
public pagereference Save()
  {  
     RecType =[select id,name from recordtype where name='Training'];
     Case CaseTempRec= new case();
     Cntlst=[select id,name,email,Accountid from contact where email=:CaseNewRec.Requestor_Email_Address__c limit 1];
     
     //QueueRec=[Select SobjectType, QueueId, Id,name From QueueSobject where name='HwTrng_SpclTrng_Queue'];
     
     QueueRec= [Select Id, SobjectType, QueueId, Queue.Name from QueueSobject where SobjectType = 'Case' AND Queue.Name = 'Honeywell Training Administrators']; 
     CaseTempRec.Types_of_Training__c=CaseNewRec.Types_of_Training__c;
     CaseTempRec.Customer_Service_Level__c=CaseNewRec.Customer_Service_Level__c;
     if(CaseNewRec.Honeywell_Product_Area__c!='Select an area')
     {
     CaseTempRec.Honeywell_Product_Area__c=CaseNewRec.Honeywell_Product_Area__c;
     }
     else
     {
     CaseTempRec.Honeywell_Product_Area__c=Null;
     }
     CaseTempRec.Specific_Honeywell_Product_for_ur_requst__c=CaseNewRec.Specific_Honeywell_Product_for_ur_requst__c;
     if(CaseNewRec.Level_of_Training__c!='Select an area')
     {
     CaseTempRec.Level_of_Training__c=CaseNewRec.Level_of_Training__c;
     }
     else
     {
     CaseTempRec.Level_of_Training__c=Null;
     }
     CaseTempRec.Preferred_Date_for_Training__c=CaseNewRec.Preferred_Date_for_Training__c;
     CaseTempRec.Preferred_Date_for_Training__c=CaseNewRec.Preferred_Date_for_Training__c;
     if(CaseNewRec.Requested_Training_Location__c!='Select a location')
     {
     CaseTempRec.Requested_Training_Location__c=CaseNewRec.Requested_Training_Location__c;
     }
     else
     {
     CaseTempRec.Requested_Training_Location__c=Null;
     }
     CaseTempRec.Number_of_Students__c=CaseNewRec.Number_of_Students__c;
     CaseTempRec.Aircraft_Type_Model__c=CaseNewRec.Aircraft_Type_Model__c;
     CaseTempRec.Company__c=CaseNewRec.Company__c;
     CaseTempRec.Company_Street_Address__c=CaseNewRec.Company_Street_Address__c;
     CaseTempRec.City_Town__c=CaseNewRec.City_Town__c;
     CaseTempRec.State_Province__c=CaseNewRec.State_Province__c;
     CaseTempRec.Zip_Postal_Code__c=CaseNewRec.Zip_Postal_Code__c;
     CaseTempRec.Requestor_Name__c=CaseNewRec.Requestor_Name__c;
     CaseTempRec.Requestor_Email_Address__c=CaseNewRec.Requestor_Email_Address__c;
     CaseTempRec.Requestor_Telephone__c=CaseNewRec.Requestor_Telephone__c;
     CaseTempRec.Requestor_Fax__c=CaseNewRec.Requestor_Fax__c;
     CaseTempRec.Customer_Type__c=CaseNewRec.Customer_Type__c;
     CaseTempRec.Other_Customer_Type__c=CaseNewRec.Other_Customer_Type__c;
     CaseTempRec.Country__c=CaseNewRec.Country__c;
     CaseTempRec.Your_Field_Service_Engineering_Rep__c=CaseNewRec.Your_Field_Service_Engineering_Rep__c;
     CaseTempRec.Additional_Web_Form_Info__c=CaseNewRec.Additional_Web_Form_Info__c;
     CaseTempRec.recordtypeid=RecType.id;
     CaseTempRec.ownerid=QueueRec.QueueId;
     CaseTempRec.subject='Special training request';
     CaseTempRec.origin='Web';
     //Setting flag to sent notification email to the case owners
     CaseTempRec.Created_From_Form__c=True;
     
     //CaseTempRec.Priority='Urgent';
     if(Cntlst.size()>0)
        {
           CaseTempRec.Contactid=Cntlst[0].id;
           CaseTempRec.Accountid=Cntlst[0].Accountid;
        }
     insert CaseTempRec;
     Pagereference p = new pagereference('/apex/HwTrng_Thanku_VF');
     //Pagereference p = new pagereference('/'+CaseTempRec.id);
     return p;
  }
    
}