src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Cage_Code__c.field-meta.xml
<CustomField>
    <fullName>Cage_Code__c</fullName>
    <description>Cage Code from Web</description>
    <label>Manufacturing Plant Cage Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

src/objects/Case/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Access Codes/SN</fullName>
            </value>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Account Issue</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>Account Mgt Portal</fullName>
            </value>
            <value>
                <fullName>Accounts / Billing</fullName>
            </value>
            <value>
                <fullName>Account Support</fullName>
            </value>
            <value>
                <fullName>Account Updates</fullName>
            </value>
            <value>
                <fullName>Acct Update</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>AeroWave</fullName>
            </value>
            <value>
                <fullName>AIRCRAFT</fullName>
            </value>
            <value>
                <fullName>Aircraft Sale</fullName>
            </value>
            <value>
                <fullName>Aircraft Transfer</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>AMDB</fullName>
            </value>
            <value>
                <fullName>AMI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>APAC ACT Internal</fullName>
            </value>
            <value>
                <fullName>APIS</fullName>
            </value>
            <value>
                <fullName>Application Error</fullName>
            </value>
            <value>
                <fullName>Arinc</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AT&amp;R (Tier 1)</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Spares</fullName>
            </value>
            <value>
                <fullName>Repair/Overhaul</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Special Programs</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Queries</fullName>
            </value>
            <value>
                <fullName>Advance Exchange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case_Line_Item__c/Case_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Case Line Item</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Case Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Line_Item__c/fields/Cage_Code__c.field-meta.xml
<CustomField>
    <fullName>Cage_Code__c</fullName>
    <description>Cage Code from Web</description>
    <label>Cage Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Case_Line_Item__c/fields/Sales_Order_number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_number__c</fullName>
    <label>Sales Order number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Contact/fields/Phone_Tree_Extn__c.field-meta.xml
<CustomField>
    <fullName>Phone_Tree_Extn__c</fullName>
    <label>Phone Tree Extn</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

src/classes/Test_PortalCaseAutoClose.cls
@isTest
public class Test_PortalCaseAutoClose{

static testmethod void PortalCaseAutoClose(){
     
     //test.startTest();
    List<Case> cslist = new List<Case>();
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,
  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='T147567');
     insert cont;
       
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No',Sales_Order_Number__c='test1234', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Customer Hold',Reason_for_hold__c='Business Hold'); //For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Customer Hold'); //For ticket INC000010025414
     insert case1;
          
    Case1.status = 'Re-Open';
     Update case1;
     
     Test.startTest();       
     Case case2=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
     //No_FCR_Reason__c='Not Trained',
     recordtypeid=label.QuotesRecordID,Type='Place Order',Order_Type__c = 'Spares',Sales_Order_Number__c='test1234',Product_Type__c='Electrical',
     cage_code__c = '123', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Customer Hold',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold'); //For ticket INC000010025414
     //cage_code__c = '123', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Customer Hold',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case2;
     
     case2.ownerid=label.portal_quotes;
     case2.status='Re-Open';
     update case2;
       // Sprint 2- Only for Code Coverage - Start
        //case1.ownerid=label.R_O_Basingstoke_Quotes_Queue_ID;
        //update case1;        
        // Sprint 2- Only for Code Coverage - End

     
     Case_Line_Item__c cli1 =  new Case_Line_Item__c (Case_Number__c = case1.id,Price__c = 10.00,Quantity__c=10.00);
     Case_Line_Item__c cli2 =  new Case_Line_Item__c (Case_Number__c = case1.id,Price__c = 10.00,Quantity__c=20.00);
     Case_Line_Item__c cli3 =  new Case_Line_Item__c (Case_Number__c = case1.id,Price__c = 10.00,Quantity__c=30.00);
     Case_Line_Item__c cli4 =  new Case_Line_Item__c (Case_Number__c = case1.id,Price__c = 10.00,recordtypeid=label.AverageTimeHold_RecID);
     
     
     case2.status='Discard';
     Update case2;
     Test.stopTest();
     
}
static testmethod void PortalCaseAutoClose1(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
     insert cont;
      Test.startTest(); 
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
        // No_FCR_Reason__c='Not Trained',
        recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373',Sales_Order_Number__c='test1234', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Engineering Hold',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold'); //For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Engineering Hold',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='Import Hold';
     update case1;
}
static testmethod void PortalCaseAutoClose2(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='T123567');
     insert cont;
      Test.startTest(); 
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373',Sales_Order_Number__c='test1234', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'MTO Customer',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold'); //For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'MTO Customer',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='Business Hold';
     update case1;
}
static testmethod void PortalCaseAutoClose3(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='H123567');
     insert cont;
     Test.startTest();  
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Order_RecordType,Sales_Order_Number__c='test1234',Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Export Hold',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold');// For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Export Hold',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='Credit Hold';
     update case1;
}

static testmethod void PortalCaseAutoClose4(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='T123567');
     insert cont;
      Test.startTest(); 
     Case case1=new Case(contactid = Cont.id,Sales_Order_Number__c='test1234',Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
        // No_FCR_Reason__c='Not Trained',
        recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'MTO',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold'); //For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'MTO',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='Quality Hold';
     update case1;
}

static testmethod void PortalCaseAutoClose5(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
     insert cont;
       Test.startTest();
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373',Sales_Order_Number__c='test1234',classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Pricing Hold',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold'); //For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Pricing Hold',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='Integrated Supply Chain Hold';
     update case1;
}
static testmethod void PortalCaseAutoClose6(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
     insert cont;
     Test.startTest();  
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373',Sales_Order_Number__c='test1234', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Pricing Hold',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold');// For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Pricing Hold',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='MTO';
     update case1;
}
static testmethod void PortalCaseAutoClose7(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
     insert cont;
      Test.startTest(); 
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
         //No_FCR_Reason__c='Not Trained',
         recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373',Sales_Order_Number__c='test1234', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Pricing Hold',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold');// For ticket INC000010025414
         //cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Pricing Hold',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='MTO Customer';
     update case1;
}
static testmethod void PortalCaseAutoClose8(){
     
     
     Account acc= new Account(name='Test Account');
     insert acc;
   
     Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495', Phone_Tree_Extn__c='1234',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567');
     insert cont;
     Test.startTest();  
     Case case1=new Case(contactid = Cont.id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',origin='Web',
        // No_FCR_Reason__c='Not Trained',
        recordtypeid=label.Order_RecordType,Type='Order Changes',Order_Type__c = 'Spares',
         cage_code__c = '22373',Sales_Order_Number__c='test1234', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Import Hold',VN_Name__c=cont.id,Reason_for_hold__c='Business Hold');//For ticket INC000010025414
        // cage_code__c = '22373', classification__c = 'EMS',status = 'On Hold',sub_status__c = 'Import Hold',VN_Name__c=cont.id); //For ticket INC000010025414
     insert case1;
     
     case1.sub_status__c='Engineering Hold';
     update case1;
}

}