src/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case/fields/Export_Compliance_Content_ITAR_EAR__c.field-meta.xml
<CustomField>
    <fullName>Export_Compliance_Content_ITAR_EAR__c</fullName>
    <inlineHelpText>Select yes if export controlled data is in this case. Export controlled data may include drawings, specifications, instructions, BoMs or other technical data.  A yes check will result in a case review and update to remove the export controlled data.</inlineHelpText>
    <label>Export Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case/fields/Government_Compliance_SM_M_Content__c.field-meta.xml
<CustomField>
    <fullName>Government_Compliance_SM_M_Content__c</fullName>
    <inlineHelpText>Select yes if data is related to a contract with government/customer restrictions. Included data may be technical or may be in support of government agencies .A yes check will result in a case review and update to remove the restricted data.</inlineHelpText>
    <label>Government Compliance Content</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/classes/ShowRelatedlst_TestCls.cls
@isTest
private class ShowRelatedlst_TestCls{ 

static testMethod void ShowRelatedlst_TM()
{
Account acc= new Account(name='Test Account');
 insert acc;

 //creating contact;
 Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495',
  Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='E123567' );
 insert cont;

 
 //creating case
 Case cases=new Case(AccountId=acc.Id,subject='Fax:{9986502495} test data',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
 //No_FCR_Reason__c='Not Trained',For Ticket INC000009687923
 Type='Order',status='Done');
 insert cases;
 
 Case cases2=new Case(AccountId=acc.Id,subject='Test Case',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
 //No_FCR_Reason__c='Not Trained',For Ticket INC000009687923
 Type='Order');
 insert cases2;
test.starttest();
emailmessage emlrec1=new emailmessage();
emlrec1.parentId=cases.id;
emlrec1.status='1';
emlrec1.Incoming=false;
emlrec1.ToAddress='testing@testing.com';
insert emlrec1;

emailmessage emlrec2=new emailmessage();
emlrec2.parentId=cases.id;
emlrec2.status='2';
emlrec2.Incoming=false;
emlrec2.ToAddress='testing@testing.com';
insert emlrec2;

emailmessage emlrec3=new emailmessage();
emlrec3.parentId=cases.id;
emlrec3.status='3';
emlrec3.Incoming=false;
emlrec3.ToAddress='testing@testing.com';
insert emlrec3;

emailmessage emlrec4=new emailmessage();
emlrec4.parentId=cases.id;
emlrec4.status='0';
emlrec4.Incoming=false;
emlrec4.ToAddress='testing@testing.com';
insert emlrec4;

emailmessage emlrec5=new emailmessage();
emlrec5.parentId=cases2.id;
emlrec5.status='1';
emlrec5.Incoming=false;
emlrec5.subject = 'Test Message';
emlrec5.ToAddress='testing@testing.com';
insert emlrec5;

ApexPages.StandardController controller= new ApexPages.StandardController(cases);
System.currentPagereference().getParameters().put('id', cases.id);
showrelatedlist showreltedlst=new showrelatedlist(controller);




showreltedlst.getdata();
showreltedlst.getallmodels();
 test.stoptest();
}


}