src/objects/ContractLineItem.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContractLineItem/fields/GDMFS_PO_Number_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFS_PO_Number_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Number required for Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_24HrCoverage_BusinessDays__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_24HrCoverage_BusinessDays__c</fullName>
    <defaultValue>false</defaultValue>
    <label>24 hour Reactive Coverage Business Days</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_After_Hr_Reactive_Response__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_After_Hr_Reactive_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Hours Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_HolidayNoReactiveCoverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_HolidayNoReactiveCoverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Holidays No Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_Maintenance_Hours__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Maintenance_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maintenance Hours</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_Office_Hr_Reactive_Response__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Office_Hr_Reactive_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Hours Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_Parts_Replacement_Managment__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Parts_Replacement_Managment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parts Replacement</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_Reactive_Work_Not_Chargeable__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Reactive_Work_Not_Chargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reactive Work is Not Chargeable</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_Warranty_Services__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Warranty_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warranty Services</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ContractLineItem/fields/GDMFSL_X24hr_Reactive_Response__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_X24hr_Reactive_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>24 hour Reactive Coverage - 7 days/week</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Associated_Contract__c/GDMFSL_Associated_Contract__c.object-meta.xml
<CustomObject>
    <label>Associated Contract</label>
    <nameField>
        <displayFormat>ACN-{0000}</displayFormat>
        <label>Associated Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GDMFSL_SLA__c/GDMFSL_SLA__c.object-meta.xml
<CustomObject>
    <description>This custom object will hold SLA records related to Asset or Location/Service Contract combination and it will used to derive Work dates.</description>
    <label>SLA</label>
    <nameField>
        <displayFormat>SLA-{00000000}</displayFormat>
        <label>SLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Arrival_Time__c</fullName>
    <description>SLA Arrival Time</description>
    <label>Arrival Time (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Associated_Contract__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Associated_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Location and Contract the SLA is related to</description>
    <inlineHelpText>The Location and Contract the SLA is related to</inlineHelpText>
    <label>Associated Contract</label>
    <referenceTo>GDMFSL_Associated_Contract__c</referenceTo>
    <relationshipLabel>SLAs</relationshipLabel>
    <relationshipName>SLAs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Line Item</label>
    <referenceTo>ContractLineItem</referenceTo>
    <relationshipLabel>SLAs</relationshipLabel>
    <relationshipName>SLAs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Priority__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Priority__c</fullName>
    <description>SLA Priority...</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Resolution_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Resolution_Time__c</fullName>
    <description>SLA Resolution Time</description>
    <label>Resolution Time (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Response_Time__c</fullName>
    <description>SLA Response Time</description>
    <label>Response Time (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ServiceContract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract/fields/GDMFS_PO_Number_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFS_PO_Number_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Number required for Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceContract/fields/GDMFSL_24HrCoverage_BusinessDays__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_24HrCoverage_BusinessDays__c</fullName>
    <defaultValue>false</defaultValue>
    <description>..</description>
    <label>24 hour Reactive Coverage Business Days</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceContract/fields/GDMFSL_After_Hr_Reactive_Response__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_After_Hr_Reactive_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Hours Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceContract/fields/GDMFSL_HolidayNoReactiveCoverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_HolidayNoReactiveCoverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Holidays No Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceContract/fields/GDMFSL_Office_Hr_Reactive_Response__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Office_Hr_Reactive_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Hours Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceContract/fields/GDMFSL_Reactive_Work_Not_Chargeable__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Reactive_Work_Not_Chargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reactive Work is Not Chargeable</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceContract/fields/GDMFSL_Warranty_Services__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Warranty_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warranty Services</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceContract/fields/GDMFSL_X24hr_Reactive_Response__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_X24hr_Reactive_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>24 hour Reactive Coverage - 7 days/week</label>
    <type>Checkbox</type>
</CustomField>

src/classes/GDMFSL_ContractLineItemProcessor.cls
/**
 * Name       :    GDMFSL_ContractLineItemProcessor
 * Purpose    :    Processor Logic for ContractLine Item object . See method descriptions for proper context for calling each method
 * --------------------------------------------------------------------------
 * Developer               Date          Description
 * --------------------------------------------------------------------------
 * Udbhav                  2020-Oct-12    Created
 **/
public without sharing class GDMFSL_ContractLineItemProcessor {

    public static Map<Id, Map<Id, List<ContractLineItem>>> getRecords(Set<Id> serviceContractIds, Set<Id> assetIds) {

        System.debug('Inside GDMFSL_ContractLineItemProcessor');

        Map<Id, Map<Id, List<ContractLineItem>>> scAssetRelatedCLI = new Map<Id, Map<Id, List<ContractLineItem>>>();

        for (ContractLineItem contractLineItem : [
                SELECT
                        StartDate,
                        EndDate,
                        Id,
                        AssetId,
                        ServiceContractId,
                        GDMFSL_Warranty_Services__c,
                        GDMFSL_Parts_Replacement_Managment__c,
                        GDMFS_PO_Number_Reactive_Coverage__c,
                        GDMFSL_Reactive_Work_Not_Chargeable__c,
                        GDMFSL_Office_Hr_Reactive_Response__c,
                        GDMFSL_After_Hr_Reactive_Response__c,
                        GDMFSL_X24hr_Reactive_Response__c,
                        GDMFSL_HolidayNoReactiveCoverage__c,
                        GDMFSL_24HrCoverage_BusinessDays__c,
                        GDMFSL_Maintenance_Hours__c, (
                        SELECT Id,GDMFSL_Priority__c,GDMFSL_Resolution_Time__c,
                                GDMFSL_Response_Time__c,GDMFSL_Arrival_Time__c,
                                GDMFSL_Associated_Contract__c,GDMFSL_Contract_Line_Item__c
                        FROM SLAs__r
                )
                FROM ContractLineItem
                WHERE
                ServiceContractId IN :serviceContractIds AND
                AssetId IN :assetIds
        ]) {

            if (!scAssetRelatedCLI.containsKey(contractLineItem.ServiceContractId)) {
                scAssetRelatedCLI.put(contractLineItem.ServiceContractId, new Map<Id, List<ContractLineItem>>());
            }

            if (!scAssetRelatedCLI.get(contractLineItem.ServiceContractId).containsKey(contractLineItem.AssetId)) {
                scAssetRelatedCLI.get(contractLineItem.ServiceContractId).put(contractLineItem.AssetId, new List<ContractLineItem>());
            }

            scAssetRelatedCLI.get(contractLineItem.ServiceContractId).get(contractLineItem.AssetId).add(contractLineItem);
        }

        System.debug('Exit GDMFSL_ContractLineItemProcessor return value count : ' + scAssetRelatedCLI.size());
        return scAssetRelatedCLI;
    }

    public static void updateCLIfromSC(Map<Id, ServiceContract> serviceContractMap) {

        if (serviceContractMap != null && !serviceContractMap.isEmpty()) {
            List<ContractLineItem> clisToUpdate = new List<ContractLineItem>();

            for (ContractLineItem cli : [
                    SELECT
                            StartDate,
                            EndDate,
                            Id,
                            ServiceContractId
                    FROM ContractLineItem
                    WHERE
                            ServiceContractId IN :serviceContractMap.keySet()
            ]) {
                if (cli.StartDate <= serviceContractMap.get(cli.ServiceContractId).EndDate) {
                    cli.EndDate = serviceContractMap.get(cli.ServiceContractId).EndDate;
                    clisToUpdate.add(cli);
                }
            }

            if (!clisToUpdate.isEmpty()) {
                GDMFSL_CommonUtilities.updateRecords(clisToUpdate);
            }
        }
    }

}