src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Access__c.field-meta.xml
<CustomField>
    <fullName>Access__c</fullName>
    <description>Access level to aircrafts</description>
    <label>Access</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>No Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Managing_SBU__c.field-meta.xml
<CustomField>
    <fullName>Managing_SBU__c</fullName>
    <formula>text( Platform_Name__r.Managing_SBU__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Managing SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Type__c</fullName>
    <inlineHelpText>The Fleet entry&apos;s Platform Type.</inlineHelpText>
    <label>Platform Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>The Serial Number of the current Fleet entry.</inlineHelpText>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Master_Service_Program__c/Master_Service_Program__c.object-meta.xml
<CustomObject>
    <description>stores all Service Programs irrespective of user access</description>
    <label>Master Service Program</label>
    <nameField>
        <label>Master Service Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Service Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Managing_SBU__c.field-meta.xml
<CustomField>
    <fullName>Managing_SBU__c</fullName>
    <label>Managing SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Type__c</fullName>
    <inlineHelpText>Defines the Platform Type.</inlineHelpText>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Airplane</fullName>
            </value>
            <value>
                <fullName>Combat Support Vehicles</fullName>
            </value>
            <value>
                <fullName>Combat Vehicles</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles</fullName>
            </value>
            <value>
                <fullName>Components</fullName>
            </value>
            <value>
                <fullName>Fire Direction Control Vehicle</fullName>
            </value>
            <value>
                <fullName>Helicopter</fullName>
            </value>
            <value>
                <fullName>Hovercraft</fullName>
            </value>
            <value>
                <fullName>Marine Craft</fullName>
            </value>
            <value>
                <fullName>Missiles &amp; Munitions</fullName>
            </value>
            <value>
                <fullName>Non-Aircraft</fullName>
            </value>
            <value>
                <fullName>Radar</fullName>
            </value>
            <value>
                <fullName>Service Center</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Surface Ship</fullName>
            </value>
            <value>
                <fullName>Tactical Vehicles</fullName>
            </value>
            <value>
                <fullName>Various</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Restricted_Service_Program__c/Restricted_Service_Program__c.object-meta.xml
<CustomObject>
    <label>Restricted Service Program</label>
    <nameField>
        <displayFormat>RSP-{00000}</displayFormat>
        <label>Restricted Service Program</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restricted Service Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Restricted_Service_Program__c/fields/Master_Service_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Master_Service_Program_Name__c</fullName>
    <label>Master Service Program Name</label>
    <referenceTo>Master_Service_Program__c</referenceTo>
    <relationshipLabel>Restricted Service Programs</relationshipLabel>
    <relationshipName>Restricted_Service_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Restricted_Service_Program__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Restricted Service Programs</relationshipLabel>
    <relationshipName>Restricted_Service_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains Email Id of &apos;ATR Opportunity Scheduled Report&apos; recipients</description>
    <label>Users</label>
</CustomObject>

src/objects/User_Aircraft_Association__c/User_Aircraft_Association__c.object-meta.xml
<CustomObject>
    <description>stores Fleet Asset Aircraft details for each user.</description>
    <label>User Aircraft Association</label>
    <nameField>
        <displayFormat>UAA-{00000}</displayFormat>
        <label>User Aircraft Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Aircraft Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Aircraft_Association__c/fields/Fleet_Asset_Aircraft_Name__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Asset_Aircraft_Name__c</fullName>
    <description>Fleet Asset Aircraft to which Contact have access</description>
    <label>Fleet Asset Aircraft Name</label>
    <referenceTo>Fleet_Asset_Detail__c</referenceTo>
    <relationshipLabel>User Aircraft Associations</relationshipLabel>
    <relationshipName>User_Aircraft_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/User_Aircraft_Association__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Serial Number of related Fleet Asset Aircraft</description>
    <formula>Fleet_Asset_Aircraft_Name__r.Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

src/objects/User_Aircraft_Association__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>User who have access to a particular Fleet Asset Aircraft</description>
    <label>User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>User Aircraft Associations</relationshipLabel>
    <relationshipName>User_Aircraft_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/updateContactOnChildUpdates_test.cls
@isTest

public class updateContactOnChildUpdates_test{
    static testMethod void insertUAA() {
    Test.startTest();
    //Insert Platform //
    Platform__c p = new Platform__c(Name='Dassault Aviation Falcon 900 B',Platform_Type__c= 'Airplane',Managing_SBU__c='BGA');
    insert p; 
    
    //Insert Fleet_Asset_Aircraft //
    Fleet_Asset_Detail__c FAA= new Fleet_Asset_Detail__c();
    FAA.Name='TEST-Boeing 737-100 S=1234';
    FAA.Serial_Number__c ='12345';
    FAA.Platform_Name__c=p.Id;
    insert FAA;
    
    //Insert Contact //
    Contact con = new Contact();
    Con.FirstName='Test' ;
    Con.LastName = 'Contact';
    insert con ;
     
    //Insert User_Aircraft_Association__c //
    User_Aircraft_Association__c UAA = new User_Aircraft_Association__c ();
    UAA.Fleet_Asset_Aircraft_Name__c=  FAA.Id;
    UAA.User__c= con.Id;
    insert UAA;
    Test.stopTest();
    
    }
    
    static testMethod void insertRSP()
    {
    Test.startTest();
     //Insert Master Service Program//
    Master_Service_Program__c MSP = new Master_Service_Program__c();
    MSP.Name ='Flight Services Test Record';
    insert MSP;
    
    //Insert Contact //
    Contact cont = new Contact();
    cont .FirstName='Test1' ;
    cont .LastName = 'Contact1';
    insert cont ;
    
    //Insert Restricetd Service
    Restricted_Service_Program__c RSP = new Restricted_Service_Program__c ();
    RSP.Master_Service_Program_Name__c= MSP.Id;
    RSP.User__c= cont.Id;
    insert RSP;
    Test.stopTest();
    }
    
    static testMethod void deleteRSP()
    {
        Test.startTest();
    Master_Service_Program__c MSP = new Master_Service_Program__c();
    MSP.Name ='Flight Services Test Record';
    insert MSP;
    
   
    Contact cont = new Contact();
    cont .FirstName='Test1' ;
    cont .LastName = 'Contact1';
    insert cont ;
    
    //Delete Restricetd Service
    Restricted_Service_Program__c RSP = new Restricted_Service_Program__c ();
    RSP.Master_Service_Program_Name__c= MSP.Id;
    RSP.User__c= cont.Id;
    insert RSP;
    delete  RSP;
     Test.stopTest();
    }
    static testMethod void deleteUAA()
    
    {
    Test.startTest();
    //Delete Platform record//
    Platform__c p = new Platform__c(Name='Dassault Aviation Falcon 900 B',Platform_Type__c= 'Airplane',Managing_SBU__c='BGA');
    insert p; 
    
    
    Fleet_Asset_Detail__c FAA= new Fleet_Asset_Detail__c();
    FAA.Name='TEST-Boeing 737-100 S=1234';
    FAA.Serial_Number__c ='12345';
    FAA.Platform_Name__c=p.Id;
    insert FAA;
    
    
    Contact con = new Contact();
    Con.FirstName='Test' ;
    Con.LastName = 'Contact';
    insert con ;
     
    //Delete User_Aircraft_Association__c //
    User_Aircraft_Association__c UAA = new User_Aircraft_Association__c ();
    UAA.Fleet_Asset_Aircraft_Name__c=  FAA.Id;
    UAA.User__c= con.Id;
    insert UAA;
    delete UAA;
    Test.stopTest();
    
    }
    static testMethod void updateContact() {
    Test.startTest();
    //Insert Platform //
    Platform__c p = new Platform__c(Name='Dassault Aviation Falcon 900 B',Platform_Type__c= 'Airplane',Managing_SBU__c='BGA');
    insert p; 
    
    //Insert Fleet_Asset_Aircraft //
    List<Fleet_Asset_Detail__c> FAAList= new List<Fleet_Asset_Detail__c>();
    Fleet_Asset_Detail__c FAA= new Fleet_Asset_Detail__c();
    FAA.Name='TEST-Boeing 737-100 S=1234';
    FAA.Serial_Number__c ='12345';
    FAA.Platform_Name__c=p.Id;
        FAAList.add(FAA);
        Fleet_Asset_Detail__c FAA1= new Fleet_Asset_Detail__c();
    FAA1.Name='TEST-Boeing 737-100 S=12341';
    FAA1.Serial_Number__c ='12345';
    FAA1.Platform_Name__c=p.Id;
        FAAList.add(FAA1);
    insert FAAList;
    
    //Insert Contact //
    Contact con = new Contact();
    Con.FirstName='Test' ;
    Con.LastName = 'Contact';
    insert con ;
        con.Access__c = 'Full Access';
        update con;
     
    //Insert User_Aircraft_Association__c //
    List<User_Aircraft_Association__c> UAAList = new List<User_Aircraft_Association__c>();
    User_Aircraft_Association__c UAA = new User_Aircraft_Association__c ();
    UAA.Fleet_Asset_Aircraft_Name__c=  FAA.Id;
    UAA.User__c= con.Id;
        UAAList.add(UAA);
    User_Aircraft_Association__c UAA1 = new User_Aircraft_Association__c ();
    UAA1.Fleet_Asset_Aircraft_Name__c=  FAA1.Id;
    UAA1.User__c= con.Id;
        UAAList.add(UAA1);
    insert UAAList;
    con.Access__c = 'No Access';
        update con;    
    Test.stopTest();
    
    }
    }