src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Marketing Engaged</fullName>
            </value>
            <value>
                <fullName>With Telemarketing</fullName>
            </value>
            <value>
                <fullName>Assigned - Target Team</fullName>
            </value>
            <value>
                <fullName>Working - Target Team</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>With Customer Marketing</fullName>
            </value>
            <value>
                <fullName>Working - Contacted</fullName>
            </value>
            <value>
                <fullName>Closed - Existing Opportunity</fullName>
            </value>
            <value>
                <fullName>Closed - No Project Now</fullName>
            </value>
            <value>
                <fullName>Closed - Converted (Qualified)</fullName>
            </value>
            <value>
                <fullName>Redirected - Channel Sales</fullName>
            </value>
            <value>
                <fullName>Closed - Competitor</fullName>
            </value>
            <value>
                <fullName>Closed - Duplicate</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid Contact</fullName>
            </value>
            <value>
                <fullName>Redirected - LGS</fullName>
            </value>
            <value>
                <fullName>Sent to Partner</fullName>
            </value>
            <value>
                <fullName>Redirected - Partner Sales Manager</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Assigned - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Working - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Contacted - Inside Sales</fullName>
            </value>
            <value>
                <fullName>Handoff</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Converted to Opportunity</fullName>
            </value>
            <value>
                <fullName>Converted To Contact</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Key_Affected_OEMs_Operators__c/Key_Affected_OEMs_Operators__c.object-meta.xml
<CustomObject>
    <label>Key Affected OEMs/Operators</label>
    <nameField>
        <displayFormat>OEM{0}</displayFormat>
        <label>Key Affected OEM(s) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Affected OEMs/Operators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Key_Affected_OEMs_Operators__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Key Affected OEMs/Operators</relationshipLabel>
    <relationshipName>Key_Affected_OEMs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>SR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>AOG - Requires response within 4 hours
IFSD - In Flight Shut Down / Requires response within 4 hours
Critical - SOF or potential SOF / Requires response within 12 hours
Leadership Alert - Critical and requires Leadership to be alerted
High - Requires</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AOG</fullName>
            </value>
            <value>
                <fullName>IFSD</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Leadership Alert</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Routine</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Problem_Description_new__c.field-meta.xml
<CustomField>
    <fullName>Problem_Description_new__c</fullName>
    <inlineHelpText>Short description of the problem. Include what the customer seeing, under what conditions (4-Up,DB)
Example: Phase 3 DU flickering/blanking caused by WiFi. When GCC box is checked will be visible to members, in One List and on the GCC slide.</inlineHelpText>
    <label>Problem Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/fields/SR_Type__c.field-meta.xml
<CustomField>
    <fullName>SR_Type__c</fullName>
    <label>SR Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complex Problem</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Issue</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>EPS OOMR- Out Of Model Request</fullName>
            </value>
            <value>
                <fullName>Field Event</fullName>
            </value>
            <value>
                <fullName>GDC</fullName>
            </value>
            <value>
                <fullName>M2M Digital Adoption</fullName>
            </value>
            <value>
                <fullName>Non-Technical Systemic Issue</fullName>
            </value>
            <value>
                <fullName>Order Management Issue</fullName>
            </value>
            <value>
                <fullName>Quality Issue</fullName>
            </value>
            <value>
                <fullName>Significant Customer Dissatisfier</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>VOC</fullName>
            </value>
            <value>
                <fullName>Defect</fullName>
            </value>
            <value>
                <fullName>Standard Work</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Amend</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Update/Minor Changes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>&quot;Open&quot;: Investigation is active or fix is in work.
&quot;Closed&quot;: Issue has been resolved or completed.
&quot;Monitor&quot;: Issue is waiting for additional information from customer or there is a request for issue to be monitored.
&quot;Queue&quot;: SR awaiting to be assigned</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Containment</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>RCCA</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Very brief, high level explanation of SR. Platform, Model or PN, Issue.The subject line of an email or the title of the case ticket.</description>
    <inlineHelpText>Brief description of SR (90 Char Max) (4-Up,DB)</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/TestClass_UpdateOEMsTrigger.cls
@isTest
private class TestClass_UpdateOEMsTrigger
{
    static testmethod void  TestClass_UpdateOEMsTrigger()
    {
        Account acc = New Account(
            Name= 'sbuaccount'
                  );
        insert acc;
        
        Contact cont=new Contact(
            firstname='Test',
            LastName='Contactfor upd',
            AccountId=acc.Id,
            Phone_3__c='9986502495',
            Contact_Is_Employee__c=true,
            Contact_Status__c='Active' ,
            Employee_Number__c='E157567',
            Employee_Contact_Role__c='Administrator'
        );
        insert cont;
        
        Service_Request__c serreq = new Service_Request__c(
            Subject__c='test ser',
            SR_Type__c='Field Event',
            Priority__c='AOG',
            status__c='Open',
            Problem_Description_new__c='hgcdatrd',
            Deliverable__c='htfrd',
            Risk_Assessment__c='Red',
            Contact_Name__c=cont.id,
            Customer_Reason_Change__c='Original',
            Atr__c='Value',
            Attribute_Details__c='Allocation Priority',
            Complexity_Level__c='1-Part Price/Availability'
            );
        insert serreq;
        
                
        //test.starttest();

        Key_Affected_OEMs_Operators__c KAOO = new Key_Affected_OEMs_Operators__c(
            Service_Request__c = serreq.id,
            Account_Name__c = acc.id,
        OEM_Operator__c = 'OEM'
        );
        insert KAOO;  
        update serreq;
      //  test.stoptest();     
    }
}