src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Referrer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/ServiceAppointment/fields/GDMFSL_Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Delivery_Block__c</fullName>
    <formula>IF(
AND(
OR( ISPICKVAL(StatusCategory, &quot;None&quot;) ,
ISPICKVAL(StatusCategory, &quot;Scheduled&quot;),
ISPICKVAL(StatusCategory, &quot;Dispatched&quot;) ,
ISPICKVAL(StatusCategory, &quot;In Progress&quot;)),
NOT( ISNULL(  GDMFSL_Sold_To_Source_System_Reference__c  )))
,
 GDMFSL_Sold_To_Source_System_Reference__r.GDMFSL_Delivery_Block__c  , false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Block</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Sold_To_Source_System_Reference__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Sold_To_Source_System_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Source System Reference</label>
    <referenceTo>Source_System__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Source_System__c/fields/GDMFSL_Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Delivery_Block__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delivery Block</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder/fields/GDMFSL_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Contact_Email__c</fullName>
    <formula>Contact.Email</formula>
    <label>Contact Email</label>
    <type>Text</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Delivery_Block__c</fullName>
    <formula>IF(
AND(
OR( ISPICKVAL(StatusCategory, &quot;New&quot;) ,
ISPICKVAL(StatusCategory, &quot;In Progress&quot;)),
NOT( ISNULL( GDMFSL_Sold_To_Source_System_Reference__c)))
,
GDMFSL_Sold_To_Source_System_Reference__r.GDMFSL_Delivery_Block__c, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Block</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Executed_by_Sub_Contractor__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Executed_by_Sub_Contractor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Executed by Sub-Contractor</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Sold_To_Source_System_Reference__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Sold_To_Source_System_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Source System Reference</label>
    <referenceTo>Source_System__c</referenceTo>
    <relationshipLabel>Work Orders (Sold To Source System Reference)</relationshipLabel>
    <relationshipName>Work_Orders_SoldTo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/GDMFSL_ServiceReportProcessorTest.cls
@IsTest
private class GDMFSL_ServiceReportProcessorTest {

    @TestSetup
    static void init() {
        Account a = new Account(Name = 'Test Account', Phone = '1234561234', BillingStreet = 'Anywhere', BillingCity = 'City', BillingState = 'Florida', BillingCountry = 'United States');
        insert a;

        WorkType wt = GDMFSL_DataFactory.createWorkType('Break/Fix', 4);
        insert wt;
        OperatingHours ohs = GDMFSL_DataFactory.createOperatingHour();
        insert ohs;
        ServiceTerritory st = GDMFSL_DataFactory.createServiceTerritory('SSProc Test', ohs.Id);
        insert st;
        Schema.Location lo = GDMFSL_DataFactory.createLocation('Test Location', st.Id);
        insert lo;

        Source_System__c ss = GDMFSL_DataFactory.createSourceSystem(a.Id, '11111');
        ss.Customer_Order_Block__c = true;
        ss.GDMFSL_Delivery_Block__c = false;
        ss.Type__c = 'SOLDTO';
        insert ss;

        WorkOrder wo = GDMFSL_DataFactory.createWorkOrder(wt.Id, a.Id, lo.Id, System.now(), System.now());
        wo.GDMFSL_Sold_To_Source_System_Reference__c = ss.Id;
        wo.GDMFSL_PO_Number__c = '12345';
        insert wo;

        ServiceAppointment theSA = GDMFSL_DataFactory.createServiceAppointmentwithParentWO(wo.Id, GDMFSL_WorkOrderProcessor.COMPLETEDSTATUS);
        theSA.SchedStartTime = System.now();
        theSA.SchedEndTime = System.now().addHours(4);
        insert theSA;

        ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
        );
        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = theSA.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'V';
        insert cdl;


        ServiceReport sr = new ServiceReport();
        sr.DocumentBody = Blob.valueOf('Test Content') ;
        sr.DocumentContentType ='application/pdf';
        sr.DocumentName='Test';
        sr.ParentId = theSA.Id;
        insert sr ;
    }

    @IsTest
    static void getorgNoReplyEmailAddressTest() {

        OrgWideEmailAddress theEmail = GDMFSL_ServiceReportProcessor.getOrgWideNoReplyAddress();

        System.assertEquals(GDMFSL_ServiceReportProcessor.NO_REPLY_EMAIL, theEmail.DisplayName, 'Wrong Org wide email address returned');
    }

    @IsTest
    static void sendSiteContactEmailCompletedWOsTest(){

        // we can't test this method directly because of the way Contact info is checked on the WOrder.  So we have to do DML
        Map<Id, WorkOrder> theWOs = new Map<Id, WorkOrder>([SELECT Id, ContactId, GDMFSL_Contact_Email__c,
                                                            Status, GDMFSL_Executed_by_Sub_Contractor__c
                                                            FROM WorkOrder]);


        Account theAccount = [SELECT Id FROM Account LIMIT 1];

        Contact theContact = GDMFSL_DataFactory.createTestContact(theAccount.Id);
        insert theContact;

        for (WorkOrder thisWO : theWOs.values()){
            thisWO.ContactId = theContact.Id;
            thisWO.GDMFSL_Executed_by_Sub_Contractor__c = false;
            thisWO.Status = GDMFSL_WorkOrderProcessor.COMPLETEDSTATUS;
        }

        Integer origEmailSends = Limits.getEmailInvocations();

        System.debug('TEST start');

        System.debug('The GDMFSL_ServiceReportProcessor.sendSiteContactEmailCompletedWOs() method is tested via its call in the WO trigger');
        update theWOs.values();

        System.assertNotEquals(origEmailSends, Limits.getEmailInvocations(), 'sendSiteContactEmailCompletedWOs(): Email was not sent as expected');

    }
}