src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Raw</fullName>
                    <default>true</default>
                    <label>Raw</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                    <label>Qualified (now)</label>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                    <label>Nurture (not now)</label>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                    <label>Unqualified (never)</label>
                </value>
                <value>
                    <fullName>Bounced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact/fields/Contact_Is_Employee__c.field-meta.xml
<CustomField>
    <fullName>Contact_Is_Employee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies a Honeywell Employee by virtue of a checkmark.</inlineHelpText>
    <label>Contact Is Employee</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact/fields/Employee_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Employee_Contact_Role__c</fullName>
    <inlineHelpText>This is the Field used for the Support Locator application.  Please use &quot;Field Service Engineer&quot; / &quot;Field Service Manager&quot; usually.</inlineHelpText>
    <label>Employee Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales Manager</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Credit Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Business Director</fullName>
            </value>
            <value>
                <fullName>Customer Business Manager (CBM)</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Leader</fullName>
            </value>
            <value>
                <fullName>Customer Business Team Member</fullName>
            </value>
            <value>
                <fullName>Customer Service Administrator</fullName>
            </value>
            <value>
                <fullName>Customer Service Engineer (CSE)</fullName>
            </value>
            <value>
                <fullName>Customer Service Manager</fullName>
            </value>
            <value>
                <fullName>Customer Service Project Manager (CSPM)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact/fields/Phone_3__c.field-meta.xml
<CustomField>
    <fullName>Phone_3__c</fullName>
    <label>Primary Fax Number</label>
    <type>Phone</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <formula>TEXT( Contact.Contact_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Status</label>
    <type>Text</type>
</CustomField>

src/objects/User/fields/SBU_User__c.field-meta.xml
<CustomField>
    <fullName>SBU_User__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ALT</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>C&amp;PS</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>E&amp;T</fullName>
            </value>
            <value>
                <fullName>EngPS</fullName>
            </value>
            <value>
                <fullName>EngPS BD</fullName>
            </value>
            <value>
                <fullName>EngPS OE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FNCE</fullName>
            </value>
            <value>
                <fullName>FNCE AMER</fullName>
            </value>
            <value>
                <fullName>FNCE APAC</fullName>
            </value>
            <value>
                <fullName>FNCE ELECSOL</fullName>
            </value>
            <value>
                <fullName>FNCE EMEA</fullName>
            </value>
            <value>
                <fullName>FNCE ENGPS</fullName>
            </value>
            <value>
                <fullName>FNCE MECH</fullName>
            </value>
            <value>
                <fullName>FNCE SERVCONN</fullName>
            </value>
            <value>
                <fullName>HBT</fullName>
            </value>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>HOS</fullName>
            </value>
            <value>
                <fullName>HOS CE</fullName>
            </value>
            <value>
                <fullName>HOS CE CRM</fullName>
            </value>
            <value>
                <fullName>HOS CE SO</fullName>
            </value>
            <value>
                <fullName>HOSG</fullName>
            </value>
            <value>
                <fullName>HOS PMO</fullName>
            </value>
            <value>
                <fullName>HOS PRICING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/Test_Contact_UpdateOwner.cls
/** * File Name: Test_Contact_UpdateOwner
* Description :Trigger to update owner
* Copyright : Wipro Technologies Limited Copyright (c) 2001 *
 * @author : Wipro
 * Modification Log =============================================================== **/
@isTest
private class Test_Contact_UpdateOwner{

    static testMethod void myUnitTest() {
    
        User MasterUsr= [select id from User where name = 'API User SFDC Cust Master'];
        Profile pf= [select id from Profile where name = 'Honeywell System Administrator'];
        // User usr1 = new User(LastName = 'TestUsrCont',Username = 'tuContact@test.com',Email = 'testuserContact@test.com',Alias = 'tcnt' ,CommunityNickname= 'tucont' ,TimeZoneSidKey = 'America/Los_Angeles',LocaleSidKey='en_US',EmailEncodingKey= 'ISO-8859-1',LanguageLocaleKey = 'en_US',SBU_User__c = 'D&S',IsActive= False,ProfileId = pf.Id);
        // insert usr1;
        User usr1 = new User(LastName = 'TestUsrCont',Username = 'tuContact@test.com',Email = 'testuserContact@test.com',Alias = 'tcnt' ,CommunityNickname= 'tucont' ,TimeZoneSidKey = 'America/Los_Angeles',LocaleSidKey='en_US',EmailEncodingKey= 'ISO-8859-1',LanguageLocaleKey = 'en_US',SBU_User__c = 'D&S',ProfileId = pf.Id);
        insert usr1;
        
        //creating account;
        Account acc= new Account(name='Test Contact Inactive Account');
        insert acc;

        //creating contact;
        Contact cont=new Contact(firstname='Test',LastName='Contact Inactive',AccountId=acc.Id,Phone_3__c='9986502456',
        Contact_Is_Employee__c=true,  Contact_Status__c='Active' ,Employee_Number__c='E534543',Employee_Contact_Role__c='Administrator',ownerid = usr1.Id );
        insert cont;
       
        // usr1.IsActive= False;
        // update usr1;
       
        // User Inactiveusr= [select id,IsActive  from User where  IsActive  =False limit 1];

       cont.ownerid =MasterUsr.id;
       update cont;
       
       cont.Contact_Status__c = 'Inactive';
       cont.OwnerId = Label.Inactive_Record_Owner_Id;
       update cont;
    }
}