src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Raw</businessProcess>
        <label>Outbound</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead/fields/Account_Address_line_1__c.field-meta.xml
<CustomField>
    <fullName>Account_Address_line_1__c</fullName>
    <label>Account Address line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Lead/fields/HONEYWELL_ID__c.field-meta.xml
<CustomField>
    <fullName>HONEYWELL_ID__c</fullName>
    <label>HONEYWELL ID</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

src/objects/Lead/fields/Reasons_for_Disqualification__c.field-meta.xml
<CustomField>
    <fullName>Reasons_for_Disqualification__c</fullName>
    <description>Reasons for Disqualification field for ATR, BGA,D&amp;S and GTO</description>
    <label>Reason for Disqualification/Recycle</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Lead/fields/Service_Bulletins__c.field-meta.xml
<CustomField>
    <fullName>Service_Bulletins__c</fullName>
    <label>Service Bulletins</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

src/classes/UpdateLeadCreator_Test.cls
@isTest
public class UpdateLeadCreator_Test {
    @isTest
    Public Static void testMethod1(){
       // Contact tstCon =[Select id,Honeywell_ID__c from contact where (not email like '%@honeywell.com') and Honeywell_ID__c != '' and  CreatedDate > 2015-08-03T05:35:18.000+0000 limit 1];
        Id  RID =Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Create C&PS Lead').getRecordTypeId();
        Lead lead = new Lead();
        lead.Status='Sales Qualified Lead (SQL)';
        lead.Account_Address_line_1__c='test';
        lead.LastName = 'Test';
        lead.Company = 'Honey';
        lead.HONEYWELL_ID__c= '547821';
        lead.RecordtypeID = RID;
        lead.Service_Bulletins__c = 'Test';
        //lead.LeadSource = 'Honeywell.com.cn';
        insert lead;
        
        lead.Status='Disqualified'; 
        lead.Reasons_for_Disqualification__c = 'test';
        update lead;
        
        Id  RID1 =Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Convert C&PS Lead').getRecordTypeId();
        Lead lead1 = new Lead();
        lead1.Status='Engaged';
        lead1.Account_Address_line_1__c='test';
        lead1.LastName = 'Test';
        lead1.Company = 'Honey';
        lead1.HONEYWELL_ID__c= '547821';
        lead1.RecordtypeID = RID1;
        lead1.Service_Bulletins__c = 'Test';
        //lead.LeadSource = 'Honeywell.com.cn';
        insert lead1;

        
    }
}