src/objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Raw</businessProcess>
        <label>Outbound</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead/fields/ATR_Product_Information__c.field-meta.xml
<CustomField>
    <fullName>ATR_Product_Information__c</fullName>
    <description>Aircraft / Platform
System/Product Line
Service (e.g., ISS)
Training (e.g., Training Academy)</description>
    <inlineHelpText>Enter the product or service of interest.</inlineHelpText>
    <label>Product Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Lead/fields/Lead_Market_Selection__c.field-meta.xml
<CustomField>
    <fullName>Lead_Market_Selection__c</fullName>
    <label>Lead Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Airlines/Cargo</fullName>
            </value>
            <value>
                <fullName>Business Aviation</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>General Aviation</fullName>
            </value>
            <value>
                <fullName>Helicopters</fullName>
            </value>
            <value>
                <fullName>Non-Aerospace</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>UAS - UAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Lead/fields/Lead_Region__c.field-meta.xml
<CustomField>
    <fullName>Lead_Region__c</fullName>
    <label>Lead Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
                <label>Asia/Pacific Rim</label>
            </value>
            <value>
                <fullName>EMEAI</fullName>
                <label>Europe/MiddleEast/Africa/India</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestLeadBuilder.cls
/**
 * Created by Haritha Lekkala on 4/30/2019.
 * OWNED BY THE CRM SALES TEAM.
 */

public class TestLeadBuilder {
    private String status = 'Inquiry';
    private String leadMarket = 'Business Aviation';
    private String leadRegion ='Americas';
    private String productInformation = 'Lead Record';
    private String company = 'Honeywell';
    private String lastName = 'LastName';
    private Map<String,Object> fields = new Map<String, Object>();

    public TestLeadBuilder() {}

    public TestLeadBuilder setStatus(String status) {
        this.status = status;

        return this;
    }
    public TestLeadBuilder setLeadMarket(String leadMarket){
        this.leadMarket = leadMarket;

        return this;
    }
    public TestLeadBuilder setLeadRegion(String leadRegion){
        this.leadRegion = leadRegion;

        return this;
    }
    public TestLeadBuilder setProductInformation(String ProductInformation){
        this.productInformation = ProductInformation;

        return this;
    }
    public TestLeadBuilder setCompany(String company){
        this.company = company;

        return this;
    }
    public TestLeadBuilder setLastName(String LastName){
        this.lastName = LastName;

        return this;
    }
    public TestLeadBuilder addField(String field, Object value) {
        fields.put(field, value);

        return this;
    }

    public Lead build(){
        Lead lead = new Lead();
        lead.Status = status;
        lead.Lead_Market_Selection__c = leadMarket;
        lead.Lead_Region__c = leadRegion;
        lead.ATR_Product_Information__c = productInformation;
        lead.Company = company;
        lead.LastName = lastName;

        for (String field: fields.keySet()) {
            Object value = fields.get(field);
            lead.put(field, value);
        }

        return lead;
    }

    public Lead generate() {
        Lead lead = build();
        Database.insert(lead);
        return lead;
    }

}