src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Opp_Update__c.field-meta.xml
<CustomField>
    <fullName>Opp_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opp Update</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.Win_Only_Opportunity__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/OppUpdate.cls
Public class OppUpdate {
    @future
    public static void opportunityfieldupdate(String oppId) {
        Opportunity[] opplist = new Opportunity[]{};
        List<Opportunity> opp = [select id, Opp_Update__c, Parent_Opportunity__c, Name from Opportunity where id=:oppId];
        if(opp!=null && opp.size()>0){
            for(Integer i=0;i<opp.size();i++){
                if(opp[i].Opp_Update__c == false)
                    opp[i].Opp_Update__c = true;
                else
                    opp[i].Opp_Update__c = false;
                opplist.add(opp[i]);
            }
        }
        if(opplist.size()>0 && opplist!=null){
            try{
                update opplist;
            }Catch(DMLException ee){}
        }
    }
}