src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/ATR_Aircraft_Quantity__c.field-meta.xml
<CustomField>
    <fullName>ATR_Aircraft_Quantity__c</fullName>
    <label>Aircraft Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Opportunity/fields/ATR_Probability__c.field-meta.xml
<CustomField>
    <fullName>ATR_Probability__c</fullName>
    <inlineHelpText>INFO ONLY: This field is read only and preserves the legacy probability value. User must populate the PWin field for the opportunity to progress.</inlineHelpText>
    <label>Estimated Win Probability</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/objects/Opportunity/fields/Certification_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Certification_Requirements__c</fullName>
    <inlineHelpText>Direct Commercial : Non-govt
FAR 12 Commercial: Comm’l procurement rules
FAR 15 (CIJ Response): Needs Comm&apos;l Item Justification
FAR 15 Competitive: Not sole-source
FAR 15 TINA: Needs certified cost/pricing data
Foreign Military Funded: Non-US govt</inlineHelpText>
    <label>Certification Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Commercial</fullName>
            </value>
            <value>
                <fullName>FAR 12 Commercial</fullName>
            </value>
            <value>
                <fullName>FAR 15 (CIJ Response)</fullName>
            </value>
            <value>
                <fullName>FAR 15 Competitive</fullName>
            </value>
            <value>
                <fullName>FAR 15 TINA</fullName>
            </value>
            <value>
                <fullName>Foreign Military Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/Program_Go_Probability__c.field-meta.xml
<CustomField>
    <fullName>Program_Go_Probability__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>INFO ONLY: This field is read only and preserves the legacy probability value. User must populate the PGo field for the opportunity to progress.</inlineHelpText>
    <label>Program Go Probability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/objects/Opportunity/fields/Push_Product_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Product_Date__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This box is checked by default - it will keep the date on the product and revenue aligned to the close date.</inlineHelpText>
    <label>Push Product Date</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/RFP_Expected_Date__c.field-meta.xml
<CustomField>
    <fullName>RFP_Expected_Date__c</fullName>
    <inlineHelpText>When would Honeywell receive the RFP? Should be entered by Launch stage</inlineHelpText>
    <label>RFP Expected Date</label>
    <type>Date</type>
</CustomField>

src/objects/Opportunity/fields/Tech_Sales_Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Tech_Sales_Product_Area__c</fullName>
    <inlineHelpText>Techincal Sales Product Area</inlineHelpText>
    <label>Tech Sales  Product Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tech_Sales__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Repair</fullName>
            </value>
            <value>
                <fullName>Adjacencies</fullName>
            </value>
            <value>
                <fullName>AGT1500</fullName>
            </value>
            <value>
                <fullName>AIMS/ VIA</fullName>
            </value>
            <value>
                <fullName>Air Cycle Systems</fullName>
            </value>
            <value>
                <fullName>Air Data Products</fullName>
            </value>
            <value>
                <fullName>Airframe Hydraulics</fullName>
            </value>
            <value>
                <fullName>Air Source Systems</fullName>
            </value>
            <value>
                <fullName>Air Turbine Start Systems &amp; Motors</fullName>
            </value>
            <value>
                <fullName>ALF502 / LF507</fullName>
            </value>
            <value>
                <fullName>APU 131</fullName>
            </value>
            <value>
                <fullName>APU 331</fullName>
            </value>
            <value>
                <fullName>APU 331 Large</fullName>
            </value>
            <value>
                <fullName>APU 36-100</fullName>
            </value>
            <value>
                <fullName>APU 36-150</fullName>
            </value>
            <value>
                <fullName>APU 36-155</fullName>
            </value>
            <value>
                <fullName>APU 36-200</fullName>
            </value>
            <value>
                <fullName>APU 36-280 / 36-300</fullName>
            </value>
            <value>
                <fullName>APU 36-50/55</fullName>
            </value>
            <value>
                <fullName>APU 660 / 700</fullName>
            </value>
            <value>
                <fullName>APU 85</fullName>
            </value>
            <value>
                <fullName>APU AMADs</fullName>
            </value>
            <value>
                <fullName>APU G250</fullName>
            </value>
            <value>
                <fullName>APU HGT1700</fullName>
            </value>
            <value>
                <fullName>APU HGT750</fullName>
            </value>
            <value>
                <fullName>APU Jet Fuel Starter</fullName>
            </value>
            <value>
                <fullName>APU JSF</fullName>
            </value>
            <value>
                <fullName>APU Misc Adv Tech</fullName>
            </value>
            <value>
                <fullName>APU Other D&amp;S</fullName>
            </value>
            <value>
                <fullName>APU RE100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APO</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
                <default>true</default>
                <label>Forecast</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Tech_Sales_Product_Area__c/Tech_Sales_Product_Area__c.object-meta.xml
<CustomObject>
    <label>Tech Sales Product Area</label>
    <nameField>
        <label>Tech Sales Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tech Sales Product Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/preventScheduleChange_Testcls.cls
@isTest
private class preventScheduleChange_Testcls{
static testmethod void preventScheduleChange_TstMthd(){
 
  Profile ProfRec = [select name from Profile where name = 'System Administrator'];
        User userRec = new User(LastName = 'Test',Username = 'testingHC@testHC.com',Email = 'test@test.com',Alias = 'Testing' ,
        CommunityNickname= 'Test' ,TimeZoneSidKey = 'America/Los_Angeles',LocaleSidKey='en_US',
        EmailEncodingKey= 'ISO-8859-1',ProfileId = ProfRec.Id, LanguageLocaleKey = 'en_US');
        insert userRec;
 
Date dl1 =Date.newInstance(2009,08,1);
Date dl2 =Date.newInstance(2009,09,12);
Date dl3 =Date.newInstance(2009,08,2);
   Test.startTest();
    Account acc=new Account();
    acc.name='Sample';
    insert acc;
            
    Opportunity opp=new Opportunity();
    opp.Name='Sample Opp';
    opp.Account=acc;
    opp.accountid=acc.id;
    opp.stageName='Cultivate';
    opp.closeDate=System.today();
    opp.Tech_Sales_Product_Area__c='Integrated Avionics';
    opp.Certification_Requirements__c = 'Direct Commercial';
    opp.CloseDate=Date.today();
    opp.RFP_Expected_Date__c = System.today();
    opp.ATR_Aircraft_Quantity__c = 1;
    insert opp;
    
    Pricebook2 pb = [select name, isactive from Pricebook2 where IsStandard = true Limit 1];
Product2 prdNew=new Product2(Name='NewProduct',ProductCode='xxx');
insert prdNew;
PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.id,Product2Id   = prdNew.id,IsActive     = true,     UnitPrice    = 1); 
    insert pbe;
    
    OpportunityLineItem LineItem=new OpportunityLineItem( OpportunityId=opp.Id,ServiceDate=dl1,quantity=10,pricebookentryid =pbe.Id,UnitPrice= 1,type__c='APO');
insert LineItem;
      
LineItem.quantity=12;
LineItem.TotalPrice=6;
System.runAs ( userRec) { 
try{
update LineItem;
}
catch(System.DMLException e){System.assert(e.getMessage().contains(
                'Schedule can be changed only by an admin'),
                  e.getMessage());
      }
      }
Test.stopTest();
}

 static testMethod void preventScheduleChange_TstMthd1()    
    {
        Test.startTest();
        
        OpportunityLineItem oppLine = [select OpportunityID from OpportunityLineItem where ServiceDate<>null and Type__c = 'Forecast' limit 1];
        Opportunity opp = [select id,CloseDate from Opportunity where CloseDate<>null and id =:oppLine.OpportunityID limit 1];
        opp.CloseDate = opp.CloseDate+1;
        opp.Push_Product_Date__c = true;
        opp.ATR_Probability__c = 10;
        opp.Program_Go_Probability__c = 10;
        update opp;
        
        Test.stopTest();
    }
}