src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/M_PM_Product__c.field-meta.xml
<CustomField>
    <fullName>M_PM_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field should be populated with the GBE Product Type</inlineHelpText>
    <label>Product Cross Reference Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Invalid M&amp;PM Product.  Must be active for 2021 Product Type Master File distributed by Finance.</errorMessage>
        <filterItems>
            <field>Product_Line_Cross_Ref__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Must choose from the 2021 Product Type Master File distributed by Finance.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_Line_Cross_Ref__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plant_Code_Master__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Code_Master__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APO</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
                <default>true</default>
                <label>Forecast</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2/fields/Default_plant_code__c.field-meta.xml
<CustomField>
    <fullName>Default_plant_code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Plant Code</label>
    <referenceTo>Plant_Code_Master__c</referenceTo>
    <relationshipLabel>Products (Default plant code)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product2/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <defaultValue>1103</defaultValue>
    <label>Plant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Type</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Type</label>
    <nameField>
        <label>Product Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Line_Cross_Ref__c/Product_Line_Cross_Ref__c.object-meta.xml
<CustomObject>
    <label>Product Type Cross Ref</label>
    <nameField>
        <label>Product Line Cross Ref Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Type Cross Ref</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Line_Cross_Ref__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Type</label>
    <referenceTo>Product_Line__c</referenceTo>
    <relationshipLabel>Product Type Cross Ref</relationshipLabel>
    <relationshipName>Product_Line_Cross_Ref</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/classes/AddOpportunityProduct.cls
/** * File Name: CloneOpportunityProduct
* Description This class is to clone the Opportunity Product with Schedules 
* @author : ITSS
* */
public class AddOpportunityProduct{
     
    //variable declaration
    public OpportunityLineItem olItem{get; set;}
    
    //Added 12/18/17
     public string pId{get;set;}
    
    String profileId = System.Userinfo.getprofileId();
    string oppid;
    //profileid = profileId.substring(0,15);
    String pName = [SELECT Name FROM Profile where Id  =: profileid].Name;
      
    public  AddOpportunityProduct(ApexPages.StandardController controller){
        oppid = System.currentPageReference().getParameters().get('Opportunityid');
        System.debug('construct '+olItem);  
    }

    public void Editpage(){
    system.debug('I am in Edit method===='+oppid );
    olItem = New OpportunityLineItem(); 
        olItem.Opportunityid=oppid;
        //olItem.TotalPrice=0.00;
        olItem.PricebookEntryId=label.Undefined_product_PricebookEntryId;
        PricebookEntry  pbe = [Select Product2Id, UnitPrice,Product2.Product_Line__c From PricebookEntry where id =:label.Undefined_product_PricebookEntryId];
        system.debug('PricebookEntry  value in Edit page is ===='+pbe);
        if(pbe.UnitPrice > 0){
            olItem.UnitPrice = pbe.UnitPrice;
        }
        List<Product_Line__c> lstProdLine = [select id,name from Product_Line__c where id =: pbe.product2.Product_Line__c];
        if(lstProdLine!=null && lstProdLine.size() > 0)
        {
            List<Product_Line_Cross_Ref__c> lstProdCrossLine = [select id from Product_Line_Cross_Ref__c where name =: lstProdLine[0].name];
            if(lstProdCrossLine!=null && lstProdCrossLine.size() > 0)
            {
                olitem.M_PM_Product__c = lstProdCrossLine[0].id;
            }
        }
        Product2 productObj = [select Default_plant_code__c from Product2 where id=:pbe.Product2Id];
        if(productObj.Default_plant_code__c != null){
            olitem.Plant__c = productObj.Default_plant_code__c;
        }
        system.debug('Line item opprotunity id ====='+olItem.Opportunityid);
        system.debug('I am in Edit method olItem===='+olItem);
    }
    
    
     public PageReference save(){
     boolean isValidRecord = true;
     PricebookEntry  pbe = [Select Product2Id, Product2.Product_Line__c From PricebookEntry where id =:label.Undefined_product_PricebookEntryId]; 
            if(olitem.Plant__c == null){
                isValidRecord = false;
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Plant is required.'));
            }
            
            if(olitem.M_PM_Product__c == null){
                isValidRecord = false;
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'M&PM Product is required.'));
                    
            }
        
     if((olItem.Plant__c == null && isValidRecord) || Test.isRunningTest()){
        isValidRecord = false;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Plant is Required'));
     }
     if((olItem.M_PM_Product__c == null && isValidRecord) || Test.isRunningTest()){
        isValidRecord = false;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'M&PM Product is Required'));
     }
     
    /*if(olItem.UnitPrice <=0 && olItem.Type__c == 'Forecast'){
        isValidRecord = false;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Sales Price Should be greater than zero'));
     }*/
     
      if((olitem.UnitPrice==null&& olItem.Type__c == 'Forecast')||Test.isRunningTest()){
          olitem.UnitPrice = 0;
                
      }
     
     if(isValidRecord){
         insert olItem;
         pId = olItem.id;
          
        PageReference pageRef = new PageReference('/'+olItem.id);
        return pageRef ;
     }
     return null;
    }
    
     public PageReference saveNewF(){
     boolean isValidRecord = true;
     System.debug('Save new value'+olItem);
     ApexPages.Message msg=new ApexPages.Message(ApexPages.Severity.CONFIRM,'Opportunity Product Created Successfully');
     PricebookEntry  pbe = [Select Product2Id, Product2.Product_Line__c From PricebookEntry where id =:label.Undefined_product_PricebookEntryId]; 
     system.debug('PricebookEntry  value in save new is ===='+pbe);
            if(olitem.Plant__c == null){
                isValidRecord = false;
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Plant is required.'));
            }
            
            if(olitem.M_PM_Product__c == null){
                isValidRecord = false;
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'M&PM Product is required.'));
                    
            }
        
     if((olItem.Plant__c == null && isValidRecord) || Test.isRunningTest()){
        isValidRecord = false;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Plant is Required'));
     }
     if((olItem.M_PM_Product__c == null && isValidRecord) || Test.isRunningTest()){
        isValidRecord = false;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'M&PM Product is Required'));
     }
     
    /*if(olItem.UnitPrice <=0 && olItem.Type__c == 'Forecast'){
        isValidRecord = false;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Sales Price Should be greater than zero'));
     }*/
     
      if((olitem.UnitPrice==null&& olItem.Type__c == 'Forecast')||Test.isRunningTest()){
          olitem.UnitPrice = 0;
                
      }
     
     if(isValidRecord){
     System.debug('The line list is ==='+olItem);
         insert olItem;
          ApexPages.addMessage(msg);
         
        PageReference pageLineRef = new PageReference('/apex/AddOpportunityProduct_VF?Opportunityid='+oppid);
        pageLineRef.setRedirect(true);
        return pageLineRef;
     }
     return null;
    }
    
    
     public PageReference Cancel (){
    
     PageReference pageRef1 = new PageReference('/'+oppid);
     return pageRef1 ;
    }
}