src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Avionics_Count__c.field-meta.xml
<CustomField>
    <fullName>Avionics_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Avionics_Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Record Type</label>
</CustomObject>

src/objects/Opportunity_Product_Line__c/Opportunity_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Line</label>
    <nameField>
        <displayFormat>OPL-{00000}</displayFormat>
        <label>Opportunity Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Product_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Avionics BFE/SSFE Suite Detail</relationshipLabel>
    <relationshipName>Opportunity_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/OpportunityProductLineHelper.cls
public with sharing class OpportunityProductLineHelper {
 public void updateLineItemCount(set < string > deskIDs) {
  if (deskIDs == null) {
   return;
  }
  if (deskIDs.size() == 0) {
   return;
  }
  list <Opportunity_Product_Line__c> deskList = new list <Opportunity_Product_Line__c> ();
  deskList = [Select ID,Opportunity__c From Opportunity_Product_Line__c Where Opportunity__c =: deskIDs];
  integer totalCount;
  
  map < string, integer > classroomIDToDeskCountMap = new map < string, integer > ();
  
  for (Opportunity_Product_Line__c deskItem: deskList) {
   if (classroomIDToDeskCountMap.containsKey(deskItem.Opportunity__c)) {
    totalCount = classroomIDToDeskCountMap.get(deskItem.Opportunity__c);
   } else {
    totalCount = 0;
   }
   totalCount += 1;
   classroomIDToDeskCountMap.put(deskItem.Opportunity__c, totalCount);
  }
  if(deskList.size()==0){
    for(String str:deskIDs){
        classroomIDToDeskCountMap.put(str, 0);
    }   
  }
  list < Opportunity > deskUpdateList = new list < Opportunity > ();
  Opportunity deskTemp;
  for (string deskID: classroomIDToDeskCountMap.keySet()) {
   deskTemp = new Opportunity();
   deskTemp.ID = deskID;
   deskTemp.Avionics_Count__c = classroomIDToDeskCountMap.get(deskID);
   deskUpdateList.add(deskTemp);
  }
  if (deskUpdateList.size() > 0) {
   update deskUpdateList;
  }
 }
}