src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Account_Name_formula__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_formula__c</fullName>
    <description>This is for Coding Purpose.</description>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name formula</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Close_Date_Formula__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_Formula__c</fullName>
    <formula>TEXT(MONTH( CloseDate ))+&apos;/&apos;+TEXT(DAY(CloseDate))+&apos;/&apos;+TEXT(YEAR(CloseDate))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Close Date Formula</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

src/objects/Opportunity/fields/Opportunity_Owner_formula__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_formula__c</fullName>
    <description>This is for Coding purpose.</description>
    <formula>Opportunity_Owner_First_Name__c + &quot; &quot; + Opportunity_Owner_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Owner formula</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Platform_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name_Formula__c</fullName>
    <description>Used for coding purpose.</description>
    <formula>Platform__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform Name Formula</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Product_Line_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Product_Group__c</fullName>
    <label>Product Type GBE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Services</fullName>
            </value>
            <value>
                <fullName>Aerospace Services</fullName>
            </value>
            <value>
                <fullName>Air &amp; Thermal Systems</fullName>
            </value>
            <value>
                <fullName>APU</fullName>
            </value>
            <value>
                <fullName>Auxiliary Power and Thermal Systems</fullName>
            </value>
            <value>
                <fullName>BendixKing</fullName>
            </value>
            <value>
                <fullName>Cockpit Systems</fullName>
            </value>
            <value>
                <fullName>Electric Power</fullName>
            </value>
            <value>
                <fullName>Electric Power and Lighting</fullName>
            </value>
            <value>
                <fullName>Engines</fullName>
            </value>
            <value>
                <fullName>Lighting</fullName>
            </value>
            <value>
                <fullName>Mechanical Components</fullName>
            </value>
            <value>
                <fullName>Navigation &amp; Sensors</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Propulsion</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Information Management</fullName>
            </value>
            <value>
                <fullName>Safety and Connectivity</fullName>
            </value>
            <value>
                <fullName>Wheels &amp; Brakes</fullName>
            </value>
            <value>
                <fullName>Wheels and Braking Systems</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <inlineHelpText>SBU responsible for this opportunity</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/VF_Template_Controller.cls
Public class VF_Template_Controller{
    List<Opportunity> Opps = new List<Opportunity>();
    List<String> optyOwner=new List<String>();
    List<Id> oppIds=new List<Id>();
    Public List<Opportunity> getClosedYest(){
        Date yest=System.today()-1;
Opps=[Select SBU__c,StageName,Opportunity_Number__c,Description,Close_Date_Formula__c,Name,Amount,Account_name_formula__c,opportunity_owner_formula__c,Platform_Name_Formula__c,Product_line_Product_group__c,(Select title,IsPrivate from NotesAndAttachments) from Opportunity where SBU__c=:'ATR' and CloseDate=:yest and StageName=:'Closed Won'];
        /*for(Integer i=0;i<Opps.size;i++)
            Opps[i].Amount*/
        System.debug('Closed yest'+opps);
        if(opps.size()>0)
            return opps;
        else
            return null;
    }
}