src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Close_date_changed__c.field-meta.xml
<CustomField>
    <fullName>Close_date_changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Close date changed</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity/fields/Revenue_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Start_Date__c</fullName>
    <description>Revenue Start Date</description>
    <label>Revenue Start Date</label>
    <summarizedField>OpportunityLineItem.Revenue_Start_Date__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Revenue_Start_Date__c</field>
        <operation>notEqual</operation>
        <value/>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/OpportunityLineItem/fields/Revenue_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Start_Date__c</fullName>
    <inlineHelpText>To modify Revenue Start date please edit Revenue Schedule</inlineHelpText>
    <label>Revenue Start Date</label>
    <type>Date</type>
</CustomField>

src/classes/RedirecttoSchedule.cls
public class RedirecttoSchedule
{
    private final Opportunity opp;
    public list<OpportunityLineItem>OpportunityLineItemlist {get;set;}
    public string opplineid{get;set;}
    public Id oppid{get;set;}
    public Opportunity opplist{get;set;}
    public Boolean closedatechange{get;set;}
    public Boolean popvariable{get;set;}
    public redirecttoschedule(ApexPages.StandardController stdController )
    {
        oppid=stdController.getId();
        this.opp=[select id,Close_date_changed__c from opportunity where id=:oppid];
        closedatechange=opp.Close_date_changed__c;
        OpportunityLineItemlist =[select id,OpportunityId, Revenue_Start_Date__c from OpportunityLineItem where OpportunityId=:opp.id and Revenue_Start_Date__c != null order by createddate desc limit 1];
        if(OpportunityLineItemlist.size()>0)
         opplineid=OpportunityLineItemlist[0].Id;
        //popvariable=false;
    }
    public void updatesave()
    {
       system.debug('inside update********');
       opp.Close_date_changed__c=false;
       Update opp;
       popvariable=true;
    }
}