src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <businessProcess>Sales</businessProcess>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Record Type</label>
</CustomObject>

src/objects/Opportunity_Sales_Team__c/Opportunity_Sales_Team__c.object-meta.xml
<CustomObject>
    <label>Opportunity Team</label>
    <nameField>
        <displayFormat>OT-{0}</displayFormat>
        <label>Opportunity Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Sales_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sales_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Opportunity_Sales_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Sales_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains Email Id of &apos;ATR Opportunity Scheduled Report&apos; recipients</description>
    <label>Users</label>
</CustomObject>

src/classes/TestOpportunityTeamBuilder_Test.cls
/**
 * Created by Satya Mohanty on 4/25/2019.
 * OWNED BY THE CRM SALES TEAM.
 */
@IsTest
private class TestOpportunityTeamBuilder_Test {
    private static Opportunity testOpportunity;
    private static User user;
    private static final String BENDIXKING = 'Bendixking';
    private static void init() {
        testOpportunity = new TestOpportunityBuilder( 'Test', BENDIXKING )
                .generate();
        user = new TestUserBuilder()
                .generate();
    }
    @IsTest
    static void testDefaultBuild() {
        init();
        System.Test.startTest();
        Opportunity_Sales_Team__c opportunityTeam = new TestOpportunityTeamBuilder()
                .setUserId(user.Id)
                .build();
        System.Test.stopTest();

        System.assertEquals(null, opportunityTeam.Id);
        System.assertEquals(user.Id, opportunityTeam.User__c);
    }
    @IsTest
    static void testGenerateWithaddfield() {
        init();
        System.Test.startTest();
        Opportunity_Sales_Team__c opportunityTeam = new TestOpportunityTeamBuilder()
                .setUserId(user.Id)
                .addField('Opportunity__c', testOpportunity.Id)
                .generate();
        System.Test.stopTest();

        Opportunity_Sales_Team__c insertedOpportunityTeam = [
                SELECT Id
                FROM Opportunity_Sales_Team__c
                WHERE User__c = :user.Id
                AND Opportunity__c = :testOpportunity.Id
        ];
        System.assertEquals(insertedOpportunityTeam.Id, opportunityTeam.Id);
        System.assertEquals(user.Id, opportunityTeam.User__c);
        System.assertEquals(testOpportunity.Id, opportunityTeam.Opportunity__c);

    }
}