src/objects/Product2.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Product2/fields/Hours_of_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Hours_of_Instruction__c</fullName>
    <label>Hours of Instruction</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

src/objects/Product2/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level I</fullName>
                <default>true</default>
                <label>Level I</label>
            </value>
            <value>
                <fullName>Level II</fullName>
            </value>
            <value>
                <fullName>Level III</fullName>
            </value>
            <value>
                <fullName>Level IV</fullName>
            </value>
            <value>
                <fullName>Level V</fullName>
            </value>
            <value>
                <fullName>O Level</fullName>
            </value>
            <value>
                <fullName>I Level</fullName>
            </value>
            <value>
                <fullName>D Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Product2/fields/Per_student_Price__c.field-meta.xml
<CustomField>
    <fullName>Per_student_Price__c</fullName>
    <label>Per-student Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Product2/fields/Prerequisites__c.field-meta.xml
<CustomField>
    <fullName>Prerequisites__c</fullName>
    <label>Prerequisites</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Product2/fields/Who_Should_Attend__c.field-meta.xml
<CustomField>
    <fullName>Who_Should_Attend__c</fullName>
    <label>Who Should Attend</label>
    <type>TextArea</type>
</CustomField>

src/classes/HwTrng_Coursedetail_cls.cls
public class HwTrng_Coursedetail_cls {

Product2 c = new Product2();
public void getdetails()
{
Id  i = ApexPages.currentPage().getParameters().get('id');
 c  = [select name,Description,Level__c,Prerequisites__c,Who_Should_Attend__c,Hours_Of_Instruction__c,Per_student_Price__c,Duration__c  from Product2 where id =:i]; 

}
public Product2 getprod()
{
return c;
}
/*public String getName()
{
return c.name;
}
public String getDescription()
{
return c.Description;
}
public String getlevel()
{
return c.Level__c;
}
public String getPrerequisites()
{
return c.Prerequisites__c;
}
public String getwho()
{
return c.Who_Should_Attend__c;
}
public decimal gethours()
{
return c.Hours_Of_Instruction__c ;
}

public decimal getprice()
{
return c.Per_student_Price__c ;
}
public String getduration()
{
return c.Duration__c ;
}*/
}