src/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <label>Contact Address</label>
    <nameField>
        <label>SFDC Row ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c/fields/Amenities__c.field-meta.xml
<CustomField>
    <fullName>Amenities__c</fullName>
    <label>Amenities</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Location__c/fields/Contact_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address__c</fullName>
    <formula>Primary_Contact__r.FirstName+&apos; &apos;+ Primary_Contact__r.LastName+&apos;,&apos;+ Primary_Contact__r.MobilePhone +&apos;,&apos;+
Primary_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Address</label>
    <type>Text</type>
</CustomField>

src/objects/Location__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Location__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Location</relationshipLabel>
    <relationshipName>Location</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Location__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>$RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

src/objects/Location__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Location__c/fields/Transportation_Provided__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Provided__c</fullName>
    <label>Transportation Provided</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not provided</fullName>
                <default>true</default>
                <label>Not provided</label>
            </value>
            <value>
                <fullName>Provided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/HWTRNG_TrngHotel_cls.cls
public class HWTRNG_TrngHotel_cls {

String str = ApexPages.currentPage().getParameters().get('region');

public String getstr(){
return str;
}
List<Location__c> strlist = new List<Location__c>();
public List<Location__c> getallregions()
{
 List<Location__c> loclist = [select name , id,region__c,street__c,city__c,postal_code__c,state__c,
    Amenities__c,Primary_Contact__c,Transportation_Provided__c,Distance__c,Contact_Address__c
 from
 Location__c where region__c = :str and record_type_name__c='Hotel' ]; 

return loclist;
}
}