src/objects/Aircraft_Base__c/Aircraft_Base__c.object-meta.xml
<CustomObject>
    <description>This object contains list of all the aircraft bases, city country and region.</description>
    <label>Aircraft Base ( Airport )</label>
    <nameField>
        <label>Aircraft Base Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Bases  ( Airports )</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Aircraft_Base__c/fields/Base_ICAO__c.field-meta.xml
<CustomField>
    <fullName>Base_ICAO__c</fullName>
    <label>Base ICAO</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Base__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ALABAMA</fullName>
            </value>
            <value>
                <fullName>ALASKA</fullName>
            </value>
            <value>
                <fullName>ARIZONA</fullName>
            </value>
            <value>
                <fullName>ARKANSAS</fullName>
            </value>
            <value>
                <fullName>CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>COLORADO</fullName>
            </value>
            <value>
                <fullName>CONNECTICUT</fullName>
            </value>
            <value>
                <fullName>DELAWARE</fullName>
            </value>
            <value>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </value>
            <value>
                <fullName>FLORIDA</fullName>
            </value>
            <value>
                <fullName>GEORGIA</fullName>
            </value>
            <value>
                <fullName>HAWAII</fullName>
            </value>
            <value>
                <fullName>IDAHO</fullName>
            </value>
            <value>
                <fullName>ILLINOIS</fullName>
            </value>
            <value>
                <fullName>INDIANA</fullName>
            </value>
            <value>
                <fullName>IOWA</fullName>
            </value>
            <value>
                <fullName>KANSAS</fullName>
            </value>
            <value>
                <fullName>KENTUCKY</fullName>
            </value>
            <value>
                <fullName>LOUISIANA</fullName>
            </value>
            <value>
                <fullName>MAINE</fullName>
            </value>
            <value>
                <fullName>MARYLAND</fullName>
            </value>
            <value>
                <fullName>MASSACHUSETTS</fullName>
            </value>
            <value>
                <fullName>MICHIGAN</fullName>
            </value>
            <value>
                <fullName>MINNESOTA</fullName>
            </value>
            <value>
                <fullName>MISSISSIPPI</fullName>
            </value>
            <value>
                <fullName>MISSOURI</fullName>
            </value>
            <value>
                <fullName>MONTANA</fullName>
            </value>
            <value>
                <fullName>NEBRASKA</fullName>
            </value>
            <value>
                <fullName>NEVADA</fullName>
            </value>
            <value>
                <fullName>NEW HAMPSHIRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Account_SBU__c.field-meta.xml
<CustomField>
    <fullName>Account_SBU__c</fullName>
    <formula>text(Account__r.Strategic_Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Aircraft_Base__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Base__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft Base</label>
    <referenceTo>Aircraft_Base__c</referenceTo>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/AMSTAT_base_ICAO__c.field-meta.xml
<CustomField>
    <fullName>AMSTAT_base_ICAO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AMSTAT Base ICAO</label>
    <referenceTo>Aircraft_Base__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (AMSTAT Base ICAO)</relationshipLabel>
    <relationshipName>Fleet_Asset_Aircraft1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Base_ICAO__c.field-meta.xml
<CustomField>
    <fullName>Base_ICAO__c</fullName>
    <formula>Aircraft_Base__r.Base_ICAO__c</formula>
    <label>Base ICAO</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cntry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestmodifyAircraftData.cls
/**
 * OWNED BY THE CRM SALES TEAM.
 */
@IsTest (SeeAllData = true)
public class TestmodifyAircraftData{
    testMethod static void testAircraft(){
        Fleet_Asset_Detail__c fad = [SELECT Id,Name,AMSTAT_base_ICAO__c FROM Fleet_Asset_Detail__c WHERE Base_ICAO__c<>NULL AND State__c<>NULL LIMIT 1];
        update fad;
        fad = [SELECT Id,Name,AMSTAT_base_ICAO__c FROM Fleet_Asset_Detail__c WHERE Base_ICAO__c=NULL AND State__c<>NULL LIMIT 1];
        update fad;
        
        fad = [SELECT Id,Name,AMSTAT_base_ICAO__c FROM Fleet_Asset_Detail__c WHERE AMSTAT_base_ICAO__c<>NULL AND Account_SBU__c='BGA' LIMIT 1];
        update fad;
        
        fad = [SELECT Id,Name,AMSTAT_base_ICAO__c FROM Fleet_Asset_Detail__c WHERE Aircraft_Base__c=NULL AND Admin__c=false LIMIT 1];
        update fad;
    }
}