src/objects/Discretionary_Plan__c/Discretionary_Plan__c.object-meta.xml
<CustomObject>
    <description>Discretionary Plan : New related list in opportunity</description>
    <label>Discretionary Plan</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Discretionary Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discretionary Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Discretionary_Plan__c/fields/Carry_Over__c.field-meta.xml
<CustomField>
    <fullName>Carry_Over__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If DR Spend carried over from last year</description>
    <label>Carry Over</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Discretionary_Plan__c/fields/DLI_Spent__c.field-meta.xml
<CustomField>
    <fullName>DLI_Spent__c</fullName>
    <label>DLI Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Discretionary_Plan__c/fields/DR_Funded__c.field-meta.xml
<CustomField>
    <fullName>DR_Funded__c</fullName>
    <label>DR Approved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Discretionary_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Discretionary Plans</relationshipLabel>
    <relationshipName>Discretionary_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Discretionary_Plan__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
                <default>true</default>
                <label>2021</label>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Record Type</label>
</CustomObject>

src/classes/UpdateCarryOverDP.cls
global class UpdateCarryOverDP {
    
    public static boolean flag = true; 
    public static void updateCarryOver(List<Id> opptyId, Set<String> Yearset, List<Discretionary_Plan__c> dp ){
    List<Discretionary_Plan__c> DR = new List<Discretionary_Plan__c>();   
    try{
        DR = [Select Id, Carry_Over__c, Year__c, Opportunity__c,DLI_Spent__c,DR_Funded__c from Discretionary_plan__c where Opportunity__c in :opptyId order by Year__c,Opportunity__c ];
    }
    catch(Exception e){
    }
    
    //Boolean flg = false;  
    //for(Integer k=0; k<dp.size();k++){
       for(integer i=0;i<DR.size()-1;i++){
       //System.debug('Year1 : '+DR[i].Year__c + ' Year2 : '+year);
       //DR[i].Opportunity__c == dp[k].Opportunity__c &&
         if( DR[i].Year__c < DR[i+1].Year__c && DR[i].DLI_Spent__c != 0){
             //flg = true;
             DR[i+1].Carry_Over__c = true;
         }else {
             //flg = false;
             DR[i+1].Carry_Over__c = false;
         }
         /*
         if(flg == true){
           DR[i+1].Carry_Over__c = true;
           //dptot.Carry_Over__c = true;
         }else{
           DR[i+1].Carry_Over__c = false;
           //dptot.Carry_Over__c = false;
         }*/
       }
       
    //}
      if(DR.size()>0){  
        try {
            update DR;
        }catch(Exception ex){} 
      }     
    } 
}