src/objects/Development_Action__c/Development_Action__c.object-meta.xml
<CustomObject>
    <description>Sales Competency, Sales Competency Rating, and Development Action custom objects make up the PMT Sales Competency module for assessing sales employees on selling competencies and identifying growth/development areas.</description>
    <label>Development Action</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Development Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Development_Action__c/fields/Action_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Action_Accepted__c</fullName>
    <label>Action Accepted</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Development_Action__c/fields/Sales_Competency_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Sales_Competency_Assessment__c</fullName>
    <label>Sales Competency Assessment</label>
    <referenceTo>Sales_Competency__c</referenceTo>
    <relationshipLabel>Development Actions</relationshipLabel>
    <relationshipName>Sales_Competency_Development_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Sales_Competency__c/Sales_Competency__c.object-meta.xml
<CustomObject>
    <description>Sales Competency, Sales Competency Rating, and Development Action custom objects make up the PMT Sales Competency module for assessing sales employees on selling competencies and identifying growth/development areas.</description>
    <label>Sales Competency</label>
    <nameField>
        <label>Sales Competency Assessment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Competency</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Competency__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <label>Job Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Leader</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Sales_Competency__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

src/objects/Sales_Competency__c/fields/Level_1_Manager__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 1 Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Competency1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Sales_Competency__c/fields/Role_Category__c.field-meta.xml
<CustomField>
    <fullName>Role_Category__c</fullName>
    <inlineHelpText>If the manager changes the employee&apos;s role category, which also changes the competency expectations for the role, then a reason for the change must be provided.</inlineHelpText>
    <label>Role Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Sales_Competency__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Defines the status of the assessment process and who owns step:
Step 0: In Process
Step 1: Draft (Manager)
Step 2: In Review (Employee)
Step 3: Review Action Plan (Manager)
Step 4: Final Approval (Manager)

(Opt Out - Employee will not be assessed)</inlineHelpText>
    <label>Status (Owner)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self Assessment (Employee)</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>Self Assessment (Employee)</label>
            </value>
            <value>
                <fullName>Draft (Manager)</fullName>
                <color>#E27001</color>
                <label>Draft (Manager)</label>
            </value>
            <value>
                <fullName>In Review (Employee)</fullName>
                <color>#A845DC</color>
                <label>In Review (Employee)</label>
            </value>
            <value>
                <fullName>Review Action Plan (Manager)</fullName>
                <color>#33CCFF</color>
                <label>Review Action Plan (Manager)</label>
            </value>
            <value>
                <fullName>Final Approval (Manager)</fullName>
                <color>#78C953</color>
                <label>Final Approval (Manager)</label>
            </value>
            <value>
                <fullName>Opt Out</fullName>
                <color>#A53711</color>
                <label>Opt Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Sales_Competency__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Competency</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/Level_1_Manager__c.field-meta.xml
<CustomField>
    <fullName>Level_1_Manager__c</fullName>
    <description>User&apos;s First Level Manager for Sales Competency Sharing.</description>
    <label>Level 1 Manager</label>
    <relationshipName>Level_1_Manager</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains Email Id of &apos;ATR Opportunity Scheduled Report&apos; recipients</description>
    <label>Users</label>
</CustomObject>

src/classes/DevelopmentactionEditableGrid_Test.cls
@isTest
public With Sharing Class DevelopmentactionEditableGrid_Test 
{

    static Testmethod Void DAEG_test1()
    {
        
         String userAgent='iPad';
         
         //Profile p = [SELECT Id,name FROM Profile WHERE Name='Salesforce'];
         User u = [ select Id from User where id =: UserInfo.getUserId() ];
         
         Sales_Competency__c sc = new Sales_Competency__c();
         sc.user__c = u.id;
         sc.Job_Title__c = 'sales';
         sc.Status__c = 'Self Assessment (Employee)';
         sc.Role_Category__c = 'A';
         sc.Job_Category__c = 'Sales';
         sc.Name = 'test';
         sc.Level_1_Manager__c = u.id;
         insert sc;
         system.debug('-------------------sc---------------' +sc);
      
         
         test.StartTest();
         Development_Action__c DA = new Development_Action__c();
         DA.Sales_Competency_Assessment__c = sc.id;
         DA.Action_Accepted__c = 'yes';
         insert DA;
         
         Test.setCurrentPageReference(new PageReference('/'+DA.Id));
         DevelopmentactionEditableGrid DAEG = new DevelopmentactionEditableGrid(new ApexPages.StandardController(sc));
         DAEG.saveId = DA.id;
         DAEG.strSCId = DA.id;
         DAEG.getSalesCompetencies();
         DAEG.saveRecord();
         DAEG.cancel();
         
         test.StopTest();
         
      }
      
}