src/objects/Aero_China_Kaizen__c/Aero_China_Kaizen__c.object-meta.xml
<CustomObject>
    <description>This object is created for the POC of Aero China team to capture Kaizen as a part of HOS journey and evaluate Force.com platform</description>
    <label>Kaizen</label>
    <nameField>
        <label>Kaizen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kaizens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Aero_China_Kaizen__c/fields/Action_Owner__c.field-meta.xml
<CustomField>
    <fullName>Action_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action Owner</label>
    <referenceTo>Kaizen_Users__c</referenceTo>
    <relationshipLabel>Kaizens (Action Owner)</relationshipLabel>
    <relationshipName>Kaizens1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Aero_China_Kaizen__c/fields/Dept__c.field-meta.xml
<CustomField>
    <fullName>Dept__c</fullName>
    <label>Dept</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>P&amp;E</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>HSE&amp;F</fullName>
            </value>
            <value>
                <fullName>HOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Aero_China_Kaizen__c/fields/Kaizen_Level__c.field-meta.xml
<CustomField>
    <fullName>Kaizen_Level__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Kaizen Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Aero_China_Kaizen__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Kaizen_Users__c</referenceTo>
    <relationshipLabel>Kaizens</relationshipLabel>
    <relationshipName>Kaizens</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Aero_China_Kaizen__c/recordTypes/Approved.recordType-meta.xml
<RecordType>
    <fullName>Approved</fullName>
    <active>true</active>
    <label>Approved</label>
</RecordType>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <label>User Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre-Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Post Sales-Installation</fullName>
            </value>
            <value>
                <fullName>Post Sales-Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Kaizen_Users__c/Kaizen_Users__c.object-meta.xml
<CustomObject>
    <description>Maintain the list of users who use Kaizen tool in SFDC and also classify by the role</description>
    <label>Kaizen User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kaizen Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Kaizen_Users__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HOS</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>HSE&amp;F</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>P&amp;E</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Kaizen_Users__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <label>User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitter</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Task.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tact</description>
    <label>Task</label>
</RecordType>

src/classes/KaizanApproval.cls
public with sharing class KaizanApproval
{
    public string message {get;set;}
    public Aero_China_Kaizen__c item {get;set;}    
    public KaizanApproval(ApexPages.StandardController controller) {
        //item = (Aero_China_Kaizen__c )controller.getRecord();
    }
    public void PageLoad()   
    {
        String task = ApexPages.currentPage().getParameters().get('Action');
        String itemId = ApexPages.currentPage().getParameters().get('id');        
        if(task != null && itemId != null)
        {
            item = [select id,ownerid,Kaizen_Level__c,name,Action_Owner__r.Name,CreatedBy.Name,dept__c,requester__c,LastModifiedBy.Name from Aero_China_Kaizen__c where id =:itemId];
            if(task =='Submit')
            {
                           
                //item.recordTypeId = Schema.SObjectType.Aero_China_Kaizen__c.getRecordTypeInfosByName().get('Approved').getRecordTypeId();
                item.Kaizen_Level__c = 2;
                update item;
                message = 'Request Sent for Approval.';
                List<Kaizen_Users__c > users = [select email__C from Kaizen_Users__c where User_Role__c includes ('Supervisor') and Department__c =:item.dept__c ];
                string[] toEmails = new List<String>();
                for(Kaizen_users__C u: users)
                {
                    toEmails.add(u.email__c);                
                }
                string ccEMail = [select email__C from Kaizen_Users__c where  id =:item.Action_Owner__c].email__c;
                if(toEmails.size() == 0)
                {
                    message = 'No Owner set for this department. Contact Admin.';                
                } 
                else
                {
                    Messaging.SingleEMailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(toEmails);
                    mail.setCCAddresses(new List<string>{ccEmail});
                    mail.setSaveAsActivity(false);                    
                    //mail.setTargetObjectId(item.OwnerId);
                    mail.setSenderDisplayName('Salesforce Internal');
                    //EmailTemplate et = [select id from emailtemplate where developername='Kaizen_Submitted_for_Review'];                        
                    //mail.setTemplateId(et.id);
                    mail.setSubject('New Kaizen: '+item.Name);
                    mail.setHtmlBody('Hi,<br/><br/>New Kaizen: <b>'+item.Name+'</b> has submitted by '+item.CreatedBy.Name+'<br/><br/>');
                    mail.setHtmlBody(mail.getHtmlBody()+'Review and Approve be clicking below link.<br/>');
                    mail.setHtmlBody(mail.getHtmlBody()+'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/'+item.id+'.<br/><br/>');
                    mail.setHtmlBody(mail.getHtmlBody()+'Regards.<br/>Internal Team');
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
                    message = 'Request Sent for Approval to these people:'+toEmails;         
                }          
            }   
            else if(task == 'Approve')
            {
                boolean isApproved = false;
                string ccEMail = [select email__C from Kaizen_Users__c where  id =:item.Action_Owner__c].email__c;
                if(item.Kaizen_Level__c == 2)
                {
                    List<Kaizen_Users__c > users = [select email__C from Kaizen_Users__c where User_Role__c includes ('Leader') and Department__c =:item.dept__c ];
                    string[] toEmails = new List<String>();
                    for(Kaizen_users__C u: users)
                    {
                        toEmails.add(u.email__c);                
                    }
                    
                    if(toEmails.size() != 0)
                    {
                        Messaging.SingleEMailMessage mail = new Messaging.SingleEmailMessage();
                        mail.setToAddresses(toEmails);
                        mail.setCCAddresses(new List<string>{ccEmail});
                        mail.setSaveAsActivity(false);                    
                        mail.setSenderDisplayName('Salesforce Internal');
                        mail.setSubject('New Kaizen: '+item.Name);
                        mail.setHtmlBody('Hi,<br/><br/>Leader Approval Required Kaizen:<b>'+item.Name+'</b> has been approved by '+item.LastModifiedBy.Name+'<br/><br/>');
                        mail.setHtmlBody(mail.getHtmlBody()+'Review and Approve be clicking below link.<br/>');
                        mail.setHtmlBody(mail.getHtmlBody()+'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/'+item.id+'.<br/><br/>');
                        mail.setHtmlBody(mail.getHtmlBody()+'Regards.<br/>Internal Team');
                        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});              
                    }
                    else
                    {
                        isApproved = true;
                    }
                }
                else if(item.Kaizen_Level__c == 3 || isApproved)
                {
                    Messaging.SingleEMailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(new List<string>{ccEmail});
                    mail.setSaveAsActivity(false);                    
                    mail.setSenderDisplayName('Salesforce Internal');
                    mail.setSubject('Kaizen Approved: '+item.Name);
                    mail.setHtmlBody('Hi,<br/><br/>Kaizen Approved:<b>'+item.Name+'</b> has been approved by '+item.LastModifiedBy.Name+'<br/><br/>');
                    mail.setHtmlBody(mail.getHtmlBody()+'Use below link to access the details.<br/>');
                    mail.setHtmlBody(mail.getHtmlBody()+'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/'+item.id+'.<br/><br/>');
                    mail.setHtmlBody(mail.getHtmlBody()+'Regards.<br/>Internal Team');
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
                }
                item.Kaizen_Level__c = item.Kaizen_Level__c +1;
                update item;
                
                message = 'Item Approved.';
            }  
            else if(task == 'Reject')
            {
                item.Kaizen_Level__c = 1;
                update item;
                message = 'Item Rejected.';
                string toEMail = [select email__C from Kaizen_Users__c where  id =:item.requester__c ].email__c;
                Messaging.SingleEMailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<string>{toEmail});
                mail.setSaveAsActivity(false);                    
                mail.setSenderDisplayName('Salesforce Internal');
                mail.setSubject('Kaizen Rejected: '+item.Name);
                mail.setHtmlBody('Hi,<br/><br/>Kaizen Rejected:<b>'+item.Name+'</b> has been rejected by '+item.LastModifiedBy.Name+'<br/><br/>');
                mail.setHtmlBody(mail.getHtmlBody()+'Use below link to access the details.<br/>');
                mail.setHtmlBody(mail.getHtmlBody()+'https://'+ApexPages.currentPage().getHeaders().get('Host')+'/'+item.id+'.<br/><br/>');
                mail.setHtmlBody(mail.getHtmlBody()+'Regards.<br/>Internal Team');
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
            }
        } 
        else 
        {
            message = 'Invalid Action or Page. Please Contact Admin';   
           
        }       
    }
}