src/objects/Discretionary__c/Discretionary__c.object-meta.xml
<CustomObject>
    <label>Discretionary Request</label>
    <nameField>
        <displayFormat>DR-{0}</displayFormat>
        <label>Discretionary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discretionary Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Discretionary__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Pending Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary__c/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACST-Connected Solutions</fullName>
            </value>
            <value>
                <fullName>ACST-E&amp;I</fullName>
            </value>
            <value>
                <fullName>ACST-Honeywell Quantum Solutions</fullName>
            </value>
            <value>
                <fullName>ACST-RTG</fullName>
            </value>
            <value>
                <fullName>ACST-Sustainability Technologies</fullName>
            </value>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other CBT</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other CBT</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S OTHER CBT</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>Defense Channel Partners</fullName>
            </value>
            <value>
                <fullName>DES</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary__c/fields/Discretionary_Workflow_Approver__c.field-meta.xml
<CustomField>
    <fullName>Discretionary_Workflow_Approver__c</fullName>
    <formula>Owner__r.Discretionary_Workflow_Approver__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discretionary Workflow Approver</label>
    <type>Text</type>
</CustomField>

src/objects/Discretionary__c/fields/Discretionary_Workflow_Approver_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discretionary_Workflow_Approver_Amount__c</fullName>
    <description>11/29 - previous formula - Text($User.Discretionary_Workflow_Approver_Amount__c)</description>
    <formula>text(Owner__r.Discretionary_Workflow_Approver_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discretionary_Workflow_Approver_Amount</label>
    <type>Text</type>
</CustomField>

src/objects/Discretionary__c/fields/Estimated_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Completion_Date__c</fullName>
    <label>Estimated Completion Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/objects/Discretionary__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Discretionary Requests</relationshipLabel>
    <relationshipName>Discretionaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Discretionary__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>GTO</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid &amp; Proposal</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Direct Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary_Line_Item__c/Discretionary_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Discretionary Line Item</label>
    <nameField>
        <displayFormat>DLI-{0}</displayFormat>
        <label>Discretionary Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discretionary Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Discretionary_Line_Item__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <inlineHelpText>New: New line item request.
Pending open: Set by SFDC after request has been submitted, but not approved.
Open: Charge number is open and available for use.
Pending Close:Set by SFDC after request to close and charge number closure is pending.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Open</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <formula>TEXT( Discretionary_Request__r.CBT__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CBT</label>
    <type>Text</type>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/Discretionary_Request__c.field-meta.xml
<CustomField>
    <fullName>Discretionary_Request__c</fullName>
    <label>Discretionary Request</label>
    <referenceTo>Discretionary__c</referenceTo>
    <relationshipLabel>Discretionary Line Items</relationshipLabel>
    <relationshipName>Discretionary_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <inlineHelpText>Enter dollar amount requested for E&amp;T.  (hours x labor rate)
Example: $5000</inlineHelpText>
    <label>Requested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <formula>TEXT(Discretionary_Request__r.SBU__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SBU</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <inlineHelpText>SBU responsible for this opportunity</inlineHelpText>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACS Labs</fullName>
            </value>
            <value>
                <fullName>Aero Level</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BGA</fullName>
            </value>
            <value>
                <fullName>D&amp;S</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Intracompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/CBT__c.field-meta.xml
<CustomField>
    <fullName>CBT__c</fullName>
    <label>CBT</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU_User__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACST-Connected Solutions</fullName>
            </value>
            <value>
                <fullName>ACST-Sustainability Technologies</fullName>
            </value>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>Aero Level Other</fullName>
            </value>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>APAC OEM</fullName>
            </value>
            <value>
                <fullName>ATR EMEAI OEM</fullName>
            </value>
            <value>
                <fullName>ATR Other</fullName>
            </value>
            <value>
                <fullName>BendixKing CBT</fullName>
            </value>
            <value>
                <fullName>BGA Aftermarket</fullName>
            </value>
            <value>
                <fullName>BGA Other</fullName>
            </value>
            <value>
                <fullName>Boeing ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier ATR</fullName>
            </value>
            <value>
                <fullName>Bombardier BGA</fullName>
            </value>
            <value>
                <fullName>Components Business</fullName>
            </value>
            <value>
                <fullName>D&amp;S Other</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Dassault</fullName>
            </value>
            <value>
                <fullName>DBL</fullName>
            </value>
            <value>
                <fullName>DMA</fullName>
            </value>
            <value>
                <fullName>DMM</fullName>
            </value>
            <value>
                <fullName>DSE</fullName>
            </value>
            <value>
                <fullName>DSPC</fullName>
            </value>
            <value>
                <fullName>Embraer ATR</fullName>
            </value>
            <value>
                <fullName>Embraer BGA</fullName>
            </value>
            <value>
                <fullName>FM&amp;T</fullName>
            </value>
            <value>
                <fullName>General Aviation Americas</fullName>
            </value>
            <value>
                <fullName>General Aviation Europe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/User/fields/Discretionary_Workflow_Approver__c.field-meta.xml
<CustomField>
    <fullName>Discretionary_Workflow_Approver__c</fullName>
    <label>Discretionary Workflow Approver</label>
    <relationshipName>Users</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

src/classes/Discretionary_WorkflowTest.cls
@isTest (seealldata = true)
public class Discretionary_WorkflowTest{
    testMethod static void discritionaryTest(){
        Opportunity opp = [select id from opportunity limit 1];
            
        Discretionary__C disc= new Discretionary__C();
        disc.Type__c='Bid & Praposal';
        disc.SBU__c='ATR';
        
        //disc.CBT__c='EMS';
        disc.ownerid=UserInfo.getUserid();
        disc.Estimated_Completion_Date__c = System.today();
        disc.opportunity__c=opp.id;
        insert disc;
        
        Discretionary_Line_item__c DLI=new Discretionary_Line_item__c();
        DLI.Funding_Amount__c=4000;
        dli.Requested_Amount__c=5000;
        DLI.Discretionary_Request__c = disc.id;
        Test.starttest();
        insert DLI;
        disc.Approval_Status__c = 'Pending Approval';
        disc.SBU__c='D&S';
        disc.CBT__c='Advanced Technology';
        disc.Type__c='Bid & Proposal';
        update disc;
        //disc.opportunity__c=null;
        disc.SBU__c='ATR';
        update disc;
        Test.stoptest();
    }
    
    testMethod static void discritionaryTest1(){
        Opportunity opp = [select id from opportunity limit 1];
            
        Discretionary__C disc= new Discretionary__C();
        disc.Type__c='Bid & Praposal';
        disc.SBU__c='ATR';
        
        disc.CBT__c='EMS';
        disc.ownerid=UserInfo.getUserid();
        disc.Estimated_Completion_Date__c = System.today();
        disc.opportunity__c=opp.id;
        insert disc;
        
        Discretionary_Line_item__c DLI=new Discretionary_Line_item__c();
        DLI.Funding_Amount__c=4000;
        dli.Requested_Amount__c=5000;
        DLI.Discretionary_Request__c = disc.id;
        Test.starttest();
        insert DLI;
        disc.Approval_Status__c = 'Pending Approval';
        disc.SBU__c='D&S';
        //disc.CBT__c='Advanced Technology';
        disc.Type__c='Bid & Proposal';
        update disc;
        //disc.opportunity__c=null;
        disc.SBU__c=null;
        update disc;
        Test.stoptest();
    }

     testMethod static void discritionaryTest2(){
        Opportunity opp = [select id from opportunity limit 1];
            
        Discretionary__C disc= new Discretionary__C();
        disc.Type__c='Bid & Praposal';
        disc.SBU__c='ATR';
        User userValue1 = [select id,Discretionary_Workflow_Approver__c from User where id !=:UserInfo.getUserid() and isActive=true limit 1];
        User userValue = [select id,Discretionary_Workflow_Approver__c from User where id=:UserInfo.getUserid()];
        if(userValue.Discretionary_Workflow_Approver__c == null){
            userValue.Discretionary_Workflow_Approver__c = userValue1.id;
            userValue.Discretionary_Workflow_Approver_Amount__c = 500;
            update userValue;
        }
        disc.CBT__c='EMS';
        disc.ownerid=userValue.id;
        disc.Estimated_Completion_Date__c = System.today();
        disc.opportunity__c=opp.id;
        insert disc;
        
        Discretionary_Line_item__c DLI=new Discretionary_Line_item__c();
        DLI.Funding_Amount__c=40;
        dli.Requested_Amount__c=50;
        DLI.Discretionary_Request__c = disc.id;
        Test.starttest();
        insert DLI;
        disc.Approval_Status__c = 'Pending Approval';
        disc.SBU__c='D&S';
        //disc.CBT__c='Advanced Technology';
        disc.Type__c='Bid & Proposal';
        update disc;
        //disc.opportunity__c=null;
        
        dli.Requested_Amount__c=0;
        update DLI;
        disc.ownerid=userValue.id;
        disc.SBU__c='ACS Labs';
        disc.Escalate_To_Delegate__c=true;
        update disc;
        Test.stoptest();
    }
}