src/objects/Discretionary__c/Discretionary__c.object-meta.xml
<CustomObject>
    <label>Discretionary Request</label>
    <nameField>
        <displayFormat>DR-{0}</displayFormat>
        <label>Discretionary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discretionary Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Discretionary__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Pending Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
                <default>true</default>
                <label>2021</label>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/Discretionary_Mass_Closer.cls
/** * File Name: Discretionary_Mass_Closer
* Description Class to update Approval Status of Discretionary Requests 
*of the current fiscal year to Closed when the current month is 12 
* Copyright : Wipro Technologies Limited Copyright (c) 2010
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
global class  Discretionary_Mass_Closer implements Schedulable 
{   
     global void execute(SchedulableContext SC)
      {
        
        Integer currentMonth = System.Today().month();
        Integer yr = System.Today().Year();
        
        System.debug('currentMonth-- > ' + currentMonth);
            System.debug('yr-- > ' + yr);
            String year=String.valueOf(yr);
            System.debug('yr to String -- > ' + yr);
              List <Discretionary__c>disLst=new List<Discretionary__c>();
        if (currentMonth==12)
        {
         
       // List <Discretionary__c>disLst=new List<Discretionary__c>();
        
        for (Discretionary__c  dis :[Select d.Id, d.Fiscal_Year__c, d.Approval_Status__c From Discretionary__c d where d.Approval_Status__c<>'Approved' and d.Approval_Status__c <>'Rejected' and
                                    d.Approval_Status__c <>'Closed' and d.Fiscal_Year__c=:year ])
            {
                    Discretionary__c disretionaryUpdate=new Discretionary__c(Id=dis.Id);
                    disretionaryUpdate.Approval_Status__c='Closed';
                    disLst.add(disretionaryUpdate);
            }
       /* if (disLst.size()>0)
             {
                 update disLst;
             }*/
        }
          if (disLst.size()>0)
             {
                 update disLst;
             }
     }
     

}


/*global class  Discretionary_Mass_Closer implements Schedulable 
{  
   global void execute(SchedulableContext SC)
    {
     List <Discretionary__c>disLst=new List<Discretionary__c>();
     
    for (Discretionary__c  dis :[Select d.Id, d.Fiscal_Year__c, d.Approval_Status__c From Discretionary__c d where d.Approval_Status__c<>'Approved' and d.Approval_Status__c <>'Rejected' and
                  d.Approval_Status__c <>'Closed' and d.Fiscal_Year__c='2010' and id='a06Q0000003EWtw'])
      {
          Discretionary__c disretionaryUpdate=new Discretionary__c(Id=dis.Id);
          disretionaryUpdate.Approval_Status__c='Closed';
          disLst.add(disretionaryUpdate);
      }
    if (disLst.size()>0)
       {
         update disLst;
       }
   }
   

}*/