src/objects/Discretionary__c/Discretionary__c.object-meta.xml
<CustomObject>
    <label>Discretionary Request</label>
    <nameField>
        <displayFormat>DR-{0}</displayFormat>
        <label>Discretionary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discretionary Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Discretionary__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Closure</fullName>
            </value>
            <value>
                <fullName>Pending Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary_Line_Item__c/Discretionary_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Discretionary Line Item</label>
    <nameField>
        <displayFormat>DLI-{0}</displayFormat>
        <label>Discretionary Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discretionary Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Discretionary_Line_Item__c/fields/Acknowledge__c.field-meta.xml
<CustomField>
    <fullName>Acknowledge__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Acknowledge</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <inlineHelpText>New: New line item request.
Pending open: Set by SFDC after request has been submitted, but not approved.
Open: Charge number is open and available for use.
Pending Close:Set by SFDC after request to close and charge number closure is pending.</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Open</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Pending Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/Discretionary_Request__c.field-meta.xml
<CustomField>
    <fullName>Discretionary_Request__c</fullName>
    <label>Discretionary Request</label>
    <referenceTo>Discretionary__c</referenceTo>
    <relationshipLabel>Discretionary Line Items</relationshipLabel>
    <relationshipName>Discretionary_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/Req_Amount_Changed__c.field-meta.xml
<CustomField>
    <fullName>Req_Amount_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created to show an alert to user for submitting the DR when a new DLI is created or requested amount is changed.</description>
    <label>Req Amount Changed</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Discretionary_Line_Item__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <inlineHelpText>Enter dollar amount requested for E&amp;T.  (hours x labor rate)
Example: $5000</inlineHelpText>
    <label>Requested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/classes/dlpopup.cls
public class dlpopup {
    
    public boolean displaypopup{get;set;}
    public string ASM {get;set;}
    public Boolean refreshPage {get; set;}
    public Boolean showpopup {get; set;}
    public ApexPages.StandardController stdCtrl {get; set;}
    public Discretionary_Line_Item__c dl {get;set;}
    public  String isDtp {get;set;}
    
    public dlpopup(ApexPages.StandardController controller) {
      
        isDtp =ApexPages.currentPage().getParameters().get('isdtp');
        System.debug('@@@url'+isDtp);
        dl= [SELECT Id,Discretionary_Request__c, Discretionary_Request__r.Approval_Status__c,Approval_Status__c,Requested_Amount__c,Req_Amount_changed__c FROM Discretionary_Line_Item__c
             WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        refreshPage=false;
        stdCtrl=controller;
        if (dl.Discretionary_Request__r.Approval_Status__c == 'new'){
            showpopup=true;
        }else{showpopup=false;}
        system.debug('**********'+dl.Discretionary_Request__r.Approval_Status__c);    
    }
    
    public pagereference submit()
    {        
        stdCtrl.save();                
        return null;
    }
    public Pagereference submitLtgn()
    {
        stdCtrl.save();        
        Discretionary_Line_Item__c newItem = new Discretionary_Line_Item__c();
        newItem.Req_Amount_Changed__c =false;
        newItem.Id=dl.id;
        update newItem;
        system.debug('new pagerefe'+dl.Discretionary_Request__c);
        return new Pagereference('/apex/SendDiscretionaryApproval?id='+dl.Discretionary_Request__c);
    }
    
    public pagereference acknowledge()
    {
        if(dl.Approval_Status__c!='Pending Close'){
            dl.acknowledge__c= True;
            update dl;
        }
        //PageReference pagref = new PageReference('/'+dl.id);
        return null ;
    }
    public pagereference closeitem()
    {
        refreshPage=true;
        stdCtrl.save();
        return null;
    }
    
   @AuraEnabled
    public static String iSShowbutton(Id discItemId)
    {
        if(discItemId !=null)
        {
            Discretionary_Line_Item__c  dll= [SELECT Id, Discretionary_Request__r.Approval_Status__c,Approval_Status__c,Requested_Amount__c,Req_Amount_changed__c FROM Discretionary_Line_Item__c
                                             WHERE Id = :discItemId];            
            if (dll.Discretionary_Request__r.Approval_Status__c == 'new')
            {
                return 'true';
            }
            else
            {
                return 'false';
            }            
        }
        return null;
    }
   
    
}