src/objects/GDMFSL_Agreement_Level__c/GDMFSL_Agreement_Level__c.object-meta.xml
<CustomObject>
    <label>Agreement Level</label>
    <nameField>
        <label>Agreement Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_24hr_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_24hr_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Break fix covered (not-chargeable) 24/7</description>
    <label>24hr Reactive Coverage - 7 days/week</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_24HrCoverage_BusinessDays__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_24HrCoverage_BusinessDays__c</fullName>
    <defaultValue>false</defaultValue>
    <label>24 hour Reactive coverage business days</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_After_Hr_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_After_Hr_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Break fix covered (not-chargeable) after hours Business Hours</description>
    <label>After Hours Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Connected_Digital_Services__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Connected_Digital_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contracts with digital services, ACI Connectivity (Forge, Cyber, HRM, Remote, etc…)</description>
    <label>Digital Services - Connected Tech Sup</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_DigitalServices_CS__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_DigitalServices_CS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Digital Services - Cybersecurity Sup</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_DigitalServices_OTS__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_DigitalServices_OTS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Digital Services - Operational Tech Sup</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_HolidayNoReactiveCoverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_HolidayNoReactiveCoverage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Holidays No Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Office_Hr_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Office_Hr_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Break fix covered (not-chargeable) during Business Hours</description>
    <label>Business Hours Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Parts_Replacement_Management__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Parts_Replacement_Management__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Parts Replacement and Management included on ALE</description>
    <label>Parts Replacement</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_PartsReplacementManagement_L__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PartsReplacementManagement_L__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parts Replacement – Limited</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_PartsStockManagement__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PartsStockManagement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parts Stock management</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_PO_Number_Reactive_Coverage__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number_Reactive_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contract/Asset reactive coverage rerquires a PO or Job Number from the customer</description>
    <label>PO Number Required for Reactive Coverage</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Preventative_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Preventative_Maintenance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Preventative Maintenance work is covered on ALE</description>
    <label>Preventative Maintenance</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Reactive_Work_Chargeable__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Reactive_Work_Chargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Break Fix covered at a charge</description>
    <label>Reactive Work Is Chargeable</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Reactive_Work_Not_Chargeable__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Reactive_Work_Not_Chargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Break Fix covered at no charge</description>
    <label>Reactive Work Is Not Chargeable</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_ReactiveWork_Chargeable_L__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_ReactiveWork_Chargeable_L__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reactive work is Chargeable - Limited</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_RemoteReactiveWork_Chargeable_L__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_RemoteReactiveWork_Chargeable_L__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Reactive work Chargeable Limited</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_RemoteReactiveWork_NotChargeable__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_RemoteReactiveWork_NotChargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Reactive work is Not Chargeable</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_RemoteSupport_AM__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_RemoteSupport_AM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Support - Alarm Management</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_RemoteSupport_BO__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_RemoteSupport_BO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Support - Building Operations</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_RemoteSupport_SH__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_RemoteSupport_SH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Support - Software Hosting</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Site_Resident_Labour_Present__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Site_Resident_Labour_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contract with man on site, first responders</description>
    <label>Site Resident Labour Present</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_SLA_Guarantee_Financial_Penalty__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_SLA_Guarantee_Financial_Penalty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Service Level Agreements linked to financial penalties due to non performance/miss</description>
    <label>SLA Guarantee with Financial Penalty</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Software_Assurance__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Software_Assurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contracts with software assurance services - EBI upgrades</description>
    <label>Digital Services - Application SW Sup</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Tech_Phone_Support__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Tech_Phone_Support__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tech Support Services</description>
    <label>Remote Support - Phone</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Third_Party_Support__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Third_Party_Support__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contracts with equipment maintained by third parties</description>
    <label>Third Party Support</label>
    <type>Checkbox</type>
</CustomField>

src/objects/GDMFSL_Agreement_Level__c/fields/GDMFSL_Warranty_Services__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Warranty_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Asset is under Warranty</description>
    <label>Warranty Services</label>
    <type>Checkbox</type>
</CustomField>

src/classes/GDMFSL_AgreementLevelProcessor.cls
/**
 * Name       :    GDMFSL_AgreementLevelProcessor
 * Purpose    :    Wrapper class to encapsulate Agreement Level data
 * --------------------------------------------------------------------------
 * Developer               Date          Description
 * --------------------------------------------------------------------------
 * Udbhav                  2020-Oct-14    Created
 **/

public without sharing class GDMFSL_AgreementLevelProcessor {


    private static Map<Id, GDMFSL_Agreement_Level__c> retVals = new Map<Id, GDMFSL_Agreement_Level__c>();

    /**
     * Method to get Agreement Level Fields
     *
     * @param AgreementLevelIds Set of Ids for AgreementLevel
     *
     * @return Map of Id and Record for Agreement Level
     **/
    public static Map<Id, GDMFSL_Agreement_Level__c> getRecords(Set<Id> recIds) {

        System.debug('Agreement Level Ids Passed: ' + recIds);

        if (recIds != null && !recIds.isEmpty()) {

            Set<Id> newRecIds = new Set<Id>();

            if (retVals.isEmpty()) {
                newRecIds.addAll(recIds);
            } else {
                for (Id thisRecId : recIds) {
                    if (!retVals.containsKey(thisRecId)) {
                        newRecIds.add(thisRecId);
                    }
                }
            }

            if (!newRecIds.isEmpty()) {

                Map<Id, GDMFSL_Agreement_Level__c> theRecs = new Map<Id, GDMFSL_Agreement_Level__c>([
                        SELECT Id,
                                Name,
                                GDMFSL_24hr_Reactive_Coverage__c,
                                GDMFSL_After_Hr_Reactive_Coverage__c,
                                GDMFSL_Connected_Digital_Services__c,
                                GDMFSL_SLA_Guarantee_Financial_Penalty__c,
                                GDMFSL_Office_Hr_Reactive_Coverage__c,
                                GDMFSL_Parts_Replacement_Management__c,
                                GDMFSL_PO_Number_Reactive_Coverage__c,
                                GDMFSL_Preventative_Maintenance__c,
                                GDMFSL_Reactive_Work_Chargeable__c,
                                GDMFSL_Reactive_Work_Not_Chargeable__c,
                                GDMFSL_Site_Resident_Labour_Present__c,
                                GDMFSL_Software_Assurance__c,
                                GDMFSL_Tech_Phone_Support__c,
                                GDMFSL_Third_Party_Support__c,
                                GDMFSL_Warranty_Services__c,
                                GDMFSL_DigitalServices_OTS__c,
                                GDMFSL_DigitalServices_CS__c,
                                GDMFSL_RemoteSupport_SH__c,
                                GDMFSL_RemoteSupport_AM__c,
                                GDMFSL_RemoteSupport_BO__c,
                                GDMFSL_ReactiveWork_Chargeable_L__c,
                                GDMFSL_RemoteReactiveWork_Chargeable_L__c,
                                GDMFSL_RemoteReactiveWork_NotChargeable__c,
                                GDMFSL_HolidayNoReactiveCoverage__c,
                                GDMFSL_24HrCoverage_BusinessDays__c,
                                GDMFSL_PartsStockManagement__c,
                                GDMFSL_PartsReplacementManagement_L__c

                        FROM GDMFSL_Agreement_Level__c
                        WHERE Id IN :newRecIds

                ]);

                retVals.putAll(theRecs);
                System.debug('Retrieved AgreementLevel: ' + retVals);
            }
        }

        return retVals;
    }

}