src/objects/Case_Extension__c/Case_Extension__c.object-meta.xml
<CustomObject>
    <description>Extension of Case object</description>
    <label>Case Extension</label>
    <nameField>
        <label>Case Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Extension__c/fields/Case_object__c.field-meta.xml
<CustomField>
    <fullName>Case_object__c</fullName>
    <label>Case object</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Extensions</relationshipLabel>
    <relationshipName>Case_Extensions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Case_Extension__c/fields/CaseDateCompare__c.field-meta.xml
<CustomField>
    <fullName>CaseDateCompare__c</fullName>
    <formula>IF(DATEVALUE(Case_object__r.CreatedDate) = DATEVALUE(Case_object__r.LastModifiedDate), &apos;True&apos;,&apos;False&apos;)</formula>
    <label>CaseDateCompare</label>
    <type>Text</type>
</CustomField>

src/objects/Case_Extension__c/fields/CaselastModDateCompare__c.field-meta.xml
<CustomField>
    <fullName>CaselastModDateCompare__c</fullName>
    <formula>IF( NOT(ISBLANK(Manual_Intervention_Last_Modified_Date__c))  &amp;&amp;  (Manual_Intervention_Last_Modified_Date__c = DATEVALUE(Case_object__r.LastModifiedDate)), &apos;True&apos;,&apos;False&apos;)</formula>
    <label>CaselastModDateCompare</label>
    <type>Text</type>
</CustomField>

src/objects/Case_Extension__c/fields/Manual_Intervention_Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Manual_Intervention_Last_Modified_Date__c</fullName>
    <description>Created for UFR Pricing Project IT-14-044</description>
    <label>Manual Intervention Last Modified Date</label>
    <type>Date</type>
</CustomField>

src/objects/Case_Extension__c/fields/UFR_SBU__c.field-meta.xml
<CustomField>
    <fullName>UFR_SBU__c</fullName>
    <label>UFR SBU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/UFRPricing_EmailRemainderStatusTest.cls
@isTest
class UFRPricing_EmailRemainderStatusTest{
    static testMethod void UFRPricing_EmailRemainderStatus_Test() 
    {   
        
        case c1 = new case();
        c1.recordtypeid = label.Repair_Overhaul_RT_ID;
        c1.origin = 'UFR Pricing';
        c1.type = 'PO Mismtach';
        c1.Status = 'Open';
        insert c1;
        List<Case> cas = [select id,CaseNumber,lastmodifieddate,createddate,(select id,UFR_SBU__c,Case_object__c,CaseDateCompare__c,CaselastModDateCompare__c,Manual_Intervention_Last_Modified_Date__c,Case_object__r.LastModifiedDate from CASE.Case_Extensions__r) from case where id=:c1.id];
        
        List<Case_Extension__c> elist = new List<Case_Extension__c>();
        for(Case cases:cas){
            Case_Extension__c e = new Case_Extension__c();
            if(cases.Case_Extensions__r!=null && cases.Case_Extensions__r.size()>0)
                e = cases.Case_Extensions__r;
                else
                e.Case_object__c = cases.id;
                e.Manual_Intervention_Last_Modified_Date__c = system.today()-6;
                e.UFR_SBU__c = 'BGA';
                elist.add(e);
        }
        update elist;
        
        EmailMessage newEmail = new EmailMessage();
        newEmail = new EmailMessage(FromAddress = 'aerodonotreply@honeywell.com', ToAddress= 'harikishore.vutukuri@honeywell.com', Subject = 'HIA - Action', TextBody = '2345678', ParentId = c1.Id); 
        insert newEmail;
        test.startTest();
        try{
        UFRPricing_EmailRemainderStatus batch = new UFRPricing_EmailRemainderStatus();
        batch.start( (Database.BatchableContext) null );
        batch.execute( (Database.BatchableContext) null, elist);
        batch.finish( (Database.BatchableContext) null );
        batch.execute((SchedulableContext) null );
        }catch(Exception e){}
        test.stopTest();
    }   
}