src/objects/GDMFSL_Associated_Contract__c/GDMFSL_Associated_Contract__c.object-meta.xml
<CustomObject>
    <label>Associated Contract</label>
    <nameField>
        <displayFormat>ACN-{0000}</displayFormat>
        <label>Associated Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GDMFSL_SLA__c/GDMFSL_SLA__c.object-meta.xml
<CustomObject>
    <description>This custom object will hold SLA records related to Asset or Location/Service Contract combination and it will used to derive Work dates.</description>
    <label>SLA</label>
    <nameField>
        <displayFormat>SLA-{00000000}</displayFormat>
        <label>SLA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Arrival_Time__c</fullName>
    <description>SLA Arrival Time</description>
    <label>Arrival Time (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Associated_Contract__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Associated_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Location and Contract the SLA is related to</description>
    <inlineHelpText>The Location and Contract the SLA is related to</inlineHelpText>
    <label>Associated Contract</label>
    <referenceTo>GDMFSL_Associated_Contract__c</referenceTo>
    <relationshipLabel>SLAs</relationshipLabel>
    <relationshipName>SLAs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Line Item</label>
    <referenceTo>ContractLineItem</referenceTo>
    <relationshipLabel>SLAs</relationshipLabel>
    <relationshipName>SLAs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Priority__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Priority__c</fullName>
    <description>SLA Priority...</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Resolution_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Resolution_Time__c</fullName>
    <description>SLA Resolution Time</description>
    <label>Resolution Time (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/GDMFSL_SLA__c/fields/GDMFSL_Response_Time__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Response_Time__c</fullName>
    <description>SLA Response Time</description>
    <label>Response Time (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/GDMFSL_SLAProcessor.cls
/**
 * Name       :    GDMFSL_SLAProcessor
 * Purpose    :    Business Logic for SLA object . See method descriptions for proper context for calling each method
 * --------------------------------------------------------------------------
 * Developer               Date          Description
 * --------------------------------------------------------------------------
 * Udbhav                  2020-Sep-11    Created
 **/
public without sharing class GDMFSL_SLAProcessor {

    private static Map<Id, List<GDMFSL_SLA__c>> retVals = new Map<Id, List<GDMFSL_SLA__c>>();

    /**
     * Method to get AssociatedContract Fields
     *
     * @param relatedIds
     * @param idSObjectType
     *
     * @return Map of Id and lsit od SLA
     **/
    public static Map<Id, List<GDMFSL_SLA__c>> getRecords(Set<Id> relatedIds, SObjectType idSObjectType) {

        System.debug('GDMFSL_SLAProcessor.getRecords()');
        System.debug('given IDs: ' + relatedIds);

        if (relatedIds != null && !relatedIds.isEmpty()) {

            Set<Id> moreIdsToGet = new Set<Id>();

            if (retVals.isEmpty()){
                moreIdsToGet.addAll(relatedIds);
            } else {
                for (Id checkId : relatedIds) {
                    if (!retVals.containsKey(checkId)) {
                        moreIdsToGet.add(checkId);
                    }
                }
            }

            System.debug('More IDs to get: ' + moreIdsToGet);

            if (!moreIdsToGet.isEmpty()) {

                if (idSObjectType == ContractLineItem.SObjectType) {

                    System.debug('Getting SLA based on CLI');

                    for (GDMFSL_SLA__c sla : [
                            SELECT Id,GDMFSL_Priority__c, GDMFSL_Resolution_Time__c,
                                    GDMFSL_Response_Time__c, GDMFSL_Arrival_Time__c,
                                    GDMFSL_Associated_Contract__c, GDMFSL_Contract_Line_Item__c
                            FROM
                                    GDMFSL_SLA__c
                            WHERE GDMFSL_Contract_Line_Item__c IN :relatedIds
                    ]) {

                        if (!retVals.containsKey(sla.GDMFSL_Contract_Line_Item__c)) {
                            retVals.put(sla.GDMFSL_Contract_Line_Item__c, new List<GDMFSL_SLA__c>());
                        }

                        retVals.get(sla.GDMFSL_Contract_Line_Item__c).add(sla);
                    }

                } else if (idSObjectType == GDMFSL_Associated_Contract__c.SObjectType) {

                    System.debug('Getting SLA based on Associated Contract');

                    for (GDMFSL_SLA__c sla : [
                            SELECT Id,GDMFSL_Priority__c, GDMFSL_Resolution_Time__c,
                                    GDMFSL_Response_Time__c, GDMFSL_Arrival_Time__c,
                                    GDMFSL_Associated_Contract__c, GDMFSL_Contract_Line_Item__c
                            FROM GDMFSL_SLA__c
                            WHERE GDMFSL_Associated_Contract__c IN :relatedIds
                    ]) {

                        if (!retVals.containsKey(sla.GDMFSL_Associated_Contract__c)) {
                            retVals.put(sla.GDMFSL_Associated_Contract__c, new List<GDMFSL_SLA__c>());
                        }

                        retVals.get(sla.GDMFSL_Associated_Contract__c).add(sla);
                    }
                }
            }
        }

        System.debug('Returning this many SLAs: ' + retVals.size());

        return retVals;
    }

}