src/objects/Aircraft_Custom_Configuration__c/Aircraft_Custom_Configuration__c.object-meta.xml
<CustomObject>
    <label>Aircraft Custom Configuration</label>
    <nameField>
        <label>Aircraft LRU Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Custom Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Aircraft_Custom_Configuration__c/fields/AIRCRAFT_CLASSIFICATION_CD__c.field-meta.xml
<CustomField>
    <fullName>AIRCRAFT_CLASSIFICATION_CD__c</fullName>
    <label>Aircraft Classification Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/Aircraft_Platform_Standard_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Platform_Standard_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft Platform Standard Configuration</label>
    <referenceTo>Aircraft_Platform_Configuration__c</referenceTo>
    <relationshipLabel>Aircraft Custom Configuration</relationshipLabel>
    <relationshipName>Aircraft_Custom_Configuration</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/AVEL_MECH_IND__c.field-meta.xml
<CustomField>
    <fullName>AVEL_MECH_IND__c</fullName>
    <label>AVEL Mech. Indicator</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/DESCRIPTION_NM__c.field-meta.xml
<CustomField>
    <fullName>DESCRIPTION_NM__c</fullName>
    <label>Description Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/Fleet_Asset_Detail__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Asset_Detail__c</fullName>
    <label>Fleet Asset Detail</label>
    <referenceTo>Fleet_Asset_Detail__c</referenceTo>
    <relationshipLabel>Aircraft Custom Configuration</relationshipLabel>
    <relationshipName>Aircraft_Custom_Configuration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/SITE_CD__c.field-meta.xml
<CustomField>
    <fullName>SITE_CD__c</fullName>
    <label>Site Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Custom_Configuration__c/fields/Sub_System__c.field-meta.xml
<CustomField>
    <fullName>Sub_System__c</fullName>
    <label>Sub System</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/Aircraft_Platform_Configuration__c.object-meta.xml
<CustomObject>
    <label>Aircraft Platform Standard Configuration</label>
    <nameField>
        <label>LRU Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Platform Standard Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Aircraft_Platform_Configuration__c/fields/AIRCRAFT_CLASSIFICATION_CD__c.field-meta.xml
<CustomField>
    <fullName>AIRCRAFT_CLASSIFICATION_CD__c</fullName>
    <label>Aircraft Classification Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Civil Helo</fullName>
            </value>
            <value>
                <fullName>Business Jet</fullName>
            </value>
            <value>
                <fullName>Business Turboprop</fullName>
            </value>
            <value>
                <fullName>Civil Utility</fullName>
            </value>
            <value>
                <fullName>Jet</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>Military Combat</fullName>
            </value>
            <value>
                <fullName>Military Combat Helo</fullName>
            </value>
            <value>
                <fullName>Military Ground Vehicle</fullName>
            </value>
            <value>
                <fullName>Military Helo</fullName>
            </value>
            <value>
                <fullName>Military Missiles</fullName>
            </value>
            <value>
                <fullName>Military Special Mission</fullName>
            </value>
            <value>
                <fullName>Military Trainer</fullName>
            </value>
            <value>
                <fullName>Military Transport</fullName>
            </value>
            <value>
                <fullName>Military Utility Helo</fullName>
            </value>
            <value>
                <fullName>Regional Turboprop</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Submarine</fullName>
            </value>
            <value>
                <fullName>Tanker</fullName>
            </value>
            <value>
                <fullName>Transport, Single-Aisle</fullName>
            </value>
            <value>
                <fullName>Transport, Twin-Aisle</fullName>
            </value>
            <value>
                <fullName>Turboprop</fullName>
            </value>
            <value>
                <fullName>Helicopter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/AIRCRAFT_PART_MODEL_NM__c.field-meta.xml
<CustomField>
    <fullName>AIRCRAFT_PART_MODEL_NM__c</fullName>
    <label>Aircraft Part Model Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/AIRCRAFT_PART_NUM__c.field-meta.xml
<CustomField>
    <fullName>AIRCRAFT_PART_NUM__c</fullName>
    <label>LRU Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/AVEL_MECH_IND__c.field-meta.xml
<CustomField>
    <fullName>AVEL_MECH_IND__c</fullName>
    <label>AVEL Mechanical Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Avionics</fullName>
            </value>
            <value>
                <fullName>GP-402</fullName>
            </value>
            <value>
                <fullName>Electical</fullName>
            </value>
            <value>
                <fullName>Mechanical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/DESCRIPTION_NM__c.field-meta.xml
<CustomField>
    <fullName>DESCRIPTION_NM__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <label>Sub System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AHRS/IRS</fullName>
            </value>
            <value>
                <fullName>Air Data</fullName>
            </value>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>Autoflight</fullName>
            </value>
            <value>
                <fullName>Comm/Nav</fullName>
            </value>
            <value>
                <fullName>Connector Kit</fullName>
            </value>
            <value>
                <fullName>Displays</fullName>
            </value>
            <value>
                <fullName>EGPWS</fullName>
            </value>
            <value>
                <fullName>Epic</fullName>
            </value>
            <value>
                <fullName>Epic Comm/Nav</fullName>
            </value>
            <value>
                <fullName>Epic Core</fullName>
            </value>
            <value>
                <fullName>FMS</fullName>
            </value>
            <value>
                <fullName>GP-401</fullName>
            </value>
            <value>
                <fullName>HF</fullName>
            </value>
            <value>
                <fullName>Instruments</fullName>
            </value>
            <value>
                <fullName>Primus 2000</fullName>
            </value>
            <value>
                <fullName>RADAR</fullName>
            </value>
            <value>
                <fullName>SATCOM</fullName>
            </value>
            <value>
                <fullName>Sat TV</fullName>
            </value>
            <value>
                <fullName>Surveillance</fullName>
            </value>
            <value>
                <fullName>TCAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <label>Aircraft Platform</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Aircraft Platform Standard Configuration</relationshipLabel>
    <relationshipName>Aircraft_Platform_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/Secondary__c.field-meta.xml
<CustomField>
    <fullName>Secondary__c</fullName>
    <label>Primary / Secondary</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Aircraft_Platform_Configuration__c/fields/SITE_CD__c.field-meta.xml
<CustomField>
    <fullName>SITE_CD__c</fullName>
    <label>Site Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AircraftPlatformSTDConf.cls
public with sharing class AircraftPlatformSTDConf 
{
    
    private List<Aircraft_Platform_Configuration__c> pltConf;
    private List<Aircraft_Custom_Configuration__c> airConf;
    private Fleet_Asset_Detail__c air;
    
    public AircraftPlatformSTDConf(ApexPages.StandardController controller) 
    {
        this.air= (Fleet_Asset_Detail__c)controller.getRecord();
    }
    public List<Aircraft_Platform_Configuration__c> getPltConf()
    {
        List<Aircraft_Custom_Configuration__c> airCustConf = [Select Aircraft_Platform_Standard_Configuration__c from Aircraft_Custom_Configuration__c where Fleet_Asset_Detail__c = :air.Id];
        
        integer i = 0;
        if(airCustConf != null && airCustConf.size() > 0)
        {
            i = airCustConf.size();
        }
        string[] ids = new string[i];
        for (integer cnt=0;cnt<i;cnt++)
        {
             ids[cnt] =  airCustConf[cnt].Aircraft_Platform_Standard_Configuration__c;      
        }  
        
        
        if(i > 0)
        {
            pltConf = [Select id,Platform_Name__r.Name, Name,AIRCRAFT_PART_MODEL_NM__c,AIRCRAFT_CLASSIFICATION_CD__c,AVEL_MECH_IND__c,DESCRIPTION_NM__c,AIRCRAFT_PART_NUM__c,Manufacturer__c,Secondary__c,SITE_CD__c,Epic__c from Aircraft_Platform_Configuration__c where Platform_Name__c = :air.Platform_Name__c And Secondary__c = 'Primary' And Id NOT IN :ids ORDER BY Secondary__c,Epic__c];
        }
        else
        {
            pltConf = [Select id,Platform_Name__r.Name, Name,AIRCRAFT_PART_MODEL_NM__c,AIRCRAFT_CLASSIFICATION_CD__c,AVEL_MECH_IND__c,DESCRIPTION_NM__c,AIRCRAFT_PART_NUM__c,Manufacturer__c,Secondary__c,SITE_CD__c,Epic__c from Aircraft_Platform_Configuration__c where Platform_Name__c = :air.Platform_Name__c And Secondary__c = 'Primary' ORDER BY Secondary__c,Epic__c];
        }
        
        return pltConf;
        
    }

    public List<Aircraft_Custom_Configuration__c> getAirConf()
    {
        airConf = [Select id,Name,DESCRIPTION_NM__c,Sub_System__c,AVEL_MECH_IND__c,Manufacturer__c,SITE_CD__c from Aircraft_Custom_Configuration__c where Fleet_Asset_Detail__c = :air.Id];
        return airConf;
        
    }

}