src/objects/ServiceAppointment/fields/GDMFSL_Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Delivery_Block__c</fullName>
    <formula>IF(
AND(
OR( ISPICKVAL(StatusCategory, &quot;None&quot;) ,
ISPICKVAL(StatusCategory, &quot;Scheduled&quot;),
ISPICKVAL(StatusCategory, &quot;Dispatched&quot;) ,
ISPICKVAL(StatusCategory, &quot;In Progress&quot;)),
NOT( ISNULL(  GDMFSL_Sold_To_Source_System_Reference__c  )))
,
 GDMFSL_Sold_To_Source_System_Reference__r.GDMFSL_Delivery_Block__c  , false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Block</label>
    <type>Checkbox</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

src/objects/ServiceAppointment/fields/GDMFSL_Sold_To_Source_System_Reference__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Sold_To_Source_System_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Source System Reference</label>
    <referenceTo>Source_System__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Source_System__c/fields/GDMFSL_Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Delivery_Block__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delivery Block</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder/fields/GDMFSL_Created_by_WO_Merge_Process__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Created_by_WO_Merge_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created by WO Merge Process</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Delivery_Block__c</fullName>
    <formula>IF(
AND(
OR( ISPICKVAL(StatusCategory, &quot;New&quot;) ,
ISPICKVAL(StatusCategory, &quot;In Progress&quot;)),
NOT( ISNULL( GDMFSL_Sold_To_Source_System_Reference__c)))
,
GDMFSL_Sold_To_Source_System_Reference__r.GDMFSL_Delivery_Block__c, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Block</label>
    <type>Checkbox</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

src/objects/WorkOrder/fields/GDMFSL_Sold_To_Source_System_Reference__c.field-meta.xml
<CustomField>
    <fullName>GDMFSL_Sold_To_Source_System_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Source System Reference</label>
    <referenceTo>Source_System__c</referenceTo>
    <relationshipLabel>Work Orders (Sold To Source System Reference)</relationshipLabel>
    <relationshipName>Work_Orders_SoldTo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/GDMFSL_ServiceAppointmentGeneratorTest.cls
@IsTest
private class GDMFSL_ServiceAppointmentGeneratorTest {

    @TestSetup
    static void init() {
        Account a = new Account(Name = 'Test Account', Phone = '1234561234', BillingStreet = 'Anywhere', BillingCity = 'City', BillingState = 'Florida', BillingCountry = 'United States');
        insert a;

        WorkType wt = GDMFSL_DataFactory.createWorkType('Break/Fix', 4);
        insert wt;
        OperatingHours ohs = GDMFSL_DataFactory.createOperatingHour();
        insert ohs;
        ServiceTerritory st = GDMFSL_DataFactory.createServiceTerritory('SSProc Test', ohs.Id);
        insert st;
        Schema.Location lo = GDMFSL_DataFactory.createLocation('Test Location', st.Id);
        insert lo;

        Source_System__c ss = GDMFSL_DataFactory.createSourceSystem(a.Id, '11111');
        ss.Customer_Order_Block__c = true;
        ss.GDMFSL_Delivery_Block__c = false;
        ss.Type__c = 'SOLDTO';
        insert ss;

        WorkOrder wo = GDMFSL_DataFactory.createWorkOrder(wt.Id, a.Id, lo.Id, System.now(), System.now());
        wo.GDMFSL_Sold_To_Source_System_Reference__c = ss.Id;
        wo.GDMFSL_PO_Number__c = '12345';
        insert wo;

        ServiceAppointment theSA = GDMFSL_DataFactory.createServiceAppointmentwithParentWO(wo.Id, GDMFSL_WorkOrderProcessor.COMPLETEDSTATUS);
        theSA.SchedStartTime = System.now();
        theSA.SchedEndTime = System.now().addHours(4);
        insert theSA;

    }

    @IsTest
    static void generateSAsForSpecificWOId() {

        List<WorkOrder> wosToProcess = new List<WorkOrder>([SELECT Id FROM WorkOrder LIMIT 1]);

        GDMFSL_ServiceAppointmentGenerator saGen = new GDMFSL_ServiceAppointmentGenerator();

        for (WorkOrder aWO : wosToProcess){
            saGen.woIdsToTestWith.add(aWO.Id);
        }

        Test.startTest();

        System.debug('TEST: ');

        Database.executeBatch(saGen);

        Test.stopTest();

        System.debug('See if SA was created');
        List<ServiceAppointment> allSAs = new List<ServiceAppointment>([SELECT Id FROM ServiceAppointment WHERE ParentRecordId IN :wosToProcess]);

        System.assertNotEquals(0, allSAs.size(), 'SAGenerator did not create ServiceAppointments for specified WO');

    }

    @IsTest
    static void generateSAsForMergeCreatedWOs() {

        List<WorkOrder> wosToProcess = new List<WorkOrder>([SELECT Id FROM WorkOrder LIMIT 1]);

        GDMFSL_ServiceAppointmentGenerator saGen = new GDMFSL_ServiceAppointmentGenerator();

        for (WorkOrder aWO : wosToProcess){
            aWO.GDMFSL_Created_by_WO_Merge_Process__c = true;
        }
        update wosToProcess;

        Test.startTest();

        System.debug('TEST: ');

        Database.executeBatch(saGen);

        Test.stopTest();

        System.debug('See if SA was created');
        List<ServiceAppointment> allSAs = new List<ServiceAppointment>([SELECT Id FROM ServiceAppointment]);

        System.assertNotEquals(0, allSAs.size(), 'SAGenerator did not create ServiceAppointments for Merge-Created WOs');

    }

    @IsTest
    private static void saGeneratorSchedulableTest(){

        Test.startTest();

        System.debug('TEST: start');

        GDMFSL_ServiceAppointmentGenerator theJob = new GDMFSL_ServiceAppointmentGenerator();
        System.schedule('SAGenerator Sched', '0 0 23 * * ?', theJob);

        Test.stopTest();

        System.debug('Nothing meaningful to assert');

    }


}