src/objects/APTS_PDF_Attachment_Status__c/APTS_PDF_Attachment_Status__c.object-meta.xml
<CustomObject>
    <label>Attachment Integration Status</label>
    <nameField>
        <displayFormat>PDF-{0000000000}</displayFormat>
        <label>PDF Attachment Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Integration Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>APTS_Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Memo</label>
    <referenceTo>Apttus_Billing__CreditMemo__c</referenceTo>
    <relationshipName>PDF_Attachment_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Invoice__c.field-meta.xml
<CustomField>
    <fullName>APTS_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipName>PDF_Attachment_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Status__c.field-meta.xml
<CustomField>
    <fullName>APTS_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__CreditMemo__c/Apttus_Billing__CreditMemo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Credit Memo Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__CreditMemo__c/fields/Apttus_Billing__BillToAccountId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillToAccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Bill To address on the associated Account.</description>
    <inlineHelpText>The Bill To address on the associated Account.</inlineHelpText>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/objects/Apttus_Billing__CreditMemo__c/fields/Apttus_Billing__CreditAmount__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__CreditAmount__c</fullName>
    <description>The total amount to set off against a balance from invoice or other transactions.</description>
    <inlineHelpText>Amount to set off against a balance from invoice or other transactions.</inlineHelpText>
    <label>Credit Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

src/objects/Apttus_Billing__Invoice__c/Apttus_Billing__Invoice__c.object-meta.xml
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__Invoice__c/fields/Apttus_Billing__BillToAccountId__c.field-meta.xml
<CustomField>
    <fullName>Apttus_Billing__BillToAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the bill to account</description>
    <inlineHelpText>ID of the bill to account</inlineHelpText>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Bill To)</relationshipLabel>
    <relationshipName>InvoicesBillTo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/APTS_AttachmentSubmitControllerTest.cls
@isTest
public class APTS_AttachmentSubmitControllerTest {
    
    public static testMethod void testSubmitMemo() {
        Apttus_Billing__CreditMemo__c creditMemo = new Apttus_Billing__CreditMemo__c();
        Account account = new Account();
        account.name = 'test';
        insert account;
        creditMemo.Apttus_Billing__CreditAmount__c = 10.0;
        creditMemo.Apttus_Billing__BillToAccountId__c = account.Id;
        insert creditMemo;
        
        APTS_PDF_Attachment_Status__c objats= new APTS_PDF_Attachment_Status__c();
        objats.APTS_Credit_Memo__c=creditMemo.id;
        objats.APTS_Status__c='To be Processed';
        insert objats;
        
        Id creditMemoId = (Id)objats.get('id');
        PageReference pageRef = new PageReference('/' + objats);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objats);
            // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', creditMemoId);
        APTS_AttachmentSubmitController  controller = new APTS_AttachmentSubmitController(standardController); 
        String nextPage = controller.doSubmitAttcahment().getUrl();        
    }
    
    public static testMethod void testSubmitMemo1() {
        Apttus_Billing__Invoice__c invoice = new Apttus_Billing__Invoice__c();
        insert invoice;
        APTS_PDF_Attachment_Status__c objats= new APTS_PDF_Attachment_Status__c();
        objats.APTS_Invoice__c=invoice.id;
        objats.APTS_Status__c='To be Processed';
        insert objats;
        Id invoiceId = (Id)objats.get('id');
        PageReference pageRef = new PageReference('/' + invoiceId);
        Test.setCurrentPage(pageRef);
      
        ApexPages.StandardController standardController  = new ApexPages.StandardController(objats);
            // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', invoiceId);
        APTS_AttachmentSubmitController controller = new APTS_AttachmentSubmitController(standardController); 
        String nextPage = controller.doSubmitAttcahment().getUrl();        
    }
}