src/objects/APTS_PDF_Attachment_Status__c/APTS_PDF_Attachment_Status__c.object-meta.xml
<CustomObject>
    <label>Attachment Integration Status</label>
    <nameField>
        <displayFormat>PDF-{0000000000}</displayFormat>
        <label>PDF Attachment Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Integration Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>APTS_Attachment_Id__c</fullName>
    <label>Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>APTS_Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Memo</label>
    <referenceTo>Apttus_Billing__CreditMemo__c</referenceTo>
    <relationshipName>PDF_Attachment_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Delete_Draft_Attachments__c.field-meta.xml
<CustomField>
    <fullName>APTS_Delete_Draft_Attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Draft Attachments</label>
    <type>Checkbox</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Integration_Requested__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Requested__c</fullName>
    <label>Integration Requested</label>
    <type>DateTime</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Integration_Result__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Result__c</fullName>
    <label>Integration Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Status__c.field-meta.xml
<CustomField>
    <fullName>APTS_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/APTS_SendFailedAttachmentstoSAP.cls
global class APTS_SendFailedAttachmentstoSAP implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {    
         String Type = 'Error';
         return Database.getQueryLocator('select id,APTS_Credit_Memo__c,APTS_Integration_Requested__c,APTS_Integration_Result__c,APTS_Attachment_Id__c,APTS_Delete_Draft_Attachments__c,APTS_Status__c from APTS_PDF_Attachment_Status__c where '+'APTS_Status__c=:Type');
    }
    
    global void execute(Database.BatchableContext BC, List<APTS_PDF_Attachment_Status__c>scope)
    {
         list<APTS_PDF_Attachment_Status__c> lstUpdate = new list<APTS_PDF_Attachment_Status__c>();
         for(APTS_PDF_Attachment_Status__c objPAS:scope)
         {
             objPAS.APTS_Status__c='To be Processed';
             objPAS.APTS_Integration_Result__c='';
             objPAS.APTS_Integration_Requested__c=system.now();
             lstUpdate.add(objPAS);
         }     
         
         update lstUpdate;
    }
    
    global void finish(Database.BatchableContext BC)
    {
            // Logic to be Executed at finish
    }
}