src/objects/APTS_PDF_Attachment_Status__c/APTS_PDF_Attachment_Status__c.object-meta.xml
<CustomObject>
    <label>Attachment Integration Status</label>
    <nameField>
        <displayFormat>PDF-{0000000000}</displayFormat>
        <label>PDF Attachment Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Integration Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>APTS_Attachment_Id__c</fullName>
    <label>Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Attachment_Title__c.field-meta.xml
<CustomField>
    <fullName>APTS_Attachment_Title__c</fullName>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_CM_Billing_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>APTS_CM_Billing_Document_Number__c</fullName>
    <label>CM Billing Document Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>APTS_Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Memo</label>
    <referenceTo>Apttus_Billing__CreditMemo__c</referenceTo>
    <relationshipName>PDF_Attachment_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Integration_Result__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Result__c</fullName>
    <label>Integration Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_INV_Billing_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>APTS_INV_Billing_Document_Number__c</fullName>
    <label>Invoice Billing Document Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Invoice__c.field-meta.xml
<CustomField>
    <fullName>APTS_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipName>PDF_Attachment_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Status__c.field-meta.xml
<CustomField>
    <fullName>APTS_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Apttus_Billing__CreditMemo__c/Apttus_Billing__CreditMemo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Credit Memo Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__Invoice__c/Apttus_Billing__Invoice__c.object-meta.xml
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__Invoice__c/fields/APTS_Integration_Result__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Result__c</fullName>
    <label>Integration Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/APIGEE_AttachmentIntegrationStatus_REST.cls
@RestResource(urlMapping='/attachmentintegrationstatus/*') 
global with sharing class APIGEE_AttachmentIntegrationStatus_REST {
    @HttpGet
    global static void attachmentIntegrationStatusGET(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        APIGEE_Result result = new APIGEE_Result();
        
        String id = req.params.get('id');
        if(String.isNotBlank(id)){
            result.data = [SELECT APTS_Attachment_Id__c,APTS_Attachment_Title__c,APTS_Invoice__c,APTS_Invoice__r.Name,APTS_INV_Billing_Document_Number__c,APTS_Integration_Result__c,APTS_Credit_Memo__c,APTS_Credit_Memo__r.Name,APTS_CM_Billing_Document_Number__c,APTS_Status__c,Id FROM APTS_PDF_Attachment_Status__c where Id=:id];
        }
        else{
            res.statusCode = 400;
            result.status='FAIL';
            result.StatusCode=400;
            result.error = new APIGEE_Error(400,System.now(),Null,'Please Provide the Attachment Integration Status Id');
        }
        res.responseBody = Blob.valueOf(JSON.serialize(result));
    }
    
    @HttpPUT
    global static void attachmentIntegrationStatusUpdate(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');
        APIGEE_Result result = new APIGEE_Result();
        try{
            String requestBody = req.requestBody.toString();
            APTS_PDF_Attachment_Status__c attachmentIntegrationStatus = (APTS_PDF_Attachment_Status__c)JSON.deserialize(requestBody, APTS_PDF_Attachment_Status__c.class);
            update attachmentIntegrationStatus;
            result.data = attachmentIntegrationStatus;
        }catch(Exception ex){
            res.statusCode = 400;
            result.status = 'FAIL';
            result.StatusCode=400;
            result.error = new APIGEE_Error(400, System.now(), Null, ex.getMessage());
        }
        res.responseBody = Blob.valueOf(JSON.serialize(result));
    }

}