src/objects/APTS_PDF_Attachment_Status__c/APTS_PDF_Attachment_Status__c.object-meta.xml
<CustomObject>
    <label>Attachment Integration Status</label>
    <nameField>
        <displayFormat>PDF-{0000000000}</displayFormat>
        <label>PDF Attachment Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Integration Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>APTS_Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Memo</label>
    <referenceTo>Apttus_Billing__CreditMemo__c</referenceTo>
    <relationshipName>PDF_Attachment_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Integration_Requested__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Requested__c</fullName>
    <label>Integration Requested</label>
    <type>DateTime</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Integration_Result__c.field-meta.xml
<CustomField>
    <fullName>APTS_Integration_Result__c</fullName>
    <label>Integration Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Invoice__c.field-meta.xml
<CustomField>
    <fullName>APTS_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
    <relationshipName>PDF_Attachment_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTS_PDF_Attachment_Status__c/fields/APTS_Status__c.field-meta.xml
<CustomField>
    <fullName>APTS_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Processed</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/APTS_AttachmentSubmitController.cls
public class APTS_AttachmentSubmitController {
   private final APTS_PDF_Attachment_Status__c attachment;
   APTS_PDF_Attachment_Status__c attachmentObj;
   public APTS_AttachmentSubmitController(ApexPages.StandardController stdController) {
        this.attachment = (APTS_PDF_Attachment_Status__c)stdController.getRecord();
        //id recordid=this.attachment.get('id');
        attachmentObj=[select id,APTS_Invoice__c,APTS_Credit_Memo__c,APTS_Integration_Requested__c from APTS_PDF_Attachment_Status__c where id=:attachment.id];
        
   }
    
   public PageReference doSubmitAttcahment() {
       this.attachment.APTS_Status__c= 'To be Processed';
       this.attachment.APTS_Integration_Result__c = '';
       this.attachment.APTS_Integration_Requested__c=system.now();
       update this.attachment;
       if(attachmentObj.APTS_Invoice__c!=null)
           return new PageReference('/' + attachmentObj.APTS_Invoice__c);
       else if (attachmentObj.APTS_Credit_Memo__c!=null)
           return new PageReference('/' + attachmentObj.APTS_Credit_Memo__c);
       return null;
   }
}