src/objects/Portal_User_Registration__c/Portal_User_Registration__c.object-meta.xml
<CustomObject>
    <description>Custom object to track the MyAerospace Portal User Registration</description>
    <label>Portal User Registration</label>
    <nameField>
        <displayFormat>PUR-{00000}</displayFormat>
        <label>Portal User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal User Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_User_Registration__c/fields/Create_HoneywellId__c.field-meta.xml
<CustomField>
    <fullName>Create_HoneywellId__c</fullName>
    <description>Field to hold the success iteration for Create Honeywell ID step in Portal</description>
    <label>Create_HoneywellId</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

src/objects/Portal_User_Registration__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <description>Field to hold the Portal User record creation Date</description>
    <label>Created_Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Portal_User_Registration__c/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <description>Field to hold the Honeywell ID value provided by Portal user during registration</description>
    <label>Honeywell ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

src/objects/Portal_User_Registration__c/fields/Initial_Reg__c.field-meta.xml
<CustomField>
    <fullName>Initial_Reg__c</fullName>
    <description>Field to hold the success iteration for Initial registration step in Portal</description>
    <label>Initial_Reg</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

src/classes/AccountNotSetUpBatchtest.cls
@isTest/*(seeAllData = true)*/
public class AccountNotSetUpBatchtest{
public static list<Portal_User_Registration__c > lp=new list<Portal_User_Registration__c >();
 public static testmethod void testmethod1()
 {      
     Portal_User_Registration__c obj=new Portal_User_Registration__c();
     obj.Honeywell_ID__c='test1234';
     obj.EmailAddress__c='manish.das@honeywell.com';
     
     
    // obj.CurrencyIsoCode='EUR-Euro';
insert obj;
 obj.Created_Date__c=System.now()-30.5;
 obj.Initial_Reg__c = 'Y';
 obj.Create_HoneywellId__c ='N';
 
 update obj;
 
Test.startTest();
AccountNotSetUpBatch obj1=new AccountNotSetUpBatch();
Id batchjobid=Database.executeBatch(obj1);
Test.stopTest();

}


}