src/objects/Portal_User_Registration__c/Portal_User_Registration__c.object-meta.xml
<CustomObject>
    <description>Custom object to track the MyAerospace Portal User Registration</description>
    <label>Portal User Registration</label>
    <nameField>
        <displayFormat>PUR-{00000}</displayFormat>
        <label>Portal User Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal User Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_User_Registration__c/fields/Contact_Creation_in_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Contact_Creation_in_SFDC__c</fullName>
    <description>Field to hold the success iteration for Contact Creation in SFDC step in Portal</description>
    <label>Contact_Creation_in_SFDC</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

src/objects/Portal_User_Registration__c/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <description>Field to hold the Honeywell ID value provided by Portal user during registration</description>
    <label>Honeywell ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

src/classes/PortalUserRegistrationclsTest.cls
@isTest()
private class PortalUserRegistrationclsTest{

    static testMethod void myUnitTest() 
    {
     Portal_User_Registration__c p=new Portal_User_Registration__c();
     p.Contact_Creation_in_SFDC__c='';
     p.Honeywell_ID__c='1234';
     insert p;     
     PortalUserRegistrationcls pur= new PortalUserRegistrationcls ();
     integer SFDCUser=1;     
     pur.contactCreatedCount=SFDCUser;     
     pur.firstTryCount=SFDCUser;
     pur.getCases();
 
    }
    
    static testMethod void myUnitTest1() 
    {
     Portal_User_Registration__c p=new Portal_User_Registration__c();
     p.Contact_Creation_in_SFDC__c='';
     p.Honeywell_ID__c='1234';
     insert p;
     Portal_User_Registration__c p1=new Portal_User_Registration__c();
     p1.Contact_Creation_in_SFDC__c='y';
     p1.Honeywell_ID__c='1234';
     insert p1;       
     PortalUserRegistrationcls pur= new PortalUserRegistrationcls ();
     pur.getCases();
 
    }
     static testMethod void myUnitTest2() 
    {
     Portal_User_Registration__c p=new Portal_User_Registration__c();
     p.Contact_Creation_in_SFDC__c='y';
     p.Honeywell_ID__c='1234';
     insert p;  
     
     PortalUserRegistrationcls pur= new PortalUserRegistrationcls ();
     integer SFDCUser=1;     
         
     pur.firstTryCount=SFDCUser;
     pur.getCases();
 
    }
    static testMethod void myUnitTest3() 
    {
     Portal_User_Registration__c p=new Portal_User_Registration__c();
     p.Contact_Creation_in_SFDC__c='';
     p.Honeywell_ID__c='1234';
     insert p;  
     Apexpages.currentPage().getParameters().put('event_start_date_alternate','2016-01-01');
     Apexpages.currentPage().getParameters().put('event_end_date_alternate','2016-12-31');
     PortalUserRegistrationcls pur= new PortalUserRegistrationcls ();
     integer SFDCUser=1;     
     pur.contactCreatedCount=SFDCUser;     
     pur.firstTryCount=SFDCUser;
     pur.getCases();
 
    }
 }