src/objects/Account_Cross_Ref__c/Account_Cross_Ref__c.object-meta.xml
<CustomObject>
    <label>Account Cross Ref</label>
    <nameField>
        <label>Account Cross Ref Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Cross Ref</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Cross_Ref__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Account Status should not be inactive</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Cross Ref</relationshipLabel>
    <relationshipName>Account_Cross_Ref</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/External_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Account_ID__c</fullName>
    <inlineHelpText>Defines the External unique ID for this Account Cross Reference.</inlineHelpText>
    <label>External  Account ID</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/Account_Cross_Ref__c/fields/XREF_Type__c.field-meta.xml
<CustomField>
    <fullName>XREF_Type__c</fullName>
    <inlineHelpText>Defines the Account Cross Reference Type Code for this Account Cross Reference.</inlineHelpText>
    <label>XREF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTUAL_REVENUES</fullName>
            </value>
            <value>
                <fullName>ASA_CUSTOMER_XREF</fullName>
            </value>
            <value>
                <fullName>ASA_VOC_CARD</fullName>
            </value>
            <value>
                <fullName>ASA_VOC_CARD_CONTACT</fullName>
            </value>
            <value>
                <fullName>ASA_VOC_CARD_SR</fullName>
            </value>
            <value>
                <fullName>BIZVIEW_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>BMS_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>NonSAP_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>SAP_SOLD_TO</fullName>
            </value>
            <value>
                <fullName>SIMS_SOLD_TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact/fields/Honeywell_ID__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Honeywell ID assigned to Customers via the Web portal.</inlineHelpText>
    <label>Honeywell ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/classes/NavDBandTPinterface.cls
global class NavDBandTPinterface {

    global class Result
    {
         webservice string Resultstatus;
         webservice list<AccountCorssRefdetails> lstAccountCorssRefdetails;
    }
    
    global class AccountCorssRefdetails {
        webservice string AccountNumber;
        webservice string XREFType;
               
    }
    
    webservice static Result NavDBandTPMethod(string Honid)
    {
        Result resobj= new Result();
        list<Account_Cross_Ref__c> Acrlst = new list<Account_Cross_Ref__c >();
        list<AccountCorssRefdetails> lstAcrd=new list<AccountCorssRefdetails>();
        
        if(Honid==null || Honid.trim().length()==0){
                resobj.Resultstatus='Invalid data:Please provide valid honeywell id';
                resobj.lstAccountCorssRefdetails=null;
        
        }
        if(Honid!=null && Honid.trim().length()>0)
        {
            
            list<contact> lstCon=[select id,Accountid from contact where Honeywell_ID__c=:Honid limit 1];
            
            if(lstCon==null || lstCon.isEmpty()){
                resobj.Resultstatus='No contact found with provided honeywell id';
                resobj.lstAccountCorssRefdetails=null;
            }
            
            
            if(lstCon!=null && !lstCon.isEmpty())
            {
                Acrlst = [select XREF_Type__c,External_Account_ID__c from Account_Cross_Ref__c where Account_Name__c=:lstCon[0].Accountid and XREF_Type__c = 'SAP_SOLD_TO'];
                
                for(Account_Cross_Ref__c acrs : Acrlst){
                    AccountCorssRefdetails acr = new AccountCorssRefdetails();
                    acr.AccountNumber = acrs.External_Account_ID__c;
                    acr.XREFType= acrs.XREF_Type__c;
                    lstAcrd.add(acr);
                
                }
                             
                if(lstAcrd!=null && !lstAcrd.isEmpty())
                {
                    
                    resobj.Resultstatus='Success';
                    resobj.lstAccountCorssRefdetails=lstAcrd;
                }
                else
                {
                    resobj.Resultstatus='No Account records found with provided honeywell id';
                    resobj.lstAccountCorssRefdetails=null;
                }
            }
            
        }
        return resobj;
    }
}