src/objects/Entitlement__c/Entitlement__c.object-meta.xml
<CustomObject>
    <label>Entitlement</label>
    <nameField>
        <displayFormat>EN-{0}</displayFormat>
        <label>Entitlement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Entitlement__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Entitlement End Date</label>
    <type>Date</type>
</CustomField>

src/objects/Entitlement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Do Not Generate</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>FYI</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>NetJets</fullName>
            </value>
            <value>
                <fullName>Next Plan</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ready-Accepted</fullName>
            </value>
            <value>
                <fullName>Ready-Pushed</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
            <value>
                <fullName>Special Annual</fullName>
            </value>
            <value>
                <fullName>-Status Not Found-</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Wait</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/Entitlementstatuschangebatch.cls
global class Entitlementstatuschangebatch implements Database.batchable<sObject>, Schedulable{
    global string query;
  
  global Entitlementstatuschangebatch(){
     
      query = 'SELECT End_Date__c,Id,Name,Status__c FROM Entitlement__c WHERE End_Date__c < today AND Status__c=\'Active\'';
  }
    
  global Database.QueryLocator start(Database.BatchableContext BC){
     
       return Database.getQueryLocator(query);
  }
    
  global void execute(Database.BatchableContext BC, List<Entitlement__c> scope){
     List<Entitlement__c> lstentitlement = new List<Entitlement__c>();
     
      for(Entitlement__c ent:scope){
         ent.Status__c = 'Inactive';
         lstentitlement.add(ent);  
      }
        
      if(lstentitlement.size()>0){
         try{
             update lstentitlement;
            }
            catch(Exception ex){}
      }
  }
    
  global void finish(Database.BatchableContext BC){        
    
  } 
    
  global void execute(SchedulableContext sc){
        Entitlementstatuschangebatch EntitlementBatch = new Entitlementstatuschangebatch();
        database.executeBatch(EntitlementBatch,200);
  }
     
}