src/objects/airbus__c/airbus__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>airbus</label>
</CustomObject>

src/objects/Airlines__c/Airlines__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Airlines</label>
</CustomObject>

src/objects/Boeing__c/Boeing__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Boeing</label>
</CustomObject>

src/objects/Tier_Level__c/Tier_Level__c.object-meta.xml
<CustomObject>
    <label>Tier Level</label>
    <nameField>
        <displayFormat>TN-{00000000}</displayFormat>
        <label>Tier Level Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Level</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tier_Level__c/fields/Exposed_Cost__c.field-meta.xml
<CustomField>
    <fullName>Exposed_Cost__c</fullName>
    <label>Exposed Cost (K$)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Tier_Level__c/fields/Exposed_Cost_Max_Year_K__c.field-meta.xml
<CustomField>
    <fullName>Exposed_Cost_Max_Year_K__c</fullName>
    <label>Exposed Cost Max/Year (K$)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Tier_Level__c/fields/Front_End_Loss__c.field-meta.xml
<CustomField>
    <fullName>Front_End_Loss__c</fullName>
    <label>Front End Loss (K$)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Tier_Level__c/fields/Front_End_Loss_Max_Year__c.field-meta.xml
<CustomField>
    <fullName>Front_End_Loss_Max_Year__c</fullName>
    <label>Front End Loss Max/Year (K$)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Tier_Level__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Tier_Level__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/objects/Tier_Level__c/fields/X5_Year_Revenue__c.field-meta.xml
<CustomField>
    <fullName>X5_Year_Revenue__c</fullName>
    <label>Standard 5 Year Revenue (K$)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Workflow_details__c/Workflow_details__c.object-meta.xml
<CustomObject>
    <label>eGreensheet</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Workflow ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eGreensheet</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Workflow_details__c/fields/Airbus__c.field-meta.xml
<CustomField>
    <fullName>Airbus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Airbus</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/Airlines__c.field-meta.xml
<CustomField>
    <fullName>Airlines__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Airlines</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/ATR__c.field-meta.xml
<CustomField>
    <fullName>ATR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ATR</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/BG_A__c.field-meta.xml
<CustomField>
    <fullName>BG_A__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BGA</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/Boeing__c.field-meta.xml
<CustomField>
    <fullName>Boeing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Boeing</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/Defence_Space__c.field-meta.xml
<CustomField>
    <fullName>Defence_Space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defense &amp; Space</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/Exposed_Cost__c.field-meta.xml
<CustomField>
    <fullName>Exposed_Cost__c</fullName>
    <label>Exposed Cost (K$)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Workflow_details__c/fields/Exposed_Cost_Max_Year_K__c.field-meta.xml
<CustomField>
    <fullName>Exposed_Cost_Max_Year_K__c</fullName>
    <label>Exposed Cost Max/Year (K$)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Workflow_details__c/fields/Front_End_Loss__c.field-meta.xml
<CustomField>
    <fullName>Front_End_Loss__c</fullName>
    <label>Front End Loss (K$)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Workflow_details__c/fields/Front_End_Loss_Max_Year__c.field-meta.xml
<CustomField>
    <fullName>Front_End_Loss_Max_Year__c</fullName>
    <label>Front End Loss Max/Year (K$)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Workflow_details__c/fields/HIS__c.field-meta.xml
<CustomField>
    <fullName>HIS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HIS</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/HTSI__c.field-meta.xml
<CustomField>
    <fullName>HTSI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HTSI</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/RACC__c.field-meta.xml
<CustomField>
    <fullName>RACC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Components</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Workflow_details__c/fields/Suggested_Tier__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Tier__c</fullName>
    <label>Suggested Tier</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Workflow_details__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Non Standard</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Workflow_details__c/fields/X5_Year_Revenue_K__c.field-meta.xml
<CustomField>
    <fullName>X5_Year_Revenue_K__c</fullName>
    <label>5 Year Revenue (K$)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/classes/TriggerTier_Test.cls
/**
 * Created by Meiying Liang on 1/18/2020.
 */

@IsTest
private class TriggerTier_Test {
    private static Workflow_details__c workflowDetails;
    private static Tier_Level__c tierLevel;

    static void init() {
        workflowDetails = new TestEgreensheetBuilder()
                .setApprovalLevelinProgress('Tier I')
                .addField('Exposed_Cost__c',100)
                .addField('Exposed_Cost_Max_Year_K__c',200)
                .addField('Front_End_Loss__c',100)
                .addField('Front_End_Loss_Max_Year__c',200)
                .addField('X5_Year_Revenue_K__c',100)
                .build();

        tierLevel = new Tier_Level__c();
        tierLevel.Exposed_Cost__c = 150;
        tierLevel.Front_End_Loss_Max_Year__c = 300;
        tierLevel.Front_End_Loss__c = 150;
        tierLevel.Exposed_Cost_Max_Year_K__c = 300;
        tierLevel.X5_Year_Revenue__c = 150;
    }
    @IsTest
    static void BI_Airbus_Test() {
        init();

        tierLevel.SBU__c = 'Airbus';
        tierLevel.Tier__c = 'Airbus Tier II-1';

        insert tierLevel;

        workflowDetails.Airbus__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'Airbus Tier II-1');
    }

    @IsTest
    static void BI_Airlines_Test() {
        init();

        tierLevel.SBU__c = 'Airlines';
        tierLevel.Tier__c = 'Airlines Tier III-5';

        insert tierLevel;

        workflowDetails.Airlines__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Non-Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'Airlines Tier III-5');
    }

    @IsTest
    static void BI_ATR_Test() {
        init();

        tierLevel.SBU__c = 'ATR';
        tierLevel.Tier__c = 'Airbus Tier III-2';

        insert tierLevel;

        workflowDetails.ATR__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];
        system.assertEquals(result[0].Suggested_Tier__c,'Airbus Tier III-2');
    }

    @IsTest
    static void BI_BGA_Test() {
        init();

        tierLevel.SBU__c = 'BGA';
        tierLevel.Tier__c = 'BGA Tier III-5';

        insert tierLevel;

        workflowDetails.BG_A__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'BGA Tier III-5');
    }

    @IsTest
    static void BI_Boeing_Test() {
        init();

        tierLevel.SBU__c = 'Boeing';
        tierLevel.Tier__c = 'Boeing Tier II-1';

        insert tierLevel;

        workflowDetails.Boeing__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'Boeing Tier II-1');
    }

    @IsTest
    static void BI_Components_Test() {
        init();

        tierLevel.SBU__c = 'Components';
        tierLevel.Tier__c = 'Components Tier III-5';

        insert tierLevel;

        workflowDetails.RACC__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'Components Tier III-5');
    }

    @IsTest
    static void BI_D_And_S_Test() {
        init();

        tierLevel.SBU__c = 'D&S';
        tierLevel.Tier__c = 'D&S Tier III-2';

        insert tierLevel;

        workflowDetails.Defence_Space__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

       List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'D&S Tier III-2');
    }

    @IsTest
    static void BI_HIS_Test() {
        init();

        tierLevel.SBU__c = 'HIS';
        tierLevel.Tier__c = 'HIS Tier I-1';

        insert tierLevel;

        workflowDetails.HIS__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'HIS Tier I-1');
    }

    @IsTest
    static void BI_HTSI_Test() {
        init();

        tierLevel.SBU__c = 'HTSI';
        tierLevel.Tier__c = 'HTSI Tier I-3';

        insert tierLevel;

        workflowDetails.HTSI__c = true;
        workflowDetails.Terms_and_Conditions__c = 'Standard';
        insert workflowDetails;

        List<Workflow_details__c> result = [Select Suggested_Tier__c From Workflow_details__c];

        system.assertEquals(result[0].Suggested_Tier__c,'HTSI Tier I-3');
    }
}