src/objects/REG_API_Trace_Detail__c/REG_API_Trace_Detail__c.object-meta.xml
<CustomObject>
    <description>To log the error/trace as a result of calling API</description>
    <label>REG API Trace Detail</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Trace Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REG API Trace Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/REG_API_Trace_Detail__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Contains the name of API in which error occured</description>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/REG_API_Trace_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Transaction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/REG_API_Trace_Detail_ErrorRecordTest.cls
@isTest 
public class REG_API_Trace_Detail_ErrorRecordTest 
{
    static testMethod void testMethod1() 
    {
        REG_API_Trace_Detail__c acc = new REG_API_Trace_Detail__c();
        acc.API_Name__c ='Name1';
        acc.Type__c ='Error';
        acc.CreatedDate = system.today()-15;
        insert acc;
         
        //Test.setCreatedDate(acc.Id, Date.today().addDays(-15));
        System.assertEquals(Date.today().addDays(-15), acc.CreatedDate);
        
        Test.startTest();
        REG_API_Trace_Detail_ErrorRecordBatch obj = new REG_API_Trace_Detail_ErrorRecordBatch();
        obj.execute(null, new list<sObject>{acc});   
        database.executeBatch(obj);
        Test.stopTest();
        
    }
}