src/objects/REG_API_Trace_Detail__c/REG_API_Trace_Detail__c.object-meta.xml
<CustomObject>
    <description>To log the error/trace as a result of calling API</description>
    <label>REG API Trace Detail</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Trace Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REG API Trace Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/REG_API_Trace_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Transaction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/REG_API_Trace_Detail_ErrorRecordBatch.cls
global class REG_API_Trace_Detail_ErrorRecordBatch implements Database.Batchable<sObject>{ 
    //Start
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator('select Id,createddate FROM REG_API_Trace_Detail__c WHERE createddate < LAST_N_DAYS:14 and Type__c =\'Error\' ');
    }
    //Execute
    global void execute(Database.BatchableContext bc, List<sObject> records)
    { 
        try{
            System.debug('records' +records);
            delete records; 
             }catch(Exception e) {
            System.debug(e);
        }
    }
    //Finish
    global void finish(Database.BatchableContext bc){}   
}