src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Service</fullName>
            </value>
            <value>
                <fullName>On order</fullName>
                <label>On Order</label>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Type swap</fullName>
                <label>Type Swap</label>
            </value>
            <value>
                <fullName>Written off</fullName>
                <label>Written Off</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On option</fullName>
                <label>On Option</label>
            </value>
            <value>
                <fullName>LOI to Option</fullName>
            </value>
            <value>
                <fullName>LOI to Order</fullName>
            </value>
            <value>
                <fullName>Reengineered</fullName>
            </value>
            <value>
                <fullName>For Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/TestFleetAssetDetailBuilder_Test.cls
/**
 * Created by Nikolay Kolev on 4/18/2019.
 * OWNED BY THE CRM SALES TEAM.
 */

@IsTest
private class TestFleetAssetDetailBuilder_Test {
    @IsTest
    static void testDefaultBuild() {
        System.Test.startTest();
        Fleet_Asset_Detail__c fleetAssetDetail = new TestFleetAssetDetailBuilder()
                .build();
        System.Test.stopTest();

        System.assertEquals(null, fleetAssetDetail.Id);
        System.assertEquals('Test_Fleet_Asset_Detail',fleetAssetDetail.Name);
    }
    @IsTest
    static void testDefaultBuildSetName() {
        System.Test.startTest();
        Fleet_Asset_Detail__c fleetAssetDetail = new TestFleetAssetDetailBuilder()
                .setName('My_Fleet_Asset_Detail')
                .build();
        System.Test.stopTest();

        System.assertEquals(null, fleetAssetDetail.Id);
        System.assertEquals('My_Fleet_Asset_Detail',fleetAssetDetail.Name);
    }
    @IsTest
    static void testGenerate() {
        Platform__c platform = new TestPlatformBuilder().generate();

        System.Test.startTest();
        Fleet_Asset_Detail__c fleetAssetDetail = new TestFleetAssetDetailBuilder()
                .addField('Status__c', 'In Service')
                .setPlatform(platform.Id)
                .generate();
        System.Test.stopTest();

        Fleet_Asset_Detail__c insertedFleetAssetDetail = [
                SELECT
                        Id,
                        Platform_Name__c
                FROM Fleet_Asset_Detail__c
                WHERE Id = :fleetAssetDetail.Id
                AND Status__c = 'In Service'
                AND Platform_Name__c = :platform.Id
        ];

        System.assertEquals(insertedFleetAssetDetail.Id, fleetAssetDetail.Id);
    }
}