src/objects/Fleet_Asset_Detail__c/Fleet_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>BM 7/16/2013 - updated page layouts for Svcs Sf interfaces project</description>
    <label>Fleet Asset Aircraft</label>
    <nameField>
        <label>Fleet Asset Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Asset Aircraft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fleet_Asset_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Account (Customer) Name associated with this Fleet entry.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND ( NOT 2)</booleanFilter>
        <errorMessage>Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Customer_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Account)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Platform_Name__r.Model__c</formula>
    <label>Aircraft Model</label>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/OEM_Name__c.field-meta.xml
<CustomField>
    <fullName>OEM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The OEM / Maker Name for the current Fleet entry.</inlineHelpText>
    <label>OEM Name</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>OEM Name: Account Status should not be inactive and Account Name should not contain Various</errorMessage>
        <filterItems>
            <field>Account.Report_Account_Name_upper__c</field>
            <operation>contains</operation>
            <value>VARIOUS</value>
        </filterItems>
        <infoMessage>Account Status should not be inactive and Account Name should not contain &quot;Various&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (OEM Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <inlineHelpText>The Platform Name for the current Fleet entry.</inlineHelpText>
    <label>Platform Name</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Fleet Asset Aircraft (Platform Name)</relationshipLabel>
    <relationshipName>Fleet_Asset_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <inlineHelpText>The Serial Number of the current Fleet entry.</inlineHelpText>
    <label>Serial Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Fleet_Asset_Detail__c/fields/Tail_Number__c.field-meta.xml
<CustomField>
    <fullName>Tail_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The Fleet entry&apos;s registered Tail Number.</inlineHelpText>
    <label>Tail Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <formula>Aircraft_Ref__r.Model__c</formula>
    <label>Aircraft Model</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The platform the opportunity will support.</inlineHelpText>
    <label>Platform</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Platform__c.Parent_Platform__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.SBU__c</field>
            <operation>equals</operation>
            <value>D&amp;S</value>
        </filterItems>
        <filterItems>
            <field>$Source.SBU__c</field>
            <operation>notEqual</operation>
            <value>D&amp;S</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity/fields/Platform_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name__c</fullName>
    <label>Platform Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Opportunity/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <formula>Aircraft_Ref__r.Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aircraft Serial Number</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Record Type</label>
</CustomObject>

src/objects/OpportunityLineItem/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <formula>Opportunity.Platform__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Platform</label>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Defines the Model.</inlineHelpText>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/OEM_Name__c.field-meta.xml
<CustomField>
    <fullName>OEM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defines the OEM/Maker Name for the current Platform.</inlineHelpText>
    <label>OEM Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms</relationshipLabel>
    <relationshipName>Platforms</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/utilClass.cls
public with sharing class utilClass 
{
   /* 
    public static string createAircraft
    (
        string pOwnerAccount,
        string pAirName,
        string pMake,
        string pModel,
        string pTail,
        string pSerialNbr 
    )
    {
        string retstr;
        
        integer errLoc =0;
        
        try
        {   
            errLoc = 10;
            
            Fleet_Asset_Detail__c createAir = new Fleet_Asset_Detail__c();
            
            createAir.Account__c            = pOwnerAccount;
            createAir.Name                  = pAirName;
            //createAir.Aircraft_Make__c    = pMake;
            //createAir.Aircraft_Model__c   = pModel;
            createAir.TAIL_NUMBER__C  = pTail;
            createAir.SERIAL_NUMBER__C  = pSerialNbr;
            
            List<Platform__c> airPlat = [ Select  Id From Platform__c 
                        Where   OEM_NAME__C = :pMake 
                        And     MODEL__C = :pModel 
                    ];
            
            if(airPlat != null && airPlat.size() > 0)
            {
                createAir.Platform_Name__c  = airPlat[0].Id;
            }
            
            
            errLoc = 20;                        
            insert createAir;
                        
                            if(createAir.Id!= null)
                            {
                                errLoc = 30;                                
                                retstr = createAir.Id;
                            }
                            else
                            {
                                errLoc = 40;                                
                                retstr = null;
                            }
                        errLoc = 50;            
            return retstr;
        
        }
        catch(DmlException e)
        {
                        createErrorLog
                                     (
                                     'utilClass',
                                     'createAircraft',
                                     'ERRLOC:'+errLoc+' - '+e.getMessage()
                                     );
                        retstr = null;
                        return retstr;
                        
        }
        
    }
    
    public static string createOppAircraft
                                        (
                                            string pOppId,
                                            string pAirId
                                        )
                                        {
                                            string retstr;
                                            integer errLoc =0;
                                            try
                                            {
                                                            errLoc =10;
                                                            
                                                            Opportunity_Fleet_Asset_Detail__c oppAircraft = new Opportunity_Fleet_Asset_Detail__c();
                                                            
                                                            oppAircraft.Fleet_Asset_Detail__c = pAirId;
                                                            oppAircraft.Opportunity__c = pOppId;
                                                            
                                                            List<Fleet_Asset_Detail__c> objAir = [select AIRCRAFT_REG_TAIL__c,Aircraft_Serial__c from Fleet_Asset_Detail__c where Id= :pAirId ];
                                                            
                                                            for(integer i=0;i<objAir.size();i++)
                                                            {
                                                                
                                                                oppAircraft.Tail_Number__c = objAir[0].AIRCRAFT_REG_TAIL__c;
                                                                oppAircraft.Aircraft_Serial_No__c = objAir[0].Aircraft_Serial__c;
                                                                
                                                            }
                                                            
                                                            errLoc =20;
                                                            insert oppAircraft;
                                                            
                                                            errLoc =30;
                                                            if(oppAircraft.Id!= null)
                                                            {
                                                                    errLoc =40;
                                                                    retstr = oppAircraft.Id;
                                                            }
                                                            else
                                                            {
                                                                    errLoc =50;
                                                                    retstr = null;
                                                            }
                                                            
                                                            
                                                            Opportunity opp = new Opportunity(Id=pOppId);

                                                            for(integer i=0;i<objAir.size();i++)
                                                            {
                                                                opp.Aircraft_Reg_Tail__c = objAir[0].AIRCRAFT_REG_TAIL__c;
                                                                opp.Aircraft_Serial__c   = objAir[0].Aircraft_Serial__c;
                                                            }
                                                            
                                                             update opp;
                                                            
                                                            errLoc =60; 
                                                            return retstr;
                                            }
                                            catch(DmlException e)
                                            {
                                                createErrorLog
                                                             (
                                                             'utilClass',
                                                             'createOppAircraft',
                                                             'ERRLOC:'+errLoc+' - '+e.getMessage()
                                                             );     
                                                                
                                                retstr = null;
                                                return retstr;
                        
                                            }

                                            
                                            
                                        }
    */
 /*   public static string createOppProduct
                                        (
                                                string  pDescription ,
                                                string  pOpportunityId ,
                                                string  pPriceBookEntryId ,
                                                integer pQuantity ,
                                                date    pServiceDate ,
                                                double  pUnitPrice  
                                        )
    {
        string retstr;
        integer errLoc =0;
        
        try
        {   
                            errLoc =10;
                            OpportunityLineItem  createOppProd = new OpportunityLineItem();
                        
                            createOppProd.Description       = pDescription      ; 
                            createOppProd.OpportunityId     = pOpportunityId    ; 
                            createOppProd.PriceBookEntryId  = pPriceBookEntryId ;
                            createOppProd.Quantity          = pQuantity         ;
                            createOppProd.ServiceDate       = pServiceDate      ;
                            createOppProd.UnitPrice         = pUnitPrice        ; 
                            
                            errLoc =20;
                        
                            insert createOppProd;
                            
                            errLoc =30;
                            
                            if(createOppProd.Id!= null)
                            {
                                errLoc =40; 
                                retstr = createOppProd.Id;
                            }
                            else
                            {
                                errLoc =50;
                                retstr = null;
                            }
            errLoc =60;
            return retstr;
        
        }
        catch(DmlException e)
        {
                                                createErrorLog
                                                             (
                                                             'utilClass',
                                                             'createOppProduct',
                                                             e.getMessage()
                                                             );         
            
                        retstr = null;
                        return retstr;
                        
        }
        
    }*/

    
        public static void createErrorLog
                                        (
                                                string  pTableName      ,
                                                string  pCodeObjectName ,
                                                string  pErrorMsg 
                                        )
    {
        

        
    }
    
    
}