src/objects/Campaign_Gate__c/Campaign_Gate__c.object-meta.xml
<CustomObject>
    <label>Campaign Tollgate</label>
    <nameField>
        <label>Tollgate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Tollgates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Gate__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Campaign_Gates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Campaign_Gate_Approval_History__c/Campaign_Gate_Approval_History__c.object-meta.xml
<CustomObject>
    <label>Campaign Tollgate  Approval History</label>
    <nameField>
        <displayFormat>CPAH-{0000}</displayFormat>
        <label>Tollgate  Approval History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Tollgate  Approval History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Gate_Approval_History__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <label>Approver Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Campaign_Gate_Approval_History__c/fields/Campaign_Phase__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Phase__c</fullName>
    <label>Campaign Tollgate</label>
    <referenceTo>Campaign_Gate__c</referenceTo>
    <relationshipLabel>Campaign Tollgate  Approval History</relationshipLabel>
    <relationshipName>Campaign_Gate_Approval_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Campaign_Gate_Approval_History__c/fields/Campaign_Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Team_Name__c</fullName>
    <label>Campaign Team Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Campaign_Team__c/Campaign_Team__c.object-meta.xml
<CustomObject>
    <label>Campaign Team</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Campaign Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Team__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Campaign_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Campaign_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Contact should be Honeywell Employee (Contact Is Employee = Checked) and Contact Status should not be inactive</errorMessage>
        <filterItems>
            <field>Contact.Contact_Is_Employee__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <infoMessage>Contacts listed are Honeywell Employees</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaign Team (Contact)</relationshipLabel>
    <relationshipName>Campaign_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Campaign_Team__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Team_User__c !=null, Team_User__r.Email ,IF(Contact__c !=null, Contact__r.Email ,&apos;&apos;))</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

src/objects/Campaign_Team__c/fields/Team_User__c.field-meta.xml
<CustomField>
    <fullName>Team_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/SendcampaignApprovalMail.cls
/** * File Name: SendcampaignApprovalMail 
* Description Controller for the visualforce page which displays the Campaign team members for
 *Phase approval and inserts record in the Campaign_Gate_Approval_History__c object
* Copyright : Wipro Technologies Limited Copyright (c) 2010
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 

public class SendcampaignApprovalMail {

public boolean showlist{get; set;}
public boolean backto{get; set;}
 boolean showerror = false;
List<Oppwrap> wrapper=new List<Oppwrap>();

List<String> team = new List<String>();
List<Campaign_Gate_Approval_History__c> ApproveobjRec=new List<Campaign_Gate_Approval_History__c>();
public Id oppGateId;
public Id oppId;  

public SendcampaignApprovalMail(ApexPages.StandardController controller) {
  oppGateId = System.currentPageReference().getParameters().get('id');
  Campaign_Gate__c og= [Select o.Campaign__c, o.Id From Campaign_Gate__c o where o.Id=: oppGateId];
      oppId=og.Campaign__c;
      System.debug('oppId -- > '+oppId);
//Code to avoid duplicate approvals being sent to users/contacts 
   List<Campaign_Gate_Approval_History__c> ch = [select name,Campaign_Team_Name__c from Campaign_Gate_Approval_History__c where Campaign_Phase__c = : oppGateId ];
   for(integer i=0;i<ch.size();i++)
   {
   team.add(ch[i].Campaign_Team_Name__c);
   }
    List<Campaign_Team__c> oppcon = [Select team_user__r.name,contact__r.name,contact__r.email,team_user__r.email,name from Campaign_Team__c where campaign__c=:oppId and name not in :team];
         
            System.debug('oppcon '+ oppcon);
            if(oppcon.size()==0)
            {
            showlist = false;
            backto = true;
            System.debug('campaign team nulllllll ');
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'There are no Campiagn Team Members for the Campaign '));
            }
            else
            {
            for(integer i=0;i<oppcon.size();i++)
            {
            System.debug('Contact role oppId -- > '+oppId);
            if(oppcon[i].team_user__c == null)
            {
            showlist = true;
            backto = false;
            wrapper.add(new Oppwrap(oppcon[i].contact__r.name,'Contact',oppcon[i].contact__r.email,oppcon[i].name));
            }
            if(oppcon[i].contact__c == null)
            {
            showlist = true;
            backto =false;
            wrapper.add(new Oppwrap(oppcon[i].team_user__r.name,'User',oppcon[i].team_user__r.email,oppcon[i].name));
            }
            }
        }
}
    public pagereference sendMail() {
    try{     
           System.debug('wrapper.size() -- > '+wrapper.size());
           for(Integer i=0;i<wrapper.size();i++){
           if(wrapper[i].selected==true && wrapper[i].Email==null)
    {   
     ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please select contact with email id '));
         return null;
    }
     //Code to insert records in Campaign_Gate_Approval_History__c object
            if(wrapper[i].selected==true && wrapper[i].Email!=null){
                
                showerror = true;
                Campaign_Gate_Approval_History__c aprec=new Campaign_Gate_Approval_History__c();
                aprec.Approval_Status__c='Pending';
                aprec.Campaign_Phase__c=oppGateId;
                aprec.Email__c=wrapper[i].Email;
                aprec.Approver_Email__c=wrapper[i].Email;
                aprec.Approver_Name__c=wrapper[i].Name;
                aprec.Campaign_Team_Name__c=wrapper[i].team;
                ApproveobjRec.add(aprec);
                
            }
            
            System.debug('wrapper[i].selected==true'+wrapper[i].selected);
        }
         if(ApproveobjRec.size()==0)
    {   
     ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please select atleast one Campaign Team Member '));
         return null;
    }
   
      Database.SaveResult[] lsr = Database.insert(ApproveobjRec,false);
      PageReference oppPage = new PageReference('/' + oppGateId);
      oppPage.setRedirect(true);
      return  oppPage;
       
       
       
      
    }
     catch(Exception e)    
          {   
                  System.debug('Exception............e'+e);   
           } 
         return null;
    }
   //Usage of wrapper class
public class Oppwrap{
     public boolean selected{get;set;}
     public String Name{get;set;}
     public String Obj{get;set;}
     public String Email{get;set;}
     public String team{get;set;}
     public Oppwrap(String Nm,String Ob,String mailId,String team){
          this.Name=Nm;
          this.Obj=Ob;
          this.Email=mailId;
          this.team=team;
          this.selected=true;
     }
 }
    public List<Oppwrap> getWrapper(){
        return this.wrapper;
    }
    public void setWrapper(List<Oppwrap> op){
        this.wrapper=op;
    }
    public PageReference Back()
    {
      PageReference oppPage = new PageReference('/' + oppId);
        return  oppPage; 
    }
    public PageReference cancelmail()
    {
      PageReference oppPage = new PageReference('/' + oppgateId);
        return  oppPage; 
    }
}