src/objects/VOC_OVOC_Record_Number__c/VOC_OVOC_Record_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will store the VOC/OVOC record number and will increment each record by 1 every time a record is saved</description>
    <label>VOC/OVOC Record Number</label>
</CustomObject>

src/objects/VOC_OVOC_Record_Number__c/fields/OVOC__c.field-meta.xml
<CustomField>
    <fullName>OVOC__c</fullName>
    <label>OVOC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/VOC_OVOC_Record_Number__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/Voice_of_Customer__c.object-meta.xml
<CustomObject>
    <label>VOC</label>
    <nameField>
        <displayFormat>VOC-{0000}</displayFormat>
        <label>Voice of Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOC Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Voice_of_Customer__c/fields/Date_of_VOC__c.field-meta.xml
<CustomField>
    <fullName>Date_of_VOC__c</fullName>
    <description>Its a Date of VOC</description>
    <label>Date of VOC</label>
    <type>Date</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/OVOC__c.field-meta.xml
<CustomField>
    <fullName>OVOC__c</fullName>
    <label>OVOC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Services</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Crew Interface</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Lighting</fullName>
            </value>
            <value>
                <fullName>Mechanical Components</fullName>
            </value>
            <value>
                <fullName>Mechanical Subsystems</fullName>
            </value>
            <value>
                <fullName>Navigation Systems &amp; Sensors</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Platform Systems</fullName>
            </value>
            <value>
                <fullName>Propulsion</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Info Mgmt</fullName>
            </value>
            <value>
                <fullName>Wheels &amp; Brakes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/selectedgroup__c.field-meta.xml
<CustomField>
    <fullName>selectedgroup__c</fullName>
    <label>selectedgroup</label>
    <length>235</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>NOTE: When “Sensitive Information” is selected, VOC information is available to key CBT members only</inlineHelpText>
    <label>Sensitive Information?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Its a VOC Name of Title</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/classes/VoiceofcustomerTestclass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seealldata=true)
private class VoiceofcustomerTestclass {

    static testMethod void myUnitTest() {
        
        /*VOC_OVOC_Record_Number__c vocrn = new VOC_OVOC_Record_Number__c();
        vocrn.Name='Reference record';
        vocrn.VOC__c = '1999';
        vocrn.OVOC__c = '2222';
        insert vocrn;*/
        
        Voice_of_Customer__c voc= new Voice_of_Customer__c();
        voc.Title__c='VOCTest';
        voc.sensitive__c=false;
        voc.Product_Family__c='[test;test1]';
        //voc.selectedgroup__c='a4Je0000000CdEhEAK';
        //insert voc;
        
        Attachment attach=new Attachment();    
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=voc.id;
        //insert attach;
        
                
      list<string>selectedgroup= new list<string>();
      ApexPages.StandardController con = new ApexPages.StandardController(voc);
      
      
      PageReference pageRef = Page.VocCreate;
      Test.setCurrentPage(pageRef);
      
       
      VoiceofcustomerClass vc= new VoiceofcustomerClass(con);
          
       
      
      
      VC.attachment=attach;
      vc.attachment.Body=Blob.valueOf('Unit Test Attachment Body');
      vc.getselectedgroup();
      vc.setselectedgroup(selectedgroup);
      vc.checkforaccount();
      vc.clearform();
      vc.depedentvalue();
      vc.attachment=attach;
      //vc.attachment();
      vc.gettype();
      vc.getchattergroup();
      vc.getproductfamily();
      vc.save();
      vc.showgroup();
      vc.oemsetval();
    }
    static testMethod void myUnitTest1() {
        
        /*VOC_OVOC_Record_Number__c vocrn = new VOC_OVOC_Record_Number__c();
        vocrn.Name='Reference record';
        vocrn.VOC__c = '1999';
        vocrn.OVOC__c = '2222';
        insert vocrn;*/
        
        Voice_of_Customer__c voc= new Voice_of_Customer__c();
        voc.Title__c='VOCTest';
        voc.sensitive__c=true;
        voc.Product_Family__c='[test;test1]';
        voc.RecordTypeid = '012a0000001ZPAJ';
        voc.selectedgroup__c='a4Je0000000CdEhEAK';
        voc.Date_of_VOC__c = system.today().addDays(-4);
        //insert voc;
    
        
        Attachment attach=new Attachment();    
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=voc.id;
        //insert attach;
        
                
      list<string>selectedgroup= new list<string>();
      ApexPages.StandardController con = new ApexPages.StandardController(voc);

      
      PageReference pageRef = Page.VocCreate;
      Test.setCurrentPage(pageRef);
      ApexPages.currentPage().getParameters().put('RecordType','012a0000001ZPAJ'); 
      
       
      VoiceofcustomerClass vc= new VoiceofcustomerClass(con);
          
       
      
      
      VC.attachment=attach;
      vc.attachment.Body=Blob.valueOf('Unit Test Attachment Body');
      vc.getselectedgroup();
      vc.setselectedgroup(selectedgroup);
      vc.checkforaccount();
      vc.clearform();
      vc.depedentvalue();
      vc.attachment=attach;
      //vc.attachment();
      vc.gettype();
      vc.getchattergroup();
      vc.getproductfamily();
      vc.save();
      vc.showgroup();
      vc.oemsetval();
    }
}