src/objects/Go_Green_Plan__c/Go_Green_Plan__c.object-meta.xml
<CustomObject>
    <label>Go Green Plan</label>
    <nameField>
        <displayFormat>GGP-{00000}</displayFormat>
        <label>Go Green Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go Green plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Go_Green_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Go Green plans</relationshipLabel>
    <relationshipName>Go_Green_plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Go_Green_Plan__c/fields/GGP_Status_del__c.field-meta.xml
<CustomField>
    <fullName>GGP_Status_del__c</fullName>
    <label>GGP Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Go_Green_Plan__c/fields/Go_Green_Status__c.field-meta.xml
<CustomField>
    <fullName>Go_Green_Status__c</fullName>
    <label>Go Green Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Go_Green_Plan__c/fields/Interviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSPM Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Go_Green_plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Go_Green_Plan__c/fields/Prod_LN_Prgm_Product_LIne__c.field-meta.xml
<CustomField>
    <fullName>Prod_LN_Prgm_Product_LIne__c</fullName>
    <label>Prod LN/Prgm Product LIne</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advanced Programs</fullName>
            </value>
            <value>
                <fullName>Advanced Technology</fullName>
            </value>
            <value>
                <fullName>AFSB</fullName>
            </value>
            <value>
                <fullName>AFSB 401st</fullName>
            </value>
            <value>
                <fullName>AFSB 402nd</fullName>
            </value>
            <value>
                <fullName>Aftermarket Summary</fullName>
            </value>
            <value>
                <fullName>AGENCY</fullName>
            </value>
            <value>
                <fullName>AH-64</fullName>
            </value>
            <value>
                <fullName>Albuquerque</fullName>
            </value>
            <value>
                <fullName>APU</fullName>
            </value>
            <value>
                <fullName>APU - 131-9A</fullName>
            </value>
            <value>
                <fullName>APU - 131-9B</fullName>
            </value>
            <value>
                <fullName>APU - 131-9D</fullName>
            </value>
            <value>
                <fullName>APU - 131-9 Series</fullName>
            </value>
            <value>
                <fullName>APU - 331-200/-250</fullName>
            </value>
            <value>
                <fullName>APU - 331-350/-400</fullName>
            </value>
            <value>
                <fullName>APU - 331-500</fullName>
            </value>
            <value>
                <fullName>APU - 331-600</fullName>
            </value>
            <value>
                <fullName>APU - 331 Series</fullName>
            </value>
            <value>
                <fullName>APU - 36-100/-150 Series</fullName>
            </value>
            <value>
                <fullName>APU - 36-100 Series</fullName>
            </value>
            <value>
                <fullName>APU - 36-150 Series</fullName>
            </value>
            <value>
                <fullName>APU - 36-280</fullName>
            </value>
            <value>
                <fullName>APU - 36-300</fullName>
            </value>
            <value>
                <fullName>APU - 85 Series</fullName>
            </value>
            <value>
                <fullName>APU - APU Sunset Models</fullName>
            </value>
            <value>
                <fullName>APU - GTCP660</fullName>
            </value>
            <value>
                <fullName>APU - GTCP700</fullName>
            </value>
            <value>
                <fullName>APU - HGT1500</fullName>
            </value>
            <value>
                <fullName>APU - HGT Series</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/User.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User/fields/Functional_Role__c.field-meta.xml
<CustomField>
    <fullName>Functional_Role__c</fullName>
    <label>Functional Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Team Lead</fullName>
            </value>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Aftermarket Manager</fullName>
            </value>
            <value>
                <fullName>Aftermarket Sales Manager</fullName>
            </value>
            <value>
                <fullName>Airline Business Manager</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Area Sales</fullName>
            </value>
            <value>
                <fullName>Area Sales - Mgt Co</fullName>
            </value>
            <value>
                <fullName>Area Sales - Operator</fullName>
            </value>
            <value>
                <fullName>Business Administration</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Business Management AMERICAS</fullName>
            </value>
            <value>
                <fullName>Business Management APAC</fullName>
            </value>
            <value>
                <fullName>Business Management EMEAI</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Business Operations Manager</fullName>
            </value>
            <value>
                <fullName>Campaign Manager</fullName>
            </value>
            <value>
                <fullName>Capture Manager</fullName>
            </value>
            <value>
                <fullName>CBT Leader</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Contracts Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TestGGPEmailservice.cls
@isTest(seealldata=true)
public class TestGGPEmailservice{
static testmethod void GGPEmailservicetest(){

    Account acc= new Account(name='Test Account');
    insert acc;

   Profile ProfRec1 = [select name from Profile where name = 'D&S Sales API User'];

    User usr = new User(LastName = 'Test User',Username = 'testuser@test31.com.honeywell',Email = 'testuser@test.com',Alias = 't3user1' ,CommunityNickname= 't3user1' ,TimeZoneSidKey   = 'America/Los_Angeles',LocaleSidKey='en_US',EmailEncodingKey= 'ISO-8859-1',ProfileId = ProfRec1.Id, LanguageLocaleKey = 'en_US',Functional_Role__c='testrole');
insert usr;

   Go_Green_Plan__c gp= new Go_Green_Plan__c (Go_Green_Status__c='TestP',account__c=acc.Id, Prod_LN_Prgm_Product_LIne__c='APU', GGP_Status_del__c='open', Interviewer_Name__c=usr.id);
    insert gp;

   Go_Green_Plan__c gplist=[select id,name from Go_Green_Plan__c where id=:gp.id];

     string name='GGP#'+gplist.Name;
    Messaging.InboundEmail email = new Messaging.InboundEmail();
    Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();

    //string ggpnumber = 'GGP-00801';
    //Go_green_plan__c[]   ggp=[select id,Name,ownerId from Go_green_plan__c where name=:gp.name];

    Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
    attachment.body = blob.valueOf('my attachment text');
    attachment.fileName = 'textfile.txt';
    attachment.mimeTypeSubType = 'text/plain';
 
    email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
    //email.subject = 'GGP#GGP-00801';
     email.subject = name;
     GGPEmailservice  emailProcess = new GGPEmailservice();
     emailProcess.handleInboundEmail(email, envelope);
}
}