src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/A_Event_Duration__c.field-meta.xml
<CustomField>
    <fullName>A_Event_Duration__c</fullName>
    <label>A check Time Frame ( Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/ACHK_NUM__c.field-meta.xml
<CustomField>
    <fullName>ACHK_NUM__c</fullName>
    <inlineHelpText>Airframe A Check period/interval in Hrs</inlineHelpText>
    <label>A Check Flight Hours</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/Avg_Flying_Hors_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>Avg_Flying_Hors_Per_Year__c</fullName>
    <formula>Avg_Flying_Hours_Per_Month__c *12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Flying Hours Per Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/Avg_Flying_Hours_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Avg_Flying_Hours_Per_Month__c</fullName>
    <label>Avg Flying Hours  ( Per Month )</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/B_Event_Duration__c.field-meta.xml
<CustomField>
    <fullName>B_Event_Duration__c</fullName>
    <label>B check Time Frame ( Months )</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/BCHK_NUM__c.field-meta.xml
<CustomField>
    <fullName>BCHK_NUM__c</fullName>
    <inlineHelpText>Airframe B Check period/interval in Hrs</inlineHelpText>
    <label>B Check Flight Hours</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/C_Event_Duration__c.field-meta.xml
<CustomField>
    <fullName>C_Event_Duration__c</fullName>
    <label>C check Time Frame ( Months )</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/CCHK_NUM__c.field-meta.xml
<CustomField>
    <fullName>CCHK_NUM__c</fullName>
    <inlineHelpText>Airframe C Check period/interval in Hrs</inlineHelpText>
    <label>C Check Flight Hours</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/TestClass_ApexBatch_GenMainEvntPlt.cls
/** * File Name:  TestClass_ApexShdlr_GenMainEvntPlt
* Description Test Method
* Class Tested: GenerateMaintEvent_Platform_C 
* Copyright : Wipro Technologies Limited Copyright (c) 2011
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
@isTest
private class TestClass_ApexBatch_GenMainEvntPlt {

    static testMethod void genMainEvntPltATest() {
    	
    	Platform__c testPltfrmRec = new Platform__c (
                Name='Test Platform for EventA', 
                ACHK_NUM__c = 10 ,
                A_Event_Duration__c=10,
                Avg_Flying_Hours_Per_Month__c =2
            );
        insert testPltfrmRec;    
        Test.StartTest();
        GenerateMaintEvent_Platform_A tstGenMaintEvntPltfrmA = new GenerateMaintEvent_Platform_A();
        tstGenMaintEvntPltfrmA.query='SELECT Id From Platform__c Where (ACHK_NUM__c > 0 OR A_Event_Duration__c > 0) AND Avg_Flying_Hors_Per_Year__c > 0 and ID=\''+testPltfrmRec.Id+'\'';
        ID batchprocessId = Database.executeBatch(tstGenMaintEvntPltfrmA);
        Test.StopTest();
    }
    static testMethod void genMainEvntPltBTest() {
        Platform__c testPltfrmRec = new Platform__c (
                Name='Test Platform for EventB', 
                BCHK_NUM__c = 10 ,
                B_Event_Duration__c=10,
                Avg_Flying_Hours_Per_Month__c =2
            );
        insert testPltfrmRec;    
        Test.StartTest();
        GenerateMaintEvent_Platform_B tstGenMaintEvntPltfrmB = new GenerateMaintEvent_Platform_B();
        tstGenMaintEvntPltfrmB.query='SELECT Id From Platform__c Where (BCHK_NUM__c > 0 OR B_Event_Duration__c > 0) AND Avg_Flying_Hors_Per_Year__c > 0 and ID=\''+testPltfrmRec.Id+'\'';
        ID batchprocessId = Database.executeBatch(tstGenMaintEvntPltfrmB);
        Test.StopTest();
    }
    static testMethod void genMainEvntPltCTest() {
        Platform__c testPltfrmRec = new Platform__c (
                Name='Test Platform for EventC', 
                CCHK_NUM__c = 10 ,
                C_Event_Duration__c=10,
                Avg_Flying_Hours_Per_Month__c =2
            );
        insert testPltfrmRec;    
        Test.StartTest();
        GenerateMaintEvent_Platform_C tstGenMaintEvntPltfrmC = new GenerateMaintEvent_Platform_C();
        tstGenMaintEvntPltfrmC.query='SELECT Id From Platform__c Where (CCHK_NUM__c > 0 OR C_Event_Duration__c > 0) AND Avg_Flying_Hors_Per_Year__c > 0 and ID=\''+testPltfrmRec.Id+'\'';
        ID batchprocessId = Database.executeBatch(tstGenMaintEvntPltfrmC);
        Test.StopTest();
    }
}