src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/SRD_Supported__c.field-meta.xml
<CustomField>
    <fullName>SRD_Supported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SRD Supported?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>SR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Request__c/fields/Aircraft_Type__c.field-meta.xml
<CustomField>
    <fullName>Aircraft_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Mandatory on Technical SRs. If additional aircraft inpacted, add in the Aircraft/Platforms Affected section below</inlineHelpText>
    <label>Aircraft Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Platform__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Platform__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Service_Request__c/fields/Atr__c.field-meta.xml
<CustomField>
    <fullName>Atr__c</fullName>
    <inlineHelpText>For attribute definitions, see the SW document on the C&amp;PS HOS SharePoint under Standard Work, Service Requests, tab titled &quot;Attribute Definitions.&quot; Contact SR Core Team for adding attributes, or contact aerocpscontroltower@honeywell.com</inlineHelpText>
    <label>Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Reliability</fullName>
            </value>
            <value>
                <fullName>Repairs Delivery</fullName>
            </value>
            <value>
                <fullName>Responsiveness</fullName>
            </value>
            <value>
                <fullName>Service/Support</fullName>
            </value>
            <value>
                <fullName>Spares Delivery</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>OEM/Spares Delivery</fullName>
            </value>
            <value>
                <fullName>R&amp;O Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Count_Of_SRD_Supported__c.field-meta.xml
<CustomField>
    <fullName>Count_Of_SRD_Supported__c</fullName>
    <label>Count Of SRD Supported</label>
    <summaryFilterItems>
        <field>Aircraft_Platforms_Affected__c.SRD_Supported__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Aircraft_Platforms_Affected__c.Service_Request__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/objects/Service_Request__c/fields/Criteria_Score__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Score__c</fullName>
    <formula>X1st_18Mth_EIS_Score__c + Previous_Inv_Score__c + Financial_12mth_Score__c + Cust_Impact_Score__c + Reliability_Score__c + Prod_Maturity_Score__c</formula>
    <label>Criteria Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Service_Request__c/fields/CUS_IFSD_21_3_FMS__c.field-meta.xml
<CustomField>
    <fullName>CUS_IFSD_21_3_FMS__c</fullName>
    <description>CUS = Condition Under Study, Potential Safety or Known Safety Of Flight, 21.3 reportable event, In flight shutdown</description>
    <label>CUS, IFSD, 21.3, FMS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Cust_Impact__c.field-meta.xml
<CustomField>
    <fullName>Cust_Impact__c</fullName>
    <description>Customer Impact</description>
    <label>Cust Impact</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nuisance or Work around available</fullName>
            </value>
            <value>
                <fullName>Top 10 D&amp;C driver</fullName>
            </value>
            <value>
                <fullName>Air Turn Back or Diversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Customer_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Due_Date__c</fullName>
    <inlineHelpText>Date, discussed, agreed upon, and committed to the Customer raising the issue of this SR</inlineHelpText>
    <label>Customer Due Date</label>
    <type>DateTime</type>
</CustomField>

src/objects/Service_Request__c/fields/Date_Initiated__c.field-meta.xml
<CustomField>
    <fullName>Date_Initiated__c</fullName>
    <inlineHelpText>Date of record creation - within 30 days from submission by customer</inlineHelpText>
    <label>Date Initiated</label>
    <type>DateTime</type>
</CustomField>

src/objects/Service_Request__c/fields/Deliverable__c.field-meta.xml
<CustomField>
    <fullName>Deliverable__c</fullName>
    <description>Actions necessary to close the SR and meet or exceed customer expectations</description>
    <inlineHelpText>Deliverables required to close issue. Expectations from customer. Do not include any Restricted information including but not limited to, Regulatory Restricted (e.g. Export Controlled, DFARS, etc.) or Contractually Obligated Restricted information</inlineHelpText>
    <label>Deliverable</label>
    <type>TextArea</type>
</CustomField>

src/objects/Service_Request__c/fields/Financial_12mth__c.field-meta.xml
<CustomField>
    <fullName>Financial_12mth__c</fullName>
    <description>Anticipated 12 Month Financial Impact to Honeywell (MSA cost, warranty, loss of sales, etc)</description>
    <label>Financial 12mth</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>$100K to $250K</fullName>
            </value>
            <value>
                <fullName>$250K to $1M</fullName>
            </value>
            <value>
                <fullName>Greater than $1M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Investigate__c.field-meta.xml
<CustomField>
    <fullName>Investigate__c</fullName>
    <formula>IF(AND(ISPICKVAL(CUS_IFSD_21_3_FMS__c,&quot;&quot;),ISPICKVAL(X1st_18Mth_EIS__c,&quot;&quot;)),&quot;&quot;,IF(OR(ISPICKVAL(CUS_IFSD_21_3_FMS__c,&quot;Yes&quot;),AND(ISPICKVAL(X1st_18Mth_EIS__c,&quot;No&quot;), Criteria_Score__c &gt;= VALUE($Label.RDF_QFD_Cutoff_Score), Count_Of_SRD_Supported__c &gt;0, Previous_Inv_Score__c = 0)),&quot;YES&quot;,&quot;NO&quot;))</formula>
    <label>Investigate</label>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/fields/Legacy_Siebel_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Siebel_Account_Id__c</fullName>
    <label>Queue Priority #</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Service_Request__c/fields/Previous_Inv__c.field-meta.xml
<CustomField>
    <fullName>Previous_Inv__c</fullName>
    <description>Previously had SRD program or  Fielded SRD</description>
    <label>Previous Inv</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NO</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Recent SRD/Investigated &lt;Yr</fullName>
            </value>
            <value>
                <fullName>Recent SRD/Investigated &lt;3 Yrs</fullName>
            </value>
            <value>
                <fullName>Recent SRD/Investigated &lt;5 Yrs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/Previous_Inv_Score__c.field-meta.xml
<CustomField>
    <fullName>Previous_Inv_Score__c</fullName>
    <formula>VALUE(TEXT(Value($Label.RDF_Previous_Inv_Weighting) * Previous_Inv_History__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Inv Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Service_Request__c/fields/Problem_Description__c.field-meta.xml
<CustomField>
    <fullName>Problem_Description__c</fullName>
    <inlineHelpText>Detailed (clear &amp; concise) summary of the problem. Do not include any Restricted information including but not limited to, Regulatory Restricted (e.g. Export Controlled, DFARS, etc.) or Contractually Obligated Restricted information</inlineHelpText>
    <label>Problem Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Service_Request__c/fields/Prod_Maturity__c.field-meta.xml
<CustomField>
    <fullName>Prod_Maturity__c</fullName>
    <description>Product Maturity (Product Rankings)</description>
    <label>Prod Maturity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunset – Kill program and refer to GBE/PAC for consideration</fullName>
            </value>
            <value>
                <fullName>Stable</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/QFD_Entry_Logic__c.field-meta.xml
<CustomField>
    <fullName>QFD_Entry_Logic__c</fullName>
    <label>QFD Entry / Logic</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/fields/QFD_Entry_Logic_History__c.field-meta.xml
<CustomField>
    <fullName>QFD_Entry_Logic_History__c</fullName>
    <formula>TEXT(Criteria_Score__c)&amp; &quot;, &quot; &amp; IF(ISPICKVAL(CUS_IFSD_21_3_FMS__c,&quot;Yes&quot;),&quot;IFSD,FMS,PVA&quot;,
IF(ISPICKVAL(X1st_18Mth_EIS__c,&quot;Yes&quot;),&quot;EIS&quot;,IF(Previous_Inv_Score__c&lt;0,&quot;Previous&quot;,
IF(Count_Of_SRD_Supported__c = 0,&quot;Platform&quot;,IF(Criteria_Score__c &lt; VALUE($Label.RDF_QFD_Cutoff_Score),&quot;Below 40&quot;,&quot;Above&quot;)))))</formula>
    <label>QFD Entry / Logic History</label>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/fields/Reliability__c.field-meta.xml
<CustomField>
    <fullName>Reliability__c</fullName>
    <description>Reliability Impact</description>
    <label>Reliability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>At or above guarantee’s (PSAA or other)</fullName>
            </value>
            <value>
                <fullName>Platform Fleet Perf up to LT 40%  Below Target</fullName>
            </value>
            <value>
                <fullName>Platform Fleet Perf GT 40% Below Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/sr_owner__c.field-meta.xml
<CustomField>
    <fullName>sr_owner__c</fullName>
    <inlineHelpText>Populated by IRB from AeroPDM</inlineHelpText>
    <label>IRB Owner</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>&quot;Open&quot;: Investigation is active or fix is in work.
&quot;Closed&quot;: Issue has been resolved or completed.
&quot;Monitor&quot;: Issue is waiting for additional information from customer or there is a request for issue to be monitored.
&quot;Queue&quot;: SR awaiting to be assigned</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Containment</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>RCCA</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Service_Request__c/fields/X1st_18Mth_EIS__c.field-meta.xml
<CustomField>
    <fullName>X1st_18Mth_EIS__c</fullName>
    <label>1st 18Mth &amp; EIS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/QFDFieldsAutoPopulation.cls
public class QFDFieldsAutoPopulation 
{
    public static void populateQFDFieldsData( List<Service_Request__c> newRecList, Boolean isBeforeExecute, Boolean isAfterExecute )
    { 
       Set<Id> SerReqID = new Set<Id> ();
       List<Service_Request__c> SRList = new List <Service_Request__c> ();
        
        for(Service_Request__c serRec : newRecList ){
           SerReqID.add(serRec.Id);
        }

        system.debug('SerReqID=========>'+SerReqID);
        
        if(SerReqID.size() > 0 && isAfterExecute) 
        {
            SRList = [Select id, Atr__c, QFD_Entry_Logic__c,Legacy_Siebel_Account_Id__c,Count_Of_SRD_Supported__c , QFD_Entry_Logic_History__c, Criteria_Score__c, CUS_IFSD_21_3_FMS__c, X1st_18Mth_EIS__c,Previous_Inv__c,Override__c,
                      Financial_12mth__c,Cust_Impact__c,Reliability__c,Prod_Maturity__c,Previous_Inv_Score__c,Aircraft_Type__r.SRD_Supported__c, Investigate__c, CreatedDate, Date_Initiated__c, Customer_Due_Date__c,Date_Closed__c,sr_owner__c, Status__c,
                      Problem_Description__c, Deliverable__c, Status_Resolution__c,RecordType.Name,Platforms_Affected__c from Service_Request__c where ID IN : SerReqID  AND (RecordType.Name='Service Request' OR RecordType.Name ='SR(General)')];           
           
        }
        if(isBeforeExecute && !isAfterExecute)        
        {
          System.debug('Inside of Before Upadte');
          QFDFieldsAutoPopulation.formulateQFDData(newRecList, isBeforeExecute, isAfterExecute);
        }
        if(!isBeforeExecute && isAfterExecute)
        {
          System.debug('Inside of After Insert');
          QFDFieldsAutoPopulation.formulateQFDData(SRList, isBeforeExecute, isAfterExecute);
        } 
    }
    
    public static void formulateQFDData(List<Service_Request__c> newRecList,Boolean isBeforeExecute, Boolean isAfterExecute)
    {
    
      // QFD fields population code
        Map<ID, Service_Request__c> SRMap = new Map <ID, Service_Request__c> ();        
        Integer cutOffScore = Integer.valueOf(Label.RDF_QFD_Cutoff_Score);
        List<Service_Request__c> UpdateQFDList = new List<Service_Request__c> ();
        String OverideString = '';
        String QFDEntryLogic = '';
    
       for(Service_Request__c SR : newRecList) 
            {
                System.debug('Inside of QFD Fields');                
                Service_Request__c srObj = new Service_Request__c ();
                String CriteriaScore = String.ValueOf(SR.Criteria_Score__c);
                system.debug('CriteriaScore ====>'+CriteriaScore );
                Boolean isNegValue = false;                                
                 system.debug('SR.Platforms_Affected__c' + SR.Platforms_Affected__c);
                if((SR.CUS_IFSD_21_3_FMS__c == null || SR.Previous_Inv__c == null|| SR.Financial_12mth__c == null
                  || SR.Cust_Impact__c == null || SR.Reliability__c == null || SR.Prod_Maturity__c == null || SR.X1st_18Mth_EIS__c == null) 
                  || (SR.Platforms_Affected__c==null && SR.RecordTypeId==Schema.sobjecttype.Service_request__c.getRecordtypeInfosbyname().get('SR(General)').getRecordtypeId()) )
                {
                  system.debug('inside of null' );
                  SR.QFD_Entry_Logic__c = '';
                 if(!isBeforeExecute)
                  UpdateQFDList.add(SR);
                }
                else 
                {                 
                    if(String.isNotBlank(CriteriaScore))
                         isNegValue = CriteriaScore.contains('-');
                      
                      system.debug('inside of else' );
                      
                    If(SR.Criteria_Score__c != null )
                     {
                       if(CriteriaScore.length() == 2 && isNegValue )
                       {
                          QFDEntryLogic = '-00'+CriteriaScore.substring(1,2);                      
                       }
                       else if(CriteriaScore.length() == 3 && isNegValue )
                       {
                            QFDEntryLogic = '-0'+CriteriaScore.substring(1,3);                      
                       }
                       else if(CriteriaScore.length() == 1 && !isNegValue )
                       {                   
                           QFDEntryLogic = '00'+CriteriaScore;                     
                       }
                       else if(CriteriaScore.length() == 2 && !isNegValue )
                       {
                          QFDEntryLogic = '0'+CriteriaScore;                      
                       }                   
                       else
                       {
                         QFDEntryLogic = CriteriaScore;                         
                       }
                    }
                    If(!String.isEmpty(QFDEntryLogic))
                     {
                        System.debug('Inside of QFDEntryLogic');
    
                        If(SR.CUS_IFSD_21_3_FMS__c != null && SR.CUS_IFSD_21_3_FMS__c == 'Yes') 
                        {
                            QFDEntryLogic = QFDEntryLogic + ', ' + 'IFSD,FMS,PVA';
                        }
                        else if (SR.X1st_18Mth_EIS__c != null && SR.X1st_18Mth_EIS__c == 'Yes') 
                        {
                            QFDEntryLogic = QFDEntryLogic + ', ' + 'EIS';
                        } 
                        else if (SR.Previous_Inv_Score__c != null && SR.Previous_Inv_Score__c < 0)
                        {
                            QFDEntryLogic = QFDEntryLogic + ', ' + 'Previous';
                        } 
                        else if (SR.Count_Of_SRD_Supported__c  == 0)
                        {
                            QFDEntryLogic = QFDEntryLogic + ', ' + 'Platform';
                        } 
                        else if (SR.Criteria_Score__c != null && SR.Criteria_Score__c < cutOffScore) 
                        {
                            QFDEntryLogic = QFDEntryLogic + ', ' + 'Below 40';
                        } 
                        else
                        {
                            QFDEntryLogic = QFDEntryLogic + ', ' + 'Above';
                        }
    
                        if (SR.Investigate__c != null && SR.Investigate__c != '' && SR.Investigate__c == 'NO') {
                            QFDEntryLogic = QFDEntryLogic + ', ' + 'Rejected';
                        } 
                        else 
                        {
                            QFDEntryLogic = QFDEntryLogic;
                        } 
                        // Queue Priority# value Assigmment 
                        if(String.isBlank(SR.Legacy_Siebel_Account_Id__c))
                        {
                            SR.Legacy_Siebel_Account_Id__c = QFDEntryLogic;
                        }
                        else if(String.isNotBlank(SR.Legacy_Siebel_Account_Id__c) && SR.Legacy_Siebel_Account_Id__c.contains('Override') && SR.Override__c == false)
                        {
                             SR.Legacy_Siebel_Account_Id__c = QFDEntryLogic.replace('Override','Rejected') ;                              
                        }
                        else if(String.isNotBlank(SR.Legacy_Siebel_Account_Id__c) && SR.Legacy_Siebel_Account_Id__c.contains('Rejected') && SR.Override__c == true)
                        {
                             SR.Legacy_Siebel_Account_Id__c = QFDEntryLogic.replace('Rejected','Override') ;                              
                        } 
                        else
                        {
                             SR.Legacy_Siebel_Account_Id__c = QFDEntryLogic;
                        }
                         
                        SR.QFD_Entry_Logic__c = QFDEntryLogic;
                    }                    
                    System.debug('Inside of final String ===>' + QFDEntryLogic);
                    if(isAfterExecute && !isBeforeExecute){ 
                        UpdateQFDList.add(SR);
                    }  
                }    
            }
        System.debug('UpdateQFDList ======>'+UpdateQFDList );
        if(!UpdateQFDList.isEmpty() && !isBeforeExecute) 
        {
            upsert UpdateQFDList;
        }
    
    }
}