src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/Voice_of_Customer__c.object-meta.xml
<CustomObject>
    <label>VOC</label>
    <nameField>
        <displayFormat>VOC-{0000}</displayFormat>
        <label>Voice of Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOC Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Voice_of_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Voice_of_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Customer_Participant_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Participant_Name__c</fullName>
    <label>Customer (Participant) Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Customer_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_Email__c</fullName>
    <label>Customer’s Email</label>
    <type>Email</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Customer_s_Title_Role__c.field-meta.xml
<CustomField>
    <fullName>Customer_s_Title_Role__c</fullName>
    <label>Customer’s Title/Role</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Enddate__c.field-meta.xml
<CustomField>
    <fullName>Enddate__c</fullName>
    <label>Enddate</label>
    <type>Date</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Financial_Implications__c.field-meta.xml
<CustomField>
    <fullName>Financial_Implications__c</fullName>
    <label>Financial Implications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Honeywell__c.field-meta.xml
<CustomField>
    <fullName>Honeywell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Honeywell Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Voice_of_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Honeywell_Lead__c.field-meta.xml
<CustomField>
    <fullName>Honeywell_Lead__c</fullName>
    <label>Honeywell Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Is_Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Is_Sensitive__c</fullName>
    <formula>IF(Sensitive__c = true, &apos;Yes&apos;, &apos;No&apos;)</formula>
    <label>Is Sensitive</label>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Key_Takeaways1__c.field-meta.xml
<CustomField>
    <fullName>Key_Takeaways1__c</fullName>
    <label>Key Takeaways</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Platform</label>
    <referenceTo>Platform__c</referenceTo>
    <relationshipName>Voice_of_Customer</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aero Services</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Crew Interface</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Lighting</fullName>
            </value>
            <value>
                <fullName>Mechanical Components</fullName>
            </value>
            <value>
                <fullName>Mechanical Subsystems</fullName>
            </value>
            <value>
                <fullName>Navigation Systems &amp; Sensors</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Platform Systems</fullName>
            </value>
            <value>
                <fullName>Propulsion</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Info Mgmt</fullName>
            </value>
            <value>
                <fullName>Wheels &amp; Brakes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Purpose_of_this_VOC__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_this_VOC__c</fullName>
    <label>Purpose of this VOC</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Understanding the Market</fullName>
            </value>
            <value>
                <fullName>Sizing the Market</fullName>
            </value>
            <value>
                <fullName>Segmenting the Market</fullName>
            </value>
            <value>
                <fullName>Understanding Segment Needs</fullName>
            </value>
            <value>
                <fullName>Quantified Customer Needs</fullName>
            </value>
            <value>
                <fullName>Concept Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Security_Group__c</fullName>
    <label>Security Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airbus Restricted</fullName>
            </value>
            <value>
                <fullName>Boeing Restricted</fullName>
            </value>
            <value>
                <fullName>Bombardier Restricted</fullName>
            </value>
            <value>
                <fullName>Cessna Restricted</fullName>
            </value>
            <value>
                <fullName>China OEM Restricted</fullName>
            </value>
            <value>
                <fullName>D&amp;S Restricted</fullName>
            </value>
            <value>
                <fullName>Dassault Restricted</fullName>
            </value>
            <value>
                <fullName>Embraer Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Sensitive__c.field-meta.xml
<CustomField>
    <fullName>Sensitive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>NOTE: When “Sensitive Information” is selected, VOC information is available to key CBT members only</inlineHelpText>
    <label>Sensitive Information?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Startdate__c.field-meta.xml
<CustomField>
    <fullName>Startdate__c</fullName>
    <label>Startdate</label>
    <type>Date</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC_Collection__c.field-meta.xml
<CustomField>
    <fullName>VOC_Collection__c</fullName>
    <label>VOC Collection</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HTF 500 APU Collection</fullName>
            </value>
            <value>
                <fullName>Dessault Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC_Date__c.field-meta.xml
<CustomField>
    <fullName>VOC_Date__c</fullName>
    <label>VOC Date</label>
    <type>Date</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC_Hypothesis__c.field-meta.xml
<CustomField>
    <fullName>VOC_Hypothesis__c</fullName>
    <description>Its VOC  Hypothesis</description>
    <label>VOC Hypothesis</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Voice_of_Customer__c/fields/VOC_Title__c.field-meta.xml
<CustomField>
    <fullName>VOC_Title__c</fullName>
    <label>VOC Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/classes/VOC_ExportToExcel_controller.cls
public with sharing class VOC_ExportToExcel_controller{
    public List<Voice_of_Customer__c> voc{get; set;}
    list<Voice_of_Customer__c> voclist;
    public VOC_ExportToExcel_controller() {
        id pgid = ApexPages.currentPage().getParameters().get('id');
        voc = new List<Voice_of_Customer__c>();
        voclist = [select Id,(select id,Company_Name__c,Customer_s_Title_Role__c,Primary_Customer_s_Email__c,Contact__c,VOC_Record__c, Customer_name__c from VOC_Customer_Names__r), VOC__c,CreatedDate,Name,Company_Name__c,Customer_Participant_Name__c,Customer_s_Email__c,Customer_s_Title_Role__c,Purpose_of_this_VOC__c,Security_Group__c,VOC_Collection__c,VOC_Date__c,VOC_Title__c,Honeywell__c,Honeywell__r.Name,VOC_Hypothesis__c,Key_Takeaways1__c,Product_Name__c,Platform__c,Platform__r.Name,Product_Family__c,Sensitive__c,Is_Sensitive__c,Account__c,Enddate__c,Startdate__c,Financial_Implications__c,Honeywell_Lead__c,status__c from Voice_of_Customer__c where id =:pgid];
        for (Voice_of_Customer__c vc : voclist) {       
            voc.add(vc);
        }
    }
    
  /*  public PageReference sendPdf() {
    id pgid = ApexPages.currentPage().getParameters().get('id');
    PageReference pdf = Page.VOC_Email_to_pdf;
    // add parent id to the parameters for standardcontroller
    pdf.getParameters().put('id',pgid);

    // the contents of the attachment from the pdf
    Blob body;
    // returns the output of the page as a PDF
      body = pdf.getContent();

    // need to pass unit test -- current bug  
     // body = Blob.valueOf('Some Text');


    Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
    attach.setContentType('application/pdf');
    attach.setFileName('testPdf.pdf');
    attach.setInline(false);
    attach.Body = body;

    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    mail.setUseSignature(false);
    mail.setToAddresses(new String[] {'debajyoti.chatterjee@nttdata.com'});
    mail.setSubject('PDF Email Demo');
    mail.setHtmlBody('Here is the email you requested.');
    mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach }); 

    // Send the email
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Email with PDF sent to '));

    return null;

  }
  */
}