src/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Platform__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>added on demand by Dieter for data migration</description>
    <label>Make</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Make_Model__c.field-meta.xml
<CustomField>
    <fullName>Make_Model__c</fullName>
    <formula>Make__c +  Model__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Make &amp; Model</label>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Defines the Model.</inlineHelpText>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <inlineHelpText>Defines the Platform.</inlineHelpText>
    <label>Platform</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/Platform__c/fields/Serial_Number_Format__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number_Format__c</fullName>
    <label>Serial Number Format</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/classes/REG_API_Aircraft_test.cls
@IsTest
public class REG_API_Aircraft_test {
    
    @TestSetup
    static void fncDataSetup(){
        Reg_TestDataFactory.createTestRecords();
    }
    
    static testMethod void testGetAllAircraftAndModel(){
        
        RestRequest request = new RestRequest(); 
        RestResponse response = new RestResponse();
        RestContext.request = request;  
        RestContext.response= response;
        request.requestURI = '/aircrafts/';  //Request URL
        request.httpMethod = 'GET';//HTTP Request Type
        System.assertEquals('GET', request.httpMethod);
        list<Platform__c> aircrafts = [SELECT Make__c, Model__c, Serial_Number_Format__c FROM Platform__c where Make__c = 'testing' and Make_Model__c!=null ORDER BY Make__c ASC, Make_Model__c ASC];
        Map<String,List<String>> makeModelMap = new Map<String,List<String>>();
        List<REG_Aircraft_Wrapper> aircraftWrapperList = new List<REG_Aircraft_Wrapper>();
        test.startTest();
        REG_API_Aircrafts.doGet();
        test.stopTest();
        String result = response.responseBody.toString();
        List<REG_Aircraft_Wrapper> aircraftList = (List<REG_Aircraft_Wrapper>)JSON.deserialize(result, List<REG_Aircraft_Wrapper>.class);
        system.assert(!aircraftList.isEmpty());
        
    }
}