src/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Record Type</label>
</CustomObject>

src/objects/Opportunity_Sales_Team__c/Opportunity_Sales_Team__c.object-meta.xml
<CustomObject>
    <label>Opportunity Team</label>
    <nameField>
        <displayFormat>OT-{0}</displayFormat>
        <label>Opportunity Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Sales_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sales_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Opportunity_Sales_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Sales_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains Email Id of &apos;ATR Opportunity Scheduled Report&apos; recipients</description>
    <label>Users</label>
</CustomObject>

src/classes/TestOpportunityTeamBuilder.cls
/**
 * Created by Satya Mohanty on 4/25/2019.
 * OWNED BY THE CRM SALES TEAM.
 */
public class TestOpportunityTeamBuilder {

    private String name = 'testOpportunityTeam';
    private Id opportunityId;
    private Id userId;
    private Map<String, Object> fields = new Map<String, Object>();

    public TestOpportunityTeamBuilder() {}

    public TestOpportunityTeamBuilder setOpportunityId(Id opportunityId){
        this.opportunityId = opportunityId;

        return this;
    }
    public TestOpportunityTeamBuilder setUserId(Id userId) {
        this.userId = userId;

        return this;
    }
    public TestOpportunityTeamBuilder addField(String field, Object value) {
        fields.put(field, value);

        return this;
    }
    public Opportunity_Sales_Team__c build() {
        Opportunity_Sales_Team__c opportunityTeam = new Opportunity_Sales_Team__c();
        opportunityTeam.User__c = userId;
        opportunityTeam.Opportunity__c = opportunityId;

        for (String field: fields.keySet()) {
            Object value = fields.get(field);
            opportunityTeam.put(field, value);
        }
        return opportunityTeam;
    }
    public Opportunity_Sales_Team__c generate() {
        Opportunity_Sales_Team__c opportunityTeam = build();
        Database.insert(opportunityTeam);
        return opportunityTeam;
    }
}