src/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Record Type</label>
</CustomObject>

src/objects/Opportunity_Sales_Team__c/Opportunity_Sales_Team__c.object-meta.xml
<CustomObject>
    <label>Opportunity Team</label>
    <nameField>
        <displayFormat>OT-{0}</displayFormat>
        <label>Opportunity Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Sales_Team__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity_Sales_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Opportunity_Sales_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Sales_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains Email Id of &apos;ATR Opportunity Scheduled Report&apos; recipients</description>
    <label>Users</label>
</CustomObject>

src/classes/UserUpdateHelperBatchTest.cls
@isTest(SeeAllData=true)
private class UserUpdateHelperBatchTest
{

    static testMethod void testMethod1()
    {  
         List<Opportunity> oppList= new List<Opportunity>();
         List<Opportunity_Sales_Team__c > lstTeam = new List<Opportunity_Sales_Team__c >();
         Id informUser = UserInfo.getUserId();
         set<id> userIdSet = new set<id>();
         userIdSet.add(informUser);
                
        
        Opportunity opp = [select id from Opportunity limit 1];
        
        
        Opportunity_Sales_Team__c team = new Opportunity_Sales_Team__c();
        team.Opportunity__c = opp.Id;
        team.User__c = informUser;
        insert lstTeam;
        
              Test.StartTest();
            
            UserUpdateHelperBatch userTeam = new UserUpdateHelperBatch(userIdSet);
            Database.executeBatch(userTeam);
            
            Test.StopTest();
        
     }
     
}